### ISSUE TITLE
TypeError when using None as custom_vjp cotangent for custom pytree and asarray

### ISSUE THREAD

**Issue by eelregit** [google/jax#10238]
```python
import jax.numpy as jnp
from jax.tree_util import register_pytree_node_class

@register_pytree_node_class
class C:
    def __init__(self, a=1.):
        self.a = jnp.asarray(a, dtype=float)  # TypeError: float() argument must be a string or a real number, not 'object'
        # self.a = jnp.asarray(a)  # TypeError: Value '<object object at 0x7fff5220fc20>' with dtype object is not a valid JAX array type. Only arrays of numeric types are supported by JAX.

    def tree_flatten(self):
        return (self.a,), None

    @classmethod
    def tree_unflatten(cls, aux_data, children):
        return cls(*children)

@custom_vjp
def f(x, y):
    return 2. * x  # doesn't depend on y in this simple example


def f_fwd(x, y):
    z = f(x, y)
    res = None
    return z, res

def f_bwd(res, z_cot):
    x_cot = 2. * z_cot
    y_cot = None
    return x_cot, y_cot

f.defvjp(f_fwd, f_bwd)

c = C()
vjp(f, 3., c)[1](3.)  # TypeError with different messages (see above) depending on whether c.a is weakly typed or not
vjp(f, 3., [1., 2])[1](3.)  # this works
```

**Comment by YouJiacheng** [comment]
This because the gradient of c will be `C(None)`.
Option 1 to fix:(suggest)
```python
@register_pytree_node_class
class C:
    def __init__(self, a):
        self.a = a

    def tree_flatten(self):
        return (self.a,), None

    @classmethod
    def tree_unflatten(cls, aux_data, children):
        return cls(*children)
```
Option 2 to fix it:
```python
@register_pytree_node_class
class C:
    def __init__(self, a):
        if a is None:
            self.a = None
            return

        self.a = jnp.asarray(a)

    def tree_flatten(self):
        return (self.a,), None

    @classmethod
    def tree_unflatten(cls, aux_data, children):
        return cls(*children)
```

**Comment by eelregit** [comment]
@YouJiacheng  ``None`` stands for null cotangent from the function decorated by ``custom_vjp``, according to https://jax.readthedocs.io/en/latest/custom_vjp_update.html

**Comment by eelregit** [comment]
Well... Not sure that's the case. The error message says ``object`` not ``NoneType``, also that list example works.

**Comment by eelregit** [comment]
You are right that ``asarray`` is causing this. But I am adding ``asarray`` here to make dtype explicit, and to avoid other problems associated with JAX weak types. For example sometimes I get TypeError due to dtype mismatch, likely from type promotion between weak and non-weak dtypes.

**Comment by YouJiacheng** [comment]
I find where the `object` come from:
Actually it is converted from `None`.
https://github.com/google/jax/blob/a2c2d9af9133df73758ea060a21940fd6a4aa47d/jax/_src/custom_derivatives.py#L600-L633

**Comment by YouJiacheng** [comment]
@eelregit I use following code to investigate the trace of this `object`:
```python
from jax.tree_util import register_pytree_node_class
from jax import vjp, custom_vjp

@register_pytree_node_class
class C:
    def __init__(self, a):
        if type(a) is object:
            raise
        self.a = a

    def tree_flatten(self):
        return (self.a,), None

    @classmethod
    def tree_unflatten(cls, aux_data, children):
        return cls(*children)

@custom_vjp
def f(x, y):
    return 2. * x  # doesn't depend on y in this simple example


def f_fwd(x, y):
    z = f(x, y)
    res = None
    return z, res

def f_bwd(res, z_cot):
    x_cot = 2. * z_cot
    y_cot = None
    return x_cot, y_cot

f.defvjp(f_fwd, f_bwd)

c = C(1.0)
print(vjp(f, 3., c)[1](3.))
```
And find:
```python
Traceback (most recent call last):
  File "/home/jiacheng/fermi-flow/x.py", line 37, in <module>
    print(vjp(f, 3., c)[1](3.))
jax._src.source_info_util.JaxStackTraceBeforeTransformation: RuntimeError: No active exception to reraise

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jiacheng/test/x.py", line 37, in <module>
    print(vjp(f, 3., c)[1](3.))
  File "/home/jiacheng/jax/jax/_src/tree_util.py", line 284, in __call__
    return self.fun(*args, **kw)
  File "/home/jiacheng/jax/jax/_src/api.py", line 2333, in _vjp_pullback_wrapper
    ans = fun(*args)
  File "/home/jiacheng/jax/jax/_src/tree_util.py", line 284, in __call__
    return self.fun(*args, **kw)
  File "/home/jiacheng/jax/jax/interpreters/ad.py", line 126, in unbound_vjp
    arg_cts = backward_pass(jaxpr, reduce_axes, True, consts, dummy_args, cts)
  File "/home/jiacheng/jax/jax/interpreters/ad.py", line 238, in backward_pass
    cts_out = get_primitive_transpose(eqn.primitive)(
  File "/home/jiacheng/jax/jax/interpreters/ad.py", line 737, in _custom_lin_transpose
    cts_in = bwd.call_wrapped(*res, *cts_out)
  File "/home/jiacheng/jax/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/jiacheng/jax/jax/_src/custom_derivatives.py", line 647, in <lambda>
    bwd_ = lu.wrap_init(lambda *args: bwd.call_wrapped(*args))
  File "/home/jiacheng/jax/jax/linear_util.py", line 181, in call_wrapped
    ans = gen.send(ans)
  File "/home/jiacheng/jax/jax/_src/custom_derivatives.py", line 613, in _flatten_bwd
    dummy = tree_unflatten(in_tree, [object()] * in_tree.num_leaves)
  File "/home/jiacheng/jax/jax/_src/tree_util.py", line 72, in tree_unflatten
    return treedef.unflatten(leaves)
  File "/home/jiacheng/test/x.py", line 17, in tree_unflatten
    return cls(*children)
  File "/home/jiacheng/test/x.py", line 9, in __init__
    raise
RuntimeError: No active exception to reraise
```
I think there is a solution now:
convert `object` to `None` (Actually `jnp.asarray(None)` will be `DeviceArray(nan, dtype=float32)`)
```python
import jax.numpy as jnp
from jax.tree_util import register_pytree_node_class
from jax import vjp, custom_vjp

@register_pytree_node_class
class C:
    def __init__(self, a):
        self.a = jnp.asarray(a)

    def tree_flatten(self):
        return (self.a,), None

    @classmethod
    def tree_unflatten(cls, aux_data, children):
        return cls(*(None if type(c) is object else c for c in children))

@custom_vjp
def f(x, y):
    return 2. * x  # doesn't depend on y in this simple example


def f_fwd(x, y):
    z = f(x, y)
    res = None
    return z, res

def f_bwd(res, z_cot):
    x_cot = 2. * z_cot
    y_cot = None
    return x_cot, y_cot

f.defvjp(f_fwd, f_bwd)

c = C(1.0)
print(vjp(f, 3., c)[1](3.)[1].a) # 0.0
```
And it works! (not sure bug-free)

**Comment by YouJiacheng** [comment]
However, I think it is not elegant: Pytree should be pure container(IIUC)
I think you can apply
```python
lambda x: jax.tree_map(jnp.asarray, x)
```
on your function inputs to make dtype explicit.
WDYT?

**Comment by eelregit** [comment]
In the actual code I am debugging I used ``tree_map`` in the ``__post_init__`` of a custom pytree dataclass.

If you meant to ``tree_map`` the argument before instantiating ``C``, that would avoid this problem. But I was hoping the API can be simpler so the user don't need to ``tree_map`` every time before calling ``C()``.

**Comment by YouJiacheng** [comment]
So special check in `tree_unflatten` maybe ok?

**Comment by jakevdp** [comment]
I've marked this as a documentation issue, because I think we could improve discussion surrounding this in the custom pytree doc

**Comment by jakevdp** [comment]
Yes, we should definitely explore those ideas.

**Comment by eelregit** [comment]
Thanks for the explanation. @jakevdp 

I wonder if writing another constructor that skips all validations for pytree unflattening can be a simpler alternative solution in this case?

**Comment by jakevdp** [comment]
> I wonder if writing another constructor that skips all validations for pytree unflattening can be a simpler alternative solution in this case?

That could be a really nice solution
