### ISSUE TITLE
PyTree tree_map of multi-arg function rejects compatible tree types

### ISSUE THREAD

**Issue by awf** [google/jax#10710]
Please:

- [x] Check for duplicate issues.
- [x] Provide a complete example of how to reproduce the bug, wrapped in triple backticks like this:

```python
import jax
import jax.numpy as jnp

@jax.tree_util.register_pytree_node_class
class ParamsDict:
    def __init__(self, **kwargs):
        self.params = {**kwargs}

    def tree_flatten(self):
        return jax.tree_flatten(self.params)

    @classmethod
    def tree_unflatten(cls, aux, values):
        return ParamsDict(**jax.tree_unflatten(aux, values))


print('create e')
e = ParamsDict()
e.params['a'] = jnp.zeros((1,4))

print('e1 = map over e')
e1 = jax.tree_util.tree_map(lambda x: (x,1.1), e) # Now it's a tree of pairs

print('l = map over e, e1')
l = jax.tree_util.tree_map(lambda a,b: 2.2, e, e1)
# ValueError: Mismatch custom node data: PyTreeDef({'a': *}) != PyTreeDef({'a': (*, *)}); value: <__main__.ParamsDict object at 0x7f2d89a14ee0>.
```

It feels as if the above check, in `PyTreeDef::FlattenUpTo`, is overly strict -- there should be no reason to reject the above code?  Replacing `ParamsDict` with `dict` works as hoped:
```python
e = dict()
e['a'] = jnp.zeros((1,4))
e1 = jax.tree_util.tree_map(lambda x: (x,1.1), e)
l = jax.tree_util.tree_map(lambda a,b: 2.2, e, e1)
```

- [x] If applicable, include full error messages/tracebacks.
```
create e
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
e1 = map over e
l = map over e, e1
Traceback (most recent call last):
  File "pytree-custom.py", line 25, in <module>
    l = jax.tree_util.tree_map(lambda a,b: 2.2, e, e1)
  File "/home/awf-wsl/envs/jax/lib/python3.8/site-packages/jax/_src/tree_util.py", line 177, in tree_map
    all_leaves = [leaves] + [treedef.flatten_up_to(r) for r in rest]
  File "/home/awf-wsl/envs/jax/lib/python3.8/site-packages/jax/_src/tree_util.py", line 177, in <listcomp>
    all_leaves = [leaves] + [treedef.flatten_up_to(r) for r in rest]
ValueError: Mismatch custom node data: PyTreeDef({'a': *}) != PyTreeDef({'a': (*, *)}); value: <__main__.ParamsDict object at 0x7f578a5dd7f0>.
```

**Comment by YouJiacheng** [comment]
The problem is caused by the overly strict `tree_unflatten`.
`jax.tree_flatten(self.params)` will produce `aux_data = PyTreeDef({'a': *})` for `e`, and `aux_data = PyTreeDef({'a': (*, *)})` for `e1`.
Thus, `e` and `e1` have different structures, just like `(0, 1)` and `(0, 1, 2)`.
