### ISSUE TITLE
AttributeError: module 'jaxlib.gpu_linalg' has no attribute 'rocm_lu_pivots_to_permutation'

### ISSUE THREAD

**Issue by adam-hartshorne** [google/jax#11118]
Using jax 0.3.13 with jaxlib built from main branch of github (today) on a Windows 10 machine with Cuda 11.2 and python 3.9 I get the following error when importing jax.

```
Traceback (most recent call last):
   import jax
  File "C:\Users\Adam\anaconda3\envs\jax_latest\lib\site-packages\jax\__init__.py", line 120, in <module>
    from jax.experimental.maps import soft_pmap as soft_pmap
  File "C:\Users\Adam\anaconda3\envs\jax_latest\lib\site-packages\jax\experimental\maps.py", line 26, in <module>
    from jax import numpy as jnp
  File "C:\Users\Adam\anaconda3\envs\jax_latest\lib\site-packages\jax\numpy\__init__.py", line 18, in <module>
    from jax.numpy import fft as fft
  File "C:\Users\Adam\anaconda3\envs\jax_latest\lib\site-packages\jax\numpy\fft.py", line 15, in <module>
    from jax._src.numpy.fft import (
  File "C:\Users\Adam\anaconda3\envs\jax_latest\lib\site-packages\jax\_src\numpy\fft.py", line 19, in <module>
    from jax import lax
  File "C:\Users\Adam\anaconda3\envs\jax_latest\lib\site-packages\jax\lax\__init__.py", line 359, in <module>
    from jax.lax import linalg as linalg
  File "C:\Users\Adam\anaconda3\envs\jax_latest\lib\site-packages\jax\lax\linalg.py", line 15, in <module>
    from jax._src.lax.linalg import (
  File "C:\Users\Adam\anaconda3\envs\jax_latest\lib\site-packages\jax\_src\lax\linalg.py", line 984, in <module>
    gpu_linalg.rocm_lu_pivots_to_permutation),
AttributeError: module 'jaxlib.gpu_linalg' has no attribute 'rocm_lu_pivots_to_permutation'

Process finished with exit code 1
```

**Comment by adam-hartshorne** [comment]
Solved by upgrading jax itself to code from main branch.
