### ISSUE TITLE
Error using host_callback primitives inside nested xmap calls

### ISSUE THREAD

**Issue by ludvb** [google/jax#11239]
The `jax.experimental.host_callback` primitives appear to not work inside nested xmaps:
```python
import jax.numpy as jnp
from jax.experimental.maps import xmap
from jax.experimental.host_callback import id_print

inner_xmap = xmap(id_print, in_axes=["a", ...], out_axes=["a", ...])
outer_xmap = xmap(inner_xmap, in_axes=["b", ...], out_axes=["b", ...])

_ = inner_xmap(jnp.zeros((1, 1)))  # OK
_ = outer_xmap(jnp.zeros((1, 1)))  # NotImplementedError: outfeed rewrite xmap
```

Full traceback:
```
Traceback (most recent call last):
  File "/home/ludvig/code/jafx/mre.py", line 7, in <module>
    _ = outer_xmap(jnp.zeros((1, 1)))
  File "/home/ludvig/code/jax/jax/experimental/maps.py", line 625, in fun_mapped
    out_flat = xmap_p.bind(fun_flat, *args_flat, **params)
  File "/home/ludvig/code/jax/jax/experimental/maps.py", line 845, in bind
    return core.map_bind(self, fun, *args, in_axes=in_axes, **params)
  File "/home/ludvig/code/jax/jax/core.py", line 1971, in map_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/home/ludvig/code/jax/jax/experimental/maps.py", line 848, in process
    return trace.process_xmap(self, fun, tracers, params)
  File "/home/ludvig/code/jax/jax/core.py", line 683, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/ludvig/code/jax/jax/experimental/maps.py", line 653, in xmap_impl
    xmap_callable = make_xmap_callable(
  File "/home/ludvig/code/jax/jax/linear_util.py", line 286, in memoized_fun
    ans = call(fun, *args)
  File "/home/ludvig/code/jax/jax/experimental/maps.py", line 725, in make_xmap_callable
    return dispatch.lower_xla_callable(
  File "/home/ludvig/code/jax/jax/_src/profiler.py", line 312, in wrapper
    return func(*args, **kwargs)
  File "/home/ludvig/code/jax/jax/_src/dispatch.py", line 299, in lower_xla_callable
    jaxpr = apply_outfeed_rewriter(jaxpr)
  File "/home/ludvig/code/jax/jax/_src/dispatch.py", line 443, in apply_outfeed_rewriter
    return outfeed_rewriter(jaxpr)
  File "/home/ludvig/code/jax/jax/experimental/host_callback.py", line 1831, in <lambda>
    dispatch.outfeed_rewriter = lambda j: _rewrite_jaxpr(j, False, False)
  File "/home/ludvig/code/jax/jax/experimental/host_callback.py", line 1527, in _rewrite_jaxpr
    _rewrite_eqn(eqn, eqns, last_token_var, output_token_var,
  File "/home/ludvig/code/jax/jax/experimental/host_callback.py", line 1714, in _rewrite_eqn
    raise NotImplementedError(f"outfeed rewrite {eqn.primitive}")
NotImplementedError: outfeed rewrite xmap
```
P.S: Thanks JAX authors for a stellar library, really love it!

**Comment by sharadmv** [comment]
Does `jax.debug.print` work for you here?

**Comment by ludvb** [comment]
The `jax.debug` module indeed solves the problem I was facing. Thank you @sharadmv! I'm closing this since I think `jax.debug` provides a good substitute.
