### ISSUE TITLE
softplus (and maybe others) KeyErrors

### ISSUE THREAD

**Issue by stefanozampini** [google/jax#11241]
This is with jax 0.3.13 

```python
import jax.numpy as jnp
from jax import jacobian
from jax.nn import softplus

x = jnp.array([1.])

mysoftplus = lambda x : jnp.logaddexp(x,0.0)
print(jacobian(mysoftplus)(x))
# this triggers a KeyError
print(jacobian(softplus)(x))
```

```
--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ibex/ai/home/zampins/Devel/ML/examples/bug.py", line 10, in <module>
    print(jacobian(softplus)(x))
  File "/ibex/ai/home/zampins/miniforge/envs/ecrcml-cuda/lib/python3.9/site-packages/jax/_src/api.py", line 1182, in jacfun
    y, pullback = _vjp(f_partial, *dyn_args)
  File "/ibex/ai/home/zampins/miniforge/envs/ecrcml-cuda/lib/python3.9/site-packages/jax/_src/api.py", line 2457, in _vjp
    out_primal, out_vjp = ad.vjp(
  File "/ibex/ai/home/zampins/miniforge/envs/ecrcml-cuda/lib/python3.9/site-packages/jax/interpreters/ad.py", line 130, in vjp
    out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
  File "/ibex/ai/home/zampins/miniforge/envs/ecrcml-cuda/lib/python3.9/site-packages/jax/interpreters/ad.py", line 119, in linearize
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr_nounits(jvpfun_flat, in_pvals)
  File "/ibex/ai/home/zampins/miniforge/envs/ecrcml-cuda/lib/python3.9/site-packages/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/ibex/ai/home/zampins/miniforge/envs/ecrcml-cuda/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 616, in trace_to_jaxpr_nounits
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/ibex/ai/home/zampins/miniforge/envs/ecrcml-cuda/lib/python3.9/site-packages/jax/linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/ibex/ai/home/zampins/miniforge/envs/ecrcml-cuda/lib/python3.9/site-packages/jax/_src/nn/functions.py", line 66, in softplus
    return jnp.logaddexp(x, 0)
  File "/ibex/ai/home/zampins/miniforge/envs/ecrcml-cuda/lib/python3.9/site-packages/jax/_src/numpy/ufuncs.py", line 361, in _logaddexp_jvp
    x1, x2, t1, t2 = _promote_args_inexact("logaddexp_jvp", x1, x2, t1, t2)
  File "/ibex/ai/home/zampins/miniforge/envs/ecrcml-cuda/lib/python3.9/site-packages/jax/_src/numpy/util.py", line 327, in _promote_args_inexact
    return _promote_shapes(fun_name, *_promote_dtypes_inexact(*args))
  File "/ibex/ai/home/zampins/miniforge/envs/ecrcml-cuda/lib/python3.9/site-packages/jax/_src/numpy/util.py", line 262, in _promote_dtypes_inexact
    to_dtype, weak_type = dtypes._lattice_result_type(*args)
KeyError: dtype([('float0', 'V')])
```

**Comment by jakevdp** [comment]
Thanks for the report – I believe this is a consequence of #11221, and has already been fixed in #11230. For now, I'd recommend either installing JAX from the main branch, or downgrading numpy to version 1.22.4.
