### ISSUE TITLE
Cannot build jaxlib on Windows through proxy server

### ISSUE THREAD

**Issue by dmsol98** [google/jax#11304]
**System Info**
- Windows 10
- Python 3.9.12
- Bazel 5.1.1

**Description of the bug:**
I am building JAX from source on Windows but I cannot complete the build due to an SSL certificate issue. My environment variables are set up to work with my proxy, and I've configured various other programs to work with it as well. I need help configuring the build process to work with my proxy.

---

**Error messages:**
When I attempt to build jaxlib with the command `python .\build\build.py`, I get the following output:
```
     _   _  __  __
    | | / \ \ \/ /
 _  | |/ _ \ \  /
| |_| / ___ \/  \
 \___/_/   \/_/\_\


Bazel binary path: C:\ProgramData\chocolatey\bin\bazel.EXE
Bazel version: 5.1.1
Python binary path: C:/Users/dmsol/Anaconda3/python.exe
Python version: 3.9
NumPy version: 1.21.5
MKL-DNN enabled: yes
Target CPU: AMD64
Target CPU features: release
CUDA enabled: no
TPU enabled: no
ROCm enabled: no

Building XLA and installing it in the jaxlib source tree...
C:\ProgramData\chocolatey\bin\bazel.EXE run --verbose_failures=true --config=mkl_open_source_only :build_wheel -- --output_path=C:\Users\dmsol\Documents\ROTE\jax\dist --cpu=AMD64
WARNING: Option 'experimental_strict_action_env' is deprecated: Use --incompatible_strict_action_env instead
INFO: Reading 'startup' options from c:\users\dmsol\documents\rote\jax\.bazelrc: --host_jvm_args=-Djavax.net.ssl.trustStore=C:Program Files (x86)Javajre1.8.0_261libsecuritycacerts, --host_jvm_args=-Djavax.net.ssl.trustStorePassword=changeit
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
INFO: Reading rc options for 'run' from c:\users\dmsol\documents\rote\jax\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  Inherited 'build' options: --python_path=C:/Users/dmsol/Anaconda3/python.exe
INFO: Reading rc options for 'run' from c:\users\dmsol\documents\rote\jax\.bazelrc:
  Inherited 'build' options: --apple_platform_type=macos --macos_minimum_os=10.14 --announce_rc --define open_source_build=true --spawn_strategy=standalone --enable_platform_specific_config --experimental_cc_shared_library --define=no_aws_support=true --define=no_gcp_support=true --define=no_hdfs_support=true --define=no_kafka_support=true --define=no_ignite_support=true --define=grpc_no_ares=true -c opt --config=short_logs --copt=-DMLIR_PYTHON_PACKAGE_PREFIX=jaxlib.mlir. --@org_tensorflow//tensorflow/compiler/xla/python:enable_gpu=false --@org_tensorflow//tensorflow/compiler/xla/python:enable_tpu=false
INFO: Reading rc options for 'run' from c:\users\dmsol\documents\rote\jax\.jax_configure.bazelrc:
  Inherited 'build' options: --strategy=Genrule=standalone --repo_env PYTHON_BIN_PATH=C:/Users/dmsol/Anaconda3/python.exe --action_env=PYENV_ROOT --python_path=C:/Users/dmsol/Anaconda3/python.exe --distinct_host_configuration=false
INFO: Found applicable config definition build:short_logs in file c:\users\dmsol\documents\rote\jax\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:mkl_open_source_only in file c:\users\dmsol\documents\rote\jax\.bazelrc: --define=tensorflow_mkldnn_contraction_kernel=1
INFO: Found applicable config definition build:windows in file c:\users\dmsol\documents\rote\jax\.bazelrc: --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/Zc:preprocessor --cxxopt=/std:c++17 --host_cxxopt=/std:c++17 --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true
INFO: Repository org_tensorflow instantiated at:
  C:/users/dmsol/documents/rote/jax/WORKSPACE:8:13: in <toplevel>
Repository rule http_archive defined at:
  C:/users/dmsol/_bazel_dmsol/hjx2szml/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
WARNING: Download from https://github.com/tensorflow/tensorflow/archive/b6ab86a3f12d1f7dda9c4be801f9920b4ef2ef7a.tar.gz failed: class javax.net.ssl.SSLHandshakeException PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: An error occurred during the fetch of repository 'org_tensorflow':
   Traceback (most recent call last):
        File "C:/users/dmsol/_bazel_dmsol/hjx2szml/external/bazel_tools/tools/build_defs/repo/http.bzl", line 100, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/tensorflow/tensorflow/archive/b6ab86a3f12d1f7dda9c4be801f9920b4ef2ef7a.tar.gz] to C:/users/dmsol/_bazel_dmsol/hjx2szml/external/org_tensorflow/temp13347771389098100590/b6ab86a3f12d1f7dda9c4be801f9920b4ef2ef7a.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: C:/users/dmsol/documents/rote/jax/WORKSPACE:8:13: fetching http_archive rule //external:org_tensorflow: Traceback (most recent call last):
        File "C:/users/dmsol/_bazel_dmsol/hjx2szml/external/bazel_tools/tools/build_defs/repo/http.bzl", line 100, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/tensorflow/tensorflow/archive/b6ab86a3f12d1f7dda9c4be801f9920b4ef2ef7a.tar.gz] to C:/users/dmsol/_bazel_dmsol/hjx2szml/external/org_tensorflow/temp13347771389098100590/b6ab86a3f12d1f7dda9c4be801f9920b4ef2ef7a.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
INFO: Reading rc options for 'run' from c:\users\dmsol\documents\rote\jax\.bazelrc:
  Inherited 'build' options: --apple_platform_type=macos --macos_minimum_os=10.14 --announce_rc --define open_source_build=true --spawn_strategy=standalone --enable_platform_specific_config --experimental_cc_shared_library --define=no_aws_support=true --define=no_gcp_support=true --define=no_hdfs_support=true --define=no_kafka_support=true --define=no_ignite_support=true --define=grpc_no_ares=true -c opt --config=short_logs --copt=-DMLIR_PYTHON_PACKAGE_PREFIX=jaxlib.mlir. --@org_tensorflow//tensorflow/compiler/xla/python:enable_gpu=false --@org_tensorflow//tensorflow/compiler/xla/python:enable_tpu=false
WARNING: Option 'experimental_strict_action_env' is deprecated: Use --incompatible_strict_action_env instead
ERROR: @org_tensorflow//tensorflow/compiler/xla/python:enable_gpu :: Error loading option @org_tensorflow//tensorflow/compiler/xla/python:enable_gpu: no such package '@org_tensorflow//tensorflow': java.io.IOException: Error downloading [https://github.com/tensorflow/tensorflow/archive/b6ab86a3f12d1f7dda9c4be801f9920b4ef2ef7a.tar.gz] to C:/users/dmsol/_bazel_dmsol/hjx2szml/external/org_tensorflow/temp13347771389098100590/b6ab86a3f12d1f7dda9c4be801f9920b4ef2ef7a.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
b''
Traceback (most recent call last):
  File "C:\Users\dmsol\Documents\ROTE\jax\build\build.py", line 528, in <module>
    main()
  File "C:\Users\dmsol\Documents\ROTE\jax\build\build.py", line 523, in main
    shell(command)
  File "C:\Users\dmsol\Documents\ROTE\jax\build\build.py", line 53, in shell
    output = subprocess.check_output(cmd)
  File "C:\Users\dmsol\Anaconda3\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\dmsol\Anaconda3\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\ProgramData\\chocolatey\\bin\\bazel.EXE', 'run', '--verbose_failures=true', '--config=mkl_open_source_only', ':build_wheel', '--', '--output_path=C:\\Users\\dmsol\\Documents\\ROTE\\jax\\dist', '--cpu=AMD64']' returned non-zero exit status 2.
```

---

**How to  reproduce the bug:**
Set up a proxy server / firewall. Follow [these instructions](https://jax.readthedocs.io/en/latest/developer.html#additional-notes-for-building-jaxlib-from-source-on-windows) to build JAX from source on Windows for CPU only. For Bazel, I followed [these](https://bazel.build/install/bazelisk) instructions to install Bazelisk on my device.

After configuring the proxy for pip, MSYS2, git, and my device (using environment variables), I followed the JAX instructions, opened PowerShell as admin, and ran the command:
```
python .\build\build.py
```

---

**Similar issues:**
- [Unable to find valid certification path](https://github.com/tensorflow/tensorflow/issues/54899)
- [Bazel build behind proxy](https://stackoverflow.com/questions/52311486/bazel-build-behind-proxy)
- [Work behind a proxy](https://github.com/bazelbuild/bazel/issues/601)
- [tensorflow building issue on ubuntu 14.04: Accessing remote repository through a proxy](https://github.com/bazelbuild/bazel/issues/587)

**Comment by brunomorampc** [comment]
Same problem here

**Comment by gukejun1** [comment]
Same error, can't find a solution

**Comment by gukejun1** [comment]
> Same error, can't find a solution

Why is it closed?
