### ISSUE TITLE
build fails with gpu

### ISSUE THREAD

**Issue by hanyas** [google/jax#1138]
Having trouble compiling the latest master version. The problem seems related to bazel, Tensorflow and Cuda config. I have cuda 10.1

```     _   _  __  __
    | | / \ \ \/ /
 _  | |/ _ \ \  /
| |_| / ___ \/  \
 \___/_/   \/_/\_\


Downloading bazel from: https://github.com/bazelbuild/bazel/releases/download/0.24.1/bazel-0.24.1-linux-x86_64
bazel-0.24.1-linux-x86_64 [########################################] 100%
Extracting Bazel installation...
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
Starting local Bazel server and connecting to it...
Bazel binary path: ./bazel-0.24.1-linux-x86_64
Python binary path: /home/hany/.miniconda3/envs/hbreps/bin/python
MKL-DNN enabled: yes
-march=native: no
CUDA enabled: yes

Building XLA and installing it in the jaxlib source tree...
ERROR: Skipping ':install_xla_in_source_tree': error loading package 'build': in /home/hany/.cache/bazel/_bazel_hany/c243152a5587b2957239c02eac1e1dc1/external/org_tensorflow/tensorflow/core/platform/default/cuda_build_defs.bzl: Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/hany/.cache/bazel/_bazel_hany/c243152a5587b2957239c02eac1e1dc1/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1266
		_create_local_cuda_repository(repository_ctx)
	File "/home/hany/.cache/bazel/_bazel_hany/c243152a5587b2957239c02eac1e1dc1/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 988, in _create_local_cuda_repository
		_get_cuda_config(repository_ctx)
	File "/home/hany/.cache/bazel/_bazel_hany/c243152a5587b2957239c02eac1e1dc1/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 714, in _get_cuda_config
		find_cuda_config(repository_ctx, ["cuda", "cudnn"])
	File "/home/hany/.cache/bazel/_bazel_hany/c243152a5587b2957239c02eac1e1dc1/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 694, in find_cuda_config
		auto_configure_fail(("Failed to run find_cuda_config...))
	File "/home/hany/.cache/bazel/_bazel_hany/c243152a5587b2957239c02eac1e1dc1/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 325, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Failed to run find_cuda_config.py: Could not find any cuda.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        '/opt/cuda/extras/CUPTI/lib64'
        '/opt/cuda/lib64'
        '/opt/cuda/nvvm/lib64'
        '/usr'
        '/usr/lib'
        '/usr/lib/libfakeroot'
        '/usr/lib/openmpi'
        '/usr/lib32'
        '/usr/lib32/libfakeroot'

WARNING: Target pattern parsing failed.
ERROR: error loading package 'build': in /home/hany/.cache/bazel/_bazel_hany/c243152a5587b2957239c02eac1e1dc1/external/org_tensorflow/tensorflow/core/platform/default/cuda_build_defs.bzl: Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/hany/.cache/bazel/_bazel_hany/c243152a5587b2957239c02eac1e1dc1/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1266
		_create_local_cuda_repository(repository_ctx)
	File "/home/hany/.cache/bazel/_bazel_hany/c243152a5587b2957239c02eac1e1dc1/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 988, in _create_local_cuda_repository
		_get_cuda_config(repository_ctx)
	File "/home/hany/.cache/bazel/_bazel_hany/c243152a5587b2957239c02eac1e1dc1/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 714, in _get_cuda_config
		find_cuda_config(repository_ctx, ["cuda", "cudnn"])
	File "/home/hany/.cache/bazel/_bazel_hany/c243152a5587b2957239c02eac1e1dc1/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 694, in find_cuda_config
		auto_configure_fail(("Failed to run find_cuda_config...))
	File "/home/hany/.cache/bazel/_bazel_hany/c243152a5587b2957239c02eac1e1dc1/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 325, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Failed to run find_cuda_config.py: Could not find any cuda.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        '/opt/cuda/extras/CUPTI/lib64'
        '/opt/cuda/lib64'
        '/opt/cuda/nvvm/lib64'
        '/usr'
        '/usr/lib'
        '/usr/lib/libfakeroot'
        '/usr/lib/openmpi'
        '/usr/lib32'
        '/usr/lib32/libfakeroot'

INFO: Elapsed time: 4.638s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: build
Traceback (most recent call last):
  File "build/build.py", line 334, in <module>
    main()
  File "build/build.py", line 329, in main
    [":install_xla_in_source_tree", os.getcwd()])
  File "build/build.py", line 50, in shell
    output = subprocess.check_output(cmd)
  File "/home/hany/.miniconda3/envs/hbreps/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/home/hany/.miniconda3/envs/hbreps/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./bazel-0.24.1-linux-x86_64', 'run', '--verbose_failures=true', '--config=mkl_open_source_only', '--config=cuda', ':install_xla_in_source_tree', '/home/hany/repos/jax/build']' returned non-zero exit status 1.
```

**Comment by hanyas** [comment]
Sorry should have read the doc more carefully. Cudnn path was missing.

**Comment by surak** [comment]
> Sorry should have read the doc more carefully. Cudnn path was missing.

Where was it missing? How did you configure it?
