### ISSUE TITLE
pretty_printer.py get_ipython() not found in latest colab version

### ISSUE THREAD

**Issue by bsense-rius** [google/jax#11508]
Please:

- [ X] Check for duplicate issues.
- [X ] Provide a complete example of how to reproduce the bug, wrapped in triple backticks like this:

Running a colab notebook ([here](https://github.com/Kazuhito00/YOLOX-Colaboratory-Training-Sample/blob/main/YOLOX_Colaboratory_Training_Sample.ipynb)) based in Megvi's Yolox stopped working since 2 days ago because of an issue with the _can_use_color() from pretty_printer.py. The error is created by the exception of get_ipython().that if we print the traceback inside _can_use_color()  reports get_ipython() not found.  

Please note that for the last several weeks the _can_use_color() did not raise the exception of NameError for get_ipython, working like a charm. Might colab have changed something?

```
def _can_use_color() -> bool:
  try:
    # Check if we're in IPython or Colab
    ipython = get_ipython()  # type: ignore[name-defined]
    shell = ipython.__class__.__name__
    if shell == "ZMQInteractiveShell":
      # Jupyter Notebook
      return True
    elif "colab" in str(ipython.__class__):
      # Google Colab (external or internal)
      return True
  except NameError:
    pass
  # Otherwise check if we're in a terminal
  return sys.stdout.isatty()
```

- [ ] If applicable, include full error messages/tracebacks.

```
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/util.py", line 51, in <module>
    from jax import xla_computation as _xla_computation

  File "/usr/local/lib/python3.7/dist-packages/jax/__init__.py", line 59, in <module>
    from .core import eval_context as ensure_compile_time_eval

  File "/usr/local/lib/python3.7/dist-packages/jax/core.py", line 47, in <module>
    import jax._src.pretty_printer as pp

  File "/usr/local/lib/python3.7/dist-packages/jax/_src/pretty_printer.py", line 61, in <module>
    CAN_USE_COLOR = _can_use_color()
                    └ <function _can_use_color at 0x7f31629d3320>

  File "/usr/local/lib/python3.7/dist-packages/jax/_src/pretty_printer.py", line 59, in _can_use_color
    return sys.stdout.isatty()
           │   └ <yolox.utils.logger.StreamToLoguru object at 0x7f353ea0e390>
           └ <module 'sys' (built-in)>

AttributeError: 'StreamToLoguru' object has no attribute 'isatty'
```

The error of object has no attribute isatty is not important. It is a result of running the return sys.stdout.isatty() due to the exception of

**Comment by jakevdp** [comment]
Thanks for the report – do you have a self-contained reproduction of the issue? I could not reproduce this either in Colab or in a non-ipython runtime. This is what I tried:
```python
# In Colab
from jax._src import pretty_printer
print(pretty_printer._can_use_color())
# True
```
```
# In a non-ipython shell
$ python -c "from jax._src import pretty_printer; print(pretty_printer._can_use_color())"
True
```

**Comment by jakevdp** [comment]
Looking a little deeper, I think the issue is with the definition of `StreamToLoguru` in the YOLOX package; see https://github.com/Megvii-BaseDetection/YOLOX/issues/1437#issuecomment-1185744910

**Comment by bsense-rius** [comment]
This improves jax resilience to logger's patching stdout / stderr. Nice work!

However, the underlying issue I reported was related to the moment that _can_use_color() calls get_ipython(). It seems that the logic to detect whether if it is being called from from Colab / Notebook / Terminal is not totally accurate.

I have slightly modified _can_use_color() in a colab instance to be more verbose, so that when importing it it tells us the shell string and the detail from the NameError exception. 

```
import traceback
from IPython import get_ipython

def _can_use_color() -> bool:
  try:
    # Check if we're in IPython or Colab
    ipython = get_ipython()  # type: ignore[name-defined]
    shell = ipython.__class__.__name__
    print(f"Shell:{shell } - {str(ipython.__class__)}")
    if shell == "ZMQInteractiveShell":
      # Jupyter Notebook
      return True
    elif "colab" in str(ipython.__class__):
      # Google Colab (external or internal)
      return True
  except NameError:
    print(traceback.format_exc())
    pass
  # Otherwise check if we're in a terminal
  return sys.stdout.isatty()
```

When i run a plain test in a colab cell there is no issue at all and perfectly detects we are in a colab instance:
```
#In colab
from jax._src import pretty_printer
print(pretty_printer._can_use_color())

RETURNS:
Shell:Shell - <class 'google.colab._shell.Shell'>
Shell:Shell - <class 'google.colab._shell.Shell'>
True
```

**But when jax is imported in colab for the tensorboard reporting then the Shell is None, therefore running the stdout.isatty() section. Despite the code is actually run from a colab instance.**

So when running the training for the neural network, look, _can_use_color() reports NoneType shell (I have marked it down for easier spotting). The rest of the traceback shows that the issue happens when calling the tensorboard for reporting. 

The funny thing is that 3 days ago the code had been running without issues for several weeks. I checked YOLOX and there was no change in the logger patching (it had been that way for some time)

```
!python tools/train.py \
    -f nano.py \
    -b 16 \
    --fp16 \
    -o \
    -c yolox_nano.pth
...
2022-07-16 06:07:06 | INFO     | pycocotools.coco:88 - index created!

Shell:NoneType - <class 'NoneType'>                        <------- NO SHELL? 


2022-07-16 06:07:07 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (812), thread 'MainThread' (140019826562944):
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401

ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.7/dist-packages/tensorboard/compat/__init__.py)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "tools/train.py", line 141, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=16, cache=False, ckpt='yolox_nano.pth', devices=None, dist_backend='nccl', dist_url=None, exp_file='nano...
          └ ╒═══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "/content/YOLOX/yolox/core/launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒═══════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7f58e5d969e0>

  File "tools/train.py", line 118, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7f586006ccb0>
    └ <yolox.core.trainer.Trainer object at 0x7f5846504dd0>

  File "/content/YOLOX/yolox/core/trainer.py", line 74, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x7f5846500dd0>
    └ <yolox.core.trainer.Trainer object at 0x7f5846504dd0>

  File "/content/YOLOX/yolox/core/trainer.py", line 181, in before_train
    self.tblogger = SummaryWriter(os.path.join(self.file_name, "tensorboard"))
    │               │             │  │    │    │    └ './YOLOX_outputs/nano'
    │               │             │  │    │    └ <yolox.core.trainer.Trainer object at 0x7f5846504dd0>
    │               │             │  │    └ <function join at 0x7f58e5e437a0>
    │               │             │  └ <module 'posixpath' from '/usr/lib/python3.7/posixpath.py'>
    │               │             └ <module 'os' from '/usr/lib/python3.7/os.py'>
    │               └ <class 'torch.utils.tensorboard.writer.SummaryWriter'>
    └ <yolox.core.trainer.Trainer object at 0x7f5846504dd0>

  File "/usr/local/lib/python3.7/dist-packages/torch/utils/tensorboard/writer.py", line 246, in __init__
    self._get_file_writer()
    │    └ <function SummaryWriter._get_file_writer at 0x7f584ac37dd0>
    └ <torch.utils.tensorboard.writer.SummaryWriter object at 0x7f58442e7810>

  File "/usr/local/lib/python3.7/dist-packages/torch/utils/tensorboard/writer.py", line 277, in _get_file_writer
    self.log_dir, self.max_queue, self.flush_secs, self.filename_suffix
    │    │        │    │          │    │           │    └ ''
    │    │        │    │          │    │           └ <torch.utils.tensorboard.writer.SummaryWriter object at 0x7f58442e7810>
    │    │        │    │          │    └ 120
    │    │        │    │          └ <torch.utils.tensorboard.writer.SummaryWriter object at 0x7f58442e7810>
    │    │        │    └ 10
    │    │        └ <torch.utils.tensorboard.writer.SummaryWriter object at 0x7f58442e7810>
    │    └ './YOLOX_outputs/nano/tensorboard'
    └ <torch.utils.tensorboard.writer.SummaryWriter object at 0x7f58442e7810>

  File "/usr/local/lib/python3.7/dist-packages/torch/utils/tensorboard/writer.py", line 76, in __init__
    log_dir, max_queue, flush_secs, filename_suffix
    │        │          │           └ ''
    │        │          └ 120
    │        └ 10
    └ './YOLOX_outputs/nano/tensorboard'

  File "/usr/local/lib/python3.7/dist-packages/tensorboard/summary/writer/event_file_writer.py", line 72, in __init__
    tf.io.gfile.makedirs(logdir)
    │                    └ './YOLOX_outputs/nano/tensorboard'
    └ <module 'tensorboard.compat.tf' via LazyModule (not yet loaded)>

  File "/usr/local/lib/python3.7/dist-packages/tensorboard/lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
                   │         │      └ 'io'
                   │         └ <module 'tensorboard.compat.tf' via LazyModule (not yet loaded)>
                   └ <function lazy_load.<locals>.wrapper.<locals>.load_once at 0x7f5860010050>

  File "/usr/local/lib/python3.7/dist-packages/tensorboard/lazy.py", line 97, in wrapper
    cache[arg] = f(arg)
    │     │      │ └ <module 'tensorboard.compat.tf' via LazyModule (not yet loaded)>
    │     │      └ <function lazy_load.<locals>.wrapper.<locals>.load_once at 0x7f586008bf80>
    │     └ <module 'tensorboard.compat.tf' via LazyModule (not yet loaded)>
    └ {}

  File "/usr/local/lib/python3.7/dist-packages/tensorboard/lazy.py", line 50, in load_once
    module = load_fn()
             └ <function tf at 0x7f586008bc20>

  File "/usr/local/lib/python3.7/dist-packages/tensorboard/compat/__init__.py", line 45, in tf
    import tensorflow

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/__init__.py", line 51, in <module>
    from ._api.v2 import compat

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/compat/__init__.py", line 37, in <module>
    from . import v1

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/compat/v1/__init__.py", line 30, in <module>
    from . import compat

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/compat/v1/compat/__init__.py", line 37, in <module>
    from . import v1

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/compat/v1/compat/v1/__init__.py", line 47, in <module>
    from tensorflow._api.v2.compat.v1 import lite

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/compat/v1/lite/__init__.py", line 9, in <module>
    from . import experimental

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/compat/v1/lite/experimental/__init__.py", line 8, in <module>
    from . import authoring

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/compat/v1/lite/experimental/authoring/__init__.py", line 8, in <module>
    from tensorflow.lite.python.authoring.authoring import compatible

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/authoring/authoring.py", line 43, in <module>
    from tensorflow.lite.python import convert

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/convert.py", line 29, in <module>
    from tensorflow.lite.python import util

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/util.py", line 51, in <module>
    from jax import xla_computation as _xla_computation

  File "/usr/local/lib/python3.7/dist-packages/jax/__init__.py", line 59, in <module>
    from .core import eval_context as ensure_compile_time_eval

  File "/usr/local/lib/python3.7/dist-packages/jax/core.py", line 47, in <module>
    import jax._src.pretty_printer as pp

  File "/usr/local/lib/python3.7/dist-packages/jax/_src/pretty_printer.py", line 61, in <module>
    CAN_USE_COLOR = _can_use_color()
                    └ <function _can_use_color at 0x7f546a54e680>

  File "/usr/local/lib/python3.7/dist-packages/jax/_src/pretty_printer.py", line 59, in _can_use_color
    return sys.stdout.isatty()
           │   └ <yolox.utils.logger.StreamToLoguru object at 0x7f584649bc90>
           └ <module 'sys' (built-in)>

AttributeError: 'StreamToLoguru' object has no attribute 'isatty'
```

**Comment by jakevdp** [comment]
What changed in the past few days is that colab updated the default Jax installation to the latest version.
