### ISSUE TITLE
JAX invokes many child processes

### ISSUE THREAD

**Issue by ayaka14732** [google/jax#11682]
```python
import jax
import time

time.sleep(10)
```

Run `python main.py`

Process tree:

```
python main.py
┕ python main.py
  python main.py
  python main.py
  python main.py
  python main.py
  python main.py
  ...
```

Expected behaviour: No child processes should be invoked

Actual behaviour: JAX invokes many child processes

JAX version: `jax-0.3.15` `jaxlib-0.3.15` `libtpu-nightly-0.1.dev20220722`

**Comment by hawkinsp** [comment]
Can you share how you generated that output?

I suspect what you are seeing is not child *processes* but child *threads*, which is at least somewhat expected. It is normal behavior for JAX to create a thread pool with at least one thread per CPU core on your machine. (Actually, I'm a bit surprised that threads get spawned before backend initialization, but not too surprised.)

Can you say more why this is a problem?

**Comment by ayaka14732** [comment]
> Can you share how you generated that output?

I generated that output using `htop`. `pstree` also yields the same result.

```sh
$ ps aux | grep python
...
ayaka    3497070  788  0.0 5535160 154944 pts/4  Sl+  21:00   0:15 python main.py
$ pstree -p 3497070
python(3497070)─┬─{python}(3497071)
                ├─{python}(3497072)
                ├─{python}(3497073)
                ├─{python}(3497074)
                ├─{python}(3497075)
                ├─{python}(3497076)
                ├─{python}(3497077)
                ├─{python}(3497078)
                ├─{python}(3497079)
                ├─{python}(3497080)
                ├─{python}(3497081)
                ├─{python}(3497082)
                ├─{python}(3497083)
                ├─{python}(3497084)
                ├─{python}(3497085)
                ├─{python}(3497086)
                ├─{python}(3497087)
                ├─{python}(3497088)
                ├─{python}(3497089)
                ├─{python}(3497090)
                ├─{python}(3497091)
                ├─{python}(3497092)
                ├─{python}(3497093)
                ├─{python}(3497094)
                ├─{python}(3497095)
                ├─{python}(3497096)
                ├─{python}(3497097)
                ├─{python}(3497098)
                ├─{python}(3497099)
                ├─{python}(3497100)
                ├─{python}(3497101)
                ├─{python}(3497102)
                ├─{python}(3497103)
                ├─{python}(3497104)
                ├─{python}(3497105)
                ├─{python}(3497106)
                ├─{python}(3497107)
                ├─{python}(3497108)
                ├─{python}(3497109)
                ├─{python}(3497110)
                ├─{python}(3497111)
                ├─{python}(3497112)
                ├─{python}(3497113)
                ├─{python}(3497114)
                ├─{python}(3497115)
                ├─{python}(3497116)
                ├─{python}(3497117)
                ├─{python}(3497118)
                ├─{python}(3497119)
                ├─{python}(3497120)
                ├─{python}(3497121)
                ├─{python}(3497122)
                ├─{python}(3497123)
                ├─{python}(3497124)
                ├─{python}(3497125)
                ├─{python}(3497126)
                ├─{python}(3497127)
                ├─{python}(3497128)
                ├─{python}(3497129)
                ├─{python}(3497130)
                ├─{python}(3497131)
                ├─{python}(3497132)
                ├─{python}(3497133)
                ├─{python}(3497154)
                ├─{python}(3497155)
                ├─{python}(3497158)
                ├─{python}(3497160)
                ├─{python}(3497161)
                ├─{python}(3497162)
                ├─{python}(3497163)
                ├─{python}(3497164)
                ├─{python}(3497165)
                ├─{python}(3497166)
                ├─{python}(3497167)
                ├─{python}(3497168)
                ├─{python}(3497169)
                ├─{python}(3497170)
                ├─{python}(3497171)
                ├─{python}(3497172)
                ├─{python}(3497173)
                ├─{python}(3497174)
                ├─{python}(3497175)
                ├─{python}(3497176)
                ├─{python}(3497177)
                ├─{python}(3497178)
                ├─{python}(3497179)
                ├─{python}(3497180)
                ├─{python}(3497181)
                ├─{python}(3497182)
                ├─{python}(3497183)
                ├─{python}(3497184)
                ├─{python}(3497185)
                ├─{python}(3497186)
                ├─{python}(3497187)
                ├─{python}(3497188)
                ├─{python}(3497189)
                ├─{python}(3497190)
                ├─{python}(3497191)
                ├─{python}(3497192)
                ├─{python}(3497193)
                ├─{python}(3497194)
                ├─{python}(3497195)
                ├─{python}(3497196)
                ├─{python}(3497197)
                ├─{python}(3497198)
                ├─{python}(3497199)
                ├─{python}(3497200)
                ├─{python}(3497201)
                ├─{python}(3497202)
                ├─{python}(3497203)
                ├─{python}(3497204)
                ├─{python}(3497205)
                ├─{python}(3497206)
                ├─{python}(3497207)
                ├─{python}(3497208)
                ├─{python}(3497209)
                ├─{python}(3497210)
                ├─{python}(3497211)
                ├─{python}(3497212)
                ├─{python}(3497214)
                ├─{python}(3497215)
                ├─{python}(3497216)
                ├─{python}(3497217)
                ├─{python}(3497218)
                ├─{python}(3497219)
                └─{python}(3497220)
```

**Comment by hawkinsp** [comment]
Can you say why it's a problem that JAX uses threads internally?

**Comment by ayaka14732** [comment]
@hawkinsp 

> I suspect what you are seeing is not child processes but child threads.

From my understanding, child threads share the same PID with their parent thread (correct me if I am wrong). But the output indicates that the PIDs are different, so I think they are child processes.

Python example:

```python
import os
import threading

def f():
    print('PID of child thread:', os.getpid())

if __name__ == '__main__':
    print('PID of parent thread:', os.getpid())

    threads = []

    for _ in range(8):
        thread = threading.Thread(target=f)
        thread.start()
        threads.append(thread)

    for thread in threads:
        thread.join()
```

Prints:

```
PID of parent thread: 3518802
PID of child thread: 3518802
PID of child thread: 3518802
PID of child thread: 3518802
PID of child thread: 3518802
PID of child thread: 3518802
PID of child thread: 3518802
PID of child thread: 3518802
PID of child thread: 3518802
```

> Can you say why it's a problem that JAX uses threads internally?

This would not be a big problem.

One previous problem for me is that JAX does not work with the multiprocessing "fork" strategy because JAX is internally multithreaded, as you commented in https://github.com/google/jax/issues/1805. But I have already solved it by changing to the `spawn` or `forkserver` strategies.

**Comment by hawkinsp** [comment]
Those are threads, not processes. Try the `-T` option to `pstree`:

```
  -T, --hide-threads  hide threads, show only processes
```

**Comment by hawkinsp** [comment]
And actually, those threads aren't even from JAX!

Using `gdb`:
```
[Switching to thread 124 (Thread 0x7fa0dea93640 (LWP 198584))]
#0  0x00007fa213f0a0fa in __futex_abstimed_wait_common64 (futex_word=futex_word@entry=0x7fa171f9c0e0 <thread_status+7648>, expected=expected@entry=0, clockid=clockid@entry=0,
    abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at ../sysdeps/nptl/futex-internal.c:74
74      ../sysdeps/nptl/futex-internal.c: No such file or directory.
(gdb) bt
#0  0x00007fa213f0a0fa in __futex_abstimed_wait_common64 (futex_word=futex_word@entry=0x7fa171f9c0e0 <thread_status+7648>, expected=expected@entry=0, clockid=clockid@entry=0,
    abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at ../sysdeps/nptl/futex-internal.c:74
#1  0x00007fa213f0a15b in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x7fa171f9c0e0 <thread_status+7648>, expected=expected@entry=0, clockid=clockid@entry=0,
    abstime=abstime@entry=0x0, private=private@entry=0) at ../sysdeps/nptl/futex-internal.c:123
#2  0x00007fa213f03c30 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7fa171f9c090 <thread_status+7568>, cond=0x7fa171f9c0b8 <thread_status+7608>)
    at pthread_cond_wait.c:504
#3  __pthread_cond_wait (cond=0x7fa171f9c0b8 <thread_status+7608>, mutex=0x7fa171f9c090 <thread_status+7568>) at pthread_cond_wait.c:619
#4  0x00007fa1705fec6b in blas_thread_server ()
   from /usr/local/google/home/phawkins/.pyenv/versions/py310/lib/python3.10/site-packages/scipy/linalg/../../scipy.libs/libopenblasp-r0-8b9e111f.3.17.so
#5  0x00007fa213efdd80 in start_thread (arg=0x7fa0dea93640) at pthread_create.c:481
#6  0x00007fa213cc876f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

They come from `scipy` and specifically the OpenBLAS library inside `scipy`, which JAX imports.

Hope that helps!

**Comment by ayaka14732** [comment]
@hawkinsp Thank you for the in-depth analysis!
