### ISSUE TITLE
UNKNOWN bug

### ISSUE THREAD

**Issue by dsm-72** [google/jax#11699]
Please:

- [x ] Check for duplicate issues.
- [x ] Provide a complete example of how to reproduce the bug, wrapped in triple backticks like this:

```bash
# clone jkonet from github
# follow jkonet setup instructions
$ python main.py --out_dir results --config_folder configs --task semicircle
```

- [x ] If applicable, include full error messages/tracebacks.
```
/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/chex/_src/pytypes.py:37: FutureWarning: jax.tree_structure is deprecated, and will be removed in a future release. Use jax.tree_util.tree_structure instead.
  PyTreeDef = type(jax.tree_structure(None))
Started run.
2022-08-01 17:28:07.861579: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_asm_compiler.cc:57] cuLinkAddData fails. This is usually caused by stale driver version.
2022-08-01 17:28:07.861611: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_compiler.cc:1325] The CUDA linking API did not work. Please use XLA_FLAGS=--xla_gpu_force_compilation_parallelism=1 to bypass it, but expect to get longer compilation time due to the lack of multi-threading.
Traceback (most recent call last):
  File "/home/USER/projects/jkonet/main.py", line 292, in <module>
    main(args)
  File "/home/USER/projects/jkonet/main.py", line 266, in main
    run_jko(config, task_dir=task_dir, logging=args.wandb)
  File "/home/USER/projects/jkonet/main.py", line 32, in run_jko
    rng = jax.random.PRNGKey(int(time.time()))
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/random.py", line 125, in PRNGKey
    key = prng.seed_with_impl(impl, seed)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/prng.py", line 233, in seed_with_impl
    return PRNGKeyArray(impl, impl.seed(seed))
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/prng.py", line 272, in threefry_seed
    lax.shift_right_logical(seed_arr, lax_internal._const(seed_arr, 32)))
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/lax/lax.py", line 487, in shift_right_logical
    return shift_right_logical_p.bind(x, y)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/core.py", line 324, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/core.py", line 327, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/core.py", line 684, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/dispatch.py", line 99, in apply_primitive
    compiled_fun = xla_primitive_callable(prim, *unsafe_map(arg_spec, args),
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/util.py", line 220, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/util.py", line 213, in cached
    return f(*args, **kwargs)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/dispatch.py", line 164, in xla_primitive_callable
    compiled = _xla_callable_uncached(lu.wrap_init(prim_fun), device, None,
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/dispatch.py", line 248, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars, False,
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/dispatch.py", line 827, in compile
    self._executable = XlaCompiledComputation.from_xla_computation(
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/dispatch.py", line 934, in from_xla_computation
    compiled = compile_or_get_cached(backend, xla_computation, options,
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/dispatch.py", line 899, in compile_or_get_cached
    return backend_compile(backend, computation, compile_options, host_callbacks)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/profiler.py", line 294, in wrapper
    return func(*args, **kwargs)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/dispatch.py", line 843, in backend_compile
    return backend.compile(built_c, compile_options=options)
jaxlib.xla_extension.XlaRuntimeError: UNKNOWN: no kernel image is available for execution on the device
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_asm_compiler.cc(60): 'status'

```

**Comment by hawkinsp** [comment]
I strongly suspect that this means your NVidia driver is too old for your CUDA/`ptxas` release. Please see the requirements listed here:
https://github.com/google/jax#pip-installation-gpu-cuda
notably the sentence "You must use an NVidia driver version that is at least as new as your [CUDA toolkit's corresponding driver version](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-major-component-versions__table-cuda-toolkit-driver-versions)."

What do `nvidia-smi` and `ptxas --version` show?

Closing since this is very likely an NVidia driver version problem.

**Comment by dsm-72** [comment]
@hawkinsp 

`nvidia-smi` v510.68.02

`nvcc --version` 11.7.64


`ptxas --version` 11.7.64

Sorry if this is basic how do I install the latest drivers on wsl2?

**Comment by hawkinsp** [comment]
I think you just update your Windows NVidia driver.
