### ISSUE TITLE
jax.ops has no attribute index_update

### ISSUE THREAD

**Issue by dsm-72** [google/jax#11706]
Please:

- [x ] Check for duplicate issues.
- [ x] Provide a complete example of how to reproduce the bug, wrapped in triple backticks like this:

```python
# clone jkonet from github
# follow jkonet setup instructions
$ python main.py --out_dir results --config_folder configs --task semicircle
```

- [x ] If applicable, include full error messages/tracebacks.

```
$ python main.py --out_dir results --config_folder configs --task semicircle

/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/chex/_src/pytypes.py:37: FutureWarning: jax.tree_structure is deprecated, and will be removed in a future release. Use jax.tree_util.tree_structure instead.
  PyTreeDef = type(jax.tree_structure(None))
Started run.
/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/optax/_src/transform.py:319: FutureWarning: jax.tree_map is deprecated, and will be removed in a future release. Use jax.tree_util.tree_map instead.
  mu = jax.tree_map(  # First moment
/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/optax/_src/transform.py:321: FutureWarning: jax.tree_map is deprecated, and will be removed in a future release. Use jax.tree_util.tree_map instead.
  nu = jax.tree_map(jnp.zeros_like, params)  # Second moment
  0%|                                                                                                          | 0/1001 [00:00<?, ?it/s]/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/optax/_src/transform.py:82: FutureWarning: jax.tree_multimap is deprecated, and will be removed in a future release. Use jax.tree_util.tree_multimap instead.
  return jax.tree_multimap(
/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/tree_util.py:205: FutureWarning: jax.tree_util.tree_multimap() is deprecated. Please use jax.tree_util.tree_map() instead as a drop-in replacement.
  warnings.warn('jax.tree_util.tree_multimap() is deprecated. Please use jax.tree_util.tree_map() '
/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/optax/_src/transform.py:99: FutureWarning: jax.tree_multimap is deprecated, and will be removed in a future release. Use jax.tree_util.tree_multimap instead.
  return jax.tree_multimap(
/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/optax/_src/transform.py:106: FutureWarning: jax.tree_map is deprecated, and will be removed in a future release. Use jax.tree_util.tree_map instead.
  return jax.tree_map(lambda t: t / bias_correction.astype(t.dtype), moment)
/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/optax/_src/transform.py:331: FutureWarning: jax.tree_multimap is deprecated, and will be removed in a future release. Use jax.tree_util.tree_multimap instead.
  updates = jax.tree_multimap(
/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/optax/_src/transform.py:359: FutureWarning: jax.tree_map is deprecated, and will be removed in a future release. Use jax.tree_util.tree_map instead.
  updates = jax.tree_map(lambda g: step_size * g, updates)
/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/optax/_src/update.py:42: FutureWarning: jax.tree_multimap is deprecated, and will be removed in a future release. Use jax.tree_util.tree_multimap instead.
  return jax.tree_multimap(
/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/optax/_src/linear_algebra.py:29: FutureWarning: jax.tree_leaves is deprecated, and will be removed in a future release. Use jax.tree_util.tree_leaves instead.
  sum([jnp.sum(numerics.abs_sq(x)) for x in jax.tree_leaves(updates)]))
/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/optax/_src/clipping.py:117: FutureWarning: jax.tree_map is deprecated, and will be removed in a future release. Use jax.tree_util.tree_map instead.
  updates = jax.tree_map(
/home/USER/projects/jkonet/jkonet/utils/optim.py:43: FutureWarning: jax.tree_leaves is deprecated, and will be removed in a future release. Use jax.tree_util.tree_leaves instead.
  sum([jnp.sum(jnp.square(x)) for x in jax.tree_leaves(updates)]))
  0%|                                                                                                          | 0/1001 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/USER/projects/jkonet/main.py", line 292, in <module>
    main(args)
  File "/home/USER/projects/jkonet/main.py", line 266, in main
    run_jko(config, task_dir=task_dir, logging=args.wandb)
  File "/home/USER/projects/jkonet/main.py", line 130, in run_jko
    ) = train_step_fn((rng_i, state_energy), batch)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/api.py", line 526, in cache_miss
    out_flat = xla.xla_call(
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/core.py", line 1919, in bind
    return call_bind(self, fun, *args, **params)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/core.py", line 1935, in call_bind
    outs = top_trace.process_call(primitive, fun_, tracers, params)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/core.py", line 687, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/dispatch.py", line 199, in _xla_call_impl
    compiled_fun = xla_callable(fun, device, backend, name, donated_invars,
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/linear_util.py", line 295, in memoized_fun
    ans = call(fun, *args)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/dispatch.py", line 248, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars, False,
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/profiler.py", line 294, in wrapper
    return func(*args, **kwargs)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/dispatch.py", line 293, in lower_xla_callable
    jaxpr, out_type, consts = pe.trace_to_jaxpr_final2(
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/profiler.py", line 294, in wrapper
    return func(*args, **kwargs)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 2167, in trace_to_jaxpr_final2
    jaxpr, out_type, consts = trace_to_subjaxpr_dynamic2(fun, main)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 2117, in trace_to_subjaxpr_dynamic2
    ans = fun.call_wrapped(*in_tracers_)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/USER/projects/jkonet/jkonet/models/model_jko.py", line 153, in step_fn
    loss_energy, loss_psi, grad_norm) = jax.lax.scan(
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/lax/control_flow/loops.py", line 259, in scan
    init_flat, carry_avals, carry_avals_out, init_tree, *rest = _create_jaxpr(init)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/lax/control_flow/loops.py", line 245, in _create_jaxpr
    jaxpr, consts, out_tree = _initial_style_jaxpr(
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/util.py", line 273, in wrapped
    result = call(weak_arg, *args, **kwargs)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/lax/control_flow/common.py", line 57, in _initial_style_jaxpr
    jaxpr, consts, out_tree = _initial_style_open_jaxpr(
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/util.py", line 273, in wrapped
    result = call(weak_arg, *args, **kwargs)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/lax/control_flow/common.py", line 51, in _initial_style_open_jaxpr
    jaxpr, _, consts = pe.trace_to_jaxpr_dynamic(wrapped_fun, in_avals, debug)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/profiler.py", line 294, in wrapper
    return func(*args, **kwargs)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 2074, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 2089, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/USER/projects/jkonet/jkonet/models/model_jko.py", line 144, in _through_time
    batch = jax.lax.cond(
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/lax/control_flow/conditionals.py", line 254, in cond
    return _cond(*args, **kwargs)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/lax/control_flow/conditionals.py", line 218, in _cond
    jaxprs, consts, out_trees = _initial_style_jaxprs_with_common_consts(
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/util.py", line 220, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/util.py", line 213, in cached
    return f(*args, **kwargs)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/lax/control_flow/common.py", line 73, in _initial_style_jaxprs_with_common_consts
    unzip3(_initial_style_open_jaxpr(fun, in_tree, in_avals, primitive_name)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/util.py", line 67, in unzip3
    for x, y, z in xyzs:
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/lax/control_flow/common.py", line 73, in <genexpr>
    unzip3(_initial_style_open_jaxpr(fun, in_tree, in_avals, primitive_name)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/util.py", line 273, in wrapped
    result = call(weak_arg, *args, **kwargs)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/lax/control_flow/common.py", line 51, in _initial_style_open_jaxpr
    jaxpr, _, consts = pe.trace_to_jaxpr_dynamic(wrapped_fun, in_avals, debug)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/profiler.py", line 294, in wrapper
    return func(*args, **kwargs)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 2074, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 2089, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/USER/projects/jkonet/jkonet/models/model_jko.py", line 146, in <lambda>
    lambda x: jax.ops.index_update(x, t + 1, predicted), batch)
jax._src.traceback_util.UnfilteredStackTrace: AttributeError: module 'jax.ops' has no attribute 'index_update'

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/USER/projects/jkonet/main.py", line 292, in <module>
    main(args)
  File "/home/USER/projects/jkonet/main.py", line 266, in main
    run_jko(config, task_dir=task_dir, logging=args.wandb)
  File "/home/USER/projects/jkonet/main.py", line 130, in run_jko
    ) = train_step_fn((rng_i, state_energy), batch)
  File "/home/USER/projects/jkonet/jkonet/models/model_jko.py", line 153, in step_fn
    loss_energy, loss_psi, grad_norm) = jax.lax.scan(
  File "/home/USER/projects/jkonet/jkonet/models/model_jko.py", line 144, in _through_time
    batch = jax.lax.cond(
  File "/home/USER/projects/jkonet/jkonet/models/model_jko.py", line 146, in <lambda>
    lambda x: jax.ops.index_update(x, t + 1, predicted), batch)
AttributeError: module 'jax.ops' has no attribute 'index_update'

```

**Comment by jakevdp** [comment]
Hi - `index_update` and friends were removed in jax version 0.3.2; see the CHANGELOG here: https://jax.readthedocs.io/en/latest/changelog.html#jax-0-3-2-march-16-2022

Instead of `ops.index_update(x, idx, vals)` you should use `x.at[idx].set(vals)`

It looks like the calls to `index_update` are coming through `optax` – I would suggest updating your installation of `optax` to a newer version, as I believe recent releases should use the new APIs.
