### ISSUE TITLE
BUG: jax building from source with rocm support fails in arch linux

### ISSUE THREAD

**Issue by UwUeeb** [google/jax#11868]
### Description

While compiling jax with:
```sh
python3 ./build/build.py --enable_rocm --rocm_path=/opt/rocm --rocm_amdgpu_targets "gfx803" --bazel_options=--jobs=6
```
with rocm and other dependencies installed it starts alright , but after a certain time it returns the following error and the compilation stops:
```
ERROR: /home/user/.cache/bazel/_bazel_user/4a9a3e4cb33c9476739efed2ba436c83/external/org_tensorflow/tensorflow/stream_executor/rocm/BUILD:413:11: Compiling tensorflow/stream_executor/rocm/rocm_helpers.cu.cc failed: undeclared inclusion(s) in rule '@org_tensorflow//tensorflow/stream_executor/rocm:rocm_helpers':
this rule is missing dependency declarations for the following files included by 'tensorflow/stream_executor/rocm/rocm_helpers.cu.cc':
  '/opt/rocm/include/hip/hip_version.h'
  '/opt/rocm/include/hip/hip_runtime.h'
  '/opt/rocm/include/hip/hip_common.h'
  '/opt/rocm/include/hip/amd_detail/amd_hip_runtime.h'
  '/opt/rocm/include/hip/amd_detail/amd_hip_common.h'
  '/opt/rocm/include/hip/hip_runtime_api.h'
  '/opt/rocm/include/hip/amd_detail/host_defines.h'
  '/opt/rocm/include/hip/driver_types.h'
  '/opt/rocm/include/hip/texture_types.h'
  '/opt/rocm/include/hip/channel_descriptor.h'
  '/opt/rocm/include/hip/amd_detail/amd_channel_descriptor.h'
  '/opt/rocm/include/hip/amd_detail/amd_hip_vector_types.h'
  '/opt/rocm/include/hip/surface_types.h'
  '/opt/rocm/include/hip/amd_detail/amd_hip_runtime_pt_api.h'
  '/opt/rocm/include/hip/amd_detail/hip_ldg.h'
  '/opt/rocm/include/hip/amd_detail/amd_hip_atomic.h'
  '/opt/rocm/include/hip/amd_detail/amd_device_functions.h'
  '/opt/rocm/include/hip/amd_detail/math_fwd.h'
  '/opt/rocm/include/hip/hip_vector_types.h'
  '/opt/rocm/include/hip/amd_detail/device_library_decls.h'
  '/opt/rocm/include/hip/amd_detail/llvm_intrinsics.h'
  '/opt/rocm/include/hip/amd_detail/amd_warp_functions.h'
  '/opt/rocm/include/hip/amd_detail/amd_hip_unsafe_atomics.h'
  '/opt/rocm/include/hip/amd_detail/amd_surface_functions.h'
  '/opt/rocm/include/hip/amd_detail/ockl_image.h'
  '/opt/rocm/include/hip/amd_detail/texture_fetch_functions.h'
  '/opt/rocm/include/hip/hip_texture_types.h'
  '/opt/rocm/include/hip/amd_detail/texture_indirect_functions.h'
  '/opt/rocm/include/hip/amd_detail/amd_math_functions.h'
  '/opt/rocm/include/hip/amd_detail/hip_fp16_math_fwd.h'
  '/opt/rocm/include/hip/library_types.h'
clang-14: warning: argument unused during compilation: '-fcuda-flush-denormals-to-zero' [-Wunused-command-line-argument]
Target //build:build_wheel failed to build
INFO: Elapsed time: 170.404s, Critical Path: 25.44s
INFO: 816 processes: 12 internal, 804 local.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully
b''
Traceback (most recent call last):
  File "/home/user/Documents/jax/./build/build.py", line 555, in <module>
    main()
  File "/home/user/Documents/jax/./build/build.py", line 550, in main
    shell(command)
  File "/home/user/Documents/jax/./build/build.py", line 53, in shell
    output = subprocess.check_output(cmd)
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/bazel', 'run', '--verbose_failures=true', ':build_wheel', '--', '--output_path=/home/user/Documents/jax/dist', '--cpu=x86_64']' returned non-zero exit status 1.
```
I am using Rocm-5.2.1 at this moment for compiling the same error can be reproduced with rocm-5.2.0 as well

### What jax/jaxlib version are you using?

jax 0.3.16 / jaxlib 0.3.16

### Which accelerator(s) are you using?

RX580

### Additional System Info

Linux (5.19.0-arch-1)

**Comment by hawkinsp** [comment]
@rsanthanam-amd

**Comment by rsanthanam-amd** [comment]
For future reference, to build jax for ROCm, please use the script: build/rocm/build_rocm.sh

but even with this script, there is an issue that we are currently looking into.

i will update this ticket once the issue has been resolved.

**Comment by UwUeeb** [comment]
ok the build script worked, but the thing is when i do 
```py
>>> import jax
>>> jax.devices()
```
it says
```
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
[CpuDevice(id=0)]
```
any idea why?

**Comment by rsanthanam-amd** [comment]
It could be related to the issue that we currently looking into...

**Comment by UwUeeb** [comment]
Nope it seems this is the issue:
```py
2022-08-13 04:54:06.450256: I external/org_tensorflow/tensorflow/compiler/xla/service/platform_util.cc:145] StreamExecutor ROCM device (0) is of unsupported AMDGPU version : gfx803. The supported AMDGPU versions are gfx1030, gfx900, gfx906, gfx908, gfx90a.
```
can close the issue now if you want

**Comment by rsanthanam-amd** [comment]
@hawkinsp  this can be closed
