### ISSUE TITLE
BUG: Cannot build jaxlib on CentOS

### ISSUE THREAD

**Issue by carlosgmartin** [google/jax#11970]
### Description

I am trying to follow [these instructions](https://jax.readthedocs.io/en/latest/developer.html) to build jaxlib with CUDA support on a Slurm computing cluster. When I run `python3 build/build.py --enable_cuda`, I get the following error:

```
Downloading bazel from: https://github.com/bazelbuild/bazel/releases/download/5.1.1/bazel-5.1.1-linux-x86_64
Traceback (most recent call last):
  File ".../anaconda3/envs/py10/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File ".../anaconda3/envs/py10/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File ".../anaconda3/envs/py10/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File ".../anaconda3/envs/py10/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File ".../anaconda3/envs/py10/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File ".../anaconda3/envs/py10/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File ".../anaconda3/envs/py10/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File ".../anaconda3/envs/py10/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File ".../anaconda3/envs/py10/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File ".../anaconda3/envs/py10/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../jax/build/build.py", line 555, in <module>
    main()
  File ".../jax/build/build.py", line 473, in main
    bazel_path, bazel_version = get_bazel_path(args.bazel_path)
  File ".../jax/build/build.py", line 195, in get_bazel_path
    for path in filter(None, get_bazel_paths(bazel_path_flag)):
  File ".../jax/build/build.py", line 183, in get_bazel_paths
    yield download_and_verify_bazel()
  File ".../jax/build/build.py", line 150, in download_and_verify_bazel
    tmp_path, _ = urlretrieve(uri, None,
  File ".../anaconda3/envs/py10/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File ".../anaconda3/envs/py10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File ".../anaconda3/envs/py10/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File ".../anaconda3/envs/py10/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File ".../anaconda3/envs/py10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File ".../anaconda3/envs/py10/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File ".../anaconda3/envs/py10/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
```

### What jax/jaxlib version are you using?

jaxlib v0.3.15

### Which accelerator(s) are you using?

GPU

### Additional System Info

Python 3.10.4, CentOS 7 (Core)

**Comment by carlosgmartin** [comment]
Possibly related issue: #11304

**Comment by hawkinsp** [comment]
It sounds to me like something is broken with SSL root of trust in your `python` implementation. This isn't really JAX specific: this means that `python` is unable to open an https connection to `github.com`. I suspect you need to fix something about your Python installation or the SSL key store that it is using.

(Or just use a prebuilt `jaxlib`.)

I'm not sure there's any action we can take here.
