### ISSUE TITLE
Vmap of pure_callback with multiple arguments error

### ISSUE THREAD

**Issue by lenarttreven** [google/jax#12596]
### Description

Here is the minimal example of the error:
```
import jax.numpy as jnp
from jax import pure_callback, vmap

dim = 5
num_samples = 3
test_a = jnp.ones(shape=(num_samples, dim))


def _simple_pass(a):
    return a


def simple_pass(a):
    return pure_callback(_simple_pass, a, a, vectorized=False)


out = vmap(simple_pass)(test_a)


def _simple_pass_pair(a, b):
    return a, b


def simple_pass_pair(a, b):
    return pure_callback(_simple_pass_pair, (a, b), a, b, vectorized=False)


out_pair = vmap(simple_pass_pair)(test_a, test_a)
```
While the vmapping in the case when we have one input argument works, in the case when we have **two or more** input arguments we get the following error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/lenarttreven/PycharmProjects/learning_dynamical_systems/experiments/random/pure_callback.py", line 28, in <module>
    out_pair = vmap(simple_pass_pair)(test_a, test_a)
  File "/Users/lenarttreven/PycharmProjects/learning_dynamical_systems/experiments/random/pure_callback.py", line 25, in simple_pass_pair
    return pure_callback(_simple_pass, (a, b), a, b, vectorized=False)
  File "/Users/lenarttreven/python_venv/artemis/lib/python3.10/site-packages/jax/_src/callback.py", line 136, in pure_callback
    out_flat = pure_callback_p.bind(
  File "/Users/lenarttreven/python_venv/artemis/lib/python3.10/site-packages/jax/_src/callback.py", line 95, in pure_callback_batching_rule
    outvals = lax_map(_batch_fun, *batched_args)
TypeError: map() takes 2 positional arguments but 3 were given
``` 

### What jax/jaxlib version are you using?

jax v0.3.20, jaxlib v0.3.20

### Which accelerator(s) are you using?

CPU

### Additional system info

Mac M1

**Comment by jakevdp** [comment]
Thanks for the report – #12607 should fix this
