### ISSUE TITLE
Build error: An error occurred during the fetch of repository 'local_config_cuda'

### ISSUE THREAD

**Issue by adamjstewart** [google/jax#12614]
### Description

I'm trying to build jaxlib but I see the following error during installation:
```console
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "/tmp/spack26d5tykr/c126d21af0d42f631ea076a051f19300/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1401, column 38, in _cuda_autoconf_impl
                _create_local_cuda_repository(repository_ctx)
        File "/tmp/spack26d5tykr/c126d21af0d42f631ea076a051f19300/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1076, column 27, in _create_local_cuda_repository
                cuda_libs = _find_libs(repository_ctx, check_cuda_libs_script, cuda_config)
        File "/tmp/spack26d5tykr/c126d21af0d42f631ea076a051f19300/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 606, column 21, in _find_libs
                _check_cuda_libs(repository_ctx, check_cuda_libs_script, check_cuda_libs_params.values())
        File "/tmp/spack26d5tykr/c126d21af0d42f631ea076a051f19300/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 501, column 28, in _check_cuda_libs
                checked_paths = execute(repository_ctx, [python_bin, "-c", cmd]).stdout.splitlines()
        File "/tmp/spack26d5tykr/c126d21af0d42f631ea076a051f19300/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
Expected even number of arguments
```
Any idea how to fix this? Here is the full build log:

* [build log](https://github.com/google/jax/files/9691171/spack-build-out.txt)

### What jax/jaxlib version are you using?

jaxlib v0.1.74

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.9.13, Linux

### NVIDIA GPU info

This error was found in CI, so I don't have access to run `nvidia-smi`.

@aweits

**Comment by aweits** [comment]
this is probably the fix: https://github.com/tensorflow/tensorflow/commit/a76f797b9cd4b9b15bec4c503b16236a804f676f

**Comment by aweits** [comment]
some more detail for anyone else who runs into this:

- cuda 11.7.1 added whitespace in front of the definitions for versioning in cusolver include files, causing the error you see.
- TF 2.10.0 includes a fix for this: https://github.com/tensorflow/tensorflow/commit/a76f797b9cd4b9b15bec4c503b16236a804f676f
- jax 0.3.14 references a version of tensorflow that includes that commit.
