### ISSUE TITLE
Jaxlib v0.3.22 Build Failure on Windows 10

### ISSUE THREAD

**Issue by adam-hartshorne** [google/jax#12759]
### Description

On windows 10 box with python 3.9, cuda 11.7, cudnn 8.4.0 using the following command

`python .\build\build.py --enable_cuda --cuda_path="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.7" --cudnn_path="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.7" --cuda_compute_capabilities="7.5" --cuda_version="11.7" --cudnn_version="8.4.0" --noenable_rocm --noenable_tp`

fails to build from source with the following error.

```
INFO: Repository llvm-project instantiated at:
  C:/sdks/jax-jaxlib-v0.3.22/WORKSPACE:38:14: in <toplevel>
  C:/users/adam/_bazel_adam/ipwjqsrb/external/org_tensorflow/tensorflow/workspace2.bzl:938:21: in workspace
  C:/users/adam/_bazel_adam/ipwjqsrb/external/org_tensorflow/tensorflow/workspace2.bzl:533:15: in _tf_repositories
  C:/users/adam/_bazel_adam/ipwjqsrb/external/org_tensorflow/third_party/llvm/setup.bzl:22:19: in llvm_setup
Repository rule llvm_configure defined at:
  C:/users/adam/_bazel_adam/ipwjqsrb/external/llvm-raw/utils/bazel/configure.bzl:84:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'llvm-project':
   Traceback (most recent call last):
        File "C:/users/adam/_bazel_adam/ipwjqsrb/external/llvm-raw/utils/bazel/configure.bzl", line 74, column 25, in _llvm_configure_impl
                _overlay_directories(repository_ctx)
        File "C:/users/adam/_bazel_adam/ipwjqsrb/external/llvm-raw/utils/bazel/configure.bzl", line 63, column 13, in _overlay_directories
                fail(("Failed to execute overlay script: '{cmd}'\n" +
Error in fail: Failed to execute overlay script: 'C:/Users/Adam/anaconda3/envs/jax_latest/python.exe C:/users/adam/_bazel_adam/ipwjqsrb/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/adam/_bazel_adam/ipwjqsrb/external/llvm-raw --overlay C:/users/adam/_bazel_adam/ipwjqsrb/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 1
stdout:

stderr:
Traceback (most recent call last):
  File "C:\users\adam\_bazel_adam\ipwjqsrb\external\llvm-raw\utils\bazel\overlay_directories.py", line 92, in <module>
    main(parse_arguments())
  File "C:\users\adam\_bazel_adam\ipwjqsrb\external\llvm-raw\utils\bazel\overlay_directories.py", line 80, in main
    _symlink_abs(os.path.join(args.overlay, relpath),
  File "C:\users\adam\_bazel_adam\ipwjqsrb\external\llvm-raw\utils\bazel\overlay_directories.py", line 64, in _symlink_abs
    os.symlink(os.path.abspath(from_path), os.path.abspath(to_path))
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\users\\adam\\_bazel_adam\\ipwjqsrb\\external\\llvm-raw\\utils\\bazel\\llvm-project-overlay\\.bazelignore' -> 'C:\\users\\adam\\_bazel_adam\\ipwjqsrb\\external\\llvm-project\\.bazelignore'

ERROR: C:/sdks/jax-jaxlib-v0.3.22/WORKSPACE:38:14: fetching llvm_configure rule //external:llvm-project: Traceback (most recent call last):
        File "C:/users/adam/_bazel_adam/ipwjqsrb/external/llvm-raw/utils/bazel/configure.bzl", line 74, column 25, in _llvm_configure_impl
                _overlay_directories(repository_ctx)
        File "C:/users/adam/_bazel_adam/ipwjqsrb/external/llvm-raw/utils/bazel/configure.bzl", line 63, column 13, in _overlay_directories
                fail(("Failed to execute overlay script: '{cmd}'\n" +
Error in fail: Failed to execute overlay script: 'C:/Users/Adam/anaconda3/envs/jax_latest/python.exe C:/users/adam/_bazel_adam/ipwjqsrb/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/adam/_bazel_adam/ipwjqsrb/external/llvm-raw --overlay C:/users/adam/_bazel_adam/ipwjqsrb/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 1
stdout:

stderr:
Traceback (most recent call last):
  File "C:\users\adam\_bazel_adam\ipwjqsrb\external\llvm-raw\utils\bazel\overlay_directories.py", line 92, in <module>
    main(parse_arguments())
  File "C:\users\adam\_bazel_adam\ipwjqsrb\external\llvm-raw\utils\bazel\overlay_directories.py", line 80, in main
    _symlink_abs(os.path.join(args.overlay, relpath),
  File "C:\users\adam\_bazel_adam\ipwjqsrb\external\llvm-raw\utils\bazel\overlay_directories.py", line 64, in _symlink_abs
    os.symlink(os.path.abspath(from_path), os.path.abspath(to_path))
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\users\\adam\\_bazel_adam\\ipwjqsrb\\external\\llvm-raw\\utils\\bazel\\llvm-project-overlay\\.bazelignore' -> 'C:\\users\\adam\\_bazel_adam\\ipwjqsrb\\external\\llvm-project\\.bazelignore'

INFO: Repository stablehlo instantiated at:
  C:/sdks/jax-jaxlib-v0.3.22/WORKSPACE:38:14: in <toplevel>
  C:/users/adam/_bazel_adam/ipwjqsrb/external/org_tensorflow/tensorflow/workspace2.bzl:931:28: in workspace
  C:/users/adam/_bazel_adam/ipwjqsrb/external/org_tensorflow/tensorflow/workspace2.bzl:78:14: in _initialize_third_party
  C:/users/adam/_bazel_adam/ipwjqsrb/external/org_tensorflow/third_party/stablehlo/workspace.bzl:11:20: in repo
  C:/users/adam/_bazel_adam/ipwjqsrb/external/org_tensorflow/third_party/repo.bzl:136:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  C:/users/adam/_bazel_adam/ipwjqsrb/external/org_tensorflow/third_party/repo.bzl:89:35: in <toplevel>
ERROR: C:/sdks/jax-jaxlib-v0.3.22/jaxlib/mlir/_mlir_libs/BUILD.bazel:171:11: //jaxlib/mlir/_mlir_libs:jaxlib_mlir_capi_objects depends on @llvm-project//mlir:CAPISparseTensorObjects in repository @llvm-project which failed to fetch. no such package '@llvm-project//mlir': Failed to execute overlay script: 'C:/Users/Adam/anaconda3/envs/jax_latest/python.exe C:/users/adam/_bazel_adam/ipwjqsrb/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/adam/_bazel_adam/ipwjqsrb/external/llvm-raw --overlay C:/users/adam/_bazel_adam/ipwjqsrb/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 1
stdout:

stderr:
Traceback (most recent call last):
  File "C:\users\adam\_bazel_adam\ipwjqsrb\external\llvm-raw\utils\bazel\overlay_directories.py", line 92, in <module>
    main(parse_arguments())
  File "C:\users\adam\_bazel_adam\ipwjqsrb\external\llvm-raw\utils\bazel\overlay_directories.py", line 80, in main
    _symlink_abs(os.path.join(args.overlay, relpath),
  File "C:\users\adam\_bazel_adam\ipwjqsrb\external\llvm-raw\utils\bazel\overlay_directories.py", line 64, in _symlink_abs
    os.symlink(os.path.abspath(from_path), os.path.abspath(to_path))
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\users\\adam\\_bazel_adam\\ipwjqsrb\\external\\llvm-raw\\utils\\bazel\\llvm-project-overlay\\.bazelignore' -> 'C:\\users\\adam\\_bazel_adam\\ipwjqsrb\\external\\llvm-project\\.bazelignore'

ERROR: C:/sdks/jax-jaxlib-v0.3.22/jaxlib/mlir/_mlir_libs/BUILD.bazel:171:11: //jaxlib/mlir/_mlir_libs:jaxlib_mlir_capi_objects depends on @llvm-project//mlir:CAPITransformsObjects in repository @llvm-project which failed to fetch. no such package '@llvm-project//mlir': Failed to execute overlay script: 'C:/Users/Adam/anaconda3/envs/jax_latest/python.exe C:/users/adam/_bazel_adam/ipwjqsrb/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/adam/_bazel_adam/ipwjqsrb/external/llvm-raw --overlay C:/users/adam/_bazel_adam/ipwjqsrb/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 1
stdout:

stderr:
Traceback (most recent call last):
  File "C:\users\adam\_bazel_adam\ipwjqsrb\external\llvm-raw\utils\bazel\overlay_directories.py", line 92, in <module>
    main(parse_arguments())
  File "C:\users\adam\_bazel_adam\ipwjqsrb\external\llvm-raw\utils\bazel\overlay_directories.py", line 80, in main
    _symlink_abs(os.path.join(args.overlay, relpath),
  File "C:\users\adam\_bazel_adam\ipwjqsrb\external\llvm-raw\utils\bazel\overlay_directories.py", line 64, in _symlink_abs
    os.symlink(os.path.abspath(from_path), os.path.abspath(to_path))
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\users\\adam\\_bazel_adam\\ipwjqsrb\\external\\llvm-raw\\utils\\bazel\\llvm-project-overlay\\.bazelignore' -> 'C:\\users\\adam\\_bazel_adam\\ipwjqsrb\\external\\llvm-project\\.bazelignore'

ERROR: C:/sdks/jax-jaxlib-v0.3.22/jaxlib/mlir/_mlir_libs/BUILD.bazel:171:11: //jaxlib/mlir/_mlir_libs:jaxlib_mlir_capi_objects depends on @llvm-project//mlir:MLIRBindingsPythonCAPIObjects in repository @llvm-project which failed to fetch. no such package '@llvm-project//mlir': Failed to execute overlay script: 'C:/Users/Adam/anaconda3/envs/jax_latest/python.exe C:/users/adam/_bazel_adam/ipwjqsrb/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/adam/_bazel_adam/ipwjqsrb/external/llvm-raw --overlay C:/users/adam/_bazel_adam/ipwjqsrb/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 1
stdout:

stderr:
Traceback (most recent call last):
  File "C:\users\adam\_bazel_adam\ipwjqsrb\external\llvm-raw\utils\bazel\overlay_directories.py", line 92, in <module>
    main(parse_arguments())
  File "C:\users\adam\_bazel_adam\ipwjqsrb\external\llvm-raw\utils\bazel\overlay_directories.py", line 80, in main
    _symlink_abs(os.path.join(args.overlay, relpath),
  File "C:\users\adam\_bazel_adam\ipwjqsrb\external\llvm-raw\utils\bazel\overlay_directories.py", line 64, in _symlink_abs
    os.symlink(os.path.abspath(from_path), os.path.abspath(to_path))
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\users\\adam\\_bazel_adam\\ipwjqsrb\\external\\llvm-raw\\utils\\bazel\\llvm-project-overlay\\.bazelignore' -> 'C:\\users\\adam\\_bazel_adam\\ipwjqsrb\\external\\llvm-project\\.bazelignore'

ERROR: Analysis of target '//build:build_wheel' failed; build aborted:
INFO: Elapsed time: 0.813s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets conf\
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets conf\
igured)
    currently loading: @org_tensorflow//tensorflow/compiler/xla/mlir_hlo
    Fetching @pybind11; fetching
    Fetching @com_google_absl; fetching
    Fetching ...bind11; Extracting C:/users/adam/_bazel_adam/ipwjqsrb/external\
/pybind11/temp17273281197274405934/v2.10.0.tar.gz
    Fetching ...e_absl; Extracting C:/users/adam/_bazel_adam/ipwjqsrb/external\
/com_google_absl/temp2095935738277474412/273292d1cfc0a94a65082ee350509af1d1133\
44d.tar.gz
b''
Traceback (most recent call last):
  File "C:\sdks\jax-jaxlib-v0.3.22\build\build.py", line 567, in <module>
    main()
  File "C:\sdks\jax-jaxlib-v0.3.22\build\build.py", line 562, in main
    shell(command)
  File "C:\sdks\jax-jaxlib-v0.3.22\build\build.py", line 53, in shell
    output = subprocess.check_output(cmd)
  File "C:\Users\Adam\anaconda3\envs\jax_latest\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\Adam\anaconda3\envs\jax_latest\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['.\\bazel-5.1.1-windows-x86_64.exe', 'run', '--verbose_failures=true', ':build_wheel', '--', '--output_path=C:\\sdks\\jax-jaxlib-v0.3.22\\dist', '--cpu=AMD64']' returned non-zero exit status 1.
```

### What jax/jaxlib version are you using?

jaxlib 0.3.22

### Which accelerator(s) are you using?

N/A

### Additional system info

Windows 10, Python 3.9, Cuda 11.7, Cudnn 8.4.0

### NVIDIA GPU info

Nvidia 2070 Max-Q 8GB
NVIDIA-SMI 517.48       
Driver Version: 517.48      
CUDA Version: 11.7

**Comment by hawkinsp** [comment]
The Windows build is community-supported, but I'd guess "A required privilege is not held by the client" means that you don't have privileges to create symbolic links. You'll need to enable that for Bazel builds of JAX to work. (Googling for "enable symbolic links windows" turns up some likely ways to do this, but I don't have a Windows box to hand to try it out.)

Does that work?

**Comment by adam-hartshorne** [comment]
Solved - Admin permissions hadn't been setup properly to allow for this.
