### ISSUE TITLE
WARNING:root:Error importing mlir initializer _mlirRegisterEverything. This may happen in unclean incremental builds but is likely a real bug if encountered otherwise and the MLIR Python API may not function.

### ISSUE THREAD

**Issue by JPGoodale** [google/jax#12829]
### Description

ANY piece of jax code I run returns this same error:

WARNING:root:Error importing mlir initializer _mlirRegisterEverything. This may happen in unclean incremental builds but is likely a real bug if encountered otherwise and the MLIR Python API may not function.
Traceback (most recent call last):
  File "/home/jpgoodale/anaconda3/envs/deeplearning/lib/python3.10/site-packages/jaxlib/mlir/_mlir_libs/__init__.py", line 62, in process_initializer_module
    m = importlib.import_module(f".{module_name}", __name__)
  File "/home/jpgoodale/anaconda3/envs/deeplearning/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: /home/jpgoodale/anaconda3/envs/deeplearning/lib/python3.10/site-packages/jaxlib/mlir/_mlir_libs/_mlirRegisterEverything.so: undefined symbol: mlirRegisterConversionPasses
Traceback (most recent call last):
  File "/home/jpgoodale/anaconda3/envs/deeplearning/testingJAX/main.py", line 1, in <module>
    import jax
  File "/home/jpgoodale/anaconda3/envs/deeplearning/lib/python3.10/site-packages/jax/__init__.py", line 35, in <module>
    from jax import config as _config_module
  File "/home/jpgoodale/anaconda3/envs/deeplearning/lib/python3.10/site-packages/jax/config.py", line 17, in <module>
    from jax._src.config import config
  File "/home/jpgoodale/anaconda3/envs/deeplearning/lib/python3.10/site-packages/jax/_src/config.py", line 29, in <module>
    from jax._src import lib
  File "/home/jpgoodale/anaconda3/envs/deeplearning/lib/python3.10/site-packages/jax/_src/lib/__init__.py", line 101, in <module>
    import jaxlib.lapack as lapack
  File "/home/jpgoodale/anaconda3/envs/deeplearning/lib/python3.10/site-packages/jaxlib/lapack.py", line 18, in <module>
    import jaxlib.mlir.ir as ir
  File "/home/jpgoodale/anaconda3/envs/deeplearning/lib/python3.10/site-packages/jaxlib/mlir/ir.py", line 5, in <module>
    from ._mlir_libs._mlir.ir import *
  File "/home/jpgoodale/anaconda3/envs/deeplearning/lib/python3.10/site-packages/jaxlib/mlir/_mlir_libs/__init__.py", line 106, in <module>
    _site_initialize()
  File "/home/jpgoodale/anaconda3/envs/deeplearning/lib/python3.10/site-packages/jaxlib/mlir/_mlir_libs/__init__.py", line 83, in _site_initialize
    process_initializer_module("_mlirRegisterEverything")
  File "/home/jpgoodale/anaconda3/envs/deeplearning/lib/python3.10/site-packages/jaxlib/mlir/_mlir_libs/__init__.py", line 72, in process_initializer_module
    if hasattr(m, "register_dialects"):
UnboundLocalError: local variable 'm' referenced before assignment

### What jax/jaxlib version are you using?

jax 0.3.16 and jaxlib 0.3.15+cuda11.cudnn82

### Which accelerator(s) are you using?

GPU and CPU

### Additional system info

WSL

### NVIDIA GPU info

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.57       Driver Version: 516.59       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| N/A   54C    P8     6W /  N/A |      0MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A        27      G   /Xwayland                       N/A      |
+-----------------------------------------------------------------------------+

**Comment by froystig** [comment]
This is likely due to the rather old jaxlib version (0.3.15). That's technically the current minimum supported jaxlib version according to [`version.py`](https://github.com/google/jax/blob/7a99e5194aece5b9129524b68291c08f14965299/jax/version.py), but we may have meant to raise that number by now. cc @yashk2810 @hawkinsp 

Try upgrading your jaxlib, preferably to the latest version?

**Comment by hawkinsp** [comment]
I'm actually guessing that you have a mixture of `jaxlib` installations somehow. Can you try completely removing your jaxlib installation (`pip uninstall jaxlib`) and removing the `jaxlib` directory where it was installed (use `pip show jaxlib` to show the parent directory) and then reinstalling it?

**Comment by JPGoodale** [comment]
Ok so when I run `pip show jaxlib` it returns this:
`Name: jaxlib
Version: 0.3.22
Summary: XLA library for JAX
Home-page: https://github.com/google/jax
Author: JAX team
Author-email: jax-dev@google.com
License: Apache-2.0
Location: /home/jpgoodale/anaconda3/envs/deeplearning/lib/python3.10/site-packages
Requires: absl-py, numpy, scipy
Required-by: chex, numpyro, optax`
which seems to be the right version, however when I run `conda list` it shows up as: 
`jaxlib -0.3.15+cuda11.cudnn82`
and in my files I notice that there's a `jaxlib 0.3.15+cuda11.cudnn82.dist-info` folder as well as a `jaxlib-0.3.22.dist-info ` one. Is this an issue with using pip in a conda env? When I run `conda uninstall jaxlib-0.3.15` it returns:
`Collecting package metadata (repodata.json): done
Solving environment: failed_openblas
  libgfortran-ng-12.1.0-h69a702a_17
PackagesNotFoundError: The following packages are missing from the target environment:
  - jaxlib-0.3.15-16_linux64_openblas
  libopenblas-0.3.21-pthreads_h78a6416_3
  libprotobuf-3.21.7-h6239696_0`
Very sorry for all the confusion... All your help so far is greatly appreciated!

**Comment by hawkinsp** [comment]
Yeah I suspect you have a mess of different jaxlib versions in your environment. Can you start over with a fresh conda environment? (Note also that there are community-supported conda-forge packages for JAX that you may prefer, see the github readme for details. The PIP packages should work also, though.)

**Comment by hawkinsp** [comment]
Closing because I suspect this is a bad installation not a problem with jaxlib.
