### ISSUE TITLE
Could not find cublas.h

### ISSUE THREAD

**Issue by dhpollack** [google/jax#1305]
I'm using the install of CUDA 10.1 with Arch Linux and got the following error.  The problem seems to be that although I specified a path of `/opt/cuda` the script seems to be looking for the includes in `/opt/cuda/lib64`

```
$ python build.py --enable_march_native --enable_mkl_dnn --enable_cuda --cuda_path /opt/cuda
...
Bazel binary path: ./bazel-0.24.1-linux-x86_64
Python binary path: ~/miniconda3/envs/pytorch_dev/bin/python
MKL-DNN enabled: yes
-march=native: yes
CUDA enabled: yes
CUDA toolkit path: /opt/cuda
CUDNN library path: /opt/cuda

Building XLA and installing it in the jaxlib source tree...
ERROR: Skipping ':install_xla_in_source_tree': error loading package 'build': in ~/.cache/bazel/_bazel_david/9d74510baba13ae20478b5800bcfdf90/external/org_tensorflow/tensorflow/core/platform/default/cuda_build_defs.bzl: Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "~/.cache/bazel/_bazel_david/9d74510baba13ae20478b5800bcfdf90/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1266
		_create_local_cuda_repository(repository_ctx)
	File "~/.cache/bazel/_bazel_david/9d74510baba13ae20478b5800bcfdf90/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 988, in _create_local_cuda_repository
		_get_cuda_config(repository_ctx)
	File "~/.cache/bazel/_bazel_david/9d74510baba13ae20478b5800bcfdf90/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 714, in _get_cuda_config
		find_cuda_config(repository_ctx, ["cuda", "cudnn"])
	File "~/.cache/bazel/_bazel_david/9d74510baba13ae20478b5800bcfdf90/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 694, in find_cuda_config
		auto_configure_fail(("Failed to run find_cuda_config...))
	File "~/.cache/bazel/_bazel_david/9d74510baba13ae20478b5800bcfdf90/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 325, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Failed to run find_cuda_config.py: Could not find any cublas_api.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        '/opt/cuda/extras/CUPTI/lib64'
        '/opt/cuda/lib64'
        '/opt/cuda/nvvm/lib64'
        '/usr'
        '/usr/lib'
        '/usr/lib/intel'
        '/usr/lib/libfakeroot'
        '/usr/lib/openmpi'
```

As a work around I created a symlink from `/usr/include/cuda` to `/opt/cuda/include` but that's not an ideal solution.

**Comment by KeAWang** [comment]
Same issue for me

**Comment by skye** [comment]
Can you try setting the `TF_CUDA_PATHS` environment variable? See https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/find_cuda_config.py#L26, which is the script that tries to find your cuda install. We may need some extra plumbing to pass the env var through bazel though, please report back if just setting the env var doesn't work.

**Comment by KeAWang** [comment]
Strange, I restarted my computer and it worked without needing TF_CUDA_PATHS...

**Comment by hawkinsp** [comment]
Seems like this issue may be moot now, especially given the last comment. Closing; feel free to reopen if you are still having problems!

**Comment by bitterengsci** [comment]
> TF_CUDA_PATHS



> Can you try setting the `TF_CUDA_PATHS` environment variable? See https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/find_cuda_config.py#L26, which is the script that tries to find your cuda install. We may need some extra plumbing to pass the env var through bazel though, please report back if just setting the env var doesn't work.

worked for me!~\(≧▽≦)/~
