### ISSUE TITLE
Jaxlib release v0.3.24 XlaRuntimeError

### ISSUE THREAD

**Issue by camenduru** [google/jax#13130]
### Description

same code working with
```
Name: jax
Version: 0.3.23
Summary: Differentiate, compile, and transform Numpy code.
Home-page: https://github.com/google/jax
Author: JAX team
Author-email: jax-dev@google.com
License: Apache-2.0
Location: /home/camenduru/.local/lib/python3.8/site-packages
Requires: absl-py, numpy, opt-einsum, scipy, typing-extensions, etils
Required-by: flax, chex, optax
```
not working with v0.3.24 😭

```
train_dreambooth_flax.py", line 666, in <module>
    main()
  File "train_dreambooth_flax.py", line 617, in main
    unet_state, text_encoder_state, train_metric, train_rngs = p_train_step(
  File "/home/camenduru/.local/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/camenduru/.local/lib/python3.8/site-packages/jax/_src/api.py", line 2249, in cache_miss
    out = map_bind_continuation(execute(*tracers))
  File "/home/camenduru/.local/lib/python3.8/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/home/camenduru/.local/lib/python3.8/site-packages/jax/interpreters/pxla.py", line 2066, in __call__
    input_bufs = self.in_handler(args)
  File "/home/camenduru/.local/lib/python3.8/site-packages/jax/interpreters/pxla.py", line 1827, in __call__
    return self.handler(input_buffers)
  File "/home/camenduru/.local/lib/python3.8/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/home/camenduru/.local/lib/python3.8/site-packages/jax/interpreters/pxla.py", line 422, in shard_args
    return [_shard_arg(arg, devices, indices[i], mode) for i, arg in enumerate(args)]
  File "/home/camenduru/.local/lib/python3.8/site-packages/jax/interpreters/pxla.py", line 422, in <listcomp>
    return [_shard_arg(arg, devices, indices[i], mode) for i, arg in enumerate(args)]
  File "/home/camenduru/.local/lib/python3.8/site-packages/jax/interpreters/pxla.py", line 394, in _shard_arg
    return [
  File "/home/camenduru/.local/lib/python3.8/site-packages/jax/interpreters/pxla.py", line 395, in <listcomp>
    buf if buf.device() == d else buf.copy_to_device(d)
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Failed to allocate request for 56.25MiB (58982400B) on device ordinal 4

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train_dreambooth_flax.py", line 666, in <module>
    main()
  File "train_dreambooth_flax.py", line 617, in main
    unet_state, text_encoder_state, train_metric, train_rngs = p_train_step(
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Failed to allocate request for 56.25MiB (58982400B) on device ordinal 4
```

### What jax/jaxlib version are you using?

v0.3.24

### Which accelerator(s) are you using?

TPU v3-8

**Comment by camenduru** [comment]
I am using this: https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth_flax.py

**Comment by hawkinsp** [comment]
Well, it sounds like you are running out of memory.

It's not surprising that there might be small variations in memory use between JAX releases: if a model only just fits any small change might push it over the edge. Can you try lowering, e.g., the batch size and see if it fits once more?

**Comment by camenduru** [comment]
😮 this is not a bug v0.3.24 just using more memory, thanks @hawkinsp ❤

**Comment by Lime-Cakes** [comment]
> open_mouth this is not a bug v0.3.24 just using more memory, thanks @hawkinsp heart

Just wanted to check, what resolution are you training with? (image resolution/latent resolution) The default 512x512 (64x64)?

**Comment by camenduru** [comment]
hi @Lime-Cakes 👋 --resolution=512

```
python3 train_dreambooth_flax.py \
  --pretrained_model_name_or_path="/home/camenduru/stable-diffusion-v1-5"  \
  --instance_data_dir="instance-images" \
  --output_dir="450-1e6" \
  --instance_prompt="instance_prompt" \
  --resolution=512 \
  --train_batch_size=1 \
  --learning_rate=1e-6 \
  --max_train_steps=450 \
  --report_to="wandb" \
  --push_to_hub \
  --hub_token="token"
```
