### ISSUE TITLE
in_axes of vmap and pmap working differently

### ISSUE THREAD

**Issue by Kamuish** [google/jax#13214]
### Description

Following the docs, I would expect to use pmap as a drop-in replacement for vmap. However this is not the case as pmap raises an exception related to PyTrees (minimal working example + traceback below)

You can find here a small working example that can reproduce the issue:

``` python
import jax 
import jax.numpy as jnp 

def foo(a,b, c, d):
    return b 

in_axis_specification = [None, 0, None, 0]

vmap_test = jax.vmap(foo, in_axes=in_axis_specification)
pmap_test = jax.pmap(foo, in_axes=in_axis_specification)

d = jnp.zeros((2, 100000))

c = jnp.asarray([4, 5])
b = jnp.asarray([4, 5])
a = jnp.asarray([4, 5])

for name, func in [("vmap", vmap_test), ("pmap", pmap_test)]:
    print(f"Testing {name}:")
    try:
        func(a, b, c, d)
    except Exception as e:
        print("\tFailed: ", e)
```

And here the traceback
``` python
Traceback (most recent call last):
  File "/home/amiguel/work/HOMER/scripts/toy_test.py", line 20, in <module>
    print(pmap_test(a, b, c, d, e, f))
  File "/home/amiguel/.conda/envs/HOMERenv/lib/python3.10/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/amiguel/.conda/envs/HOMERenv/lib/python3.10/site-packages/jax/_src/api.py", line 2226, in cache_miss
    p = _prepare_pmap(fun, in_axes, out_axes, static_broadcasted_tuple,
  File "/home/amiguel/.conda/envs/HOMERenv/lib/python3.10/site-packages/jax/_src/api.py", line 2049, in _prepare_pmap
    in_axes_flat = tuple(flatten_axes("pmap in_axes", in_tree, (dyn_in_axes, 0)))
  File "/home/amiguel/.conda/envs/HOMERenv/lib/python3.10/site-packages/jax/_src/api_util.py", line 418, in flatten_axes
    raise ValueError(f"{name} specification must be a tree prefix of the "
jax._src.traceback_util.UnfilteredStackTrace: ValueError: pmap in_axes specification must be a tree prefix of the corresponding value, got specification ([None, 0, 0, 0, None, 0], 0) for value tree PyTreeDef(((*, *, *, *, *, *), {})).
```

### What jax/jaxlib version are you using?

jax v0.3.24

### Which accelerator(s) are you using?

CPU

### Additional system info

reproduced in Python 3.8.12 and 3.10.6

**Comment by JiaYaobo** [comment]
try to replace `[None, 0, None, 0]` to tuple `(None, 0, None, 0)`?

**Comment by Kamuish** [comment]
@JiaYaobo that works on the two implementations (thanks for the tip :) ). That said, I will not close the issue as the problem still exists (and the docs don't make any mention for the need of passing a tuple, instead of a list)

**Comment by selamw1** [comment]
Hi @Kamuish 
I executed the mentioned code with the latest version of JAX(0.4.23). Now the error message indicates that a tuple is required instead of a list. Could you please verify this behavior with JAX 0.4.23 and confirm closure of this issue once resolved?

```Python
import jax 
import jax.numpy as jnp 

def foo(a,b, c, d):
    return b 

in_axis_specification = [None, 0, None, 0] # will raise an error: `in_axes` argument to `pmap` must be a tree prefix of that tuple.
# in_axis_specification = (None, 0, None, 0) # correct: tuple will be passed to passed positionally to the pmapped function.

vmap_test = jax.vmap(foo, in_axes=in_axis_specification)
pmap_test = jax.pmap(foo, in_axes=in_axis_specification)

d = jnp.zeros((2, 100000))

c = jnp.asarray([4, 5])
b = jnp.asarray([4, 5])
a = jnp.asarray([4, 5])

for name, func in [("vmap", vmap_test), ("pmap", pmap_test)]:
    print(f"Testing {name}:")
    try:
        func(a, b, c, d)
    except Exception as e:
        print("\tFailed: ", e)
```
Output:
```
Testing vmap:
Array([4, 5], dtype=int32)
Testing pmap:
        Failed:  pytree structure error: different types at key path
    pmap in_axes[0]
At that key path, the prefix pytree pmap in_axes has a subtree of type
    <class 'list'>
but at the same key path the full pytree has a subtree of different type
    <class 'tuple'>.

The 'full pytree' here is the tuple of arguments passed positionally to the pmapped function, and the value of `in_axes` must be a tree prefix of that tuple. But it was not a prefix.

Check that the value of the `in_axes` argument to `pmap` is a tree prefix of the tuple of arguments passed positionally to the pmapped function.
```

**Comment by Kamuish** [comment]
Hi @selamw1, I confirm that I find the same behaviour. Thanks for the heads up!
