### ISSUE TITLE
JAX/XLA compiling for one device and running on another

### ISSUE THREAD

**Issue by jlebar** [google/jax#1325]
```
$ python3 api_test.py
```

hits the following fatal error on my machine

```
[ RUN      ] APITest.test_issue_1062
2019-09-08 06:14:25.836744: E external/org_tensorflow/tensorflow/compiler/xla/python/local_client.cc:731] Execution of replica 1 failed: Invalid argument: executable is built for device CUDA:0 of type "TITAN V"; cannot run it on device CUDA:1 of type "Quadro K2200"
2019-09-08 06:14:30.809031: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nccl_all_reduce_thunk.cc:122] This thread has been waiting for 5000ms for and may be stuck: participant for device ordinal 0, stream 0x270b1b0 waiting for all participants to be arrive at rendezvous RendezvousKey{run_id=RunId: 1796, participating_replicas=[0,1], all_reduce_kind=1, op_id=141}
2019-09-08 06:14:35.837040: F external/org_tensorflow/tensorflow/compiler/xla/python/local_client.cc:839] Replicated computation launch failed, but not all replicas terminated. Aborting process to work around deadlock. Failure message (there may have been multiple failures, see the error log for all failures): 

executable is built for device CUDA:0 of type "TITAN V"; cannot run it on device CUDA:1 of type "Quadro K2200"
Fatal Python error: Aborted
```

Thankfully this is pretty clear about what's going on; it says we compiled for one device but ran on another.  It is also saying we're doing an all-reduce, which is fishy, as XLA does not allow you to target two different GPU models with one XLA computation.  It's possible you're doing this all-reduce between two different XLA computations, but my bet is you're not, in which case...boom.

CUDA_VISIBLE_DEVICES=0 fixes this problem for me.

The test failure isn't that important, but I hit the same problem, this time without a helpful error message, when trying to use trax:

```
python3 -m tensor2tensor.trax.trainer --data_dir=$TMPDIR/trax --dataset=mnist   --model=MLP   --config="train.train_steps=1000"
```

this prints a bunch of

```
2019-09-07 21:38:09.628423: E external/org_tensorflow/tensorflow/stream_executor/stream.cc:332] Error recording event in stream: error recording CUDA event on stream 0x5777730: 
```

and then eventually fails with

```
failed to load in-memory CUBIN: CUDA_ERROR_INVALID_SOURCE: device kernel image is invalid
```

full log https://gist.github.com/jlebar/fcb502278cc03019238e677dc6c25896.  Again setting CUDA_VISIBLE_DEVICES=0 works around the problem.

I think this is a bug in JAX that it's compiling for one device and then running the computation on another device.  But I'd say it's also a bug somewhere in XLA for not detecting this and printing a nice error in the trax case the way it did in the unit test case.

**Comment by mktal** [comment]
I had the same issue when running trax and jax on gpu.  Setting either CUDA_VISIBLE_DEVICES=0 or CUDA_VISIBLE_DEVICES=1 fixes the problem. But not CUDA_VISIBLE_DEVICES=0,1. My two gpu devices are of the same type so the error in this case does not seem to be originated from targeting two different gpu models with one xla computation as mentioned above. Any thoughts on what is the  cause of the problem then?

**Comment by skye** [comment]
@mktal can you share the exact error you're getting, and also the code that's producing it? That's odd you'd see this with two identical GPUs.

**Comment by mktal** [comment]
> @mktal can you share the exact error you're getting, and also the code that's producing it? That's odd you'd see this with two identical GPUs.

The following error was produced using the master branch. 

```
$ python trax/trainer.py --config_file=./trax/configs/mlp_mnist.gin

I0130 05:57:38.439771 140589291689728 trainer_lib.py:752] No --output_dir specified
No --output_dir specified
I0130 05:57:38.440040 140589291689728 trainer_lib.py:752] Using default output_dir: /nfs/private/trax/MLP_mnist_20200130_0557
Using default output_dir: /nfs/private/trax/MLP_mnist_20200130_0557
I0130 05:57:39.167536 140589291689728 inputs.py:141] No dataset directory provided. Downloading and generating dataset for mnist inside data directory /nfs/private/tensorflow_datasets/ For large datasets it is better to prepare datasets manually!
I0130 05:57:39.211611 140589291689728 dataset_builder.py:193] Overwrite dataset info from restored data version.
I0130 05:57:39.219218 140589291689728 dataset_builder.py:273] Reusing dataset mnist (/nfs/private/tensorflow_datasets/mnist/1.0.0)
I0130 05:57:39.233974 140589291689728 dataset_builder.py:193] Overwrite dataset info from restored data version.
I0130 05:57:39.251142 140589291689728 dataset_builder.py:193] Overwrite dataset info from restored data version.
I0130 05:57:39.253719 140589291689728 dataset_builder.py:273] Reusing dataset mnist (/nfs/private/tensorflow_datasets/mnist/1.0.0)
I0130 05:57:39.253939 140589291689728 dataset_builder.py:434] Constructing tf.data.Dataset for split train, from /nfs/private/tensorflow_datasets/mnist/1.0.0
I0130 05:57:39.521964 140589291689728 dataset_builder.py:193] Overwrite dataset info from restored data version.
I0130 05:57:39.526323 140589291689728 dataset_builder.py:273] Reusing dataset mnist (/nfs/private/tensorflow_datasets/mnist/1.0.0)
I0130 05:57:39.526546 140589291689728 dataset_builder.py:434] Constructing tf.data.Dataset for split test, from /nfs/private/tensorflow_datasets/mnist/1.0.0
I0130 05:57:39.994026 140589291689728 inputs.py:443] Heuristically setting bucketing to False based on shapes of target tensors.
I0130 05:57:40.006169 140589291689728 inputs.py:443] Heuristically setting bucketing to False based on shapes of target tensors.
I0130 05:57:40.013097 140589291689728 inputs.py:443] Heuristically setting bucketing to False based on shapes of target tensors.
2020-01-30 05:57:44.782346: E external/org_tensorflow/tensorflow/stream_executor/stream.cc:332] Error recording event in stream: Error recording CUDA event: CUDA_ERROR_INVALID_HANDLE: invalid resource handle; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
2020-01-30 05:57:44.782757: E external/org_tensorflow/tensorflow/stream_executor/stream.cc:332] Error recording event in stream: Error recording CUDA event: CUDA_ERROR_INVALID_HANDLE: invalid resource handle; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
2020-01-30 05:57:44.783067: E external/org_tensorflow/tensorflow/stream_executor/stream.cc:332] Error recording event in stream: Error recording CUDA event: CUDA_ERROR_INVALID_HANDLE: invalid resource handle; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
2020-01-30 05:57:44.783398: E external/org_tensorflow/tensorflow/stream_executor/stream.cc:332] Error recording event in stream: Error recording CUDA event: CUDA_ERROR_INVALID_HANDLE: invalid resource handle; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
2020-01-30 05:57:44.783678: E external/org_tensorflow/tensorflow/stream_executor/stream.cc:332] Error recording event in stream: Error recording CUDA event: CUDA_ERROR_INVALID_HANDLE: invalid resource handle; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
2020-01-30 05:57:44.783957: E external/org_tensorflow/tensorflow/stream_executor/stream.cc:332] Error recording event in stream: Error recording CUDA event: CUDA_ERROR_INVALID_HANDLE: invalid resource handle; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
2020-01-30 05:57:44.784232: E external/org_tensorflow/tensorflow/stream_executor/stream.cc:332] Error recording event in stream: Error recording CUDA event: CUDA_ERROR_INVALID_HANDLE: invalid resource handle; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
2020-01-30 05:57:44.954529: E external/org_tensorflow/tensorflow/compiler/xla/python/local_client.cc:758] Execution of replica 0 failed: Internal: Failed to launch CUDA kernel: CUDA_ERROR_INVALID_HANDLE: invalid resource handle
Traceback (most recent call last):
  File "trax/trainer.py", line 171, in <module>
    app.run(main)
  File "/usr/local/miniconda3/envs/trax-dev/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/miniconda3/envs/trax-dev/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "trax/trainer.py", line 164, in main
    trainer_lib.train(output_dir=output_dir)
  File "/usr/local/miniconda3/envs/trax-dev/lib/python3.6/site-packages/gin/config.py", line 1078, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/usr/local/miniconda3/envs/trax-dev/lib/python3.6/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/usr/local/miniconda3/envs/trax-dev/lib/python3.6/site-packages/gin/config.py", line 1055, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/nfs/private/play/trax/trax/supervised/trainer_lib.py", line 632, in train
    metrics=metrics, id_to_mask=id_to_mask)
  File "/nfs/private/play/trax/trax/supervised/trainer_lib.py", line 111, in __init__
    rng, init_rng = jax_random.split(rng)
  File "/nfs/private/play/trax/trax/math/backend.py", line 123, in split
    return backend()['random_split'](prng, num)
  File "/usr/local/miniconda3/envs/trax-dev/lib/python3.6/site-packages/jax/random.py", line 244, in split
    return _split(key, num)
  File "/usr/local/miniconda3/envs/trax-dev/lib/python3.6/site-packages/jax/api.py", line 149, in f_jitted
    out = xla.xla_call(flat_fun, *args_flat, device=device, backend=backend)
  File "/usr/local/miniconda3/envs/trax-dev/lib/python3.6/site-packages/jax/core.py", line 602, in call_bind
    outs = primitive.impl(f, *args, **params)
  File "/usr/local/miniconda3/envs/trax-dev/lib/python3.6/site-packages/jax/interpreters/xla.py", line 444, in _xla_call_impl
    return compiled_fun(*args)
  File "/usr/local/miniconda3/envs/trax-dev/lib/python3.6/site-packages/jax/interpreters/xla.py", line 549, in _execute_compiled
    out_bufs = compiled.Execute(input_bufs).destructure()
RuntimeError: Internal: Failed to launch CUDA kernel: CUDA_ERROR_INVALID_HANDLE: invalid resource handle
  In call to configurable 'train' (<function train at 0x7fdd6c847a60>)
```

**Comment by jekbradbury** [comment]
Maybe it's setting a cuBLAS or cuDNN handle at compile time that isn't valid on another device? If that's the case we should probably specialize our GPU binaries for the device instance they're going to run on (we don't need to do this when using CPUs or TPUs though...)

**Comment by hawkinsp** [comment]
@mktal I just hit this issue myself.

Trax uses TF for its input pipelines. I think it might be some sort of bad interaction between JAX and TensorFlow on GPU. Can you try installing a CPU-only tensorflow wheel from here: https://www.tensorflow.org/install/pip#package-location

Note the default wheels include GPU support, so you'll need to explicitly install a `tensorflow-cpu` wheel.

**Comment by MatejHl** [comment]
Hi @hawkinsp,

It seems that I'm facing similar issue as @jlebar using simple pmap and two GPUs with different types with jaxlib 0.1.67. Has something changed since 0.1.44 or am I missing something? 
Thanks.
- jaxlib version:  0.1.67+cuda111
- python version: 3.8.0
- jax version: 0.2.14
- CUDA version: 11.2

```
import jax
import jax.numpy as jnp

def fun(x):
    return jnp.sum(x)

pmapped_fun = jax.pmap(fun)

key = jax.random.PRNGKey(0)
data = jax.random.normal(key, shape = (2, 500))

results = pmapped_fun(data)

print(results)
```
And I'm getting this RuntimeError:
```
2021-07-08 19:19:44.915453: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:1981] Execution of replica 1 failed: Invalid argument: executable is built for device CUDA:0 of type "Quadro RTX 5000"; cannot run it on device CUDA:1 of type "Quadro RTX 4000"
Traceback (most recent call last):
  File "prot_bert_GNN/main_train_test.py", line 12, in <module>
    results = pmapped_fun(data)
  File "/home/matej/miniconda3/envs/ProtLig/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 183, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/matej/miniconda3/envs/ProtLig/lib/python3.8/site-packages/jax/_src/api.py", line 1647, in f_pmapped
    out = pxla.xla_pmap(
  File "/home/matej/miniconda3/envs/ProtLig/lib/python3.8/site-packages/jax/core.py", line 1620, in bind
    return call_bind(self, fun, *args, **params)
  File "/home/matej/miniconda3/envs/ProtLig/lib/python3.8/site-packages/jax/core.py", line 1551, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/home/matej/miniconda3/envs/ProtLig/lib/python3.8/site-packages/jax/core.py", line 1623, in process
    return trace.process_map(self, fun, tracers, params)
  File "/home/matej/miniconda3/envs/ProtLig/lib/python3.8/site-packages/jax/core.py", line 606, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/matej/miniconda3/envs/ProtLig/lib/python3.8/site-packages/jax/interpreters/pxla.py", line 637, in xla_pmap_impl
    return compiled_fun(*args)
  File "/home/matej/miniconda3/envs/ProtLig/lib/python3.8/site-packages/jax/interpreters/pxla.py", line 1152, in execute_replicated
    out_bufs = compiled.execute_sharded_on_local_devices(input_bufs)
jax._src.traceback_util.UnfilteredStackTrace: RuntimeError: Invalid argument: executable is built for device CUDA:0 of type "Quadro RTX 5000"; cannot run it on device CUDA:1 of type "Quadro RTX 4000": while running replica 1 and partition 0 of a replicated computation (other replicas may have failed as well).

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "prot_bert_GNN/main_train_test.py", line 12, in <module>
    results = pmapped_fun(data)
  File "/home/matej/miniconda3/envs/ProtLig/lib/python3.8/site-packages/jax/interpreters/pxla.py", line 1152, in execute_replicated
    out_bufs = compiled.execute_sharded_on_local_devices(input_bufs)
RuntimeError: Invalid argument: executable is built for device CUDA:0 of type "Quadro RTX 5000"; cannot run it on device CUDA:1 of type "Quadro RTX 4000": while running replica 1 and partition 0 of a replicated computation (other replicas may have failed as well).
```

**Comment by hawkinsp** [comment]
We don't intend to support `pmap` across heterogenous GPUs at this time. I admit the error isn't great, thoug.

**Comment by MatejHl** [comment]
Thanks for the super quick reply. 

I found the error message quite informative, I just could not find that this is expected behavior (and there is no intention to support this). Maybe there can be a small note in the docs for `pmap`.
