### ISSUE TITLE
TPU not found on VM

### ISSUE THREAD

**Issue by Eichhof** [google/jax#13321]
### Description

Hello

I'm running a TPU v3-8 VM on Google. On the VM I installed jax with `pip install "jax[tpu]==0.2.16" -f https://storage.googleapis.com/jax-releases/libtpu_releases.html`.

Unfortunately, I'm getting the message `No GPU/TPU found, falling back to CPU.` when issuing `jax.device_count()`. The same holds for `pip install jax==0.2.12`. Only when I'm using `pip install "jax[tpu]>=0.2.16" -f https://storage.googleapis.com/jax-releases/libtpu_releases.html` (newest jax version), it works. But I need jax version 0.2.12 or 0.2.16.

How can I get it running with these versions?

### What jax/jaxlib version are you using?

jax 0.2.16

### Which accelerator(s) are you using?

TPU

**Comment by zhangqiaorjc** [comment]
@skye do you know?

**Comment by skye** [comment]
Can you say more about why you need 0.2.12 or 0.2.16? These are very old versions. I'll dig into why 0.2.16 doesn't work, but it would definitely be simpler to use a newer version :)

**Comment by skye** [comment]
That didn't take as long as I expected :)

For 0.2.16, you can workaround by setting the env var `TPU_LIBRARY_PATH=/home/skyewm/.local/lib/python3.8/site-packages/libtpu/libtpu.so`. (You may have to adjust that path depending on where libtpu-nightly was installed; `locate libtpu.so` may be helpful)

The underlying problem is that this version of jax still expected libtpu.so to be automatically installed in the VM image (https://github.com/google/jax/blob/jax-v0.2.16/jax/_src/cloud_tpu_init.py#L104), which the TPU VM base image no longer does.

**Comment by skye** [comment]
Hey @Eichhof, does this work for you? If so I'll close the issue.

**Comment by Eichhof** [comment]
Thank you so much for your help. Highly appreciated! I will teat it this week and let you know.

**Comment by skye** [comment]
Thanks for letting us know, no rush!

**Comment by Eichhof** [comment]
I tested it now. I created a new TPU VM and installed jax using `pip install "jax[tpu]==0.2.16" -f https://storage.googleapis.com/jax-releases/libtpu_releases.html`. Afterwards, I set `echo TPU_LIBRARY_PATH=/home/myUsername/.local/lib/python3.8/site-packages/libtpu/libtpu.so`. When I was running now `import jax; jax.device_count()`, I got the following response:

```
D1205 22:55:15.241566995   11179 ev_posix.cc:173]            Using polling engine: epollex
D1205 22:55:15.241638035   11179 lb_policy_registry.cc:42]   registering LB policy factory for "grpclb"
D1205 22:55:15.241648712   11179 lb_policy_registry.cc:42]   registering LB policy factory for "priority_experimental"
D1205 22:55:15.241653540   11179 lb_policy_registry.cc:42]   registering LB policy factory for "weighted_target_experimental"
D1205 22:55:15.241656624   11179 lb_policy_registry.cc:42]   registering LB policy factory for "pick_first"
D1205 22:55:15.241659451   11179 lb_policy_registry.cc:42]   registering LB policy factory for "round_robin"
D1205 22:55:15.241664217   11179 lb_policy_registry.cc:42]   registering LB policy factory for "ring_hash_experimental"
D1205 22:55:15.241674608   11179 dns_resolver_ares.cc:497]   Using ares dns resolver
D1205 22:55:15.241704644   11179 certificate_provider_registry.cc:33] registering certificate provider factory for "file_watcher"
D1205 22:55:15.241714378   11179 lb_policy_registry.cc:42]   registering LB policy factory for "cds_experimental"
D1205 22:55:15.241719498   11179 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_impl_experimental"
D1205 22:55:15.241726682   11179 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_resolver_experimental"
D1205 22:55:15.241732858   11179 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_manager_experimental"
I1205 22:55:15.241853753   11179 server_builder.cc:349]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I1205 22:55:15.241936900   11179 socket_utils_common_posix.cc:353] TCP_USER_TIMEOUT is available. TCP_USER_TIMEOUT will be used thereafter
I1205 22:55:15.278600008   11881 subchannel.cc:1065]         New connected subchannel at 0x47f3080 for subchannel 0x492a000
8
```

So I think this looks good. But when I then exited python and issued again `python3; import jax;`, I got the error:

```
WARNING: Logging before InitGoogle() is written to STDERR
I1205 22:59:35.682652   15381 tpu_initializer_helper.cc:66] libtpu.so already in used by another process. Not attempting to load libtpu.so in this process.
```

**Comment by Eichhof** [comment]
Hello again

In addition to the above issue, I'm facing now a new problem. I try to run mesh-transformer-jax following this [guideline](https://github.com/Eichhof/mesh-transformer-jax/blob/master/howto_finetune.md). In particular, I'm installing the following packages:

```
pip install "jax[tpu]==0.2.16" -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
numpy~=1.19.5
tqdm>=4.48.0
wandb>=0.11.2
einops~=0.3.0
requests~=2.25.1
fabric~=2.6.0
optax==0.1.2
chex==0.1.2
dm-haiku==0.0.5
git+https://github.com/EleutherAI/lm-evaluation-harness/
ray[default]==1.4.1
jaxlib==0.1.68
Flask~=1.1.2
cloudpickle~=1.3.0
tensorflow-cpu~=2.5.0
google-cloud-storage~=1.36.2
transformers
smart_open[gcs]
func_timeout
ftfy
fastapi
uvicorn
lm_dataformat
pathy
protobuf==3.20.*
```

But when I now run `device_train.py`, I'm getting the following error:

```
2022-12-06 13:31:36.349286: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/lib
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

SystemError: <built-in method __contains__ of dict object at 0x7efe56345e00> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "device_train.py", line 16, in <module>
    from tfrecord_loader import TFRecordNewInputs
  File "/home/myUser/mesh-transformer-jax/tfrecord_loader.py", line 2, in <module>
    import TensorFlow as tf
  File "/home/myUser/.local/lib/python3.8/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/myUser/.local/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/home/myUser/.local/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 34, in <module>
    from tensorflow.python.client import pywrap_tf_session
  File "/home/myUser/.local/lib/python3.8/site-packages/tensorflow/python/client/pywrap_tf_session.py", line 19, in <module>
    from tensorflow.python.client._pywrap_tf_session import *
ImportError: initialization failed

```

**Comment by skye** [comment]
Can you try rerunning and sharing `/tmp/tpu_logs/tpu_driver.INFO`? That should give more information why the TPU runtime isn't able to come up.

(BTW, we've improved TPU runtime error reporting substantially since  0.2.16)

**Comment by skye** [comment]
Also, are you able to share why you're unable to upgrade jax? The real fix here may be addressing that issue :)

**Comment by Eichhof** [comment]
Please see below the content of tpu_driver.INFO.

I'm not able to upgrade jax because I want to use jax for fine-tuning GPT-J using the following tutorial: https://github.com/kingoflolz/mesh-transformer-jax/blob/master/howto_finetune.md
With newer Jax versions this does not work.


```
Log file created at: 2022/12/09 15:40:15
Running on machine: t1v-n-ee970b5a-w-0
Binary: Built on Jun 10 2021 11:50:32 (1623351002)
Binary: Built at cloud-tpus-runtime-release-tool@jgww9.prod.google.com:/google/src/cloud/buildrabbit-username/buildrabbit-client/g3
Binary: Built for gcc-4.X.Y-crosstool-v18-llvm-grtev4-k8
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1209 15:40:15.567064   13256 b295d63588a.cc:758] Linux version 5.13.0-1027-gcp (buildd@lcy02-amd64-062) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #32~20.04.1-Ubuntu SMP Thu May 26 10:53:08 UTC 2022
I1209 15:40:15.567366   13256 b295d63588a.cc:825] Process id 13256
I1209 15:40:15.567378   13256 b295d63588a.cc:830] Current working directory /home/myUsername
I1209 15:40:15.567379   13256 b295d63588a.cc:832] Current timezone is UTC (currently UTC +00:00)
I1209 15:40:15.567382   13256 b295d63588a.cc:836] Built on Jun 10 2021 11:50:32 (1623351002)
I1209 15:40:15.567382   13256 b295d63588a.cc:837]  at cloud-tpus-runtime-release-tool@jgww9.prod.google.com:/google/src/cloud/buildrabbit-username/buildrabbit-client/g3
I1209 15:40:15.567383   13256 b295d63588a.cc:838]  as //learning/45eac/tfrc/executor:_libtpu.so
I1209 15:40:15.567384   13256 b295d63588a.cc:839]  for gcc-4.X.Y-crosstool-v18-llvm-grtev4-k8
I1209 15:40:15.567385   13256 b295d63588a.cc:842]  from changelist 378699432 with baseline 378699432 in a mint client based on __ar56t/g3
I1209 15:40:15.567386   13256 b295d63588a.cc:846] Build label: libtpu_runtime_20210610_RC00
I1209 15:40:15.567387   13256 b295d63588a.cc:848] Build tool: Bazel, release r4rca-2021.06.04-6 (mainline @377391976)
I1209 15:40:15.567388   13256 b295d63588a.cc:849] Build target:
I1209 15:40:15.567389   13256 b295d63588a.cc:861] Command line arguments:
I1209 15:40:15.567390   13256 b295d63588a.cc:863] argv[0]: './tpu_driver'
I1209 15:40:15.567393   13256 b295d63588a.cc:863] argv[1]: '--minloglevel=0'
I1209 15:40:15.567394   13256 b295d63588a.cc:863] argv[2]: '--stderrthreshold=3'
I1209 15:40:15.567395   13256 b295d63588a.cc:863] argv[3]: '--v=0'
I1209 15:40:15.567396   13256 b295d63588a.cc:863] argv[4]: '--vmodule='
I1209 15:40:15.567397   13256 b295d63588a.cc:863] argv[5]: '--log_dir=/tmp/tpu_logs'
I1209 15:40:15.567398   13256 b295d63588a.cc:863] argv[6]: '--max_log_size=1024'
I1209 15:40:15.567654   13256 builtin.cc:16] 7edfa70aa11b3ffd6f: /memfile/routing_cache_files
I1209 15:40:15.567666   13256 builtin.cc:16] 7edfa70aa11b3ffd6f: /memfile/tpu_chip_config_memfile_default
I1209 15:40:15.567670   13256 builtin.cc:16] 7edfa70aa11b3ffd6f: /memfile/tpu_chip_config_memfile_inference
I1209 15:40:15.567675   13256 builtin.cc:16] 7edfa70aa11b3ffd6f: /memfile/tpu_chip_parts_memfile
I1209 15:40:15.567717   13256 coredump_hook.cc:666] Remote crash gathering hook installed.
I1209 15:40:15.568024   13256 prodhostname_userspace_monitor_impl.cc:188] Not running under a Borglet, disabling ProdHostname userspace monitoring.
W1209 15:40:15.568059   13256 tf_tpu_flags.cc:51] Configuring 2a886c8 Platform flags with tensorflow flags. The original flag values are ignored.
W1209 15:40:15.568136   13256 tf_tpu_flags.cc:78] --2a886c8_chips_per_host_bounds overridden to: {x = 2, y = 2, z = 1}
W1209 15:40:15.568150   13256 tf_tpu_flags.cc:85] --2a886c8_wrap overridden to: {x = false, y = false, z = false}
W1209 15:40:15.568155   13256 tf_tpu_flags.cc:94] --2a886c8_host_bounds overridden to: {x = 1, y = 1, z = 1}
W1209 15:40:15.568161   13256 tf_tpu_flags.cc:98] --2a886c8_missing_chip_count overridden to: 0
I1209 15:40:15.568209   13256 logger.cc:274] Enabling threaded logging for severity WARNING
I1209 15:40:23.491515   13256 device_util.cc:61] Found 4 6bf72d463e chips.
I1209 15:40:23.491567   13256 tpu_version_flag.cc:50] Using auto-detected TPU version 6bf72d463e
I1209 15:40:23.492314   13256 device_util.cc:61] Found 4 6bf72d463e chips.
I1209 15:40:23.492992   13256 device_util.cc:61] Found 4 6bf72d463e chips.
I1209 15:40:23.493635   13256 device_util.cc:61] Found 4 6bf72d463e chips.
I1209 15:40:23.493641   13256 flags_util.cc:215] Using default chip configuration.
I1209 15:40:23.493926   13256 flags_util.cc:330] Picked unused port 56020 as a555f10594 port.
I1209 15:40:23.494705   13256 device_util.cc:61] Found 4 6bf72d463e chips.
I1209 15:40:23.494713   13256 2a886c8_platform.cc:402] Initializing 2a886c8Platform hardware implementation.
I1209 15:40:23.495307   13256 device_util.cc:61] Found 4 6bf72d463e chips.
I1209 15:40:23.495957   13256 device_util.cc:61] Found 4 6bf72d463e chips.
W1209 15:40:23.499049   13256 device_scanner.cc:210] failures while refreshing ba16c7433 device info from files:
FAILED_PRECONDITION: Failed to read file [type.googleapis.com/util.ErrorSpacePayload='util::PosixErrorSpace::Bad file descriptor']
FAILED_PRECONDITION: Failed to read file [type.googleapis.com/util.ErrorSpacePayload='util::PosixErrorSpace::Bad file descriptor']
FAILED_PRECONDITION: Failed to read file [type.googleapis.com/util.ErrorSpacePayload='util::PosixErrorSpace::Bad file descriptor']
```

**Comment by rinapch** [comment]
Hey @Eichhof! For what it's worth, I was able to train GPTJ with this code using jax 0.2.18 or 0.2.20. You'd have to resolve a few dependency issues (I used poetry), but it works

**Comment by skye** [comment]
Hey sorry, missed this earlier. Unfortunately it's not clear to me from the log what the issue is. This looks ok (despite the FAILED_PRECONDITION lines, those are usually spurious), but like it's just getting stuck somewhere.

I suggest trying to use a newer jax version like @rinapch. You can also try using a different code base that supports newer jax versions. https://github.com/salesforce/jaxformer could be a reasonable alternative.
