### ISSUE TITLE
OOM with only ~47MB memory allocated / requested on GPU

### ISSUE THREAD

**Issue by GCChen97** [google/jax#13428]
### Description

I tried to run multinerf, but no matter how small the batch size was, OOM would arise.

```
2022-11-29 20:30:37.803154: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2153] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 49592744 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    2.72MiB
              constant allocation:     2.8KiB
        maybe_live_out allocation:   386.5KiB
     preallocated temp allocation:   47.29MiB
  preallocated temp fragmentation:    3.50MiB (7.40%)
                 total allocation:   50.40MiB
              total fragmentation:    3.86MiB (7.66%)
Peak buffers:
        Buffer 1:
                Size: 4.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/select_n" source_file="/media/gccrcv/Data/Opensources/multinerf/internal/models.py" source_line=457
                XLA Label: fusion
                Shape: f32[4096,256]
                ==========================

        Buffer 2:
                Size: 4.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/select_n" source_file="/media/gccrcv/Data/Opensources/multinerf/internal/models.py" source_line=457
                XLA Label: fusion
                Shape: f32[4096,256]
                ==========================

        Buffer 3:
                Size: 2.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/vmap(jvp(Dense_6))/dot_general[dimension_numbers=(((1,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
                XLA Label: custom-call
                Shape: f32[2048,256]
                ==========================

        Buffer 4:
                Size: 2.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/vmap(jvp(Dense_5))/dot_general[dimension_numbers=(((1,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
                XLA Label: custom-call
                Shape: f32[2048,256]
                ==========================

        Buffer 5:
                Size: 2.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/vmap(jvp(Dense_4))/dot_general[dimension_numbers=(((1,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
                XLA Label: custom-call
                Shape: f32[2048,256]
                ==========================

        Buffer 6:
                Size: 2.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/vmap(jvp(Dense_3))/dot_general[dimension_numbers=(((1,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
                XLA Label: custom-call
                Shape: f32[2048,256]
                ==========================

        Buffer 7:
                Size: 2.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/vmap(jvp(Dense_2))/dot_general[dimension_numbers=(((1,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
                XLA Label: custom-call
                Shape: f32[2048,256]
                ==========================

        Buffer 8:
                Size: 2.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/vmap(jvp(Dense_1))/dot_general[dimension_numbers=(((1,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
                XLA Label: custom-call
                Shape: f32[2048,256]
                ==========================

        Buffer 9:
                Size: 2.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/vmap(jvp(Dense_0))/dot_general[dimension_numbers=(((1,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
                XLA Label: custom-call
                Shape: f32[2048,256]
                ==========================

        Buffer 10:
                Size: 2.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/vmap(jvp(Dense_7))/dot_general[dimension_numbers=(((1,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
                XLA Label: custom-call
                Shape: f32[2048,256]
                ==========================

        Buffer 11:
                Size: 2.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/vmap(jvp(Dense_6))/dot_general[dimension_numbers=(((1,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
                XLA Label: custom-call
                Shape: f32[2048,256]
                ==========================

        Buffer 12:
                Size: 2.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/vmap(jvp(Dense_5))/dot_general[dimension_numbers=(((1,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
                XLA Label: custom-call
                Shape: f32[2048,256]
                ==========================

        Buffer 13:
                Size: 2.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/vmap(jvp(Dense_4))/dot_general[dimension_numbers=(((1,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
                XLA Label: custom-call
                Shape: f32[2048,256]
                ==========================

        Buffer 14:
                Size: 2.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/vmap(jvp(Dense_3))/dot_general[dimension_numbers=(((1,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
                XLA Label: custom-call
                Shape: f32[2048,256]
                ==========================

        Buffer 15:
                Size: 2.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/vmap(jvp(Dense_2))/dot_general[dimension_numbers=(((1,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
                XLA Label: custom-call
                Shape: f32[2048,256]
                ==========================


Traceback (most recent call last):
  File "/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/media/gccrcv/Data/Opensources/multinerf/train.py", line 288, in <module>
    app.run(main)
  File "/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/media/gccrcv/Data/Opensources/multinerf/train.py", line 229, in main
    rendering = models.render_image(
  File "/media/gccrcv/Data/Opensources/multinerf/internal/models.py", line 673, in render_image
    chunk_renderings, _ = render_fn(rng, chunk_rays)
ValueError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 49592744 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    2.72MiB
              constant allocation:     2.8KiB
        maybe_live_out allocation:   386.5KiB
     preallocated temp allocation:   47.29MiB
  preallocated temp fragmentation:    3.50MiB (7.40%)
                 total allocation:   50.40MiB
              total fragmentation:    3.86MiB (7.66%)
Peak buffers:
        Buffer 1:
                Size: 4.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/select_n" source_file="/media/gccrcv/Data/Opensources/multinerf/internal/models.py" source_line=457
                XLA Label: fusion
                Shape: f32[4096,256]
                ==========================

        Buffer 2:
                Size: 4.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/select_n" source_file="/media/gccrcv/Data/Opensources/multinerf/internal/models.py" source_line=457
                XLA Label: fusion
                Shape: f32[4096,256]
                ==========================

        Buffer 3:
                Size: 2.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/vmap(jvp(Dense_6))/dot_general[dimension_numbers=(((1,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
                XLA Label: custom-call
                Shape: f32[2048,256]
                ==========================

        Buffer 4:
                Size: 2.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/vmap(jvp(Dense_5))/dot_general[dimension_numbers=(((1,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
                XLA Label: custom-call
                Shape: f32[2048,256]
                ==========================

        Buffer 5:
                Size: 2.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/vmap(jvp(Dense_4))/dot_general[dimension_numbers=(((1,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
                XLA Label: custom-call
                Shape: f32[2048,256]
                ==========================

        Buffer 6:
                Size: 2.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/vmap(jvp(Dense_3))/dot_general[dimension_numbers=(((1,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
                XLA Label: custom-call
                Shape: f32[2048,256]
                ==========================

        Buffer 7:
                Size: 2.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/vmap(jvp(Dense_2))/dot_general[dimension_numbers=(((1,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
                XLA Label: custom-call
                Shape: f32[2048,256]
                ==========================

        Buffer 8:
                Size: 2.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/vmap(jvp(Dense_1))/dot_general[dimension_numbers=(((1,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
                XLA Label: custom-call
                Shape: f32[2048,256]
                ==========================

        Buffer 9:
                Size: 2.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/vmap(jvp(Dense_0))/dot_general[dimension_numbers=(((1,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
                XLA Label: custom-call
                Shape: f32[2048,256]
                ==========================

        Buffer 10:
                Size: 2.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/vmap(jvp(Dense_7))/dot_general[dimension_numbers=(((1,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
                XLA Label: custom-call
                Shape: f32[2048,256]
                ==========================

        Buffer 11:
                Size: 2.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/vmap(jvp(Dense_6))/dot_general[dimension_numbers=(((1,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
                XLA Label: custom-call
                Shape: f32[2048,256]
                ==========================

        Buffer 12:
                Size: 2.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/vmap(jvp(Dense_5))/dot_general[dimension_numbers=(((1,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
                XLA Label: custom-call
                Shape: f32[2048,256]
                ==========================

        Buffer 13:
                Size: 2.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/vmap(jvp(Dense_4))/dot_general[dimension_numbers=(((1,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
                XLA Label: custom-call
                Shape: f32[2048,256]
                ==========================

        Buffer 14:
                Size: 2.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/vmap(jvp(Dense_3))/dot_general[dimension_numbers=(((1,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
                XLA Label: custom-call
                Shape: f32[2048,256]
                ==========================

        Buffer 15:
                Size: 2.00MiB
                Operator: op_name="pmap(render_eval_fn)/jit(main)/Model/NerfMLP_0/vmap(jvp(Dense_2))/dot_general[dimension_numbers=(((1,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
                XLA Label: custom-call
                Shape: f32[2048,256]
                ==========================

```

### What jax/jaxlib version are you using?

jax v0.3.24/0.3.25 jaxlib v0.3.24/0.3.25, flax v0.6.1/2

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.9, Ubuntu 20.04.5

### NVIDIA GPU info

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.85.02    Driver Version: 510.85.02    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   52C    P8    32W / 350W |   1177MiB / 24576MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

```

**Comment by GCChen97** [comment]
Got different output after reboot.
```
2022-11-29 21:04:39.275246: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2153] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 6291456 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    6.00MiB
              constant allocation:         0B
        maybe_live_out allocation:    6.00MiB
     preallocated temp allocation:         0B
                 total allocation:   12.00MiB
              total fragmentation:         0B (0.00%)
Peak buffers:
        Buffer 1:
                Size: 6.00MiB
                Operator: op_name="jit(concatenate)/jit(main)/concatenate[dimension=0]" source_file="/media/gccrcv/Data/Opensources/multinerf/internal/models.py" source_line=689
                XLA Label: concatenate
                Shape: f32[4096,128,3]
                ==========================

        Buffer 2:
                Size: 384.0KiB
                Entry Parameter Subshape: f32[256,128,3]
                ==========================

        Buffer 3:
                Size: 384.0KiB
                Entry Parameter Subshape: f32[256,128,3]
                ==========================

        Buffer 4:
                Size: 384.0KiB
                Entry Parameter Subshape: f32[256,128,3]
                ==========================

        Buffer 5:
                Size: 384.0KiB
                Entry Parameter Subshape: f32[256,128,3]
                ==========================

        Buffer 6:
                Size: 384.0KiB
                Entry Parameter Subshape: f32[256,128,3]
                ==========================

        Buffer 7:
                Size: 384.0KiB
                Entry Parameter Subshape: f32[256,128,3]
                ==========================

        Buffer 8:
                Size: 384.0KiB
                Entry Parameter Subshape: f32[256,128,3]
                ==========================

        Buffer 9:
                Size: 384.0KiB
                Entry Parameter Subshape: f32[256,128,3]
                ==========================

        Buffer 10:
                Size: 384.0KiB
                Entry Parameter Subshape: f32[256,128,3]
                ==========================

        Buffer 11:
                Size: 384.0KiB
                Entry Parameter Subshape: f32[256,128,3]
                ==========================

        Buffer 12:
                Size: 384.0KiB
                Entry Parameter Subshape: f32[256,128,3]
                ==========================

        Buffer 13:
                Size: 384.0KiB
                Entry Parameter Subshape: f32[256,128,3]
                ==========================

        Buffer 14:
                Size: 384.0KiB
                Entry Parameter Subshape: f32[256,128,3]
                ==========================

        Buffer 15:
                Size: 384.0KiB
                Entry Parameter Subshape: f32[256,128,3]
                ==========================


Traceback (most recent call last):
  File "/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/media/gccrcv/Data/Opensources/multinerf/train.py", line 288, in <module>
    app.run(main)
  File "/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/media/gccrcv/Data/Opensources/multinerf/train.py", line 229, in main
    rendering = models.render_image(
  File "/media/gccrcv/Data/Opensources/multinerf/internal/models.py", line 689, in render_image
    jax.tree_util.tree_map(lambda *args: jnp.concatenate(args), *chunks))
  File "/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/jax/_src/tree_util.py", line 207, in tree_map
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/jax/_src/tree_util.py", line 207, in <genexpr>
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "/media/gccrcv/Data/Opensources/multinerf/internal/models.py", line 689, in <lambda>
    jax.tree_util.tree_map(lambda *args: jnp.concatenate(args), *chunks))
  File "/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 1791, in concatenate
    arrays_out = [lax.concatenate(arrays_out[i:i+k], axis)
  File "/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 1791, in <listcomp>
    arrays_out = [lax.concatenate(arrays_out[i:i+k], axis)
  File "/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/jax/_src/lax/lax.py", line 648, in concatenate
    return concatenate_p.bind(*operands, dimension=dimension)
  File "/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/jax/core.py", line 329, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/jax/core.py", line 332, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/jax/core.py", line 712, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/jax/_src/dispatch.py", line 115, in apply_primitive
    return compiled_fun(*args)
  File "/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/jax/_src/dispatch.py", line 200, in <lambda>
    return lambda *args, **kw: compiled(*args, **kw)[0]
  File "/home/gccrcv/anaconda3/envs/multinerf/lib/python3.9/site-packages/jax/_src/dispatch.py", line 895, in _execute_compiled
    out_flat = compiled.execute(in_flat)
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 6291456 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    6.00MiB
              constant allocation:         0B
        maybe_live_out allocation:    6.00MiB
     preallocated temp allocation:         0B
                 total allocation:   12.00MiB
              total fragmentation:         0B (0.00%)
Peak buffers:
        Buffer 1:
                Size: 6.00MiB
                Operator: op_name="jit(concatenate)/jit(main)/concatenate[dimension=0]" source_file="/media/gccrcv/Data/Opensources/multinerf/internal/models.py" source_line=689
                XLA Label: concatenate
                Shape: f32[4096,128,3]
                ==========================

        Buffer 2:
                Size: 384.0KiB
                Entry Parameter Subshape: f32[256,128,3]
                ==========================

        Buffer 3:
                Size: 384.0KiB
                Entry Parameter Subshape: f32[256,128,3]
                ==========================

        Buffer 4:
                Size: 384.0KiB
                Entry Parameter Subshape: f32[256,128,3]
                ==========================

        Buffer 5:
                Size: 384.0KiB
                Entry Parameter Subshape: f32[256,128,3]
                ==========================

        Buffer 6:
                Size: 384.0KiB
                Entry Parameter Subshape: f32[256,128,3]
                ==========================

        Buffer 7:
                Size: 384.0KiB
                Entry Parameter Subshape: f32[256,128,3]
                ==========================

        Buffer 8:
                Size: 384.0KiB
                Entry Parameter Subshape: f32[256,128,3]
                ==========================

        Buffer 9:
                Size: 384.0KiB
                Entry Parameter Subshape: f32[256,128,3]
                ==========================

        Buffer 10:
                Size: 384.0KiB
                Entry Parameter Subshape: f32[256,128,3]
                ==========================

        Buffer 11:
                Size: 384.0KiB
                Entry Parameter Subshape: f32[256,128,3]
                ==========================

        Buffer 12:
                Size: 384.0KiB
                Entry Parameter Subshape: f32[256,128,3]
                ==========================

        Buffer 13:
                Size: 384.0KiB
                Entry Parameter Subshape: f32[256,128,3]
                ==========================

        Buffer 14:
                Size: 384.0KiB
                Entry Parameter Subshape: f32[256,128,3]
                ==========================

        Buffer 15:
                Size: 384.0KiB
                Entry Parameter Subshape: f32[256,128,3]
                ==========================
```
