### ISSUE TITLE
Failed to determine best cudnn convolution algorithm

### ISSUE THREAD

**Issue by RemiLacroix-IDRIS** [google/jax#13612]
### Description

Hello,

I got the following error message running https://github.com/google-research/multinerf:

```
2022-12-12 14:17:37.451910: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_conv_algorithm_picker.cc:727] None of the algorithms provided by cuDNN heuristics worked; trying fallback algorithms.  Conv: (f32[2520,1,1287]{2,1,0}, u8[0]{0}) custom-call(f32[2520,1,1297]{2,1,0}, f32[1,1,11]{2,1,0}), window={size=11}, dim_labels=bf0_oi0->bf0, custom_call_target="__cudnn$convForward", backend_config="{\"conv_result_scale\":1,\"activation_mode\":\"0\",\"side_input_scale\":0}"
Traceback (most recent call last):
  File "/.../tensorflow/multinerf/train.py", line 288, in <module>
    app.run(main)
  File "/.../pub/anaconda-py3/2021.05/envs/tensorflow-2.9.1+py3.10/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/.../pub/anaconda-py3/2021.05/envs/tensorflow-2.9.1+py3.10/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/.../tensorflow/multinerf/train.py", line 242, in main
    metric = metric_harness(
  File "/.../tensorflow/multinerf/internal/image.py", line 136, in __call__
    ssim = float(self.ssim_fn(rgb_pred, rgb_gt))
  File "/.../src/pub/anaconda-py3/2021.05/tensorflow-2.9.1+py3.10/jaxlib-v0.3.14/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/.../src/pub/anaconda-py3/2021.05/tensorflow-2.9.1+py3.10/jaxlib-v0.3.14/jax/_src/api.py", line 522, in cache_miss
    out_flat = xla.xla_call(
  File "/.../src/pub/anaconda-py3/2021.05/tensorflow-2.9.1+py3.10/jaxlib-v0.3.14/jax/core.py", line 1836, in bind
    return call_bind(self, fun, *args, **params)
  File "/.../src/pub/anaconda-py3/2021.05/tensorflow-2.9.1+py3.10/jaxlib-v0.3.14/jax/core.py", line 1852, in call_bind
    outs = top_trace.process_call(primitive, fun_, tracers, params)
  File "/.../src/pub/anaconda-py3/2021.05/tensorflow-2.9.1+py3.10/jaxlib-v0.3.14/jax/core.py", line 683, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/.../src/pub/anaconda-py3/2021.05/tensorflow-2.9.1+py3.10/jaxlib-v0.3.14/jax/_src/dispatch.py", line 196, in _xla_call_impl
    compiled_fun = xla_callable(fun, device, backend, name, donated_invars,
  File "/.../src/pub/anaconda-py3/2021.05/tensorflow-2.9.1+py3.10/jaxlib-v0.3.14/jax/linear_util.py", line 286, in memoized_fun
    ans = call(fun, *args)
  File "/.../src/pub/anaconda-py3/2021.05/tensorflow-2.9.1+py3.10/jaxlib-v0.3.14/jax/_src/dispatch.py", line 246, in _xla_callable_uncached
    keep_unused, *arg_specs).compile().unsafe_call
  File "/.../src/pub/anaconda-py3/2021.05/tensorflow-2.9.1+py3.10/jaxlib-v0.3.14/jax/_src/dispatch.py", line 808, in compile
    self._executable = XlaCompiledComputation.from_xla_computation(
  File "/.../src/pub/anaconda-py3/2021.05/tensorflow-2.9.1+py3.10/jaxlib-v0.3.14/jax/_src/dispatch.py", line 911, in from_xla_computation
    compiled = compile_or_get_cached(backend, xla_computation, options)
  File "/.../src/pub/anaconda-py3/2021.05/tensorflow-2.9.1+py3.10/jaxlib-v0.3.14/jax/_src/dispatch.py", line 872, in compile_or_get_cached
    return backend_compile(backend, computation, compile_options)
  File "/.../src/pub/anaconda-py3/2021.05/tensorflow-2.9.1+py3.10/jaxlib-v0.3.14/jax/_src/profiler.py", line 312, in wrapper
    return func(*args, **kwargs)
  File "/.../src/pub/anaconda-py3/2021.05/tensorflow-2.9.1+py3.10/jaxlib-v0.3.14/jax/_src/dispatch.py", line 818, in backend_compile
    return backend.compile(built_c, compile_options=options)
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: UNKNOWN: Failed to determine best cudnn convolution algorithm for:
%cudnn-conv = (f32[2520,1,1287]{2,1,0}, u8[0]{0}) custom-call(f32[2520,1,1297]{2,1,0} %bitcast.4, f32[1,1,11]{2,1,0} %bitcast.5), window={size=11}, dim_labels=bf0_oi0->bf0, custom_call_target="__cudnn$convForward", metadata={op_name="jit(ssim)/jit(main)/vmap(jit(convolve))/jit(_conv)/conv_general_dilated[window_strides=(1,) padding=((0, 0),) lhs_dilation=(1,) rhs_dilation=(1,) dimension_numbers=ConvDimensionNumbers(lhs_spec=(0, 1, 2), rhs_spec=(0, 1, 2), out_spec=(0, 1, 2)) feature_group_count=1 batch_group_count=1 lhs_shape=(2520, 1, 1297) rhs_shape=(1, 1, 11) precision=(<Precision.HIGHEST: 2>, <Precision.HIGHEST: 2>) preferred_element_type=None]" source_file="/.../.local/lib/python3.10/site-packages/dm_pix/_src/metrics.py" source_line=177}, backend_config="{\"conv_result_scale\":1,\"activation_mode\":\"0\",\"side_input_scale\":0}"

Original error: INTERNAL: All algorithms tried for %cudnn-conv = (f32[2520,1,1287]{2,1,0}, u8[0]{0}) custom-call(f32[2520,1,1297]{2,1,0} %bitcast.4, f32[1,1,11]{2,1,0} %bitcast.5), window={size=11}, dim_labels=bf0_oi0->bf0, custom_call_target="__cudnn$convForward", metadata={op_name="jit(ssim)/jit(main)/vmap(jit(convolve))/jit(_conv)/conv_general_dilated[window_strides=(1,) padding=((0, 0),) lhs_dilation=(1,) rhs_dilation=(1,) dimension_numbers=ConvDimensionNumbers(lhs_spec=(0, 1, 2), rhs_spec=(0, 1, 2), out_spec=(0, 1, 2)) feature_group_count=1 batch_group_count=1 lhs_shape=(2520, 1, 1297) rhs_shape=(1, 1, 11) precision=(<Precision.HIGHEST: 2>, <Precision.HIGHEST: 2>) preferred_element_type=None]" source_file="/.../.local/lib/python3.10/site-packages/dm_pix/_src/metrics.py" source_line=177}, backend_config="{\"conv_result_scale\":1,\"activation_mode\":\"0\",\"side_input_scale\":0}" failed. Falling back to default algorithm.  Per-algorithm errors:
  Profiling failure on cuDNN engine eng30{k2=2,k4=0,k5=0,k6=0,k7=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'
  Profiling failure on cuDNN engine eng28{k2=4,k3=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'
  Profiling failure on cuDNN engine eng1{k2=4,k3=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'
  Profiling failure on cuDNN engine eng42{k4=3,k5=1,k6=0,k7=0,k2=1}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'
  Profiling failure on cuDNN engine eng42{k2=2,k4=1,k5=0,k6=0,k7=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'
  Profiling failure on cuDNN engine eng0{}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'
  Profiling failure on cuDNN engine eng1{}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'
  Profiling failure on cuDNN engine eng2{}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'
  Profiling failure on cuDNN engine eng4{}: UNKNOWN: CUDNN_STATUS_INTERNAL_ERROR
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'
  Profiling failure on cuDNN engine eng28{}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'
  Profiling failure on cuDNN engine eng30{}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'
  Profiling failure on cuDNN engine eng34{}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'
  Profiling failure on cuDNN engine eng42{}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'

To ignore this failure and try to use a fallback algorithm (which may have suboptimal performance), use XLA_FLAGS=--xla_gpu_strict_conv_algorithm_picker=false.  Please also file a bug for the root cause of failing autotuning.
```
Not sure what to do about it.

Best,
Rémi

### What jax/jaxlib version are you using?

0.3.14

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.10.5, Linux RedHat 8.4

### NVIDIA GPU info

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.07    Driver Version: 515.65.07    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:1A:00.0 Off |                    0 |
| N/A   46C    P0    45W / 300W |      0MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:1C:00.0 Off |                    0 |
| N/A   47C    P0    43W / 300W |      0MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  On   | 00000000:88:00.0 Off |                    0 |
| N/A   71C    P0   290W / 300W |   1794MiB / 16384MiB |     98%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  On   | 00000000:8A:00.0 Off |                    0 |
| N/A   69C    P0   294W / 300W |   1794MiB / 16384MiB |     98%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Comment by hawkinsp** [comment]
Can you try an experiment for me? I'm speculating you ran out of GPU memory.
Try lowering the GPU memory fraction as documented here: https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html

(Try perhaps 0.8?)

**Comment by RemiLacroix-IDRIS** [comment]
> Can you try an experiment for me? I'm speculating you ran out of GPU memory.

Seems like you're right! I tried on a node with 32GB V100 GPU and it seems to work fine.

I would not have thought about this so thanks! :)
