### ISSUE TITLE
Build failure for jaxlib v0.4.1 on Windows 10 #12187

### ISSUE THREAD

**Issue by adam-hartshorne** [google/jax#13646]
### Description

On windows 10 box with python 3.9, cuda 11.7, cudnn 8.4.0 using the following command

`python .\build\build.py --enable_cuda --cuda_path="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.7" --cudnn_path="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.7" --cuda_compute_capabilities="7.5" --cuda_version="11.7" --cudnn_version="8.4.0" --noenable_rocm --noenable_tp`

fails to build from source with the following error

`syntax error: '#'\r\nexternal/org_tensorflow/tensorflow/compiler/xla/python/jax_jit.cc(811): error C3536: '_status_or_value10': cannot be used before it is initialized\r\nexternal/org_tensorflow/tensorflow/compiler/xla/python/jax_jit.cc(806): error C2512: 'xla::DevicePutResult': no appropriate default constructor available\r\nexternal/org_tensorflow\\tensorflow/compiler/xla/python/py_values.h(33): note: see declaration of 'xla::DevicePutResult'\r\n"`

The full error message is as follows,

```
b"external/llvm-project/llvm/include\\llvm/Support/type_traits.h(79): warning C4624: 'llvm::detail::copy_construction_triviality_helper<T>': destructor was implicitly defined as deleted\r\n        with\r\n        [\r\n            T=mlir::detail::ElementsAttrIndexer\r\n        ]\r\nC:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\include\\type_traits(631): note: see reference to class template instantiation 'llvm::detail::copy_construction_triviality_helper<T>' being compiled\r\n        with\r\n        [\r\n            T=mlir::detail::ElementsAttrIndexer\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/Support/type_traits.h(100): note: see reference to class template instantiation 'std::is_copy_constructible<llvm::detail::copy_construction_triviality_helper<T>>' being compiled\r\n        with\r\n        [\r\n            T=mlir::detail::ElementsAttrIndexer\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/ADT/Optional.h(51): note: see reference to class template instantiation 'llvm::is_trivially_copy_constructible<T>' being compiled\r\n        with\r\n        [\r\n            T=mlir::detail::ElementsAttrIndexer\r\n        ]\r\nexternal/llvm-project/mlir/include\\mlir/Support/LogicalResult.h(78): note: see reference to class template instantiation 'llvm::Optional<T>' being compiled\r\n        with\r\n        [\r\n            T=mlir::detail::ElementsAttrIndexer\r\n        ]\r\nbazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/BuiltinAttributeInterfacesIncGen\\mlir/IR/BuiltinAttributeInterfaces.h.inc(206): note: see reference to class template instantiation 'mlir::FailureOr<mlir::detail::ElementsAttrIndexer>' being compiled\r\nbazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/BuiltinAttributeInterfacesIncGen\\mlir/IR/BuiltinAttributeInterfaces.h.inc(351): note: see reference to class template instantiation 'mlir::detail::ElementsAttrTrait<ConcreteAttr>' being compiled\r\nexternal/llvm-project/llvm/include\\llvm/Support/type_traits.h(86): warning C4624: 'llvm::detail::move_construction_triviality_helper<T>': destructor was implicitly defined as deleted\r\n        with\r\n        [\r\n            T=mlir::detail::ElementsAttrIndexer\r\n        ]\r\nC:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\include\\type_traits(662): note: see reference to class template instantiation 'llvm::detail::move_construction_triviality_helper<T>' being compiled\r\n        with\r\n        [\r\n            T=mlir::detail::ElementsAttrIndexer\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/Support/type_traits.h(111): note: see reference to class template instantiation 'std::is_move_constructible<llvm::detail::move_construction_triviality_helper<T>>' being compiled\r\n        with\r\n        [\r\n            T=mlir::detail::ElementsAttrIndexer\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/ADT/Optional.h(51): note: see reference to class template instantiation 'llvm::is_trivially_move_constructible<T>' being compiled\r\n        with\r\n        [\r\n            T=mlir::detail::ElementsAttrIndexer\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/Support/type_traits.h(79): warning C4624: 'llvm::detail::copy_construction_triviality_helper<T>': destructor was implicitly defined as deleted\r\n        with\r\n        [\r\n            T=std::unique_ptr<mlir::Region,std::default_delete<mlir::Region>>\r\n        ]\r\nC:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\include\\type_traits(631): note: see reference to class template instantiation 'llvm::detail::copy_construction_triviality_helper<T>' being compiled\r\n        with\r\n        [\r\n            T=std::unique_ptr<mlir::Region,std::default_delete<mlir::Region>>\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/Support/type_traits.h(100): note: see reference to class template instantiation 'std::is_copy_constructible<llvm::detail::copy_construction_triviality_helper<T>>' being compiled\r\n        with\r\n        [\r\n            T=std::unique_ptr<mlir::Region,std::default_delete<mlir::Region>>\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/ADT/SmallVector.h(329): note: see reference to class template instantiation 'llvm::is_trivially_copy_constructible<T>' being compiled\r\n        with\r\n        [\r\n            T=std::unique_ptr<mlir::Region,std::default_delete<mlir::Region>>\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/ADT/SmallVector.h(1199): note: see reference to class template instantiation 'llvm::SmallVectorImpl<T>' being compiled\r\n        with\r\n        [\r\n            T=std::unique_ptr<mlir::Region,std::default_delete<mlir::Region>>\r\n        ]\r\nexternal/llvm-project/mlir/include\\mlir/IR/OperationSupport.h(638): note: see reference to class template instantiation 'llvm::SmallVector<std::unique_ptr<mlir::Region,std::default_delete<mlir::Region>>,1>' being compiled\r\nexternal/llvm-project/llvm/include\\llvm/Support/type_traits.h(86): warning C4624: 'llvm::detail::move_construction_triviality_helper<T>': destructor was implicitly defined as deleted\r\n        with\r\n        [\r\n            T=std::unique_ptr<mlir::Region,std::default_delete<mlir::Region>>\r\n        ]\r\nC:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\include\\type_traits(662): note: see reference to class template instantiation 'llvm::detail::move_construction_triviality_helper<T>' being compiled\r\n        with\r\n        [\r\n            T=std::unique_ptr<mlir::Region,std::default_delete<mlir::Region>>\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/Support/type_traits.h(111): note: see reference to class template instantiation 'std::is_move_constructible<llvm::detail::move_construction_triviality_helper<T>>' being compiled\r\n        with\r\n        [\r\n            T=std::unique_ptr<mlir::Region,std::default_delete<mlir::Region>>\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/ADT/SmallVector.h(329): note: see reference to class template instantiation 'llvm::is_trivially_move_constructible<T>' being compiled\r\n        with\r\n        [\r\n            T=std::unique_ptr<mlir::Region,std::default_delete<mlir::Region>>\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/Support/type_traits.h(79): warning C4624: 'llvm::detail::copy_construction_triviality_helper<T>': destructor was implicitly defined as deleted\r\n        with\r\n        [\r\n            T=mlir::Diagnostic\r\n        ]\r\nC:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\include\\type_traits(631): note: see reference to class template instantiation 'llvm::detail::copy_construction_triviality_helper<T>' being compiled\r\n        with\r\n        [\r\n            T=mlir::Diagnostic\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/Support/type_traits.h(100): note: see reference to class template instantiation 'std::is_copy_constructible<llvm::detail::copy_construction_triviality_helper<T>>' being compiled\r\n        with\r\n        [\r\n            T=mlir::Diagnostic\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/ADT/Optional.h(51): note: see reference to class template instantiation 'llvm::is_trivially_copy_constructible<T>' being compiled\r\n        with\r\n        [\r\n            T=mlir::Diagnostic\r\n        ]\r\nexternal/llvm-project/mlir/include\\mlir/IR/Diagnostics.h(396): note: see reference to class template instantiation 'llvm::Optional<mlir::Diagnostic>' being compiled\r\nexternal/llvm-project/llvm/include\\llvm/Support/type_traits.h(86): warning C4624: 'llvm::detail::move_construction_triviality_helper<T>': destructor was implicitly defined as deleted\r\n        with\r\n        [\r\n            T=mlir::Diagnostic\r\n        ]\r\nC:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\include\\type_traits(662): note: see reference to class template instantiation 'llvm::detail::move_construction_triviality_helper<T>' being compiled\r\n        with\r\n        [\r\n            T=mlir::Diagnostic\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/Support/type_traits.h(111): note: see reference to class template instantiation 'std::is_move_constructible<llvm::detail::move_construction_triviality_helper<T>>' being compiled\r\n        with\r\n        [\r\n            T=mlir::Diagnostic\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/ADT/Optional.h(51): note: see reference to class template instantiation 'llvm::is_trivially_move_constructible<T>' being compiled\r\n        with\r\n        [\r\n            T=mlir::Diagnostic\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/Support/type_traits.h(79): warning C4624: 'llvm::detail::copy_construction_triviality_helper<T>': destructor was implicitly defined as deleted\r\n        with\r\n        [\r\n            T=mlir::SymbolTable::UseRange\r\n        ]\r\nC:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\include\\type_traits(631): note: see reference to class template instantiation 'llvm::detail::copy_construction_triviality_helper<T>' being compiled\r\n        with\r\n        [\r\n            T=mlir::SymbolTable::UseRange\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/Support/type_traits.h(100): note: see reference to class template instantiation 'std::is_copy_constructible<llvm::detail::copy_construction_triviality_helper<T>>' being compiled\r\n        with\r\n        [\r\n            T=mlir::SymbolTable::UseRange\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/ADT/Optional.h(51): note: see reference to class template instantiation 'llvm::is_trivially_copy_constructible<T>' being compiled\r\n        with\r\n        [\r\n            T=mlir::SymbolTable::UseRange\r\n        ]\r\nbazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/SymbolInterfacesIncGen\\mlir/IR/SymbolInterfaces.h.inc(216): note: see reference to class template instantiation 'llvm::Optional<mlir::SymbolTable::UseRange>' being compiled\r\nbazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/SymbolInterfacesIncGen\\mlir/IR/SymbolInterfaces.h.inc(279): note: see reference to class template instantiation 'mlir::detail::SymbolOpInterfaceTrait<ConcreteOp>' being compiled\r\nexternal/llvm-project/llvm/include\\llvm/Support/type_traits.h(86): warning C4624: 'llvm::detail::move_construction_triviality_helper<T>': destructor was implicitly defined as deleted\r\n        with\r\n        [\r\n            T=mlir::SymbolTable::UseRange\r\n        ]\r\nC:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\include\\type_traits(662): note: see reference to class template instantiation 'llvm::detail::move_construction_triviality_helper<T>' being compiled\r\n        with\r\n        [\r\n            T=mlir::SymbolTable::UseRange\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/Support/type_traits.h(111): note: see reference to class template instantiation 'std::is_move_constructible<llvm::detail::move_construction_triviality_helper<T>>' being compiled\r\n        with\r\n        [\r\n            T=mlir::SymbolTable::UseRange\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/ADT/Optional.h(51): note: see reference to class template instantiation 'llvm::is_trivially_move_constructible<T>' being compiled\r\n        with\r\n        [\r\n            T=mlir::SymbolTable::UseRange\r\n        ]\r\nexternal/org_tensorflow\\tensorflow/tsl/profiler/lib/traceme_encode.h(49): warning C4141: 'inline': used more than once\r\nexternal/org_tensorflow\\tensorflow/tsl/profiler/lib/traceme_encode.h(62): warning C4141: 'inline': used more than once\r\nexternal/org_tensorflow\\tensorflow/tsl/profiler/lib/traceme_encode.h(87): warning C4141: 'inline': used more than once\r\nexternal/org_tensorflow\\tensorflow/tsl/profiler/lib/traceme_encode.h(108): warning C4141: 'inline': used more than once\r\nexternal/org_tensorflow\\tensorflow/tsl/profiler/lib/traceme_encode.h(112): warning C4141: 'inline': used more than once\r\nexternal/org_tensorflow\\tensorflow/tsl/profiler/lib/traceme_encode.h(116): warning C4141: 'inline': used more than once\r\nexternal/org_tensorflow\\tensorflow/tsl/profiler/lib/traceme_encode.h(129): warning C4141: 'inline': used more than once\r\nexternal/org_tensorflow\\tensorflow/tsl/profiler/lib/traceme_encode.h(135): warning C4141: 'inline': used more than once\r\nexternal/org_tensorflow\\tensorflow/tsl/profiler/lib/traceme_encode.h(140): warning C4141: 'inline': used more than once\r\nexternal/org_tensorflow\\tensorflow/tsl/profiler/lib/traceme_encode.h(145): warning C4141: 'inline': used more than once\r\nexternal/org_tensorflow\\tensorflow/tsl/profiler/lib/traceme_encode.h(152): warning C4141: 'inline': used more than once\r\nexternal/org_tensorflow\\tensorflow/tsl/profiler/lib/traceme_encode.h(157): warning C4141: 'inline': used more than once\r\nexternal/org_tensorflow/tensorflow/compiler/xla/python/jax_jit.cc(808): warning C5101: use of preprocessor directive in function-like macro argument list is undefined behavior\r\nexternal/org_tensorflow/tensorflow/compiler/xla/python/jax_jit.cc(810): warning C5101: use of preprocessor directive in function-like macro argument list is undefined behavior\r\nexternal/org_tensorflow/tensorflow/compiler/xla/python/jax_jit.cc(806): error C2059: syntax error: '#'\r\nexternal/org_tensorflow/tensorflow/compiler/xla/python/jax_jit.cc(811): error C3536: '_status_or_value10': cannot be used before it is initialized\r\nexternal/org_tensorflow/tensorflow/compiler/xla/python/jax_jit.cc(806): error C2512: 'xla::DevicePutResult': no appropriate default constructor available\r\nexternal/org_tensorflow\\tensorflow/compiler/xla/python/py_values.h(33): note: see declaration of 'xla::DevicePutResult'\r\n"
Traceback (most recent call last):
  File "C:\sdks\jax-jaxlib-v0.4.1\build\build.py", line 567, in <module>
    main()
  File "C:\sdks\jax-jaxlib-v0.4.1\build\build.py", line 562, in main
    shell(command)
  File "C:\sdks\jax-jaxlib-v0.4.1\build\build.py", line 53, in shell
    output = subprocess.check_output(cmd)
  File "C:\Users\Adam\anaconda3\envs\jax_latest\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\Adam\anaconda3\envs\jax_latest\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['.\\bazel-5.1.1-windows-x86_64.exe', 'run', '--verbose_failures=true', ':build_wheel', '--', '--output_path=C:\\sdks\\jax-jaxlib-v0.4.1\\dist', '--cpu=AMD64']' returned non-zero exit status 1.
```

### What jax/jaxlib version are you using?

Jaxlib v0.4.1

### Additional system info

Windows 10, Python 3.9, Cuda 11.7, Cudnn 8.4.0

**Comment by nrwahl2** [comment]
Cleaning up the errors a bit:
```
external/org_tensorflow/tensorflow/compiler/xla/python/jax_jit.cc(808): warning C5101: use of preprocessor directive in function-like macro argument list is undefined behavior
external/org_tensorflow/tensorflow/compiler/xla/python/jax_jit.cc(810): warning C5101: use of preprocessor directive in function-like macro argument list is undefined behavior
external/org_tensorflow/tensorflow/compiler/xla/python/jax_jit.cc(806): error C2059: syntax error: '#'
external/org_tensorflow/tensorflow/compiler/xla/python/jax_jit.cc(811): error C3536: '_status_or_value10': cannot be used before it is initialized
external/org_tensorflow/tensorflow/compiler/xla/python/jax_jit.cc(806): error C2512: 'xla::DevicePutResult': no appropriate default constructor available
external/org_tensorflow\\tensorflow/compiler/xla/python/py_values.h(33): note: see declaration of 'xla::DevicePutResult'
```

The relevant snippet from the TensorFlow version pinned for jaxlib v0.4.1 is [here](https://github.com/tensorflow/tensorflow/blob/f3cc513887e06150b6f870c522220dabedc58920/tensorflow/compiler/xla/python/jax_jit.cc#L806-L811):
```
    TF_ASSIGN_OR_RETURN(xla::DevicePutResult on_device,
                        DevicePut(arg,
#ifdef JAX_ENABLE_IFRT
                                  arguments.ifrt_client,
#endif
                                  data_device, options));
```

The compiler didn't like the use of preprocessor directives (`#ifdef`, `#endif`) within the macro arguments. Commit [f01b09d8](https://github.com/tensorflow/tensorflow/commit/f01b09d8) removed them, a week after the release of jaxlib v0.4.1. So this should be fixed in future versions.

I'm new here, poking at a "contributions welcome" issue. I'm not sure what the protocol is when a build bug is found in an existing release. You can probably work around it by overriding the pinned TensorFlow version with a newer one as described here: https://jax.readthedocs.io/en/latest/developer.html#building-jaxlib-from-source-with-a-modified-tensorflow-repository

**Comment by adam-hartshorne** [comment]
I have tried using the more recent TF with this change and it does fix this particular issue. Unfortunately, there is a second issue that remains (when trying to build 0.4.1).

TPU file included in build even when tpu enabled set to false.
https://github.com/google/jax/issues/13871

**Comment by hawkinsp** [comment]
Closing, since it seems likely this is stale.
