### ISSUE TITLE
pmap inside jit causes assert not ragged assertion

### ISSUE THREAD

**Issue by cvjjm** [google/jax#13931]
### Description

I am aware that it may not be a good idea to use `pmap` inside `jit` https://github.com/google/jax/issues/2926 but I want to use `pmap` inside the cost function passed to `jax.numpy.linalg.cg()` and which jit compiles it for me, so I have no choice...

Running the following minimal example on 16 Tesla V100 GPUs demonstrates the problem (here I jit manually):
```
import jax
from jax import numpy as np
from jax import lax

for batches in [
        [np.ones((2, 2)), np.ones((14, 1))], # works
        [np.ones((3, 2))],                   # works
        [np.ones((13, 1))],                  # works
        [np.ones((13, 1)), np.ones((3, 2))], # pmap fails
]:
    def compute_batch(batch):
        return np.ones((7))

    @jax.jit
    def pmap_over_batches(batches):
        ret = [
            jax.pmap(
                compute_batch,
                devices=jax.devices()[:len(batch)],
                )(batch).flatten()
            for batch in batches
        ]
        return ret

    pmap_ret = pmap_over_batches(batches)
    print("pmap done", [batch.shape for batch in batches], pmap_ret)

```
The third value in the for loop triggers a `assert not ragged` assertion 

```
Traceback (most recent call last):
  File "test_pmap.py", line 39, in <module>
    pmap_ret = pmap_over_batches(batches)
  File "test_pmap.py", line 28, in pmap_over_batches
    ret = [
  File "test_pmap.py", line 29, in <listcomp>
    jax.pmap(
jax._src.source_info_util.JaxStackTraceBeforeTransformation: AssertionError

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test_pmap.py", line 39, in <module>
    pmap_ret = pmap_over_batches(batches)
  File "/.../lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/.../lib/python3.8/site-packages/jax/_src/api.py", line 473, in cache_miss
    out_flat = xla.xla_call(
  File "/.../lib/python3.8/site-packages/jax/core.py", line 1767, in bind
    return call_bind(self, fun, *args, **params)
  File "/.../lib/python3.8/site-packages/jax/core.py", line 1783, in call_bind
    outs = top_trace.process_call(primitive, fun_, tracers, params)
  File "/.../lib/python3.8/site-packages/jax/core.py", line 680, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/.../lib/python3.8/site-packages/jax/_src/dispatch.py", line 182, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, name, donated_invars,
  File "/.../lib/python3.8/site-packages/jax/linear_util.py", line 285, in memoized_fun
    ans = call(fun, *args)
  File "/.../lib/python3.8/site-packages/jax/_src/dispatch.py", line 230, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars, False,
  File "/.../lib/python3.8/site-packages/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/.../lib/python3.8/site-packages/jax/_src/dispatch.py", line 340, in lower_xla_callable
    module, keepalive = mlir.lower_jaxpr_to_module(
  File "/.../lib/python3.8/site-packages/jax/interpreters/mlir.py", line 546, in lower_jaxpr_to_module
    lower_jaxpr_to_fun(
  File "/.../lib/python3.8/site-packages/jax/interpreters/mlir.py", line 800, in lower_jaxpr_to_fun
    out_vals, tokens_out = jaxpr_subcomp(ctx.replace(name_stack=callee_name_stack),
  File "/.../lib/python3.8/site-packages/jax/interpreters/mlir.py", line 918, in jaxpr_subcomp
    ans = rule(rule_ctx, *map(_unwrap_singleton_ir_values, in_nodes),
  File "/.../lib/python3.8/site-packages/jax/interpreters/pxla.py", line 1700, in _pmap_lowering
    outs = [_mhlo_unshard(aval, new_env, out_axis, shard,
  File "/.../lib/python3.8/site-packages/jax/interpreters/pxla.py", line 1700, in <listcomp>
    outs = [_mhlo_unshard(aval, new_env, out_axis, shard,
  File "/.../lib/python3.8/site-packages/jax/interpreters/pxla.py", line 1649, in _mhlo_unshard
    xla.axis_groups(axis_env, axis_env.names[-1]))
  File "/.../lib/python3.8/site-packages/jax/interpreters/xla.py", line 360, in axis_groups
    assert not ragged
jax._src.traceback_util.UnfilteredStackTrace: AssertionError

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test_pmap.py", line 39, in <module>
    pmap_ret = pmap_over_batches(batches)
AssertionError

```

very similar to the one reported here for `scan` https://github.com/google/jax/issues/2018 . Other batch shapes also trigger the error. Some work, some don't. I wasn't able to find any pattern.

Because of the advice here https://github.com/google/jax/issues/13858 I have also tried v0.3.10 but got the same result as on v0.4.1.

### What jax/jaxlib version are you using?

jax 0.4.1, jaxlib 0.4.1+cuda11.cudnn86

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.8.12, Linux

**Comment by mattjj** [comment]
Thanks for raising this, with the clear reproducer!

The issue is that we compute the number of replicas needed by the `jit`ted computation with a [`max` over all the numbers of replicas needed by each pmap inside it](https://github.com/google/jax/blob/7788f0cf6bd013052ffb73aa91bee0752d909733/jax/_src/dispatch.py#L639), but actually we need a least common multiple.

Here's another reproducer:

```python
import jax
import jax.numpy as jnp

@jax.jit
def f():
  a = jax.pmap(lambda x: x)(jnp.arange(2))
  b = jax.pmap(lambda x: x)(jnp.arange(3))
  return a, b

f()
```

**Comment by mattjj** [comment]
Actually, we don't really need a least-common-multiple here. We just need that for nested pmaps; having a max across separate pmaps is right. So the #13938 fix isn't ideal yet: it'll pass these tests, but require too many devices. For example, for the code in the OP to run would require lcm(3, 13) = 39 devices.

But the 'axis_groups' calculations we perform while lowering to HLO _do_ currently require this least-common-multiple logic. So to require fewer devices, we'll need to adapt that logic to create unevenly sized axis groups. (That's basically what the assertion is checking will never happen.)

**Comment by mattjj** [comment]
> but I want to use pmap inside the cost function passed to jax.numpy.linalg.cg() and which jit compiles it for me, so I have no choice...

You meant `jax.scipy.sparse.linalg.cg` right?

**Comment by cvjjm** [comment]
Awesome! Thanks for looking into this so quickly! Yes I mean `jax.scipy.sparse.linalg.cg`.

I was under the impression that the number of devices must match the 0th axis of `batch`, so for the case `[np.ones((13, 1)), np.ones((3, 2))]` the frst `pmap` in the list comprehension would run on 13 devices and the second on 3.
Is that no longer true after the function has been jit compiled? 

In the actual use case I have a function that needs to compute a number of things that are not a multiple of the number of devices with `pmap` inside the cost function passed to `jax.scipy.sparse.linalg.cg`. I want to do that by calling `pmap` twice. Once with a batch whose 0th axis is equal to the number of devices and then a second call to spread the computation of the remained over a subset of devices.

**Comment by cvjjm** [comment]
Is there any chance of getting a full fix for this, which also solves the problem of requiring an excessive amount of devices? Or maybe a workaround how `pmap` could be called from a `jit` compiled function that avoids the problem in the first place? Thanks very much for your time and effort!

**Comment by mattjj** [comment]
Verified at head: the internal `assert not ragged` failure is gone. The single-pmap-inside-jit cases from the repro now work. Mixing two pmaps over *different* device subsets inside one jit now raises an intentional, clear error ("Received incompatible devices for jitted computation...") rather than an internal assertion. That pattern isn't supported (pmap is implemented via shard_map these days; use shard_map directly for anything fancy). Closing since the internal-assertion bug is fixed.
