### ISSUE TITLE
Bazel Build Failed because it can't identify Python path

### ISSUE THREAD

**Issue by timelessnesses** [google/jax#14012]
### Description

I tried to using jax today and saw that I need to locally build this.  
So I did and Bazel said it can't find my python binary.
```
jax on  main via 🐍 v3.9.7 took 25s
❯ py -3.10 .\build\build.py

     _   _  __  __
    | | / \ \ \/ /
 _  | |/ _ \ \  /
| |_| / ___ \/  \
 \___/_/   \/_/\_\


Bazel binary path: C:\Users\moopi\scoop\shims\bazel.EXE
Bazel version: 5.3.2
Python binary path: C:/Users/moopi/AppData/Local/Programs/Python/Python310/python.exe
Python version: 3.10
NumPy version: 1.24.1
MKL-DNN enabled: yes
Target CPU: AMD64
Target CPU features: release
CUDA enabled: no
TPU enabled: no
Remote TPU enabled: no
ROCm enabled: no
Plugin device enabled: no

Building XLA and installing it in the jaxlib source tree...
C:\Users\moopi\scoop\shims\bazel.EXE run --verbose_failures=true :build_wheel -- --output_path=F:\Desktop\jax\dist --cpu=AMD64
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=133
INFO: Reading rc options for 'run' from f:\desktop\jax\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  Inherited 'build' options: --python_path=F:/Python/python.exe
INFO: Reading rc options for 'run' from f:\desktop\jax\.bazelrc:
  Inherited 'build' options: --apple_platform_type=macos --macos_minimum_os=10.14 --announce_rc --define open_source_build=true --spawn_strategy=standalone --enable_platform_specific_config --experimental_cc_shared_library --define=no_aws_support=true --define=no_gcp_support=true --define=no_hdfs_support=true --define=no_kafka_support=true --define=no_ignite_support=true --define=grpc_no_ares=true --define=tsl_link_protobuf=true -c opt --config=short_logs --copt=-DMLIR_PYTHON_PACKAGE_PREFIX=jaxlib.mlir. --@org_tensorflow//tensorflow/compiler/xla/python:enable_gpu=false --@org_tensorflow//tensorflow/compiler/xla/python:enable_tpu=false --@org_tensorflow//tensorflow/compiler/xla/python:enable_plugin_device=false
INFO: Reading rc options for 'run' from f:\desktop\jax\.jax_configure.bazelrc:
  Inherited 'build' options: --strategy=Genrule=standalone --repo_env PYTHON_BIN_PATH=C:/Users/moopi/AppData/Local/Programs/Python/Python310/python.exe --action_env=PYENV_ROOT --python_path=C:/Users/moopi/AppData/Local/Programs/Python/Python310/python.exe --distinct_host_configuration=false --config=mkl_open_source_only
INFO: Found applicable config definition build:short_logs in file f:\desktop\jax\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:mkl_open_source_only in file f:\desktop\jax\.bazelrc: --define=tensorflow_mkldnn_contraction_kernel=1
INFO: Found applicable config definition build:windows in file f:\desktop\jax\.bazelrc: --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/Zc:preprocessor --cxxopt=/std:c++17 --host_cxxopt=/std:c++17 --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --incompatible_strict_action_env=true
INFO: Build option --python_path has changed, discarding analysis cache.
INFO: Repository local_execution_config_python instantiated at:
  F:/desktop/jax/WORKSPACE:38:14: in <toplevel>
  C:/users/moopi/_bazel_moopi/nlmg3mro/external/org_tensorflow/tensorflow/workspace2.bzl:945:19: in workspace
  C:/users/moopi/_bazel_moopi/nlmg3mro/external/org_tensorflow/tensorflow/workspace2.bzl:91:27: in _tf_toolchains
  C:/users/moopi/_bazel_moopi/nlmg3mro/external/org_tensorflow/tensorflow/tools/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  C:/users/moopi/_bazel_moopi/nlmg3mro/external/org_tensorflow/tensorflow/tools/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  C:/users/moopi/_bazel_moopi/nlmg3mro/external/org_tensorflow/third_party/py/python_configure.bzl:279:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/moopi/_bazel_moopi/nlmg3mro/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/users/moopi/_bazel_moopi/nlmg3mro/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "C:/users/moopi/_bazel_moopi/nlmg3mro/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C:/Users/moopi/AppData/Local/Programs/Python/Python310/python.exe' is not executable. Is it the python binary?
ERROR: F:/desktop/jax/WORKSPACE:38:14: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last):
        File "C:/users/moopi/_bazel_moopi/nlmg3mro/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/users/moopi/_bazel_moopi/nlmg3mro/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "C:/users/moopi/_bazel_moopi/nlmg3mro/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C:/Users/moopi/AppData/Local/Programs/Python/Python310/python.exe' is not executable. Is it the python binary?
INFO: Repository go_sdk instantiated at:
  F:/desktop/jax/WORKSPACE:44:14: in <toplevel>
  C:/users/moopi/_bazel_moopi/nlmg3mro/external/org_tensorflow/tensorflow/workspace0.bzl:134:20: in workspace
  C:/users/moopi/_bazel_moopi/nlmg3mro/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:36:27: in grpc_extra_deps
  C:/users/moopi/_bazel_moopi/nlmg3mro/external/io_bazel_rules_go/go/private/sdk.bzl:431:28: in go_register_toolchains
  C:/users/moopi/_bazel_moopi/nlmg3mro/external/io_bazel_rules_go/go/private/sdk.bzl:130:21: in go_download_sdk
Repository rule _go_download_sdk defined at:
  C:/users/moopi/_bazel_moopi/nlmg3mro/external/io_bazel_rules_go/go/private/sdk.bzl:117:35: in <toplevel>
ERROR: Analysis of target '//build:build_wheel' failed; build aborted: Configuration Error: --define PYTHON_BIN_PATH='C:/Users/moopi/AppData/Local/Programs/Python/Python310/python.exe' is not executable. Is it the python binary?
INFO: Elapsed time: 7.145s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (33 packages loaded, 10 targets configured)
FAILED: Build did NOT complete successfully (33 packages loaded, 10 targets configured)
    Fetching @local_config_python; fetching
b''
Traceback (most recent call last):
  File "F:\Desktop\jax\build\build.py", line 567, in <module>
    main()
  File "F:\Desktop\jax\build\build.py", line 562, in main
    shell(command)
  File "F:\Desktop\jax\build\build.py", line 53, in shell
    output = subprocess.check_output(cmd)
  File "C:\Users\moopi\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\moopi\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\moopi\\scoop\\shims\\bazel.EXE', 'run', '--verbose_failures=true', ':build_wheel', '--', '--output_path=F:\\Desktop\\jax\\dist', '--cpu=AMD64']' returned non-zero exit status 1.
```
Did tried this on 3.10 and also failed

### What jax/jaxlib version are you using?

jax 0.4.1 and jaxlib commit d203926c16a98cf87e88bf090098e6372267b8b2

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.9/3.10, Windows 10

**Comment by hawkinsp** [comment]
JAX on Windows is community-supported. So we'll accept patches to fix it if it breaks but we don't promise anything about it ourselves.

Is this message relevant/correct?
```
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C:/Users/moopi/AppData/Local/Programs/Python/Python310/python.exe' is not executable. Is it the python binary?
```
