### ISSUE TITLE
Tensorflow archive checksums do not match when building from source.

### ISSUE THREAD

**Issue by oursland** [google/jax#14213]
### Description

Observed earlier today on an internal CI build was a build failure for v0.3.25 due to tensorflow checksum error.  Attempting to upgrade to the latest v0.4.2 results in the same error (with different checksums, of course).  Notably:

WARNING: Download from https://github.com/tensorflow/tensorflow/archive/bbabe41b20327819d2472425d43178c35ce2b1bf.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was **d547203e0e1de2cabd6e68c312441d421285409c18cd161f0721c7cf86dfb314** but wanted **eee3984f41375d438c18fdfae71f66673a35cefe883ef309f4c6a9a4ffc16218**.

Manually downloading and checksumming has confirmed that the current artifacts do not match the expected sha256sum.

Build log below:

```shell
#8 [build 3/3] RUN git clone --depth=1 https://github.com/google/jax -b jax-v0.4.2 &&     cd jax &&     /venv/bin/pip install numpy wheel &&     /venv/bin/python build/build.py
#8 sha256:595eaede8f7ec52e88fd1062586ea3d231e154cc92f3cd276bce0711c5b361e7
#8 0.210 Cloning into 'jax'...
#8 3.253 Note: switching to '838bc454895ed2086563301936fb0d6d852fd198'.
#8 3.253 
#8 3.253 You are in 'detached HEAD' state. You can look around, make experimental
#8 3.253 changes and commit them, and you can discard any commits you make in this
#8 3.253 state without impacting any branches by switching back to a branch.
#8 3.253 
#8 3.253 If you want to create a new branch to retain commits you create, you may
#8 3.253 do so (now or later) by using -c with the switch command. Example:
#8 3.253 
#8 3.253   git switch -c <new-branch-name>
#8 3.253 
#8 3.253 Or undo this operation with:
#8 3.253 
#8 3.253   git switch -
#8 3.253 
#8 3.253 Turn off this advice by setting config variable advice.detachedHead to false
#8 3.253 
#8 3.837 Collecting numpy
#8 4.550   Downloading numpy-1.24.1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (14.0 MB)
#8 5.207      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 22.5 MB/s eta 0:00:00
#8 5.267 Collecting wheel
#8 5.595   Downloading wheel-0.38.4-py3-none-any.whl (36 kB)
#8 5.606 Installing collected packages: wheel, numpy
#8 6.675 Successfully installed numpy-1.24.1 wheel-0.38.4
#8 14.38 Extracting Bazel installation...
#8 16.64 Starting local Bazel server and connecting to it...
#8 17.51 INFO: Options provided by the client:
#8 17.51   Inherited 'common' options: --isatty=0 --terminal_columns=80
#8 17.51 INFO: Reading rc options for 'run' from /jax/.bazelrc:
#8 17.51   Inherited 'common' options: --experimental_repo_remote_exec
#8 17.51 INFO: Reading rc options for 'run' from /jax/.bazelrc:
#8 17.51   Inherited 'build' options: --apple_platform_type=macos --macos_minimum_os=10.14 --announce_rc --define open_source_build=true --spawn_strategy=standalone --enable_platform_specific_config --experimental_cc_shared_library --define=no_aws_support=true --define=no_gcp_support=true --define=no_hdfs_support=true --define=no_kafka_support=true --define=no_ignite_support=true --define=grpc_no_ares=true --define=tsl_link_protobuf=true -c opt --config=short_logs --copt=-DMLIR_PYTHON_PACKAGE_PREFIX=jaxlib.mlir. --@org_tensorflow//tensorflow/compiler/xla/python:enable_gpu=false --@org_tensorflow//tensorflow/compiler/xla/python:enable_tpu=false --@org_tensorflow//tensorflow/compiler/xla/python:enable_plugin_device=false
#8 17.51 INFO: Reading rc options for 'run' from /jax/.jax_configure.bazelrc:
#8 17.51   Inherited 'build' options: --strategy=Genrule=standalone --repo_env PYTHON_BIN_PATH=/venv/bin/python --action_env=PYENV_ROOT --python_path=/venv/bin/python --distinct_host_configuration=false --config=mkl_open_source_only
#8 17.51 INFO: Found applicable config definition build:short_logs in file /jax/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
#8 17.51 INFO: Found applicable config definition build:mkl_open_source_only in file /jax/.bazelrc: --define=tensorflow_mkldnn_contraction_kernel=1
#8 17.51 INFO: Found applicable config definition build:linux in file /jax/.bazelrc: --config=posix --copt=-Wno-unknown-warning-option --copt=-Wno-stringop-truncation --copt=-Wno-array-parameter
#8 17.51 INFO: Found applicable config definition build:posix in file /jax/.bazelrc: --copt=-fvisibility=hidden --copt=-Wno-sign-compare --cxxopt=-std=c++17 --host_cxxopt=-std=c++17
#8 29.42 INFO: Repository org_tensorflow instantiated at:
#8 29.42   /jax/WORKSPACE:8:13: in <toplevel>
#8 29.42 Repository rule http_archive defined at:
#8 29.42   /root/.cache/bazel/_bazel_root/bee4ad1fd43279be7a03b33426e824d5/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
#8 29.42 WARNING: Download from https://github.com/tensorflow/tensorflow/archive/bbabe41b20327819d2472425d43178c35ce2b1bf.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was d547203e0e1de2cabd6e68c312441d421285409c18cd161f0721c7cf86dfb314 but wanted eee3984f41375d438c18fdfae71f66673a35cefe883ef309f4c6a9a4ffc16218
#8 29.42 ERROR: An error occurred during the fetch of repository 'org_tensorflow':
#8 29.42    Traceback (most recent call last):
#8 29.42        File "/root/.cache/bazel/_bazel_root/bee4ad1fd43279be7a03b33426e824d5/external/bazel_tools/tools/build_defs/repo/http.bzl", line 100, column 45, in _http_archive_impl
#8 29.42                download_info = ctx.download_and_extract(
#8 29.42 Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/tensorflow/tensorflow/archive/bbabe41b20327819d2472425d43178c35ce2b1bf.tar.gz] to /root/.cache/bazel/_bazel_root/bee4ad1fd43279be7a03b33426e824d5/external/org_tensorflow/temp6049807858397632604/bbabe41b20327819d2472425d43178c35ce2b1bf.tar.gz: Checksum was d547203e0e1de2cabd6e68c312441d421285409c18cd161f0721c7cf86dfb314 but wanted eee3984f41375d438c18fdfae71f66673a35cefe883ef309f4c6a9a4ffc16218
#8 29.42 ERROR: /jax/WORKSPACE:8:13: fetching http_archive rule //external:org_tensorflow: Traceback (most recent call last):
#8 29.42        File "/root/.cache/bazel/_bazel_root/bee4ad1fd43279be7a03b33426e824d5/external/bazel_tools/tools/build_defs/repo/http.bzl", line 100, column 45, in _http_archive_impl
#8 29.42                download_info = ctx.download_and_extract(
#8 29.42 Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/tensorflow/tensorflow/archive/bbabe41b20327819d2472425d43178c35ce2b1bf.tar.gz] to /root/.cache/bazel/_bazel_root/bee4ad1fd43279be7a03b33426e824d5/external/org_tensorflow/temp6049807858397632604/bbabe41b20327819d2472425d43178c35ce2b1bf.tar.gz: Checksum was d547203e0e1de2cabd6e68c312441d421285409c18cd161f0721c7cf86dfb314 but wanted eee3984f41375d438c18fdfae71f66673a35cefe883ef309f4c6a9a4ffc16218
#8 29.44 INFO: Reading rc options for 'run' from /jax/.bazelrc:
#8 29.44   Inherited 'build' options: --apple_platform_type=macos --macos_minimum_os=10.14 --announce_rc --define open_source_build=true --spawn_strategy=standalone --enable_platform_specific_config --experimental_cc_shared_library --define=no_aws_support=true --define=no_gcp_support=true --define=no_hdfs_support=true --define=no_kafka_support=true --define=no_ignite_support=true --define=grpc_no_ares=true --define=tsl_link_protobuf=true -c opt --config=short_logs --copt=-DMLIR_PYTHON_PACKAGE_PREFIX=jaxlib.mlir. --@org_tensorflow//tensorflow/compiler/xla/python:enable_gpu=false --@org_tensorflow//tensorflow/compiler/xla/python:enable_tpu=false --@org_tensorflow//tensorflow/compiler/xla/python:enable_plugin_device=false
#8 29.44 ERROR: @org_tensorflow//tensorflow/compiler/xla/python:enable_gpu :: Error loading option @org_tensorflow//tensorflow/compiler/xla/python:enable_gpu: no such package '@org_tensorflow//tensorflow': java.io.IOException: Error downloading [https://github.com/tensorflow/tensorflow/archive/bbabe41b20327819d2472425d43178c35ce2b1bf.tar.gz] to /root/.cache/bazel/_bazel_root/bee4ad1fd43279be7a03b33426e824d5/external/org_tensorflow/temp6049807858397632604/bbabe41b20327819d2472425d43178c35ce2b1bf.tar.gz: Checksum was d547203e0e1de2cabd6e68c312441d421285409c18cd161f0721c7cf86dfb314 but wanted eee3984f41375d438c18fdfae71f66673a35cefe883ef309f4c6a9a4ffc16218
#8 29.46 Traceback (most recent call last):
#8 29.46   File "/jax/build/build.py", line 567, in <module>
#8 29.46 
#8 29.46      _   _  __  __
#8 29.46     | | / \ \ \/ /
#8 29.46  _  | |/ _ \ \  /
#8 29.46 | |_| / ___ \/  \
#8 29.46  \___/_/   \/_/\_\
#8 29.46 
#8 29.46 
#8 29.46 Downloading bazel from: https://github.com/bazelbuild/bazel/releases/download/5.1.1/bazel-5.1.1-linux-arm64
#8 29.46 
#8 29.46 Bazel binary path: ./bazel-5.1.1-linux-arm64
#8 29.46 Bazel version: 5.1.1
#8 29.46 Python binary path: /venv/bin/python
#8 29.46 Python version: 3.9
#8 29.46 NumPy version: 1.24.1
#8 29.46 MKL-DNN enabled: yes
#8 29.46 Target CPU: aarch64
#8 29.46 Target CPU features: release
#8 29.46 CUDA enabled: no
#8 29.46 TPU enabled: no
#8 29.46 Remote TPU enabled: no
#8 29.46 ROCm enabled: no
#8 29.46 Plugin device enabled: no
#8 29.46 
#8 29.46 Building XLA and installing it in the jaxlib source tree...
#8 29.46 ./bazel-5.1.1-linux-arm64 run --verbose_failures=true :build_wheel -- --output_path=/jax/dist --cpu=aarch64
#8 29.46 b''
#8 29.46     main()
#8 29.46   File "/jax/build/build.py", line 562, in main
#8 29.46     shell(command)
#8 29.46   File "/jax/build/build.py", line 53, in shell
#8 29.46     output = subprocess.check_output(cmd)
#8 29.46   File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
#8 29.46     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
#8 29.46   File "/usr/lib/python3.9/subprocess.py", line 528, in run
#8 29.46     raise CalledProcessError(retcode, process.args,
#8 29.46 subprocess.CalledProcessError: Command '['./bazel-5.1.1-linux-arm64', 'run', '--verbose_failures=true', ':build_wheel', '--', '--output_path=/jax/dist', '--cpu=aarch64']' returned non-zero exit status 2.
#8 ERROR: executor failed running [/bin/sh -c git clone --depth=1 https://github.com/google/jax -b jax-${JAX_VERSION} &&     cd jax &&     /venv/bin/pip install numpy wheel &&     /venv/bin/python build/build.py]: exit code: 1

```

### What jax/jaxlib version are you using?

v0.4.2

### Which accelerator(s) are you using?

CPU

### Additional system info

Linux

**Comment by hawkinsp** [comment]
This is https://github.com/orgs/community/discussions/45830 which is being rolled back. We'll look into better caching for the future to mitigate any future problems.
