### ISSUE TITLE
cuSPARSE related test failures

### ISSUE THREAD

**Issue by branfosj** [google/jax#14663]
### Description

I'm seeing seven test failures - all from `tests/sparse_test.py`. There are three different error messages that all relate to cuSPARSE:
1. `On entry to cusparseSpMM_bufferSize(): matrix B and C must be in column-major order`
   * `cuSparseTest.test_coo_matmat1`
   * `cuSparseTest.test_coo_matmat3`
   * `cuSparseTest.test_coo_matmat5`
   * `cuSparseTest.test_coo_sorted_indices_gpu_lowerings`
1. `On entry to cusparseSpMM_bufferSize(): opA != CUSPARSE_OPERATION_NON_TRANSPOSE is not supported with CUSPARSE_SPMM_COO_ALG2`
   * `cuSparseTest.test_coo_matmat6`
   * `cuSparseTest.test_coo_matmat7`
1. `On entry to cusparseSpMM_bufferSize(): CUSPARSE_SPMM_COO_ALG2 does not support 64-bit indices`
   * `cuSparseTest.test_coo_matmat_layout`

For the first one, using the `cuSparseTest.test_coo_matmat_layout` test as an example. Though when running it outside of the testsuite I get the first error from it:
```py
import jax.numpy as jnp
from jax import jit
from jax.experimental.sparse import coo as sparse_coo

d = jnp.array([1.0, 2.0, 3.0, 4.0])
i = jnp.array([0, 0, 1, 2])
j = jnp.array([0, 2, 0, 0])
shape = (3, 3)

x = jnp.arange(9).reshape(3, 3).astype(d.dtype)

def f(x):
  return sparse_coo._coo_matmat(d, i, j, x.T, spinfo=sparse_coo.COOInfo(shape=shape, rows_sorted=True))

result_jit = jit(f)(x)
```

Gets me the traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'jit' is not defined
>>> from jax import jit
>>> result_jit = jit(f)(x)
 ** On entry to cusparseSpMM_bufferSize(): matrix B and C must be in column-major order

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in f
  File "/rds/projects/b/branfosj-bear-apps/devel/2022a/branfosj-1/EL8-ice/software/jax/0.4.4-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/jax/experimental/sparse/coo.py", line 542, in _coo_matmat
    return coo_matmat_p.bind(data, row, col, B, spinfo=spinfo, transpose=transpose)
jax._src.source_info_util.JaxStackTraceBeforeTransformation: RuntimeError: jaxlib/gpu/sparse.cc:538: operation gpusparseSpMM_bufferSize( handle.get(), op_A, GPUSPARSE_OPERATION_NON_TRANSPOSE, &alpha, mat_a,
 mat_b, &beta, mat_c, C.type, GPUSPARSE_SPMM_COO_ALG, &buffer_size) failed: invalid value

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.
--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):                                                                                                                                                                              File "<stdin>", line 1, in <module>
  File "/rds/projects/b/branfosj-bear-apps/devel/2022a/branfosj-1/EL8-ice/software/jax/0.4.4-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/jax/_src/traceback_util.py", line 163, in reraise_with_filter
ed_traceback
    return fun(*args, **kwargs)
  File "/rds/projects/b/branfosj-bear-apps/devel/2022a/branfosj-1/EL8-ice/software/jax/0.4.4-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/jax/_src/pjit.py", line 237, in cache_miss
    outs, out_flat, out_tree, args_flat = _python_pjit_helper(
  File "/rds/projects/b/branfosj-bear-apps/devel/2022a/branfosj-1/EL8-ice/software/jax/0.4.4-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/jax/_src/pjit.py", line 185, in _python_pjit_helper
    out_flat = pjit_p.bind(*args_flat, **params)
  File "/rds/projects/b/branfosj-bear-apps/devel/2022a/branfosj-1/EL8-ice/software/jax/0.4.4-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/jax/_src/core.py", line 2559, in bind
    return self.bind_with_trace(top_trace, args, params)
  File "/rds/projects/b/branfosj-bear-apps/devel/2022a/branfosj-1/EL8-ice/software/jax/0.4.4-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/jax/_src/core.py", line 346, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/rds/projects/b/branfosj-bear-apps/devel/2022a/branfosj-1/EL8-ice/software/jax/0.4.4-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/jax/_src/core.py", line 789, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/rds/projects/b/branfosj-bear-apps/devel/2022a/branfosj-1/EL8-ice/software/jax/0.4.4-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/jax/_src/pjit.py", line 1286, in _pjit_call_impl
    compiled = _pjit_lower(
  File "/rds/projects/b/branfosj-bear-apps/devel/2022a/branfosj-1/EL8-ice/software/jax/0.4.4-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/jax/_src/pjit.py", line 1372, in _pjit_lower
    return _pjit_lower_cached(jaxpr, in_shardings, out_shardings, *args, **kwargs)
  File "/rds/projects/b/branfosj-bear-apps/devel/2022a/branfosj-1/EL8-ice/software/jax/0.4.4-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/jax/_src/pjit.py", line 1437, in _pjit_lower_cached
    return pxla.lower_sharding_computation(
  File "/rds/projects/b/branfosj-bear-apps/devel/2022a/branfosj-1/EL8-ice/software/jax/0.4.4-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/rds/projects/b/branfosj-bear-apps/devel/2022a/branfosj-1/EL8-ice/software/jax/0.4.4-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/jax/_src/interpreters/pxla.py", line 2991, in lower_sharding_
computation
    lowering_result = mlir.lower_jaxpr_to_module(
  File "/rds/projects/b/branfosj-bear-apps/devel/2022a/branfosj-1/EL8-ice/software/jax/0.4.4-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/jax/_src/interpreters/mlir.py", line 739, in lower_jaxpr_to_m
odule
    lower_jaxpr_to_fun(
  File "/rds/projects/b/branfosj-bear-apps/devel/2022a/branfosj-1/EL8-ice/software/jax/0.4.4-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/jax/_src/interpreters/mlir.py", line 1021, in lower_jaxpr_to_
fun
    out_vals, tokens_out = jaxpr_subcomp(ctx.replace(name_stack=callee_name_stack),
  File "/rds/projects/b/branfosj-bear-apps/devel/2022a/branfosj-1/EL8-ice/software/jax/0.4.4-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/jax/_src/interpreters/mlir.py", line 1155, in jaxpr_subcomp
    ans = rule(rule_ctx, *map(_unwrap_singleton_ir_values, in_nodes),
  File "/rds/projects/b/branfosj-bear-apps/devel/2022a/branfosj-1/EL8-ice/software/jax/0.4.4-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/jax/experimental/sparse/coo.py", line 587, in _coo_matmat_gpu
_lowering
    return [coo_matmat_hlo(data, row, col, B, shape=shape,
  File "/rds/projects/b/branfosj-bear-apps/devel/2022a/branfosj-1/EL8-ice/software/jax/0.4.4-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/jaxlib/gpu_sparse.py", line 311, in _coo_matmat_hlo
    buffer_size, opaque = gpu_sparse.build_coo_matmat_descriptor(
jax._src.traceback_util.UnfilteredStackTrace: RuntimeError: jaxlib/gpu/sparse.cc:538: operation gpusparseSpMM_bufferSize( handle.get(), op_A, GPUSPARSE_OPERATION_NON_TRANSPOSE, &alpha, mat_a, mat_b, &beta,
mat_c, C.type, GPUSPARSE_SPMM_COO_ALG, &buffer_size) failed: invalid value

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/rds/projects/b/branfosj-bear-apps/devel/2022a/branfosj-1/EL8-ice/software/jax/0.4.4-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/jax/experimental/sparse/coo.py", line 587, in _coo_matmat_gpu
_lowering
    return [coo_matmat_hlo(data, row, col, B, shape=shape,
  File "/rds/projects/b/branfosj-bear-apps/devel/2022a/branfosj-1/EL8-ice/software/jax/0.4.4-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/jaxlib/gpu_sparse.py", line 311, in _coo_matmat_hlo
    buffer_size, opaque = gpu_sparse.build_coo_matmat_descriptor(
RuntimeError: jaxlib/gpu/sparse.cc:538: operation gpusparseSpMM_bufferSize( handle.get(), op_A, GPUSPARSE_OPERATION_NON_TRANSPOSE, &alpha, mat_a, mat_b, &beta, mat_c, C.type, GPUSPARSE_SPMM_COO_ALG, &buffer
_size) failed: invalid value
```

### What jax/jaxlib version are you using?

0.4.4 for both (compiled from source)

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.10.4, CUDA 11.7.0, cuDNN 8.4.1.50, NCCL 2.12.12

### NVIDIA GPU info

The node used has 4 GPUs, but I am inside a cgroup with access to just one.

```
$ nvidia-smi
Fri Feb 24 09:55:57 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  On   | 00000000:31:00.0 Off |                    0 |
| N/A   31C    P0    72W / 500W |      0MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by branfosj** [comment]
Further debugging: This looks to be a CUDA 11.7.0 issue. If I switch to 11.7.1 then I do not see the failure in the code included above.

From the CUDA 11.7.1 release notes:
> Improved COO cusparseSpMM Alg2 with support for batched computation, custom row/col-major layout for B/C, and mixed-precision computation.

**Comment by jakevdp** [comment]
Thanks for the report! It's proven pretty difficult to write correct lowering code across cusparse versions. Hopefully cusparse will stabilize more in the near future. cc/ @tlu7

**Comment by jakevdp** [comment]
I think this has been addressed.
