### ISSUE TITLE
INTERNAL: RET_CHECK failure

### ISSUE THREAD

**Issue by oslumbers** [google/jax#14801]
### Description

Hi, am getting the following error - I suspect an issue with CudNN / Cuda however have re-installed both multiple times without any luck in improving the situation. 
```
import jax
jax.numpy.zeros(2)

2023-03-06 16:35:33.099150: W external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:397] There was an error before creating cudnn handle: cudaGetErrorName symbol not found. : cudaGetErrorString symbol not found.
2023-03-06 16:35:33.099243: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:429] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2023-03-06 16:35:33.099836: E external/org_tensorflow/tensorflow/compiler/xla/status_macros.cc:57] INTERNAL: RET_CHECK failure (external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_compiler.cc:627) dnn != nullptr 
*** Begin stack trace ***
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	_PyObject_MakeTpCall
	
	_PyEval_EvalFrameDefault
	
	_PyEval_EvalFrameDefault
	
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	
	_PyEval_EvalFrameDefault
	
	_PyFunction_Vectorcall
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	
	_PyFunction_Vectorcall
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	_PyFunction_Vectorcall
	PyObject_Call
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	_PyFunction_Vectorcall
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	_PyFunction_Vectorcall
	
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	_PyEval_EvalFrameDefault
	
	_PyEval_EvalFrameDefault
	
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	_PyEval_EvalFrameDefault
	
	_PyEval_EvalFrameDefault
	
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	
	_PyEval_EvalCodeWithName
	PyEval_EvalCodeEx
	PyEval_EvalCode
	
	
	
	PyRun_InteractiveLoopFlags
	
	
	Py_BytesMain
	
	__libc_start_main
	
*** End stack trace ***

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oslumbers/miniconda3/envs/ens_v4/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 2158, in zeros
    return lax.full(shape, 0, _jnp_dtype(dtype))
  File "/home/oslumbers/miniconda3/envs/ens_v4/lib/python3.9/site-packages/jax/_src/lax/lax.py", line 1245, in full
    return broadcast(fill_value, shape)
  File "/home/oslumbers/miniconda3/envs/ens_v4/lib/python3.9/site-packages/jax/_src/lax/lax.py", line 811, in broadcast
    return broadcast_in_dim(operand, tuple(sizes) + np.shape(operand), dims)
  File "/home/oslumbers/miniconda3/envs/ens_v4/lib/python3.9/site-packages/jax/_src/lax/lax.py", line 839, in broadcast_in_dim
    return broadcast_in_dim_p.bind(
  File "/home/oslumbers/miniconda3/envs/ens_v4/lib/python3.9/site-packages/jax/_src/core.py", line 345, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/home/oslumbers/miniconda3/envs/ens_v4/lib/python3.9/site-packages/jax/_src/core.py", line 348, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/oslumbers/miniconda3/envs/ens_v4/lib/python3.9/site-packages/jax/_src/core.py", line 792, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/oslumbers/miniconda3/envs/ens_v4/lib/python3.9/site-packages/jax/_src/dispatch.py", line 122, in apply_primitive
    compiled_fun = xla_primitive_callable(prim, *unsafe_map(arg_spec, args),
  File "/home/oslumbers/miniconda3/envs/ens_v4/lib/python3.9/site-packages/jax/_src/util.py", line 253, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
  File "/home/oslumbers/miniconda3/envs/ens_v4/lib/python3.9/site-packages/jax/_src/util.py", line 246, in cached
    return f(*args, **kwargs)
  File "/home/oslumbers/miniconda3/envs/ens_v4/lib/python3.9/site-packages/jax/_src/dispatch.py", line 201, in xla_primitive_callable
    compiled = _xla_callable_uncached(lu.wrap_init(prim_fun), device, None,
  File "/home/oslumbers/miniconda3/envs/ens_v4/lib/python3.9/site-packages/jax/_src/dispatch.py", line 354, in _xla_callable_uncached
    return computation.compile(_allow_propagation_to_outputs=allow_prop).unsafe_call
  File "/home/oslumbers/miniconda3/envs/ens_v4/lib/python3.9/site-packages/jax/_src/interpreters/pxla.py", line 3322, in compile
    executable = self._compile_unloaded(
  File "/home/oslumbers/miniconda3/envs/ens_v4/lib/python3.9/site-packages/jax/_src/interpreters/pxla.py", line 3293, in _compile_unloaded
    return UnloadedMeshExecutable.from_hlo(
  File "/home/oslumbers/miniconda3/envs/ens_v4/lib/python3.9/site-packages/jax/_src/interpreters/pxla.py", line 3575, in from_hlo
    xla_executable = dispatch.compile_or_get_cached(
  File "/home/oslumbers/miniconda3/envs/ens_v4/lib/python3.9/site-packages/jax/_src/dispatch.py", line 1085, in compile_or_get_cached
    return backend_compile(backend, serialized_computation, compile_options,
  File "/home/oslumbers/miniconda3/envs/ens_v4/lib/python3.9/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/home/oslumbers/miniconda3/envs/ens_v4/lib/python3.9/site-packages/jax/_src/dispatch.py", line 1030, in backend_compile
    return backend.compile(built_c, compile_options=options)
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: RET_CHECK failure (external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_compiler.cc:627) dnn != nullptr
```
```
nvcc --version
```
![image](https://user-images.githubusercontent.com/40644337/223176255-21a1b488-f969-417e-82e3-1064650501e0.png)

```
cat /usr/local/cuda/include/cudnn_version.h
...
#define CUDNN_MAJOR 8
#define CUDNN_MINOR 8
...
```

### What jax/jaxlib version are you using?

v0.4.4 - but problems persist in other versions

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.9, Ubuntu 22.04

### NVIDIA GPU info

![image](https://user-images.githubusercontent.com/40644337/223174496-89e820ba-561d-4ba0-b3bb-510880b1c21a.png)

**Comment by jakevdp** [comment]
I don't think any of JAX's pre-built wheels have support for CUDA 12 yet; see https://github.com/google/jax/issues/13637

Until that is addressed, you'll have to use a supported CUDA version; see https://github.com/google/jax#pip-installation-gpu-cuda

**Comment by oslumbers** [comment]
@jakevdp, a simple driver downgrade has fixed it! Thanks for pointing that out!
