### ISSUE TITLE
JAX recognizes AMD GPU but can't run JAX functions 

### ISSUE THREAD

**Issue by LRFreeborn** [google/jax#15141]
### Description

ROCm version = 5.3.0
python = 3.11
jax = 0.4.7
jaxlib = 0.4.7
RHEL 8

I built `jaxlib` and `jax` inside a new conda environment. I had to add a `target.lst` file to `$ROCM_PATH/bin` (per #13006 ), but otherwise followed the steps in `build_rocm.sh` without any error.

My command to build the `jaxlib` wheel:
```
python3 ./build/build.py --enable_rocm --rocm_path=${ROCM_PATH} --bazel_options=--override_repository=org_tensorflow=/path/to/my/tensorflow-upstream
```

After the final `pip install` I am able to import `jax` and other libs:
```
>>> import os
>>> import jax.numpy as jnp
>>> from jax import grad, jit, vmap
>>> from jax import random
>>> import numpy as np
>>> from jax.lib import xla_bridge
>>> import time
>>> from timeit import default_timer as timer
>>> from jax import device_put
>>> print(xla_bridge.get_backend().platform)
gpu
```
However, `random.PRNGKey` returns the error `RuntimeError: Unexpected index`. Full stack trace below. 
It's probably worth noting that the same function works when I run on a CPU-only node.

I'm assuming this is a bug, but I'm also open to troubleshooting suggestions. Are there any XLA flags that I should export before invoking the test script?

>>> key = random.PRNGKey(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/curc/sw/install/jax/rocm/5.3.0/0.4.7.b/jax_env/lib/python3.11/site-packages/jax/_src/random.py", line 137, in PRNGKey
    key = prng.seed_with_impl(impl, seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/curc/sw/install/jax/rocm/5.3.0/0.4.7.b/jax_env/lib/python3.11/site-packages/jax/_src/prng.py", line 270, in seed_with_impl
    return random_seed(seed, impl=impl)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/curc/sw/install/jax/rocm/5.3.0/0.4.7.b/jax_env/lib/python3.11/site-packages/jax/_src/prng.py", line 561, in random_seed
    return random_seed_p.bind(seeds_arr, impl=impl)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/curc/sw/install/jax/rocm/5.3.0/0.4.7.b/jax_env/lib/python3.11/site-packages/jax/_src/core.py", line 359, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/curc/sw/install/jax/rocm/5.3.0/0.4.7.b/jax_env/lib/python3.11/site-packages/jax/_src/core.py", line 362, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/curc/sw/install/jax/rocm/5.3.0/0.4.7.b/jax_env/lib/python3.11/site-packages/jax/_src/core.py", line 817, in process_primitive
    return primitive.impl(*tracers, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/curc/sw/install/jax/rocm/5.3.0/0.4.7.b/jax_env/lib/python3.11/site-packages/jax/_src/prng.py", line 573, in random_seed_impl
    base_arr = random_seed_impl_base(seeds, impl=impl)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/curc/sw/install/jax/rocm/5.3.0/0.4.7.b/jax_env/lib/python3.11/site-packages/jax/_src/prng.py", line 578, in random_seed_impl_base
    return seed(seeds)
           ^^^^^^^^^^^
  File "/curc/sw/install/jax/rocm/5.3.0/0.4.7.b/jax_env/lib/python3.11/site-packages/jax/_src/prng.py", line 813, in threefry_seed
    lax.shift_right_logical(seed, lax_internal._const(seed, 32)))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/curc/sw/install/jax/rocm/5.3.0/0.4.7.b/jax_env/lib/python3.11/site-packages/jax/_src/lax/lax.py", line 512, in shift_right_logical
    return shift_right_logical_p.bind(x, y)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/curc/sw/install/jax/rocm/5.3.0/0.4.7.b/jax_env/lib/python3.11/site-packages/jax/_src/core.py", line 359, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/curc/sw/install/jax/rocm/5.3.0/0.4.7.b/jax_env/lib/python3.11/site-packages/jax/_src/core.py", line 362, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/curc/sw/install/jax/rocm/5.3.0/0.4.7.b/jax_env/lib/python3.11/site-packages/jax/_src/core.py", line 817, in process_primitive
    return primitive.impl(*tracers, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/curc/sw/install/jax/rocm/5.3.0/0.4.7.b/jax_env/lib/python3.11/site-packages/jax/_src/dispatch.py", line 117, in apply_primitive
    compiled_fun = xla_primitive_callable(prim, *unsafe_map(arg_spec, args),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/curc/sw/install/jax/rocm/5.3.0/0.4.7.b/jax_env/lib/python3.11/site-packages/jax/_src/util.py", line 253, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/curc/sw/install/jax/rocm/5.3.0/0.4.7.b/jax_env/lib/python3.11/site-packages/jax/_src/util.py", line 246, in cached
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/curc/sw/install/jax/rocm/5.3.0/0.4.7.b/jax_env/lib/python3.11/site-packages/jax/_src/dispatch.py", line 208, in xla_primitive_callable
    compiled = _xla_callable_uncached(lu.wrap_init(prim_fun), prim.name,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/curc/sw/install/jax/rocm/5.3.0/0.4.7.b/jax_env/lib/python3.11/site-packages/jax/_src/dispatch.py", line 254, in _xla_callable_uncached
    return computation.compile(_allow_propagation_to_outputs=allow_prop).unsafe_call
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/curc/sw/install/jax/rocm/5.3.0/0.4.7.b/jax_env/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 2851, in compile
    executable = self._compile_unloaded(
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/curc/sw/install/jax/rocm/5.3.0/0.4.7.b/jax_env/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 2822, in _compile_unloaded
    return UnloadedMeshExecutable.from_hlo(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/curc/sw/install/jax/rocm/5.3.0/0.4.7.b/jax_env/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 3059, in from_hlo
    xla_executable = dispatch.compile_or_get_cached(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/curc/sw/install/jax/rocm/5.3.0/0.4.7.b/jax_env/lib/python3.11/site-packages/jax/_src/dispatch.py", line 526, in compile_or_get_cached
    return backend_compile(backend, serialized_computation, compile_options,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/curc/sw/install/jax/rocm/5.3.0/0.4.7.b/jax_env/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/curc/sw/install/jax/rocm/5.3.0/0.4.7.b/jax_env/lib/python3.11/site-packages/jax/_src/dispatch.py", line 471, in backend_compile
    return backend.compile(built_c, compile_options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Unexpected index

### What jax/jaxlib version are you using?

0.4.7/0.4.7 

### Which accelerator(s) are you using?

AMD MI100 GPU

### Additional system info

3.11

**Comment by mattjj** [comment]
Thanks for raising this!

We're a bit limited on ROCm expertise, but maybe @jayfurmanek or @rsanthanam-amd (who have contributed JAX+ROCm stuff in the past) know what's up.

Does the behavior change if you install an earlier version of jax, like `pip install jax==0.4.6`?

**Comment by rahulbatra85** [comment]
Also, note that starting with jaxlib 0.4.7 jaxlib moved to building against XLA, so you would need to override repo like this
`python3 ./build/build.py --enable_rocm --rocm_path=${ROCM_PATH} --bazel_options=--override_repository=xla=${XLA_CLONE_DIR}`

My PR above also has this change

**Comment by rahulbatra85** [comment]
Note the PR with build updates have been merged. Also, we have docker containers for Jax on ROCm. You can find more info here
https://github.com/ROCmSoftwarePlatform/jax/releases

**Comment by jakevdp** [comment]
Thanks @rahulbatra85 – it sounds like this issue is resolved.
