### ISSUE TITLE
jit fails for fft

### ISSUE THREAD

**Issue by ItayKishon-Remondo** [google/jax#15386]
### Description

As part of an effort of performing fft over a sharded array, I've stumbled upon a basic issue: it seems I'm unable to jit fft().
The following MRE:
```
import jax
import jax.numpy as jnp

def my_fft(a,b):
    return jnp.fft.fft(a,b)

a = jnp.arange(1000)
b = jnp.array(1024)

# non-jit is valid:
_ = my_fft(a,b)

# jit fails:
_ = jax.jit(my_fft)(a,b)
```

will successfully execute the non-jit version, yet will fail when trying to jit.

<details>
  <summary>Error message:</summary>

```
Traceback (most recent call last):
  File "/home/itayk/git/Sandbox/ItayK/Playground/jax/jit-fft-issue__Apr23/jit-fft-issue-1.py", line 11, in <module>
    print(jit_fft(a,b))
  File "/home/itayk/miniconda3/envs/dev_23-04/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/itayk/miniconda3/envs/dev_23-04/lib/python3.9/site-packages/jax/_src/pjit.py", line 238, in cache_miss
    outs, out_flat, out_tree, args_flat = _python_pjit_helper(
  File "/home/itayk/miniconda3/envs/dev_23-04/lib/python3.9/site-packages/jax/_src/pjit.py", line 180, in _python_pjit_helper
    args_flat, _, params, in_tree, out_tree, _ = infer_params_fn(
  File "/home/itayk/miniconda3/envs/dev_23-04/lib/python3.9/site-packages/jax/_src/api.py", line 311, in infer_params
    return pjit.common_infer_params(pjit_info_args, *args, **kwargs)
  File "/home/itayk/miniconda3/envs/dev_23-04/lib/python3.9/site-packages/jax/_src/pjit.py", line 480, in common_infer_params
    jaxpr, consts, canonicalized_out_shardings_flat = _pjit_jaxpr(
  File "/home/itayk/miniconda3/envs/dev_23-04/lib/python3.9/site-packages/jax/_src/pjit.py", line 918, in _pjit_jaxpr
    jaxpr, final_consts, out_type = _create_pjit_jaxpr(
  File "/home/itayk/miniconda3/envs/dev_23-04/lib/python3.9/site-packages/jax/_src/linear_util.py", line 322, in memoized_fun
    ans = call(fun, *args)
  File "/home/itayk/miniconda3/envs/dev_23-04/lib/python3.9/site-packages/jax/_src/pjit.py", line 874, in _create_pjit_jaxpr
    jaxpr, global_out_avals, consts = pe.trace_to_jaxpr_dynamic(
  File "/home/itayk/miniconda3/envs/dev_23-04/lib/python3.9/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/home/itayk/miniconda3/envs/dev_23-04/lib/python3.9/site-packages/jax/_src/interpreters/partial_eval.py", line 2049, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
  File "/home/itayk/miniconda3/envs/dev_23-04/lib/python3.9/site-packages/jax/_src/interpreters/partial_eval.py", line 2066, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/home/itayk/miniconda3/envs/dev_23-04/lib/python3.9/site-packages/jax/_src/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/itayk/git/Sandbox/ItayK/Playground/jax/jit-fft-issue__Apr23/jit-fft-issue-1.py", line 5, in my_fft
    return jnp.fft.fft(a,b)
  File "/home/itayk/miniconda3/envs/dev_23-04/lib/python3.9/site-packages/jax/_src/numpy/fft.py", line 155, in fft
    return _fft_core_1d('fft', xla_client.FftType.FFT, a, n=n, axis=axis,
  File "/home/itayk/miniconda3/envs/dev_23-04/lib/python3.9/site-packages/jax/_src/numpy/fft.py", line 149, in _fft_core_1d
    return _fft_core(func_name, fft_type, a, s, axes, norm)
  File "/home/itayk/miniconda3/envs/dev_23-04/lib/python3.9/site-packages/jax/_src/numpy/fft.py", line 50, in _fft_core
    s = tuple(map(operator.index, s))
  File "/home/itayk/miniconda3/envs/dev_23-04/lib/python3.9/site-packages/jax/_src/core.py", line 583, in __index__
    raise TracerIntegerConversionError(self)
jax._src.traceback_util.UnfilteredStackTrace: jax._src.errors.TracerIntegerConversionError: The __index__() method was called on the JAX Tracer object Traced<ShapedArray(int32[], weak_type=True)>with<DynamicJaxprTrace(level=1/0)>
See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.TracerIntegerConversionError

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/itayk/git/Sandbox/ItayK/Playground/jax/jit-fft-issue__Apr23/jit-fft-issue-1.py", line 11, in <module>
    print(jit_fft(a,b))
  File "/home/itayk/git/Sandbox/ItayK/Playground/jax/jit-fft-issue__Apr23/jit-fft-issue-1.py", line 5, in my_fft
    return jnp.fft.fft(a,b)
  File "/home/itayk/miniconda3/envs/dev_23-04/lib/python3.9/site-packages/jax/_src/numpy/fft.py", line 155, in fft
    return _fft_core_1d('fft', xla_client.FftType.FFT, a, n=n, axis=axis,
  File "/home/itayk/miniconda3/envs/dev_23-04/lib/python3.9/site-packages/jax/_src/numpy/fft.py", line 149, in _fft_core_1d
    return _fft_core(func_name, fft_type, a, s, axes, norm)
  File "/home/itayk/miniconda3/envs/dev_23-04/lib/python3.9/site-packages/jax/_src/numpy/fft.py", line 50, in _fft_core
    s = tuple(map(operator.index, s))
jax._src.errors.TracerIntegerConversionError: The __index__() method was called on the JAX Tracer object Traced<ShapedArray(int32[], weak_type=True)>with<DynamicJaxprTrace(level=1/0)>
See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.TracerIntegerConversionError
```
</details>

Is there a fundamental issue with jit'ing such a complex function, or an alternative way to perform that?

Thank you.

### What jax/jaxlib version are you using?

jax 0.4.8; jaxlib 0.4.7+cuda12.cudnn88

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.9.12, WSL Ubuntu 22.04

### NVIDIA GPU info

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.07    Driver Version: 527.27       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A4000    On   | 00000000:01:00.0 Off |                  Off |
| 41%   29C    P8     7W / 140W |     13MiB / 16376MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Comment by jakevdp** [comment]
Thanks for the question! The JIT call is failing because the second argument controls the shape of the output, and in JAX output shapes must be static. If you want to JIT-compile the FFT operation, one way to do so is to mark the second argument as static:
```python
jax.jit(my_fft, static_argnums=1)(a, 1024)
```
You can read more about this in [JAX Sharp Bits: Dynamic Shapes](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#dynamic-shapes).

**Comment by ItayKishon-Remondo** [comment]
Got it. Thanks for the quick & informative response!
