### ISSUE TITLE
``JAX`` conflicts with ``PyTorch`` at import time

### ISSUE THREAD

**Issue by Badr-MOUFAD** [google/jax#15624]
### Description

When importing ``jax`` and ``pytorch``, namely

```python
import torch

import os
os.environ['XLA_FLAGS'] = '--xla_gpu_force_compilation_parallelism=1'
import jax
```

I get the following error
```bash
Traceback (most recent call last):
  File "debug_script.py", line 6, in <module>
    import jax
  File "/home/badr-moufad/anaconda3/envs/skglm-gpu/lib/python3.7/site-packages/jax/__init__.py", line 35, in <module>
    from jax import config as _config_module
  File "/home/badr-moufad/anaconda3/envs/skglm-gpu/lib/python3.7/site-packages/jax/config.py", line 17, in <module>
    from jax._src.config import config  # noqa: F401
  File "/home/badr-moufad/anaconda3/envs/skglm-gpu/lib/python3.7/site-packages/jax/_src/config.py", line 27, in <module>
    from jax._src import lib
  File "/home/badr-moufad/anaconda3/envs/skglm-gpu/lib/python3.7/site-packages/jax/_src/lib/__init__.py", line 87, in <module>
    import jaxlib.xla_client as xla_client
  File "/home/badr-moufad/anaconda3/envs/skglm-gpu/lib/python3.7/site-packages/jaxlib/xla_client.py", line 25, in <module>
    from . import xla_extension as _xla
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/badr-moufad/anaconda3/envs/skglm-gpu/lib/python3.7/site-packages/jaxlib/xla_extension.so)
```

I thought it might be an error linked to the version of ``libstdc++``, but it appears to be not the case.
Indeed, the problem disappears when swapping the import order of them.

### What jax/jaxlib version are you using?

jax v`0.3.25`, jaxlib v`0.3.22`

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.7, OS Linux Ubuntu 64-bit

### NVIDIA GPU info

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.105.01   Driver Version: 515.105.01   CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA T600 Lap...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   49C    P0     8W /  N/A |      9MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1766      G   /usr/lib/xorg/Xorg                  4MiB |
|    0   N/A  N/A      2699      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+
```

**Comment by Badr-MOUFAD** [comment]
I would stick with inversing the order of imports as the conflict between both packages persists despite installing them from `conda`.

Thanks for your response!
