### ISSUE TITLE
 DNN library initialization failed.

### ISSUE THREAD

**Issue by GravityPHY** [google/jax#15742]
### Description

I tried run AlphaFold-Multimer on GPU, after the parameters and inputs are loaded, the running stopped by raising: `jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
`
I can't find out the exact error information from the error message I have. Following the errors:

> I0425 13:55:15.099713 140484539389760 af_multimer_multiseed.py:552] Running model model_1_multimer_v2_pred_0
I0425 13:55:15.100178 140484539389760 model.py:165] Running predict with shape(feat) = {'aatype': (247,), 'residue_index': (247,), 'seq_length': (), 'msa': (4096, 247), 'num_alignments': (), 'template_all_atom_positions': (4, 247, 37, 3), 'template_all_atom_mask': (4, 247, 37), 'template_aatype': (4, 247), 'asym_id': (247,), 'sym_id': (247,), 'entity_id': (247,), 'deletion_matrix': (4096, 247), 'deletion_mean': (247,), 'all_atom_mask': (247, 37), 'all_atom_positions': (247, 37, 3), 'assembly_num_chains': (), 'entity_mask': (247,), 'num_templates': (), 'cluster_bias_mask': (4096,), 'bert_mask': (4096, 247), 'seq_mask': (247,), 'msa_mask': (4096, 247)}
2023-04-25 13:55:17.465601: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:417] Loaded runtime CuDNN library: 8.4.1 but source was compiled with: 8.6.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
Traceback (most recent call last):
  File "/home/user/project/alphafold/multiseed/af_multimer_multiseed.py", line 676, in <module>
    app.run(main)
  File "/home/user/miniconda3/envs/alpha_mul_v3/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/user/miniconda3/envs/alpha_mul_v3/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/user/project/alphafold/multiseed/af_multimer_multiseed.py", line 666, in main
    predict_structure(FLAGS.output_dir, model_runners, random_seed, multimer_feature, FLAGS.num_prediction, FLAGS.model_preset, FLAGS.enable_single_seed, FLAGS.single_seed)
  File "/home/user/project/alphafold/multiseed/af_multimer_multiseed.py", line 564, in predict_structure
    prediction_result = model_runner.predict(processed_feature_dict,
  File "/home/user/project/alphafold/alphafold/alphafold/model/model.py", line 167, in predict
    result = self.apply(self.params, jax.random.PRNGKey(random_seed), feat)
  File "/home/user/miniconda3/envs/alpha_mul_v3/lib/python3.8/site-packages/jax/_src/random.py", line 136, in PRNGKey
    key = prng.seed_with_impl(impl, seed)
  File "/home/user/miniconda3/envs/alpha_mul_v3/lib/python3.8/site-packages/jax/_src/prng.py", line 270, in seed_with_impl
    return random_seed(seed, impl=impl)
  File "/home/user/miniconda3/envs/alpha_mul_v3/lib/python3.8/site-packages/jax/_src/prng.py", line 561, in random_seed
    return random_seed_p.bind(seeds_arr, impl=impl)
  File "/home/user/miniconda3/envs/alpha_mul_v3/lib/python3.8/site-packages/jax/_src/core.py", line 360, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/home/user/miniconda3/envs/alpha_mul_v3/lib/python3.8/site-packages/jax/_src/core.py", line 363, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/user/miniconda3/envs/alpha_mul_v3/lib/python3.8/site-packages/jax/_src/core.py", line 817, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/user/miniconda3/envs/alpha_mul_v3/lib/python3.8/site-packages/jax/_src/prng.py", line 573, in random_seed_impl
    base_arr = random_seed_impl_base(seeds, impl=impl)
  File "/home/user/miniconda3/envs/alpha_mul_v3/lib/python3.8/site-packages/jax/_src/prng.py", line 578, in random_seed_impl_base
    return seed(seeds)
  File "/home/user/miniconda3/envs/alpha_mul_v3/lib/python3.8/site-packages/jax/_src/prng.py", line 813, in threefry_seed
    lax.shift_right_logical(seed, lax_internal._const(seed, 32)))
  File "/home/user/miniconda3/envs/alpha_mul_v3/lib/python3.8/site-packages/jax/_src/lax/lax.py", line 458, in shift_right_logical
    return shift_right_logical_p.bind(x, y)
  File "/home/user/miniconda3/envs/alpha_mul_v3/lib/python3.8/site-packages/jax/_src/core.py", line 360, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/home/user/miniconda3/envs/alpha_mul_v3/lib/python3.8/site-packages/jax/_src/core.py", line 363, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/user/miniconda3/envs/alpha_mul_v3/lib/python3.8/site-packages/jax/_src/core.py", line 817, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/user/miniconda3/envs/alpha_mul_v3/lib/python3.8/site-packages/jax/_src/dispatch.py", line 117, in apply_primitive
    compiled_fun = xla_primitive_callable(prim, *unsafe_map(arg_spec, args),
  File "/home/user/miniconda3/envs/alpha_mul_v3/lib/python3.8/site-packages/jax/_src/util.py", line 253, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
  File "/home/user/miniconda3/envs/alpha_mul_v3/lib/python3.8/site-packages/jax/_src/util.py", line 246, in cached
    return f(*args, **kwargs)
  File "/home/user/miniconda3/envs/alpha_mul_v3/lib/python3.8/site-packages/jax/_src/dispatch.py", line 208, in xla_primitive_callable
    compiled = _xla_callable_uncached(lu.wrap_init(prim_fun), prim.name,
  File "/home/user/miniconda3/envs/alpha_mul_v3/lib/python3.8/site-packages/jax/_src/dispatch.py", line 254, in _xla_callable_uncached
    return computation.compile(_allow_propagation_to_outputs=allow_prop).unsafe_call
  File "/home/user/miniconda3/envs/alpha_mul_v3/lib/python3.8/site-packages/jax/_src/interpreters/pxla.py", line 2816, in compile
    self._executable = UnloadedMeshExecutable.from_hlo(
  File "/home/user/miniconda3/envs/alpha_mul_v3/lib/python3.8/site-packages/jax/_src/interpreters/pxla.py", line 3028, in from_hlo
    xla_executable = dispatch.compile_or_get_cached(
  File "/home/user/miniconda3/envs/alpha_mul_v3/lib/python3.8/site-packages/jax/_src/dispatch.py", line 526, in compile_or_get_cached
    return backend_compile(backend, serialized_computation, compile_options,
  File "/home/user/miniconda3/envs/alpha_mul_v3/lib/python3.8/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/home/user/miniconda3/envs/alpha_mul_v3/lib/python3.8/site-packages/jax/_src/dispatch.py", line 471, in backend_compile
    return backend.compile(built_c, compile_options=options)
jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.

### What jax/jaxlib version are you using?

jax version 0.4.8
jaxlib version: 0.4.7+cuda11.cudnn86

### Which accelerator(s) are you using?

GPU

### NVIDIA GPU info

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A6000    Off  | 00000000:81:00.0 Off |                  Off |
| 43%   70C    P2   111W / 300W |  10575MiB / 49140MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA RTX A6000    Off  | 00000000:82:00.0 Off |                  Off |
| 30%   52C    P8    34W / 300W |    123MiB / 49140MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA RTX A6000    Off  | 00000000:C1:00.0 Off |                  Off |
| 32%   61C    P8    38W / 300W |      8MiB / 49140MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA RTX A6000    Off  | 00000000:C2:00.0 Off |                  Off |
| 34%   62C    P8    41W / 300W |      8MiB / 49140MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2282      G   /usr/lib/xorg/Xorg                  4MiB |
|    1   N/A  N/A      2282      G   /usr/lib/xorg/Xorg                 64MiB |
|    1   N/A  N/A      2592      G   /usr/bin/gnome-shell                7MiB |
|    2   N/A  N/A      2282      G   /usr/lib/xorg/Xorg                  4MiB |
|    3   N/A  N/A      2282      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+

**Comment by GravityPHY** [comment]
Version: 0.4.7+cuda11.cudnn86

**Comment by hawkinsp** [comment]
The error message explains the problem:

```
 Loaded runtime CuDNN library: 8.4.1 but source was compiled with: 8.6.0. CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.
```

Upgrade your CuDNN installation?

**Comment by GravityPHY** [comment]
> 

Thanks! Problem solved. I upgraded the installation by running
`# Installs the wheel compatible with Cuda 11.4+ and cudnn 8.2+ (deprecated).
pip install "jax[cuda11_cudnn82]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`
Following https://github.com/google/jax#installation
