### ISSUE TITLE
'argnums' in grad, jacfwd, and jacrev only accepts literal Python integers

### ISSUE THREAD

**Issue by adabbott** [google/jax#1575]
I've been having a blast using JAX for the couple months, but I've recently hit a roadblock that I can't seem to work around. Any help would be appreciated!

The crux of the issue is that the 'argnums' argument of `grad`, `jacfwd`, and `jacrev` requires either an integer or a tuple of integers. Indexing an array to retrieve an integer and setting `argnums` to the value of that integer does not work, for example:

```python
import jax
import jax.numpy as np

def f(x,y):
    return 2 * x + 3 * y

# Passing integers or tuple of integers is fine
g = jax.grad(f, argnums=0)(2.0,2.0)
g = jax.grad(f, argnums=(0,1))(2.0,2.0)

# Passing integer from a Python list works
diff_indices = [0,1]
g = jax.grad(f, argnums=diff_indices[0])(2.0,2.0)

# Passing integer from an array does not work
diff_indices = np.array([0,1])
g = jax.grad(f, argnums=diff_indices[0])(2.0,2.0)
```

The last line gives the following error:
```python
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    g = jax.grad(f, argnums=diff_indices[0])(2.0,2.0)
  File "/home/adabbott/Git/jax/jax/jax/api.py", line 343, in grad_f
    _, g = value_and_grad_f(*args, **kwargs)
  File "/home/adabbott/Git/jax/jax/jax/api.py", line 389, in value_and_grad_f
    f_partial, dyn_args = _argnums_partial(f, argnums, args)
  File "/home/adabbott/Git/jax/jax/jax/api.py", line 1250, in _argnums_partial
    dyn_argnums = tuple(dyn_argnums)
  File "/home/adabbott/Git/jax/jax/jax/interpreters/xla.py", line 683, in __iter__
    raise TypeError("iteration over a 0-d array")  # same as numpy error
TypeError: iteration over a 0-d array
```

The source of this error appears to be that in `jax.api._argnums_partial`, the `argnums` are packed into a tuple, but this cannot be done to DeviceArray values (I think?). 

Normally, this isn't a big deal. But for my use case, I want to evaluate *different* partial derivatives of a function over many input values, thus each input value requires a different `argnum` in `jax.grad`. Here's a simple example of what I'm trying to do. The following code works:
```python
import jax
import jax.numpy as np

def f(x,y):
    return 2 * x + 3 * y

inp = np.array([1.0,2.0,3.0,4.0,5.0])
grad_indices = [0,0,1,0,1]

for i in range(5):
    idx = grad_indices[i]
    grad_result = jax.grad(f, idx)(inp[i],inp[i])
```

but for my 'real' use-case, the loop is much larger, and the function is much more complicated. Thus, I would really like to use one of JAX's many awesome utilities, such as `jax.lax.map`, to speed things up a bit. In order to do this, `grad_indices` has to be a JAX array:

```python
import jax
import jax.numpy as np

def f(x,y):
    return 2 * x + 3 * y

inp = np.array([1.0,2.0,3.0,4.0,5.0])
grad_indices = np.array([0,0,1,0,1]) # this now has to be an array

def partialf(i):
    idx = grad_indices[i]
    grad_result = jax.grad(f, argnums=idx)(inp[i],inp[i])
    return grad_result

grad_result = jax.lax.map(partialf, np.arange(5))
```

And of course, we get similar Traceback to before:
```python
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    grad_result = jax.lax.map(partialf, np.arange(5))
  File "/home/adabbott/Git/jax/jax/jax/lax/lax_control_flow.py", line 831, in map
    _, ys = scan(g, (), xs)
  File "/home/adabbott/Git/jax/jax/jax/lax/lax_control_flow.py", line 476, in scan
    jaxpr, consts, out_tree = _initial_style_jaxpr(f, in_tree, carry_avals + x_avals)
  File "/home/adabbott/Git/jax/jax/jax/lax/lax_control_flow.py", line 59, in _initial_style_jaxpr
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr(fun, in_pvals, instantiate=True)
  File "/home/adabbott/Git/jax/jax/jax/interpreters/partial_eval.py", line 343, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/home/adabbott/Git/jax/jax/jax/linear_util.py", line 165, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/adabbott/Git/jax/jax/jax/lax/lax_control_flow.py", line 830, in <lambda>
    g = lambda _, x: ((), f(x))
  File "usecase2.py", line 13, in partialf
    grad_result = jax.grad(f, argnums=idx)(inp[i],inp[i])
  File "/home/adabbott/Git/jax/jax/jax/api.py", line 343, in grad_f
    _, g = value_and_grad_f(*args, **kwargs)
  File "/home/adabbott/Git/jax/jax/jax/api.py", line 389, in value_and_grad_f
    f_partial, dyn_args = _argnums_partial(f, argnums, args)
  File "/home/adabbott/Git/jax/jax/jax/api.py", line 1250, in _argnums_partial
    dyn_argnums = tuple(dyn_argnums)
  File "/home/adabbott/Git/jax/jax/jax/core.py", line 293, in __iter__
    return iter(self.aval._iter(self))
  File "/home/adabbott/Git/jax/jax/jax/lax/lax.py", line 1439, in _iter
    raise TypeError("iteration over a 0-d array")  # same as numpy error
TypeError: iteration over a 0-d array
```

Would it be possible to adjust the code so that `argnums` can be an integer jax.numpy array without breaking anything? Alternatively, if there's a possible workaround that I am missing, I would love to know! Thanks!

**Comment by gnecula** [comment]
This seems something that we could improve in JAX (treating 0-d arrays as numerics). Meanwhile, a workaround that should work is to use `int(diff_indices[0])` to force conversion from 0-d array to an int.

**Comment by adabbott** [comment]
Thanks for the suggestion @gnecula !
Wrapping `argnums` in `int()` does work most of the time, but I do not believe that it works 
with many of JAX's utilities like `jit`, `vmap`, `lax.scan`, and `lax.map`. Example:
```python
import jax
import jax.numpy as np

def f(x,y):
    return 2 * x + 3 * y

inp = np.array([1.0,2.0,3.0,4.0,5.0])
grad_indices = np.array([0,0,1,0,1]) # this now has to be an array

def partialf(i):
    idx = int(grad_indices[i]) # force conversion to int
    grad_result = jax.grad(f, argnums=idx)(inp[i],inp[i])
    return grad_result

grad_result = jax.lax.map(partialf, np.arange(5))
```
Returns the following error:
```python
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    grad_result = jax.lax.map(partialf, np.arange(5))
  File "/home/adabbott/Git/jax/jax/jax/lax/lax_control_flow.py", line 831, in map
    _, ys = scan(g, (), xs)
  File "/home/adabbott/Git/jax/jax/jax/lax/lax_control_flow.py", line 476, in scan
    jaxpr, consts, out_tree = _initial_style_jaxpr(f, in_tree, carry_avals + x_avals)
  File "/home/adabbott/Git/jax/jax/jax/lax/lax_control_flow.py", line 59, in _initial_style_jaxpr
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr(fun, in_pvals, instantiate=True)
  File "/home/adabbott/Git/jax/jax/jax/interpreters/partial_eval.py", line 343, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/home/adabbott/Git/jax/jax/jax/linear_util.py", line 165, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/adabbott/Git/jax/jax/jax/lax/lax_control_flow.py", line 830, in <lambda>
    g = lambda _, x: ((), f(x))
  File "ahh.py", line 11, in partialf
    idx = int(grad_indices[i]) # force conversion to int
  File "/home/adabbott/Git/jax/jax/jax/core.py", line 343, in __int__
    def __int__(self): return self.aval._int(self)
  File "/home/adabbott/Git/jax/jax/jax/abstract_arrays.py", line 38, in error
    raise TypeError(concretization_err_msg(fun))
TypeError: Abstract value passed to `int`, which requires a concrete value. The function to be transformed can't be traced at the required level of abstraction. If using `jit`, try using `static_argnums` or applying `jit` to smaller subfunctions instead.
```

So there still seems to be a limitation here.

**Comment by shoyer** [comment]
Unfortunately, I don't think what you're trying to do can work. JAX's transformations like `grad` aren't implemented in LAX. They are implemented using custom control flow in Python.

So functions like `lax.map` break, because they expect control flow. It's basically the same issue you would have if you used Python `if` statement inside your mapped function.

**Comment by adabbott** [comment]
Thanks for the explanation! I understand what's going on a bit better now.
