### ISSUE TITLE
v0.4.9 Build fails on linux arm

### ISSUE THREAD

**Issue by mowoe** [google/jax#15960]
### Description

To compile [tf-df](https://github.com/tensorflow/decision-forests) for arm we need jaxlib. Due to no linux arm64 wheels being published, i am trying to build from source.

This fails at `jaxlib-v.0.4.9`, i have tried to use the XLA repo at head instead of the pinned one, which brpught no luck.

```Dockerfile
FROM python:3.10-buster
RUN git clone -b jaxlib-v0.4.9 https://github.com/google/jax
WORKDIR /jax
RUN pip install numpy wheel
RUN python build/build.py
```
```bash
$ docker buildx build --platform linux/arm64 .
#0 891.5 In file included from external/xla/xla/hlo/ir/hlo_instruction.h:43,
#0 891.5                  from external/xla/xla/hlo/ir/hlo_computation.h:35,
#0 891.5                  from external/xla/xla/hlo/ir/dfs_hlo_visitor_with_default.h:24,
#0 891.5                  from external/xla/xla/service/topk_rewriter.h:24,
#0 891.5                  from external/xla/xla/service/topk_rewriter.cc:16:
#0 891.5 external/xla/xla/comparison_util.h:74:60: note: declared here
#0 891.5    enum class [[deprecated("Use PrimitiveType and Order")]] Type : uint8_t{
#0 891.5                                                             ^~~~
#0 891.5 external/xla/xla/service/topk_rewriter.cc: In instantiation of 'xla::HasIota(xla::HloSortInstruction*, xla::HloInstruction*)::<lambda(auto:5)> [with auto:5 = std::initializer_list<const long int>]':
#0 891.5 external/xla/xla/service/topk_rewriter.cc:177:67:   required from here
#0 891.5 external/xla/xla/service/topk_rewriter.cc:174:78: error: no matching function for call to 'xla::match::detail::ShapePattern<const xla::Shape, xla::match::detail::AllOfPattern<xla::Shape, xla::match::detail::ShapePatternBaseImpl, xla::match::detail::ShapePatternElementTypeImpl> >::WithDims(std::initializer_list<const long int>&)'
#0 891.5      return m::Iota().WithShape(m::Shape().WithElementType(S32).WithDims(dims));
#0 891.5                                                                               ^
#0 891.5 In file included from external/xla/xla/service/topk_rewriter.cc:30:
#0 891.5 external/xla/xla/service/pattern_matcher.h:1073:18: note: candidate: 'constexpr auto xla::match::detail::ShapePattern<ShapeType, Impl>::WithDims(absl::lts_20230125::Span<const long int>) const [with ShapeType = const xla::Shape; Impl = xla::match::detail::AllOfPattern<xla::Shape, xla::match::detail::ShapePatternBaseImpl, xla::match::detail::ShapePatternElementTypeImpl>]'
#0 891.5    constexpr auto WithDims(absl::Span<const int64_t> dims) const {
#0 891.5                   ^~~~~~~~
#0 891.5 external/xla/xla/service/pattern_matcher.h:1073:18: note:   no known conversion for argument 1 from 'std::initializer_list<const long int>' to 'absl::lts_20230125::Span<const long int>'
#0 891.5 external/xla/xla/service/topk_rewriter.cc: In function 'bool xla::HasIota(xla::HloSortInstruction*, xla::HloInstruction*)':
#0 891.5 external/xla/xla/service/topk_rewriter.cc:177:68: error: invalid use of void expression
#0 891.5           Match(sort->operand(1), m::Broadcast(match_iota(sort_dims)));
#0 891.5                                                                     ^
#0 891.5 In file included from external/xla/xla/hlo/ir/hlo_computation.h:35,
#0 891.5                  from external/xla/xla/hlo/ir/dfs_hlo_visitor_with_default.h:24,
#0 891.5                  from external/xla/xla/service/topk_rewriter.h:24,
#0 891.5                  from external/xla/xla/service/topk_rewriter.cc:16:
#0 891.5 external/xla/xla/hlo/ir/hlo_instruction.h: In member function 'virtual absl::lts_20230125::Span<const long int> xla::HloInstruction::dimensions() const':
#0 891.5 external/xla/xla/hlo/ir/hlo_instruction.h:1934:19: warning: control reaches end of non-void function [-Wreturn-type]
#0 891.5      LOG(FATAL) << "Unimplemented method.";
#0 891.5                    ^~~~~~~~~~~~~~~~~~~~~~~
#0 891.5 At global scope:
#0 891.5 cc1plus: warning: unrecognized command line option '-Wno-array-parameter'
#0 891.5 cc1plus: warning: unrecognized command line option '-Wno-unknown-warning-option'
#0 892.1 Target //build:build_wheel failed to build
#0 892.3 INFO: Elapsed time: 884.795s, Critical Path: 200.45s
#0 892.3 INFO: 2635 processes: 242 internal, 2393 local.
#0 892.3 FAILED: Build did NOT complete successfully
#0 892.3 ERROR: Build failed. Not running target
#0 892.3 FAILED: Build did NOT complete successfully
#0 892.4 
#0 892.4      _   _  __  __
#0 892.4     | | / \ \ \/ /
#0 892.4  _  | |/ _ \ \  /
#0 892.4 | |_| / ___ \/  \
#0 892.4  \___/_/   \/_/\_\
#0 892.4 
#0 892.4 
#0 892.4 Downloading bazel from: https://github.com/bazelbuild/bazel/releases/download/5.1.1/bazel-5.1.1-linux-arm64
#0 892.4 
#0 892.4 Bazel binary path: ./bazel-5.1.1-linux-arm64
#0 892.4 Bazel version: 5.1.1
#0 892.4 Python binary path: /usr/local/bin/python
#0 892.4 Python version: 3.10
#0 892.4 NumPy version: 1.24.3
#0 892.4 MKL-DNN enabled: yes
#0 892.4 Target CPU: aarch64
#0 892.4 Target CPU features: release
#0 892.4 CUDA enabled: no
#0 892.4 TPU enabled: no
#0 892.4 ROCm enabled: no
#0 892.4 Plugin device enabled: no
#0 892.4 
#0 892.4 Building XLA and installing it in the jaxlib source tree...
#0 892.4 ./bazel-5.1.1-linux-arm64 run --verbose_failures=true :build_wheel -- --output_path=/jax/dist --cpu=aarch64
#0 892.4 b''
#0 892.4 Traceback (most recent call last):
#0 892.4   File "/jax/build/build.py", line 564, in <module>
#0 892.4     main()
#0 892.4   File "/jax/build/build.py", line 559, in main
#0 892.4     shell(command)
#0 892.4   File "/jax/build/build.py", line 53, in shell
#0 892.4     output = subprocess.check_output(cmd)
#0 892.4   File "/usr/local/lib/python3.10/subprocess.py", line 421, in check_output
#0 892.4     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
#0 892.4   File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
#0 892.4     raise CalledProcessError(retcode, process.args,
#0 892.4 subprocess.CalledProcessError: Command '['./bazel-5.1.1-linux-arm64', 'run', '--verbose_failures=true', ':build_wheel', '--', '--output_path=/jax/dist', '--cpu=aarch64']' returned non-zero exit status 1.
```

The actual issue seems to be with xla, but unfourtunately it is beyond my understanding and skills to fix the build, so any help is appreciated!

### What jax/jaxlib version are you using?

jax v.0.4.9

### Additional system info

python3.10, arm64

**Comment by hawkinsp** [comment]
This was fixed by https://github.com/openxla/xla/commit/be1cee3e4aeee55ea5487d15398d92d9e21e19b2
