### ISSUE TITLE
How to use jit with jax.numpy.reshape?

### ISSUE THREAD

**Issue by JLenssen** [google/jax#1629]
Hi,

i started to use JAX today to compute some gradients and it works perfectly. 
Now i want to speed up things with `jit`, but i encountered a problem with `jax.numpy.reshape`.

If someone could tell me what is going wrong or how to debug the function, that would be great.

```
 def functional(X):
   r = X.shape[0]
   X_imshape = np.reshape(X, (r, m, n), order = 'F')
   ....
```

The output i get is

```
UserWarning:

No GPU/TPU found, falling back to CPU.

Traceback (most recent call last):
  File "/Users/xxx/anaconda/envs/xxx/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
TypeError: 'JaxprTracer' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "spatial_unmixing.py", line 111, in <module>
    main()
  File "spatial_unmixing.py", line 87, in main
    x_res = ms.optimII(x0, lambda x: jax_gradient_spatial_functional(x, Y, K_GT, m, n, lambda_, tau, h), ms.projectVectorsCanonicalSimplex, alpha0, mu, L, restart_nesterov, maxIter, threshold)
  File "/Users/xxx/Desktop/xxx/Projects/unmixing/unmixing_example/utilities/msiplib.py", line 675, in optimII
    xNew = projC(yOld - 1 / L * fGrad(yOld))
  File "spatial_unmixing.py", line 87, in <lambda>
    x_res = ms.optimII(x0, lambda x: jax_gradient_spatial_functional(x, Y, K_GT, m, n, lambda_, tau, h), ms.projectVectorsCanonicalSimplex, alpha0, mu, L, restart_nesterov, maxIter, threshold)
  File "/Users/xxx/anaconda/envs/xxx/lib/python3.7/site-packages/jax/api.py", line 148, in f_jitted
    out = xla.xla_call(flat_fun, *args_flat, device=device, backend=backend)
  File "/Users/xxx/anaconda/envs/xxx/lib/python3.7/site-packages/jax/core.py", line 591, in call_bind
    outs = primitive.impl(f, *args, **params)
  File "/Users/xxx/anaconda/envs/xxx/lib/python3.7/site-packages/jax/interpreters/xla.py", line 418, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, *map(abstractify, args))
  File "/Users/xxx/anaconda/envs/xxx/lib/python3.7/site-packages/jax/linear_util.py", line 217, in cached_fun
    ans, f_prev = cached_fun_body(f, args)
  File "/Users/xxx/anaconda/envs/xxx/lib/python3.7/site-packages/jax/linear_util.py", line 214, in cached_fun_body
    return call(f, *args), f
  File "/Users/xxx/anaconda/envs/xxx/lib/python3.7/site-packages/jax/interpreters/xla.py", line 434, in _xla_callable
    jaxpr, (pvals, consts, env) = pe.trace_to_subjaxpr(fun, master, False).call_wrapped(pvals)
  File "/Users/xxx/anaconda/envs/xxx/lib/python3.7/site-packages/jax/linear_util.py", line 165, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/xxx/anaconda/envs/xxx/lib/python3.7/site-packages/jax/api.py", line 343, in grad_f
    _, g = value_and_grad_f(*args, **kwargs)
  File "/Users/xxx/anaconda/envs/xxx/lib/python3.7/site-packages/jax/api.py", line 391, in value_and_grad_f
    ans, vjp_py = vjp(f_partial, *dyn_args)
  File "/Users/xxx/anaconda/envs/xxx/lib/python3.7/site-packages/jax/api.py", line 1149, in vjp
    out_primal, out_vjp = ad.vjp(flat_fun, primals_flat)
  File "/Users/xxx/anaconda/envs/xxx/lib/python3.7/site-packages/jax/interpreters/ad.py", line 107, in vjp
    out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
  File "/Users/xxx/anaconda/envs/xxx/lib/python3.7/site-packages/jax/interpreters/ad.py", line 96, in linearize
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr(jvpfun_flat, in_pvals)
  File "/Users/xxx/anaconda/envs/xxx/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 343, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/Users/xxx/anaconda/envs/xxx/lib/python3.7/site-packages/jax/linear_util.py", line 165, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/xxx/Desktop/xxx/Projects/unmixing/unmixing_example/jax_unmixing.py", line 24, in spatial_functional_jax
    X_imshape = np.reshape(X, (r, m, n), order = 'F')
  File "/Users/xxx/anaconda/envs/xxx/lib/python3.7/site-packages/jax/numpy/lax_numpy.py", line 778, in reshape
    return a.reshape(newshape, order=order)  # forward to method for ndarrays
  File "/Users/xxx/anaconda/envs/xxx/lib/python3.7/site-packages/jax/numpy/lax_numpy.py", line 808, in _reshape_method
    return _reshape(a, newshape, order=order)
  File "/Users/xxx/anaconda/envs/xxx/lib/python3.7/site-packages/jax/numpy/lax_numpy.py", line 784, in _reshape
    computed_newshape = onp.reshape(dummy_val, newshape).shape
  File "<__array_function__ internals>", line 6, in reshape
  File "/Users/xxx/anaconda/envs/xxx/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 301, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/xxx/anaconda/envs/xxx/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 70, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/xxx/anaconda/envs/xxx/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
TypeError: 'JaxprTracer' object cannot be interpreted as an integer

```

**Comment by mattjj** [comment]
Thanks for the question! Can you share a minimal but runnable code snippet that reproduces the error?

**Comment by hawkinsp** [comment]
This issue has been open with no response for a while; closing. Feel free to reopen with details. (It might be more appropriate as a discussion thread, rather than an issue.)
