### ISSUE TITLE
Crash from `jvp(jit(vmap(custom_jvp(in-place-update-on-size-zero-array))))`

### ISSUE THREAD

**Issue by patrick-kidger** [google/jax#16374]
### Description

Yes, I know what that title sounds like. You don't know want to know how long this has taken me to track down.

First of all, a repro:
```python
import jax
import jax.numpy as jnp


@jax.custom_jvp
def f(x):
    y = jnp.zeros((1,) + x.shape)
    return y.at[0].set(x)


@f.defjvp
def f_jvp(primals, tangents):
    (x,) = primals
    (t_x,) = tangents
    out = jnp.broadcast_to(x, (1,) + x.shape)
    t_out = jnp.broadcast_to(t_x, (1,) + t_x.shape)
    return out, t_out

x = tx = jnp.zeros((1, 0))
jax.jvp(jax.jit(jax.vmap(f)), (x,), (tx,))
```
which raises the following error from within JAX:
```
  File ".../jax/_src/lax/lax.py", line 2849, in _broadcast_in_dim_abstract_eval
    shape = _broadcast_in_dim_shape_rule(  # error checking
  File ".../jax/_src/lax/lax.py", line 2686, in _broadcast_in_dim_shape_rule
    raise TypeError(msg.format(broadcast_dimensions, operand_ndim))
jax._src.traceback_util.UnfilteredStackTrace: TypeError: broadcast_in_dim broadcast_dimensions must have length equal to operand ndim; got broadcast_dimensions (1, 2) for operand ndim 3.
```

---

Second of all, the root cause:
```python
import jax
import jax.numpy as jnp

def g(x):
    y = jnp.zeros((1,) + x.shape)
    return y.at[0].set(x)
z = jnp.zeros((0,))
print(jax.make_jaxpr(g)(z))
#{ lambda ; a:f32[0]. let
#    b:f32[1,0] = broadcast_in_dim[broadcast_dimensions=() shape=(1, 0)] 0.0
#    _:i32[1] = broadcast_in_dim[broadcast_dimensions=() shape=(1,)] 0
#  in (b,) }
```
This snippet demonstrates that in-place updates to size-zero arrays are ignored, which implies that the output has no data dependency on the input, and the batch tracer is not promulgated.

However, returning to our original example: the JVP rule implementation *does* propagate batch tracers through size-zero arrays.

As a result the primal and tangent branches of the `vmap(custom_jvp)` get different shapes, and JAX crashes. 

For completeness, here's the full traceback:
```python
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    jax.jvp(jax.jit(jax.vmap(f)), (x,), (tx,))
  File ".../jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File ".../jax/_src/pjit.py", line 212, in cache_miss
    outs, out_flat, out_tree, args_flat = _python_pjit_helper(
  File ".../jax/_src/pjit.py", line 159, in _python_pjit_helper
    out_flat = pjit_p.bind(*args_flat, **params)
  File ".../jax/_src/core.py", line 2628, in bind
    return self.bind_with_trace(top_trace, args, params)
  File ".../jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File ".../jax/_src/interpreters/ad.py", line 315, in process_primitive
    primal_out, tangent_out = jvp(primals_in, tangents_in, **params)
  File ".../jax/_src/pjit.py", line 1431, in _pjit_jvp
    jaxpr_jvp, is_nz_tangents_out = ad.jvp_jaxpr(
  File ".../jax/_src/interpreters/ad.py", line 699, in jvp_jaxpr
    return _jvp_jaxpr(jaxpr, tuple(nonzeros), tuple(instantiate))
  File ".../jax/_src/interpreters/ad.py", line 709, in _jvp_jaxpr
    jaxpr_out, avals_out, literals_out = pe.trace_to_jaxpr_dynamic(f_jvp, avals_in)
  File ".../jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File ".../jax/_src/interpreters/partial_eval.py", line 2150, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
  File ".../jax/_src/interpreters/partial_eval.py", line 2172, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File ".../jax/_src/linear_util.py", line 188, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File ".../jax/_src/core.py", line 229, in jaxpr_as_fun
    return eval_jaxpr(closed_jaxpr.jaxpr, closed_jaxpr.consts, *args)
  File ".../jax/_src/core.py", line 447, in eval_jaxpr
    ans = eqn.primitive.bind(*subfuns, *map(read, eqn.invars), **bind_params)
  File ".../jax/_src/core.py", line 380, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File ".../jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File ".../jax/_src/interpreters/ad.py", line 315, in process_primitive
    primal_out, tangent_out = jvp(primals_in, tangents_in, **params)
  File ".../jax/_src/lax/lax.py", line 2796, in _broadcast_in_dim_jvp_rule
    y = broadcast_in_dim_p.bind(operand, *dyn_shape, shape=shape,
  File ".../jax/_src/core.py", line 380, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File ".../jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File ".../jax/_src/interpreters/partial_eval.py", line 1854, in process_primitive
    return custom_staging_rules[primitive](self, *tracers, **params)
  File ".../jax/_src/lax/lax.py", line 2770, in _broadcast_in_dim_staging_rule
    return trace.default_process_primitive(broadcast_in_dim_p, (x,), params)
  File ".../jax/_src/interpreters/partial_eval.py", line 1859, in default_process_primitive
    out_avals, effects = primitive.abstract_eval(*avals, **params)
  File ".../jax/_src/core.py", line 416, in abstract_eval_
    return abstract_eval(*args, **kwargs), no_effects
  File ".../jax/_src/lax/lax.py", line 2849, in _broadcast_in_dim_abstract_eval
    shape = _broadcast_in_dim_shape_rule(  # error checking
  File ".../jax/_src/lax/lax.py", line 2686, in _broadcast_in_dim_shape_rule
    raise TypeError(msg.format(broadcast_dimensions, operand_ndim))
jax._src.traceback_util.UnfilteredStackTrace: TypeError: broadcast_in_dim broadcast_dimensions must have length equal to operand ndim; got broadcast_dimensions (1, 2) for operand ndim 3.
```

### What jax/jaxlib version are you using?

HEAD

**Comment by mattjj** [comment]
Wow, thanks for diagnosing this, Patrick! Sorry it took so long to diagnose but... I really appreciate you doing it!

And thanks for taking JAX's composable transformations seriously :P

**Comment by mattjj** [comment]
Happy late birthday to this issue!

Because I'm not going to fix this now (sorry), a note to future self: I think we need `DynamicJaxprTrace.process_custom_jvp_call` to run both `fun` and `jvp` (rather than delaying the latter), and for `BatchTrace.process_custom_jvp_call` to prepare that case (i.e. not only ready for just one or the other running, as it is now, but also being ready for both being run) and join the output batching as appropriate. This is essentially the logic that @dougalm thought of for a final-style cond back in 2018. (The reason we delay running `jvp` in a thunk is to avoid an infinite mutual recursion in case `jvp` calls `fun` internally... we'll have to sort that out.)

The best temporary workaround I can think of is to ensure `f` and `f_jvp` have the same primal-input-to-primal-output data dependencies. An easy way to do that is to compute the primal outputs in `f_jvp` just by calling `f`.

We could also catch this error earlier; the earliest we can at the moment is [above this line in `DynamicJaxprTrace.process_custom_jvp_call`](https://github.com/google/jax/blob/d350ef779c26b9765db5830819c2eeb9075a7029/jax/_src/interpreters/partial_eval.py#L2159). That's when we should realize the JVP function's output primal types don't match those of the primal function's. But at that point it's too late to fix things.

We _could_ patch up this one case by making `y.at[0].set(x)` have a data dependence on `x` even in the case where `x` and/or `y` are size 0. That fix feels bad to rely on but at least it would've saved Patrick a lot of time.
