### ISSUE TITLE
Interaction between `vmap` and new PRNG

### ISSUE THREAD

**Issue by DruvPai** [google/jax#16422]
### Description

Hi, I'm having trouble seeing how the following MWE using [Diffrax](https://github.com/patrick-kidger/diffrax) errors:
```py
import jax
from jax import numpy as jnp
from diffrax import diffeqsolve, ControlTerm, Euler, MultiTerm, ODETerm, SaveAt, VirtualBrownianTree

B = 20
D = 5

tol = 1e-3
dt0 = 0.05
T0 = 0.0
Tf = 1.0

def f(x0, key):
    drift = lambda t, x, args: jnp.zeros((D, ))
    diffusion = lambda t, x, args: jnp.zeros((D, D))
    brownian_motion = VirtualBrownianTree(T0, Tf, tol=tol, shape=x0.shape, key=key)
    terms = MultiTerm(ODETerm(drift), ControlTerm(diffusion, brownian_motion))
    solver = Euler()
    saveat = SaveAt(dense=True)
    sol = diffeqsolve(terms, solver, T0, Tf, dt0=dt0, y0=x0, saveat=saveat)
    return sol.evaluate(Tf)

x0 = jnp.zeros((D, ))
key = jax.random.key(1)
print(f(x0, key))

x0 = jnp.zeros((B, D))
key = jax.random.split(key, B)
print(jax.vmap(f)(x0, key))
```
In particular, the last three lines (with `vmap`) cause an error, while the previous three lines seem to work fine.
I raised [this issue in Diffrax](https://github.com/patrick-kidger/diffrax/issues/267) and was told that it was an issue only with the new PRNG, so the bug is in Jax rather than Diffrax. Hence I'm raising it here.

Here are links for:
- [The stack trace.](https://pastebin.com/46hbkCKb)
- [The output of my `conda list`.](https://pastebin.com/3xjrfYYz)

### What jax/jaxlib version are you using?

0.4.12/0.4.12

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.10.11, WSL 2 -> Ubuntu 22.04.2 LTS

**Comment by jakevdp** [comment]
Thanks for the report! Indeed it looks like a JAX problem; here's a simpler reproduction:
```python
import jax

def f(key):
  key1, key2 = jax.random.split(key)
  return jax.numpy.where(True, key1, key2)

keys = jax.random.split(jax.random.key(0), 5)
print(jax.vmap(f)(keys))
```
```pytb
Traceback (most recent call last):
  File "/Users/vanderplas/github/google/jax/tmp.py", line -1, in <module>
  File "/Users/vanderplas/github/google/jax/tmp.py", line -1, in f
  File "/Users/vanderplas/github/google/jax/jax/_src/numpy/lax_numpy.py", line -1, in where
  File "/Users/vanderplas/github/google/jax/jax/_src/numpy/util.py", line -1, in _where
jax._src.source_info_util.JaxStackTraceBeforeTransformation: AssertionError

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/vanderplas/github/google/jax/tmp.py", line 8, in <module>
    print(jax.vmap(f)(keys))
          ^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/api.py", line 1234, in vmap_f
    out_flat = batching.batch(
               ^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/linear_util.py", line 188, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/tmp.py", line 5, in f
    return jax.numpy.where(True, key1, key2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/numpy/lax_numpy.py", line 1097, in where
    return util._where(condition, x, y)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/pjit.py", line 250, in cache_miss
    outs, out_flat, out_tree, args_flat, jaxpr = _python_pjit_helper(
                                                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/pjit.py", line 163, in _python_pjit_helper
    out_flat = pjit_p.bind(*args_flat, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/core.py", line 2675, in bind
    return self.bind_with_trace(top_trace, args, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/interpreters/batching.py", line 398, in process_primitive
    val_out, dim_out = batched_primitive(vals_in, dims_in, **params)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/pjit.py", line 1405, in _pjit_batcher
    vals_out = pjit_p.bind(
               ^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/core.py", line 2675, in bind
    return self.bind_with_trace(top_trace, args, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/core.py", line 813, in process_primitive
    return primitive.impl(*tracers, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/pjit.py", line 1193, in _pjit_call_impl
    return xc._xla.pjit(name, f, call_impl_cache_miss, [], [], donated_argnums,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/pjit.py", line 1177, in call_impl_cache_miss
    out_flat, compiled = _pjit_call_impl_python(
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/pjit.py", line 1110, in _pjit_call_impl_python
    compiled = _pjit_lower(
               ^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/pjit.py", line 1239, in _pjit_lower
    return _pjit_lower_cached(jaxpr, in_shardings, out_shardings, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/pjit.py", line 1279, in _pjit_lower_cached
    return pxla.lower_sharding_computation(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/interpreters/pxla.py", line 2085, in lower_sharding_computation
    nreps, tuple_args, shape_poly_state) = _cached_lowering_to_hlo(
                                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/interpreters/pxla.py", line 1928, in _cached_lowering_to_hlo
    lowering_result = mlir.lower_jaxpr_to_module(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/interpreters/mlir.py", line 666, in lower_jaxpr_to_module
    lower_jaxpr_to_fun(
  File "/Users/vanderplas/github/google/jax/jax/_src/interpreters/mlir.py", line 997, in lower_jaxpr_to_fun
    out_vals, tokens_out = jaxpr_subcomp(ctx.replace(name_stack=callee_name_stack),
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/interpreters/mlir.py", line 1143, in jaxpr_subcomp
    ans = rule(rule_ctx, *map(_unwrap_singleton_ir_values, in_nodes),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/lax/lax.py", line 3515, in _select_hlo_lowering
    return [_select_hlo_lowering_opaque(ctx, which, *cases)]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/lax/lax.py", line 3491, in _select_hlo_lowering_opaque
    assert avals_in[0].ndim == aval_out.ndim
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jax._src.traceback_util.UnfilteredStackTrace: AssertionError

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/vanderplas/github/google/jax/tmp.py", line 8, in <module>
    print(jax.vmap(f)(keys))
          ^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/tmp.py", line 5, in f
    return jax.numpy.where(True, key1, key2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/numpy/lax_numpy.py", line 1097, in where
    return util._where(condition, x, y)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by jakevdp** [comment]
I think the issue is that the assertion here is just wrong: the shape of the condition in `lax.select` does not need to match the shape of the output. I believe the fix is to remove the assertion.
