### ISSUE TITLE
nested gmres does not work

### ISSUE THREAD

**Issue by WangHaiYang874** [google/jax#16441]
### Description

I am building an iterative solver. Naturally some of my linear operators is defined iteratively using gmres. A simple example would be
```
def a(x):
    # this function is essentially the linear operator x -> 2*x
    return gmres(lambda i: i, 2 * x)[0]
```
On top of this linear operator I can define another linear operator
```
def b(x):
    # this function is essentially the inverse of a
    return gmres(a, x)[0]
```

However, jax would throw an error message whenever i am trying to call `b`. 

Here is the full script: 
```
import jax
from jax import numpy as np
from functools import partial

gmres = partial(jax.scipy.sparse.linalg.gmres, tol=1e-3, restart=10, solve_method='batched')


def a(x):
    # this function is essentially the linear operator x-> 2*x
    return gmres(lambda i: i, 2 * x)[0]


def b(x):
    # this function is essentially the inverse of a
    # but it does not work...
    return gmres(a, x)[0]


if __name__ == '__main__':
    t = np.ones((10,))
    b(t)
```

And here is the error message

python3 jax_error_reproduce.py 
Traceback (most recent call last):
  File "/Users/hwang/PycharmProjects/helmholtz_direct_solver/jax_error_reproduce.py", line 19, in <module>
    b(x)
  File "/Users/hwang/PycharmProjects/helmholtz_direct_solver/jax_error_reproduce.py", line 15, in b
    return gmres(a, 2 * x)[0]
  File "/usr/local/lib/python3.11/site-packages/jax/_src/scipy/sparse/linalg.py", line 704, in gmres
    x = lax.custom_linear_solve(A, b, solve=_solve, transpose_solve=_solve)
  File "/Users/hwang/PycharmProjects/helmholtz_direct_solver/jax_error_reproduce.py", line 10, in a
    return gmres(lambda i: i, 2 * x)[0]
  File "/usr/local/lib/python3.11/site-packages/jax/_src/scipy/sparse/linalg.py", line 704, in gmres
    x = lax.custom_linear_solve(A, b, solve=_solve, transpose_solve=_solve)
jax._src.source_info_util.JaxStackTraceBeforeTransformation: TypeError: Value UndefinedPrimal(ShapedArray(float32[])) with type <class 'jax._src.interpreters.ad.UndefinedPrimal'> is not a valid JAX type

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hwang/PycharmProjects/helmholtz_direct_solver/jax_error_reproduce.py", line 19, in <module>
    b(x)
  File "/Users/hwang/PycharmProjects/helmholtz_direct_solver/jax_error_reproduce.py", line 15, in b
    return gmres(a, 2 * x)[0]
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jax/_src/scipy/sparse/linalg.py", line 704, in gmres
    x = lax.custom_linear_solve(A, b, solve=_solve, transpose_solve=_solve)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jax/_src/lax/control_flow/solves.py", line 272, in custom_linear_solve
    vecmat_jaxpr, vecmat_consts, out_tree = _initial_style_jaxpr(
                                            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jax/_src/lax/control_flow/common.py", line 60, in _initial_style_jaxpr
    jaxpr, consts, out_tree = _initial_style_open_jaxpr(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jax/_src/lax/control_flow/common.py", line 54, in _initial_style_open_jaxpr
    jaxpr, _, consts = pe.trace_to_jaxpr_dynamic(wrapped_fun, in_avals, debug)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jax/_src/interpreters/partial_eval.py", line 2155, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jax/_src/interpreters/partial_eval.py", line 2177, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jax/_src/linear_util.py", line 188, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jax/_src/lax/control_flow/solves.py", line 175, in transposed_fun
    (y,) = transpose_fun(x)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jax/_src/api.py", line 2269, in transposed_fun
    in_cts = ad.backward_pass(jaxpr, reduce_axes, True, const, dummies, out_cts)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jax/_src/interpreters/ad.py", line 253, in backward_pass
    cts_out = get_primitive_transpose(eqn.primitive)(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jax/_src/lax/control_flow/solves.py", line 371, in _linear_solve_transpose_rule
    cotangent_b_full = linear_solve_p.bind(
                       ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jax/_src/core.py", line 2652, in bind
    return self.bind_with_trace(top_trace, args, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jax/_src/core.py", line 475, in full_raise
    return self.pure(val)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jax/_src/interpreters/partial_eval.py", line 1798, in new_const
    aval = raise_to_shaped(get_aval(c), weak_type=dtypes.is_weakly_typed(c))
                           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jax/_src/core.py", line 1334, in get_aval
    return concrete_aval(x)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jax/_src/core.py", line 1326, in concrete_aval
    raise TypeError(f"Value {repr(x)} with type {type(x)} is not a valid JAX "
jax._src.traceback_util.UnfilteredStackTrace: TypeError: Value UndefinedPrimal(ShapedArray(float32[])) with type <class 'jax._src.interpreters.ad.UndefinedPrimal'> is not a valid JAX type

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hwang/PycharmProjects/helmholtz_direct_solver/jax_error_reproduce.py", line 19, in <module>
    b(x)
  File "/Users/hwang/PycharmProjects/helmholtz_direct_solver/jax_error_reproduce.py", line 15, in b
    return gmres(a, 2 * x)[0]
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jax/_src/scipy/sparse/linalg.py", line 704, in gmres
    x = lax.custom_linear_solve(A, b, solve=_solve, transpose_solve=_solve)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Value UndefinedPrimal(ShapedArray(float32[])) with type <class 'jax._src.interpreters.ad.UndefinedPrimal'> is not a valid JAX type

### What jax/jaxlib version are you using?

jax v0.4.12

### Which accelerator(s) are you using?

cpu

**Comment by f0uriest** [comment]
Curiously it seems to work fine if you use `cg` or `bicgstab` for either `a` or `b` (or both) so it seems to be limited to `gmres` not other iterative linear solvers. Under the hood both `cg` and `bicgstab` use [similar infrastructure](https://github.com/google/jax/blob/68a38c6021b40f1d53dece52b651b525b9f6f0f5/jax/_src/scipy/sparse/linalg.py#L196) that `gmres` doesn't.

**Comment by patrick-kidger** [comment]
You may like to try [Lineax](https://github.com/google/lineax), which is our new more-comprehensive solution for linear solvers.
I've just checked and it appears to handle this case without issues.

**Comment by ThatGuyDavid09** [comment]
Assuming this is still a bug, I did some digging and I figured out that the issue is probably caused when the solver calls linear_transpose at the end of the solve. For some reason, as opposed to every other time this function is called, when it generates the jaxpr (line 2282 in api.py), despite having, as far as I can tell, the same parameters, it produces a jaxpr with a non-zero length of equations (`len(jaxpr.eqns) > 0`) and produces invars that are not in the constvars. This produces a problem further down the line when backwards_pass is called (line 181 in ad.py). This method generates a mapping of sorts between the constvars of the provided jaxpr and some other constants passed into the function itself. Later, the method iterates over every equation in jaxpr.eqns, and as part of that loop, it tries to read the invars from the mapping it generated earlier. If the invar is not defined in the mapping, it gets an UndefinedPrimal by default. Later, when concrete_aval is called on the values, it tries to concrete_aval on the UndefinedPrimal, which fails because apparently an UndefinedPrimal does not have the `"__jax_array__" `attribute, which causes the method to error out. I am not sure if UndefinedPrimals are supposed to have that attribute (they probably aren't) and I have no idea why the jaxpr generation method just suddenly decided to throw in a bunch of extra invars and constvars. Every other call I caught made a jaxpr with 0 constvars, 1 invar (a), and 0 equations, which didn't cause issues later in the backwards_pass method since it tried to iterate over the equations and immediately stopped since there aren't any. Once again, as far as I can tell, the inputs into the jaxpr generation method are identical each time.

**Comment by f0uriest** [comment]
I noticed this when working on some other stuff, but it seems like its a more general problem using `gmres` with `fori_loop` in the linear function:
```python
def bfun(x):
    out = jnp.zeros_like(x)
    def body(i, out):
        out = out.at[i].set(3*x[i])
        return out
    return jax.lax.fori_loop(0, x.size, body, out)

jax.scipy.sparse.linalg.gmres(bfun, jnp.arange(5).astype(float))
```

gives the following assertion error:
```
AssertionError                            Traceback (most recent call last)
Cell In[108], line 8
      5         return out
      6     return jax.lax.fori_loop(0, x.size, body, out)
----> 8 jax.scipy.sparse.linalg.gmres(bfun, jnp.arange(5).astype(float))

File ~/miniconda3/envs/desc/lib/python3.10/site-packages/jax/_src/scipy/sparse/linalg.py:704, in gmres(A, b, x0, tol, atol, restart, maxiter, M, solve_method)
    702 def _solve(A, b):
    703   return _gmres_solve(A, b, x0, atol, ptol, restart, maxiter, M, gmres_func)
--> 704 x = lax.custom_linear_solve(A, b, solve=_solve, transpose_solve=_solve)
    706 failed = jnp.isnan(_norm(x))
    707 info = jnp.where(failed, x=-1, y=0)

    [... skipping hidden 12 frame]

File ~/miniconda3/envs/desc/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py:718, in _scan_transpose(reduce_axes, cts, reverse, length, num_consts, num_carry, jaxpr, linear, unroll, *args)
    716 ires, _ = split_list(consts, [num_ires])
    717 _, eres = split_list(xs, [sum(xs_lin)])
--> 718 assert not any(ad.is_undefined_primal(r) for r in ires)
    719 assert not any(ad.is_undefined_primal(r) for r in eres)
    721 carry_avals, y_avals = split_list(jaxpr.out_avals, [num_carry])

AssertionError:

**Comment by peterdsharpe** [comment]
Encountering this issue too. Just to contribute another self-contained minimum-reproducible example in case anyone wants to take a look:

```python
import jax
import jax.numpy as jnp

n = 20
A = jnp.arange(n**2).reshape(n, n).astype(float) / n
b = jnp.arange(n).astype(float)
solve = jax.scipy.sparse.linalg.gmres


def A_operator(x):
    return A @ x


x, _ = solve(A_operator, b)  # This works fine


def A_operator_map(x):
    def row_compute(i):
        return A[i] @ x

    return jax.lax.map(row_compute, jnp.arange(n))


assert jnp.allclose(A_operator_map(x), A_operator(x))  # Passes; these are identical

x_map, _ = solve(A_operator_map, b)  # Raises AssertionError

assert jnp.allclose(x_map, x)
```

With `AssertionError` here:
```
File <project>/.venv/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py:769, in _scan_transpose(cts, reverse, length, num_consts, num_carry, jaxpr, linear, unroll, _split_transpose, *args)
    767 ires, _ = split_list(consts, [num_ires])
    768 _, eres = split_list(xs, [sum(xs_lin)])
--> 769 assert not any(ad.is_undefined_primal(r) for r in ires)
    770 assert not any(ad.is_undefined_primal(r) for r in eres)
    772 carry_avals, y_avals = split_list(jaxpr.out_avals, [num_carry])

AssertionError: 
```

On my JAX version, I see this error occuring with `gmres` and `bicgstab`, but not `cg`.

System info below. Running on CUDA 12:
```
--------------------------------------------------------------------------------
  Date: Sat Mar 22 19:40:15 2025 EDT

                OS : Linux (Ubuntu 24.04)
            CPU(s) : 32
           Machine : x86_64
      Architecture : 64bit
               RAM : 54.9 GiB
       Environment : Python
       File system : ext4

  Python 3.10.16 (main, Mar 17 2025, 21:01:46) [Clang 20.1.0 ]

               jax : 0.5.3
            jaxlib : 0.5.3
--------------------------------------------------------------------------------
```

Thanks Patrick for the Lineax suggestion; I'll give that a try.
