### ISSUE TITLE
Scan over parallelized xmap

### ISSUE THREAD

**Issue by rkruegs123** [google/jax#16476]
### Description

I am performing a computation that requires an outer scan, but the inner computations can be vectorized. Previously, I was just using `vmap`, but to limit memory I have been experimenting with `pmap` and `xmap`. I am on a machine with 2 x 40 GB A100s.

I quickly realized that I could not `pmap` inside of the `scan`. So, I turned to `xmap`. However, I am getting some unexpected behavior. 

First, the following code *works*:

```python
import pdb
import numpy as onp

import jax
import jax.numpy as jnp
from jax import jit, vmap, pmap
from jax.experimental.maps import xmap
from jax.sharding import Mesh


device_axis_names = ('x')
mesh_devices = onp.array(jax.devices())
assert(len(mesh_devices) == 2 and len(mesh_devices.shape) == 1)
mesh_def = (mesh_devices, device_axis_names)

def foo(x):
    return x + 3

def test_xmap():
    xs = jnp.arange(12).reshape(2, -1)

    # Option 1: Unparallelized version                                                               
    # foo_xmapped = xmap(foo, in_axes={0: 'batch'}, out_axes={0: 'batch'})                           
    # ys = foo_xmapped(xs)                                                                           

    # Option 2: Parallelized version                                                                 
    foo_xmapped = xmap(foo, in_axes={0: 'batch'}, out_axes={0: 'batch'},
                       axis_resources={'batch': 'x'})
    with Mesh(*mesh_def):
        ys = foo_xmapped(xs)

    return
test_xmap()
```
Both Options 1 and 2 work.

However, when I try to place the same computation in a scan, I get an error with Option 2:
```python
def test_xmap_scan():

    def scan_fn(sm, i):
        xs = jnp.arange(12).reshape(2, -1)

        # Option 1: Unparallelized version                                                           
        # foo_xmapped = xmap(foo, in_axes={0: 'batch'}, out_axes={0: 'batch'})                       
        # ys = foo_xmapped(xs)                                                                       

        # Option 2: Parallelized version                                                             
        foo_xmapped = xmap(foo, in_axes={0: 'batch'}, out_axes={0: 'batch'}, axis_resources={'batch'\
: 'x'})
        ys = foo_xmapped(xs)

        sm += ys.sum()
        return sm, None

    with Mesh(*mesh_def):
        fin_sm, _ = jax.lax.scan(scan_fn, 0.0, jnp.arange(4))

    return fin_sm
test_xmap_scan()
```
This yields the following error:
```
Traceback (most recent call last):
  File "/home/ryan/scan_pmap_test.py", line 115, in <module>
    test_xmap_scan()
  File "/home/ryan/scan_pmap_test.py", line 100, in test_xmap_scan
    fin_sm, _ = jax.lax.scan(scan_fn, 0.0, jnp.arange(4))
  File "/home/ryan/scan_pmap_test.py", line 94, in scan_fn
    ys = foo_xmapped(xs)
jax._src.source_info_util.JaxStackTraceBeforeTransformation: NameError: unbound axis name: x. The following axis names (e.g. defined by pmap) are available to collective operations: []
```

To be clear, I understand that this computation doesn't require a `scan`, but it is a minimal example of my failing use case. Practically, I need a way to distribute computation within a scan over multiple devices. 

I have also seen `shmap` but haven't tried it yet.

Thank you in advance for your help.

### What jax/jaxlib version are you using?

jax v0.4.11, jaxlib v0.4.11+cuda12.cudnn88

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.9.16, Debian 11

### NVIDIA GPU info

```
Mon Jun 19 16:33:12 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-SXM4-40GB           Off| 00000000:00:04.0 Off |                    0 |
| N/A   34C    P0               61W / 400W|      0MiB / 40960MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM4-40GB           Off| 00000000:00:05.0 Off |                    0 |
| N/A   35C    P0               61W / 400W|      0MiB / 40960MiB |     27%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

**Comment by acse-itk22** [comment]
Hi, I am encountering the same error. Has there been any updates on this @apaszke?

**Comment by apaszke** [comment]
xmap was removed from JAX, so this is obsolete
