### ISSUE TITLE
error, building from source on centos 7

### ISSUE THREAD

**Issue by mgbukov** [google/jax#1659]
Following #854, I tried [building from source](https://jax.readthedocs.io/en/latest/developer.html#building-from-source) but ran into trouble:

```
(jax) [mbukov@scc1 jax]$ python build/build.py --enable_cuda

     _   _  __  __
    | | / \ \ \/ /
 _  | |/ _ \ \  /
| |_| / ___ \/  \
 \___/_/   \/_/\_\


WARNING: Output base '/usr3/graduate/mbukov/.cache/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a' is on NFS. This may lead to surprising failures and undetermined behavior.
Starting local Bazel server and connecting to it...
Bazel binary path: ./bazel-0.29.1-linux-x86_64
Python binary path: /usr3/graduate/mbukov/.conda/envs/jax/bin/python
MKL-DNN enabled: yes
-march=native: no
CUDA enabled: yes

Building XLA and installing it in the jaxlib source tree...
WARNING: Output base '/usr3/graduate/mbukov/.cache/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a' is on NFS. This may lead to surprising failures and undetermined behavior.
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
INFO: Call stack for the definition of repository 'org_tensorflow' which is a http_archive (rule definition at /usr3/graduate/mbukov/.cache/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/bazel_tools/tools/build_defs/repo/http.bzl:262:16):
 - /usr3/graduate/mbukov/jax/WORKSPACE:24:1
Loading: 0 packages loaded
INFO: Repository 'org_tensorflow' used the following cache hits instead of downloading the corresponding file.
 * Hash '508eb48faee23f318ab18075af522527074fc67780ac8ff127d21a5a5d1a71cf' for https://github.com/tensorflow/tensorflow/archive/d325350fe6db8ef2dda9d94e1551b831980d1115.tar.gz
If the definition of 'org_tensorflow' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'org_tensorflow':
   java.io.IOException: Error extracting /usr3/graduate/mbukov/.cache/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/d325350fe6db8ef2dda9d94e1551b831980d1115.tar.gz to /usr3/graduate/mbukov/.cache/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow: error when closing file
ERROR: no such package '@org_tensorflow//tensorflow': java.io.IOException: Error extracting /usr3/graduate/mbukov/.cache/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/d325350fe6db8ef2dda9d94e1551b831980d1115.tar.gz to /usr3/graduate/mbukov/.cache/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow: error when closing file
ERROR: no such package '@org_tensorflow//tensorflow': java.io.IOException: Error extracting /usr3/graduate/mbukov/.cache/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/d325350fe6db8ef2dda9d94e1551b831980d1115.tar.gz to /usr3/graduate/mbukov/.cache/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow: error when closing file
INFO: Elapsed time: 32.609s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully (0 packages loaded)
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: java.io.IOException: error when closing file
	at com.google.devtools.build.lib.runtime.CommandLogModule.commandComplete(CommandLogModule.java:86)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.afterCommand(BlazeRuntime.java:650)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:526)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:192)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:573)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:624)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: error when closing file
	at com.google.devtools.build.lib.unix.NativePosixFiles.close(Native Method)
	at com.google.devtools.build.lib.unix.UnixFileSystem$NativeFileOutputStream.close(UnixFileSystem.java:474)
	at com.google.devtools.build.lib.runtime.CommandLogModule.commandComplete(CommandLogModule.java:84)
	... 6 more
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: java.io.IOException: error when closing file
	at com.google.devtools.build.lib.runtime.CommandLogModule.commandComplete(CommandLogModule.java:86)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.afterCommand(BlazeRuntime.java:650)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:526)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:192)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:573)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:624)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: error when closing file
	at com.google.devtools.build.lib.unix.NativePosixFiles.close(Native Method)
	at com.google.devtools.build.lib.unix.UnixFileSystem$NativeFileOutputStream.close(UnixFileSystem.java:474)
	at com.google.devtools.build.lib.runtime.CommandLogModule.commandComplete(CommandLogModule.java:84)
	... 6 more
java.lang.RuntimeException: java.io.IOException: error when closing file
	at com.google.devtools.build.lib.runtime.CommandLogModule.commandComplete(CommandLogModule.java:86)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.afterCommand(BlazeRuntime.java:650)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:526)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:192)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:573)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:624)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: error when closing file
	at com.google.devtools.build.lib.unix.NativePosixFiles.close(Native Method)
	at com.google.devtools.build.lib.unix.UnixFileSystem$NativeFileOutputStream.close(UnixFileSystem.java:474)
	at com.google.devtools.build.lib.runtime.CommandLogModule.commandComplete(CommandLogModule.java:84)
	... 6 more
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: java.io.IOException: error when closing file
	at com.google.devtools.build.lib.runtime.CommandLogModule.commandComplete(CommandLogModule.java:86)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.afterCommand(BlazeRuntime.java:650)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:526)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:192)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:573)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:624)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: error when closing file
	at com.google.devtools.build.lib.unix.NativePosixFiles.close(Native Method)
	at com.google.devtools.build.lib.unix.UnixFileSystem$NativeFileOutputStream.close(UnixFileSystem.java:474)
	at com.google.devtools.build.lib.runtime.CommandLogModule.commandComplete(CommandLogModule.java:84)
	... 6 more
java.lang.RuntimeException: java.io.IOException: error when closing file
	at com.google.devtools.build.lib.runtime.CommandLogModule.commandComplete(CommandLogModule.java:86)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.afterCommand(BlazeRuntime.java:650)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:526)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:192)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:573)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:624)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: error when closing file
	at com.google.devtools.build.lib.unix.NativePosixFiles.close(Native Method)
	at com.google.devtools.build.lib.unix.UnixFileSystem$NativeFileOutputStream.close(UnixFileSystem.java:474)
	at com.google.devtools.build.lib.runtime.CommandLogModule.commandComplete(CommandLogModule.java:84)
	... 6 more
Traceback (most recent call last):
  File "build/build.py", line 345, in <module>
    main()
  File "build/build.py", line 340, in main
    [":install_xla_in_source_tree", os.getcwd()])
  File "build/build.py", line 50, in shell
    output = subprocess.check_output(cmd)
  File "/usr3/graduate/mbukov/.conda/envs/jax/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr3/graduate/mbukov/.conda/envs/jax/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./bazel-0.29.1-linux-x86_64', 'run', '--verbose_failures=true', '--config=mkl_open_source_only', '--config=cuda', ':install_xla_in_source_tree', '/usr3/graduate/mbukov/jax/build']' returned non-zero exit status 37.
```

**Comment by hawkinsp** [comment]
I think this warning is relevant.
```
WARNING: Output base '/usr3/graduate/mbukov/.cache/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a' is on NFS. This may lead to surprising failures and undetermined behavior.
```

Can you try using a non-NFS directory for your bazel cache? (I don't know how to do that specifically but I would guess the bazel docs describe it; failing that making `~/.cache/bazel` a symlink to somewhere else would probably work.)

**Comment by mgbukov** [comment]
Yes, running `export TEST_TMPDIR=/tmp/bazel` suppressed the warning. But I'm not quite there yet.

I located the `cuda.h` file and passed the path to the installer; now it seems to be complaining about the cuda version. Running `nvcc --version` shows `Cuda compilation tools, release 10.1, V10.1.105`. Any suggestions how to fix this?

```
(jax) [mbukov@scc1 jax]$ python build/build.py --enable_cuda --cuda_path /usr/include/linux/

     _   _  __  __
    | | / \ \ \/ /
 _  | |/ _ \ \  /
| |_| / ___ \/  \
 \___/_/   \/_/\_\


$TEST_TMPDIR defined: output root default is '/tmp/bazel' and max_idle_secs default is '15'.
Starting local Bazel server and connecting to it...
Bazel binary path: ./bazel-0.29.1-linux-x86_64
Python binary path: /usr3/graduate/mbukov/.conda/envs/jax/bin/python
MKL-DNN enabled: yes
-march=native: no
CUDA enabled: yes
CUDA toolkit path: /usr/include/linux/

Building XLA and installing it in the jaxlib source tree...
$TEST_TMPDIR defined: output root default is '/tmp/bazel' and max_idle_secs default is '15'.
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
INFO: Call stack for the definition of repository 'local_config_cuda' which is a cuda_configure (rule definition at /tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/cuda_configure.bzl:1306:18):
 - /tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/tensorflow/workspace.bzl:71:5
 - /tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/tensorflow/workspace.bzl:61:5
 - /usr3/graduate/mbukov/jax/WORKSPACE:41:1
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
	File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1304
		_create_local_cuda_repository(repository_ctx)
	File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1006, in _create_local_cuda_repository
		_get_cuda_config(repository_ctx)
	File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 729, in _get_cuda_config
		find_cuda_config(repository_ctx, ["cuda", "cudnn"])
	File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 709, in find_cuda_config
		auto_configure_fail(("Failed to run find_cuda_config...))
	File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 340, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Failed to run find_cuda_config.py: Traceback (most recent call last):
  File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/find_cuda_config.py", line 500, in <module>
    main()
  File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/find_cuda_config.py", line 492, in main
    for key, value in sorted(find_cuda_config().items()):
  File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/find_cuda_config.py", line 457, in find_cuda_config
    result.update(_find_cuda_config(cuda_paths, cuda_version))
  File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/find_cuda_config.py", line 251, in _find_cuda_config
    get_header_version)
  File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/find_cuda_config.py", line 238, in _find_header
    required_version, get_version)
  File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/find_cuda_config.py", line 227, in _find_versioned_file
    actual_version = get_version(file)
  File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/find_cuda_config.py", line 244, in get_header_version
    version = int(_get_header_version(path, "CUDA_VERSION"))
ValueError: invalid literal for int() with base 10: ''

ERROR: Skipping ':install_xla_in_source_tree': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1304
		_create_local_cuda_repository(repository_ctx)
	File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1006, in _create_local_cuda_repository
		_get_cuda_config(repository_ctx)
	File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 729, in _get_cuda_config
		find_cuda_config(repository_ctx, ["cuda", "cudnn"])
	File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 709, in find_cuda_config
		auto_configure_fail(("Failed to run find_cuda_config...))
	File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 340, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Failed to run find_cuda_config.py: Traceback (most recent call last):
  File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/find_cuda_config.py", line 500, in <module>
    main()
  File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/find_cuda_config.py", line 492, in main
    for key, value in sorted(find_cuda_config().items()):
  File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/find_cuda_config.py", line 457, in find_cuda_config
    result.update(_find_cuda_config(cuda_paths, cuda_version))
  File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/find_cuda_config.py", line 251, in _find_cuda_config
    get_header_version)
  File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/find_cuda_config.py", line 238, in _find_header
    required_version, get_version)
  File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/find_cuda_config.py", line 227, in _find_versioned_file
    actual_version = get_version(file)
  File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/find_cuda_config.py", line 244, in get_header_version
    version = int(_get_header_version(path, "CUDA_VERSION"))
ValueError: invalid literal for int() with base 10: ''

WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1304
		_create_local_cuda_repository(repository_ctx)
	File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1006, in _create_local_cuda_repository
		_get_cuda_config(repository_ctx)
	File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 729, in _get_cuda_config
		find_cuda_config(repository_ctx, ["cuda", "cudnn"])
	File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 709, in find_cuda_config
		auto_configure_fail(("Failed to run find_cuda_config...))
	File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 340, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Failed to run find_cuda_config.py: Traceback (most recent call last):
  File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/find_cuda_config.py", line 500, in <module>
    main()
  File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/find_cuda_config.py", line 492, in main
    for key, value in sorted(find_cuda_config().items()):
  File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/find_cuda_config.py", line 457, in find_cuda_config
    result.update(_find_cuda_config(cuda_paths, cuda_version))
  File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/find_cuda_config.py", line 251, in _find_cuda_config
    get_header_version)
  File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/find_cuda_config.py", line 238, in _find_header
    required_version, get_version)
  File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/find_cuda_config.py", line 227, in _find_versioned_file
    actual_version = get_version(file)
  File "/tmp/bazel/_bazel_mbukov/b2fea789f5f1264c27f5e95048996d5a/external/org_tensorflow/third_party/gpus/find_cuda_config.py", line 244, in get_header_version
    version = int(_get_header_version(path, "CUDA_VERSION"))
ValueError: invalid literal for int() with base 10: ''

INFO: Elapsed time: 4.856s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully (0 packages loaded)
Traceback (most recent call last):
  File "build/build.py", line 345, in <module>
    main()
  File "build/build.py", line 340, in main
    [":install_xla_in_source_tree", os.getcwd()])
  File "build/build.py", line 50, in shell
    output = subprocess.check_output(cmd)
  File "/usr3/graduate/mbukov/.conda/envs/jax/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr3/graduate/mbukov/.conda/envs/jax/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./bazel-0.29.1-linux-x86_64', 'run', '--verbose_failures=true', '--config=mkl_open_source_only', '--config=cuda', ':install_xla_in_source_tree', '/usr3/graduate/mbukov/jax/build']' returned non-zero exit status 1.
```

**Comment by jekbradbury** [comment]
The `--cuda_path` flag should be the toolkit directory (containing CUDA shared libraries and headers; often `/usr/local/cuda`), not a global include directory. Unfortunately, TF/XLA doesn't play very well with the distro-provided CUDA packages in some Linuxes; if there's no toolkit directory, there's no great way to give the installer what it wants (options include reinstalling CUDA using NVIDIA's RPMs, or constructing a fake toolkit directory using symlinks...)

**Comment by hawkinsp** [comment]
I'm guessing this issue is stale (much has changed since then!) Please open a new issue if there's still a problem.
