### ISSUE TITLE
CUDA_ERROR_INVALID_IMAGE: device kernel image is invalid; current tracing scope: fusion; current profiling annotation: XlaModule

### ISSUE THREAD

**Issue by Dharmendra04** [google/jax#16765]
### Description

2023-07-16 21:25:08.343505: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-07-16 21:25:08.942423: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
I0716 21:25:08.991377 140319043823424 xla_bridge.py:603] Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: CUDA Interpreter
I0716 21:25:08.991567 140319043823424 xla_bridge.py:603] Unable to initialize backend 'tpu': module 'jaxlib.xla_extension' has no attribute 'get_tpu_client'
2023-07-16 21:25:10.101890: W external/xla/xla/stream_executor/gpu/asm_compiler.cc:231] Falling back to the CUDA driver for PTX compilation; ptxas does not support CC 8.9
2023-07-16 21:25:10.101905: W external/xla/xla/stream_executor/gpu/asm_compiler.cc:234] Used ptxas at ptxas
2023-07-16 21:25:10.115792: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:548] failed to load PTX text as a module: CUDA_ERROR_INVALID_IMAGE: device kernel image is invalid
2023-07-16 21:25:10.115803: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:553] error log buffer (63 bytes): error   : Binary format for key='0', ident='' is not recognize
2023-07-16 21:25:10.115814: W external/xla/xla/service/gpu/runtime/support.cc:58] Intercepted XLA runtime error:
INTERNAL: Failed to load PTX text as a module: CUDA_ERROR_INVALID_IMAGE: device kernel image is invalid
2023-07-16 21:25:10.115856: E external/xla/xla/pjrt/pjrt_stream_executor_client.cc:2461] Execution of replica 0 failed: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.func.launch' failed: Failed to load PTX text as a module: CUDA_ERROR_INVALID_IMAGE: device kernel image is invalid; current tracing scope: fusion; current profiling annotation: XlaModule:#hlo_module=jit__threefry_seed,program_id=0#.
Traceback (most recent call last):
  File "/home/dharmendra/Desktop/snerg_modified/train.py", line 337, in <module>
    app.run(main)
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/home/dharmendra/Desktop/snerg_modified/train.py", line 148, in main
    rng = random.PRNGKey(20200823)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/jax/_src/random.py", line 160, in PRNGKey
    key = prng.seed_with_impl(impl, seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/jax/_src/prng.py", line 406, in seed_with_impl
    return random_seed(seed, impl=impl)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/jax/_src/prng.py", line 690, in random_seed
    return random_seed_p.bind(seeds_arr, impl=impl)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/jax/_src/prng.py", line 702, in random_seed_impl
    base_arr = random_seed_impl_base(seeds, impl=impl)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/jax/_src/prng.py", line 707, in random_seed_impl_base
    return seed(seeds)
           ^^^^^^^^^^^
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/jax/_src/prng.py", line 936, in threefry_seed
    return _threefry_seed(seed)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/jax/_src/pjit.py", line 250, in cache_miss
    outs, out_flat, out_tree, args_flat, jaxpr = _python_pjit_helper(
                                                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/jax/_src/pjit.py", line 163, in _python_pjit_helper
    out_flat = pjit_p.bind(*args_flat, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/jax/_src/core.py", line 2677, in bind
    return self.bind_with_trace(top_trace, args, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/jax/_src/core.py", line 815, in process_primitive
    return primitive.impl(*tracers, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/jax/_src/pjit.py", line 1203, in _pjit_call_impl
    return xc._xla.pjit(name, f, call_impl_cache_miss, [], [], donated_argnums,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/jax/_src/pjit.py", line 1187, in call_impl_cache_miss
    out_flat, compiled = _pjit_call_impl_python(
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/jax/_src/pjit.py", line 1143, in _pjit_call_impl_python
    return compiled.unsafe_call(*args), compiled
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1349, in __call__
    results = self.xla_executable.execute_sharded(input_bufs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.func.launch' failed: Failed to load PTX text as a module: CUDA_ERROR_INVALID_IMAGE: device kernel image is invalid; current tracing scope: fusion; current profiling annotation: XlaModule:#hlo_module=jit__threefry_seed,program_id=0#.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/dharmendra/Desktop/snerg_modified/train.py", line 337, in <module>
    app.run(main)
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/home/dharmendra/Desktop/snerg_modified/train.py", line 148, in main
    rng = random.PRNGKey(20200823)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/jax/_src/random.py", line 160, in PRNGKey
    key = prng.seed_with_impl(impl, seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/jax/_src/prng.py", line 406, in seed_with_impl
    return random_seed(seed, impl=impl)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/jax/_src/prng.py", line 690, in random_seed
    return random_seed_p.bind(seeds_arr, impl=impl)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/jax/_src/core.py", line 380, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/jax/_src/core.py", line 815, in process_primitive
    return primitive.impl(*tracers, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/jax/_src/prng.py", line 702, in random_seed_impl
    base_arr = random_seed_impl_base(seeds, impl=impl)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/jax/_src/prng.py", line 707, in random_seed_impl_base
    return seed(seeds)
           ^^^^^^^^^^^
  File "/home/dharmendra/anaconda3/envs/snerg3/lib/python3.11/site-packages/jax/_src/prng.py", line 936, in threefry_seed
    return _threefry_seed(seed)
           ^^^^^^^^^^^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.func.launch' failed: Failed to load PTX text as a module: CUDA_ERROR_INVALID_IMAGE: device kernel image is invalid; current tracing scope: fusion; current profiling annotation: XlaModule:#hlo_module=jit__threefry_seed,program_id=0#.

### What jax/jaxlib version are you using?

JAX version: 0.4.13, jaxlib version: 0.4.13,flax : 0.7.0, tensorflow:2.13.0

### Which accelerator(s) are you using?

GPU

### Additional system info

python 3.11.0

### NVIDIA GPU info

Mon Jul 17 17:06:39 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  Off |
|  0%   52C    P8    24W / 450W |    367MiB / 24564MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2020      G   /usr/lib/xorg/Xorg                160MiB |
|    0   N/A  N/A      2151      G   /usr/bin/gnome-shell               38MiB |
|    0   N/A  N/A      3362      G   ...0/usr/lib/firefox/firefox      144MiB |
|    0   N/A  N/A     16285      G   ...b/thunderbird/thunderbird       21MiB |
+-----------------------------------------------------------------------------+

**Comment by hawkinsp** [comment]
What CUDA version do you have installed? How did you install JAX?

Can you try installing JAX via the `cuda12_pip` packages?

**Comment by Dharmendra04** [comment]
I used this code to install Jax: pip install --upgrade "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

This is my cuda version,
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0

**Comment by hawkinsp** [comment]
Can you show the output of `pip list`?

It looks to me like the version of CUDA that's installed is too old for JAX. 

Perhaps retry with a fresh virtual enviroment?

**Comment by Dharmendra04** [comment]
---------------------------- ---------------------
absl-py                      1.4.0
astunparse                   1.6.3
cachetools                   5.3.1
certifi                      2023.5.7
charset-normalizer           3.2.0
chex                         0.1.81
contourpy                    1.1.0
cycler                       0.11.0
dm-tree                      0.1.8
etils                        1.3.0
flatbuffers                  23.5.26
flax                         0.7.0
fonttools                    4.41.0
gast                         0.4.0
google-auth                  2.22.0
google-auth-oauthlib         1.0.0
google-pasta                 0.2.0
grpcio                       1.56.0
h5py                         3.9.0
idna                         3.4
importlib-resources          6.0.0
jax                          0.4.13
jaxlib                       0.4.13+cuda12.cudnn89
keras                        2.13.1
kiwisolver                   1.4.4
libclang                     16.0.6
Markdown                     3.4.3
markdown-it-py               3.0.0
MarkupSafe                   2.1.3
matplotlib                   3.7.2
mdurl                        0.1.2
ml-dtypes                    0.2.0
msgpack                      1.0.5
nest-asyncio                 1.5.6
numpy                        1.24.3
nvidia-cublas-cu12           12.2.1.16
nvidia-cuda-cupti-cu12       12.2.60
nvidia-cuda-nvcc-cu12        12.2.91
nvidia-cuda-runtime-cu12     12.2.53
nvidia-cudnn-cu12            8.9.2.26
nvidia-cufft-cu12            11.0.8.15
nvidia-cusolver-cu12         11.5.0.53
nvidia-cusparse-cu12         12.1.1.53
nvidia-nvjitlink-cu12        12.2.91
oauthlib                     3.2.2
opencv-python                4.8.0.74
opt-einsum                   3.3.0
optax                        0.1.5
orbax-checkpoint             0.2.7
packaging                    23.1
Pillow                       10.0.0
pip                          22.3.1
protobuf                     4.23.4
pyasn1                       0.5.0
pyasn1-modules               0.3.0
Pygments                     2.15.1
pyparsing                    3.0.9
python-dateutil              2.8.2
python-version               0.0.2
PyYAML                       6.0
requests                     2.31.0
requests-oauthlib            1.3.1
rich                         13.4.2
rsa                          4.9
scipy                        1.11.1
setuptools                   65.5.1
six                          1.16.0
tensorboard                  2.13.0
tensorboard-data-server      0.7.1
tensorflow                   2.13.0
tensorflow-estimator         2.13.0
tensorflow-hub               0.14.0
tensorflow-io-gcs-filesystem 0.32.0
tensorstore                  0.1.40
termcolor                    2.3.0
toolz                        0.12.0
typing_extensions            4.5.0
urllib3                      1.26.16
Werkzeug                     2.3.6
wheel                        0.38.4
wrapt                        1.15.0
zipp                         3.16.2

This is my pip list. Please let me know what went wrong in my installation.

**Comment by JYC1012** [comment]
I have the same issue

**Comment by hawkinsp** [comment]
I suspect this issue is stale, but if you install `jax` and `jaxlib` 0.4.17, they now have much stricter CUDA version checking that would probably give us a big clue about what went wrong here. Closing, but feel free to ping this issue if you have updates and I can reopen it.
