### ISSUE TITLE
jaxlib does not build on macOS

### ISSUE THREAD

**Issue by jessebett** [google/jax#1689]
I created a fresh conda `python=3.7` environment and cloned `jax/master` then following the install instructions I am unable to build successfully with `python build/build.py`:

Very long error message
```
Bazel binary path: ./bazel-0.29.1-darwin-x86_64
Python binary path: /Users/jesse/anaconda3/envs/jaxjet/bin/python
MKL-DNN enabled: yes
-march=native: no
CUDA enabled: no

Building XLA and installing it in the jaxlib source tree...
Loading:
Loading: 0 packages loaded
Analyzing: target //build:install_xla_in_source_tree (0 packages loaded, 0 targets configured)
WARNING: /private/var/tmp/_bazel_jesse/d311aee84acccd8d086529fc1296a726/external/org_tensorflow/tensorflow/core/BUILD:2199:12: in srcs attribute of cc_library rule @org_tensorflow//tensorflow/core:lib_internal_impl: please do not import '@org_tensorflow//tensorflow/core/platform:abi.h' directly. You should either move the file to this package or depend on an appropriate rule there

....
....

ERROR: /private/var/tmp/_bazel_jesse/d311aee84acccd8d086529fc1296a726/external/com_google_protobuf/BUILD:106:1: C++ compilation of rule '@com_google_protobuf//:protobuf_lite' failed (Exit 1)
external/com_google_protobuf/src/google/protobuf/arena.cc:53:13: error: use of undeclared identifier 'LifecycleId'
std::atomic<LifecycleId> ArenaImpl::lifecycle_id_generator_;
            ^
1 error generated.
Target //build:install_xla_in_source_tree failed to build
INFO: Elapsed time: 2.137s, Critical Path: 1.54s
INFO: 20 processes: 20 local.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "build/build.py", line 345, in <module>
    main()
  File "build/build.py", line 340, in main
    [":install_xla_in_source_tree", os.getcwd()])
  File "build/build.py", line 50, in shell
    output = subprocess.check_output(cmd)
  File "/Users/jesse/anaconda3/envs/jaxjet/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/Users/jesse/anaconda3/envs/jaxjet/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./bazel-0.29.1-darwin-x86_64', 'run', '--verbose_failures=true', '--config=mkl_open_source_only', ':install_xla_in_source_tree', '/Users/jesse/pensieve/jax/build']' returned non-zero exit status 1.
```

**Comment by hawkinsp** [comment]
Odd. I just built and pushed new jaxlib wheels on Mac (0.1.33). Perhaps try those?

My guess is that `jaxlib` is using a bad version of XLA/TF at the moment.

**Comment by hawkinsp** [comment]
Did you try the prebuilt pip wheels of `jaxlib`? They are up to date. I can't think of any reason to prefer building from source yourself on Mac.

I can't reproduce the build failure, but you might try again given we have updated the XLA release recently.

**Comment by jessebett** [comment]
@hawkinsp I haven't tried to build again, I was using an old wheels of jaxlib with the updated local jax, which had incompatible versions. Using the new prebuilt wheels works with my local fork of jax, so I'm going to close this issue. Thanks.
