### ISSUE TITLE
ModuleNotFoundError: No module named 'requests' when executing `jax.distributed.initialize()` on TPU Pods

### ISSUE THREAD

**Issue by ayaka14732** [google/jax#17075]
### Description

```python
import jax
jax.distributed.initialize()
```

Error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ayaka/nfs_share/venv/lib/python3.11/site-packages/jax/_src/distributed.py", line 168, in initialize
    global_state.initialize(coordinator_address, num_processes, process_id, local_device_ids)
  File "/home/ayaka/nfs_share/venv/lib/python3.11/site-packages/jax/_src/distributed.py", line 47, in initialize
    clusters.ClusterEnv.auto_detect_unset_distributed_params(
  File "/home/ayaka/nfs_share/venv/lib/python3.11/site-packages/jax/_src/clusters/cluster.py", line 55, in auto_detect_unset_distributed_params
    coordinator_address = env.get_coordinator_address()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ayaka/nfs_share/venv/lib/python3.11/site-packages/jax/_src/clusters/cloud_tpu_cluster.py", line 54, in get_coordinator_address
    return cls._get_worker_endpoints()[0].split(':')[2] + ':8476'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ayaka/nfs_share/venv/lib/python3.11/site-packages/jax/_src/clusters/cloud_tpu_cluster.py", line 74, in _get_worker_endpoints
    return get_metadata('worker-network-endpoints').split(',')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ayaka/nfs_share/venv/lib/python3.11/site-packages/jax/_src/clusters/cloud_tpu_cluster.py", line 23, in get_metadata
    import requests  # pytype: disable=import-error
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'requests'
```

I think `requests` should be automatically installed when installing JAX.

### What jax/jaxlib version are you using?

jax 0.4.14

### Which accelerator(s) are you using?

TPU

**Comment by jakevdp** [comment]
Thanks - I think that makes sense. It looks like requests is only imported in `jax/_src/clusters/cloud_tpu_cluster.py`, so it would probably be better as a TPU-only requirement. Perhaps we could include it in in the optional requirements for `jax[tpu]`?

Tagging @skye who knows a lot more about cloud TPU runtimes – what do you think?

**Comment by skye** [comment]
I agree it should be required for `jax[tpu]`. I think it used to be at some point actually, but was removed because we didn't need it anymore (but now we do!).
