### ISSUE TITLE
disable_jit array promotion issue

### ISSUE THREAD

**Issue by cgiovanetti** [google/jax#17156]
### Description

I was having some trouble running the `diffrax` package with jit disabled using `config.update('jax_disable_jit', True)` (see https://github.com/patrick-kidger/diffrax/issues/293).  @patrick-kidger looked deeper into the issue and found that it might be an issue with JAX itself, minimizing the issue down to the following snippet:

```
import jax
import jax.config as config
import jax.numpy as jnp
import jax.lax as lax

# No error if the next line is commented out
config.update("jax_disable_jit", True)

def cond(x):
    assert isinstance(x, jax.Array)
    return x

def body(x):
    return False

lax.while_loop(cond, body, jnp.array(True))
```

When I run this code with the disable_jit line uncommented, I get the following error message:
```
Traceback (most recent call last):
  File "<filepath>/jit_issue.py", line 16, in <module>
    lax.while_loop(cond, body, jnp.array(True))
  File "/ext3/miniconda3/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/ext3/miniconda3/lib/python3.9/site-packages/jax/_src/lax/control_flow/loops.py", line 1120, in while_loop
    while cond_fun(val):
  File "<filepath>/jit_issue.py", line 10, in cond
    assert isinstance(x, jax.Array)
jax._src.traceback_util.UnfilteredStackTrace: AssertionError

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<filepath>/jit_issue.py", line 16, in <module>
    lax.while_loop(cond, body, jnp.array(True))
  File "<filepath>/jit_issue.py", line 10, in cond
    assert isinstance(x, jax.Array)
AssertionError
```

### What jax/jaxlib version are you using?

jax v0.4.13, jaxlib v0.4.13

### Which accelerator(s) are you using?

GPU

### NVIDIA GPU info

```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla V100-PCIE-32GB           On  | 00000000:2F:00.0 Off |                    0 |
| N/A   28C    P0              23W / 250W |      0MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

**Comment by jakevdp** [comment]
Hi - thanks for the report!

I'm not sure whether or not this behavior should be considered a bug – the reason that the Python `False` returned by `body_fun` gets converted to `jax.Array` is *because* `body_fun` is JIT-compiled by default. When you explicitly disable JIT, you are no longer wrapping `body_fun` in `jit`, and so this conversion doesn't happen. It's not hard to imagine a situation where this is the intended behavior when someone uses `disable_jit`.

I think the best fix in this case would be in user code: if it's important that with JIT disabled, `body_fun` returns a `jax.Array` rather than a different array-like value, you should do it explicitly; e.g.
```python
def body(x):
    return jnp.array(False)
```
What do you think?

**Comment by patrick-kidger** [comment]
FWIW my interpretation was that all HOP were meant to upcast arguments to arrays by definition. Or perhaps more pragmatically: this is a case where disabling JIT breaks otherwise-acceptable user code.

I can easily work around this in Equinox/Diffrax if this is declared intended behaviour, though.
