### ISSUE TITLE
MNIST example runtime crash

### ISSUE THREAD

**Issue by zafarali** [google/jax#172]
I am trying to run the MNIST example in a Colab but the kernel dies on line:

`_, init_params = init_random_params((-1, 28 * 28))`

Any ideas on how to start debugging this?

**Comment by mattjj** [comment]
Thanks for flagging this.

Are you able to run examples/mnist_classifier.py directly in your terminal emulator (using `python`, without a colab)? That might give a better error message for us to work with.

**Comment by zafarali** [comment]
Hmm, I'm getting a segfault when I import jax now. I installed using `pip install --upgrade jax jaxlib` into a python 3.6 venv. Are the binaries built for 3.7?

```
(py36torch04) Zafaralis-MacBook-Pro-2% python3 mnist_classifier.py
/Users/zaf/anaconda/envs/py36torch04/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.7 of module 'lapack' does not match runtime version 3.6
  return f(*args, **kwds)
Traceback (most recent call last):
  File "mnist_classifier.py", line 28, in <module>
    import jax.numpy as np
  File "/Users/zaf/anaconda/envs/py36torch04/lib/python3.6/site-packages/jax/__init__.py", line 18, in <module>
    import jax.numpy as np  # side-effecting import sets up operator overloads
  File "/Users/zaf/anaconda/envs/py36torch04/lib/python3.6/site-packages/jax/numpy/__init__.py", line 18, in <module>
    from . import linalg
  File "/Users/zaf/anaconda/envs/py36torch04/lib/python3.6/site-packages/jax/numpy/linalg.py", line 24, in <module>
    from .. import lax_linalg
  File "/Users/zaf/anaconda/envs/py36torch04/lib/python3.6/site-packages/jax/lax_linalg.py", line 31, in <module>
    from jaxlib import lapack
  File "jaxlib/lapack.pyx", line 72, in init lapack
  File "jaxlib/lapack.pyx", line 37, in lapack.register_cpu_custom_call_target
  File "/Users/zaf/anaconda/envs/py36torch04/lib/python3.6/site-packages/jaxlib/xla_client.py", line 1561, in register_cpu_custom_call_target
    c_api.RegisterCpuCustomCallTarget(name, fn)
UnboundLocalError: local variable 'name' referenced before assignment
[1]    9904 segmentation fault  python3 mnist_classifier.py
```

**Comment by zafarali** [comment]
Btw this one that's given in the README works fine: https://colab.research.google.com/github/google/jax/blob/master/notebooks/neural_network_and_data_loading.ipynb#scrollTo=X2DnZo3iYj18

**Comment by hawkinsp** [comment]
I just uploaded a new version of jaxlib, which has wheels for Python 2.7, 3.6, and 3.7. Please try it out — it should fix the crash.

If using CPU only, then
pip install --upgrade jaxlib
should do the trick.

Closing, but feel free to reopen if you still have problems.
