### ISSUE TITLE
Segmentation fault in compiling function with large global variable

### ISSUE THREAD

**Issue by Findus23** [google/jax#17222]
### Description

The following short python script causes a segmentation fault when jit-compiling the function that uses a huge external variable:
```python
import jax
from jax import numpy as jnp, jit

key = jax.random.PRNGKey(42)
N = 1024

W = jax.random.normal(key, shape=(N, N, N))


def func():
    rho0 = jnp.zeros((N, N, N))
    return rho0 * W


func = jit(func)
print("compiler")
hlo = func.lower().compile().as_text()
print("run jit")
rho0 = func()
```

```
2023-08-22 17:11:21.337553: W external/xla/xla/service/gpu/nvptx_compiler.cc:698] The NVIDIA driver's CUDA version is 11.6 which is older than the ptxas CUDA version (11.8.89). Because the driver is older than the ptxas version, XLA is disabling parallel compilation, which may slow down compilation. You should update your NVIDIA driver or use the NVIDIA-provided CUDA forward compatibility packages.
compiler
Segmentation fault (core dumped)
```

I understand that this should not be done and can be very inefficient (https://github.com/google/jax/issues/10596).
But getting a segmentation fault instead of a warning makes it very hard to figure this out.

```text
> pip freeze
jax==0.4.14
jaxlib==0.4.14+cuda11.cudnn86
nvidia-cublas-cu11==11.11.3.6
nvidia-cuda-cupti-cu11==11.8.87
nvidia-cuda-nvcc-cu11==11.8.89
nvidia-cuda-nvrtc-cu11==11.8.89
nvidia-cuda-runtime-cu11==11.8.89
nvidia-cudnn-cu11==8.9.4.25
nvidia-cufft-cu11==10.9.0.58
nvidia-cusolver-cu11==11.4.1.48
nvidia-cusparse-cu11==11.7.5.86
...
```

### What jax/jaxlib version are you using?

jax==0.4.14, jaxlib==0.4.14+cuda11.cudnn86

### Which accelerator(s) are you using?

GPU (2x Nvidia A40)

### Additional system info

Python 3.11.3

### NVIDIA GPU info

```text
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.39.01    Driver Version: 510.39.01    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A40          Off  | 00000000:41:00.0 Off |                    0 |
|  0%   34C    P0    75W / 300W |      0MiB / 46068MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A40          Off  | 00000000:A1:00.0 Off |                    0 |
|  0%   33C    P0    68W / 300W |      0MiB / 46068MiB |      3%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by Findus23** [comment]
I just realized, I forgot to post a stack trace:
<details><summary>Details</summary>
<p>

```text
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fffe9dab84f in xla::CopyDenseElementsDataToXlaFormat(mlir::DenseElementsAttr, std::vector<unsigned char, std::allocator<unsigned char> >*) () from venv/lib/python3.10/site-packages/jaxlib/xla_extension.so
(gdb) bt
#0  0x00007fffe9dab84f in xla::CopyDenseElementsDataToXlaFormat(mlir::DenseElementsAttr, std::vector<unsigned char, std::allocator<unsigned char> >*) ()
   from venv/lib/python3.10/site-packages/jaxlib/xla_extension.so
#1  0x00007fffe865c36d in xla::gpu::IrEmitterUnnested::EmitConstant(mlir::Operation*) ()
   from venv/lib/python3.10/site-packages/jaxlib/xla_extension.so
#2  0x00007fffe86b455d in xla::gpu::IrEmitterUnnested::EmitOp(mlir::Operation*) ()
   from venv/lib/python3.10/site-packages/jaxlib/xla_extension.so
#3  0x00007fffe86b4eef in xla::gpu::IrEmitterUnnested::EmitLmhloRegion(mlir::Region*) ()
   from venv/lib/python3.10/site-packages/jaxlib/xla_extension.so
#4  0x00007fffe862ec54 in xla::gpu::CompileModuleToLlvmIrImpl(xla::HloModule*, llvm::LLVMContext*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*, xla::gpu::GpuDeviceInfo, stream_executor::CudaComputeCapability, stream_executor::RocmComputeCapability, std::function<std::optional<bool> (xla::HloInstruction const*, xla::HloInstruction const*, xla::ShapeIndex const&)> const&, int, xla::gpu::CompileModuleResults*, stream_executor::StreamExecutor*) ()
   from venv/lib/python3.10/site-packages/jaxlib/xla_extension.so
#5  0x00007fffe8360665 in xla::gpu::GpuCompiler::RunBackend(std::unique_ptr<xla::HloModule, std::default_delete<xla::HloModule> >, stream_executor::StreamExecutor*, xla::Compiler::CompileOptions const&) ()
   from venv/lib/python3.10/site-packages/jaxlib/xla_extension.so
#6  0x00007fffe82a5a2d in xla::Service::BuildExecutable(xla::HloModuleProto const&, std::unique_ptr<xla::HloModuleConfig, std::default_delete<xla::HloModuleConfig> >, xla::Backend*, stream_executor::StreamExecutor*, xla::Compiler::CompileOptions const&, bool) ()
   from venv/lib/python3.10/site-packages/jaxlib/xla_extension.so
#7  0x00007fffe802bb59 in xla::LocalService::CompileExecutables(xla::XlaComputation const&, absl::lts_20230125::Span<xla::Shape const* const>, xla::ExecutableBuildOptions const&) ()
   from venv/lib/python3.10/site-packages/jaxlib/xla_extension.so
#8  0x00007fffe8026da4 in xla::LocalClient::Compile(xla::XlaComputation const&, absl::lts_20230125::Span<xla::Shape const* const>, xla::ExecutableBuildOptions const&) ()
   from venv/lib/python3.10/site-packages/jaxlib/xla_extension.so
#9  0x00007fffe7fe7c9b in xla::PjRtStreamExecutorClient::Compile(xla::XlaComputation const&, xla::CompileOptions) () from venv/lib/python3.10/site-packages/jaxlib/xla_extension.so
#10 0x00007fffe7ff8e77 in xla::PjRtStreamExecutorClient::Compile(mlir::ModuleOp, xla::CompileOptions)
    () from venv/lib/python3.10/site-packages/jaxlib/xla_extension.so
#11 0x00007fffe7fab241 in xla::ifrt::PjRtLoadedExecutable::Create(xla::ifrt::PjRtCompatibleClient*, mlir::ModuleOp, xla::CompileOptions, std::vector<tsl::RCReference<xla::ifrt::LoadedHostCallback>, std::allocator<tsl::RCReference<xla::ifrt::LoadedHostCallback> > >) ()
   from venv/lib/python3.10/site-packages/jaxlib/xla_extension.so
#12 0x00007fffe7fa03ec in xla::ifrt::PjRtCompiler::Compile(mlir::ModuleOp, std::unique_ptr<xla::ifrt::CompileOptions, std::default_delete<xla::ifrt::CompileOptions> >) ()
   from venv/lib/python3.10/site-packages/jaxlib/xla_extension.so
#13 0x00007fffe75e5ef6 in xla::PyClient::Compile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, xla::CompileOptions, std::vector<pybind11::capsule, std::allocator<pybind11::capsule> >) () from venv/lib/python3.10/site-packages/jaxlib/xla_extension.so
#14 0x00007fffe72a6e77 in std::shared_ptr<xla::PyLoadedExecutable> pybind11::detail::argument_loader<xla::PyClient&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, xla::CompileOptions, std::vector<pybind11::capsule, std::allocator<pybind11::capsule> > >::call_impl<std::shared_ptr<xla::PyLoadedExecutable>, xla::ValueOrThrowWrapper<absl::lts_20230125::StatusOr<std::shared_ptr<xla::PyLoadedExecutable> > (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, xla::CompileOptions, std::vector<pybind11::capsule, std::allocator<pybind11::capsule> >), xla::PyClient>&, 0ul, 1ul, 2ul, 3ul, pybind11::detail::void_type>(xla::ValueOrThrowWrapper<absl::lts_20230125::StatusOr<std::shared_ptr<xla::PyLoadedExecutable> > (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, xla::CompileOptions, std::vector<pybind11::capsule, std::allocator<pybin--Type <RET> for more, q to quit, c to continue without paging--

```

</p>
</details>

**Comment by hawkinsp** [comment]
I'm fairly confident https://github.com/openxla/xla/pull/6803, which will be in the next jaxlib release, fixed this.

However, I recommend passing large constants as parameters, because it will be faster!
