### ISSUE TITLE
`pip install jax jaxlib` broken with 0.4.15

### ISSUE THREAD

**Issue by brentyi** [google/jax#17371]
### Description

Hi!

As of the 0.4.15 release (~30 minutes ago), running `pip install jax jaxlib` in Python 3.9 seems to break. The 0.4.15 version of `jaxlib` is installed, but the 0.4.14 version of `jax` is, and these aren't compatible.

Here's the error I get:
```
$ pip install jax jaxlib                                 
Collecting jax
  Downloading jax-0.4.15.tar.gz (1.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 19.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/a6/c4/c373ea5f69237651b72c5a351c9fca2444c9a05b7caddd700abfef23c4f7/jax-0.4.15.tar.gz (from https://pypi.org/simple/jax/) (requires-python:>=3.9): Requested jax from https://files.pythonhosted.org/packages/a6/c4/c373ea5f69237651b72c5a351c9fca2444c9a05b7caddd700abfef23c4f7/jax-0.4.15.tar.gz has inconsistent version: expected '0.4.15', but metadata has '0.4.15.dev20230830'
  Downloading jax-0.4.14.tar.gz (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 10.1 MB/s eta 0:00:00

```

### Additional system info

It happens both locally (on Ubuntu & Mac) and in a Github action workflow.

**Comment by brentyi** [comment]
This also happens in Python 3.10, after install + attempting to import `jax` I get:
```
>>> import jax
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/brent/miniconda/envs/3dsplat/lib/python3.10/site-packages/jax/__init__.py", line 35, in <module>
    from jax import config as _config_module
  File "/home/brent/miniconda/envs/3dsplat/lib/python3.10/site-packages/jax/config.py", line 17, in <module>
    from jax._src.config import config  # noqa: F401
  File "/home/brent/miniconda/envs/3dsplat/lib/python3.10/site-packages/jax/_src/config.py", line 27, in <module>
    from jax._src import lib
  File "/home/brent/miniconda/envs/3dsplat/lib/python3.10/site-packages/jax/_src/lib/__init__.py", line 73, in <module>
    version = check_jaxlib_version(
  File "/home/brent/miniconda/envs/3dsplat/lib/python3.10/site-packages/jax/_src/lib/__init__.py", line 68, in check_jaxlib_version
    raise RuntimeError(msg)
RuntimeError: jaxlib version 0.4.15.dev20230830 is newer than and incompatible with jax version 0.4.14. Please update your jax and/or jaxlib packages.
```

**Comment by NeilGirdhar** [comment]
I'm having problems with Poetry that may be related:
```
Requested jax from https://files.pythonhosted.org/packages/a6/c4/c373ea5f69237651b72c5a351c9fca2444c9a05b7caddd700abfef23c4f7/jax-0.4.15.tar.gz has inconsistent version: expected '0.4.15', but metadata has '0.4.15.dev20230830'
```

**Comment by arosen93** [comment]
Can confirm that I receive the same issue with Python 3.10 and 3.11.

**Comment by jakevdp** [comment]
Thanks for the report, we're looking into the issue.

It seems to be incorrect version metadata in the `jax` 0.4.15 wheel. This doesn't appear to affect jaxlib.

For now, please pin to jax/jaxlib 0.4.14, and we'll try to get a fix out ASAP.

**Comment by brentyi** [comment]
Thanks! As an FYI it was also easy to work around this by replacing the install command with `pip install jax[cpu]` (or `jax[cuda12_pip]`) to get the `jaxlib` version conditioned on the installed jax version's dependencies.

**Comment by mattjj** [comment]
We yanked jax==0.4.15 and jaxlib==0.4.15!

**Comment by mattjj** [comment]
I think we can close this issue since 0.4.15 no longer exists. Jake is fixing the underlying bug, and then we'll release 0.4.16.

**Comment by mattjj** [comment]
Thanks everyone for raising this, and gathering evidence!
