### ISSUE TITLE
XLA Runtime Error at jax.ppermute when setting "XLA_PYTHON_CLIENT_MEM_FRACTION"

### ISSUE THREAD

**Issue by aaronbuhendwa** [google/jax#17426]
### Description

We are performing scaling runs of our JAX code (https://github.com/tumaer/JAXFLUIDS) on the JUWELS Booster (https://apps.fz-juelich.de/jsc/hps/juwels/booster-overview.html). We experience errors using jax.lax.ppermute depending on the setting of certain environmental variables. Software in use: Python 3.10.4, jax 0.4.14, jaxlib, 0.4.14+cuda12.cudnn89, CUDA 12 installed using pip wheels provided by the jax pip install. Please find attached requirements.txt for details about the used package versions.

We run the following python script on a single compute node (4xNVIDIA A100) using a single process. 

```python
import jax, numpy as np

print(jax.devices())
x = np.arange(jax.device_count())
print(x)
def func(arr):
    arr = jax.lax.ppermute(arr, axis_name="i", perm=((0,1),(1,2),(2,3),(3,0)))
    return arr
x = jax.pmap(func, axis_name="i")(x)
print(x)

```
And get the expected output:
```
srun: job 8375613 queued and waiting for resources
srun: job 8375613 has been allocated resources
[gpu(id=0), gpu(id=1), gpu(id=2), gpu(id=3)]
[0 1 2 3]
[3 0 1 2]
```
However, when we set the environmental variable
```python
os.environ["XLA_PYTHON_CLIENT_MEM_FRACTION"]="100"
```
and run the exact same script, we get the following error:
```
srun: job 8375610 queued and waiting for resources
srun: job 8375610 has been allocated resources
2023-09-04 15:19:15.108898: W external/xla/xla/service/gpu/runtime/support.cc:58] Intercepted XLA runtime error:
INTERNAL: external/xla/xla/service/gpu/nccl_collective_permute_thunk.cc:250: NCCL operation ncclGroupEnd() failed: internal error
2023-09-04 15:19:15.109009: E external/xla/xla/pjrt/pjrt_stream_executor_client.cc:2593] Execution of replica 1 failed: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.collective_permute' failed: external/xla/xla/service/gpu/nccl_collective_permute_thunk.cc:250: NCCL operation ncclGroupEnd() failed: internal error; current tracing scope: collective-permute-start; current profiling annotation: XlaModule:#hlo_module=pmap_func,program_id=0#.
2023-09-04 15:19:15.109096: W external/xla/xla/service/gpu/runtime/support.cc:58] Intercepted XLA runtime error:
INTERNAL: external/xla/xla/service/gpu/nccl_collective_permute_thunk.cc:250: NCCL operation ncclGroupEnd() failed: internal error
2023-09-04 15:19:15.109113: E external/xla/xla/pjrt/pjrt_stream_executor_client.cc:2593] Execution of replica 0 failed: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.collective_permute' failed: external/xla/xla/service/gpu/nccl_collective_permute_thunk.cc:250: NCCL operation ncclGroupEnd() failed: internal error; current tracing scope: collective-permute-start; current profiling annotation: XlaModule:#hlo_module=pmap_func,program_id=0#.
2023-09-04 15:19:15.109152: W external/xla/xla/service/gpu/runtime/support.cc:58] Intercepted XLA runtime error:
INTERNAL: external/xla/xla/service/gpu/nccl_collective_permute_thunk.cc:250: NCCL operation ncclGroupEnd() failed: internal error
2023-09-04 15:19:15.109167: E external/xla/xla/pjrt/pjrt_stream_executor_client.cc:2593] Execution of replica 3 failed: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.collective_permute' failed: external/xla/xla/service/gpu/nccl_collective_permute_thunk.cc:250: NCCL operation ncclGroupEnd() failed: internal error; current tracing scope: collective-permute-start; current profiling annotation: XlaModule:#hlo_module=pmap_func,program_id=0#.
2023-09-04 15:19:15.109261: W external/xla/xla/service/gpu/runtime/support.cc:58] Intercepted XLA runtime error:
INTERNAL: external/xla/xla/service/gpu/nccl_collective_permute_thunk.cc:250: NCCL operation ncclGroupEnd() failed: internal error
2023-09-04 15:19:15.109277: E external/xla/xla/pjrt/pjrt_stream_executor_client.cc:2593] Execution of replica 2 failed: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.collective_permute' failed: external/xla/xla/service/gpu/nccl_collective_permute_thunk.cc:250: NCCL operation ncclGroupEnd() failed: internal error; current tracing scope: collective-permute-start; current profiling annotation: XlaModule:#hlo_module=pmap_func,program_id=0#.
[gpu(id=0), gpu(id=1), gpu(id=2), gpu(id=3)]
[0 1 2 3]
Traceback (most recent call last):
  File "/p/project/jaxfluids/jaxfluids/tests/parallelization/multihost/gpu/runfile.py", line 9, in <module>
    x = jax.pmap(func, axis_name="i")(x)
  File "/p/project/jaxfluids/venv_jax_cuda_12/lib/python3.10/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/p/project/jaxfluids/venv_jax_cuda_12/lib/python3.10/site-packages/jax/_src/api.py", line 1803, in cache_miss
    out = map_bind_continuation(execute(*tracers))
  File "/p/project/jaxfluids/venv_jax_cuda_12/lib/python3.10/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/p/project/jaxfluids/venv_jax_cuda_12/lib/python3.10/site-packages/jax/_src/interpreters/pxla.py", line 1229, in __call__
    results = self.xla_executable.execute_sharded(input_bufs)
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.collective_permute' failed: external/xla/xla/service/gpu/nccl_collective_permute_thunk.cc:250: NCCL operation ncclGroupEnd() failed: internal error; current tracing scope: collective-permute-start; current profiling annotation: XlaModule:#hlo_module=pmap_func,program_id=0#.: while running replica 0 and partition 0 of a replicated computation (other replicas may have failed as well).

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/p/project/jaxfluids/jaxfluids/tests/parallelization/multihost/gpu/runfile.py", line 9, in <module>
    x = jax.pmap(func, axis_name="i")(x)
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.collective_permute' failed: external/xla/xla/service/gpu/nccl_collective_permute_thunk.cc:250: NCCL operation ncclGroupEnd() failed: internal error; current tracing scope: collective-permute-start; current profiling annotation: XlaModule:#hlo_module=pmap_func,program_id=0#.: while running replica 0 and partition 0 of a replicated computation (other replicas may have failed as well).
srun: error: jwb0897: task 0: Exited with exit code 1
```
The program fails at compiling the pmapped function that performs a simple jax.lax.ppermute (jax.lax.psum works just fine). We noticed however, that if we deactivate P2P using
```python
os.environ["XLA_PYTHON_CLIENT_MEM_FRACTION"]="100"
os.environ["NCCL_P2P_DISABLE"] = "1"
```
the script works again.

Specifying the preallocated memory fraction enables us to run larger jobs for the scaling runs without getting OOM, so we would like to use it, but still also use P2P, as the program runs faster with it. Do you have an idea what the problem is?

Some additional info: 
We also tried using CUDA 11 from pip wheels, which produces the same error behavior.

Best
JAX-FLUIDS

### What jax/jaxlib version are you using?

jax 0.4.14, jaxlib, 0.4.14+cuda12.cudnn89

### Which accelerator(s) are you using?

GPU A100 40GB 

### Additional system info

https://apps.fz-juelich.de/jsc/hps/juwels/configuration.html#software-overview
https://apps.fz-juelich.de/jsc/hps/juwels/configuration.html#hardware-configuration-of-the-system-name-booster-module
https://apps.fz-juelich.de/jsc/hps/juwels/booster-overview.html#node-configuration
[requirements.txt](https://github.com/google/jax/files/12514238/requirements.txt)

**Comment by hawkinsp** [comment]
`XLA_PYTHON_CLIENT_MEM_FRACTION` is normally expressed as a ratio. 0.75 is typical. Using "100" seems like a mistake. 

Also you cannot use the entire GPU for XLA's heap: NVIDIA's libraries need a certain amount of GPU memory also.

Hope that helps!
