### ISSUE TITLE
Unable to connect to TPU's using v3-8 google TPU on Jax 0.4.14

### ISSUE THREAD

**Issue by Itsindigo** [google/jax#17495]
### Description

Hi all! 

Thanks for your work creating and maintaining this package.

We're having some issues initialising our Jax devices on a GCP V3-8 TPU using the node architecture on GKE.

### Dependencies

**Python:** 3.10.6
**GKE:** v1.27.4-gke.900
```
jax                      0.4.14
jaxlib                   0.4.14
libtpu-nightly           0.1.dev20230727
```

### The Error

```
>>> import jax
>>> from jax.config import config
>>> import os
>>> config.update("jax_backend_target", os.environ.get("KUBE_GOOGLE_CLOUD_TPU_ENDPOINTS")) # env var equals "'grpc://10.84.19.202:8470'"
>>> config.update("jax_xla_backend", "tpu_driver")
>>> print(jax.devices('tpu'))
WARNING: Logging before InitGoogle() is written to STDERR
I0000 00:00:1694099665.260573     484 common_lib.cc:174] Failed to fetch URL on try 1 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099665.761276     484 common_lib.cc:174] Failed to fetch URL on try 2 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099666.261921     484 common_lib.cc:174] Failed to fetch URL on try 3 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099666.762603     484 common_lib.cc:174] Failed to fetch URL on try 4 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099667.263213     484 common_lib.cc:174] Failed to fetch URL on try 5 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099667.763840     484 common_lib.cc:174] Failed to fetch URL on try 6 out of 6: Failed to fetch URL (http status: 404) No error
Failed to get 'tpu-env' from instance metadata: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099668.265593     484 common_lib.cc:174] Failed to fetch URL on try 1 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099668.766196     484 common_lib.cc:174] Failed to fetch URL on try 2 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099669.266997     484 common_lib.cc:174] Failed to fetch URL on try 3 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099669.767656     484 common_lib.cc:174] Failed to fetch URL on try 4 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099670.268351     484 common_lib.cc:174] Failed to fetch URL on try 5 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099670.769031     484 common_lib.cc:174] Failed to fetch URL on try 6 out of 6: Failed to fetch URL (http status: 404) No error
Failed to get 'tpu-env' from instance metadata: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099671.270963     484 common_lib.cc:174] Failed to fetch URL on try 1 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099671.771606     484 common_lib.cc:174] Failed to fetch URL on try 2 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099672.272241     484 common_lib.cc:174] Failed to fetch URL on try 3 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099672.772920     484 common_lib.cc:174] Failed to fetch URL on try 4 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099673.273613     484 common_lib.cc:174] Failed to fetch URL on try 5 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099673.774299     484 common_lib.cc:174] Failed to fetch URL on try 6 out of 6: Failed to fetch URL (http status: 404) No error
Failed to get 'tpu-env' from instance metadata: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099674.276043     484 common_lib.cc:174] Failed to fetch URL on try 1 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099674.776740     484 common_lib.cc:174] Failed to fetch URL on try 2 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099675.277490     484 common_lib.cc:174] Failed to fetch URL on try 3 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099675.778185     484 common_lib.cc:174] Failed to fetch URL on try 4 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099676.278803     484 common_lib.cc:174] Failed to fetch URL on try 5 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099676.779447     484 common_lib.cc:174] Failed to fetch URL on try 6 out of 6: Failed to fetch URL (http status: 404) No error
Failed to get 'tpu-env' from instance metadata: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099677.281181     484 common_lib.cc:174] Failed to fetch URL on try 1 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099677.781933     484 common_lib.cc:174] Failed to fetch URL on try 2 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099678.282643     484 common_lib.cc:174] Failed to fetch URL on try 3 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099678.783482     484 common_lib.cc:174] Failed to fetch URL on try 4 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099679.284116     484 common_lib.cc:174] Failed to fetch URL on try 5 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099679.784913     484 common_lib.cc:174] Failed to fetch URL on try 6 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099680.286588     484 common_lib.cc:174] Failed to fetch URL on try 1 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099680.787278     484 common_lib.cc:174] Failed to fetch URL on try 2 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099681.288067     484 common_lib.cc:174] Failed to fetch URL on try 3 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099681.788683     484 common_lib.cc:174] Failed to fetch URL on try 4 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099682.289363     484 common_lib.cc:174] Failed to fetch URL on try 5 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099682.789983     484 common_lib.cc:174] Failed to fetch URL on try 6 out of 6: Failed to fetch URL (http status: 404) No error
WARNING: could not determine TPU accelerator type. Set env var TPU_ACCELERATOR_TYPE to set manually. TPU runtime may not be properly initialized.
I0000 00:00:1694099683.291645     484 common_lib.cc:174] Failed to fetch URL on try 1 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099683.792368     484 common_lib.cc:174] Failed to fetch URL on try 2 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099684.293010     484 common_lib.cc:174] Failed to fetch URL on try 3 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099684.793626     484 common_lib.cc:174] Failed to fetch URL on try 4 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099685.294320     484 common_lib.cc:174] Failed to fetch URL on try 5 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099685.795097     484 common_lib.cc:174] Failed to fetch URL on try 6 out of 6: Failed to fetch URL (http status: 404) No error
WARNING: could not determine TPU worker number. Set env var TPU_WORKER_ID to set manually. TPU runtime may not be properly initialized.
I0000 00:00:1694099686.296907     484 common_lib.cc:174] Failed to fetch URL on try 1 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099686.797484     484 common_lib.cc:174] Failed to fetch URL on try 2 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099687.298116     484 common_lib.cc:174] Failed to fetch URL on try 3 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099687.798841     484 common_lib.cc:174] Failed to fetch URL on try 4 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099688.299636     484 common_lib.cc:174] Failed to fetch URL on try 5 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099688.800316     484 common_lib.cc:174] Failed to fetch URL on try 6 out of 6: Failed to fetch URL (http status: 404) No error
WARNING: could not determine TPU worker hostnames or internal IP addresses. Set env var TPU_WORKER_HOSTNAMES to set manually. TPU runtime may not be properly initialized.
I0000 00:00:1694099689.302166     484 common_lib.cc:174] Failed to fetch URL on try 1 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099689.802830     484 common_lib.cc:174] Failed to fetch URL on try 2 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099690.303521     484 common_lib.cc:174] Failed to fetch URL on try 3 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099690.804151     484 common_lib.cc:174] Failed to fetch URL on try 4 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099691.304766     484 common_lib.cc:174] Failed to fetch URL on try 5 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099691.805422     484 common_lib.cc:174] Failed to fetch URL on try 6 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099692.307177     484 common_lib.cc:174] Failed to fetch URL on try 1 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099692.807820     484 common_lib.cc:174] Failed to fetch URL on try 2 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099693.308426     484 common_lib.cc:174] Failed to fetch URL on try 3 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099693.809127     484 common_lib.cc:174] Failed to fetch URL on try 4 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099694.309889     484 common_lib.cc:174] Failed to fetch URL on try 5 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099694.810528     484 common_lib.cc:174] Failed to fetch URL on try 6 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099695.312080     484 common_lib.cc:174] Failed to fetch URL on try 1 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099695.812676     484 common_lib.cc:174] Failed to fetch URL on try 2 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099696.313297     484 common_lib.cc:174] Failed to fetch URL on try 3 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099696.813918     484 common_lib.cc:174] Failed to fetch URL on try 4 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099697.314605     484 common_lib.cc:174] Failed to fetch URL on try 5 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099697.815245     484 common_lib.cc:174] Failed to fetch URL on try 6 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099698.317007     484 common_lib.cc:174] Failed to fetch URL on try 1 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099698.817666     484 common_lib.cc:174] Failed to fetch URL on try 2 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099699.318303     484 common_lib.cc:174] Failed to fetch URL on try 3 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099699.819065     484 common_lib.cc:174] Failed to fetch URL on try 4 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099700.319659     484 common_lib.cc:174] Failed to fetch URL on try 5 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099700.820294     484 common_lib.cc:174] Failed to fetch URL on try 6 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099701.322023     484 common_lib.cc:174] Failed to fetch URL on try 1 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099701.822656     484 common_lib.cc:174] Failed to fetch URL on try 2 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099702.323345     484 common_lib.cc:174] Failed to fetch URL on try 3 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099702.824143     484 common_lib.cc:174] Failed to fetch URL on try 4 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099703.324684     484 common_lib.cc:174] Failed to fetch URL on try 5 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099703.825275     484 common_lib.cc:174] Failed to fetch URL on try 6 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099704.327280     484 common_lib.cc:174] Failed to fetch URL on try 1 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099704.827968     484 common_lib.cc:174] Failed to fetch URL on try 2 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099705.328633     484 common_lib.cc:174] Failed to fetch URL on try 3 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099705.829252     484 common_lib.cc:174] Failed to fetch URL on try 4 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099706.329948     484 common_lib.cc:174] Failed to fetch URL on try 5 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099706.830664     484 common_lib.cc:174] Failed to fetch URL on try 6 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099707.332477     484 common_lib.cc:174] Failed to fetch URL on try 1 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099707.833130     484 common_lib.cc:174] Failed to fetch URL on try 2 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099708.333767     484 common_lib.cc:174] Failed to fetch URL on try 3 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099708.834466     484 common_lib.cc:174] Failed to fetch URL on try 4 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099709.335166     484 common_lib.cc:174] Failed to fetch URL on try 5 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1694099709.835773     484 common_lib.cc:174] Failed to fetch URL on try 6 out of 6: Failed to fetch URL (http status: 404) No error
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/jax/_src/xla_bridge.py", line 612, in backends
    backend = _init_backend(platform)
  File "/usr/local/lib/python3.10/dist-packages/jax/_src/xla_bridge.py", line 666, in _init_backend
    backend = registration.factory()
  File "/usr/local/lib/python3.10/dist-packages/jax/_src/xla_bridge.py", line 198, in tpu_client_timer_callback
    client = xla_client.make_tpu_client()
  File "/usr/local/lib/python3.10/dist-packages/jaxlib/xla_client.py", line 171, in make_tpu_client
    return make_tfrt_tpu_c_api_client()
  File "/usr/local/lib/python3.10/dist-packages/jaxlib/xla_client.py", line 107, in make_tfrt_tpu_c_api_client
    return _xla.get_c_api_client('tpu', options)
jaxlib.xla_extension.XlaRuntimeError: UNKNOWN: TPU initialization failed: No ba16c7433 device found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/jax/_src/xla_bridge.py", line 776, in devices
    return get_backend(backend).devices()
  File "/usr/local/lib/python3.10/dist-packages/jax/_src/xla_bridge.py", line 710, in get_backend
    return _get_backend_uncached(platform)
  File "/usr/local/lib/python3.10/dist-packages/jax/_src/xla_bridge.py", line 691, in _get_backend_uncached
    bs = backends()
  File "/usr/local/lib/python3.10/dist-packages/jax/_src/xla_bridge.py", line 628, in backends
    raise RuntimeError(err_msg)
RuntimeError: Unable to initialize backend 'tpu': UNKNOWN: TPU initialization failed: No ba16c7433 device found. (set JAX_PLATFORMS='' to automatically choose an available backend)
```

### Other issues we have checked and have not worked for us
[https://github.com/google/jax/issues/12917](https://github.com/google/jax/issues/12917)
[https://github.com/google/jax/issues/5638](https://github.com/google/jax/issues/5638)
[https://github.com/google/jax/issues/13969](https://github.com/google/jax/issues/13969)

### Bonus

We _have_ at some point in the past gotten this working during tests, the only reason I can confirm this is because I have some logs in my notes 😄:

```
>>> import jax
>>> from jax.config import config
>>> config.update("jax_backend_target", os.environ.get("KUBE_GOOGLE_CLOUD_TPU_ENDPOINTS"))
>>> config.update("jax_xla_backend", "tpu_driver")
>>> print(jax.devices('tpu'))
[TpuDevice(id=0, process_index=0, coords=(0,0,0), core_on_chip=0), TpuDevice(id=1, process_index=0, coords=(0,0,0), core_on_chip=1), TpuDevice(id=2, process_index=0, coords=(1,0,0), core_on_chip=0), TpuDevice(id=3, process_index=0, coords=(1,0,0), core_on_chip=1), TpuDevice(id=4, process_index=0, coords=(0,1,0), core_on_chip=0), TpuDevice(id=5, process_index=0, coords=(0,1,0), core_on_chip=1), TpuDevice(id=6, process_index=0, coords=(1,1,0), core_on_chip=0), TpuDevice(id=7, process_index=0, coords=(1,1,0), core_on_chip=1)]
```

Unfortunately, whatever the secret sauce was to produce this output, I have been unable to recreate at since

### What jax/jaxlib version are you using?

jax v0.4.14, jaxlib v0.4.14

### Which accelerator(s) are you using?

TPU

**Comment by bhuvanpkaruturi** [comment]
JAX does not support TPU clusters in **node** architecture (see: https://github.com/google/jax/issues/13969#issuecomment-1380925131). Currently TPU v2, v3 are only supported in Node architecture on GKE. TPU v4 is available in TPU VM architecture on GKE and the details on how to setup a TPU v4 GKE cluster can be found here: https://cloud.google.com/kubernetes-engine/docs/concepts/tpus#configuration

**Comment by Itsindigo** [comment]
Thanks for the reply @bhuvanpkaruturi. 

>Currently TPU v2, v3 are only supported in Node architecture on GKE

Unless I'm misunderstanding you, I think we're talking about the same thing -- this is what I'm running. V3-8, Node Architecture on GKE, using Jax.

**Comment by hawkinsp** [comment]
@Itsindigo Yes, that's right, but JAX does not support the Node architecture. So at the moment you'll either need to switch to TPUv4 which has TPU VM support (needed for JAX), or avoid GKE.

**Comment by Itsindigo** [comment]
thanks @hawkinsp -- I still don't really understand how I got the results listed under the "bonus" section of the original issue, possibly human error when taking my notes. But i'm not sure how that could have happened given that the code depends on the `KUBE_GOOGLE_CLOUD_TPU_ENDPOINTS` variable which only exists in the node GKE environment

**Comment by hawkinsp** [comment]
JAX versions before 0.4 did support, somewhat, the TPU node architecture. We removed support for the TPU node architecture at that time, and strongly recommend the newer and in almost all respects much better TPU VM architecture.

**Comment by ua-chjb** [comment]
just to confirm, newer versions of jax and jaxlib [== 0.4.13] do indeed support TPU VM pods? I am running a v6e-16 with a tpu-vm-base version and see the same error.
