### ISSUE TITLE
Compiling mlir/lib/Dialect/LLVMIR/IR/LLVMDialect.cpp failed: (Exit 1): gcc failed: error executing command (from target @llvm-project//mlir:LLVMDialect)

### ISSUE THREAD

**Issue by followtheart** [google/jax#17536]
### Description

```
[5,013 / 6,398] Compiling mlir/lib/Dialect/LLVMIR/IR/LLVMDialect.cpp; 94s local ... (10 actions running)
[5,014 / 6,398] Compiling mlir/lib/Dialect/LLVMIR/IR/LLVMDialect.cpp; 95s local ... (10 actions running)
[5,015 / 6,398] Compiling mlir/lib/Dialect/LLVMIR/IR/LLVMDialect.cpp; 101s local ... (10 actions, 9 running)
ERROR: /home/jq/.cache/bazel/_bazel_jq/6adfab8d03769a8b1748a6b12f420881/external/llvm-project/mlir/BUILD.bazel:4626:11: Compiling mlir/lib/Dialect/LLVMIR/IR/LLVMDialect.cpp failed: (Exit 1): gcc failed: error executing command (from target @llvm-project//mlir:LLVMDialect)
  (cd /home/jq/.cache/bazel/_bazel_jq/6adfab8d03769a8b1748a6b12f420881/execroot/__main__ && \
  exec env - \
    PATH='/home/jq/.local/bin/:/usr/local/;/home/jq/libtorcch/:/usr/local/cuda/nvvm/bin/:/usr/local/cuda/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin' \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/k8-opt/bin/external/llvm-project/mlir/_objs/LLVMDialect/LLVMDialect.pic.d '-frandom-seed=bazel-out/k8-opt/bin/external/llvm-project/mlir/_objs/LLVMDialect/LLVMDialect.pic.o' -fPIC '-DLLVM_ON_UNIX=1' '-DHAVE_BACKTRACE=1' '-DBACKTRACE_HEADER=<execinfo.h>' '-DLTDL_SHLIB_EXT=".so"' '-DLLVM_PLUGIN_EXT=".so"' '-DLLVM_ENABLE_THREADS=1' '-DHAVE_DEREGISTER_FRAME=1' '-DHAVE_LIBPTHREAD=1' '-DHAVE_PTHREAD_GETNAME_NP=1' '-DHAVE_PTHREAD_H=1' '-DHAVE_PTHREAD_SETNAME_NP=1' '-DHAVE_REGISTER_FRAME=1' '-DHAVE_SETENV_R=1' '-DHAVE_STRERROR_R=1' '-DHAVE_SYSEXITS_H=1' '-DHAVE_UNISTD_H=1' -D_GNU_SOURCE '-DHAVE_LINK_H=1' '-DHAVE_MALLINFO=1' '-DHAVE_SBRK=1' '-DHAVE_STRUCT_STAT_ST_MTIM_TV_NSEC=1' '-DLLVM_NATIVE_ARCH="X86"' '-DLLVM_NATIVE_ASMPARSER=LLVMInitializeX86AsmParser' '-DLLVM_NATIVE_ASMPRINTER=LLVMInitializeX86AsmPrinter' '-DLLVM_NATIVE_DISASSEMBLER=LLVMInitializeX86Disassembler' '-DLLVM_NATIVE_TARGET=LLVMInitializeX86Target' '-DLLVM_NATIVE_TARGETINFO=LLVMInitializeX86TargetInfo' '-DLLVM_NATIVE_TARGETMC=LLVMInitializeX86TargetMC' '-DLLVM_NATIVE_TARGETMCA=LLVMInitializeX86TargetMCA' '-DLLVM_HOST_TRIPLE="x86_64-unknown-linux-gnu"' '-DLLVM_DEFAULT_TARGET_TRIPLE="x86_64-unknown-linux-gnu"' '-DLLVM_VERSION_MAJOR=18' '-DLLVM_VERSION_MINOR=0' '-DLLVM_VERSION_PATCH=0' '-DLLVM_VERSION_STRING="18.0.0git"' -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS '-DBLAKE3_USE_NEON=0' -DBLAKE3_NO_AVX2 -DBLAKE3_NO_AVX512 -DBLAKE3_NO_SSE2 -DBLAKE3_NO_SSE41 '-DBAZEL_CURRENT_REPOSITORY="llvm-project"' -iquote external/llvm-project -iquote bazel-out/k8-opt/bin/external/llvm-project -isystem external/llvm-project/mlir/include -isystem bazel-out/k8-opt/bin/external/llvm-project/mlir/include -isystem external/llvm-project/llvm/include -isystem bazel-out/k8-opt/bin/external/llvm-project/llvm/include '-fvisibility=hidden' -Wno-sign-compare -Wno-unknown-warning-option -Wno-stringop-truncation -Wno-array-parameter '-DMLIR_PYTHON_PACKAGE_PREFIX=jaxlib.mlir.' -mavx '-std=c++17' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/llvm-project/mlir/lib/Dialect/LLVMIR/IR/LLVMDialect.cpp -o bazel-out/k8-opt/bin/external/llvm-project/mlir/_objs/LLVMDialect/LLVMDialect.pic.o)
# Configuration: feb2fab23223bbf75110994ba52732edd23eaf8ad1303a59d74606bc93162258
# Execution platform: @local_execution_config_platform//:platform
gcc: fatal error: Killed signal terminated program cc1plus
compilation terminated.
Target //jaxlib/tools:build_wheel failed to build
[5,025 / 6,398] checking cached actions
INFO: Elapsed time: 1272.559s, Critical Path: 124.86s
INFO: 5025 processes: 485 internal, 4540 local.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
Traceback (most recent call last):
  File "/home/jq/code/jax/build/build.py", line 559, in <module>
    main()
  File "/home/jq/code/jax/build/build.py", line 554, in main
    shell(command)
  File "/home/jq/code/jax/build/build.py", line 53, in shell
    output = subprocess.check_output(cmd)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/bazel', 'run', '--verbose_failures=true', '//jaxlib/tools:build_wheel', '--', '--output_path=/home/jq/code/jax/dist', '--cpu=x86_64']' returned non-zero exit status 1.
```

### What jax/jaxlib version are you using?

jax v0.4.15 jaxlib v0.4.15

### Which accelerator(s) are you using?

cpu

### Additional system info

python 3.9 gcc-10 wsl ubuntu 20.04

**Comment by followtheart** [comment]
Thanks,fixed by allocated some swap memory and decrease bazel jobs
