### ISSUE TITLE
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)

### ISSUE THREAD

**Issue by s4nyam** [google/jax#17624]
### Description

I am trying to run this code on my college GPU with SLURM. Torch is running fine however JAX wont run.

```python
import jax

def check_gpu():
    # Get a list of devices available to JAX
    devices = jax.devices()

    # Check if any of the devices are GPUs
    for device in devices:
        if "gpu" in device.device_kind.lower():
            return True

    return False

if check_gpu():
    print("JAX is running on a GPU.")
else:
    print("JAX is not running on a GPU.")

```
![Screenshot 2023-09-15 at 6 43 22 PM](https://github.com/google/jax/assets/13884479/abb09560-0f57-4fa8-a772-0c9180a0d861)

### What jax/jaxlib version are you using?

0.4.14

### Which accelerator(s) are you using?

GPU

### Additional system info

Linux

### NVIDIA GPU info

Fri Sep 15 18:44:40 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 8000     Off  | 00000000:41:00.0 Off |                  Off |
| 28%   30C    P0    65W / 260W |      0MiB / 49152MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Quadro RTX 8000     Off  | 00000000:C1:00.0 Off |                  Off |
| 30%   29C    P0    44W / 260W |      0MiB / 49152MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by hawkinsp** [comment]
How did you install JAX?

**Comment by s4nyam** [comment]
I installed JAX using pip install jax. As pip install jax[cuda] does not work and says version mismatch with python, hwoever my python is on latest version already. I cannot downgrade either.

**Comment by hawkinsp** [comment]
What happens when you did what @ayaka14732 suggested?

**Comment by s4nyam** [comment]
Thanks for the reply. Its still at the same output. I did the installation using @ayaka14732 suggestions, it installed noramlly. But "JAX is not running on a GPU."
![Screenshot 2023-09-23 at 12 51 30 PM](https://github.com/google/jax/assets/13884479/dc6e21c0-996a-4f63-aa40-eb8dd4cc57e9)

**Comment by ayaka14732** [comment]
@s4nyam You should first uninstall the old `jax` and `jaxlib` using:

```python
pip uninstall jax jaxlib
```

**Comment by lakatosgabor** [comment]
Hi @s4nyam did you find the solution?

**Comment by s4nyam** [comment]
@ayaka14732 I did that and didn't work
@lakatosgabor Not yet, and hence moved to torch.
Lot others were also struggling - https://twitter.com/s4nyam/status/1702727177144295929

**Comment by ayaka14732** [comment]
@s4nyam Please don't move to PyTorch! JAX is much better than PyTorch. I can fix this for you!

**Comment by ayaka14732** [comment]
Based on the screenshot provided, it seems that you are utilizing a conda environment. To proceed, I recommend the following steps:

1. Create a new conda environment with Python version 3.11:
```
conda create -n <environment_name> python=3.11
```
Replace `<environment_name>` with your desired environment name.

2. Install the necessary package with pip:
```
pip install -U "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```

Please ensure to activate the newly created conda environment before executing the pip installation command.

3. Test JAX GPU Accessibility:

Execute the following Python code to check if JAX can access the GPU:

```python
import jax
print(jax.devices())
```

This script prints a list of available devices. If the GPU is configured correctly, you should see `GpuDevice`.

**Comment by lakatosgabor** [comment]
@ayaka14732 I try your description. I give below error:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-cpu 2.12.0 requires keras<2.13,>=2.12.0, but you have keras 2.14.0 which is incompatible.
tensorflow-cpu 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.26.1 which is incompatible.
tensorflow-cpu 2.12.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3, but you have protobuf 3.12.4 which is incompatible.
tensorflow-cpu 2.12.0 requires tensorboard<2.13,>=2.12, but you have tensorboard 2.8.0 which is incompatible.
tensorflow-cpu 2.12.0 requires tensorflow-estimator<2.13,>=2.12.0, but you have tensorflow-estimator 2.14.0 which is incompatible.
torch 2.1.0 requires nvidia-cublas-cu12==12.1.3.1; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu12 12.3.2.9 which is incompatible.
torch 2.1.0 requires nvidia-cuda-cupti-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-cupti-cu12 12.3.52 which is incompatible.
torch 2.1.0 requires nvidia-cuda-runtime-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-runtime-cu12 12.3.52 which is incompatible.
torch 2.1.0 requires nvidia-cufft-cu12==11.0.2.54; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cufft-cu12 11.0.11.19 which is incompatible.
torch 2.1.0 requires nvidia-cusolver-cu12==11.4.5.107; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusolver-cu12 11.5.3.52 which is incompatible.
torch 2.1.0 requires nvidia-cusparse-cu12==12.1.0.106; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusparse-cu12 12.1.3.153 which is incompatible.
torch 2.1.0 requires nvidia-nccl-cu12==2.18.1; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-nccl-cu12 2.19.3 which is incompatible.
Successfully installed jax-0.4.19 jaxlib-0.4.19+cuda12.cudnn89 nvidia-cublas-cu12-12.3.2.9 nvidia-cuda-cupti-cu12-12.3.52 nvidia-cuda-nvcc-cu12-12.3.52 nvidia-cuda-runtime-cu12-12.3.52 nvidia-cufft-cu12-11.0.11.19 nvidia-cusolver-cu12-11.5.3.52 nvidia-cusparse-cu12-12.1.3.153 nvidia-nccl-cu12-2.19.3


jax.device() resuilt is "[cuda(id=0)]"

Have you got any idea?

Thanks your help

**Comment by ayaka14732** [comment]
I apologies for the oversight. It appears that `GpuDevice` is renamed to `cuda` in recent JAX releases. Therefore, the output `[cuda(id=0)]` means JAX is working correctly on your machine.

For the pip's dependency resolver, it seems that you are trying to install JAX into an environment with Tensorflow and PyTorch installed. It appears that there are version mismatches between the dependencies of these three packages. You should install JAX into a clean environment, preferably created with venv. Remember to activate the newly create environment before executing the pip installation command.

**Comment by lakatosgabor** [comment]
@ayaka14732 thnaks your answer. I remove tensorflow-cpu and pytorch, next i can install the jax.
How to install optax with jax and gpu compatibility?

**Comment by ayaka14732** [comment]
@lakatosgabor 

> I remove tensorflow-cpu and pytorch, next i can install the jax.

You should completely delete the environment and recreate a new one to avoid any potential conflicts between the dependencies.

> How to install optax with jax and gpu compatibility?

You can just use:

```sh
pip install optax
```

Optax depends on JAX. If you install Optax in this way, it should work as expected, since you have already set up JAX successfully.

**Comment by lakatosgabor** [comment]
@ayaka14732 thanks your help.
I have now other issue with jax. i created a new env, but i use cuda 12.

11/02/2023 18:42:19 - WARNING - jax._src.xla_bridge -   CUDA backend failed to initialize: Found CUDA version 12010, but JAX was built against version 12020, which is newer. The copy of CUDA that is installed must be at least as new as the version against which JAX was built. 

Can I install jax 12010 version? I muss use the cuda 12010 version.

**Comment by lakatosgabor** [comment]
My solution in my project:

Install cuda 11.8, because this cuda version compatiblity with pytorch, and jax. You can check the versions and install command: [](https://pytorch.org/get-started/locally/)

Create empty enviromet after install cuda 11.8. I use python 3.10 on Ubuntu
`conda create -n <environment_name> python=3.10`
Install torch:
`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`

Install jax with gpu. It's important, use jax with cuda 11, if you use 11.* conda version!
`pip install -U "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`

Install flax. This command install optax for me.
`pip install flax`

Good luck!

**Comment by pengzhi1998** [comment]
Hi, I also faced this problem: `No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)` when directly installing it with `pip install flax`. 

My cuda version is 12.2, python version is 3.8 (this is requested). I tried different commands to install gpu-based jax, like:
```
pip install --upgrade "jax[cuda12_local]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```
, and
```
pip install --upgrade "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```
, and
```
pip install --upgrade "jax[cuda11_local]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```
 and
```
pip install --upgrade "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```

During installation, I would see a warning similar to `WARNING: jax 0.4.13 does not provide the extra 'cuda12-local'
`, but the installations would all succeed with a jax version of 0.4.13. However, when running: `python -c "import jax.numpy as jnp; jnp.ones((3,)); print('JAX installed successfully')"
`, I would always get something like:
```
2024-04-08 08:36:55.979761: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:407] There was an error before creating cudnn handle (302): cudaGetErrorName symbol not found. : cudaGetErrorString symbol not found.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 2161, in ones
    return lax.full(shape, 1, _jnp_dtype(dtype))
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/lax/lax.py", line 1206, in full
    return broadcast(fill_value, shape)
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/lax/lax.py", line 768, in broadcast
    return broadcast_in_dim(operand, tuple(sizes) + np.shape(operand), dims)
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/lax/lax.py", line 797, in broadcast_in_dim
    return broadcast_in_dim_p.bind(
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/core.py", line 380, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/core.py", line 815, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/dispatch.py", line 132, in apply_primitive
    compiled_fun = xla_primitive_callable(
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/util.py", line 284, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/util.py", line 277, in cached
    return f(*args, **kwargs)
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/dispatch.py", line 223, in xla_primitive_callable
    compiled = _xla_callable_uncached(
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/dispatch.py", line 253, in _xla_callable_uncached
    return computation.compile().unsafe_call
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/interpreters/pxla.py", line 2323, in compile
    executable = UnloadedMeshExecutable.from_hlo(
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/interpreters/pxla.py", line 2645, in from_hlo
    xla_executable, compile_options = _cached_compilation(
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/interpreters/pxla.py", line 2555, in _cached_compilation
    xla_executable = dispatch.compile_or_get_cached(
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/dispatch.py", line 497, in compile_or_get_cached
    return backend_compile(backend, computation, compile_options,
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/dispatch.py", line 465, in backend_compile
    return backend.compile(built_c, compile_options=options)
jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
```
May I have your suggestions on how to solve this problem? Thank you in advance for any help!! Look forward to your reply!

**Comment by ayaka14732** [comment]
@pengzhi1998 In a clean environment, do:

```
pip install "jax[cuda12_pip]==0.4.13" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
pip install flax
```

**Comment by pengzhi1998** [comment]
Thank you for your reply and help!
I got the problem, it was because I forgot to unset `LD_LIBRARY_PATH`. However, I still got: 
```
2024-04-09 22:39:58.055899: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:268] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
```
while during installation, **I found some warnings like**:
```
WARNING: jax 0.4.13 does not provide the extra 'cuda12-pip'
WARNING: The candidate selected for download or install is a yanked version: 'flax' candidate (version 0.7.1 at https://files.pythonhosted.org/packages/5d/95/c298b0be5d6f16258e422d176788d16fe0ebeabcbd407b259d29644af66b/flax-0.7.1-py3-none-any.whl (from https://pypi.org/simple/flax/))
Reason for being yanked: multiple commits accidentally pushed under same tag causing some chaos
```
Are these warnings some possible problem for the failed use of JAX with CUDA? Or what could some other possible issues?

**Comment by pengzhi1998** [comment]
Oh, the problem is back again:
```
>>> import jax.numpy as jnp
>>> from jax import grad, jit, vmap
>>> from jax import random
>>> key = random.key(0)
2024-04-10 00:24:59.976765: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:439] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2024-04-10 00:24:59.976798: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:443] Memory usage: 1844314112 bytes free, 8361017344 bytes total.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/random.py", line 139, in key
    return prng.seed_with_impl(impl, seed)
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/prng.py", line 406, in seed_with_impl
    return random_seed(seed, impl=impl)
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/prng.py", line 690, in random_seed
    return random_seed_p.bind(seeds_arr, impl=impl)
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/prng.py", line 702, in random_seed_impl
    base_arr = random_seed_impl_base(seeds, impl=impl)
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/prng.py", line 707, in random_seed_impl_base
    return seed(seeds)
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/prng.py", line 936, in threefry_seed
    return _threefry_seed(seed)
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/pjit.py", line 250, in cache_miss
    outs, out_flat, out_tree, args_flat, jaxpr = _python_pjit_helper(
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/pjit.py", line 163, in _python_pjit_helper
    out_flat = pjit_p.bind(*args_flat, **params)
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/core.py", line 2677, in bind
    return self.bind_with_trace(top_trace, args, params)
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/core.py", line 815, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/pjit.py", line 1203, in _pjit_call_impl
    return xc._xla.pjit(name, f, call_impl_cache_miss, [], [], donated_argnums,
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/pjit.py", line 1187, in call_impl_cache_miss
    out_flat, compiled = _pjit_call_impl_python(
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/pjit.py", line 1120, in _pjit_call_impl_python
    compiled = _pjit_lower(
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/interpreters/pxla.py", line 2323, in compile
    executable = UnloadedMeshExecutable.from_hlo(
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/interpreters/pxla.py", line 2645, in from_hlo
    xla_executable, compile_options = _cached_compilation(
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/interpreters/pxla.py", line 2555, in _cached_compilation
    xla_executable = dispatch.compile_or_get_cached(
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/dispatch.py", line 497, in compile_or_get_cached
    return backend_compile(backend, computation, compile_options,
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/dispatch.py", line 465, in backend_compile
    return backend.compile(built_c, compile_options=options)
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/random.py", line 139, in key
    return prng.seed_with_impl(impl, seed)
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/prng.py", line 406, in seed_with_impl
    return random_seed(seed, impl=impl)
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/prng.py", line 690, in random_seed
    return random_seed_p.bind(seeds_arr, impl=impl)
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/core.py", line 380, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/core.py", line 815, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/prng.py", line 702, in random_seed_impl
    base_arr = random_seed_impl_base(seeds, impl=impl)
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/prng.py", line 707, in random_seed_impl_base
    return seed(seeds)
  File "/home/pengzhi/anaconda3/envs/isaacgym-test/lib/python3.8/site-packages/jax/_src/prng.py", line 936, in threefry_seed
    return _threefry_seed(seed)
jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
```

**Comment by pengzhi1998** [comment]
Thank you so much for your quick reply and help!!! @ayaka14732 

I'm really sorry that I made a very stupid mistake, that the cuda version is 10.1 based on `nvcc --version`.

In a clean env, I tried:
```
pip install "jax[cuda10_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
pip install flax
```
and get it installed successfully with:
```
Looking in links: https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
Collecting jax[cuda10_pip]
  Using cached jax-0.4.13-py3-none-any.whl
WARNING: jax 0.4.13 does not provide the extra 'cuda10-pip'
Collecting ml-dtypes>=0.1.0 (from jax[cuda10_pip])
  Using cached ml_dtypes-0.2.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Collecting numpy>=1.21 (from jax[cuda10_pip])
  Using cached numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
Collecting opt-einsum (from jax[cuda10_pip])
  Using cached opt_einsum-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Collecting scipy>=1.7 (from jax[cuda10_pip])
  Using cached scipy-1.10.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (58 kB)
Collecting importlib-metadata>=4.6 (from jax[cuda10_pip])
  Using cached importlib_metadata-7.1.0-py3-none-any.whl.metadata (4.7 kB)
Collecting zipp>=0.5 (from importlib-metadata>=4.6->jax[cuda10_pip])
  Using cached zipp-3.18.1-py3-none-any.whl.metadata (3.5 kB)
Using cached importlib_metadata-7.1.0-py3-none-any.whl (24 kB)
Using cached ml_dtypes-0.2.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.0 MB)
Using cached numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
Using cached scipy-1.10.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.5 MB)
Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Using cached zipp-3.18.1-py3-none-any.whl (8.2 kB)
Installing collected packages: zipp, numpy, scipy, opt-einsum, ml-dtypes, importlib-metadata, jax
Successfully installed importlib-metadata-7.1.0 jax-0.4.13 ml-dtypes-0.2.0 numpy-1.24.4 opt-einsum-3.3.0 scipy-1.10.1 zipp-3.18.1
Collecting flax
  Using cached flax-0.7.2-py3-none-any.whl.metadata (10.0 kB)
Requirement already satisfied: numpy>=1.12 in ./anaconda3/envs/isaacgym-test/lib/python3.8/site-packages (from flax) (1.24.4)
Requirement already satisfied: jax>=0.4.2 in ./anaconda3/envs/isaacgym-test/lib/python3.8/site-packages (from flax) (0.4.13)
Collecting msgpack (from flax)
  Using cached msgpack-1.0.8-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.1 kB)
Collecting optax (from flax)
  Using cached optax-0.1.8-py3-none-any.whl.metadata (14 kB)
Collecting orbax-checkpoint (from flax)
  Using cached orbax_checkpoint-0.2.3-py3-none-any.whl.metadata (1.8 kB)
Collecting tensorstore (from flax)
  Using cached tensorstore-0.1.45-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.9 kB)
Collecting rich>=11.1 (from flax)
  Using cached rich-13.7.1-py3-none-any.whl.metadata (18 kB)
Collecting typing-extensions>=4.1.1 (from flax)
  Using cached typing_extensions-4.11.0-py3-none-any.whl.metadata (3.0 kB)
Collecting PyYAML>=5.4.1 (from flax)
  Using cached PyYAML-6.0.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Requirement already satisfied: ml-dtypes>=0.1.0 in ./anaconda3/envs/isaacgym-test/lib/python3.8/site-packages (from jax>=0.4.2->flax) (0.2.0)
Requirement already satisfied: opt-einsum in ./anaconda3/envs/isaacgym-test/lib/python3.8/site-packages (from jax>=0.4.2->flax) (3.3.0)
Requirement already satisfied: scipy>=1.7 in ./anaconda3/envs/isaacgym-test/lib/python3.8/site-packages (from jax>=0.4.2->flax) (1.10.1)
Requirement already satisfied: importlib-metadata>=4.6 in ./anaconda3/envs/isaacgym-test/lib/python3.8/site-packages (from jax>=0.4.2->flax) (7.1.0)
Collecting markdown-it-py>=2.2.0 (from rich>=11.1->flax)
  Using cached markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich>=11.1->flax)
  Using cached pygments-2.17.2-py3-none-any.whl.metadata (2.6 kB)
Collecting absl-py>=0.7.1 (from optax->flax)
  Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
Collecting chex>=0.1.7 (from optax->flax)
  Using cached chex-0.1.7-py3-none-any.whl.metadata (17 kB)
Collecting jaxlib>=0.1.37 (from optax->flax)
  Using cached jaxlib-0.4.13-cp38-cp38-manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting cached_property (from orbax-checkpoint->flax)
  Using cached cached_property-1.5.2-py2.py3-none-any.whl.metadata (11 kB)
Collecting importlib_resources (from orbax-checkpoint->flax)
  Using cached importlib_resources-6.4.0-py3-none-any.whl.metadata (3.9 kB)
Collecting etils (from orbax-checkpoint->flax)
  Using cached etils-1.3.0-py3-none-any.whl.metadata (5.5 kB)
Collecting nest_asyncio (from orbax-checkpoint->flax)
  Using cached nest_asyncio-1.6.0-py3-none-any.whl.metadata (2.8 kB)
Collecting dm-tree>=0.1.5 (from chex>=0.1.7->optax->flax)
  Using cached dm_tree-0.1.8-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.9 kB)
Collecting toolz>=0.9.0 (from chex>=0.1.7->optax->flax)
  Using cached toolz-0.12.1-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: zipp>=0.5 in ./anaconda3/envs/isaacgym-test/lib/python3.8/site-packages (from importlib-metadata>=4.6->jax>=0.4.2->flax) (3.18.1)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=11.1->flax)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Using cached flax-0.7.2-py3-none-any.whl (226 kB)
Using cached PyYAML-6.0.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (736 kB)
Using cached rich-13.7.1-py3-none-any.whl (240 kB)
Using cached typing_extensions-4.11.0-py3-none-any.whl (34 kB)
Using cached msgpack-1.0.8-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (390 kB)
Using cached optax-0.1.8-py3-none-any.whl (199 kB)
Using cached orbax_checkpoint-0.2.3-py3-none-any.whl (81 kB)
Using cached tensorstore-0.1.45-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.5 MB)
Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
Using cached chex-0.1.7-py3-none-any.whl (89 kB)
Using cached jaxlib-0.4.13-cp38-cp38-manylinux2014_x86_64.whl (71.6 MB)
Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Using cached pygments-2.17.2-py3-none-any.whl (1.2 MB)
Using cached cached_property-1.5.2-py2.py3-none-any.whl (7.6 kB)
Using cached etils-1.3.0-py3-none-any.whl (126 kB)
Using cached importlib_resources-6.4.0-py3-none-any.whl (38 kB)
Using cached nest_asyncio-1.6.0-py3-none-any.whl (5.2 kB)
Using cached dm_tree-0.1.8-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (152 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Using cached toolz-0.12.1-py3-none-any.whl (56 kB)
Installing collected packages: dm-tree, cached_property, typing-extensions, toolz, tensorstore, PyYAML, pygments, nest_asyncio, msgpack, mdurl, importlib_resources, etils, absl-py, markdown-it-py, jaxlib, rich, orbax-checkpoint, chex, optax, flax
Successfully installed PyYAML-6.0.1 absl-py-2.1.0 cached_property-1.5.2 chex-0.1.7 dm-tree-0.1.8 etils-1.3.0 flax-0.7.2 importlib_resources-6.4.0 jaxlib-0.4.13 markdown-it-py-3.0.0 mdurl-0.1.2 msgpack-1.0.8 nest_asyncio-1.6.0 optax-0.1.8 orbax-checkpoint-0.2.3 pygments-2.17.2 rich-13.7.1 tensorstore-0.1.45 toolz-0.12.1 typing-extensions-4.11.0
```
But when trying to run some example codes, I got:
```
Python 3.8.19 (default, Mar 20 2024, 19:58:24) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jax.numpy as jnp
>>> from jax import grad, jit, vmap
>>> from jax import random
>>> key = random.key(0)
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
```
Thus, Jax still cannot make use of GPU. May I again have your suggestions on this problem? Thank you so much for considering this matter and your help!

**Comment by jakevdp** [comment]
Regarding the `jax[cuda10_pip]` error, see the discussion in #20678
