### ISSUE TITLE
Could not find any cuda.h matching version ''12.0'' in any subdirectory:

### ISSUE THREAD

**Issue by mriamnobody** [google/jax#17635]
### Description

```

     _   _  __  __
    | | / \ \ \/ /
 _  | |/ _ \ \  /
| |_| / ___ \/  \
 \___/_/   \/_/\_\


Bazel binary path: C:\Users\rosha\Downloads\Compressed\bazel\bazel.exe
Bazel version: 6.3.2
Python binary path: C:/Users/rosha/AppData/Local/Programs/Python/Python310/python.exe
Python version: 3.10
NumPy version: 1.24.3
MKL-DNN enabled: yes
Target CPU: AMD64
Target CPU features: release
CUDA enabled: yes
CUDA toolkit path: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.0
CUDA version: '12.0'
CUDNN version: '8.9.5'
NCCL enabled: yes
TPU enabled: no
ROCm enabled: no

Building XLA and installing it in the jaxlib source tree...
C:\Users\rosha\Downloads\Compressed\bazel\bazel.exe run --verbose_failures=true //jaxlib/tools:build_wheel -- --output_path=C:\Users\rosha\Downloads\Compressed\jax-main\build\dist --cpu=AMD64
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
INFO: Reading rc options for 'run' from c:\users\rosha\downloads\compressed\jax-main\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  Inherited 'build' options: --python_path=C:/Users/rosha/AppData/Local/Programs/Python/Python310/python.exe
INFO: Reading rc options for 'run' from c:\users\rosha\downloads\compressed\jax-main\.bazelrc:
  Inherited 'build' options: --nocheck_visibility --apple_platform_type=macos --macos_minimum_os=10.14 --announce_rc --define open_source_build=true --spawn_strategy=standalone --enable_platform_specific_config --experimental_cc_shared_library --define=no_aws_support=true --define=no_gcp_support=true --define=no_hdfs_support=true --define=no_kafka_support=true --define=no_ignite_support=true --define=grpc_no_ares=true --define=tsl_link_protobuf=true -c opt --config=short_logs --copt=-DMLIR_PYTHON_PACKAGE_PREFIX=jaxlib.mlir. --@xla//xla/python:enable_gpu=false
INFO: Reading rc options for 'run' from c:\users\rosha\downloads\compressed\jax-main\.jax_configure.bazelrc:
  Inherited 'build' options: --strategy=Genrule=standalone --repo_env PYTHON_BIN_PATH=C:/Users/rosha/AppData/Local/Programs/Python/Python310/python.exe --action_env=PYENV_ROOT --python_path=C:/Users/rosha/AppData/Local/Programs/Python/Python310/python.exe --action_env CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.0 --action_env TF_CUDA_PATHS=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.0 --action_env TF_CUDA_VERSION='12.0' --action_env TF_CUDNN_VERSION='8.9.5' --config=mkl_open_source_only --config=cuda
INFO: Found applicable config definition build:short_logs in file c:\users\rosha\downloads\compressed\jax-main\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:mkl_open_source_only in file c:\users\rosha\downloads\compressed\jax-main\.bazelrc: --define=tensorflow_mkldnn_contraction_kernel=1
INFO: Found applicable config definition build:cuda in file c:\users\rosha\downloads\compressed\jax-main\.bazelrc: --repo_env TF_NEED_CUDA=1 --action_env TF_CUDA_COMPUTE_CAPABILITIES=sm_52,sm_60,sm_70,sm_80,compute_90 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda --@xla//xla/python:enable_gpu=true --@xla//xla/python:jax_cuda_pip_rpaths=true --define=xla_python_enable_gpu=true
INFO: Found applicable config definition build:windows in file c:\users\rosha\downloads\compressed\jax-main\.bazelrc: --features=compiler_param_file --features=archive_param_file --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/Zc:preprocessor --cxxopt=/std:c++17 --host_cxxopt=/std:c++17 --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --incompatible_strict_action_env=true
DEBUG: C:/users/rosha/_bazel_rosha/pblidhgn/external/xla/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'tf_runtime' because it already exists.
DEBUG: C:/users/rosha/_bazel_rosha/pblidhgn/external/xla/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'llvm-raw' because it already exists.
INFO: Repository local_config_cuda instantiated at:
  C:/users/rosha/downloads/compressed/jax-main/WORKSPACE:15:15: in <toplevel>
  C:/users/rosha/_bazel_rosha/pblidhgn/external/xla/workspace2.bzl:90:19: in workspace
  C:/users/rosha/_bazel_rosha/pblidhgn/external/tsl/workspace2.bzl:626:19: in workspace
  C:/users/rosha/_bazel_rosha/pblidhgn/external/tsl/workspace2.bzl:70:19: in _tf_toolchains
Repository rule cuda_configure defined at:
  C:/users/rosha/_bazel_rosha/pblidhgn/external/tsl/third_party/gpus/cuda_configure.bzl:1490:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "C:/users/rosha/_bazel_rosha/pblidhgn/external/tsl/third_party/gpus/cuda_configure.bzl", line 1443, column 38, in _cuda_autoconf_impl
                _create_local_cuda_repository(repository_ctx)
        File "C:/users/rosha/_bazel_rosha/pblidhgn/external/tsl/third_party/gpus/cuda_configure.bzl", line 1013, column 35, in _create_local_cuda_repository
                cuda_config = _get_cuda_config(repository_ctx, find_cuda_config_script)
        File "C:/users/rosha/_bazel_rosha/pblidhgn/external/tsl/third_party/gpus/cuda_configure.bzl", line 695, column 30, in _get_cuda_config
                config = find_cuda_config(repository_ctx, find_cuda_config_script, ["cuda", "cudnn"])
        File "C:/users/rosha/_bazel_rosha/pblidhgn/external/tsl/third_party/gpus/cuda_configure.bzl", line 672, column 41, in find_cuda_config
                exec_result = _exec_find_cuda_config(repository_ctx, script_path, cuda_libraries)
        File "C:/users/rosha/_bazel_rosha/pblidhgn/external/tsl/third_party/gpus/cuda_configure.bzl", line 666, column 19, in _exec_find_cuda_config
                return execute(repository_ctx, [python_bin, "-c", decompress_and_execute_cmd])
        File "C:/users/rosha/_bazel_rosha/pblidhgn/external/tsl/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
Could not find any cuda.h matching version ''12.0'' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
        'local/cuda/extras/CUPTI/include'
of:
        'C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.0'
ERROR: C:/users/rosha/downloads/compressed/jax-main/WORKSPACE:15:15: fetching cuda_configure rule //external:local_config_cuda: Traceback (most recent call last):
        File "C:/users/rosha/_bazel_rosha/pblidhgn/external/tsl/third_party/gpus/cuda_configure.bzl", line 1443, column 38, in _cuda_autoconf_impl
                _create_local_cuda_repository(repository_ctx)
        File "C:/users/rosha/_bazel_rosha/pblidhgn/external/tsl/third_party/gpus/cuda_configure.bzl", line 1013, column 35, in _create_local_cuda_repository
                cuda_config = _get_cuda_config(repository_ctx, find_cuda_config_script)
        File "C:/users/rosha/_bazel_rosha/pblidhgn/external/tsl/third_party/gpus/cuda_configure.bzl", line 695, column 30, in _get_cuda_config
                config = find_cuda_config(repository_ctx, find_cuda_config_script, ["cuda", "cudnn"])
        File "C:/users/rosha/_bazel_rosha/pblidhgn/external/tsl/third_party/gpus/cuda_configure.bzl", line 672, column 41, in find_cuda_config
                exec_result = _exec_find_cuda_config(repository_ctx, script_path, cuda_libraries)
        File "C:/users/rosha/_bazel_rosha/pblidhgn/external/tsl/third_party/gpus/cuda_configure.bzl", line 666, column 19, in _exec_find_cuda_config
                return execute(repository_ctx, [python_bin, "-c", decompress_and_execute_cmd])
        File "C:/users/rosha/_bazel_rosha/pblidhgn/external/tsl/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
Could not find any cuda.h matching version ''12.0'' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
        'local/cuda/extras/CUPTI/include'
of:
        'C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.0'
INFO: Repository rules_python instantiated at:
  C:/users/rosha/downloads/compressed/jax-main/WORKSPACE:15:15: in <toplevel>
  C:/users/rosha/_bazel_rosha/pblidhgn/external/xla/workspace2.bzl:90:19: in workspace
  C:/users/rosha/_bazel_rosha/pblidhgn/external/tsl/workspace2.bzl:636:21: in workspace
  C:/users/rosha/_bazel_rosha/pblidhgn/external/tsl/workspace2.bzl:528:20: in _tf_repositories
  C:/users/rosha/_bazel_rosha/pblidhgn/external/tsl/third_party/repo.bzl:136:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  C:/users/rosha/_bazel_rosha/pblidhgn/external/tsl/third_party/repo.bzl:89:35: in <toplevel>
INFO: Repository rules_cc instantiated at:
  C:/users/rosha/downloads/compressed/jax-main/WORKSPACE:18:15: in <toplevel>
  C:/users/rosha/_bazel_rosha/pblidhgn/external/xla/workspace1.bzl:12:19: in workspace
  C:/users/rosha/_bazel_rosha/pblidhgn/external/tsl/workspace1.bzl:17:28: in workspace
  C:/users/rosha/_bazel_rosha/pblidhgn/external/rules_cuda/cuda/dependencies.bzl:72:18: in rules_cuda_dependencies
  C:/users/rosha/_bazel_rosha/pblidhgn/external/rules_cuda/cuda/dependencies.bzl:35:17: in _rules_cc
Repository rule http_archive defined at:
  C:/users/rosha/_bazel_rosha/pblidhgn/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
ERROR: Skipping '@xla//xla/python:enable_gpu': no such package '@local_config_cuda//cuda': Repository command failed
Could not find any cuda.h matching version ''12.0'' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
        'local/cuda/extras/CUPTI/include'
of:
        'C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.0'
WARNING: Target pattern parsing failed.
ERROR: @xla//xla/python:enable_gpu :: Error loading option @xla//xla/python:enable_gpu: no such package '@local_config_cuda//cuda': Repository command failed
Could not find any cuda.h matching version ''12.0'' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
        'local/cuda/extras/CUPTI/include'
of:
        'C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.0'
Loading:
Traceback (most recent call last):
  File "C:\Users\rosha\Downloads\Compressed\jax-main\build\build.py", line 591, in <module>
    main()
  File "C:\Users\rosha\Downloads\Compressed\jax-main\build\build.py", line 572, in main
    shell(command)
  File "C:\Users\rosha\Downloads\Compressed\jax-main\build\build.py", line 53, in shell
    output = subprocess.check_output(cmd)
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\rosha\\Downloads\\Compressed\\bazel\\bazel.exe', 'run', '--verbose_failures=true', '//jaxlib/tools:build_wheel', '--', '--output_path=C:\\Users\\rosha\\Downloads\\Compressed\\jax-main\\build\\dist', '--cpu=AMD64']' returned non-zero exit status 2.
```

### What jax/jaxlib version are you using?

jax v04.14, jaxlib v0.4.14

### Which accelerator(s) are you using?

Nvidia 3090 Ti

### Additional system info

Python: 3.10.7, OS(Windows 11)

### NVIDIA GPU info

I have provided all the necessary paths and flags but still getting the error. I have placed all the required files of `cudnn` in the `lib`,`bin` and `include` folder of `cuda`.

**Comment by hawkinsp** [comment]
Note that JAX on Windows (and especially *CUDA*-enabled builds) are community supported. We'll welcome contributions to fix things, but we do not ourselves test or try to keep JAX/Windows/CUDA working.

The supported path on Windows is to use WSL and the Linux wheels.

**Comment by mriamnobody** [comment]
> Note that JAX on Windows (and especially _CUDA_-enabled builds) is community supported. We'll welcome contributions to fix things, but we do not ourselves test or try to keep JAX/Windows/CUDA working.

I'll try to figure out a way to build Cuda-enabled Jax.

> The supported path on Windows for CUDA support is to use WSL and the Linux wheels.

Will try this too

> If you want to debug this: where is `cuda.h` on your system? Is the build looking in the right place?

The error starts from:
```
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "C:/users/rosha/_bazel_rosha/pblidhgn/external/tsl/third_party/gpus/cuda_configure.bzl", line 1443, column 38, in _cuda_autoconf_impl
                _create_local_cuda_repository(repository_ctx)
        File "C:/users/rosha/_bazel_rosha/pblidhgn/external/tsl/third_party/gpus/cuda_configure.bzl", line 1013, column 35, in _create_local_cuda_repository
                cuda_config = _get_cuda_config(repository_ctx, find_cuda_config_script)
        File "C:/users/rosha/_bazel_rosha/pblidhgn/external/tsl/third_party/gpus/cuda_configure.bzl", line 695, column 30, in _get_cuda_config
                config = find_cuda_config(repository_ctx, find_cuda_config_script, ["cuda", "cudnn"])
        File "C:/users/rosha/_bazel_rosha/pblidhgn/external/tsl/third_party/gpus/cuda_configure.bzl", line 672, column 41, in find_cuda_config
                exec_result = _exec_find_cuda_config(repository_ctx, script_path, cuda_libraries)
        File "C:/users/rosha/_bazel_rosha/pblidhgn/external/tsl/third_party/gpus/cuda_configure.bzl", line 666, column 19, in _exec_find_cuda_config
                return execute(repository_ctx, [python_bin, "-c", decompress_and_execute_cmd])
        File "C:/users/rosha/_bazel_rosha/pblidhgn/external/tsl/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
Could not find any cuda.h matching version ''12.0'' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
        'local/cuda/extras/CUPTI/include'
of:
        'C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.0/include/'
```

I have checked for `cuda.h` file and it is present at `C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.0/include/`. I don't understand why it is not able to find it.

Command I have used:
`python build.py --enable_cuda --cuda_path="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.0/" --cudnn_path="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.0" --cuda_version='12.0' --cudnn_version='8.9.5'`

**Comment by phineas-pta** [comment]
my 2¢ is the path must not have any trailing slash nor use backslash

my attempt is like this:
```
python build/build.py
	--enable_cuda
	--cuda_path="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.1"
	--cudnn_path="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.1"
	--cuda_version="12.1"
	--cudnn_version="8.9.5"
```
unfortunately i encounter error
```
return find_msvc_tool(repository_ctx, vc_path, "cl.exe").replace("\\", "/")
Error: 'NoneType' value has no field or method 'replace'
```
but im having latest visual studio (cmake 3.26.4, msbuild 17.7.2, cl 19.37.32822), i can use `cl` in console without issue but bazel doesnt recognize it

**Comment by pctablet505** [comment]
I was working with Jax, it works much better than torch for RL related works, and for me I want to use Jax with cuda on **windows** **without WSL** requirement, I am open to contributing it, if contributions are welcome for it.

@mattjj do you have any suggestions for how we can do it? 
I might do some research and share a implementation plan for it.

**Comment by hawkinsp** [comment]
As always, we welcome PRs.

Likely there are three things you have to do to get native windows support working:
* teach the Bazel rules, especially the CUDA-related Bazel rules about Windows. For example, the Bazel rules download the CUDA packages we build against, and probably don't know anything about Windows at the moment.
* fix any code that doesn't work under Windows. I'm sure there's some platform specific things that will need to be modified.
* get the tests passing under CUDA on Windows (bazel test)

I suspect you may have some luck pointing your favorite AI tool at these tasks, it is the sort of thing for which AI might excel.
