### ISSUE TITLE
[jax2tf] polymorphic_shapes: ValueError: Cannot convert '(b, t, 1)' to a shape. Found invalid entry 't'.

### ISSUE THREAD

**Issue by lbortolotti** [google/jax#17803]
### Description

I can't get polymorphic_shapes to work on anything other than just batch size.

Minimal (not) working example follows:

```
import os

os.environ['KERAS_BACKEND'] = 'jax'
import keras_core as keras
import numpy as np

window_size = 100
inference_window_size = None

X = np.random.random((1024, window_size, 1))
Y = np.random.random((1024, window_size, 1))

model = keras.Sequential([keras.layers.Dense(128, activation='relu'),
                          keras.layers.Dense(64, activation='relu'),
                          keras.layers.Dense(1, activation='relu'),
                          ])

model.compile(optimizer=keras.optimizers.Adam(), loss=keras.losses.mean_squared_error)

model.fit(X, Y, batch_size=32)

model.summary()

import tensorflow as tf
from jax.experimental import jax2tf

module = tf.Module()
module.model = model
poly_shape_window_size = 't' if inference_window_size is None else inference_window_size
poly_shape = jax2tf.shape_poly.PolyShape('b', poly_shape_window_size, 1)

print(f'poly_shape: {poly_shape}')

predict_fn = jax2tf.convert(module.model.call,
                            native_serialization_platforms=('cpu',),
                            polymorphic_shapes=str(poly_shape),
                            )


@tf.function(autograph=False, input_signature=[tf.TensorSpec(shape=(None, inference_window_size, 1), dtype=tf.float32)])
def fn(x):
    outputs = predict_fn(x)
    return outputs


module.fn = fn

# TF 2.14 needed...
# https://github.com/google/jax/issues/17194
tf.saved_model.save(module, 'model.tf', signatures={'serving_default': module.fn})
```

Error:

```
Traceback (most recent call last):
  File "C:\Projects\jax\repro_1.py", line 50, in <module>
    tf.saved_model.save(module, 'model.tf', signatures={'serving_default': module.fn})
  File "C:\Projects\jax\venv\lib\site-packages\tensorflow\python\saved_model\save.py", line 1331, in save
    save_and_return_nodes(obj, export_dir, signatures, options)
  File "C:\Projects\jax\venv\lib\site-packages\tensorflow\python\saved_model\save.py", line 1366, in save_and_return_nodes
    _build_meta_graph(obj, signatures, options, meta_graph_def))
  File "C:\Projects\jax\venv\lib\site-packages\tensorflow\python\saved_model\save.py", line 1578, in _build_meta_graph
    return _build_meta_graph_impl(obj, signatures, options, meta_graph_def)
  File "C:\Projects\jax\venv\lib\site-packages\tensorflow\python\saved_model\save.py", line 1495, in _build_meta_graph_impl
    signature_serialization.canonicalize_signatures(signatures)
  File "C:\Projects\jax\venv\lib\site-packages\tensorflow\python\saved_model\signature_serialization.py", line 139, in canonicalize_signatures
    original_function = signature_function = _get_signature(function)
  File "C:\Projects\jax\venv\lib\site-packages\tensorflow\python\saved_model\signature_serialization.py", line 45, in _get_signature
    function = function._get_concrete_function_garbage_collected()  # pylint: disable=protected-access
  File "C:\Projects\jax\venv\lib\site-packages\tensorflow\python\eager\polymorphic_function\polymorphic_function.py", line 1192, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "C:\Projects\jax\venv\lib\site-packages\tensorflow\python\eager\polymorphic_function\polymorphic_function.py", line 694, in _initialize
    self._concrete_variable_creation_fn = tracing_compilation.trace_function(
  File "C:\Projects\jax\venv\lib\site-packages\tensorflow\python\eager\polymorphic_function\tracing_compilation.py", line 178, in trace_function
    concrete_function = _maybe_define_function(
  File "C:\Projects\jax\venv\lib\site-packages\tensorflow\python\eager\polymorphic_function\tracing_compilation.py", line 284, in _maybe_define_function
    concrete_function = _create_concrete_function(
  File "C:\Projects\jax\venv\lib\site-packages\tensorflow\python\eager\polymorphic_function\tracing_compilation.py", line 308, in _create_concrete_function
    traced_func_graph = func_graph_module.func_graph_from_py_func(
  File "C:\Projects\jax\venv\lib\site-packages\tensorflow\python\framework\func_graph.py", line 1059, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Projects\jax\venv\lib\site-packages\tensorflow\python\eager\polymorphic_function\polymorphic_function.py", line 597, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\Projects\jax\repro_1.py", line 42, in fn
    outputs = predict_fn(x)
  File "C:\Projects\jax\venv\lib\site-packages\jax\experimental\jax2tf\jax2tf.py", line 402, in converted_fun_tf
    impl.before_conversion()
  File "C:\Projects\jax\venv\lib\site-packages\jax\experimental\jax2tf\jax2tf.py", line 506, in before_conversion
    self.exported = export.export(
  File "C:\Projects\jax\venv\lib\site-packages\jax\experimental\export\export.py", line 422, in do_export
    lowered = wrapped_fun_jax.lower(
  File "C:\Projects\jax\venv\lib\site-packages\keras_core\src\models\sequential.py", line 187, in call
    return self._functional.call(inputs, training=training, mask=mask)
  File "C:\Projects\jax\venv\lib\site-packages\keras_core\src\models\functional.py", line 188, in call
    outputs = self._run_through_graph(
  File "C:\Projects\jax\venv\lib\site-packages\keras_core\src\ops\function.py", line 140, in _run_through_graph
    outputs = operation_fn(node.operation)(*args, **kwargs)
  File "C:\Projects\jax\venv\lib\site-packages\keras_core\src\models\functional.py", line 574, in call
    return operation(*args, **kwargs)
  File "C:\Projects\jax\venv\lib\site-packages\keras_core\src\utils\traceback_utils.py", line 123, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Projects\jax\venv\lib\site-packages\keras_core\src\backend\common\variables.py", line 437, in standardize_shape
    raise ValueError(
ValueError: Cannot convert '(b, t, 1)' to a shape. Found invalid entry 't'. 
```

### What jax/jaxlib version are you using?

jax==0.4.16 jaxlib==0.4.16  tensorflow==2.14.0rc1 keras-core==0.1.7

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.10.11, Windows

**Comment by lbortolotti** [comment]
Any updates on this?

**Comment by lbortolotti** [comment]
Probably a keras bug, re-opened there (https://github.com/keras-team/keras/issues/19048)
