### ISSUE TITLE
FFT implementation in float16

### ISSUE THREAD

**Issue by LiamGon** [google/jax#17954]
Hi,
I'm interested into speeding up the rFFT with jax on GPU. 
I found out the rFFT operation from jax.numpy does not work with float16 or bfloat16
Here is my code : 
```
import jax.numpy as jnp

x = jnp.linspace(0, 100)

# this line works fine
jnp.fft.rfft(x.astype(dtype=jnp.float32))

# it breaks
y = jnp.fft.rfft(x.astype(dtype=jnp.float16))

# also breaks
jnp.fft.rfft(x.astype(dtype=jnp.bfloat16))
```
Here are the error logs :
```
loc("jit(fft)/jit(main)/fft[fft_type=FftType.RFFT fft_lengths=(50,)]"("<stdin>":1:0)): error: RFFT requires f32 or f64 input type, but is given 'f16'.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/trix/lib/python3.10/site-packages/jax/_src/numpy/fft.py", line 167, in rfft
    return _fft_core_1d('rfft', xla_client.FftType.RFFT, a, n=n, axis=axis,
  File "/opt/conda/envs/trix/lib/python3.10/site-packages/jax/_src/numpy/fft.py", line 149, in _fft_core_1d
    return _fft_core(func_name, fft_type, a, s, axes, norm)
  File "/opt/conda/envs/trix/lib/python3.10/site-packages/jax/_src/numpy/fft.py", line 97, in _fft_core
    transformed = lax.fft(arr, fft_type, tuple(s))
jax._src.source_info_util.JaxStackTraceBeforeTransformation: ValueError: Operation creation failed

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/trix/lib/python3.10/site-packages/jax/_src/numpy/fft.py", line 167, in rfft
    return _fft_core_1d('rfft', xla_client.FftType.RFFT, a, n=n, axis=axis,
  File "/opt/conda/envs/trix/lib/python3.10/site-packages/jax/_src/numpy/fft.py", line 149, in _fft_core_1d
    return _fft_core(func_name, fft_type, a, s, axes, norm)
  File "/opt/conda/envs/trix/lib/python3.10/site-packages/jax/_src/numpy/fft.py", line 97, in _fft_core
    transformed = lax.fft(arr, fft_type, tuple(s))
  File "/opt/conda/envs/trix/lib/python3.10/site-packages/jaxlib/mlir/dialects/_stablehlo_ops_gen.py", line 2485, in __init__
    super().__init__(self.build_generic(attributes=attributes, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))
ValueError: Operation creation failed
```

As was wondering if rfft was actually implemented in fp16, but there might be a technical reason such as stability/accuracy. If not, this feature would be quite appreciable.

As a note, jnp.fft.fft is implemented in fp16. But on a sequence of length 1e8, fft-fp16 is taking 30% longer than rfft-fp32 so there is no advantage in speeding up rfft using fft-fp16.

I also tried with the jitted version and I got the same error.

Environment:
```
jax==0.4.17
jaxlib==0.4.17+cuda12.cudnn89
```

Harware: A100 40GB

**Comment by hawkinsp** [comment]
Yes, we currently don't support float16 FFTs. At the moment, you must upcast to float32.

The largest blocker to supporting float16 FFTs is that we don't have support for a complex32 type in NumPy, JAX or XLA. We'd have to add that.

Notes:
* I sent #17978 to fix the bad error for `bfloat16` inputs to RFFT.
* I also filed https://github.com/openxla/stablehlo/issues/1794, which is why stablehlo lowering failed for bf16 inputs.
