### ISSUE TITLE
RuntimeError in jax-metal

### ISSUE THREAD

**Issue by eterevsky** [google/jax#18006]
### Description

I've installed jax-metal 0.0.4 following instructions at https://developer.apple.com/metal/jax/. When running `python -c 'import jax; print(jax.numpy.arange(10))'` I'm getting the following error:

```
$ python -c 'import jax; print(jax.numpy.arange(10))'
2023-10-08 20:10:19.963804: W pjrt_plugin/src/mps_client.cc:534] WARNING: JAX Apple GPU support is experimental and not all JAX functionality is correctly supported!
Metal device set to: Apple M1 Pro

systemMemory: 32.00 GB
maxCacheSize: 10.67 GB

2023-10-08 20:10:19.999 Python[52193:9802415] -[MPSGraphExecutable initWithMLIRBytecode:executableDescriptor:]: unrecognized selector sent to instance 0x125a7cb70
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/olege/jax-metal/lib/python3.11/site-packages/jax/_src/numpy/lax_numpy.py", line 2304, in arange
    return lax.iota(dtype, start)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/olege/jax-metal/lib/python3.11/site-packages/jax/_src/lax/lax.py", line 1222, in iota
    return broadcasted_iota(dtype, (size,), 0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/olege/jax-metal/lib/python3.11/site-packages/jax/_src/lax/lax.py", line 1232, in broadcasted_iota
    return iota_p.bind(*dynamic_shape, dtype=dtype, shape=tuple(static_shape),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/olege/jax-metal/lib/python3.11/site-packages/jax/_src/core.py", line 380, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/olege/jax-metal/lib/python3.11/site-packages/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/olege/jax-metal/lib/python3.11/site-packages/jax/_src/core.py", line 790, in process_primitive
    return primitive.impl(*tracers, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/olege/jax-metal/lib/python3.11/site-packages/jax/_src/dispatch.py", line 132, in apply_primitive
    compiled_fun = xla_primitive_callable(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/olege/jax-metal/lib/python3.11/site-packages/jax/_src/util.py", line 284, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/olege/jax-metal/lib/python3.11/site-packages/jax/_src/util.py", line 277, in cached
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/olege/jax-metal/lib/python3.11/site-packages/jax/_src/dispatch.py", line 223, in xla_primitive_callable
    compiled = _xla_callable_uncached(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/olege/jax-metal/lib/python3.11/site-packages/jax/_src/dispatch.py", line 253, in _xla_callable_uncached
    return computation.compile().unsafe_call
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/olege/jax-metal/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 2319, in compile
    executable = UnloadedMeshExecutable.from_hlo(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/olege/jax-metal/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 2638, in from_hlo
    xla_executable, compile_options = _cached_compilation(
                                      ^^^^^^^^^^^^^^^^^^^^
  File "/Users/olege/jax-metal/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 2551, in _cached_compilation
    xla_executable = dispatch.compile_or_get_cached(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/olege/jax-metal/lib/python3.11/site-packages/jax/_src/dispatch.py", line 497, in compile_or_get_cached
    return backend_compile(backend, computation, compile_options,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/olege/jax-metal/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/olege/jax-metal/lib/python3.11/site-packages/jax/_src/dispatch.py", line 465, in backend_compile
    return backend.compile(built_c, compile_options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Caught an unknown exception!
```

### What jax/jaxlib version are you using?

jax-metal 0.0.4, jax 0.4.11, jaxlib 0.4.11

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.11.2 from python.org, macOS Ventura 13.6

**Comment by shuhand0** [comment]
@eterevsky, can you provide MacOS version/build,  python version and venv enviroment info like "conda list"?

**Comment by eterevsky** [comment]
Hi @shuhand0,

The machine is Macbook 16 with M1 Pro, OS version: Ventura 13.6

```
Python 3.11.6 (v3.11.6:8b6ee5ba3b, Oct  2 2023, 11:18:21) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
```
 (I had Python 3.11.2 when I submitted the bug, but I decided to reinstall the latest version to double-check.)

I've created a new venv, following the instructions at https://developer.apple.com/metal/jax/:

```
python3 -m venv ~/jax-metal
source ~/jax-metal/bin/activate
python -m pip install -U pip
python -m pip install numpy wheel ml-dtypes==0.2.0
python -c 'import jax; print(jax.numpy.arange(10))'
```

Creation of an array itself doesn't lead to error, for example the following works correctly:

```
a = jnp.array([1, 2, 3], dtype=jnp.float32)
print(a)
```

However any operations lead to the same RuntimeError, like:

```
```

**Comment by eterevsky** [comment]
Oh, I just noticed that for macOS 13 I need jax-metal version 0.0.3, not 0.0.4 that is installed by default by pip. Probably this is the source of the problem.

**Comment by shuhand0** [comment]
Let me know if installing jax-metal 0.0.3 or upgrading to compatible macOS doesn't solve the issue.
