### ISSUE TITLE
Cannot call custom primitive with ordered effect twice in JVP rule

### ISSUE THREAD

**Issue by dionhaefner** [google/jax#18068]
### Description

We are currently migrating mpi4jax from manual XLA tokens to the new ordered effects. The only remaining test failures are related to our JVP rules which call the underlying primitive twice (once on the primal and once on the tangent). Commenting out one of the `.bind` calls in the JVP rule works.

Reproducer:

```python
import functools

from jax.core import Primitive, ShapedArray
from jax.interpreters import ad, xla, mlir

from jax._src.effects import (
    Effect,
    lowerable_effects,
    ordered_effects,
    control_flow_allowed_effects,
    custom_derivatives_allowed_effects,
)

# Register an ordered effect
class EffectType(Effect):
    pass

lowerable_effects.add_type(EffectType)
ordered_effects.add_type(EffectType)
control_flow_allowed_effects.add_type(EffectType)
custom_derivatives_allowed_effects.add_type(EffectType)

ordered_effect = EffectType()

# Define custom Jax primitive
custom_p = Primitive("custom")
custom_impl = functools.partial(xla.apply_primitive, custom_p)


def custom(x):
    return custom_p.bind(x)


def custom_xla_encode_cpu(ctx, x):
    token = ctx.tokens_in.get(ordered_effect)[0]
    ctx.set_tokens_out(mlir.TokenSet({ordered_effect: (token,)}))
    return [x]


def custom_abstract_eval(xs):
    return ShapedArray(xs.shape, xs.dtype), {ordered_effect}


def custom_value_and_jvp(in_args, tan_args):
    (x,) = in_args
    (x_tan,) = tan_args

    val = custom_p.bind(x)
    jvp = custom_p.bind(x_tan)
    return val, jvp


def custom_transpose_rule(x_tan, *x_args):
    res = custom_p.bind(x_tan)
    return (res,)


custom_p.def_impl(custom_impl)
custom_p.def_effectful_abstract_eval(custom_abstract_eval)

ad.primitive_jvps[custom_p] = custom_value_and_jvp
ad.primitive_transposes[custom_p] = custom_transpose_rule

mlir.register_lowering(custom_p, custom_xla_encode_cpu, platform="cpu")


if __name__ == "__main__":
    import jax
    x = jax.numpy.zeros(100)

    def testfun(x):
        return custom(x).sum()
    
    jax.grad(testfun)(x)
```

Error:

```bash
$ python bug.py
Traceback (most recent call last):
  File "/home/dion/codes/mpi4jax/bug.py", line 74, in <module>
    jax.grad(testfun)(x)
  File "/home/dion/codes/mpi4jax/bug.py", line 72, in testfun
    return custom(x).sum()
  File "/home/dion/codes/mpi4jax/bug.py", line 31, in custom
    return custom_p.bind(x)
  File "/home/dion/codes/mpi4jax/bug.py", line 49, in custom_value_and_jvp
    jvp = custom_p.bind(x_tan)
jax._src.source_info_util.JaxStackTraceBeforeTransformation: ValueError: INVALID_ARGUMENT: Execution supplied 1 buffers but compiled program expected 2 buffers

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dion/codes/mpi4jax/bug.py", line 74, in <module>
    jax.grad(testfun)(x)
  File "/home/dion/codes/mpi4jax/bug.py", line 54, in custom_transpose_rule
    res = custom_p.bind(x_tan)
ValueError: INVALID_ARGUMENT: Execution supplied 1 buffers but compiled program expected 2 buffers
```

### What jax/jaxlib version are you using?

0.4.18

### Which accelerator(s) are you using?

CPU

### Additional system info

Linux

**Comment by dionhaefner** [comment]
Funnily enough, it works if I add an (unused) token argument to the primitive:

```python
import os
os.environ["JAX_PLATFORM_NAME"] = "cpu"

import functools

from jax.lax import create_token
from jax.core import Primitive, ShapedArray
from jax.interpreters import ad, xla, mlir

from jax._src.effects import (
    Effect,
    lowerable_effects,
    ordered_effects,
    control_flow_allowed_effects,
    custom_derivatives_allowed_effects,
)

# Register an ordered effect
class EffectType(Effect):
    pass

lowerable_effects.add_type(EffectType)
ordered_effects.add_type(EffectType)
control_flow_allowed_effects.add_type(EffectType)
custom_derivatives_allowed_effects.add_type(EffectType)

ordered_effect = EffectType()

# Define custom Jax primitive
custom_p = Primitive("custom")
custom_impl = functools.partial(xla.apply_primitive, custom_p)


def custom(x):
    token = create_token()  # <- new
    return custom_p.bind(x, token)


def custom_xla_encode_cpu(ctx, x, token):
    del token  # <- throw away input argument
    token = ctx.tokens_in.get(ordered_effect)[0]
    ctx.set_tokens_out(mlir.TokenSet({ordered_effect: (token,)}))
    return [x]


def custom_abstract_eval(xs, token):
    return ShapedArray(xs.shape, xs.dtype), {ordered_effect}


def custom_value_and_jvp(in_args, tan_args):
    (x, token) = in_args
    (x_tan, *_) = tan_args

    val = custom_p.bind(x, token)
    jvp = custom_p.bind(x_tan, token)
    return val, jvp


def custom_transpose_rule(x_tan, *x_args):
    _, token = x_args
    res = custom_p.bind(x_tan, token)
    return (res, ad.Zero.from_value(token))


custom_p.def_impl(custom_impl)
custom_p.def_effectful_abstract_eval(custom_abstract_eval)

ad.primitive_jvps[custom_p] = custom_value_and_jvp
ad.primitive_transposes[custom_p] = custom_transpose_rule

mlir.register_lowering(custom_p, custom_xla_encode_cpu, platform="cpu")


if __name__ == "__main__":
    import jax
    x = jax.numpy.zeros(100)

    def testfun(x):
        return custom(x).sum()
    
    testfun(x)
    jax.grad(testfun)(x)
    print("ok")
```

```bash
$ python foo.py
ok
```

**Comment by kcdodd** [comment]
I would like to second this issue, but I think it happens any time the primitive is called twice, not just for jvp rules.

Taking a look into `apply_primitive` (line ~121 in jax/_src/dispatch.py), the error can also be raised at `return compiled_fun(*args)` by simply calling it twice in a row (with the exact same local `args`). The second call appears to not get some internally prepended token argument that the first one gets, and says there is one less argument than expected. So it seems to be some statefullness to the call wrapper that gets used up, and the wrapper is cached so it can't be called again.

Also looking at the method `xla_primitive_callable` (line ~144 in jax/_src/dispatch.py) that creates the wrapper, there's the branching statement where it either binds the call to `compiled.create_cpp_call_for_apply_primitive` versus `compiled.unsafe_call`. Forcing it to use `compiled.unsafe_call` does *not* cause the same error.

**Comment by mattjj** [comment]
Wow, thanks @selamw1 ! I also ran your repro and verified it works.
