### ISSUE TITLE
Repeatedly building JAX causes string substitution failures

### ISSUE THREAD

**Issue by olupton** [google/jax#18252]
### Description

When developing JAX locally one often wants to repeatedly compile jaxlib etc.
https://github.com/NVIDIA/JAX-Toolbox/blob/c50839183fb69d20ab946cd7312521d796dc2c53/.github/container/build-jax.sh#L272-L273 is a wrapper for triggering this build. Executing it twice in succession yields an error:
```
+ pip --disable-pip-version-check install .
Processing /opt/jax-source
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: ml-dtypes>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from jax==0.4.20.dev20231023+ga4fd1097b) (0.3.1)
Requirement already satisfied: numpy>=1.22 in /usr/local/lib/python3.10/dist-packages (from jax==0.4.20.dev20231023+ga4fd1097b) (1.26.1)
Requirement already satisfied: opt-einsum in /usr/local/lib/python3.10/dist-packages (from jax==0.4.20.dev20231023+ga4fd1097b) (3.3.0)
Requirement already satisfied: scipy>=1.9 in /usr/local/lib/python3.10/dist-packages (from jax==0.4.20.dev20231023+ga4fd1097b) (1.11.3)
Building wheels for collected packages: jax
  Building wheel for jax (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for jax (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
      running bdist_wheel
      running build
      running build_py
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-giv0hxwa/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 434, in build_wheel
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-giv0hxwa/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 419, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-giv0hxwa/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 63, in <module>
        File "/tmp/pip-build-env-giv0hxwa/overlay/local/lib/python3.10/dist-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-giv0hxwa/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-giv0hxwa/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-giv0hxwa/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-giv0hxwa/overlay/local/lib/python3.10/dist-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-giv0hxwa/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-giv0hxwa/overlay/local/lib/python3.10/dist-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/tmp/pip-build-env-giv0hxwa/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-giv0hxwa/overlay/local/lib/python3.10/dist-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-giv0hxwa/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-giv0hxwa/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-giv0hxwa/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-giv0hxwa/overlay/local/lib/python3.10/dist-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-giv0hxwa/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/opt/jax-source/jax/version.py", line 108, in run
          _write_version(os.path.join(self.build_lib, pkg_source_path,
        File "/opt/jax-source/jax/version.py", line 95, in _write_version
          raise RuntimeError(f"Build: could not find {old_version_string!r} in {fname}")
      RuntimeError: Build: could not find '_release_version: str | None = None' in build/lib/jax/version.py
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for jax
Failed to build jax
ERROR: Could not build wheels for jax, which is required to install pyproject.toml-based projects
```
which can be avoided by running
```
cp ./jax-source/jax/version.py ./jax-source/build/lib/jax/version.py
```
before every build. These two files differ:
```diff
27c27
< _release_version: str | None = None
---
> _release_version: str = '0.4.20.dev20231023+ga4fd1097b'
89c89
<   old_version_string = "_release_version: str | None = None"
---
>   old_version_string = "_release_version: str = '0.4.20.dev20231023+ga4fd1097b'"
```
it's annoying to have to do this every time. It seems reasonable to expect that rebuilding jax with no changes should be a ~noop, not something that triggers an error, but perhaps this `build-jax.sh` script is doing something that it shouldn't?

### What jax/jaxlib version are you using?

development branch (commit a4fd1097b64448d37ddcb7bb2a2f4a488322bdf4)

### Which accelerator(s) are you using?

GPU (but N/A)

### Additional system info

Python 3.10, Linux

**Comment by jakevdp** [comment]
This tells me that you’re build process is finding the JAX sources in the output of the previous build, rather than from the actual source. This seems problematic for many reasons, and so the error is arguably a good thing! I’d recommend deleting the previous build before making a new one, or otherwise ensuring that you’re building from source rather than from the previous build artifact.

**Comment by hawkinsp** [comment]
Note the repro here is, from the JAX source tree:
```
pip install .
pip install .
```

I would have expected that to work?

**Comment by jakevdp** [comment]
Yeah, indeed – do you know the mechanism by which the new build process reads from the old build output? Is that intended behavior by `pip`?

**Comment by hawkinsp** [comment]
It seems like we just leave some files under`build/` (which is coincidentally our directory containing other things, sigh), which if you delete them the problem goes away. I'm not sure why `pip` doesn't remove the previous state when doing this.

**Comment by i-chaochen** [comment]
maybe we can add a if check on `build.py` to check and remove `build/bdist.linux-x86_64` `build/lib/` and `build/__pycache__/` ?

**Comment by jakevdp** [comment]
The thing that's more concerning to me here is that when you run `pip install .`, the contents of the `build/` directory are used instead of the actual source you're trying to install. That seems like a bug in `pip`, and I'd like to understand it rather than work around it. The error you're seeing here is reflecting a real build issue: the package is being built from the wrong set of files!

**Comment by olupton** [comment]
OK, I'll investigate further before doing anything else with https://github.com/NVIDIA/JAX-Toolbox/pull/396.

**Comment by olupton** [comment]
> The thing that's more concerning to me here is that when you run pip install ., the contents of the build/ directory are used instead of the actual source you're trying to install.

Can you clarify what you meant by this? As far as I can see, the code that's being **executed** is from the source directory. i.e. in the traceback in the issue, I see `/opt/jax-source/jax/version.py` (without a `build/`).

It seems that by default the `build_py` step only copies files if the source is newer than the destination (or if the destination doesn't exist). In our case, the build scripts modify the destination copy `build/version.py` and leave the source copy `version.py` alone, so the destination is newer and subsequent installs do not update it. This doesn't seem unreasonable. The error then follows because the build scripts only know how to modify an unmodified copy, they cannot update an already-modified `version.py`.

In light of all of this, I think the workaround of https://github.com/NVIDIA/JAX-Toolbox/pull/396 is valid.

As for an actual fix, the least-magic solution would probably be to not modify files in the pip build directory...
Maybe a more pragmatic / less invasive suggestion is to explicitly remove the build tree copy during the build if it exists, i.e. something like
```diff
--- a/jax/version.py
+++ b/jax/version.py
@@ -103,10 +103,13 @@ def _get_cmdclass(pkg_source_path):

   class _build_py(build_py_orig):
     def run(self):
+      _version_py_in_build = os.path.join(self.build_lib, pkg_source_path,
+                                          os.path.basename(__file__))
+      if os.path.isfile(_version_py_in_build):
+          os.unlink(_version_py_in_build)
       super().run()
       if _release_version is None:
-        _write_version(os.path.join(self.build_lib, pkg_source_path,
-                                    os.path.basename(__file__)))
+        _write_version(_version_py_in_build)

   class _sdist(sdist_orig):
     def make_release_tree(self, base_dir, files):
```

This seems preferable to "fixing" the modification logic to cope with already-modified files.

Thoughts, @jakevdp?

**Comment by jakevdp** [comment]
> It seems that by default the build_py step only copies files if the source is newer than the destination

I see – that would explain the issue.

> As for an actual fix, the least-magic solution would probably be to not modify files that are notionally copies from the source directory in the pip build directory...

Sure - if you have a suggestion for how to embed build-time version strings in the package distributions without doing this, I'd be happy to hear it! For what it's worth, the approach we use here (overriding `build_py` to overwrite the version file) is similar to the one used by standard tools like [versioneer](https://github.com/python-versioneer/python-versioneer), though the details differ.

Regarding the proposed fix – this looks reasonable to me, assuming the file is copied from the source directory to the build directory during `super().run()`. Would you like to put together a PR?

**Comment by olupton** [comment]
I opened https://github.com/google/jax/pull/18746 with essentially the workaround above, please take a look @jakevdp :)
