### ISSUE TITLE
Inconsistent behaviour of jited and non jited array assignment function on some `PositionalSharding` topologies.

### ISSUE THREAD

**Issue by Laurence-Cullen** [google/jax#18434]
### Description

We are trying to implement `PositionalSharding` in a minimal case where we are are shifting values in an array and assigning new ones. We have observed that when jiting this `assign` function the outputs are different and incorrect when `array` has a `(8,1)` or `(2, 4)` shard topology. The sharding does not effect the unjited function.

From inspection of the jited outputs on the topologies that fail, we have noticed the values from the right hand side of the initial  array end up at index `7` i.e. `jitted_assign(array, value)[7] == array[-1]`. The correct behaviour is `assign(array, value)[7] == array[8]`.

```python
import os

# Make 8 CPU devices
os.environ["XLA_FLAGS"] = '--xla_force_host_platform_device_count=8'

import jax.numpy as jnp
import jax.random
from jax.experimental import mesh_utils
from jax.sharding import PositionalSharding


def assign(array, value):
    """Shift the array to the left by one and set the rightmost column to value."""
    shifted = array.at[:-1, :].set(array[1:, :])
    return shifted.at[-1, :].set(jnp.ones(array.shape[1]) * value)


def main():
    value = 1.456
    N = 16
    array = jax.random.uniform(jax.random.PRNGKey(1241), (N, N))

    devices = mesh_utils.create_device_mesh((8,))
    sharding = PositionalSharding(devices)

    jitted_assign = jax.jit(assign)

    # This works
    array = jax.device_put(array, sharding.reshape(1, 8))
    assert jnp.allclose(assign(array, value), jitted_assign(array, value))

    # Correctly shifted output
    assert jnp.allclose(assign(array, value)[7], array[8])

    array = jax.device_put(array, sharding.reshape(8, 1))

    # This should not pass
    assert jnp.allclose(jitted_assign(array, value)[7], array[-1])

    # This fails
    assert jnp.allclose(assign(array, value), jitted_assign(array, value))

    # This fails
    array = jax.device_put(array, sharding.reshape(2, 4))
    assert jnp.allclose(assign(array, value), jitted_assign(array, value))


if __name__ == '__main__':
    main()
```

Any help to explain what is going on would be very appreciated, whether this is a bug or me just not understanding how sharding is expected to work.

### What jax/jaxlib version are you using?

jax==0.4.16 jaxlib==0.4.16

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.11.5, Ubuntu 22.04.3 LTS

**Comment by yashk2810** [comment]
Can you try on the latest jax and jaxlib version?

**Comment by Laurence-Cullen** [comment]
I get the same result after upgrading to:
```
jax==0.4.20
jaxlib==0.4.20
```

Stack trace:
```
Traceback (most recent call last):
  File "/home/laurence/2d-navier-stokes/solver/sharding_error.py", line 49, in <module>
    main()
  File "/home/laurence/2d-navier-stokes/solver/sharding_error.py", line 41, in main
    assert jnp.allclose(assign(array, value), jitted_assign(array, value))
AssertionError
```

**Comment by Laurence-Cullen** [comment]
Any ideas @yashk2810 ? Is there someway I can shard without having to use anything experimental, if there is a stability issue there?
