### ISSUE TITLE
operation gpusolverDnCreate(&handle) failed: cuSolver has not been initialized

### ISSUE THREAD

**Issue by carlosgmartin** [google/jax#18471]
### Description

After installing jax as follows:
```
python3 -m pip install --upgrade "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```

I get the following error:
```
$ python3 -c "from jax import numpy as jnp; jnp.linalg.qr(jnp.zeros([2, 2]))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/marvel/home/cgmartin/mambaforge/lib/python3.10/site-packages/jax/_src/numpy/linalg.py", line 598, in qr
    q, r = lax_linalg.qr(a, full_matrices=full_matrices)
jax._src.source_info_util.JaxStackTraceBeforeTransformation: RuntimeError: jaxlib/gpu/solver_kernels.cc:45: operation gpusolverDnCreate(&handle) failed: cuSolver has not been initialized

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/marvel/home/cgmartin/mambaforge/lib/python3.10/site-packages/jaxlib/gpu_solver.py", line 127, in _geqrf_hlo
    lwork, opaque = gpu_solver.build_geqrf_descriptor(
RuntimeError: jaxlib/gpu/solver_kernels.cc:45: operation gpusolverDnCreate(&handle) failed: cuSolver has not been initialized
```

### What jax/jaxlib version are you using?

jax 0.4.20, jaxlib 0.4.20

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.10.10, CentOS Linux 7 (Core)

### NVIDIA GPU info

```
Thu Nov  9 17:28:05 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.182.03   Driver Version: 470.182.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  On   | 00000000:07:00.0 Off |                    0 |
| N/A   26C    P0    53W / 400W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM...  On   | 00000000:0F:00.0 Off |                    0 |
| N/A   26C    P0    55W / 400W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A100-SXM...  On   | 00000000:47:00.0 Off |                    0 |
| N/A   26C    P0    54W / 400W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA A100-SXM...  On   | 00000000:4E:00.0 Off |                    0 |
| N/A   27C    P0    57W / 400W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by hawkinsp** [comment]
That return code from `cusolverDnCreate` means "cusolver initialization failed".

My best guess: is it possible you have multiple copies of cusolver installed and JAX is finding the wrong one? Is there another copy in `/usr/local/cuda` perhaps?

**Comment by carlosgmartin** [comment]
@hawkinsp Here are the file contents around that path. Let me what other commands you'd like me to run for diagnosis.

```
$ ls /usr/local
bin   cuda-11	 cuda-11.4  etc    include  lib64    sbin   src
cuda  cuda-11.0  dcgm	    games  lib	    libexec  share
$ ls /usr/local/cuda
bin				gds	 nsightee_plugins  src
compute-sanitizer		include  nvml		   targets
CUDA_Toolkit_Release_Notes.txt	lib64	 nvvm		   tools
DOCS				libnvvp  README		   version.json
EULA.txt			LICENSE  samples
extras				man	 share
$ ls /usr/local/cuda/targets
x86_64-linux
$ ls /usr/local/cuda/targets/x86_64-linux
include  lib
$ ls /usr/local/cuda/targets/x86_64-linux/lib
libaccinj64.so		      libnppial.so.11.4.0.110
libaccinj64.so.11.4	      libnppial_static.a
libaccinj64.so.11.4.120       libnppicc.so
libcublasLt.so		      libnppicc.so.11
libcublasLt.so.11	      libnppicc.so.11.4.0.110
libcublasLt.so.11.6.5.2       libnppicc_static.a
libcublasLt_static.a	      libnppidei.so
libcublas.so		      libnppidei.so.11
libcublas.so.11		      libnppidei.so.11.4.0.110
libcublas.so.11.6.5.2	      libnppidei_static.a
libcublas_static.a	      libnppif.so
libcudadevrt.a		      libnppif.so.11
libcudart.so		      libnppif.so.11.4.0.110
libcudart.so.11.0	      libnppif_static.a
libcudart.so.11.4.148	      libnppig.so
libcudart_static.a	      libnppig.so.11
libcufft.so		      libnppig.so.11.4.0.110
libcufft.so.10		      libnppig_static.a
libcufft.so.10.5.2.100	      libnppim.so
libcufft_static.a	      libnppim.so.11
libcufft_static_nocallback.a  libnppim.so.11.4.0.110
libcufftw.so		      libnppim_static.a
libcufftw.so.10		      libnppist.so
libcufftw.so.10.5.2.100       libnppist.so.11
libcufftw_static.a	      libnppist.so.11.4.0.110
libcufile_rdma.so	      libnppist_static.a
libcufile_rdma.so.1	      libnppisu.so
libcufile_rdma.so.1.0.2       libnppisu.so.11
libcufile_rdma_static.a       libnppisu.so.11.4.0.110
libcufile.so		      libnppisu_static.a
libcufile.so.0		      libnppitc.so
libcufile.so.1.0.2	      libnppitc.so.11
libcufile_static.a	      libnppitc.so.11.4.0.110
libcufilt.a		      libnppitc_static.a
libcuinj64.so		      libnpps.so
libcuinj64.so.11.4	      libnpps.so.11
libcuinj64.so.11.4.120	      libnpps.so.11.4.0.110
libculibos.a		      libnpps_static.a
libcupti.so		      libnvblas.so
libcupti.so.11.4	      libnvblas.so.11
libcupti.so.2021.2.2	      libnvblas.so.11.6.5.2
libcupti_static.a	      libnvjpeg.so
libcurand.so		      libnvjpeg.so.11
libcurand.so.10		      libnvjpeg.so.11.5.2.120
libcurand.so.10.2.5.120       libnvjpeg_static.a
libcurand_static.a	      libnvperf_host.so
libcusolverMg.so	      libnvperf_host_static.a
libcusolverMg.so.11	      libnvperf_target.so
libcusolverMg.so.11.2.0.120   libnvptxcompiler_static.a
libcusolver.so		      libnvrtc-builtins.so
libcusolver.so.11	      libnvrtc-builtins.so.11.4
libcusolver.so.11.2.0.120     libnvrtc-builtins.so.11.4.152
libcusolver_static.a	      libnvrtc.so
libcusparse.so		      libnvrtc.so.11.2
libcusparse.so.11	      libnvrtc.so.11.4.152
libcusparse.so.11.6.0.120     libnvToolsExt.so
libcusparse_static.a	      libnvToolsExt.so.1
liblapack_static.a	      libnvToolsExt.so.1.0.0
libmetis_static.a	      libOpenCL.so
libnppc.so		      libOpenCL.so.1
libnppc.so.11		      libOpenCL.so.1.0
libnppc.so.11.4.0.110	      libOpenCL.so.1.0.0
libnppc_static.a	      libpcsamplingutil.so
libnppial.so		      stubs
libnppial.so.11
```

**Comment by Micky774** [comment]
@carlosgmartin can you try updating your CUDA version to `>=11.8` and see if the issue persists? Currently it looks like it is using `cusolver` from the `/usr/local/cuda-11.4` install, and that may be causing the conflict. I wonder if this is another instance where we ought to try and prefer pip-installed CUDA tools if possible

**Comment by carlosgmartin** [comment]
@Micky774 
```sh
$ python3 -m pip list | grep nvidia
nvidia-cublas-cu11           11.11.3.6
nvidia-cublas-cu12           12.1.3.1
nvidia-cuda-cupti-cu11       11.8.87
nvidia-cuda-nvcc-cu11        11.8.89
nvidia-cuda-nvcc-cu12        12.1.105
nvidia-cuda-runtime-cu11     11.8.89
nvidia-cuda-runtime-cu12     12.1.105
nvidia-cudnn-cu11            8.9.0.131
nvidia-cudnn-cu12            8.9.0.131
nvidia-cufft-cu11            10.9.0.58
nvidia-cufft-cu12            11.0.2.54
nvidia-cusolver-cu11         11.4.1.48
nvidia-cusolver-cu12         11.4.5.107
nvidia-cusparse-cu11         11.7.5.86
nvidia-cusparse-cu12         12.1.0.106
nvidia-nccl-cu11             2.19.3
nvidia-nvjitlink-cu12        12.1.105
```

**Comment by hawkinsp** [comment]
One possible problem is you have both `cu11` and `cu12` packages installed. These cannot coexist! They will stomp over each other's files.

Can you try in a fresh virtualenv?

**Comment by carlosgmartin** [comment]
@hawkinsp What's the recommended way to pip uninstall one of the two `cu` versions?

**Comment by hawkinsp** [comment]
@carlosgmartin I'd recommend a fresh virtualenv, but if you want to try removing manually, I'd remove *all* of the packages listed above and then reinstall `jax[cuda11_pip]` (or cuda 12, if you prefer, but only one). LMK if that works!

**Comment by carlosgmartin** [comment]
@hawkinsp Looks like the error stopped occurring.

**Comment by hawkinsp** [comment]
Great! Closing.

**Comment by Leminsanche** [comment]
> @carlosgmartin I'd recommend a fresh virtualenv, but if you want to try removing manually, I'd remove _all_ of the packages listed above and then reinstall `jax[cuda11_pip]` (or cuda 12, if you prefer, but only one). LMK if that works!

how can i remove all packages  ??
