### ISSUE TITLE
XlaRuntimeError when using Pallas flash attention with bfloat16 activations on TPU

### ISSUE THREAD

**Issue by rbflx** [google/jax#18595]
### Description

Running:

```python
import jax
from jax import numpy as jnp
from jax.experimental.pallas.ops.tpu import flash_attention

bs = 2
seqlen = 1024
n_heads = 32
dim = 128
rng = jax.random.PRNGKey(0)
xq = jax.random.normal(rng, (bs, n_heads, seqlen, dim), dtype=jnp.bfloat16)
xk = jax.random.normal(rng, (bs, n_heads, seqlen, dim), dtype=jnp.bfloat16)
xv = jax.random.normal(rng, (bs, n_heads, seqlen, dim), dtype=jnp.bfloat16)

res = flash_attention.flash_attention(xq, xk, xv)

print(res.shape)
print(res.dtype)
```

on TPU v3-8 results in the following error:
```python
XlaRuntimeError: INVALID_ARGUMENT: Failed to compile a Mosaic module: 'tpu.matmul' op Unsupported input data type in matrix multiplication. (extra diagnostics trimmed...)
```

### What jax/jaxlib version are you using?

jax 0.4.20, jaxlib 0.4.20

### Which accelerator(s) are you using?

TPU v3-8

### Additional system info

Python 3.10.12, uname: Linux t1v-n-0ddffd80-w-0 5.19.0-1022-gcp #24~22.04.1-Ubuntu SMP Sun Apr 23 09:51:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### NVIDIA GPU info

None

**Comment by mattjj** [comment]
I think perhaps https://github.com/google/jax/commit/9b1572c02859287294dec7a6b3df9018f462c8aa fixed this, but maybe that hasn't been pushed to pypi yet. Can you try using JAX at GitHub HEAD?

**Comment by mattjj** [comment]
That is, either do a `git clone https://github.com/google/jax.git && pip install -e jax` or do a `pip install git+https://github.com/google/jax.git`

**Comment by sharadmv** [comment]
I think this is actually an unimplemented feature for TPU v3, whereas it should work out of the box on v4. Cc: @apaszke to confirm

**Comment by rbflx** [comment]
> That is, either do a `git clone https://github.com/google/jax.git && pip install -e jax` or do a `pip install git+https://github.com/google/jax.git`

Installing JAX from HEAD (0.4.21.dev20231119+g52b31a497) and using nightly releases of jaxlib (0.4.21.dev20231118) & libtpu-nightly (0.1.dev20231118) results in the following error:

```python
Traceback (most recent call last):
  File "/home/user/work/tests/flashattn.py", line 17, in <module>
    res = flash_attention.flash_attention(xq, xk, xv)
  File "/home/user/jax_dev_env/lib/python3.10/site-packages/jax/experimental/pallas/ops/tpu/flash_attention.py", line 181, in flash_attention
    return _flash_attention(
  File "/home/user/jax_dev_env/lib/python3.10/site-packages/jax/experimental/pallas/ops/tpu/flash_attention.py", line 199, in _flash_attention
    return _flash_attention_impl(
  File "/home/user/jax_dev_env/lib/python3.10/site-packages/jax/experimental/pallas/ops/tpu/flash_attention.py", line 729, in _flash_attention_impl
    o, *aux = pl.pallas_call(
  File "/home/user/jax_dev_env/lib/python3.10/site-packages/jax/_src/pallas/pallas_call.py", line 410, in wrapped
    out_flat = pallas_call_p.bind(
jax._src.source_info_util.JaxStackTraceBeforeTransformation: KeyError: 'xla_mosaic_dump_to'

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/work/tests/flashattn.py", line 17, in <module>
    res = flash_attention.flash_attention(xq, xk, xv)
  File "/home/user/jax_dev_env/lib/python3.10/site-packages/jax/_src/pallas/mosaic/pallas_call_registration.py", line 88, in pallas_call_tpu_lowering_rule
    return mlir.lower_fun(_lower_fun, multiple_results=True)(
  File "/home/user/jax_dev_env/lib/python3.10/site-packages/jax/_src/pallas/mosaic/pallas_call_registration.py", line 79, in _lower_fun
    return mosaic.as_tpu_kernel(
  File "/home/user/jax_dev_env/lib/python3.10/site-packages/jax/_src/tpu_custom_call.py", line 404, in as_tpu_kernel
    lowered_module_asm, constants = _lower_tpu_kernel(
  File "/home/user/jax_dev_env/lib/python3.10/site-packages/jax/_src/tpu_custom_call.py", line 300, in _lower_tpu_kernel
    dump_mlir(module, "original")
  File "/home/user/jax_dev_env/lib/python3.10/site-packages/jax/_src/tpu_custom_call.py", line 476, in dump_mlir
    if FLAGS["xla_mosaic_dump_to"].value == "sponge":
  File "/home/user/jax_dev_env/lib/python3.10/site-packages/absl/flags/_flagvalues.py", line 481, in __getitem__
    return self._flags()[name]
KeyError: 'xla_mosaic_dump_to'
```


Also, adding `interpret=True` to all `pallas_call` calls in `flash_attention.py` (as was done in this issue: https://github.com/google/jax/issues/18590) results in the code executing without errors.

**Comment by purpledog** [comment]
Hitting the same issue, would be nice to be able to use older TPUs.

**Comment by Mddct** [comment]
can flash-att. work on gpu?
