### ISSUE TITLE
Pallas implementation of attention doesn't work on CloudTPU

### ISSUE THREAD

**Issue by qihqi** [google/jax#18590]
### Description

```python
import jax
import jax.numpy as jnp
from jax.experimental.pallas.ops import attention

bs = 2
seqlen = 1000
n_heads = 32
dim = 128
rng = jax.random.PRNGKey(0)
xq = jax.random.normal(rng, (bs, seqlen, n_heads, dim))
xk = jax.random.normal(rng, (bs, seqlen, n_heads, dim))
xv = jax.random.normal(rng, (bs, seqlen, n_heads, dim))

print('reference')
res = attention.mha_reference(xq, xk, xv, None)
print(res)
print(res.shape)

print('real kernel')
print(attention.mha(xq, xk, xv, None))
```

Got:

```
hanq@t1v-n-cfe84bb3-w-0:~/llama$ python test_jax.py
reference

   ...
   [-0.68359375 -1.9609375  -1.2734375  ...  0.02490234  0.703125
     0.69921875]
   [-0.4453125  -0.5859375   1.28125    ... -0.24414062  1.21875
     0.47851562]
   [ 0.0859375  -1.703125   -0.4921875  ... -0.38476562  0.8828125
     0.09765625]]

  [[ 0.93359375 -0.6015625   1.4296875  ...  1.3515625   0.6796875
    -1.0859375 ]
   [ 0.875       0.22460938  1.0625     ...  1.421875   -0.09472656
    -0.18847656]
   [ 1.34375     0.02441406 -1.34375    ... -0.01501465 -0.90234375
    -0.31054688]
   ...
   [ 0.4609375   0.609375   -0.9921875  ... -1.015625    0.6796875
    -0.5546875 ]
   [-1.25       -0.59765625  0.1328125  ...  0.0390625   0.43945312
    -0.97265625]
   [ 1.140625   -0.17382812 -1.03125    ... -0.76171875  0.77734375
    -0.18261719]]

  ...

   [ 0.734375   -1.3203125   0.92578125 ...  0.9453125   0.18554688
     1.0078125 ]
   [ 0.96875    -1.5390625   0.47265625 ...  0.96875    -1.1640625
     0.29882812]
   ...
   [ 0.04296875  0.53515625  0.20410156 ...  1.28125    -0.69140625
    -0.10058594]
   [-0.04150391 -0.66796875 -1.078125   ... -1.09375    -0.4296875
     0.828125  ]
   [-0.5234375   0.43164062 -0.69140625 ...  1.1796875  -2.296875
     0.21972656]]

  ...

  [[ 0.06445312  0.40429688  0.03735352 ... -1.6796875   1.1796875
    -0.98828125]
   [-0.7109375  -0.34375    -0.23144531 ...  0.13085938 -0.47070312
    -0.21875   ]
   [-0.66796875 -0.02954102 -1.046875   ...  0.2421875   1.203125
    -0.42382812]
   ...
   [ 0.14257812  0.58984375  0.40234375 ... -0.01672363 -0.57421875
     1.046875  ]
   [-0.62890625 -1.1171875   0.84375    ... -0.35351562 -0.22558594
   ...
   [ 0.859375    1.9765625   0.54296875 ...  1.109375    0.05639648
     0.6796875 ]
   [-0.29101562 -1.9921875  -1.734375   ...  1.2265625   0.14453125
    -0.53125   ]
   [ 1.6484375  -0.40820312 -0.828125   ... -0.265625   -0.28320312
    -0.43164062]]

  [[-0.27539062 -1.8671875  -0.078125   ...  0.515625    0.90625
    -2.453125  ]
   [ 0.17773438 -0.11572266  0.5390625  ... -0.5546875  -0.40625
     0.9765625 ]
   [-0.05395508 -0.00325012 -0.08691406 ... -0.8046875  -0.03979492
     0.07666016]
   ...
   [-0.3359375   0.87890625 -1.453125   ...  1.1328125   0.46875
     0.65625   ]
   [ 0.30273438  0.546875    0.11083984 ...  0.98828125 -0.10791016
     1.4375    ]
   [ 1.4375     -0.46484375  1.71875    ...  1.265625    0.21386719
    -0.70703125]]]]
(2, 1000, 32, 128)
real kernel
Traceback (most recent call last):
  File "/home/hanq/llama/test_jax.py", line 20, in <module>
    print(attention.mha(xq, xk, xv, None))
  File "/home/hanq/.local/lib/python3.10/site-packages/jax/experimental/pallas/ops/attention.py", line 216, in mha
    return pl.pallas_call(
  File "/home/hanq/.local/lib/python3.10/site-packages/jax/_src/pallas/pallas_call.py", line 410, in wrapped
    out_flat = pallas_call_p.bind(
jax._src.source_info_util.JaxStackTraceBeforeTransformation: RuntimeError: Internal TPU kernel compiler error: Loading elements out of bounds

The MLIR operation involved:
  %209 = "vector.load"(%14, %9, %0, %9, %9) : (memref<1x1000x1x128xf32, #tpu.memory_space<vmem>>, index, index, index, index) -> vector<1x128x1x128xf32>

Please report a bug at: https://github.com/google/jax/issues/new?assignees=apaszke

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hanq/llama/test_jax.py", line 20, in <module>
    print(attention.mha(xq, xk, xv, None))

--------------------

The above exception was the direct cause of the following exception:

jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hanq/llama/test_jax.py", line 20, in <module>
    print(attention.mha(xq, xk, xv, None))
  File "/home/hanq/.local/lib/python3.10/site-packages/jax/_src/pallas/mosaic/pallas_call_registration.py", line 88, in pallas_call_tpu_lowering_rule
    return mlir.lower_fun(_lower_fun, multiple_results=True)(
  File "/home/hanq/.local/lib/python3.10/site-packages/jax/_src/pallas/mosaic/pallas_call_registration.py", line 79, in _lower_fun
    return mosaic.as_tpu_kernel(
  File "/home/hanq/.local/lib/python3.10/site-packages/jax/_src/tpu_custom_call.py", line 408, in as_tpu_kernel
    lowered_module_asm, constants = _lower_tpu_kernel(
  File "/home/hanq/.local/lib/python3.10/site-packages/jax/_src/tpu_custom_call.py", line 335, in _lower_tpu_kernel
    _run_pass_pipeline(pipeline, module, "infer vector layout")
  File "/home/hanq/.local/lib/python3.10/site-packages/jax/_src/tpu_custom_call.py", line 264, in _run_pass_pipeline
    raise RuntimeError("\n".join(msg)) from None
RuntimeError: Internal TPU kernel compiler error: Loading elements out of bounds

The MLIR operation involved:
  %209 = "vector.load"(%14, %9, %0, %9, %9) : (memref<1x1000x1x128xf32, #tpu.memory_space<vmem>>, index, index, index, index) -> vector<1x128x1x128xf32>

Please report a bug at: https://github.com/google/jax/issues/new?assignees=apaszke
```

### What jax/jaxlib version are you using?

jax==0.4.21.dev20231117 jaxlib==0.4.21.dev20231117

### Which accelerator(s) are you using?

TPU

### Additional system info

Python 3.10.2 Uname=Linux t1v-n-cfe84bb3-w-0 5.19.0-1022-gcp #24~22.04.1-Ubuntu SMP Sun Apr 23 09:51:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by sharadmv** [comment]
Can you try the version in jax/experimental/ops/tpu/flash_attention.py?

**Comment by qihqi** [comment]
Sure, updated test script to 

```python
hanq@t1v-n-cfe84bb3-w-0:~/llama$ cat test_jax.py
import jax
import jax.numpy as jnp
from jax.experimental.pallas.ops import attention
from jax.experimental.pallas.ops.tpu import flash_attention

bs = 2
seqlen = 1000
n_heads = 128
dim = 512
rng = jax.random.PRNGKey(0)
xq = jax.random.normal(rng, (bs, seqlen, n_heads, dim))
xk = jax.random.normal(rng, (bs, seqlen, n_heads, dim))
xv = jax.random.normal(rng, (bs, seqlen, n_heads, dim))

print('reference')
res = flash_attention.mha_reference(xq, xk, xv, None)
#print(res)
print(res.shape)

print('real kernel')
print(flash_attention.flash_attention(xq, xk, xv, None, debug=True))
```


Got
```
hanq@t1v-n-cfe84bb3-w-0:~/llama$ python test_jax.py
reference
(2, 1000, 128, 512)
real kernel

    e:f32[128,512] <- a[0,0,:,:]
    f:f32[128,512] <- b[0,0,:,:]
    g:f32[128,128] = dot_general[
      dimension_numbers=(([1], [1]), ([], []))
      preferred_element_type=float32
    ] e f
    h:f32[128] = reduce_max[axes=(1,)] g
    i:f32[128,1] = broadcast_in_dim[broadcast_dimensions=(0,) shape=(128, 1)] h
    j:f32[128,128] = sub g i
    k:f32[128,128] = exp j
    l:f32[128] = reduce_sum[axes=(1,)] k
    m:f32[128,1] = broadcast_in_dim[broadcast_dimensions=(0,) shape=(128, 1)] l
    n:f32[128,128] = div k m
    o:f32[128,512] <- c[0,0,:,:]
    p:f32[128,512] = dot_general[
      dimension_numbers=(([1], [0]), ([], []))
      preferred_element_type=float32
    ] n o
    d[0,0,:,:] <- p
  in () }
module {
  func.func @main(%arg0: i32, %arg1: i32, %arg2: i32, %arg3: i32, %arg4: memref<1x1x128x512xf32, #tpu.memory_space<vmem>>, %arg5: memref<1x1x128x512xf32, #tpu.memory_space<vmem>>, %arg6: memref<1x1x128x512xf32, #tpu.memory_space<vmem>>, %arg7: memref<1x1x128x512xf32, #tpu.memory_space<vmem>>) attributes {dimension_semantics = [#tpu.dimension_semantics<parallel>, #tpu.dimension_semantics<parallel>, #tpu.dimension_semantics<parallel>, #tpu.dimension_semantics<arbitrary>], iteration_bounds = array<i64: 2, 1000, 1, 1>, scalar_prefetch = 0 : i64, scratch_operands = 0 : i64, window_params = [{transform_indices = @transform_0, window_bounds = array<i64: 1, 1, 128, 512>}, {transform_indices = @transform_1, window_bounds = array<i64: 1, 1, 128, 512>}, {transform_indices = @transform_2, window_bounds = array<i64: 1, 1, 128, 512>}, {transform_indices = @transform_3, window_bounds = array<i64: 1, 1, 128, 512>}]} {
    %c0 = arith.constant 0 : index
    %c0_0 = arith.constant 0 : index
    %c0_1 = arith.constant 0 : index
    %c0_2 = arith.constant 0 : index
    %0 = vector.load %arg4[%c0, %c0_0, %c0_1, %c0_2] : memref<1x1x128x512xf32, #tpu.memory_space<vmem>>, vector<1x1x128x512xf32>
    %1 = vector.shape_cast %0 : vector<1x1x128x512xf32> to vector<128x512xf32>
    %c0_3 = arith.constant 0 : index
    %c0_4 = arith.constant 0 : index
    %c0_5 = arith.constant 0 : index
    %c0_6 = arith.constant 0 : index
    %2 = vector.load %arg5[%c0_3, %c0_4, %c0_5, %c0_6] : memref<1x1x128x512xf32, #tpu.memory_space<vmem>>, vector<1x1x128x512xf32>
    %3 = vector.shape_cast %2 : vector<1x1x128x512xf32> to vector<128x512xf32>
    %cst = arith.constant dense<0.000000e+00> : vector<128x128xf32>
    %4 = tpu.matmul %1, %3, %cst {transpose_rhs = true} : vector<128x512xf32>, vector<128x512xf32>, vector<128x128xf32> -> vector<128x128xf32>
    %cst_7 = arith.constant dense<0xFF800000> : vector<128xf32>
    %5 = vector.multi_reduction <maxf>, %4, %cst_7 [1] : vector<128x128xf32> to vector<128xf32>
    %6 = vector.shape_cast %5 : vector<128xf32> to vector<128x1xf32>
    %15 = vector.shape_cast %14 : vector<1x1x128x512xf32> to vector<128x512xf32>
    %cst_13 = arith.constant dense<0.000000e+00> : vector<128x512xf32>
    %16 = tpu.matmul %13, %15, %cst_13 : vector<128x128xf32>, vector<128x512xf32>, vector<128x512xf32> -> vector<128x512xf32>
    %c0_14 = arith.constant 0 : index
    %c0_15 = arith.constant 0 : index
    %c0_16 = arith.constant 0 : index
    %c0_17 = arith.constant 0 : index
    %17 = vector.load %arg7[%c0_14, %c0_15, %c0_16, %c0_17] : memref<1x1x128x512xf32, #tpu.memory_space<vmem>>, vector<1x1x128x512xf32>
    %18 = vector.shape_cast %17 : vector<1x1x128x512xf32> to vector<128x512xf32>
    %19 = vector.shape_cast %16 : vector<128x512xf32> to vector<1x1x128x512xf32>
    vector.store %19, %arg7[%c0_14, %c0_15, %c0_16, %c0_17] : memref<1x1x128x512xf32, #tpu.memory_space<vmem>>, vector<1x1x128x512xf32>
    return
  }
  func.func @transform_0(%arg0: i32, %arg1: i32, %arg2: i32, %arg3: i32) -> (i32, i32, i32, i32) {
    %c0_i32 = arith.constant 0 : i32
    return %arg0, %arg1, %arg2, %c0_i32 : i32, i32, i32, i32
  }
  func.func @transform_1(%arg0: i32, %arg1: i32, %arg2: i32, %arg3: i32) -> (i32, i32, i32, i32) {
    %c0_i32 = arith.constant 0 : i32
    return %arg0, %arg1, %arg3, %c0_i32 : i32, i32, i32, i32
  }
  func.func @transform_2(%arg0: i32, %arg1: i32, %arg2: i32, %arg3: i32) -> (i32, i32, i32, i32) {
    %c0_i32 = arith.constant 0 : i32
    return %arg0, %arg1, %arg3, %c0_i32 : i32, i32, i32, i32
  }
  func.func @transform_3(%arg0: i32, %arg1: i32, %arg2: i32, %arg3: i32) -> (i32, i32, i32, i32) {
    %c0_i32 = arith.constant 0 : i32
    return %arg0, %arg1, %arg2, %c0_i32 : i32, i32, i32, i32
  }
}

Traceback (most recent call last):
  File "/home/hanq/llama/test_jax.py", line 21, in <module>
    print(flash_attention.flash_attention(xq, xk, xv, None, debug=True))
  File "/home/hanq/.local/lib/python3.10/site-packages/jax/experimental/pallas/ops/tpu/flash_attention.py", line 181, in flash_attention
    return _flash_attention(
  File "/home/hanq/.local/lib/python3.10/site-packages/jax/experimental/pallas/ops/tpu/flash_attention.py", line 199, in _flash_attention
    return _flash_attention_impl(
  File "/home/hanq/.local/lib/python3.10/site-packages/jax/experimental/pallas/ops/tpu/flash_attention.py", line 729, in _flash_attention_impl
    o, *aux = pl.pallas_call(
  File "/home/hanq/.local/lib/python3.10/site-packages/jax/_src/pallas/pallas_call.py", line 410, in wrapped
    out_flat = pallas_call_p.bind(
jax._src.source_info_util.JaxStackTraceBeforeTransformation: RuntimeError: Expected a tiled memref

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hanq/llama/test_jax.py", line 21, in <module>
    print(flash_attention.flash_attention(xq, xk, xv, None, debug=True))
  File "/home/hanq/.local/lib/python3.10/site-packages/jax/_src/pallas/mosaic/pallas_call_registration.py", line 88, in pallas_call_tpu_lowering_rule
    return mlir.lower_fun(_lower_fun, multiple_results=True)(
  File "/home/hanq/.local/lib/python3.10/site-packages/jax/_src/pallas/mosaic/pallas_call_registration.py", line 79, in _lower_fun
    return mosaic.as_tpu_kernel(
  File "/home/hanq/.local/lib/python3.10/site-packages/jax/_src/tpu_custom_call.py", line 408, in as_tpu_kernel
    lowered_module_asm, constants = _lower_tpu_kernel(
  File "/home/hanq/.local/lib/python3.10/site-packages/jax/_src/tpu_custom_call.py", line 347, in _lower_tpu_kernel
    apply_vector_layout.apply(module, hardware_generation)
The above exception was the direct cause of the following exception:

jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hanq/llama/test_jax.py", line 21, in <module>
    print(flash_attention.flash_attention(xq, xk, xv, None, debug=True))
  File "/home/hanq/.local/lib/python3.10/site-packages/jax/_src/pallas/mosaic/pallas_call_registration.py", line 88, in pallas_call_tpu_lowering_rule
    return mlir.lower_fun(_lower_fun, multiple_results=True)(
  File "/home/hanq/.local/lib/python3.10/site-packages/jax/_src/pallas/mosaic/pallas_call_registration.py", line 79, in _lower_fun
    return mosaic.as_tpu_kernel(
  File "/home/hanq/.local/lib/python3.10/site-packages/jax/_src/tpu_custom_call.py", line 408, in as_tpu_kernel
    lowered_module_asm, constants = _lower_tpu_kernel(
  File "/home/hanq/.local/lib/python3.10/site-packages/jax/_src/tpu_custom_call.py", line 347, in _lower_tpu_kernel
    apply_vector_layout.apply(module, hardware_generation)
  File "/home/hanq/.local/lib/python3.10/site-packages/jaxlib/mosaic/python/apply_vector_layout.py", line 1628, in apply
    apply_layout_func(ctx, f)
  File "/home/hanq/.local/lib/python3.10/site-packages/jaxlib/mosaic/python/apply_vector_layout.py", line 1535, in apply_layout_func
    apply_layout_block(ctx, entry_block)
  File "/home/hanq/.local/lib/python3.10/site-packages/jaxlib/mosaic/python/apply_vector_layout.py", line 1541, in apply_layout_block
    apply_layout_op(ctx, op)
  File "/home/hanq/.local/lib/python3.10/site-packages/jaxlib/mosaic/python/apply_vector_layout.py", line 1616, in apply_layout_op
    rule(ctx, op, layout_in, layout_out)
  File "/home/hanq/.local/lib/python3.10/site-packages/jaxlib/mosaic/python/apply_vector_layout.py", line 2572, in _vector_load_rule
    memref_tiling = get_memref_tiling(op.base)
  File "/home/hanq/.local/lib/python3.10/site-packages/jaxlib/mosaic/python/apply_vector_layout.py", line 3498, in get_memref_tiling
    raise RuntimeError("Expected a tiled memref")
RuntimeError: Expected a tiled memref
```

Without the debug = True would get the same exception but without the logs of MLIR; so I pasted the one with debug = True.

**Comment by qihqi** [comment]
Another data point: if I add `interpret=True` to `pl.pallas_call` inside of the flash_attention.py; then it passes.

**Comment by sharadmv** [comment]
What TPU version are you using?

**Comment by sharadmv** [comment]
I think you'll also need a nightly jaxlib for this to work.

**Comment by qihqi** [comment]
Updated today's nightlies: 
jax==0.4.21.dev20231118
jaxlib==0.4.21.dev20231118
libtpu-nightly @ https://storage.googleapis.com/cloud-tpu-tpuvm-artifacts/wheels/libtpu-nightly/libtpu_nightly-0.1.dev20231118-py3-none-any.whl

Issue still presists.

(Note, in today's nightlies, it will first give `KeyError: 'xla_mosaic_dump_to'`; I commented that function out and then it will give back the same `RuntimeError: Expected a tiled memref` error.

**Comment by sharadmv** [comment]
One thing I see is that you need to swap the num_heads and seqlen dimension for TPU.

Could you try that? Unsure of it will fix the error but worth trying.

**Comment by qihqi** [comment]
Tried, doesnt work.

Why would it be differnt anyways? both `seqlen` and `n_heads` are just integers; and flash_attention should work bof both (seqlen=1000, n_heads=32) and (seqlen=32, n_heads=1000). 

I am curious if you can repro my error or not. If not, I'd love to know your environment setup so I can use that exact one (I don't care of using the newest Jax, I just need a version that works). Thanks!

**Comment by sharadmv** [comment]
> Why would it be differnt anyways?

In pallas, dimension order has physical implication. On TPUs, we need to pick some two dimensions to be layed out as vector register dimensions and the rest will be unrolled across many vector registers. In the case of flash attention, we lay the seqlen and head_dim across register dimensions and unroll over bs, heads.

One last thing to try before I can do a more thorough investigation tomorrow would be to use seqlen=1024. Mosaic doesn't support arbitrary padding on all dimensions quite yet so it's worth trying powers of 2 for the last two dimensions. head_dim of 128 is already fine.

**Comment by qihqi** [comment]
yes, the issue still persists with `seqlen=1024`.

Just to understand more, you are saying the flipping variables `seqlen` and `n_heads` matter because the kernel might expect `seqlen > n_heads`? Because the name of python variables  definitely shouldn't matter.

**Comment by sharadmv** [comment]
Okay, I'll do a more thorough investigation tomorrow.

Wrt to dimension order, the kernel expects a sequence length dimension (ie something usually bigger than number of heads) in the second to last position.

**Comment by sharadmv** [comment]
I was able to run it successfully on a Cloud TPU VM (v5e) with these versions:
```
absl-py==2.0.0
certifi==2023.11.17
charset-normalizer==3.3.2
idna==3.6
-e git+https://github.com/google/jax.git@523f36153f7e39f5bc87a4d9fb346fdeb5122f22#egg=jax
jaxlib==0.4.21.dev20231127
libtpu-nightly @ https://storage.googleapis.com/cloud-tpu-tpuvm-artifacts/wheels/libtpu-nightly/libtpu_nightly-0.1.dev20231127-py3-none-any.whl#sha256=9dc8214ff9a50ceec13cd93df7053106a8750bc1df4c7edc351794f436753756
ml-dtypes==0.3.1
numpy==1.26.2
opt-einsum==3.3.0
requests==2.31.0
scipy==1.11.4
urllib3==2.1.0
```

I ran this script:
```python
import jax
import jax.numpy as jnp
from jax.experimental.pallas.ops.tpu import flash_attention

bs = 2
seqlen = 1024
n_heads = 32
dim = 128
rng = jax.random.PRNGKey(0)
xq = jax.random.normal(rng, (bs, n_heads, seqlen, dim))
xk = jax.random.normal(rng, (bs, n_heads, seqlen, dim))
xv = jax.random.normal(rng, (bs, n_heads, seqlen, dim))

print('reference')
res = flash_attention.mha_reference(xq, xk, xv, None)
print(res)
print(res.shape)

print('real kernel')
print(flash_attention.flash_attention(xq, xk, xv, None))
```

**Comment by qihqi** [comment]
Thanks! Confirmed that `jax @ git+https://github.com/google/jax.git@523f36153f7e39f5bc87a4d9fb346fdeb5122f22` Also works on cloud-tpu v4-8

**Comment by qihqi** [comment]
Reopening the issue, the flash attention still have the following 2 issues:
1. When `seqlen = 1` it gives `ValueError: block_q=128 should be smaller or equal to q_seq_len=1`. I understand that it probably it is by design at this point. However, I would like to ask for the support for the case of seqlen = 1 as this is the case during the `decode` phase for a typical LLM inference.
2. It's not faster than the reference implementation; which kinda of defeats the purpose of using a specialized kernel.

Script used:
```python
import time
import jax
import jax.numpy as jnp
from jax.experimental.pallas.ops.tpu import flash_attention

bs = 2
seqlen = 1024
n_heads = 1024
dim = 512
rng = jax.random.PRNGKey(0)
xq = jax.random.normal(rng, (bs, n_heads, seqlen, dim))
xk = jax.random.normal(rng, (bs, n_heads, seqlen, dim))
xv = jax.random.normal(rng, (bs, n_heads, seqlen, dim))


print('real kernel')
mha_real = jax.jit(flash_attention.flash_attention)
for _ in range(4):
    xq = jax.random.normal(rng, (bs, n_heads, seqlen, dim))
    xk = jax.random.normal(rng, (bs, n_heads, seqlen, dim))
    xv = jax.random.normal(rng, (bs, n_heads, seqlen, dim))
    start = time.time()
    res = jax.block_until_ready(mha_real(xq, xk, xv, None))
    end = time.time()
    print(end - start)

print('reference')
mha_ref = jax.jit(flash_attention.mha_reference)
for _ in range(4):
    xq = jax.random.normal(rng, (bs, n_heads, seqlen, dim))
    xk = jax.random.normal(rng, (bs, n_heads, seqlen, dim))
    xv = jax.random.normal(rng, (bs, n_heads, seqlen, dim))
    start = time.time()
    res = jax.block_until_ready(mha_ref(xq, xk, xv, None))
    end = time.time()
    print(end - start)
print(res.shape)
del res

print(' diff ')
res1 = jax.block_until_ready(mha_ref(xq, xk, xv, None))
res2 = jax.block_until_ready(mha_real(xq, xk, xv, None))
print('max diff', jnp.max(jnp.abs(res1 - res2)))
```

Output

```
hanq@t1v-n-cfe84bb3-w-0:~/llama$ python test_jax.py
real kernel
0.29532814025878906
0.22074246406555176
0.22089743614196777
0.22095751762390137
reference
0.9379653930664062
0.1637272834777832
0.16379451751708984
0.16376519203186035
(2, 1024, 1024, 512)
 diff
max diff 0.0
```

The first run it's faster I guess it's faster to compile. But the subsequent runs are slower.

**Comment by sharadmv** [comment]
> When seqlen = 1 it gives ValueError: block_q=128 should be smaller or equal to q_seq_len=1. I understand that it probably it is by design at this point. However, I would like to ask for the support for the case of seqlen = 1 as this is the case during the decode phase for a typical LLM inference.

You probably want a slightly different kernel for decoding. On a TPU, naively using a sequence length of 1 will result in an extremely padded matmul. We might want to do a matrix vector product or somethign else.

> It's not faster than the reference implementation; which kinda of defeats the purpose of using a specialized kernel.

You're seeing these results for 2 reasons:
1. You are using default block sizes, which tend to be slow. Try passing in `block_sizes` (https://github.com/google/jax/blob/c855bb0371fd7df3e2c33c0d153a23299b4f1988/jax/experimental/pallas/ops/tpu/flash_attention.py#L148) and sweep over larger ones. You should see significant performance improvements.
2. You are using a somewhat small sequence length. For sequence lengths <= 4096, XLA has some fusions that do something similar to flash attention so the expected improvement over XLA isn't that big. Once you go to 8k and above, you should see much bigger improvements.

**Comment by qihqi** [comment]
Thanks Sharad! Yes I tried few block sizes indeed it got faster. Thanks for the pointers!
