### ISSUE TITLE
Casting from list of strings to floats

### ISSUE THREAD

**Issue by Razcle** [google/jax#1883]
Hi,

I ran into the following issue and wondered what the best way to proceed is.  I loaded some data from a text file and tried to convert it to an array. This seemed to work fine in ordinary numpy but raises an error in jax.

Is this a feature that Jax might benefit from? Do you have a recommended way around this?

thanks!

heres a minimal reproduction:
```
>>> import numpy as np
>>> import jax.numpy as jnp
>>> x = np.array('3.4').astype(np.float32)
>>> y = jnp.array('3.4').astype(jnp.float32)
Traceback (most recent call last):
  File "/Users/Raza/miniconda3/envs/active-learning/lib/python3.6/site-packages/jax/interpreters/xla.py", line 126, in abstractify
    return pytype_aval_mappings[type(x)](x)
KeyError: <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Raza/miniconda3/envs/active-learning/lib/python3.6/site-packages/jax/numpy/lax_numpy.py", line 1653, in array
    out = lax.reshape(object, ())
  File "/Users/Raza/miniconda3/envs/active-learning/lib/python3.6/site-packages/jax/lax/lax.py", line 635, in reshape
    old_sizes=onp.shape(operand))
  File "/Users/Raza/miniconda3/envs/active-learning/lib/python3.6/site-packages/jax/core.py", line 150, in bind
    return self.impl(*args, **kwargs)
  File "/Users/Raza/miniconda3/envs/active-learning/lib/python3.6/site-packages/jax/lax/lax.py", line 2475, in _reshape_impl
    dimensions=dimensions, old_sizes=old_sizes)
  File "/Users/Raza/miniconda3/envs/active-learning/lib/python3.6/site-packages/jax/interpreters/xla.py", line 142, in apply_primitive
    compiled_fun = xla_primitive_callable(prim, *abstract_args, **params)
  File "/Users/Raza/miniconda3/envs/active-learning/lib/python3.6/site-packages/jax/interpreters/xla.py", line 128, in abstractify
    raise TypeError("No abstraction handler for type: {}".format(type(x)))
TypeError: No abstraction handler for type: <class 'str'>
```

**Comment by hawkinsp** [comment]
In general JAX doesn't support string types. However, in this case, there's an easy workaround: you can first cast your array to a classic Numpy array and then convert the result to a JAX array, e.g., `jnp.array(np.array('3.4').astype(np.float32))`

Does that work for you?

**Comment by Razcle** [comment]
Thanks. Thats exactly what I ended up! :)
