### ISSUE TITLE
unexpected UnshapedArray

### ISSUE THREAD

**Issue by lvstlc** [google/jax#18859]
### Description

```python
from dataclasses import dataclass
import jax
import jax.numpy as jnp


@jax.tree_util.register_pytree_node_class
@dataclass
class DataClass_sub:
    def tree_flatten(self):
        return ([self.array], None)
    
    @classmethod
    def tree_unflatten(cls, aux_data, children):
        return cls(*children)

    array: jnp.ndarray


@jax.tree_util.register_pytree_node_class
@dataclass()
class DataClass:
    def tree_flatten(self):
        return ([self.array0, self.array1, self.dataclass_sub], None)

    @classmethod
    def tree_unflatten(cls, aux_data, children):
        return cls(*children)

    array0: jnp.ndarray
    array1: jnp.ndarray
    dataclass_sub: DataClass_sub

@jax.custom_vjp
def subfunc( data, array ):
    return 0.
def subfunc_fwd(data, array):
    return 0., (data, array)

def subfunc_bwd(input, g):
    grads = input[1]

    return (0., g * grads )

subfunc.defvjp(subfunc_fwd, subfunc_bwd)

@jax.jit
def func_custom_vjp(
    array,
    data0: DataClass
):
    tmp = data0.array0.at[jnp.array([0])].set(array)
    data = DataClass(tmp, 1.0/(1.0+tmp**2), data0.dataclass_sub)
    return subfunc(data, array)

size=10
dataclass_sub = DataClass_sub(jnp.zeros( (size,) ))
dataclass = DataClass( array0 = jnp.zeros(size), array1 = jnp.zeros(size), dataclass_sub=dataclass_sub )
grad_func = jax.grad(func_custom_vjp, argnums=0)

grads = grad_func(jnp.array([0.]), dataclass)
print(grads)

```

Above code produces the below error message 1.
When I change "data = DataClass(tmp, 1.0/(1.0+tmp**2), data0.dataclass_sub)" to "data = DataClass(tmp, tmp, data0.dataclass_sub)", I get below error message 2.
(I have obscured part of the file paths).

I am a beginner in using jax and pytree, so I would appreciate it if you could let me know if I am using it incorrectly.

===error message 1===
```
Traceback (most recent call last):
  File "test.py", line 60, in <module>
    grads = grad_func(jnp.array([0.]), dataclass)
  File "test.py", line 51, in func_custom_vjp
    tmp = data0.array0.at[jnp.array([0])].set(array)
  File "\lib\site-packages\jax\_src\numpy\array_methods.py", line 495, in set
    return scatter._scatter_update(self.array, self.index, values, lax.scatter,
  File "\lib\site-packages\jax\_src\ops\scatter.py", line 78, in _scatter_update
    return _scatter_impl(x, y, scatter_op, treedef, static_idx, dynamic_idx,
  File "\lib\site-packages\jax\_src\ops\scatter.py", line 126, in _scatter_impl
    out = scatter_op(
jax._src.source_info_util.JaxStackTraceBeforeTransformation: TypeError: UnshapedArray has no shape. Please open an issue at https://github.com/google/jax/issues because it's unexpected for UnshapedArray instances to ever be produced.

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 60, in <module>
    grads = grad_func(jnp.array([0.]), dataclass)
TypeError: UnshapedArray has no shape. Please open an issue at https://github.com/google/jax/issues because it's unexpected for UnshapedArray instances to ever be produced.
```

===error message 2===
```
Traceback (most recent call last):
  File "test.py", line 60, in <module>
    grads = grad_func(jnp.array([0.]), dataclass)
  File "test.py", line 51, in func_custom_vjp
    tmp = data0.array0.at[jnp.array([0])].set(array)
  File "\lib\site-packages\jax\_src\numpy\array_methods.py", line 495, in set
    return scatter._scatter_update(self.array, self.index, values, lax.scatter,
  File "\lib\site-packages\jax\_src\ops\scatter.py", line 78, in _scatter_update
    return _scatter_impl(x, y, scatter_op, treedef, static_idx, dynamic_idx,
  File "\lib\site-packages\jax\_src\ops\scatter.py", line 126, in _scatter_impl
    out = scatter_op(
jax._src.source_info_util.JaxStackTraceBeforeTransformation: TypeError: Invalid start_index_map; domain is [0, 0), got: 0->0.

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.  

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 60, in <module>
    grads = grad_func(jnp.array([0.]), dataclass)
TypeError: Invalid start_index_map; domain is [0, 0), got: 0->0.
```
### What jax/jaxlib version are you using?

jax0.4.21 jaxlib0.4.21

### Which accelerator(s) are you using?

cpu

### Additional system info?

print(numpy.__version__):1.24.3,   print(sys.version):3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)],    print(platform.uname()):uname_result(system='Windows', node='DESKTOP-TU7H8UO', release='10', version='10.0.22621', machine='AMD64')

**Comment by patrick-kidger** [comment]
The problem is
```python
def subfunc_bwd(input, g):
    grads = input[1]

    return (0., g * grads )
```
you're returning a scalar `0.` as the gradient for the `data` input. These are not matching pytree structures or matching array shapes.

You want either:
```python
return jax.tree_util.tree_map(jnp.zeros_like, input[0]), g * grads
```
to explicitly pass zeros for every position; or
```python
return None, g *grads
```
as JAX understands a `None` to mean passing a zero gradient for the whole argument.

I agree that this definitely isn't obvious though! The errors you get here don't communicate this at all. I've labelled this as needing a better error.

**Comment by lvstlc** [comment]
Thank you for pointing out the error in my code.
I appreciate your guidance on the correct usage of the library!
