### ISSUE TITLE
[jax_dynamic_shapes] `clean_up_dead_vars` removes variable which may still be referenced when using `jax_dynamic_shapes`

### ISSUE THREAD

**Issue by erick-xanadu** [google/jax#18936]
### Description

Hi,

we are using JAX to generate StableHLO and we are interested in `abstracted_axes` and ranked tensors with dynamic/unknown shapes. We have already contributed a couple of pull requests [[0]](https://github.com/google/jax/pull/18579), [[1]](https://github.com/google/jax/pull/18505). We are interested in continuing contributing another pull request for the following issue:

When `jax.jit`ing a function with `jax.config.update("jax_dynamic_shapes", True) ` this function will raise a `KeyError` in the following example.

```python
import jax

jax.config.update("jax_enable_x64", True)
jax.config.update("jax_platform_name", "cpu")
jax.config.update("jax_dynamic_shapes", True)

@jax.jit
def f(s):
    a = jax.numpy.ones(s)
    b = jax.numpy.ones(s)
    return a + b

f((1,))
```

with the following stack trace:

```
--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/erick.ochoalopez/Code/cataliist/test.py", line 13, in <module>
    f((1,))
  File "/home/erick.ochoalopez/Code/env/lib/python3.10/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/erick.ochoalopez/Code/env/lib/python3.10/site-packages/jax/_src/pjit.py", line 253, in cache_miss
    outs, out_flat, out_tree, args_flat, jaxpr = _python_pjit_helper(
  File "/home/erick.ochoalopez/Code/env/lib/python3.10/site-packages/jax/_src/pjit.py", line 166, in _python_pjit_helper
    out_flat = pjit_p.bind(*args_flat, **params)
  File "/home/erick.ochoalopez/Code/env/lib/python3.10/site-packages/jax/_src/core.py", line 2597, in bind
    return self.bind_with_trace(top_trace, args, params)
  File "/home/erick.ochoalopez/Code/env/lib/python3.10/site-packages/jax/_src/core.py", line 390, in bind_with_trace
    out = trace.process_primitive(self, x, params)
  File "/home/erick.ochoalopez/Code/env/lib/python3.10/site-packages/jax/_src/core.py", line 822, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/erick.ochoalopez/Code/env/lib/python3.10/site-packages/jax/_src/pjit.py", line 1209, in _pjit_call_impl
    return xc._xla.pjit(name, f, call_impl_cache_miss, [], [], donated_argnums,
  File "/home/erick.ochoalopez/Code/env/lib/python3.10/site-packages/jax/_src/pjit.py", line 1192, in call_impl_cache_miss
    out_flat, compiled = _pjit_call_impl_python(
  File "/home/erick.ochoalopez/Code/env/lib/python3.10/site-packages/jax/_src/pjit.py", line 1125, in _pjit_call_impl_python
    compiled = _pjit_lower(
  File "/home/erick.ochoalopez/Code/env/lib/python3.10/site-packages/jax/_src/pjit.py", line 1259, in _pjit_lower
    return _pjit_lower_cached(jaxpr, in_shardings, out_shardings, *args, **kwargs)
  File "/home/erick.ochoalopez/Code/env/lib/python3.10/site-packages/jax/_src/pjit.py", line 1301, in _pjit_lower_cached
    return pxla.lower_sharding_computation(
  File "/home/erick.ochoalopez/Code/env/lib/python3.10/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/home/erick.ochoalopez/Code/env/lib/python3.10/site-packages/jax/_src/interpreters/pxla.py", line 1968, in lower_sharding_computation
    nreps, tuple_args, shape_poly_state) = _cached_lowering_to_hlo(
  File "/home/erick.ochoalopez/Code/env/lib/python3.10/site-packages/jax/_src/interpreters/pxla.py", line 1808, in _cached_lowering_to_hlo
    lowering_result = mlir.lower_jaxpr_to_module(
  File "/home/erick.ochoalopez/Code/env/lib/python3.10/site-packages/jax/_src/interpreters/mlir.py", line 729, in lower_jaxpr_to_module
    lower_jaxpr_to_fun(
  File "/home/erick.ochoalopez/Code/env/lib/python3.10/site-packages/jax/_src/interpreters/mlir.py", line 1070, in lower_jaxpr_to_fun
    out_vals, tokens_out = jaxpr_subcomp(ctx.replace(name_stack=callee_name_stack),
  File "/home/erick.ochoalopez/Code/env/lib/python3.10/site-packages/jax/_src/interpreters/mlir.py", line 1223, in jaxpr_subcomp
    axis_size_env = {d: read(d)[0]
  File "/home/erick.ochoalopez/Code/env/lib/python3.10/site-packages/jax/_src/interpreters/mlir.py", line 1223, in <dictcomp>
    axis_size_env = {d: read(d)[0]
  File "/home/erick.ochoalopez/Code/env/lib/python3.10/site-packages/jax/_src/interpreters/mlir.py", line 1161, in read
    return env[v]
jax._src.traceback_util.UnfilteredStackTrace: KeyError: a

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

```

(Please note that to run this example you'll likely need to [[0]](https://github.com/google/jax/pull/18579) and [[1]](https://github.com/google/jax/pull/18505))

I've narrowed it down to an error in `last_used` and [`clean_up_dead_vars`](https://github.com/google/jax/blob/b077483bfaaf197b79717a86bee3e626474e93f2/jax/_src/core.py#L3214-L3220) inlined below

```python
def last_used(jaxpr: Jaxpr) -> dict[Var, JaxprEqn | None]:
  """Returns a mapping from every var in jaxpr to what equation uses it last."""
  last_used: dict[Var, JaxprEqn | None] = {
      v: None for v in jaxpr.outvars if not isinstance(v, Literal)}
  for eqn in reversed(jaxpr.eqns):
    for v in eqn.invars:
      if not isinstance(v, Literal) and v not in last_used:
        last_used[v] = eqn
  return last_used

def clean_up_dead_vars(eqn: JaxprEqn, env: dict[Var, Any],
                       last_used: dict[Var, JaxprEqn | None]):
  """Remove all eqn.invars from env if eqn is the last time they were used."""
  for v in {v for v in eqn.invars if not isinstance(v, Literal)}:
    if last_used[v] is eqn:
      # Delete ref to variable when it is no longer needed by next equations.
      del env[v]
```

What happens is that `last_used` does not look for the variable `v` in eqn.outvars types. When using `jax_dynamic_shapes`, jaxpr variables may be part of types. Since `last_used` does not look at the type of the variables for potential last uses, it will eventually return an instruction which is before the actual last use of the variable. The variable will be deleted by `clean_up_dead_vars` and later on, will result in the error above being raised.

I am happy to discuss possible solutions to this and submit a PR sometime (perhaps next year?). The proposed solution would look something like the following:

Thanks!

### What jax/jaxlib version are you using?

0.4.21

### Which accelerator(s) are you using?

CPU

### Additional system info?

1.26.1 3.10.11 (main, May 13 2023, 12:07:51) [GCC 9.4.0] uname_result(system='Linux', node='DL7420-GS4N1J3', release='5.15.0-88-generic', version='#98~20.04.1-Ubuntu SMP Mon Oct 9 16:43:45 UTC 2023', machine='x86_64')

**Comment by erick-xanadu** [comment]
Just a small correction, the patches mentioned in the issue description (inlined below) are not needed to reproduced this error:

> (Please note that to run this example you'll likely need to https://github.com/google/jax/pull/18579 and https://github.com/google/jax/pull/18505)

The description will be updated to remove the need of these patches to reproduce this error.
