### ISSUE TITLE
`Transpose rule for 'custom_vjp_call_jaxpr' not implemented` for `grad(custom_jvp(custom_vjp))`

### ISSUE THREAD

**Issue by patrick-kidger** [google/jax#19087]
### Description

```python
import jax

@jax.custom_jvp
def f(x, y):
    assert False

@f.defjvp
def f_jvp(primals, tangents):
    x, y = primals
    tx, ty = tangents
    return x + y, g(tx, ty)

@jax.custom_vjp
def g(tx, ty):
    return tx + ty

def g_fwd(tx, ty):
    assert False

def g_bwd(res, ct):
    assert False

g.defvjp(g_fwd, g_bwd)

jax.grad(f)(1., 1.)
```
produces
```python
  File ".../jax/_src/interpreters/ad.py", line 287, in get_primitive_transpose
    return primitive_transposes[p]
           ~~~~~~~~~~~~~~~~~~~~^^^
KeyError: custom_vjp_call_jaxpr

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "file.py", line 25, in <module>
    jax.grad(f)(1., 1.)
  File "file.py", line 11, in f_jvp
    return x + y, g(tx, ty)
jax._src.source_info_util.JaxStackTraceBeforeTransformation: NotImplementedError: Transpose rule (for reverse-mode differentiation) for 'custom_vjp_call_jaxpr' not implemented

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "file.py", line 25, in <module>
    jax.grad(f)(1., 1.)
NotImplementedError: Transpose rule (for reverse-mode differentiation) for 'custom_vjp_call_jaxpr' not implemented
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```

### What jax/jaxlib version are you using?

0.4.23

**Comment by karandhaodiyal28-hash** [comment]
Verified this still reproduces on `jax 0.11.0` (CPU, no accelerator). Minimal repro:

```python
import jax

@jax.custom_jvp
def f(x, y):
    assert False  # never called; grad only needs the JVP rule

@f.defjvp
def f_jvp(primals, tangents):
    x, y = primals
    tx, ty = tangents
    return x + y, g(tx, ty)          # tangent is produced by a custom_vjp fn

@jax.custom_vjp
def g(tx, ty):
    return tx + ty
def g_fwd(tx, ty): assert False
def g_bwd(res, ct): assert False
g.defvjp(g_fwd, g_bwd)

jax.grad(f)(1.0, 1.0)
# NotImplementedError: Transpose rule (for reverse-mode differentiation)
#                      for 'custom_vjp_call' not implemented
```

(The primitive is now `custom_vjp_call`; the issue's original `custom_vjp_call_jaxpr` name is the pre-rename form.)

**Root cause.** `jax.grad` = linearize + transpose. Linearizing `f` runs its `custom_jvp` rule `f_jvp`, whose tangent is produced by calling the `custom_vjp` function `g`. That leaves a `custom_vjp_call` primitive sitting *inside the linear (tangent) computation*, which reverse-mode then has to transpose. The transpose dispatch in `jax/_src/interpreters/ad.py` (`backward_pass`, ~L414) checks `fancy_transposes` and then `get_primitive_transpose` (`primitive_transposes`, L348), and raises `NotImplementedError` because `custom_vjp_call_p` has no transpose rule registered.

In `jax/_src/custom_derivatives.py`, `custom_vjp_call_p` (~L1058) is wired up with an MLIR lowering (~L1060), a typecheck (~L1071), a DCE rule (~L1131) and a pretty-print rule (~L1148) — but no `ad.primitive_transposes[custom_vjp_call_p]` / `ad.fancy_transposes[custom_vjp_call_p]`. By contrast `custom_jvp_call_p` *does* register one: `ad.fancy_transposes[custom_jvp_call_p] = _custom_jvp_call_transpose_fancy` (~L480), which transposes the primal `call_jaxpr` via `ad.backward_pass3(...)`.

**Why the normal `grad(custom_vjp)` path is fine but this one isn't.** In the usual path, a `custom_vjp` under reverse-mode is partial-eval'd into a `custom_lin` primitive, and `custom_lin_p` *does* have a transpose rule (`ad.primitive_transposes[custom_lin_p] = _custom_lin_transpose`, ad.py ~L1311) that invokes the user's `bwd`. But when the `custom_vjp` is called *inside a `custom_jvp` tangent*, the `custom_vjp_call` primitive lands directly in the jaxpr being transposed and never goes through the `custom_lin` partial-eval path — so there is nothing to invoke.

**Possible directions (would appreciate your steer before a PR):**
1. Register `ad.fancy_transposes[custom_vjp_call_p]` mirroring `_custom_jvp_call_transpose_fancy` — i.e. transpose the primal `call_jaxpr` directly. Simple and symmetric with `custom_jvp_call`, but it *ignores the user-supplied `bwd`*; that seems right when the `custom_vjp` is being used purely linearly inside a tangent, but I'd like to confirm the intended semantics.
2. Route `custom_vjp_call` through the existing `custom_lin` machinery in this context (partial-eval to `custom_lin` so `_custom_lin_transpose` applies and the user's `bwd` is honored). More faithful to `custom_vjp` semantics, but more invasive.
3. If neither is desirable, at minimum raise an explicit, documented error at the point of composition explaining that a `custom_vjp` used inside a `custom_jvp` tangent isn't transposable, with the recommended workaround.

@mattjj (and JAX autodiff maintainers) — which of these matches your intended design? I have a working repro + a regression test ready and am happy to implement whichever direction you prefer.

**Comment by mattjj** [comment]
Thanks for pinging the issue and providing a breakdown, @karandhaodiyal28-hash ! Actually because the expected or intended behavior is ambiguous here, as you point out, I think the best solution is to guide people to hijax primitives (namely VJPHiPrimitive), which would let them define a transpose rule directly. I can unpack that when I’m at a keyboard. I think the only changes we need are (1) documenting hi primitive transposes (maybe just in new_docs) and (2) adjusting this error message to point people that direction.

**Comment by karandhaodiyal28-hash** [comment]
Thanks @mattjj, that direction makes sense — pointing people to hijax `VJPHiPrimitive` so they can define the transpose rule themselves side-steps the ambiguity cleanly, rather than us baking in one interpretation.

Happy to take on both parts once you've had a chance to unpack the specifics: (1) adjusting the `custom_vjp_call` transpose `NotImplementedError` to point users toward hi-primitive transposes, and (2) documenting hi-primitive transposes (in `new_docs`). I'll hold off on a PR until you share the preferred wording/scope so it matches what you have in mind.

**Comment by mattjj** [comment]
Want to give it a shot and I’ll give a review? Something concise. I’m not 100% sure that we’ve cleaned up the transpose interface on VJPHiPrimitive, so be on the lookout for anything that needs improvement.
