### ISSUE TITLE
Testing __cuda_array_interface__ attribute of a CPU array throws an exception

### ISSUE THREAD

**Issue by pearu** [google/jax#19134]
### Description

As in the title.

Reproducer:

```python
>>> import jax
>>> jax.config.update('jax_platform_name', 'cpu')
>>> a = jax.numpy.array([1, 2])
>>> hasattr(a, '__cuda_array_interface__')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
jaxlib.xla_extension.XlaRuntimeError: INVALID_ARGUMENT: __cuda_array_interface__ is only defined for NVidia GPU buffers.
```

The expected behavior is
```python
>>> hasattr(a, '__cuda_array_interface__')
False
``` 
similar to PyTorch or NumPy:
```python
>>> import numpy
>>> a = numpy.array([1, 2])
>>> hasattr(a, '__cuda_array_interface__')
False
>>> import torch
>>> a = torch.tensor([1, 2], device='cpu')
>>> hasattr(a, '__cuda_array_interface__')
False
>>> a = torch.tensor([1, 2], device='cuda')
>>> hasattr(a, '__cuda_array_interface__')
True
```

### What jax/jaxlib version are you using?

0.4.24.dev20231215+41531123f 0.4.24.dev20231215+41531123f

### Which accelerator(s) are you using?

CPU

### Additional system info?

1.26.2 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:27:40) [GCC 11.3.0] uname_result(system='Linux', node='ex', release='5.4.0-153-generic', version='#170-Ubuntu SMP Fri Jun 16 13:43:31 UTC 2023', machine='x86_64')

**Comment by pearu** [comment]
The same issue also breaks `jax.numpy.from_dlpack` on CPU arrays:
```python
>>> import jax
>>> jax.config.update('jax_platform_name', 'cpu')
>>> a = jax.numpy.array([1, 2])
>>> jax.numpy.from_dlpack(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pearu/git/pearu/jax/jax/_src/numpy/lax_numpy.py", line 2386, in from_dlpack
    return from_dlpack(x.__dlpack__())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pearu/git/pearu/jax/jax/_src/dlpack.py", line 123, in from_dlpack
    return jnp.asarray(xla_client._xla.dlpack_managed_tensor_to_buffer(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pearu/git/pearu/jax/jax/_src/numpy/lax_numpy.py", line 2186, in asarray
    if hasattr(a, "__cuda_array_interface__"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: INVALID_ARGUMENT: __cuda_array_interface__ is only defined for NVidia GPU buffers.
```

**Comment by jakevdp** [comment]
Hi - thanks for the report!

Can you confirm what JAX version you're using? I can't reproduce your `jax.numpy.from_dlpack` error on any recent JAX release; in particular I can't find any JAX version where line 2186 of `lax_numpy.py` contains the line `    if hasattr(a, "__cuda_array_interface__"):`

As for the `hasattr` function failing... I think this is working as expected. All arrays have this attribute, it's just that some of them raise an error because they are not on the appropriate device. We could have chosen to implement this differently, so that only arrays on particular devices have this attribute, but that would break the assumptions of static type checkers like `mypy` and `pytype`.

Rather than `hasattr`, you might think about doing something like this:
```python
try:
  a.__cuda_array_interface__
except:
  is_cuda = False
else:
  is_cuda = True
```
What do you think?

**Comment by hawkinsp** [comment]
It's possible that we should throw a different exception from our pybind11 code, though so Python thinks the attribute is not present.

**Comment by jakevdp** [comment]
If we throw an `AttributeError`, then the `isinstance` check at the top of this thread would work as expected.

**Comment by pearu** [comment]
> Can you confirm what JAX version you're using?

Sure:
```python
>>> jax.__version__
'0.4.24.dev20231228+d9aba6f67'
```

Also, confirming that with recent main branch, https://github.com/google/jax/issues/19134#issuecomment-1873304362 is fixed.

**Comment by pearu** [comment]
> As for the `hasattr` function failing... I think this is working as expected. All arrays have this attribute, it's just that some of them raise an error because they are not on the appropriate device. We could have chosen to implement this differently, so that only arrays on particular devices have this attribute, but that would break the assumptions of static type checkers like `mypy` and `pytype`, in which the existence of object attributes cannot depend on runtime values.

The current behavior contradicts `hasattr` semantics. It should return True or False depending on whether the object has the attribute specified by a name. At the level of `hasattr`, device-specific behavior is irrelevant.

The device-specific behavior should be implemented in `getattr`. There are a few choices how to handle cuda-specific attributes of non-cuda-specific arrays:
- throw a runtime error - I think this is not correct because the device-specific attributes are set at array construction time and that cannot be changed during the array life time.
- throw an attribute error - this is exact behavior when `hasattr()` returns `False`

I think throwing an attribute error from `getattr` in this situation is not going to be a problem for `mypy` as.
For instance, PyTorch is mypy-compliant (however, it could depend on PyTorch mypy configuration, I haven't check that yet) and it implements the following behavior:
```python
>>> import torch
>>> a = torch.tensor([1, 2]).cpu()
>>> hasattr(a, "__cuda_array_interface__")
False
>>> a.__cuda_array_interface__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pearu/git/pytorch/pytorch-csc/torch/_tensor.py", line 1103, in __cuda_array_interface__
    raise AttributeError(
AttributeError: Can't get __cuda_array_interface__ on non-CUDA tensor type: torch.LongTensor If CUDA data is required use tensor.cuda() to copy tensor to device memory.
>>> a = torch.tensor([1, 2]).cuda()
>>> hasattr(a, "__cuda_array_interface__")
True
>>> a.__cuda_array_interface__
{'typestr': '<i8', 'shape': (2,), 'strides': None, 'data': (140434749784064, False), 'version': 2}
```

**Comment by jakevdp** [comment]
> The current behavior contradicts `hasattr` semantics. It should return True or False depending on whether the object has the attribute specified by a name.

That's not how `hasattr` is implemented, nor is it how it is [documented](https://docs.python.org/3/library/functions.html#hasattr)

But I think we could raise `AttributeError` here instead of `XlaRuntimeError` to make `hasattr` work in this way.

**Comment by hawkinsp** [comment]
I'll make it throw an attribute error.

**Comment by hawkinsp** [comment]
https://github.com/openxla/xla/pull/8183 (primarily) fixes this.

**Comment by jakevdp** [comment]
This still is problematic for sharded arrays; tested on the most recent nightly builds:
```python
import os
os.environ["XLA_FLAGS"] = " --xla_force_host_platform_device_count=8"

import jax
import jaxlib
import jax.numpy as jnp
from jax.sharding import Mesh, NamedSharding, PartitionSpec as P

print(jax.__version__)
# 0.4.24.dev20240117

print(jaxlib.__version__)
# 0.4.24.dev20240117

x = jnp.arange(16, dtype='float32').reshape(8, 2)
print(hasattr(x, "__cuda_array_interface__"))
# False

mesh = Mesh(jax.devices(), axis_names=("i"))
x_sharded = jax.device_put(x, NamedSharding(mesh, P('i', None)))
print(hasattr(x_sharded, "__cuda_array_interface__"))
# ---------------------------------------------------------------------------
# XlaRuntimeError                           Traceback (most recent call last)
# <ipython-input-8-54aa643797c6> in <cell line: 21>()
#      19 mesh = Mesh(jax.devices(), axis_names=("i"))
#      20 x_sharded = jax.device_put(x, NamedSharding(mesh, P('i', None)))
# ---> 21 print(hasattr(x_sharded, "__cuda_array_interface__"))
#      22 

# XlaRuntimeError: INVALID_ARGUMENT: UnsafeBufferPointer() is supported only for unsharded arrays.
```
