### ISSUE TITLE
`jax.jvp` is tricky to use with non-differentiable inputs.

### ISSUE THREAD

**Issue by wjakob** [google/jax#19386]
### Description

This ticket is a follow-up of issue #4433 following a comment by @jakevdp [[link]](https://github.com/google/jax/issues/4433#issuecomment-1894147442_).

The following reproducer tries to compute the forward derivative of a simple function that has a differentiable and a non-differentiable (scalar, in this case) input.

```python
import numpy as np
import jax
import jax.numpy as jnp

bug = 0

@jax.jit
def f(x, y):
    return x + y

x  = jnp.array([1,2], dtype=jnp.float32)
dx = jnp.array([10,20], dtype=jnp.float32)
y = 1

if bug == 0:
    dy = 0
elif bug == 1:
    dy = jnp.empty((), dtype=jax.float0)
elif bug == 2:
    dy = np.empty((), dtype=jax.float0)

out, tangents = jax.jvp(f, (x, y), (dx, dy))
print(f'{out=}, {tangents=}')
```

When the `bug` variable is set to zero at the top, the IMO most intuitive version of the code is used. This yields the error
```
Traceback (most recent call last):
  File "/Users/wjakob/test.py", line 22, in <module>
    out, tangents = jax.jvp(f, (x, y), (dx, dy))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/jax/_src/api.py", line 1945, in jvp
    return _jvp(lu.wrap_init(fun), primals, tangents, has_aux=has_aux)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/jax/_src/api.py", line 1962, in _jvp
    raise TypeError("primal and tangent arguments to jax.jvp do not match; "
TypeError: primal and tangent arguments to jax.jvp do not match; dtypes must be equal, or in case of int/bool primal dtype the tangent dtype must be float0.Got primal dtype int32 and so expected tangent dtype [('float0', 'V')], but got tangent dtype int32 instead.
```

It seems impossible to actually create a JAX array with that dtype, I tried many different things. Setting `bug=1` gives an example of those difficulties:

```python
raceback (most recent call last):
  File "/Users/wjakob/test.py", line 18, in <module>
    dy = jnp.empty((), dtype=jax.float0)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/jax/_src/numpy/lax_numpy.py", line 2305, in empty
    dtypes.check_user_dtype_supported(dtype, "empty")
  File "/opt/homebrew/lib/python3.12/site-packages/jax/_src/dtypes.py", line 685, in check_user_dtype_supported
    raise TypeError(msg)
TypeError: JAX only supports number and bool dtypes, got dtype [('float0', 'V')] in empty
```

Setting `bug=2` finally works by creating such a `float0` array using NumPy (of all things!)

```
out=Array([2., 3.], dtype=float32), tangents=Array([10., 20.], dtype=float32)
```

Anyways, this seems like a somewhat weird interface and is probably a bug. And it seems contradictory with @jakevdp's comment:

>  float0 arrays are purely a trace-time entity, and can only exist on the host (XLA does not have any equivalent of a float0 type). 

I would also say that it's quite common for functions to accept non-differentiable arguments and still expect `jax.jvp` to work (such variables are bound to occur somewhere in a pytree in more complex applications)

### What jax/jaxlib version are you using?

0.4.23 0.4.23

### Which accelerator(s) are you using?

CPU

### Additional system info?

uname_result(system='Darwin', node='Wenzels1Macbook', release='22.6.0', version='Darwin Kernel Version 22.6.0: Thu Nov  2 07:43:57 PDT 2023; root:xnu-8796.141.3.701.17~6/RELEASE_ARM64_T6000', machine='arm64')

**Comment by jakevdp** [comment]
Thanks for the detail. I'm going to assign @mattjj, because he has the most context on `float0`. Matt, maybe this is a good case for replacing `float0` with an implementation based on extended dtypes?

**Comment by davisyoshida** [comment]
+1 on some kind of easy trace-time symbolic zero existing, but for unrelated reasons. I've had a few cases where constant folding of huge zero arrays leads to really long compile times, and I'm not aware of a nice pure JAX workaround atm.

**Comment by mattjj** [comment]
Thanks for raising this.

Yes we should expose a nice symbolic-zero dtype.

However, for this `jvp` issue in the OP, I'd suggest writing it like this so you never have to make a `dy`: `out, tangents = jax.jvp(lambda x: f(x, y), (x,), (dx,))`.

**Comment by patrick-kidger** [comment]
To handle the generic case you might be able to use [equinox.filter_jvp](https://docs.kidger.site/equinox/api/transformations/#equinox.filter_jvp) which uses `None` as the appropriate tangent type.

I wouldn't conflate this with symbolic zeros, though: I think choice of tangent dtype really is a separate thing. (What dtype would such a symbolic zero have, after all?)

I'd also advocate against removing `float0`: this won't be a fun compatibility change, e.g. I have code that special-cases this is in a few spots and I would really prefer that not break. What I think *would* make sense though is for fixing various ergonomic issues, e.g. allowing for `float0` JAX arrays or adding a public `jax.unit = np.empty((), dtype=jax.float0)` that can be used.

**Comment by mattjj** [comment]
> I'd also advocate against removing float0

Yes, sorry for not being clear. I'd want to fix the implementation and completeness of float0 (along the lines you described) while preserving the existing API.
