### ISSUE TITLE
Struggling with multiprocess in JAX

### ISSUE THREAD

**Issue by cgiovanetti** [google/jax#19467]
### Description

I'm trying to compile a piece of code on multiple CPUs and evaluate it in parallel for nested sampling.  I'm not trying to parallelize individual instances of the code; I just want to control these separate processes from the same script so I know when I can stop sampling.

I found I had to do a warmup call on each CPU in order to run the code in my nested sampling routine, otherwise it recompiled each time.  But I'm finding that the warmup call often stalls.

Here's a snippet that reproduces the error:

```
import jax
import jax.numpy as jnp
from jax import vmap

import multiprocessing

rho_g_vec = jnp.logspace(3,-14,263)

@jax.jit
def get_t(rho_g_vec):

    def k2(x):
        return jnp.where(x<3,
                    jnp.exp(-x) * (
                                    784/1615 + 2/x**2 + 3232/(1615*x) - 448*x/4845 + 5416744*x**2/190855665 
                    ),
                    jnp.exp(-x) * jnp.sqrt(jnp.pi / 2) * (x**(-0.5) + (15/8)*x**(-1.5) + (105/128)*x**(-2.5)))

    k2_vec= vmap(k2)
    
    def int_3_2(a): 
        k_plus_1_vec = jnp.arange(20) + 1
        K_terms = k2_vec(a*(k_plus_1_vec))    
        return 3 * a**2 *  jnp.sum(((-1)**(k_plus_1_vec-1)) * K_terms / k_plus_1_vec**2)

    def rho_e(T):   
        result = int_3_2(0.5/T)
        return result
    rho_e_v = vmap(rho_e)

    rho_tot_vec = rho_e_v(rho_g_vec)

    return rho_tot_vec

def warmup_process():
    return get_t(rho_g_vec)

if __name__ == "__main__":
    num_cores = 4
    processes = [multiprocessing.Process(target=warmup_process) for _ in range(num_cores)]

    for p in processes:
        p.start()
    for p in processes:
        p.join()
        print("warmed up on {0}".format(p))
```

I thought it might be a memory issue--changing the length of rho_g_vec to 262 lets everything run smoothly.  But increasing the memory per CPU from 10GB to 100GB did not make a difference.  The code runs smoothly on 1 CPU (and num_cores=1) with 10GB, but when I run on 4 CPUs as above it hangs.  Interrupting gives the following error:

```
Traceback (most recent call last):
  File "/scratch/cg3566/jaxBBNsampling/multiprocess_test.py", line 45, in <module>
    p.join()
  File "/ext3/miniconda3/lib/python3.11/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ext3/miniconda3/lib/python3.11/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ext3/miniconda3/lib/python3.11/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```
This also has to be interrupted, giving
```
Exception ignored in atexit callback: <function _exit_function at 0x14d6171dfce0>
Traceback (most recent call last):
  File "/ext3/miniconda3/lib/python3.11/multiprocessing/util.py", line 357, in _exit_function
    p.join()
  File "/ext3/miniconda3/lib/python3.11/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ext3/miniconda3/lib/python3.11/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ext3/miniconda3/lib/python3.11/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt: 
```

### What jax/jaxlib version are you using?

0.4.23 0.4.23

### Which accelerator(s) are you using?

CPU

**Comment by hawkinsp** [comment]
See, e.g., https://github.com/google/jax/issues/1805#issuecomment-561244991

JAX is incompatible with the `fork` strategy for `multiprocessing`.

Does that fix the problem?

**Comment by cgiovanetti** [comment]
Yes, thanks!  Sorry, looks like I missed that when I was searching
