### ISSUE TITLE
Error building jaxlib from source on OS X

### ISSUE THREAD

**Issue by shoyer** [google/jax#1948]
It appears that the failures stem from a 404 error for a file that Blaze attempts to download?
```
$ python build/build.py

     _   _  __  __
    | | / \ \ \/ /
 _  | |/ _ \ \  /
| |_| / ___ \/  \
 \___/_/   \/_/\_\


Bazel binary path: ./bazel-0.29.1-darwin-x86_64
Python binary path: /Users/shoyer/miniconda3/envs/jax-py37-from-scratch/bin/python
MKL-DNN enabled: yes
-march=native: no
CUDA enabled: no

Building XLA and installing it in the jaxlib source tree...
./bazel-0.29.1-darwin-x86_64 run --verbose_failures=true --config=mkl_open_source_only :install_xla_in_source_tree /Users/shoyer/dev/jax/build
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'run' from /Users/shoyer/dev/jax/.bazelrc:
  Inherited 'build' options: --repo_env PYTHON_BIN_PATH=/Users/shoyer/miniconda3/envs/jax-py37-from-scratch/bin/python --python_path=/Users/shoyer/miniconda3/envs/jax-py37-from-scratch/bin/python --repo_env TF_NEED_CUDA=0 --distinct_host_configuration=false --copt=-Wno-sign-compare -c opt --apple_platform_type=macos --macos_minimum_os=10.9 --announce_rc --define=no_aws_support=true --define=no_gcp_support=true --define=no_hdfs_support=true --define=no_kafka_support=true --define=no_ignite_support=true --define=grpc_no_ares=true --spawn_strategy=standalone --strategy=Genrule=standalone --cxxopt=-std=c++14 --host_cxxopt=-std=c++14
INFO: Found applicable config definition build:mkl_open_source_only in file /Users/shoyer/dev/jax/.bazelrc: --define=tensorflow_mkldnn_contraction_kernel=1
Loading:
Loading: 0 packages loaded
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
Analyzing: target //build:install_xla_in_source_tree (0 packages loaded, 0 targets configured)
ERROR: /private/var/tmp/_bazel_shoyer/a794d5395d236f575e2213803ea6f3e1/external/local_config_cc/BUILD:64:5: in apple_cc_toolchain rule @local_config_cc//:cc-compiler-watchos_arm64_32: Xcode version must be specified to use an Apple CROSSTOOL. If your Xcode version has changed recently, verify that "xcode-select -p" is correct and then try: "bazel shutdown" to re-run Xcode configuration
ERROR: Analysis of target '//build:install_xla_in_source_tree' failed; build aborted: Analysis of target '@local_config_cc//:cc-compiler-watchos_arm64_32' failed; build aborted
INFO: Elapsed time: 0.246s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 1 target configured)
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully (0 packages loaded, 1 target configured)
Traceback (most recent call last):
  File "build/build.py", line 351, in <module>
    main()
  File "build/build.py", line 346, in main
    shell(command)
  File "build/build.py", line 50, in shell
    output = subprocess.check_output(cmd)
  File "/Users/shoyer/miniconda3/envs/jax-py37-from-scratch/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/Users/shoyer/miniconda3/envs/jax-py37-from-scratch/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./bazel-0.29.1-darwin-x86_64', 'run', '--verbose_failures=true', '--config=mkl_open_source_only', ':install_xla_in_source_tree', '/Users/shoyer/dev/jax/build']' returned non-zero exit status 1.
```

**Comment by skye** [comment]
Stupid q: have you tried following bazel's advice?
`Xcode version must be specified to use an Apple CROSSTOOL. If your Xcode version has changed recently, verify that "xcode-select -p" is correct and then try: "bazel shutdown" to re-run Xcode configuration`

(I don't use a mac so I really have no idea what's going on here)

**Comment by shoyer** [comment]
`xcode-select -p` reports `/Library/Developer/CommandLineTools` which I'm guessing is correct.

I also have homebrew installed, which might be causing a conflict here? (This is a pretty common dev setup on OS X, though)

**Comment by hawkinsp** [comment]
I think the 404 is unrelated: that simply means we should update our version of the rules-closure repository to match the TF one. The 404 is from the TF mirror which no longer carries the version we're using. Bazel falls back to the alternative github source.

I'm not having problems on my Mac, so I'm also guessing this is related to your setup somehow.

**Comment by shoyer** [comment]
For posterity, I fixed this with the following two steps:
1. I installed bazel directly (instead of implicitly via the jaxlib build script): https://docs.bazel.build/versions/master/install-os-x.html
2. I followed [these instructions](https://stackoverflow.com/questions/45276830/xcode-version-must-be-specified-to-use-an-apple-crosstool) to fix the xcode issue:
```
bazel clean --expunge 
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
sudo xcodebuild -license
bazel clean --expunge 
```
