### ISSUE TITLE
Fori loop gradient with two arguments

### ISSUE THREAD

**Issue by hzyjerry** [google/jax#1954]
Hi Jax team,

I'm currently implementing a function with fori loop, and I would like to compute gradient with respect to two arguments using `argnums=(0, 1)`. When I do this, I receive error ` NotImplementedError: Forward-mode differentiation rule for 'while' not implemented`.

Do you have any recommendations for this? Thanks a lot!

A sample script:
```python
from jax.lax import fori_loop
from jax.ops import index_update
from jax import jit
from time import time
import jax.numpy as np
import jax

def test_fori():

    def func(all_x, x):
        N = len(all_x)
        def step(t, loop_carry):
            x, all_x = loop_carry
            all_x = index_update(all_x, t, x)
            return x, all_x
        _, all_x = fori_loop(0, N, step, (x, all_x))
        return all_x.sum()

    all_x = np.zeros((50, 2))
    x = np.array([1., 2.])
    func = jit(func)
    t1 = time()
    func(all_x, x)
    print(f"time {time() - t1:.3f}")
    t1 = time()
    func(all_x, x)
    print(f"time {time() - t1:.3f}")
    grad = jax.grad(func, argnums=(0, 1))
    print(grad(all_x, x)) #  NotImplementedError: Forward-mode differentiation rule for 'while' not implemented

test_fori()
```

Here are the error messages:
```
Traceback (most recent call last):
  File "tests/optim/test_jax.py", line 31, in <module>
    test_fori()
  File "tests/optim/test_jax.py", line 29, in test_fori
    print(grad(all_x, x)) #  NotImplementedError: Forward-mode differentiation rule for 'while' not implemented
  File "/Users/jerry/anaconda3/envs/saferew/lib/python3.6/site-packages/jax/api.py", line 347, in grad_f
    _, g = value_and_grad_f(*args, **kwargs)
  File "/Users/jerry/anaconda3/envs/saferew/lib/python3.6/site-packages/jax/api.py", line 402, in value_and_grad_f
    ans, vjp_py = vjp(f_partial, *dyn_args)
  File "/Users/jerry/anaconda3/envs/saferew/lib/python3.6/site-packages/jax/api.py", line 1261, in vjp
    out_primal, out_vjp = ad.vjp(flat_fun, primals_flat)
  File "/Users/jerry/anaconda3/envs/saferew/lib/python3.6/site-packages/jax/interpreters/ad.py", line 108, in vjp
    out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
  File "/Users/jerry/anaconda3/envs/saferew/lib/python3.6/site-packages/jax/interpreters/ad.py", line 97, in linearize
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr(jvpfun_flat, in_pvals)
  File "/Users/jerry/anaconda3/envs/saferew/lib/python3.6/site-packages/jax/interpreters/partial_eval.py", line 310, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/Users/jerry/anaconda3/envs/saferew/lib/python3.6/site-packages/jax/linear_util.py", line 153, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/jerry/anaconda3/envs/saferew/lib/python3.6/site-packages/jax/api.py", line 150, in f_jitted
    out = xla.xla_call(flat_fun, *args_flat, device=device, backend=backend)
  File "/Users/jerry/anaconda3/envs/saferew/lib/python3.6/site-packages/jax/core.py", line 595, in call_bind
    outs = map(full_lower, top_trace.process_call(primitive, f, tracers, params))
  File "/Users/jerry/anaconda3/envs/saferew/lib/python3.6/site-packages/jax/interpreters/ad.py", line 235, in process_call
    result = call_primitive.bind(f_jvp, *(primals + nonzero_tangents), **params)
  File "/Users/jerry/anaconda3/envs/saferew/lib/python3.6/site-packages/jax/core.py", line 595, in call_bind
    outs = map(full_lower, top_trace.process_call(primitive, f, tracers, params))
  File "/Users/jerry/anaconda3/envs/saferew/lib/python3.6/site-packages/jax/interpreters/partial_eval.py", line 111, in process_call
    out_flat = call_primitive.bind(fun, *in_consts, **params)
  File "/Users/jerry/anaconda3/envs/saferew/lib/python3.6/site-packages/jax/core.py", line 592, in call_bind
    outs = primitive.impl(f, *args, **params)
  File "/Users/jerry/anaconda3/envs/saferew/lib/python3.6/site-packages/jax/interpreters/xla.py", line 375, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, *map(abstractify, args))
  File "/Users/jerry/anaconda3/envs/saferew/lib/python3.6/site-packages/jax/linear_util.py", line 209, in memoized_fun
    ans = call(fun, *args)
  File "/Users/jerry/anaconda3/envs/saferew/lib/python3.6/site-packages/jax/interpreters/xla.py", line 391, in _xla_callable
    jaxpr, (pvals, consts, env) = pe.trace_to_subjaxpr(fun, master, False).call_wrapped(pvals)
  File "/Users/jerry/anaconda3/envs/saferew/lib/python3.6/site-packages/jax/linear_util.py", line 153, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "tests/optim/test_jax.py", line 16, in func
    _, all_x = fori_loop(0, N, step, (x, all_x))
  File "/Users/jerry/anaconda3/envs/saferew/lib/python3.6/site-packages/jax/lax/lax_control_flow.py", line 142, in fori_loop
    (lower, upper, init_val))
  File "/Users/jerry/anaconda3/envs/saferew/lib/python3.6/site-packages/jax/lax/lax_control_flow.py", line 209, in while_loop
    body_nconsts=len(body_consts), body_jaxpr=body_jaxpr)
  File "/Users/jerry/anaconda3/envs/saferew/lib/python3.6/site-packages/jax/core.py", line 153, in bind
    out_tracer = top_trace.process_primitive(self, tracers, kwargs)
  File "/Users/jerry/anaconda3/envs/saferew/lib/python3.6/site-packages/jax/interpreters/ad.py", line 222, in process_primitive
    .format(primitive))
NotImplementedError: Forward-mode differentiation rule for 'while' not implemented
```

**Comment by hzyjerry** [comment]
It seems that the problem is not due to having two arguments, but doing
```python
all_x = index_update(all_x, t, x)
```
inside fori_loop. This somehow prevents taking gradient w.r.t. `x`

**Comment by hzyjerry** [comment]
It seems that `jax.lax.scan` provides the functionality needed. For future reference, here are two linear dynamics system implemented using `fori_loop` (gradient doesn't work) and `scan` (gradient works)


```python
from jax.lax import fori_loop, scan
from jax.ops import index_update
from jax import jit
from time import time
import jax.numpy as np
import jax

def test_fori():

    def rollout(x, us, A, B):
        N = len(us)
        outs = np.zeros((len(us), len(x)))
        def step(t, carry):
            outs, last_x = carry
            u = us[t]
            next_x = A @ last_x + B @ u
            outs = index_update(outs, t, next_x)
            return outs, next_x
        fori_loop(0, N, step, (outs, x))
        return np.sum(np.square(outs))

    A = np.array([[7., 0.5], [0.5, 0.8]])
    B = np.array([[0.4, 1.2]])
    x = np.ones(2)
    us = np.ones((10, 2))
    out = rollout(x, us, A, B)

    #grad = jax.grad(rollout, argnums=(0, 1)) # NotImplementedError: Forward-mode differentiation rule for 'while' not implemented
    #gout = grad(x, us, A, B)
    #print(gout)

test_fori()

def test_scan():
    def rollout(x, us, A, B):
        def step(carry, u):
            # system dyamics
            next_x = A @ carry + B @ u
            carry = next_x
            return carry, next_x
        _, outs = scan(step, x, us)
        return np.square(outs).sum()

    A = np.array([[7., 0.5], [0.5, 0.8]])
    B = np.array([[0.4, 1.2]])
    x = np.ones(2)
    us = np.ones((10, 2))
    out = rollout(x, us, A, B)

    grad = jax.grad(rollout, argnums=(0, 1))
    gout = grad(x, us, A, B)
    print(gout)

test_scan()
```

**Comment by mzoghi-tfr** [comment]
I just wanted to point out that this code doesn't raise an exception anymore, although there seems to be a bug in the first part and the gradient comes out 0.

To be clear, this is the code I ran:

```python
from jax.lax import fori_loop, scan
from jax.ops import index_update
from jax import jit
from time import time
import jax.numpy as np
import jax

def test_fori():

  def rollout(x, us, A, B):
    N = len(us)
    outs = np.zeros((len(us), len(x)))
    def step(t, carry):
      outs, last_x = carry
      u = us[t]
      next_x = A @ last_x + B @ u
      outs = index_update(outs, t, next_x)
      return outs, next_x
    fori_loop(0, N, step, (outs, x))
    return np.sum(np.square(outs))

  A = np.array([[7., 0.5], [0.5, 0.8]])
  B = np.array([[0.4, 1.2]])
  x = np.ones(2)
  us = np.ones((10, 2))
  out = rollout(x, us, A, B)

  grad = jax.grad(rollout, argnums=(0, 1)) # NotImplementedError: Forward-mode differentiation rule for 'while' not implemented
  gout = grad(x, us, A, B)
  print(gout)

test_fori()

def test_scan():

  def rollout(x, us, A, B):
    def step(carry, u):
      # system dyamics
      next_x = A @ carry + B @ u
      carry = next_x
      return carry, next_x
    _, outs = scan(step, x, us)
    return np.square(outs).sum()

  A = np.array([[7., 0.5], [0.5, 0.8]])
  B = np.array([[0.4, 1.2]])
  x = np.ones(2)
  us = np.ones((10, 2))
  out = rollout(x, us, A, B)

  grad = jax.grad(rollout, argnums=(0, 1))
  gout = grad(x, us, A, B)
  print(gout)

test_scan()
```

and this is what I got:

(DeviceArray([0., 0.], dtype=float32), DeviceArray([[0., 0.],
             [0., 0.],
             [0., 0.],
             [0., 0.],
             [0., 0.],
             [0., 0.],
             [0., 0.],
             [0., 0.],
             [0., 0.],
             [0., 0.]], dtype=float32))
(DeviceArray([2.4783633e+17, 1.9858477e+16], dtype=float32), DeviceArray([[1.5209793e+16, 4.5629380e+16],
             [2.1604624e+15, 6.4813875e+15],
             [3.0688108e+14, 9.2064329e+14],
             [4.3590667e+13, 1.3077201e+14],
             [6.1918004e+12, 1.8575402e+13],
             [8.7950911e+11, 2.6385273e+12],
             [1.2492913e+11, 3.7478741e+11],
             [1.7745312e+10, 5.3235933e+10],
             [2.5196127e+09, 7.5588383e+09],
             [3.5081802e+08, 1.0524540e+09]], dtype=float32))

**Comment by mattjj** [comment]
@mzoghi-tfr thanks! So, just to be clear, is there a bug here?

**Comment by soraros** [comment]
I believe there is no bug here. The difference is due to the result of `fori_loop` never being assigned to any variable.

**Comment by mzoghi-tfr** [comment]
@soraros, thank you for pointing that out: I updated my comment. @mattjj, I was just trying to point out that fori_loop works with grad now: I didn't mean a bug in JAX, but a bug in the code pasted above. Sorry for the confusion.

Also, @mattjj, I added the above comment here because when I googled "jax fori_loop grad" all the results (including this one and the ["common gotchas" colab](https://colab.research.google.com/github/google/jax/blob/main/docs/notebooks/Common_Gotchas_in_JAX.ipynb#scrollTo=SipXS5qiqk8e)) were suggesting that grad does not work with fori_loop. To give a bit of context, I'm trying to add a JAX backend to an RL library that computes gradients on sequences of actions (using tf.while_loop with a finite horizon in the current implementation). But, when I was looking into fori_loop, I started freaking out because it seemed (based on all the chatter online) that replacing tf.while_loop with jax.lax.fori_loop would result in the loss of the main functionality of the library. But, it seems (based on my very limited investigation) that that's not an issue anymore. Could you please let me know if I'm mistaken? Thanks!

P.S. I'd be happy to share more info about the specific library I'm working on if you want to look into the details.
