### ISSUE TITLE
CUDA driver not found after installing with cuda12_local wheel

### ISSUE THREAD

**Issue by Tianyue-Zhao** [google/jax#19655]
### Description

```
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from jax.lib import xla_bridge
2024-02-04 13:19:26.381840: I external/tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-02-04 13:19:26.399021: I external/tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-02-04 13:19:26.399574: I external/tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
>>> exit()
```
The above output was encountered after installing JAX on WSL2 (Ubuntu 22.04) with the cuda12_local wheel.  
Specifically, the command to install JAX was:  
`pip3 install --upgrade "jax[cuda12_local]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`

Prior to running the pip install command, I have installed the CUDA 12.3 and CuDNN 8.9.  
CUDA was installed the standard WSL way (with driver on host Windows machine and rest of CUDA in the Linux system).  
From the JAX installation page, I gather that the wheel installed is for CUDA 12.2 and CuDNN 8.9, but CUDA 12.3 should also work due to having the same major version and a newer minor version.

I have checked that `/usr/local/cuda-12.3/bin` is in PATH, and that `/usr/local/cuda-12.3/lib64` is in LD_LIBRARY_PATH.

Is this combination of CUDA, CuDNN, and JAX supported? Please advise on the recommended way to run JAX with GPU on WSL2. 
 Thanks!

### What jax/jaxlib version are you using?

0.4.23, 0.4.23

### Which accelerator(s) are you using?

GPU

### NVIDIA GPU info

```
Sun Feb  4 13:23:16 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.29.04              Driver Version: 546.17       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3080        On  | 00000000:01:00.0  On |                  N/A |
|  0%   48C    P5              52W / 320W |   1072MiB / 10240MiB |      2%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A        32      G   /Xwayland                                 N/A      |
+---------------------------------------------------------------------------------------+
```

**Comment by epignatelli** [comment]
@jakevdp Same here, on multiple machines.
The latest working version for me is `0.4.23`, both using local cuda and pip-installed cuda.

### Reproduce
`pip install "jax[cuda12_pip]"==0.4.24 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`

With `python -c "import jax; jax.devices('gpu')", I get:
```
CUDA backend failed to initialize: Found cuBLAS version 120205, but JAX was built against version 120304, which is newer. The copy of cuBLAS that is installed must be at least as new as the version against which JAX was built. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/uceeepi/miniforge3/envs/navix/lib/python3.10/site-packages/jax/_src/xla_bridge.py", line 872, in devices
    return get_backend(backend).devices()
  File "/home/uceeepi/miniforge3/envs/navix/lib/python3.10/site-packages/jax/_src/xla_bridge.py", line 806, in get_backend
    return _get_backend_uncached(platform)
  File "/home/uceeepi/miniforge3/envs/navix/lib/python3.10/site-packages/jax/_src/xla_bridge.py", line 788, in _get_backend_uncached
    platform = canonicalize_platform(platform)
  File "/home/uceeepi/miniforge3/envs/navix/lib/python3.10/site-packages/jax/_src/xla_bridge.py", line 614, in canonicalize_platform
    raise RuntimeError(f"Unknown backend: '{platform}' requested, but no "
RuntimeError: Unknown backend: 'gpu' requested, but no platforms that are instances of gpu are present. Platforms present are: cpu
```

### Machine
`nvcc --version`
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0
```
`nvidia-smi`
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
```

**Comment by a2975667** [comment]
similiar issue with 12.5. 
Error I got says  jax 0.4.28 does not provide the extra 'cuda12-local'

**Comment by rajasekharporeddy** [comment]
Hi @Tianyue-Zhao, @a2975667

I have tested the issue with latest JAX cuda local version 0.4.33 on WSL with NVIDIA RTX A5000 GPU. I could not reproduce the issue. The `xla_bridge` was imported successfully. Please find the attached screeshot for reference:

![image](https://github.com/user-attachments/assets/c6bac159-c9af-457e-8d2f-57a51534547f)
![image](https://github.com/user-attachments/assets/8a7a9f7a-9b59-4eca-9155-b1a06262783c)

Could you please verify the issue with latest JAX cuda local version, if the issue still exists?

Thank you.
