### ISSUE TITLE
AttributeError message on jax.random.KeyArray

### ISSUE THREAD

**Issue by eblur** [google/jax#19812]
### Description

Hello, I am working with a student in order to install a package that with jax dependencies. Our current version is jax 0.4.24

There is an AttributeError thrown for a call to jax.random.KeyArray. The full error message is below.

```
import harmonic as hm
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/usr/local/anaconda/envs/harmonic_env/lib/python3.9/site-packages/harmonic/_init_.py", line 5, in <module>
  from . import model
 File "/usr/local/anaconda/envs/harmonic_env/lib/python3.9/site-packages/harmonic/model.py", line 3, in <module>
  from harmonic import flows
 File "/usr/local/anaconda/envs/harmonic_env/lib/python3.9/site-packages/harmonic/flows.py", line 6, in <module>
  import distrax
 File "/usr/local/anaconda/envs/harmonic_env/lib/python3.9/site-packages/distrax/_init_.py", line 20, in <module>
  from distrax._src.bijectors.block import Block
 File "/usr/local/anaconda/envs/harmonic_env/lib/python3.9/site-packages/distrax/_src/bijectors/block.py", line 20, in <module>
  from distrax._src.utils import conversion
 File "/usr/local/anaconda/envs/harmonic_env/lib/python3.9/site-packages/distrax/_src/utils/conversion.py", line 19, in <module>
  import chex
 File "/usr/local/anaconda/envs/harmonic_env/lib/python3.9/site-packages/chex/_init_.py", line 17, in <module>
  from chex._src.asserts import assert_axis_dimension
 File "/usr/local/anaconda/envs/harmonic_env/lib/python3.9/site-packages/chex/_src/asserts.py", line 26, in <module>
  from chex._src import asserts_internal as _ai
 File "/usr/local/anaconda/envs/harmonic_env/lib/python3.9/site-packages/chex/_src/asserts_internal.py", line 34, in <module>
  from chex._src import pytypes
 File "/usr/local/anaconda/envs/harmonic_env/lib/python3.9/site-packages/chex/_src/pytypes.py", line 54, in <module>
  PRNGKey = jax.random.KeyArray
 File "/usr/local/anaconda/envs/harmonic_env/lib/python3.9/site-packages/jax/_src/deprecations.py", line 53, in getattr
  raise AttributeError(f"module {module!r} has no attribute {name!r}")
AttributeError: module 'jax.random' has no attribute 'KeyArray'
```

### System info (python version, jaxlib version, accelerator, etc.)

Python 3.9.18

### Jax environment info

```
$ python3
Python 3.9.18 (main, Sep 11 2023, 08:38:23)
[Clang 14.0.6 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jax
>>> jax.print_environment_info()
jax:  0.4.24
jaxlib: 0.4.24
numpy: 1.22.4
python: 3.9.18 (main, Sep 11 2023, 08:38:23) [Clang 14.0.6 ]
jax.devices (1 total, 1 local): [CpuDevice(id=0)]
process_count: 1
```

### Conda environment

```
> conda list
# packages in environment at /usr/local/anaconda/envs/harmonic_env:
#
# Name          Version          Build Channel
absl-py          2.1.0          pypi_0  pypi
anyio           4.2.0          pypi_0  pypi
appnope          0.1.4          pypi_0  pypi
argon2-cffi        23.1.0          pypi_0  pypi
argon2-cffi-bindings   21.2.0          pypi_0  pypi
arrow           1.3.0          pypi_0  pypi
asttokens         2.4.1          pypi_0  pypi
async-lru         2.0.4          pypi_0  pypi
attrs           23.2.0          pypi_0  pypi
babel           2.14.0          pypi_0  pypi
beautifulsoup4      4.12.3          pypi_0  pypi
bleach          6.1.0          pypi_0  pypi
ca-certificates      2023.12.12      hecd8cb5_0
certifi          2024.2.2         pypi_0  pypi
cffi           1.16.0          pypi_0  pypi
charset-normalizer    3.3.2          pypi_0  pypi
chex           0.1.7          pypi_0  pypi
cloudpickle        3.0.0          pypi_0  pypi
colorlog         6.8.2          pypi_0  pypi
comm           0.2.1          pypi_0  pypi
contourpy         1.2.0          pypi_0  pypi
cycler          0.12.1          pypi_0  pypi
cython          3.0.8          pypi_0  pypi
debugpy          1.8.1          pypi_0  pypi
decorator         5.1.1          pypi_0  pypi
defusedxml        0.7.1          pypi_0  pypi
distrax          0.1.3          pypi_0  pypi
dm-tree          0.1.8          pypi_0  pypi
emcee           3.1.4          pypi_0  pypi
etils           1.5.2          pypi_0  pypi
exceptiongroup      1.2.0          pypi_0  pypi
executing         2.0.1          pypi_0  pypi
fastjsonschema      2.19.1          pypi_0  pypi
flax           0.8.1          pypi_0  pypi
fonttools         4.48.1          pypi_0  pypi
fqdn           1.5.1          pypi_0  pypi
fsspec          2024.2.0         pypi_0  pypi
gast           0.5.4          pypi_0  pypi
getdist          1.4.7          pypi_0  pypi
h11            0.14.0          pypi_0  pypi
harmonic         1.2.0          pypi_0  pypi
httpcore         1.0.2          pypi_0  pypi
httpx           0.26.0          pypi_0  pypi
idna           3.6           pypi_0  pypi
importlib-metadata    7.0.1          pypi_0  pypi
importlib-resources    6.1.1          pypi_0  pypi
ipykernel         6.29.2          pypi_0  pypi
ipython          8.18.1          pypi_0  pypi
ipywidgets        8.1.2          pypi_0  pypi
isoduration        20.11.0         pypi_0  pypi
jax            0.4.24          pypi_0  pypi
jaxlib          0.4.24          pypi_0  pypi
jedi           0.19.1          pypi_0  pypi
jinja2          3.1.3          pypi_0  pypi
joblib          1.3.2          pypi_0  pypi
json5           0.9.14          pypi_0  pypi
jsonpointer        2.4           pypi_0  pypi
jsonschema        4.21.1          pypi_0  pypi
jsonschema-specifications 2023.12.1        pypi_0  pypi
jupyter          1.0.0          pypi_0  pypi
jupyter-client      8.6.0          pypi_0  pypi
jupyter-console      6.6.3          pypi_0  pypi
jupyter-core       5.7.1          pypi_0  pypi
jupyter-events      0.9.0          pypi_0  pypi
jupyter-lsp        2.2.2          pypi_0  pypi
jupyter-server      2.12.5          pypi_0  pypi
jupyter-server-terminals 0.5.2          pypi_0  pypi
jupyterlab        4.1.1          pypi_0  pypi
jupyterlab-pygments    0.3.0          pypi_0  pypi
jupyterlab-server     2.25.2          pypi_0  pypi
jupyterlab-widgets    3.0.10          pypi_0  pypi
kiwisolver        1.4.5          pypi_0  pypi
libcxx          14.0.6        h9765a3e_0
libffi          3.4.4        hecd8cb5_0
markdown-it-py      3.0.0          pypi_0  pypi
markupsafe        2.1.5          pypi_0  pypi
matplotlib        3.8.2          pypi_0  pypi
matplotlib-inline     0.1.6          pypi_0  pypi
mdurl           0.1.2          pypi_0  pypi
mistune          3.0.2          pypi_0  pypi
ml-dtypes         0.3.2          pypi_0  pypi
msgpack          1.0.7          pypi_0  pypi
nbclient         0.9.0          pypi_0  pypi
nbconvert         7.16.0          pypi_0  pypi
nbformat         5.9.2          pypi_0  pypi
ncurses          6.4         hcec6c5f_0
nest-asyncio       1.6.0          pypi_0  pypi
notebook         7.1.0          pypi_0  pypi
notebook-shim       0.2.3          pypi_0  pypi
numpy           1.22.4          pypi_0  pypi
openssl          3.0.13        hca72f7f_0
opt-einsum        3.3.0          pypi_0  pypi
optax           0.1.9          pypi_0  pypi
orbax-checkpoint     0.5.3          pypi_0  pypi
overrides         7.7.0          pypi_0  pypi
packaging         23.2           pypi_0  pypi
pandocfilters       1.5.1          pypi_0  pypi
parso           0.8.3          pypi_0  pypi
pexpect          4.9.0          pypi_0  pypi
pillow          10.2.0          pypi_0  pypi
pip            23.3.1      py39hecd8cb5_0
platformdirs       4.2.0          pypi_0  pypi
prometheus-client     0.20.0          pypi_0  pypi
prompt-toolkit      3.0.43          pypi_0  pypi
protobuf         4.25.2          pypi_0  pypi
psutil          5.9.8          pypi_0  pypi
ptyprocess        0.7.0          pypi_0  pypi
pure-eval         0.2.2          pypi_0  pypi
pycparser         2.21           pypi_0  pypi
pygments         2.17.2          pypi_0  pypi
pyparsing         3.1.1          pypi_0  pypi
python          3.9.18        h5ee71fb_0
python-dateutil      2.8.2          pypi_0  pypi
python-json-logger    2.0.7          pypi_0  pypi
pyyaml          6.0.1          pypi_0  pypi
pyzmq           25.1.2          pypi_0  pypi
qtconsole         5.5.1          pypi_0  pypi
qtpy           2.4.1          pypi_0  pypi
readline         8.2         hca72f7f_0
referencing        0.33.0          pypi_0  pypi
requests         2.31.0          pypi_0  pypi
rfc3339-validator     0.1.4          pypi_0  pypi
rfc3986-validator     0.1.1          pypi_0  pypi
rich           13.7.0          pypi_0  pypi
rpds-py          0.18.0          pypi_0  pypi
scikit-learn       1.4.0          pypi_0  pypi
scipy           1.12.0          pypi_0  pypi
send2trash        1.8.2          pypi_0  pypi
setuptools        68.0.0          pypi_0  pypi
six            1.16.0          pypi_0  pypi
sniffio          1.3.0          pypi_0  pypi
soupsieve         2.5           pypi_0  pypi
sqlite          3.41.2        h6c40b1e_0
stack-data        0.6.3          pypi_0  pypi
tensorflow-probability  0.23.0          pypi_0  pypi
tensorstore        0.1.53          pypi_0  pypi
terminado         0.18.0          pypi_0  pypi
threadpoolctl       3.3.0          pypi_0  pypi
tinycss2         1.2.1          pypi_0  pypi
tk            8.6.12        h5d9f67b_0
tomli           2.0.1          pypi_0  pypi
toolz           0.12.1          pypi_0  pypi
tornado          6.4           pypi_0  pypi
tqdm           4.66.2          pypi_0  pypi
traitlets         5.14.1          pypi_0  pypi
types-python-dateutil   2.8.19.20240106     pypi_0  pypi
typing-extensions     4.9.0          pypi_0  pypi
tzdata          2023d        h04d1e81_0
uri-template       1.3.0          pypi_0  pypi
urllib3          2.2.0          pypi_0  pypi
wcwidth          0.2.13          pypi_0  pypi
webcolors         1.13           pypi_0  pypi
webencodings       0.5.1          pypi_0  pypi
websocket-client     1.7.0          pypi_0  pypi
wheel           0.41.0          pypi_0  pypi
widgetsnbextension    4.0.10          pypi_0  pypi
xz            5.4.5        h6c40b1e_0
zipp           3.17.0          pypi_0  pypi
zlib           1.2.13        h4dc903c_0
```

**Comment by jakevdp** [comment]
Hi - thanks for the question. `jax.random.KeyArray` was [deprecated in jax v0.4.16](https://jax.readthedocs.io/en/latest/changelog.html#jax-0-4-16-sept-18-2023), and [removed in jax v0.4.24](https://jax.readthedocs.io/en/latest/changelog.html#jax-0-4-24-feb-6-2024).

You can find information at those links regarding how to replace it. Please let me know if you have any further questions!

**Comment by jakevdp** [comment]
It seems like this is resolved - please let us know if you still have any questions about this!
