### ISSUE TITLE
Pallas Kernel using Smem/SReg failed to lower

### ISSUE THREAD

**Issue by tankbattle** [google/jax#20046]
### Description

Tried to write a test with kernel for scalar using Smem/SReg:
```
  def test_scalar_exp(self):
    def scalar_exp_kernel(in_smem_ref: Float, out_smem_ref: Float):
      in_sreg = in_smem_ref[0]
      out_smem_ref[...] = jnp.exp(in_sreg) + jnp.zeros([1], dtype=jnp.float32)

    x = jnp.ones([1], jnp.float32)
    out = pallas.pallas_call(
        scalar_exp_kernel,
        in_spec=[pallas.BlockSpec(memory_space=pltpu.SMEM)],
        out_spec=pallas.BlockSpec(memory_space=pltpu.SMEM),
        out_shape=jax.ShapeDtypeStruct([1], jnp.float32))(x)
    numpy.testing.assert_equal(out[0], jnp.exp(x))
```
And ran into errors. The full error is 
```
======================================================================
ERROR: test_scalar_exp (__main__.JaxTest.test_scalar_exp)
JaxTest.test_scalar_exp
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/work/99cfc82c986b79a05c676f893b555558d643/google3/runfiles/google3/third_party/py/jax/_src/pallas/mosaic/lowering.py", line 546, in lower_jaxpr_to_func
    body.func_op.verify()
mlir._mlir_libs._site_initialize.<locals>.MLIRError: Verification failed:
error: "/exp"(callsite("JaxTest.test_scalar_exp.<locals>.scalar_exp_kernel"("experimental/users/wuxiao/try_jax/jax_playground_test.py":94:26) at callsite("JaxTest.test_scalar_exp"("experimental/users/wuxiao/try_jax/jax_playground_test.py":97:10) at callsite("_run_and_get_tests_result"("third_party/py/absl/testing/absltest.py":2718:19) at callsite("RunTests"("testing/pybase/googletest.py":475:18) at callsite("_run_in_app.<locals>.main_function"("third_party/py/absl/testing/absltest.py":2298:6) at callsite("_run_main"("third_party/py/absl/app.py":395:13) at callsite("run"("third_party/py/absl/app.py":473:6) at callsite("_run_in_app"("third_party/py/absl/testing/absltest.py":2300:4) at callsite("main"("testing/pybase/googletest.py":407:2) at "<module>"("experimental/users/wuxiao/try_jax/jax_playground_test.py":248:2))))))))))): 'math.exp' op operand #0 must be floating-point-like, but got 'vector<f32>'
 note: "/exp"(callsite("JaxTest.test_scalar_exp.<locals>.scalar_exp_kernel"("experimental/users/wuxiao/try_jax/jax_playground_test.py":94:26) at callsite("JaxTest.test_scalar_exp"("experimental/users/wuxiao/try_jax/jax_playground_test.py":97:10) at callsite("_run_and_get_tests_result"("third_party/py/absl/testing/absltest.py":2718:19) at callsite("RunTests"("testing/pybase/googletest.py":475:18) at callsite("_run_in_app.<locals>.main_function"("third_party/py/absl/testing/absltest.py":2298:6) at callsite("_run_main"("third_party/py/absl/app.py":395:13) at callsite("run"("third_party/py/absl/app.py":473:6) at callsite("_run_in_app"("third_party/py/absl/testing/absltest.py":2300:4) at callsite("main"("testing/pybase/googletest.py":407:2) at "<module>"("experimental/users/wuxiao/try_jax/jax_playground_test.py":248:2))))))))))): see current operation: %3 = "math.exp"(%2) <{fastmath = #arith.fastmath<none>}> : (vector<f32>) -> vector<f32>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<embedded module '_launcher'>", line 161, in run_filename_as_main
  File "<embedded module '_launcher'>", line 34, in _run_code_in_main
  File "/build/work/99cfc82c986b79a05c676f893b555558d643/google3/runfiles/google3/experimental/users/wuxiao/try_jax/jax_playground_test.py", line 248, in <module>
    googletest.main()
  File "/build/work/99cfc82c986b79a05c676f893b555558d643/google3/runfiles/google3/testing/pybase/googletest.py", line 407, in main
    absltest._run_in_app(RunTests, args, kwargs)
  File "/build/work/99cfc82c986b79a05c676f893b555558d643/google3/runfiles/google3/third_party/py/absl/testing/absltest.py", line 2300, in _run_in_app
    app.run(main=main_function)
  File "/build/work/99cfc82c986b79a05c676f893b555558d643/google3/runfiles/google3/third_party/py/absl/app.py", line 473, in run
    _run_main(main, args)
  File "/build/work/99cfc82c986b79a05c676f893b555558d643/google3/runfiles/google3/third_party/py/absl/app.py", line 395, in _run_main
    sys.exit(main(argv))
  File "/build/work/99cfc82c986b79a05c676f893b555558d643/google3/runfiles/google3/third_party/py/absl/testing/absltest.py", line 2298, in main_function
    function(argv, args, kwargs)
  File "/build/work/99cfc82c986b79a05c676f893b555558d643/google3/runfiles/google3/testing/pybase/googletest.py", line 475, in RunTests
    result, _ = absltest._run_and_get_tests_result(  # pylint: disable=protected-access
  File "/build/work/99cfc82c986b79a05c676f893b555558d643/google3/runfiles/google3/third_party/py/absl/testing/absltest.py", line 2718, in _run_and_get_tests_result
    test_program = unittest.TestProgram(*args, **kwargs)
  File "/<embedded stdlib>/unittest/main.py", line 103, in __init__
    self.runTests()
  File "/<embedded stdlib>/unittest/main.py", line 275, in runTests
    self.result = testRunner.run(self.test)
  File "/<embedded stdlib>/unittest/runner.py", line 217, in run
    test(result)
  File "/<embedded stdlib>/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/<embedded stdlib>/unittest/suite.py", line 122, in run
    test(result)
  File "/<embedded stdlib>/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/<embedded stdlib>/unittest/suite.py", line 122, in run
    test(result)
  File "/<embedded stdlib>/unittest/case.py", line 678, in __call__
    return self.run(*args, **kwds)
  File "/<embedded stdlib>/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
  File "/<embedded stdlib>/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
  File "/build/work/99cfc82c986b79a05c676f893b555558d643/google3/runfiles/google3/experimental/users/wuxiao/try_jax/jax_playground_test.py", line 97, in test_scalar_exp
    out = pallas.pallas_call(
  File "/build/work/99cfc82c986b79a05c676f893b555558d643/google3/runfiles/google3/third_party/py/jax/_src/pallas/pallas_call.py", line 562, in wrapped
    out_flat = pallas_call_p.bind(
jax._src.source_info_util.JaxStackTraceBeforeTransformation: jax._src.pallas.mosaic.lowering.LoweringException: Body failed to verify: "func.func"() <{function_type = (memref<1xf32, #tpu.memory_space<vmem>>, memref<1xf32, #tpu.memory_space<vmem>>) -> (), sym_name = "main"}> ({
^bb0(%arg0: memref<1xf32, #tpu.memory_space<vmem>>, %arg1: memref<1xf32, #tpu.memory_space<vmem>>):
  %0 = "arith.constant"() <{value = 0 : index}> : () -> index
  %1 = "vector.load"(%arg0, %0) : (memref<1xf32, #tpu.memory_space<vmem>>, index) -> vector<1xf32>
  %2 = "vector.shape_cast"(%1) : (vector<1xf32>) -> vector<f32>
  %3 = "math.exp"(%2) <{fastmath = #arith.fastmath<none>}> : (vector<f32>) -> vector<f32>
  %4 = "arith.constant"() <{value = 0.000000e+00 : f32}> : () -> f32
  %5 = "vector.broadcast"(%4) : (f32) -> vector<1xf32>
  %6 = "vector.broadcast"(%3) : (vector<f32>) -> vector<1xf32>
  %7 = "arith.addf"(%6, %5) <{fastmath = #arith.fastmath<none>}> : (vector<1xf32>, vector<1xf32>) -> vector<1xf32>
  %8 = "arith.constant"() <{value = 0 : index}> : () -> index
  %9 = "vector.load"(%arg1, %8) : (memref<1xf32, #tpu.memory_space<vmem>>, index) -> vector<1xf32>
  "vector.store"(%7, %arg1, %8) : (vector<1xf32>, memref<1xf32, #tpu.memory_space<vmem>>, index) -> ()
  "func.return"() : () -> ()
}) : () -> ()
.
This is an internal error. Please report a bug at: https://github.com/google/jax/issues/new?assignees=sharadmv.

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/build/work/99cfc82c986b79a05c676f893b555558d643/google3/runfiles/google3/experimental/users/wuxiao/try_jax/jax_playground_test.py", line 97, in test_scalar_exp
    out = pallas.pallas_call(
          ^^^^^^^^^^^^^^^^^^^
  File "/build/work/99cfc82c986b79a05c676f893b555558d643/google3/runfiles/google3/third_party/py/jax/_src/pallas/mosaic/pallas_call_registration.py", line 72, in pallas_call_tpu_lowering_rule
    mosaic_module, extra_args = lowering.lower_jaxpr_to_module(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/work/99cfc82c986b79a05c676f893b555558d643/google3/runfiles/google3/third_party/py/jax/_src/pallas/mosaic/lowering.py", line 364, in lower_jaxpr_to_module
    func_op = lower_jaxpr_to_func(ctx, jaxpr, mosaic_grid_mapping=mosaic_grid_mapping,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/work/99cfc82c986b79a05c676f893b555558d643/google3/runfiles/google3/third_party/py/jax/_src/pallas/mosaic/lowering.py", line 548, in lower_jaxpr_to_func
    raise LoweringException(
jax._src.pallas.mosaic.lowering.LoweringException: Body failed to verify: "func.func"() <{function_type = (memref<1xf32, #tpu.memory_space<vmem>>, memref<1xf32, #tpu.memory_space<vmem>>) -> (), sym_name = "main"}> ({
^bb0(%arg0: memref<1xf32, #tpu.memory_space<vmem>>, %arg1: memref<1xf32, #tpu.memory_space<vmem>>):
  %0 = "arith.constant"() <{value = 0 : index}> : () -> index
  %1 = "vector.load"(%arg0, %0) : (memref<1xf32, #tpu.memory_space<vmem>>, index) -> vector<1xf32>
  %2 = "vector.shape_cast"(%1) : (vector<1xf32>) -> vector<f32>
  %3 = "math.exp"(%2) <{fastmath = #arith.fastmath<none>}> : (vector<f32>) -> vector<f32>
  %4 = "arith.constant"() <{value = 0.000000e+00 : f32}> : () -> f32
  %5 = "vector.broadcast"(%4) : (f32) -> vector<1xf32>
  %6 = "vector.broadcast"(%3) : (vector<f32>) -> vector<1xf32>
  %7 = "arith.addf"(%6, %5) <{fastmath = #arith.fastmath<none>}> : (vector<1xf32>, vector<1xf32>) -> vector<1xf32>
  %8 = "arith.constant"() <{value = 0 : index}> : () -> index
  %9 = "vector.load"(%arg1, %8) : (memref<1xf32, #tpu.memory_space<vmem>>, index) -> vector<1xf32>
  "vector.store"(%7, %arg1, %8) : (vector<1xf32>, memref<1xf32, #tpu.memory_space<vmem>>, index) -> ()
  "func.return"() : () -> ()
}) : () -> ()
.
This is an internal error. Please report a bug at: https://github.com/google/jax/issues/new?assignees=sharadmv.
```

### System info (python version, jaxlib version, accelerator, etc.)

jax:    0.4.26
jaxlib: 0.4.26
numpy:  1.26.3
python: 3.11.7 (stable, redacted, redacted) [Clang google3-trunk (3e77871c220e4d4c91956060b15ff28e27b2b764)]
jax.devices (8 total, 8 local): [TpuDevice(id=0, process_index=0, coords=(0,0,0), core_on_chip=0) TpuDevice(id=1, process_index=0, coords=(1,0,0), core_on_chip=0) ... TpuDevice(id=6, process_index=0, coords=(2,1,0), core_on_chip=0) TpuDevice(id=7, process_index=0, coords=(3,1,0), core_on_chip=0)]
process_count: 1
platform: uname_result(system='Linux', node='jidjn4-20020a0561568bc400b000e3487a0c0e.prod.google.com', release='5.10.0-smp-1100.466.0.0', version='#1 [v5.10.0-1100.466.0.0] SMP @1706144187', machine='x86_64')

**Comment by tankbattle** [comment]
Turned out I should have used "in_specs" instead of "in_spec" when calling. 

As discussed offline, I hope the parameter mismatch can be caught more explicitly instead of returning obscure errors.

**Comment by mattjj** [comment]
That sure is a bad error message! Thanks for reporting this.
