### ISSUE TITLE
CPU: incorrect result from combo of arg donation, sharding constraint, and --xla_force_host_platform_device_count=2

### ISSUE THREAD

**Issue by dlwh** [google/jax#20088]
### Description

This test passes on GPU (1 or 2 GPUs), on CPU on MacOS M1 (with or without the XLA FLAG), and Linux CPU (without the flag)

But with the `--xla_force_host_platform_device_count=2` (or 8), on linux, on x64 CPU, the assertion fails with seemingly random garbage being returned instead. I've seen it on three different machines.

Removing the donation or the sharding constraints, or the flag makes this test past. I've instantiated other versions of this bug, but I think (hope) they're all the same.

```
(levanter) dlwh@john1:~/src/levanter$ XLA_FLAGS=--xla_force_host_platform_device_count=8 python tests/test_xx.py
Traceback (most recent call last):
  File "/juice2/u/dlwh/src/levanter/tests/test_xx.py", line 45, in <module>
    test_minimize()
  File "/juice2/u/dlwh/src/levanter/tests/test_xx.py", line 41, in test_minimize
    assert jnp.all(model0[-1] == state[-1]), f"{model0[-1]} != {state[-1]}... {model0[0]}"
AssertionError: [[ 0.00386154]
 [-0.01053566]] != [[-0.00554077]
 [ 0.02703212]]... [[-0.00099001]
 [-0.01423136]]
```

```python
 from functools import partial

import jax
import jax.numpy as jnp
from jax.sharding import Mesh, NamedSharding, PartitionSpec


def test_minimize():
    In = 2
    Out = 1

    mesh = Mesh(jax.devices(), ("devices",))

    def init_fn(key):
        k1, k2 = jax.random.split(key)

        w1 = jax.random.normal(k1, (In, Out)) * 0.02
        w2 = jax.random.normal(k2, (In, Out)) * 0.02

        # without these sharding constraints, the test passes
        w1 = jax.lax.with_sharding_constraint(w1, NamedSharding(mesh, PartitionSpec()))
        w2 = jax.lax.with_sharding_constraint(w2, NamedSharding(mesh, PartitionSpec()))
        return (w1, w2)

    # without argument donation, the test passes
    # @jax.jit
    @partial(jax.jit, donate_argnums=0)
    def init_and_merge(l2, k):
        l1, _ = init_fn(k)
        return l1, l2

    k0 = jax.random.PRNGKey(0)
    k1 = jax.random.PRNGKey(1)

    model0 = jax.jit(init_fn)(k0)

    state = init_and_merge(model0[-1], k1)

    # reinit b/c donated
    model0 = jax.jit(init_fn)(k0)
    assert jnp.all(model0[-1] == state[-1]), f"{model0[-1]} != {state[-1]}... {model0[0]}"


if __name__ == "__main__":
    test_minimize()
```

### System info (python version, jaxlib version, accelerator, etc.)

```
python -c "import jax; jax.print_environment_info()"
jax:    0.4.23
jaxlib: 0.4.23
numpy:  1.26.2
python: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
jax.devices (1 total, 1 local): [CpuDevice(id=0)]
process_count: 1
```

**Comment by yashk2810** [comment]
I can't seem to repro this in my environment:

```
In [10]: jax.print_environment_info()
jax:    0.4.25.dev20240224+f9e20d587
jaxlib: 0.4.24.dev20240120
numpy:  1.24.3
python: 3.11.7 (main, Dec  8 2023, 14:22:46) [GCC 13.2.0]
jax.devices (1 total, 1 local): [CpuDevice(id=0)]
process_count: 1
```

Can you try with jax nightly on CPU?

**Comment by yashk2810** [comment]
Commands: https://jax.readthedocs.io/en/latest/installation.html#nightly-installation

**Comment by dlwh** [comment]
yep, works fine. my bad.
