### ISSUE TITLE
Cannot serialize function that accesses namedtuple

### ISSUE THREAD

**Issue by dionhaefner** [google/jax#20134]
### Description

Repro:

```python
from collections import namedtuple
import jax.numpy as jnp
from jax.experimental.export import export, serialize, deserialize

TestTuple = namedtuple('TestTuple', ['a', 'b'])

def test_fn(x):
    return x.a

exp = export(test_fn)(TestTuple(jnp.array([1]), jnp.array([2])))
serialized = serialize(exp, vjp_order=0)
deserialized = deserialize(serialized)
```

Traceback:

```
Traceback (most recent call last):
  File "/Users/dion/codes/jax/repro.py", line 11, in <module>
    serialized = serialize(exp, vjp_order=0)
  File "/Users/dion/codes/jax/jax/experimental/export/_serialization.py", line 59, in serialize
    exported = _serialize_exported(builder, exp, vjp_order)
  File "/Users/dion/codes/jax/jax/experimental/export/_serialization.py", line 75, in _serialize_exported
    in_tree = _serialize_pytreedef(builder, exp.in_tree)
  File "/Users/dion/codes/jax/jax/experimental/export/_serialization.py", line 244, in _serialize_pytreedef
    children_vector_offset = _serialize_array(
  File "/Users/dion/codes/jax/jax/experimental/export/_serialization.py", line 144, in _serialize_array
    element_offsets = [serialize_one(builder, e) for e in elements]
  File "/Users/dion/codes/jax/jax/experimental/export/_serialization.py", line 144, in <listcomp>
    element_offsets = [serialize_one(builder, e) for e in elements]
  File "/Users/dion/codes/jax/jax/experimental/export/_serialization.py", line 244, in _serialize_pytreedef
    children_vector_offset = _serialize_array(
  File "/Users/dion/codes/jax/jax/experimental/export/_serialization.py", line 144, in _serialize_array
    element_offsets = [serialize_one(builder, e) for e in elements]
  File "/Users/dion/codes/jax/jax/experimental/export/_serialization.py", line 144, in <listcomp>
    element_offsets = [serialize_one(builder, e) for e in elements]
  File "/Users/dion/codes/jax/jax/experimental/export/_serialization.py", line 263, in _serialize_pytreedef
    raise NotImplementedError(f"serializing PyTreeDef {node_data}")
NotImplementedError: serializing PyTreeDef (<class '__main__.TestTuple'>, None)
```

Since namedtuples are natively recognized as pytree containers by JAX this should probably be in scope?

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.24
jaxlib: 0.4.24
numpy:  1.26.1
python: 3.10.13 (main, Aug 24 2023, 12:59:26) [Clang 15.0.0 (clang-1500.0.40.1)]
jax.devices (1 total, 1 local): [CpuDevice(id=0)]
process_count: 1
```

**Comment by gnecula** [comment]
It is true that JAX's pytrees support namedtuple natively, but it is not obvious that namedtuple, or any custom pytree node type, should be serializable directly. Deserialization may happen in a different Python process (or even one that is not Python ) and the particular namedtuple class may not be available there.

I'll think some more about it, but for now I recommend wrapping the function to be serialized such that it takes a dictionary argument.
