### ISSUE TITLE
Cannot divide bfloat16s in Pallas

### ISSUE THREAD

**Issue by jbuckman** [google/jax#20239]
### Description

Here is a simple Pallas kernel, a slight modification to the Quickstart kernel which does elementwise division instead of elementwise addition. When its inputs have dtype `bfloat16`, it fails at the lowering step.

```python
import jax
from jax.experimental import pallas as pl
import jax.numpy as jnp

def divide_vectors_kernel(x_ref, y_ref, o_ref):
  x, y = x_ref[...], y_ref[...]
  o_ref[...] = x / y

@jax.jit
def divide_vectors(x: jax.Array, y: jax.Array) -> jax.Array:
  return pl.pallas_call(divide_vectors_kernel,
                        out_shape=jax.ShapeDtypeStruct(x.shape, x.dtype)
                        )(x, y)

# dtype = jnp.float32  # works
dtype = jnp.bfloat16   # broken
divide_vectors(jnp.arange(8., dtype=dtype), 1.+jnp.arange(8., dtype=dtype))
```

Result:
```python
Traceback (most recent call last):
  File "/home/jacob/.cache/pypoetry/virtualenvs/testing-ozEuPuop-py3.11/lib/python3.11/site-packages/jax/_src/pallas/triton/lowering.py", line 358, in lower_jaxpr_to_triton_ir
    outvals = rule(rule_ctx, *invals, **eqn.params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jacob/.cache/pypoetry/virtualenvs/testing-ozEuPuop-py3.11/lib/python3.11/site-packages/jax/_src/pallas/triton/lowering.py", line 1093, in _div_lowering_rule
    return _floordiv(x, y)
           ^^^^^^^^^^^^^^^
  File "/home/jacob/.cache/pypoetry/virtualenvs/testing-ozEuPuop-py3.11/lib/python3.11/site-packages/jax/_src/pallas/triton/lowering.py", line 840, in _floordiv
    raise NotImplementedError(f"unsupported types: {x.type} and {y.type}")
NotImplementedError: unsupported types: tensor<8xbf16> and tensor<8xbf16>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jacob/testing/pallas_bugtest.py", line 17, in <module>
    divide_vectors(jnp.arange(8., dtype=dtype), jnp.arange(8., dtype=dtype))
  File "/home/jacob/testing/pallas_bugtest.py", line 11, in divide_vectors
    return pl.pallas_call(divide_vectors_kernel,
  File "/home/jacob/.cache/pypoetry/virtualenvs/testing-ozEuPuop-py3.11/lib/python3.11/site-packages/jax/_src/pallas/pallas_call.py", line 560, in wrapped
    out_flat = pallas_call_p.bind(
jax._src.source_info_util.JaxStackTraceBeforeTransformation: jax._src.pallas.triton.lowering.LoweringError: Exception while lowering eqn:
  a:bf16[8] = div b c
With context:
  LoweringRuleContext(context=ModuleContext(name='divide_vectors_kernel', grid_mapping=GridMapping(grid=(), block_mappings=(None, None, None), mapped_dims=(), num_index_operands=0, num_scratch_operands=0), program_ids=[]), avals_in=[ShapedArray(bfloat16[8]), ShapedArray(bfloat16[8])], avals_out=[ShapedArray(bfloat16[8])], block_infos=[None, None])
With inval types=[RankedTensorType(tensor<8xbf16>), RankedTensorType(tensor<8xbf16>)]
In jaxpr:
{ lambda ; a:MemRef<None>{bfloat16[8]} b:MemRef<None>{bfloat16[8]} c:MemRef<None>{bfloat16[8]}. let
    d:bf16[8] <- a[:]
    e:bf16[8] <- b[:]
    f:bf16[8] = div d e
    c[:] <- f
  in () }

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jacob/testing/pallas_bugtest.py", line 17, in <module>
    divide_vectors(jnp.arange(8., dtype=dtype), jnp.arange(8., dtype=dtype))
  File "/home/jacob/.cache/pypoetry/virtualenvs/testing-ozEuPuop-py3.11/lib/python3.11/site-packages/jax/_src/pallas/triton/lowering.py", line 2674, in pallas_call_lowering
    return lowering_fn(
           ^^^^^^^^^^^^
  File "/home/jacob/.cache/pypoetry/virtualenvs/testing-ozEuPuop-py3.11/lib/python3.11/site-packages/jax/_src/pallas/triton/lowering.py", line 2576, in _pallas_call_ttir_lowering
    lowering_result = lower_jaxpr_to_triton_module(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jacob/.cache/pypoetry/virtualenvs/testing-ozEuPuop-py3.11/lib/python3.11/site-packages/jax/_src/pallas/triton/lowering.py", line 315, in lower_jaxpr_to_triton_module
    () = lower_jaxpr_to_triton_ir(ctx, jaxpr, block_infos, *entry.arguments)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jacob/.cache/pypoetry/virtualenvs/testing-ozEuPuop-py3.11/lib/python3.11/site-packages/jax/_src/pallas/triton/lowering.py", line 363, in lower_jaxpr_to_triton_ir
    raise LoweringError(
jax._src.pallas.triton.lowering.LoweringError: Exception while lowering eqn:
  a:bf16[8] = div b c
With context:
  LoweringRuleContext(context=ModuleContext(name='divide_vectors_kernel', grid_mapping=GridMapping(grid=(), block_mappings=(None, None, None), mapped_dims=(), num_index_operands=0, num_scratch_operands=0), program_ids=[]), avals_in=[ShapedArray(bfloat16[8]), ShapedArray(bfloat16[8])], avals_out=[ShapedArray(bfloat16[8])], block_infos=[None, None])
With inval types=[RankedTensorType(tensor<8xbf16>), RankedTensorType(tensor<8xbf16>)]
In jaxpr:
{ lambda ; a:MemRef<None>{bfloat16[8]} b:MemRef<None>{bfloat16[8]} c:MemRef<None>{bfloat16[8]}. let
    d:bf16[8] <- a[:]
    e:bf16[8] <- b[:]
    f:bf16[8] = div d e
    c[:] <- f
  in () }
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```

### System info (python version, jaxlib version, accelerator, etc.)

```python
>>> import jax; jax.print_environment_info()
jax:    0.4.25
jaxlib: 0.4.25
numpy:  1.26.4
python: 3.11.4 (main, Dec  7 2023, 15:43:41) [GCC 12.3.0]
jax.devices (2 total, 2 local): [cuda(id=0) cuda(id=1)]
process_count: 1
platform: uname_result(system='Linux', node='jacob', release='6.2.0-39-generic', version='#40-Ubuntu SMP PREEMPT_DYNAMIC Tue Nov 14 14:18:00 UTC 2023', machine='x86_64')


$ nvidia-smi
Wed Mar 13 18:00:27 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.161.07             Driver Version: 535.161.07   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA RTX A6000               On  | 00000000:2D:00.0 Off |                  Off |
| 30%   39C    P2              35W / 300W |    269MiB / 49140MiB |      2%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA RTX A6000               On  | 00000000:41:00.0 Off |                  Off |
| 30%   41C    P2              30W / 300W |    269MiB / 49140MiB |      1%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A    318171      C   ...anifest2-ozEuPuop-py3.11/bin/python      262MiB |
|    1   N/A  N/A    318171      C   ...anifest2-ozEuPuop-py3.11/bin/python      262MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by superbobry** [comment]
Thanks for reporting! We indeed do not yet support bf16 (for no good reason, really), but it should easy to fix that.

**Comment by superbobry** [comment]
Upon further checking, [PTX has no instruction](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#floating-point-instructions-div) for dividing bf16, so there is nothing Pallas can do.

**Comment by jbuckman** [comment]
@superbobry Is there one for `log` or `lg2`? I could implement division as log, sub, exp. Right now, Pallas does not support `log` of bfloat16 either.

Also, Triton does seem to support bf16 division. Are they doing something other than PTX?

**Comment by hawkinsp** [comment]
Presumably they are doing the division in f32, because PTX doesn't have a bf16 division that I can see: https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#floating-point-instructions-div

**Comment by superbobry** [comment]
I think we might be able to support `log` etc for bfloat16, just not via libdevice. I am working on a PR doing that.

**Comment by superbobry** [comment]
@hawkinsp do you think it's reasonable for us to cast to f32 and back implicitly as well?
