### ISSUE TITLE
NumPy 2.0: `np.asarray` can leak tracers

### ISSUE THREAD

**Issue by jakevdp** [google/jax#20254]
Here's a short repro. It does not error under NumPy 1.x, but errors with NumPy v2.0.0b1. This came up in the context of checkify tests in our NumPy upstream CI job.
```python
import jax
import numpy as np

jax.config.update('jax_check_tracer_leaks', True)

def f(x):
  try:
    return np.array(x)
  except:
    return None

jax.jit(f)([1])
```
```pytb
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/vanderplas/jax_numpy_upstream/jax/tmp.py", line 12, in <module>
    jax.jit(f)([1])
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
Exception: Leaked trace MainTrace(1,DynamicJaxprTrace). Leaked tracer(s):

Traced<ShapedArray(int32[], weak_type=True)>with<DynamicJaxprTrace(level=1/0)>
This DynamicJaxprTracer was created on line /Users/vanderplas/jax_numpy_upstream/jax/tmp.py:12 (<module>)
<DynamicJaxprTracer 4310591264> is referred to by <method 4430547776>
```

**Comment by jakevdp** [comment]
Seems like a NumPy bug: `np.asarray` can leak references:
```python
import sys
import gc
import numpy as np

print(np.__version__)

class NotAnArray:
    def __array__(self):
        raise NotImplementedError()
x = NotAnArray()

print(sys.getrefcount(x))
try:
    np.asarray([x])
except:
    pass
print(sys.getrefcount(x))
gc.collect()
print(sys.getrefcount(x))
```
output under NumPy 2.0.0b1
```
2.0.0b1
2
3
4
```
output under NumPy 1.26.4:
```
1.26.4
2
2
2
```

**Comment by mattjj** [comment]
Looks like numpy/numpy#26020 is fixed, thanks Jake!
