### ISSUE TITLE
TypeError: cannot create weak reference to 'method_descriptor' object; cython cdef class; linux

### ISSUE THREAD

**Issue by mgbukov** [google/jax#2027]
I'm trying to get my jax code running on a linux cluster, and I ran into trouble (see tracebacks below). I was able to install jax w/o GPU successfully using pip.

I wonder if this is a problem with the cluster or caused by a recent update in jax, since:

i) the same code runs on my os x machine: jax (0.1.46), jaxlib (0.1.29)
ii) the code runs on another linux cluster: jax (0.1.53), jaxlib (0.1.36)
iii) the present case throwing the error has: jax (0.1.57), jaxlib (0.1.37)

Any ideas are much appreciated. 

Full traceback: jax (0.1.57), jaxlib (0.1.37)
* note that the object `DNN` in the problematic line `DNN.evaluate_phase(...)` below is an instance of a custom cython cdef class. 
* there is the possibility that cython messed something up in my custom library due to a difference in the compilers [comparing the two linux clusters], but it didn't show anything unusual during the compilation. 

```
(jax-noGPU) mgbukov@cori08:~/varqmc/simulation> python main.py 
/global/homes/m/mgbukov/miniconda3/envs/jax-noGPU/lib/python3.7/site-packages/jax/lib/xla_bridge.py:119: UserWarning: No GPU/TPU found, falling back to CPU.
  warnings.warn('No GPU/TPU found, falling back to CPU.')


ITERATION 0, PROCESS_RANK 0:


Traceback (most recent call last):
  File "/global/homes/m/mgbukov/miniconda3/envs/jax-noGPU/lib/python3.7/site-packages/jax/api.py", line 149, in f_jitted
    out = xla.xla_call(flat_fun, *args_flat, device=device, backend=backend)
  File "/global/homes/m/mgbukov/miniconda3/envs/jax-noGPU/lib/python3.7/site-packages/jax/core.py", line 602, in call_bind
    outs = primitive.impl(f, *args, **params)
  File "/global/homes/m/mgbukov/miniconda3/envs/jax-noGPU/lib/python3.7/site-packages/jax/interpreters/xla.py", line 442, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, *map(arg_spec, args))
  File "/global/homes/m/mgbukov/miniconda3/envs/jax-noGPU/lib/python3.7/site-packages/jax/linear_util.py", line 216, in memoized_fun
    cache = fun_caches.setdefault(fun.f, {})
  File "/global/homes/m/mgbukov/miniconda3/envs/jax-noGPU/lib/python3.7/weakref.py", line 489, in setdefault
    return self.data.setdefault(ref(key, self._remove),default)
TypeError: cannot create weak reference to 'method_descriptor' object
Exception ignored in: 'cpp_code.sampling_lib.Neural_Net._MC_core'
Traceback (most recent call last):
  File "/global/homes/m/mgbukov/miniconda3/envs/jax-noGPU/lib/python3.7/site-packages/jax/api.py", line 149, in f_jitted
    out = xla.xla_call(flat_fun, *args_flat, device=device, backend=backend)
  File "/global/homes/m/mgbukov/miniconda3/envs/jax-noGPU/lib/python3.7/site-packages/jax/core.py", line 602, in call_bind
    outs = primitive.impl(f, *args, **params)
  File "/global/homes/m/mgbukov/miniconda3/envs/jax-noGPU/lib/python3.7/site-packages/jax/interpreters/xla.py", line 442, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, *map(arg_spec, args))
  File "/global/homes/m/mgbukov/miniconda3/envs/jax-noGPU/lib/python3.7/site-packages/jax/linear_util.py", line 216, in memoized_fun
    cache = fun_caches.setdefault(fun.f, {})
  File "/global/homes/m/mgbukov/miniconda3/envs/jax-noGPU/lib/python3.7/weakref.py", line 489, in setdefault
    return self.data.setdefault(ref(key, self._remove),default)
TypeError: cannot create weak reference to 'method_descriptor' object
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    DNN_psi=VMC(params)
  File "../VMC_class.py", line 173, in __init__
    self.train(self.start_iter)
  File "../VMC_class.py", line 468, in train
    self.compute_batchnorm_params(self.DNN.params,len(self.shapes)+1) #
  File "../VMC_class.py", line 550, in compute_batchnorm_params
    acceptance_ratio = self.MC_tool.sample(self.DNN)
  File "../MC_lib.py", line 118, in sample
    self.phase_kets[:]=DNN.evaluate_phase(DNN.params, self.spinstates_ket.reshape(self.N_batch*self.N_symm,self.N_sites), DNN.apply_fun_args)#._value
  File "/global/homes/m/mgbukov/miniconda3/envs/jax-noGPU/lib/python3.7/site-packages/jax/api.py", line 149, in f_jitted
    out = xla.xla_call(flat_fun, *args_flat, device=device, backend=backend)
  File "/global/homes/m/mgbukov/miniconda3/envs/jax-noGPU/lib/python3.7/site-packages/jax/core.py", line 602, in call_bind
    outs = primitive.impl(f, *args, **params)
  File "/global/homes/m/mgbukov/miniconda3/envs/jax-noGPU/lib/python3.7/site-packages/jax/interpreters/xla.py", line 442, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, *map(arg_spec, args))
  File "/global/homes/m/mgbukov/miniconda3/envs/jax-noGPU/lib/python3.7/site-packages/jax/linear_util.py", line 216, in memoized_fun
    cache = fun_caches.setdefault(fun.f, {})
  File "/global/homes/m/mgbukov/miniconda3/envs/jax-noGPU/lib/python3.7/weakref.py", line 489, in setdefault
    return self.data.setdefault(ref(key, self._remove),default)
TypeError: cannot create weak reference to 'method_descriptor' object
```

I also tried downgrading jax's version to one of the above to cross-check using `pip install jax==0.1.53 jaxlib==0.1.36`, but got a different, import error:

Full traceback: jax (0.1.53), jaxlib (0.1.36)
```
(jax-noGPU) mgbukov@cori08:~/varqmc/simulation> python main.py 
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from VMC_class import VMC
  File "../VMC_class.py", line 17, in <module>
    import jax
  File "/global/homes/m/mgbukov/miniconda3/envs/jax-noGPU/lib/python3.7/site-packages/jax/__init__.py", line 20, in <module>
    from jax import nn
  File "/global/homes/m/mgbukov/miniconda3/envs/jax-noGPU/lib/python3.7/site-packages/jax/nn/__init__.py", line 17, in <module>
    from . import initializers
  File "/global/homes/m/mgbukov/miniconda3/envs/jax-noGPU/lib/python3.7/site-packages/jax/nn/initializers.py", line 28, in <module>
    from jax import random
  File "/global/homes/m/mgbukov/miniconda3/envs/jax-noGPU/lib/python3.7/site-packages/jax/random.py", line 33, in <module>
    from . import numpy as np
  File "/global/homes/m/mgbukov/miniconda3/envs/jax-noGPU/lib/python3.7/site-packages/jax/numpy/__init__.py", line 16, in <module>
    from .lax_numpy import *
  File "<frozen importlib._bootstrap>", line 1019, in _handle_fromlist
  File "/global/homes/m/mgbukov/miniconda3/envs/jax-noGPU/lib/python3.7/site-packages/jax/numpy/lax_numpy.py", line 3209, in wrapped
    raise NotImplementedError(msg.format(fun))
NotImplementedError: Numpy function <function __getattr__ at 0x2aaaacc09c20> not yet implemented
```

**Comment by mgbukov** [comment]
Just to confirm that this seems more and more like a jax issue. I just tried yet a third linux cluster and I got the same error `TypeError: cannot create weak reference to 'method_descriptor' object` (see above for full traceback).

**Comment by mgbukov** [comment]
I investigated a bit more this problem; I was wrong -- this is not an issue with jax versioning. 

The bug arises **on Linux platforms**, when jitting function methods of cython cdef classes with parameters, i.e. after using 
```
@jax.partial(jit, static_argnums=(0,2))
    def my_func(self,x,params):
        return self._my_func(x,params)
```

Looks a bit special, but it's weird that the bug occurs on linux, but not on osx. Going after it might reveal another jax problem. 


Here's a minimal example:

[bug.zip](https://github.com/google/jax/files/4124160/bug.zip)

To compile the cython code, extract and run `python setup.py build_ext -i`. Then run `main.py` to call the cython classes from python. 

The minimal cython script in `cython_code.pyx` contains two classes: a pure python class, and the cdef cython class. Both classes do the same and are structured in the exact same way. They contain a private method `_my_func()` which accepts a parameter value. This method is then partially jitted and made public as `my_func()`. In `main.py` the two classes are tested consecutively.

On mac `osx`, both the python and the cython classes work as intended. On `linux`, the cython class fails with the error message

```
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    test(obj_cy)
  File "main.py", line 10, in test
    print( obj.my_func(x,(2,)) )
  File "/home/qi/mbukov/miniconda3/envs/jax-noGPU/lib/python3.7/site-packages/jax/api.py", line 149, in f_jitted
    out = xla.xla_call(flat_fun, *args_flat, device=device, backend=backend)
  File "/home/qi/mbukov/miniconda3/envs/jax-noGPU/lib/python3.7/site-packages/jax/core.py", line 602, in call_bind
    outs = primitive.impl(f, *args, **params)
  File "/home/qi/mbukov/miniconda3/envs/jax-noGPU/lib/python3.7/site-packages/jax/interpreters/xla.py", line 442, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, *map(arg_spec, args))
  File "/home/qi/mbukov/miniconda3/envs/jax-noGPU/lib/python3.7/site-packages/jax/linear_util.py", line 216, in memoized_fun
    cache = fun_caches.setdefault(fun.f, {})
  File "/home/qi/mbukov/miniconda3/envs/jax-noGPU/lib/python3.7/weakref.py", line 489, in setdefault
    return self.data.setdefault(ref(key, self._remove),default)
TypeError: cannot create weak reference to 'method_descriptor' object
```

**Comment by hawkinsp** [comment]
I'm guessing this issue is obsolete, but if I had to guess at the fix, it would be to wrap the method you are passing to jax in another function/lambda. Please reopen if this is still causing problems for you!
