### ISSUE TITLE
DotProductAttentionTest tests failing constraints check, as well as after passing them

### ISSUE THREAD

**Issue by vladbelit** [google/jax#20438]
### Description

All the tests are failing in continuous CUDA jobs, either with the cuDNN constraints check, or after passing it.

Examples:

Constraints check passed
```
[ RUN      ] DotProductAttentionTest.test_sdpa_inference
E0326 13:26:41.794419  431866 pjrt_stream_executor_client.cc:2808] Execution of replica 0 failed: INTERNAL: No valid engine configs for Matmul_MUL_Reduction_SUB_EXP_Reduction_LOG_ADD_DIV_Matmul_
in external/xla/xla/stream_executor/cuda/cuda_dnn.cc(10398): 'graph_.create_execution_plans({cudnn_frontend::HeurMode_t::A})'
E0326 13:26:42.413864  431870 pjrt_stream_executor_client.cc:2808] Execution of replica 0 failed: INTERNAL: No valid engine configs for Matmul_MUL_Reduction_SUB_EXP_Reduction_LOG_ADD_DIV_Matmul_
in external/xla/xla/stream_executor/cuda/cuda_dnn.cc(10398): 'graph_.create_execution_plans({cudnn_frontend::HeurMode_t::A})'
E0326 13:26:42.429600  431872 pjrt_stream_executor_client.cc:2808] Execution of replica 0 failed: INTERNAL: No valid engine configs for Matmul_MUL_Reduction_SUB_EXP_Reduction_LOG_ADD_DIV_Matmul_
in external/xla/xla/stream_executor/cuda/cuda_dnn.cc(10398): 'graph_.create_execution_plans({cudnn_frontend::HeurMode_t::A})'
E0326 13:26:42.513569  431868 pjrt_stream_executor_client.cc:2808] Execution of replica 0 failed: INTERNAL: No valid engine configs for Matmul_MUL_Reduction_SUB_EXP_Reduction_LOG_ADD_DIV_Matmul_
in external/xla/xla/stream_executor/cuda/cuda_dnn.cc(10398): 'graph_.create_execution_plans({cudnn_frontend::HeurMode_t::A})'
[  FAILED  ] DotProductAttentionTest.test_sdpa_inference
[  FAILED  ] DotProductAttentionTest.test_sdpa_inference
```

Constraints check passed
```
ERROR: test_sdpa_inference (__main__.DotProductAttentionTest)
DotProductAttentionTest.test_sdpa_inference
----------------------------------------------------------------------
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/0fe1f5b2bc0694265667ca527ea660d2/execroot/__main__/bazel-out/k8-opt/bin/tests/fused_attention_stablehlo_test_gpu.runfiles/__main__/jax/_src/test_util.py", line 456, in test_method_wrapper
    return test_method(self, *args, **kwargs)
  File "/root/.cache/bazel/_bazel_root/0fe1f5b2bc0694265667ca527ea660d2/execroot/__main__/bazel-out/k8-opt/bin/tests/fused_attention_stablehlo_test_gpu.runfiles/__main__/tests/fused_attention_stablehlo_test.py", line 242, in test_sdpa_inference
    out = jitted_sdpa_inference(query, key, value, None, None)
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: No valid engine configs for Matmul_MUL_Reduction_SUB_EXP_Reduction_LOG_ADD_DIV_Matmul_
in external/xla/xla/stream_executor/cuda/cuda_dnn.cc(10398): 'graph_.create_execution_plans({cudnn_frontend::HeurMode_t::A})' : while running replica 0 and partition 0 of a replicated computation (other replicas may have failed as well).
```

Constraints check failed
```
_________________ DotProductAttentionTest.test_sdpa_inference __________________
[gw7] linux -- Python 3.9.18 /usr/local/bin/python3.9
tests/fused_attention_stablehlo_test.py:242: in test_sdpa_inference
    out = jitted_sdpa_inference(query, key, value, None, None)
jax/_src/pjit.py:298: in cache_miss
    outs, out_flat, out_tree, args_flat, jaxpr, attrs_tracked = _python_pjit_helper(
jax/_src/pjit.py:167: in _python_pjit_helper
    _infer_params(jit_info, args, kwargs)
jax/_src/pjit.py:581: in _infer_params
    jaxpr, consts, out_shardings, out_layouts_flat, attrs_tracked = _pjit_jaxpr(
jax/_src/pjit.py:1209: in _pjit_jaxpr
    jaxpr, final_consts, out_type, attrs_tracked = _create_pjit_jaxpr(
jax/_src/linear_util.py:350: in memoized_fun
    ans = call(fun, *args)
jax/_src/pjit.py:1147: in _create_pjit_jaxpr
    jaxpr, global_out_avals, consts, attrs_tracked = pe.trace_to_jaxpr_dynamic(
jax/_src/profiler.py:336: in wrapper
    return func(*args, **kwargs)
jax/_src/interpreters/partial_eval.py:2322: in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts, attrs_tracked = trace_to_subjaxpr_dynamic(
jax/_src/interpreters/partial_eval.py:2344: in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
jax/_src/linear_util.py:192: in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
jax/_src/cudnn/fused_attention_stablehlo.py:787: in dot_product_attention
    is_flash_attention = check_is_flash_attention(query, key, cudnn_version, bias is not None, is_training)
jax/_src/cudnn/fused_attention_stablehlo.py:223: in check_is_flash_attention
    raise RuntimeError("JAX requires cuDNN >= 8.9.4 to use flash cross attention.")
E   RuntimeError: JAX requires cuDNN >= 8.9.4 to use flash cross attention.
```

### System info (python version, jaxlib version, accelerator, etc.)

Python: any supported version
Jaxlib version: built from head

**Comment by vladbelit** [comment]
@Cjkkkk
Hi Shanbin, please take a look.

**Comment by Cjkkkk** [comment]
What is the cuDNN version and GPU?

**Comment by Cjkkkk** [comment]
I should also add check to only use this for A100/H100. I guess the testing gpu is not one of these two?

**Comment by vladbelit** [comment]
They are currently T4. I think they will be getting moved to L4 soonish. Possibly, in some environments, these tests may be running on A100s/H100s. @hawkinsp

**Comment by vladbelit** [comment]
This looks fixed, thanks

**Comment by guyujun** [comment]
```
    self.params, self.opt_state, self.accumu_g, aux = jax.pmap(train_step, in_axes=(0,0,0,0,0,0,None), axis_name="pbatch",
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: No valid engine configs for Matmul_MUL_GEN_INDEX_GEN_INDEX_CMP_GE_BINARY_SELECT_Reduction_SUB_EXP_Reduction_LOG_ADD_DIV_Matmul_
in external/xla/xla/stream_executor/cuda/cuda_dnn.cc(8426): 'graph_.create_execution_plans({cudnn_frontend::HeurMode_t::A})' 
```

run training using PMAP and RTX4090 not works, any comments?
