### ISSUE TITLE
Install failed when using pip for JAX and CUDA

### ISSUE THREAD

**Issue by evanatyourservice** [google/jax#20455]
### Description

Hello JAX team! Seems installing JAX and CUDA through pip (the easier path form the jax install page) is broken today, raising this error part way through:

```
...
Collecting nvidia-cudnn-cu12>=8.9.7.29 (from jax[cuda12_pip])
  Using cached nvidia_cudnn_cu12-9.0.0.312.tar.gz (885 bytes)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
        File "/tmp/pip-build-env-45n6rx2x/overlay/local/lib/python3.10/dist-packages/nvidia_stub/wheel.py", line 146, in download_wheel
          return download_manual(wheel_directory, distribution, version)
        File "/tmp/pip-build-env-45n6rx2x/overlay/local/lib/python3.10/dist-packages/nvidia_stub/wheel.py", line 113, in download_manual
          raise RuntimeError(f"Didn't find wheel for {distribution} {version}")
      Traceback (most recent call last):
        File "/tmp/pip-build-env-45n6rx2x/overlay/local/lib/python3.10/dist-packages/nvidia_stub/wheel.py", line 146, in download_wheel
          return download_manual(wheel_directory, distribution, version)
        File "/tmp/pip-build-env-45n6rx2x/overlay/local/lib/python3.10/dist-packages/nvidia_stub/wheel.py", line 113, in download_manual
          raise RuntimeError(f"Didn't find wheel for {distribution} {version}")
      RuntimeError: Didn't find wheel for nvidia-cudnn-cu12 9.0.0.312
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-build-env-45n6rx2x/overlay/local/lib/python3.10/dist-packages/nvidia_stub/buildapi.py", line 29, in build_wheel
          return download_wheel(pathlib.Path(wheel_directory), config_settings)
        File "/tmp/pip-build-env-45n6rx2x/overlay/local/lib/python3.10/dist-packages/nvidia_stub/wheel.py", line 148, in download_wheel
          report_install_failure(distribution, version, exception_context)
        File "/tmp/pip-build-env-45n6rx2x/overlay/local/lib/python3.10/dist-packages/nvidia_stub/error.py", line 63, in report_install_failure
          raise InstallFailedError(
      nvidia_stub.error.InstallFailedError:
      *******************************************************************************
      
      The installation of nvidia-cudnn-cu12 for version 9.0.0.312 failed.
      
      This is a special placeholder package which downloads a real wheel package
      from https://pypi.nvidia.com. If https://pypi.nvidia.com is not reachable, we
      cannot download the real wheel file to install.
      
      You might try installing this package via
      ```
      $ pip install --extra-index-url https://pypi.nvidia.com nvidia-cudnn-cu12
      ```
      
      Here is some debug information about your platform to include in any bug
      report:
      
      Python Version: CPython 3.10.12
      Operating System: Linux 5.4.0-166-generic
      CPU Architecture: x86_64
      Driver Version: 535.113
      CUDA Version: 12.2
      
      *******************************************************************************
```

Looks like the cause is that there isn't a "manylinux" wheel here from nvidia, only an amd64, for version 9 https://pypi.nvidia.com/nvidia-cudnn-cu12/

Is there an easy way to force 8.9 in the meantime?

### System info (python version, jaxlib version, accelerator, etc.)

      Python Version: CPython 3.10.12
      Operating System: Linux 5.4.0-166-generic
      CPU Architecture: x86_64
      Driver Version: 535.113
      CUDA Version: 12.2

**Comment by hawkinsp** [comment]
Yeah, I think NVIDIA's cudnn wheel is broken on pypi at the moment. We can't fix that, but NVIDIA are aware of it and working on it.

Workaround: just manually install `cudnn` first like this:

```
pip install nvidia-cudnn-cu12==8.9.7.29
```

**Comment by evanatyourservice** [comment]
Gotcha thanks for the quick reply, I didn't notice the 8.9.7.29 wheel was still trying to install 9.0 so doing pip install nvidia_cudnn_cu12==8.9.7.29 beforehand worked

**Comment by hawkinsp** [comment]
Actually it occurs to me we should have had an upper bound on our version constraint as well, since 9.0 might not be ABI compatible with 8.9. I'll fix that for the next JAX release.

**Comment by evanatyourservice** [comment]
nvidia has all the 9.0 wheels available now but i suppose the issue could stay open if you're going to upper bound versions?

**Comment by evanatyourservice** [comment]
Actually it turned out jax didn't recognize GPUs with cudnn 9.0, got the couldn't load cudnn warning and jax.devices only listed the CPU device, but when I installed 8.9 (and it uninstalled 9.0) it worked like normal

**Comment by hawkinsp** [comment]
https://github.com/google/jax/pull/20476 adds the upper bound constraint on cudnn, but until we make a release folks are going to keep hitting this issue. I'll leave it open for now.

**Comment by hawkinsp** [comment]
The 0.4.26 release (on pypi now) adds an upper bound constraint.
