### ISSUE TITLE
Automatic sharded parallelization of per-sample gradients fails on GPUs

### ISSUE THREAD

**Issue by MScherbela** [google/jax#20710]
### Description

The following minimal example works when run on 2 CPUs (CUDA_VISBLE_DEVICES=""), but fails when run on GPUs due to **Unexpected XLA sharding override**.

```python
import os
# os.environ["CUDA_VISIBLE_DEVICES"] = "" # Uncomment to run on CPU, in which case the code works
os.environ["XLA_FLAGS"] = "--xla_force_host_platform_device_count=2"

import jax
from jax.experimental import mesh_utils
from jax.sharding import PositionalSharding
import jax.numpy as jnp
import jax.distributed

def model(params, x):
    return x @ params

if __name__ == "__main__":
    jax.print_environment_info()
    print("Devices: ", jax.devices())
    n_devices = jax.device_count()  # 2
    devices = mesh_utils.create_device_mesh((n_devices,))
    sharding = PositionalSharding(devices)

    feature_dim = 3
    batch_size_total = 8

    # Get example data
    x = jnp.ones((batch_size_total,  feature_dim))
    params = jnp.ones(feature_dim)

    # Shard data, replicate params
    x = jax.device_put(x, sharding.reshape(n_devices, 1))
    params = jax.device_put(params, sharding.replicate(axis=0))

    y = model(params, x)
    print("Forward pass (with vectorizable function) works")

    y = jax.vmap(model, in_axes=(None, 0))(params, x)
    print("Forward pass with explicit vmap also works")

    grad = jax.grad(lambda p: model(p, x).sum())(params)
    print("Gradient of global function works")

    per_sample_grads = jax.vmap(jax.grad(model), in_axes=(None, 0))(params, x)
    print("This is never reached: per-sample gradients combining vmap and grad fails when run on GPUs")
```

It appears to be specific to the combination of vmap and grad, and does not appear when using only vmap or only grad.
In case of failure the output is:

```
Devices:  [cuda(id=0), cuda(id=1)]
Forward pass (with vectorizable function) works
Forward pass with explicity vmap also works
Gradient of global function works
Traceback (most recent call last):
  File "/home/scherbelam20/develop/sparse_wf/sparse_wf/preliminary_experiments/parallelization/per_sample_gradients/per_sample_gradients.py", line 41, in <module>
    per_sample_grads = jax.vmap(jax.grad(model), in_axes=(None, 0))(params, x)
  File "/home/scherbelam20/develop/sparse_wf/sparse_wf/preliminary_experiments/parallelization/per_sample_gradients/per_sample_gradients.py", line 12, in model
    return x @ params
  File "/home/scherbelam20/.conda/envs/sparse_wf/lib/python3.12/site-packages/jax/_src/numpy/array_methods.py", line 736, in op
    return getattr(self.aval, f"_{name}")(self, *args)
  File "/home/scherbelam20/.conda/envs/sparse_wf/lib/python3.12/site-packages/jax/_src/numpy/array_methods.py", line 264, in deferring_binary_op
    return binary_op(*args)
jax._src.source_info_util.JaxStackTraceBeforeTransformation: AssertionError: Unexpected XLA sharding override: (XLA) GSPMDSharding({replicated}) != PositionalSharding([[{GPU 0}]
                    [{GPU 1}]], shape=(2, 1)) (User sharding)
```

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.26
jaxlib: 0.4.26
numpy:  1.26.4
python: 3.12.2 | packaged by Anaconda, Inc. | (main, Feb 27 2024, 17:35:02) [GCC 11.2.0]
jax.devices (2 total, 2 local): [cuda(id=0) cuda(id=1)]
process_count: 1
platform: uname_result(system='Linux', node='gpu1-mat', release='5.15.0-1054-oracle', version='#60~20.04.1-Ubuntu SMP Wed Mar 20 22:29:27 UTC 2024', machine='x86_64')


$ nvidia-smi
Thu Apr 11 13:27:11 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-40GB          Off |   00000000:07:00.0 Off |                    0 |
| N/A   28C    P0             57W /  400W |     425MiB /  40960MiB |      3%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA A100-SXM4-40GB          Off |   00000000:0A:00.0 Off |                    0 |
| N/A   25C    P0             57W /  400W |     425MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A    559574      C   python                                        416MiB |
|    1   N/A  N/A    559574      C   python                                        416MiB |
+-----------------------------------------------------------------------------------------+
```

**Comment by yashk2810** [comment]
I was able to repro this and have filed an internal bug. It should be fixed soon :)

**Comment by yashk2810** [comment]
https://github.com/openxla/xla/pull/11483 should fix it!
