### ISSUE TITLE
Tensorflow Building from Source Code

### ISSUE THREAD

**Issue by Nicky9319** [google/jax#20871]
### Description

I am trying to build Tensorflow from source because i want to run tensorflow using c++ and i am trying to download the GPU version
So I ran ./Configure command, and choose the option to enable GPU Support
I ran the bazel command given on the tensorflow Build From source on windows 
https://www.tensorflow.org/install/source_windows

and ran into the following error, What does it imply and how can i Solve it

ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "D:/tensorflow/tensorflow-2.9.0/third_party/gpus/cuda_configure.bzl", line 1401, column 38, in _cuda_autoconf_impl
                _create_local_cuda_repository(repository_ctx)
        File "D:/tensorflow/tensorflow-2.9.0/third_party/gpus/cuda_configure.bzl", line 1179, column 17, in _create_local_cuda_repository
                cc = find_cc(repository_ctx)
        File "D:/tensorflow/tensorflow-2.9.0/third_party/gpus/cuda_configure.bzl", line 216, column 34, in find_cc
                return _get_msvc_compiler(repository_ctx)
        File "D:/tensorflow/tensorflow-2.9.0/third_party/gpus/cuda_configure.bzl", line 133, column 26, in _get_msvc_compiler
                return find_msvc_tool(repository_ctx, vc_path, "cl.exe").replace("\\", "/")
        File "C:/users/paart/_bazel_paart/3pmtytha/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 447, column 27, in find_msvc_tool
                if _is_vs_2017_or_2019(repository_ctx, vc_path) or _is_msbuildtools(vc_path):
        File "C:/users/paart/_bazel_paart/3pmtytha/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 265, column 72, in _is_vs_2017_or_2019
                vc_path_contents = [d.basename.lower() for d in repository_ctx.path(vc_path).readdir()]
Error in path: in call to path(), parameter 'path' got value of type 'NoneType', want 'string, Label, or path'
ERROR: D:/tensorflow/tensorflow-2.9.0/WORKSPACE:15:14: fetching cuda_configure rule //external:local_config_cuda: Traceback (most recent call last):
        File "D:/tensorflow/tensorflow-2.9.0/third_party/gpus/cuda_configure.bzl", line 1401, column 38, in _cuda_autoconf_impl
                _create_local_cuda_repository(repository_ctx)
        File "D:/tensorflow/tensorflow-2.9.0/third_party/gpus/cuda_configure.bzl", line 1179, column 17, in _create_local_cuda_repository
                cc = find_cc(repository_ctx)
        File "D:/tensorflow/tensorflow-2.9.0/third_party/gpus/cuda_configure.bzl", line 216, column 34, in find_cc
                return _get_msvc_compiler(repository_ctx)
        File "D:/tensorflow/tensorflow-2.9.0/third_party/gpus/cuda_configure.bzl", line 133, column 26, in _get_msvc_compiler
                return find_msvc_tool(repository_ctx, vc_path, "cl.exe").replace("\\", "/")
        File "C:/users/paart/_bazel_paart/3pmtytha/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 447, column 27, in find_msvc_tool
                if _is_vs_2017_or_2019(repository_ctx, vc_path) or _is_msbuildtools(vc_path):
        File "C:/users/paart/_bazel_paart/3pmtytha/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 265, column 72, in _is_vs_2017_or_2019
                vc_path_contents = [d.basename.lower() for d in repository_ctx.path(vc_path).readdir()]
Error in path: in call to path(), parameter 'path' got value of type 'NoneType', want 'string, Label, or path'
INFO: Found applicable config definition build:cuda in file d:\tensorflow\tensorflow-2.9.0\.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
ERROR: @local_config_cuda//:enable_cuda :: Error loading option @local_config_cuda//:enable_cuda: in call to path(), parameter 'path' got value of type 'NoneType', want 'string, Label, or path'

### System info (python version, jaxlib version, accelerator, etc.)

I am using python version 3.8
CUDA version 11.2
CuDNN version 8.1
Bazel Version 5.0.0
MSVC 2019

This was the specifications that was given on the tensorflow website
whose link I have Shared Above

**Comment by hawkinsp** [comment]
This repository is for JAX, not TensorFlow. You'd need to file this issue on the TensorFlow github project.
