### ISSUE TITLE
Cannot pass token to custom primitive when using explicit device placement

### ISSUE THREAD

**Issue by dionhaefner** [google/jax#21160]
### Description

I know the title is a mouthful, so here's a reproducer:

```python
import functools

from jax.core import Primitive, ShapedArray, abstract_token
from jax.interpreters import ad, xla, mlir

from jax._src.effects import (
    Effect,
    lowerable_effects,
    ordered_effects,
)

# Register an ordered effect
class EffectType(Effect):
    pass

lowerable_effects.add_type(EffectType)
ordered_effects.add_type(EffectType)

ordered_effect = EffectType()

# Define custom Jax primitive
custom_p = Primitive("custom")
custom_impl = functools.partial(xla.apply_primitive, custom_p)


def custom(x, token):
    return custom_p.bind(x, token)


def custom_xla_encode_cpu(ctx, x, token):
    effect = ctx.tokens_in.get(ordered_effect)[0]
    ctx.set_tokens_out(mlir.TokenSet({ordered_effect: (effect,)}))
    return x, token


def custom_abstract_eval(xs, _):
    return (ShapedArray(xs.shape, xs.dtype), abstract_token), {ordered_effect}


custom_p.def_impl(custom_impl)
custom_p.def_effectful_abstract_eval(custom_abstract_eval)
custom_p.multiple_results = True

mlir.register_lowering(custom_p, custom_xla_encode_cpu, platform="cpu")


if __name__ == "__main__":
    import jax
    x = jax.numpy.zeros(100)
    token = jax.lax.create_token(None)
    devices = jax.local_devices()
    device = devices[0]
    # all good without this line
    x = jax.device_put(x, device=device)
    custom(x, token)
```

The interesting part is this:

```python
>>> x = jax.device_put(x, device=device)
>>> custom(x, token)
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/private/tmp/jaxbug.py", line 54, in <module>
    custom(x, token)
  File "/private/tmp/jaxbug.py", line 27, in custom
    return custom_p.bind(x, token)
  File "/Users/dion/.virtualenvs/tempenv-6a142154757f3/lib/python3.10/site-packages/jax/_src/core.py", line 387, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/Users/dion/.virtualenvs/tempenv-6a142154757f3/lib/python3.10/site-packages/jax/_src/core.py", line 391, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/Users/dion/.virtualenvs/tempenv-6a142154757f3/lib/python3.10/site-packages/jax/_src/core.py", line 879, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/Users/dion/.virtualenvs/tempenv-6a142154757f3/lib/python3.10/site-packages/jax/_src/dispatch.py", line 86, in apply_primitive
    outs = fun(*args)
AttributeError: 'AbstractToken' object has no attribute 'ndim'
```

Everything's fine without the `device_put`.

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.27
jaxlib: 0.4.27
numpy:  1.26.4
python: 3.10.13 (main, Aug 24 2023, 12:59:26) [Clang 15.0.0 (clang-1500.0.40.1)]
jax.devices (1 total, 1 local): [CpuDevice(id=0)]
process_count: 1
platform: uname_result(system='Darwin', node='shrike.local', release='23.4.0', version='Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000', machine='arm64')
```

**Comment by yashk2810** [comment]
This is my bug, I'll fix it.

**Comment by yashk2810** [comment]
https://github.com/google/jax/pull/21163 should fix it.
