### ISSUE TITLE
ROCm 6.1.1: float16 + 7900 XTX, docker: NaN detected in train_loss

### ISSUE THREAD

**Issue by brettkoonce** [google/jax#21187]
### Description

When running the [scenic imagenet demo](https://github.com/google-research/scenic/blob/main/scenic/projects/baselines/configs/imagenet/imagenet_resnet_config.py) in `float16` mode (bs 256), I get the following divergence a few hours into each run (3+ now) when using the ROCm 6.1.1 + 7900 RTX + docker image combination:

```
I0511 08:18:15.127178 140653528475456 local.py:41] Setting work unit notes: 2.8 steps/s, 12.2% (55044/450360), ETA: 1d14h46m (5h28m : 0.1% checkpoint, 0.7% eval)
I0511 08:18:15.127931 140599126628096 logging_writer.py:48] [55044] steps_per_sec=2.83199
I0511 08:18:15.130603 140599126628096 logging_writer.py:48] [55044] uptime=19705
I0511 08:18:15.668868 140653528475456 local.py:41] Setting work unit notes: Steps:55045/450360 [12.2%]
Walltime:5h28m (3m2s Not-train)
ETA:39h10m
Total train time:44h37m
I0511 08:18:15.674834 140599126628096 logging_writer.py:48] [55045] core_hours=5.40294, core_hours_=5.40294, epoch=11.0002, examples_seen=14091520, img/sec=732.41, img/sec/core=732.41, uptime=19705.6
Traceback (most recent call last):
  File "/root/jax_2024/scenic/scenic/main.py", line 66, in <module>
    app.run(main=main)
  File "/pyenv/versions/3.10.0/lib/python3.10/site-packages/scenic/app.py", line 68, in run
    app.run(functools.partial(_run_main, main=main))
  File "/pyenv/versions/3.10.0/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/pyenv/versions/3.10.0/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/pyenv/versions/3.10.0/lib/python3.10/site-packages/scenic/app.py", line 109, in _run_main
    main(rng=rng, config=config, workdir=workdir, writer=writer)
  File "/root/jax_2024/scenic/scenic/main.py", line 56, in main
    trainers.get_trainer(config.trainer_name)(
  File "/pyenv/versions/3.10.0/lib/python3.10/site-packages/scenic/train_lib/classification_trainer.py", line 383, in train
    train_summary = train_utils.log_train_summary(
  File "/pyenv/versions/3.10.0/lib/python3.10/site-packages/scenic/train_lib/train_utils.py", line 952, in log_train_summary
    train_metrics_summary = metrics_normalizer_fn(train_metrics_summary, 'train')
  File "/pyenv/versions/3.10.0/lib/python3.10/site-packages/scenic/train_lib/train_utils.py", line 762, in normalize_metrics_summary
    raise TrainingDivergedError(msg)
scenic.train_lib.train_utils.TrainingDivergedError: NaN detected in train_loss (Unnormalized values: (nan, 1281024.0))

```

For reference, `float32`/ bs128 works!

#21074 is the same approach but with `bfloat16`.

For back context, #10761 was the same issue with the ROCm 5.x / CDNA2 series cards and a vit network.

### System info (python version, jaxlib version, accelerator, etc.)

```
>>> import jax; jax.print_environment_info()
jax:    0.4.26
jaxlib: 0.4.26
numpy:  1.26.4
python: 3.10.0 (default, May  6 2024, 16:35:00) [GCC 9.4.0]
jax.devices (1 total, 1 local): [rocm(id=0)]
process_count: 1
platform: uname_result(system='Linux', node='mars', release='5.15.0-106-generic', version='#116-Ubuntu SMP Wed Apr 17 09:17:56 UTC 2024', machine='x86_64')
```

**Comment by brettkoonce** [comment]
Getting this with Nvidia as well, investigating!
