### ISSUE TITLE
Unexpected Assertion error when using lax.with_sharding_constraint

### ISSUE THREAD

**Issue by andremfreitas** [google/jax#21480]
### Description

Hi,

I was facing an error when trying to use data paralellism with equinox and opened an issue there: [equinox issue #738](https://github.com/patrick-kidger/equinox/issues/738). Turns out the issue is not related with equinox but with `lax.with_sharding_constraint` so I am opening an issue here.

Here is the MWE:

```
import jax
from jax.experimental import mesh_utils
import jax.sharding as jshard

num_devices = len(jax.devices())
print(f"Num GPUs: {num_devices}")
devices = mesh_utils.create_device_mesh((1,num_devices))
sharding = jshard.PositionalSharding(devices)
replicated = sharding.replicate()

x = jax.random.uniform(jax.random.PRNGKey(42), (256, 20, 1000))

x = jax.lax.with_sharding_constraint(x, sharding)
```

And here is the error being thrown:

```
Traceback (most recent call last):
  File "/home/ids/afreitas/test/mwe2.py", line 13, in <module>
    x = jax.lax.with_sharding_constraint(x, sharding)
  File "/home/ids/afreitas/jax/lib/python3.10/site-packages/jax/_src/pjit.py", line 2179, in with_sharding_constraint
    outs = [sharding_constraint_p.bind(xf, sharding=s,
  File "/home/ids/afreitas/jax/lib/python3.10/site-packages/jax/_src/pjit.py", line 2179, in <listcomp>
    outs = [sharding_constraint_p.bind(xf, sharding=s,
  File "/home/ids/afreitas/jax/lib/python3.10/site-packages/jax/_src/core.py", line 422, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/home/ids/afreitas/jax/lib/python3.10/site-packages/jax/_src/core.py", line 425, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/ids/afreitas/jax/lib/python3.10/site-packages/jax/_src/core.py", line 913, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/ids/afreitas/jax/lib/python3.10/site-packages/jax/_src/pjit.py", line 2191, in _sharding_constraint_impl
    return api.jit(_identity_fn, out_shardings=sharding)(x)
  File "/home/ids/afreitas/jax/lib/python3.10/site-packages/jax/_src/sharding_impls.py", line 122, in shard_shape
    return _common_shard_shape(self, global_shape)
  File "/home/ids/afreitas/jax/lib/python3.10/site-packages/jax/_src/sharding_impls.py", line 68, in _common_shard_shape
    assert len(partitions) == len(global_shape), (len(partitions), len(global_shape))
AssertionError: (1, 3)
```

### System info (python version, jaxlib version, accelerator, etc.)

```
python                   3.10
jax                      0.4.26
```

**Comment by yashk2810** [comment]
You need to reshape your sharding to match the length of the shape's ndim:

```
In [7]: import jax
   ...: from jax.experimental import mesh_utils
   ...: import jax.sharding as jshard
   ...:
   ...: num_devices = len(jax.devices())
   ...: print(f"Num GPUs: {num_devices}")
   ...: devices = mesh_utils.create_device_mesh((1, num_devices))
   ...: sharding = jshard.PositionalSharding(devices).reshape(1, 1, 8)
   ...: replicated = sharding.replicate()
   ...:
   ...: x = jax.random.uniform(jax.random.PRNGKey(42), (256, 20, 1000))
   ...:
   ...: x = jax.lax.with_sharding_constraint(x, sharding)
```

This might be a might inconvenient though, so I would suggest using NamedSharding instead:

```
In [10]: import jax
    ...: from jax.experimental import mesh_utils
    ...: import jax.sharding as jshard
    ...: from jax.sharding import PartitionSpec as P
    ...:
    ...: num_devices = len(jax.devices())
    ...: print(f"Num GPUs: {num_devices}")
    ...: devices = mesh_utils.create_device_mesh((1, num_devices))
    ...: mesh = jax.sharding.Mesh(devices, ('x', 'y'))
    ...: sharding = jshard.NamedSharding(mesh, P(None, None, 'x'))
    ...:
    ...: x = jax.random.uniform(jax.random.PRNGKey(42), (256, 20, 1000))
    ...:
    ...: x = jax.lax.with_sharding_constraint(x, sharding)
Num GPUs: 8
``` 

If you want to shard only the first dimension then your PartitionSpec can be `P('x')`.

**Comment by superbobry** [comment]
We should probably raise a better error message when this happens. Wdyt @yashk2810?

**Comment by yashk2810** [comment]
Sure, feel free to send a CL :)

You would need to implement `is_compatible_aval` method on PositionalSharding to raise a better error message.

**Comment by andremfreitas** [comment]
Thanks @yashk2810 ! 
Indeed a better error message would be useful :)
