### ISSUE TITLE
jax raise AttributeError on import when running with python doctring strip optimization

### ISSUE THREAD

**Issue by zazbone** [google/jax#21542]
### Description

Hi,

I hope that the title is explicit enough.
Here some code which reproduce the crash:
```python
import jax
jax.print_environment_info()
```
The crash only appends when python is run with docstring optimization activated.
```python
$ python -OO bug_report.py 
Traceback (most recent call last):
  File "/home/[...]/bug_report.py", line 1, in <module>
    import jax
  File "/home/[...]/venv/lib/python3.10/site-packages/jax/__init__.py", line 44, in <module>
    from jax import tree as tree
  File "/home/[...]/venv/lib/python3.10/site-packages/jax/tree.py", line 20, in <module>
    from jax._src.tree import (
  File "/home/[...]/venv/lib/python3.10/site-packages/jax/_src/tree.py", line 35, in <module>
    def all(tree: Any) -> bool:
  File "/home/[...]/venv/lib/python3.10/site-packages/jax/_src/tree.py", line 27, in wrapper
    firstline, rest = doc.split('\n', 1)
AttributeError: 'NoneType' object has no attribute 'split'
```
My understanding is that jax does docstring manipulations and -OO replace them by None values.

I don't have the knowledge of jax internals to propose code modifications, and my test with -OO was a pure curiosity. I don't think anyone really need this.

Thanks and best regards.

### System info (python version, jaxlib version, accelerator, etc.)

```shell
$ python  bug_report.py 
3.10.13 (main, Dec 15 2023, 19:01:59) [GCC 11.4.0]
0.4.28
jax:    0.4.28
jaxlib: 0.4.28
numpy:  1.26.4
python: 3.10.13 (main, Dec 15 2023, 19:01:59) [GCC 11.4.0]
jax.devices (1 total, 1 local): [CpuDevice(id=0)]
process_count: 1
platform: uname_result(system='Linux', node=[...], release='6.5.0-35-generic', version='#35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue May  7 09:00:52 UTC 2', machine='x86_64')
```

I have only removed personal and irrelevant information inside [...].

**Comment by jakevdp** [comment]
Thanks for the report! We're slowly working toward removing these dynamic docstrings, but we should be able to fix this in the meantime.
