### ISSUE TITLE
Inconsistent behavior with pallas + jnp.power + fp16

### ISSUE THREAD

**Issue by seanxwzhang** [google/jax#21928]
### Description

I have the following 3 kernels that does y = x ** 1 , y= x ** 2 , y= x ** 3, and their behavior is inconsistent (one fails to compile, 2 succeeds)
```
import sys

import jax
import jax.numpy as jnp
import jax.experimental.pallas as pl


def main(kernel_num):
    def kernel_1(x_ref, o_ref):
        x_i = pl.load(x_ref, (slice(None), )) # read whole thing
        o_i = jnp.power(x_i, 1)
        pl.store(o_ref, (slice(None), ), o_i)

    def kernel_2(x_ref, o_ref):
        x_i = pl.load(x_ref, (slice(None), )) # read whole thing
        o_i = jnp.power(x_i, 2)
        pl.store(o_ref, (slice(None), ), o_i)

    def kernel_3(x_ref, o_ref):
        x_i = pl.load(x_ref, (slice(None), )) # read whole thing
        o_i = jnp.power(x_i, 3)
        pl.store(o_ref, (slice(None), ), o_i)

    if kernel_num == 1:
        kernel = kernel_1
    elif kernel_num == 2:
        kernel = kernel_2
    elif kernel_num == 3:
        kernel = kernel_3
    x = jnp.array([1.0, 2.0, 3.0, 4.0], dtype=jnp.float16)
    y = pl.pallas_call(kernel,
                       grid=(1,),
                       out_shape=jax.ShapeDtypeStruct((4,), jnp.float16))(x)

    print(y)

if __name__ == '__main__':
    argv = sys.argv
    kernel_num = int(argv[1])
    main(kernel_num)
```

Running `kernel_2` and `kernel_3` succeeds
```
$ python jax_dtype_demo.py 2
[ 1.  4.  9. 16.]
$ python jax_dtype_demo.py 3
[ 1.  8. 27. 64.]
```
But not for 1 (or any other integers that I tested, for that matter)
```
$ python jax_dtype_demo.py 1
$ python jax_dtype_demo.py 1
Traceback (most recent call last):
  File "/repo/jax_dtype_demo.py", line 41, in <module>
    main(kernel_num)
  File "/repo/jax_dtype_demo.py", line 32, in main
    y = pl.pallas_call(kernel,
  File "/venv/lib/python3.11/site-packages/jax/_src/pallas/pallas_call.py", line 589, in wrapped
    grid_mapping, jaxpr, consts, _ = _trace_to_jaxpr(
  File "/venv/lib/python3.11/site-packages/jax/_src/pallas/pallas_call.py", line 489, in _trace_to_jaxpr
    jaxpr, _, consts, () = pe.trace_to_jaxpr_dynamic(wrapped_fun, jaxpr_flat_avals, debug)
  File "/repo/jax_dtype_demo.py", line 12, in kernel_1
    o_i = jnp.power(x_i, 1)
  File "/venv/lib/python3.11/site-packages/jax/_src/numpy/ufuncs.py", line 354, in power
    return lax.integer_pow(x1, x2)
jax._src.source_info_util.JaxStackTraceBeforeTransformation: NotImplementedError: unsupported types for pow: ('float16', 'int32')

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/jax/_src/pallas/triton/lowering.py", line 351, in lower_jaxpr_to_triton_ir
    outvals = rule(rule_ctx, *invals, **eqn.params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/jax/_src/pallas/triton/lowering.py", line 574, in inner
    raise NotImplementedError(
NotImplementedError: unsupported types for pow: ('float16', 'int32')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/repo/jax_dtype_demo.py", line 41, in <module>
    main(kernel_num)
  File "/repo/jax_dtype_demo.py", line 32, in main
    y = pl.pallas_call(kernel,
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/jax/_src/pallas/pallas_call.py", line 531, in _pallas_call_lowering
    return pallas_call_registration.pallas_call_lowering(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/jax/_src/pallas/triton/pallas_call_registration.py", line 306, in pallas_call_lowering
    return lowering_fn(
           ^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/jax/_src/pallas/triton/pallas_call_registration.py", line 205, in _pallas_call_ttir_lowering
    lowering_result = lowering.lower_jaxpr_to_triton_module(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/jax/_src/pallas/triton/lowering.py", line 304, in lower_jaxpr_to_triton_module
    () = lower_jaxpr_to_triton_ir(ctx, jaxpr, block_infos, *entry.arguments)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/jax/_src/pallas/triton/lowering.py", line 351, in lower_jaxpr_to_triton_ir
    outvals = rule(rule_ctx, *invals, **eqn.params)
  ^^^^^
  File "/venv/lib/python3.11/site-packages/jax/_src/pallas/triton/lowering.py", line 1088, in f_lowered
    out = _closed_call_lowering_rule(ctx, *args, call_jaxpr=jaxpr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/jax/_src/pallas/triton/lowering.py", line 2095, in _closed_call_lowering_rule
    return lower_jaxpr_to_triton_ir(ctx.context, jaxpr, ctx.block_infos, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/jax/_src/pallas/triton/lowering.py", line 356, in lower_jaxpr_to_triton_ir
    raise LoweringError(
jax._src.pallas.triton.lowering.LoweringError: Exception while lowering eqn:
  a:f16[4] = pow b 1
With context:
  LoweringRuleContext(context=ModuleContext(name='kernel_1', grid_mapping=GridMapping(grid=(1,), block_mappings=(None, None), mapped_dims=(), num_index_operands=0, num_scratch_operands=0), program_ids=[<jaxlib.mlir._mlir_libs._mlir.ir.OpResult object at 0x7fbba8ad6170>]), avals_in=[ShapedArray(float16[4]), ShapedArray(int32[], weak_type=True)], avals_out=[ShapedArray(float16[4])], block_infos=[None, None])
With inval types=[RankedTensorType(tensor<4xf16>), None]
In jaxpr:
{ lambda ; a:f16[4]. let b:f16[4] = pow a 1 in (b,) }
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```

I have 2 questions:
1. In this simple example, why does jax/pallas handle `2`, `3` and other integers differently?
2. It seems to me that `2` and `3` works because an implicit type deduction (from python's Int to a fp-16 compatible integer when lowering) is in place, and for other integers jax don't do that. Are users required to signify the type deduction in some way when using python constant in pallas? If so, how does one do that?

### System info (python version, jaxlib version, accelerator, etc.)

```
Python 3.11.8 (main, Feb 25 2024, 16:39:33) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jax; jax.print_environment_info()
jax:    0.4.26
jaxlib: 0.4.26
numpy:  1.26.4
python: 3.11.8 (main, Feb 25 2024, 16:39:33) [GCC 11.4.0]
jax.devices (8 total, 8 local): [cuda(id=0) cuda(id=1) ... cuda(id=6) cuda(id=7)]
process_count: 1
platform: uname_result(system='Linux', node='h100-03', release='5.15.0-100-generic', version='#110-Ubuntu SMP Wed Feb 7 13:27:48 UTC 2024', machine='x86_64')


$ nvidia-smi
Mon Jun 17 20:20:37 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.161.07             Driver Version: 535.161.07   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA H100 80GB HBM3          On  | 00000000:04:00.0 Off |                  Off |
| N/A   66C    P0             580W / 700W |  64686MiB / 81559MiB |     96%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA H100 80GB HBM3          On  | 00000000:23:00.0 Off |                  Off |
| N/A   58C    P0             566W / 700W |  64656MiB / 81559MiB |     96%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA H100 80GB HBM3          On  | 00000000:44:00.0 Off |                  Off |
| N/A   66C    P0             563W / 700W |  64656MiB / 81559MiB |     96%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA H100 80GB HBM3          On  | 00000000:63:00.0 Off |                  Off |
| N/A   56C    P0             592W / 700W |  64656MiB / 81559MiB |     96%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   4  NVIDIA H100 80GB HBM3          On  | 00000000:84:00.0 Off |                  Off |
| N/A   67C    P0             563W / 700W |  64656MiB / 81559MiB |     96%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   5  NVIDIA H100 80GB HBM3          On  | 00000000:A3:00.0 Off |                  Off |
| N/A   57C    P0             572W / 700W |  64656MiB / 81559MiB |     96%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   6  NVIDIA H100 80GB HBM3          On  | 00000000:C3:00.0 Off |                  Off |
| N/A   66C    P0             589W / 700W |  64656MiB / 81559MiB |     96%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   7  NVIDIA H100 80GB HBM3          On  | 00000000:E4:00.0 Off |                  Off |
| N/A   55C    P0             571W / 700W |  64416MiB / 81559MiB |     96%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A   2824488      C   ...anifest2-P7GyiZgo-py3.11/bin/python    64142MiB |
|    0   N/A  N/A   2913433      C   python                                      526MiB |
|    1   N/A  N/A   2824488      C   ...anifest2-P7GyiZgo-py3.11/bin/python    64112MiB |
|    1   N/A  N/A   2913433      C   python                                      526MiB |
|    2   N/A  N/A   2824488      C   ...anifest2-P7GyiZgo-py3.11/bin/python    64112MiB |
|    2   N/A  N/A   2913433      C   python                                      526MiB |
|    3   N/A  N/A   2824488      C   ...anifest2-P7GyiZgo-py3.11/bin/python    64112MiB |
|    3   N/A  N/A   2913433      C   python                                      526MiB |
|    4   N/A  N/A   2824488      C   ...anifest2-P7GyiZgo-py3.11/bin/python    64112MiB |
|    4   N/A  N/A   2913433      C   python                                      526MiB |
|    5   N/A  N/A   2824488      C   ...anifest2-P7GyiZgo-py3.11/bin/python    64112MiB |
|    5   N/A  N/A   2913433      C   python                                      526MiB |
|    6   N/A  N/A   2824488      C   ...anifest2-P7GyiZgo-py3.11/bin/python    64112MiB |
|    6   N/A  N/A   2913433      C   python                                      526MiB |
|    7   N/A  N/A   2824488      C   ...anifest2-P7GyiZgo-py3.11/bin/python    63872MiB |
|    7   N/A  N/A   2913433      C   python                                      526MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by superbobry** [comment]
We special-case a few integer powers [here](https://github.com/google/jax/blob/81f63ed19cb064a09da1c1df4986c45b3c0a1755/jax/_src/pallas/triton/lowering.py#L1076) and use libdevice functions for the rest. libdevice [does not have](https://docs.nvidia.com/cuda/libdevice-users-guide/function-desc.html#function-desc) a `pow` implementation for float16 and int32.

I think we should probably loop instead in the general case, since the power is a statically known integer.
