### ISSUE TITLE
PositionalSharding for scalars fails

### ISSUE THREAD

**Issue by yuzu-ido** [google/jax#22073]
### Description

I recently upgraded jax from 0.4.26 to 0.4.29 and I am no longer able to device_put scalars because of a shape mismatch.  This is a problem because optax.adam uses a count scalar so Adam optimizer would no longer work. It also appears that the [default tutorial](https://jax.readthedocs.io/en/latest/notebooks/Distributed_arrays_and_automatic_parallelization.html) fails with the newest version. We know that NamedSharding is an option which successfully addresses scalars, but would like to continue using PositionalSharding if possible.

```

import equinox as eqx
import jax
import optax
from jax.experimental import mesh_utils
from jax.sharding import PositionalSharding

N_GPUS = jax.device_count()
sharding = PositionalSharding(mesh_utils.create_device_mesh((N_GPUS,)))
scal = jax.device_put(jnp.array(1), sharding.replicate())  # should fail
optim = optax.adam(learning_rate=1e-4)
net_params = eqx.nn.Linear(2, 3, key=jax.random.key(0))
opt_state = optim.init(net_params)
opt_state = jax.device_put(opt_state, sharding.replicate()) # also fails


```
The error message is as follows:
```
Traceback (most recent call last):
  File "foo.py", line 66, in <module>
    opt_state = jax.device_put(opt_state, sharding.replicate())
  File "/home/.../jax/_src/api.py", line 2459, in device_put
    return tree_map(_map, x)
  File "/home/.../jax/_src/tree_util.py", line 473, in tree_map
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "/home/.../jax/_src/tree_util.py", line 473, in <genexpr>
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "/home/.../jax/_src/api.py", line 2456, in _map
    _check_sharding(shaped_abstractify(y), s=device)
  File "/home/.../jax/_src/api.py", line 2419, in _check_sharding
    pjit.pjit_check_aval_sharding(
  File "/home/.../jax/_src/pjit.py", line 1315, in pjit_check_aval_sharding
    raise ValueError(
ValueError: One of device_put args is incompatible with its sharding annotation PositionalSharding([{GPU 0}], shape=(1,)): Sharding PositionalSharding([{GPU 0}], shape=(1,)) is only valid for values of rank 1, but was applied to a value of rank 0

```

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.29
jaxlib: 0.4.29
numpy:  1.26.4
python: 3.10.9 (main, Jan 16 2023, 22:37:31) [Clang 15.0.7 ]
jax.devices (1 total, 1 local): [cuda(id=0)]
process_count: 1
platform: uname_result(system='Linux', node='crepe', release='6.2.0-1017-aws', version='#17~22.04.1-Ubuntu SMP Fri Nov 17 21:07:13 UTC 2023', machine='x86_64')


$ nvidia-smi
Mon Jun 24 22:43:42 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.171.04             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A10G                    On  | 00000000:00:1E.0 Off |                    0 |
|  0%   32C    P0              23W / 300W |    258MiB / 23028MiB |      2%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A    105735      C   ...86_64-unknown-linux-gnu/bin/python3      250MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by yashk2810** [comment]
https://github.com/google/jax/pull/22074 should fix it but you should consider moving to `NamedSharding` :)

**Comment by yuzu-ido** [comment]
Wow, thank you so much for the prompt reply!
