### ISSUE TITLE
Different execution result between `_gamma_one` and 'loggamma'

### ISSUE THREAD

**Issue by TomasAndersonFang** [google/jax#22303]
### Description

When I ran the following code with `loggamma` API, everything is ok. But when I change it to `_gamma_one`, I got the following error:

My code:
```python
import jax
from jax._src.random import _gamma_one
from jax.random import loggamma
import jax.numpy as jnp

def test_f():

    key = jax.random.PRNGKey(0)
    result = _gamma_one(key, -1.0, log_space=True)
    # result = loggamma(key, -1.0)
    print(result)
    assert jnp.isnan(result)  # Expect NaN for negative alpha

if __name__ == "__main__":
    test_f()
```

```
Traceback (most recent call last):
  File "/Users/tomasandersonfang/Desktop/reserach/dnnbugs/dataset/test_script.py", line 15, in <module>
    test_f()
  File "/Users/tomasandersonfang/Desktop/reserach/dnnbugs/dataset/test_script.py", line 9, in test_f
    result = _gamma_one(key, -1.0, log_space=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tomasandersonfang/opt/anaconda3/envs/dnn-test/lib/python3.11/site-packages/jax/_src/random.py", line 1190, in _gamma_one
    key, subkey = _split(key)
                  ^^^^^^^^^^^
  File "/Users/tomasandersonfang/opt/anaconda3/envs/dnn-test/lib/python3.11/site-packages/jax/_src/random.py", line 259, in _split
    assert jnp.issubdtype(key.dtype, dtypes.prng_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.30
jaxlib: 0.4.30
numpy:  1.26.4
python: 3.11.9 (main, Apr 19 2024, 11:43:47) [Clang 14.0.6 ]
jax.devices (1 total, 1 local): [CpuDevice(id=0)]
process_count: 1
platform: uname_result(system='Darwin', node='MacBook-Pro.local', release='23.4.0', version='Darwin Kernel Version 23.4.0: Fri Mar 15 00:19:22 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8112', machine='arm64')
```

**Comment by superbobry** [comment]
`_gamma_one` expects a typed PRNG key, created via the `jax.random.key` function. See https://jax.readthedocs.io/en/latest/jax.random.html#prng-keys.

Note also that `_gamma_one` is an internal JAX API and thus comes with no stability guarantees.
