### ISSUE TITLE
Recent shape checking changes result in new XLA errors

### ISSUE THREAD

**Issue by gnecula** [google/jax#2245]
It turns out that PR #2017 breaks the following code:
```
array = np.ones(5)
print(array[:10])
```

should print `[1. 1. 1. 1. 1.]` but instead throws an error
```
Traceback (most recent call last):
  File "/Users/necula/Source/jax/jax/interpreters/xla.py", line 230, in primitive_computation
    return c.Build()
  File "/Users/necula/Source/jax/jax/lib/xla_bridge.py", line 281, in Build
    *args, **kwargs)
  File "/Users/necula/Source/jax/build/jaxlib/xla_client.py", line 734, in Build
    return Computation(self._builder.Build(), backend=backend)
RuntimeError: Invalid argument: Slice size at index 0 in gather op is out of range, must be within [0, 6), got 10.: 
```
In some sense this error is reasonable, but it is not what JAX used to do before. 
Before JAX used to sanitize indices, and produce the following JAXPR for the `gather`:
```
{ lambda b ; a.
  let c = gather[ dimension_numbers=GatherDimensionNumbers(offset_dims=(0,), collapsed_slice_dims=(), start_index_map=(0,))
                  operand_shape=(5,)
                  slice_sizes=(5,) ] a b
  in c }
```

After this change, the JAXPR is:
```
{ lambda b ; a.
  let c = gather[ dimension_numbers=GatherDimensionNumbers(offset_dims=(0,), collapsed_slice_dims=(), start_index_map=(0,))
                  operand_shape=(5,)
                  slice_sizes=(10,) ] a b
  in c }
```

**Comment by mattjj** [comment]
Thanks for catching this and managing it! I can follow up.
