### ISSUE TITLE
Bulid jaxlib from source code error:  ERROR: Build failed. Not running target! 

### ISSUE THREAD

**Issue by sfdeggb** [google/jax#22614]
### Description

When I used the pip tool
(
the command I used is: 
pip install --upgrade pip
NVIDIA CUDA 12 installation
Note: wheels only available on linux.
pip install --upgrade "jax[cuda12]"
） 
to install jaxlib and jax, and then tried to import jax display :
**This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support. You may be able work around this issue by building jaxlib from source。**
then Follow the prompts I try to install from the source code refer to**https://jax.readthedocs.io/en/latest/developer.html#building-jaxlib-from-source** .The error is take place. the key information is as below:
>ERROR: /home/chat/.cache/bazel/_bazel_chat/e07bb7f39ed7b030eaf9bab18b94dd76/external/llvm-project/llvm/BUILD.bazel:1296:7: Generating code from table: lib/Target/RISCV/RISCV.td @llvm-project//llvm:RISCVTargetParserDefGen__gen_riscv_target_def_genrule [for tool] failed: (Illegal instruction): bash failed: error executing command (from target @llvm-project//llvm:RISCVTargetParserDefGen__gen_riscv_target_def_genrule) 
 (cd /home/chat/.cache/bazel/_bazel_chat/e07bb7f39ed7b030eaf9bab18b94dd76/execroot/__main__ && \
 exec env - \
 LD_LIBRARY_PATH=/usr/local/cuda-12.3/lib64:/usr/local/cuda-12.3/lib64 \
 PATH=/usr/local/cuda-12.3/bin:/home/chat/home/chat/anaconda3/bin/bin:/home/chat/.vscode-server/cli/servers/Stable-ea1445cc7016315d0f5728f8e8b12a45dc0a7286/server/bin/remote-cli:/usr/local/cuda-12.3/bin:/home/chat/home/chat/anaconda3/bin/bin:/home/chat/anaconda3/envs/xuyunlian_clone_cloud/bin:/home/chat/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
 /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/k8-opt-exec-50AE0418/bin/external/llvm-project/llvm/llvm-min-tblgen -I external/llvm-project/llvm/include -I external/llvm-project/clang/include -I $(dirname external/llvm-project/llvm/lib/Target/RISCV/RISCV.td) -gen-riscv-target-def external/llvm-project/llvm/lib/Target/RISCV/RISCV.td  -o bazel-out/k8-opt-exec-50AE0418/bin/external/llvm-project/llvm/include/llvm/TargetParser/RISCVTargetParserDef.inc')
Configuration: 96e81dc836f2097966e75983107cb61c476a61d38f22eded3fcd30b0d3cc1a49
Execution platform: @local_execution_config_platform//:platform
Target //jaxlib/tools:build_wheel failed to build
INFO: Elapsed time: 1.152s, Critical Path: 0.26s
INFO: 22 processes: 21 internal, 1 local.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target

### System info (python version, jaxlib version, accelerator, etc.)

When I used the pip tool
(
the command I used is: 
pip install --upgrade pip
NVIDIA CUDA 12 installation
Note: wheels only available on linux.
pip install --upgrade "jax[cuda12]"
） 
to install jaxlib and jax, and then tried to import jax display :
**This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support. You may be able work around this issue by building jaxlib from source。**
then Follow the prompts I try to install from the source code refer to**https://jax.readthedocs.io/en/latest/developer.html#building-jaxlib-from-source** .The error is take place. the key information is as below:
>ERROR: /home/chat/.cache/bazel/_bazel_chat/e07bb7f39ed7b030eaf9bab18b94dd76/external/llvm-project/llvm/BUILD.bazel:1296:7: Generating code from table: lib/Target/RISCV/RISCV.td @llvm-project//llvm:RISCVTargetParserDefGen__gen_riscv_target_def_genrule [for tool] failed: (Illegal instruction): bash failed: error executing command (from target @llvm-project//llvm:RISCVTargetParserDefGen__gen_riscv_target_def_genrule) 
 (cd /home/chat/.cache/bazel/_bazel_chat/e07bb7f39ed7b030eaf9bab18b94dd76/execroot/__main__ && \
 exec env - \
 LD_LIBRARY_PATH=/usr/local/cuda-12.3/lib64:/usr/local/cuda-12.3/lib64 \
 PATH=/usr/local/cuda-12.3/bin:/home/chat/home/chat/anaconda3/bin/bin:/home/chat/.vscode-server/cli/servers/Stable-ea1445cc7016315d0f5728f8e8b12a45dc0a7286/server/bin/remote-cli:/usr/local/cuda-12.3/bin:/home/chat/home/chat/anaconda3/bin/bin:/home/chat/anaconda3/envs/xuyunlian_clone_cloud/bin:/home/chat/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
 /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/k8-opt-exec-50AE0418/bin/external/llvm-project/llvm/llvm-min-tblgen -I external/llvm-project/llvm/include -I external/llvm-project/clang/include -I $(dirname external/llvm-project/llvm/lib/Target/RISCV/RISCV.td) -gen-riscv-target-def external/llvm-project/llvm/lib/Target/RISCV/RISCV.td  -o bazel-out/k8-opt-exec-50AE0418/bin/external/llvm-project/llvm/include/llvm/TargetParser/RISCVTargetParserDef.inc')
Configuration: 96e81dc836f2097966e75983107cb61c476a61d38f22eded3fcd30b0d3cc1a49
Execution platform: @local_execution_config_platform//:platform
Target //jaxlib/tools:build_wheel failed to build
INFO: Elapsed time: 1.152s, Critical Path: 0.26s
INFO: 22 processes: 21 internal, 1 local.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target

The Complete information is：
>(xuyunlian_clone_cloud) chat@chat-Standard-PC-i440FX-PIIX-1996:~/jax/jax-main$ python build/build.py --enable_cuda
Bazel binary path: /usr/bin/bazel

Bazel version: 6.5.0

Python binary path: /home/chat/anaconda3/envs/xuyunlian_clone_cloud/bin/python

Python version: 3.11

Use clang: no

MKL-DNN enabled: yes

Target CPU: x86_64

Target CPU features: release

CUDA enabled: yes

NCCL enabled: yes

ROCm enabled: no

Building XLA and installing it in the jaxlib source tree...
/usr/bin/bazel run --verbose_failures=true //jaxlib/tools:build_wheel -- --output_path=/home/chat/jax/jax-main/dist --jaxlib_git_hash= --cpu=x86_64
INFO: Options provided by the client:
Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'run' from /home/chat/jax/jax-main/.bazelrc:
Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'run' from /home/chat/jax/jax-main/.bazelrc:
Inherited 'build' options: --nocheck_visibility --apple_platform_type=macos --macos_minimum_os=10.14 --announce_rc --define open_source_build=true --spawn_strategy=standalone --enable_platform_specific_config --experimental_cc_shared_library --define=no_aws_support=true --define=no_gcp_support=true --define=no_hdfs_support=true --define=no_kafka_support=true --define=no_ignite_support=true --define=grpc_no_ares=true --define=tsl_link_protobuf=true -c opt --config=short_logs --copt=-DMLIR_PYTHON_PACKAGE_PREFIX=jaxlib.mlir. --@xla//xla/python:enable_gpu=false
INFO: Reading rc options for 'run' from /home/chat/jax/jax-main/.jax_configure.bazelrc:
Inherited 'build' options: --strategy=Genrule=standalone --config=avx_posix --config=mkl_open_source_only --config=cuda --repo_env HERMETIC_PYTHON_VERSION=3.11
INFO: Found applicable config definition build:short_logs in file /home/chat/jax/jax-main/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:avx_posix in file /home/chat/jax/jax-main/.bazelrc: --copt=-mavx --host_copt=-mavx
INFO: Found applicable config definition build:mkl_open_source_only in file /home/chat/jax/jax-main/.bazelrc: --define=tensorflow_mkldnn_contraction_kernel=1
INFO: Found applicable config definition build:cuda in file /home/chat/jax/jax-main/.bazelrc: --repo_env TF_NEED_CUDA=1 --repo_env TF_NCCL_USE_STUB=1 --action_env TF_CUDA_COMPUTE_CAPABILITIES=sm_50,sm_60,sm_70,sm_80,compute_90 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda --@xla//xla/python:enable_gpu=true --@xla//xla/python:jax_cuda_pip_rpaths=true --define=xla_python_enable_gpu=true --linkopt=-Wl,--disable-new-dtags
INFO: Found applicable config definition build:linux in file /home/chat/jax/jax-main/.bazelrc: --config=posix --copt=-Wno-unknown-warning-option --copt=-Wno-stringop-truncation --copt=-Wno-array-parameter
INFO: Found applicable config definition build:posix in file /home/chat/jax/jax-main/.bazelrc: --copt=-fvisibility=hidden --copt=-Wno-sign-compare --cxxopt=-std=c++17 --host_cxxopt=-std=c++17
Loading:
DEBUG: /home/chat/.cache/bazel/_bazel_chat/e07bb7f39ed7b030eaf9bab18b94dd76/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:118:10:
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
DEBUG: /home/chat/.cache/bazel/_bazel_chat/e07bb7f39ed7b030eaf9bab18b94dd76/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:118:10:
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
Loading:
Loading: 2 packages loaded
Analyzing: target //jaxlib/tools:build_wheel (3 packages loaded, 0 targets configured)
Analyzing: target //jaxlib/tools:build_wheel (103 packages loaded, 3496 targets configured)
Analyzing: target //jaxlib/tools:build_wheel (156 packages loaded, 6720 targets configured)
Analyzing: target //jaxlib/tools:build_wheel (242 packages loaded, 23146 targets configured)
Analyzing: target //jaxlib/tools:build_wheel (245 packages loaded, 23707 targets configured)
Analyzing: target //jaxlib/tools:build_wheel (245 packages loaded, 23707 targets configured)
INFO: Analyzed target //jaxlib/tools:build_wheel (246 packages loaded, 24402 targets configured).
INFO: Found 1 target...
[4 / 356] [Prepa] BazelWorkspaceStatusAction stable-status.txt ... (7 actions, 4 running)
[304 / 4,299] Executing genrule @local_config_cuda//cuda:cuda-lib; 0s local ... (11 actions, 9 running)
[387 / 4,765] Executing genrule @local_config_cuda//cuda:cuda-lib; 2s local ... (14 actions, 13 running)
[3,377 / 6,935] Executing genrule @local_config_cuda//cuda:cuda-lib; 3s local ... (17 actions, 14 running)
[4,069 / 7,464] Executing genrule @local_config_cuda//cuda:cuda-lib; 4s local ... (19 actions, 18 running)
[4,495 / 9,629] Executing genrule @local_config_cuda//cuda:cuda-lib; 5s local ... (20 actions, 19 running)
[6,046 / 9,683] Executing genrule @local_config_cuda//cuda:cuda-lib; 6s local ... (19 actions, 18 running)
[6,086 / 9,698] Executing genrule @local_config_cuda//cuda:cuda-lib; 7s local ... (20 actions, 19 running)
[6,132 / 10,677] Executing genrule @local_config_cuda//cuda:cuda-lib; 8s local ... (19 actions, 18 running)
[6,175 / 11,902] Executing genrule @local_config_cuda//cuda:cuda-lib; 9s local ... (19 actions, 18 running)
[6,216 / 12,069] Executing genrule @local_config_cuda//cuda:cuda-lib; 10s local ... (19 actions, 18 running)
[6,287 / 12,273] Executing genrule @local_config_cuda//cuda:cuda-lib; 11s local ... (20 actions, 19 running)
[6,351 / 12,902] Compiling llvm/lib/TableGen/Record.cpp [for tool]; 3s local ... (20 actions, 19 running)
[6,405 / 13,190] Compiling llvm/lib/Support/APFloat.cpp [for tool]; 2s local ... (20 actions, 19 running)
[6,473 / 13,190] Compiling xla/service/gpu/buffer_comparator.cu.cc; 1s local ... (20 actions, 19 running)
[6,532 / 13,190] Compiling xla/service/gpu/buffer_comparator.cu.cc; 2s local ... (20 actions, 19 running)
[6,574 / 13,208] Compiling xla/service/gpu/buffer_comparator.cu.cc; 3s local ... (20 actions, 19 running)
[6,626 / 13,282] Compiling xla/service/gpu/buffer_comparator.cu.cc; 4s local ... (20 actions, 19 running)
[6,672 / 13,282] Compiling xla/service/gpu/buffer_comparator.cu.cc; 5s local ... (20 actions, 19 running)
[6,731 / 13,440] Compiling xla/service/gpu/buffer_comparator.cu.cc; 6s local ... (20 actions, 19 running)
[6,780 / 14,198] Compiling llvm/lib/Support/VirtualFileSystem.cpp [for tool]; 3s local ... (19 actions, 18 running)
[6,811 / 14,711] Compiling llvm/lib/Support/VirtualFileSystem.cpp [for tool]; 4s local ... (20 actions, 19 running)
[6,851 / 14,716] Compiling llvm/lib/Support/CommandLine.cpp [for tool]; 3s local ... (20 actions, 19 running)
[6,883 / 14,716] Compiling src/google/protobuf/descriptor.cc; 3s local ... (20 actions, 19 running)
[6,912 / 14,716] Compiling src/google/protobuf/descriptor.cc; 5s local ... (20 actions, 19 running)
[6,961 / 14,940] Compiling src/google/protobuf/descriptor.cc; 6s local ... (20 actions, 19 running)
[7,002 / 14,940] Compiling src/google/protobuf/descriptor.cc; 7s local ... (20 actions, 19 running)
[7,038 / 14,940] Compiling src/google/protobuf/descriptor.cc; 8s local ... (20 actions running)
[7,063 / 14,941] Compiling src/google/protobuf/descriptor.cc; 9s local ... (20 actions running)
[7,093 / 15,035] Compiling src/cpu/x64/shuffle/jit_uni_shuffle_kernel.cpp; 3s local ... (19 actions running)
[7,112 / 15,058] Compiling src/cpu/x64/shuffle/jit_uni_shuffle_kernel.cpp; 4s local ... (20 actions running)
[7,129 / 15,111] Compiling src/cpu/x64/gemm/s8x8s32/jit_sse41_u8_copy_sum_at_kern_autogen.cpp; 3s local ... (20 actions running)
[7,152 / 15,114] Compiling xla/service/cpu/runtime_single_threaded_matmul_s32.cc; 3s local ... (18 actions running)
[7,173 / 15,130] Compiling xla/service/cpu/runtime_single_threaded_matmul_s32.cc; 4s local ... (19 actions, 18 running)
[7,188 / 15,222] Compiling xla/service/cpu/runtime_single_threaded_matmul_s32.cc; 5s local ... (20 actions running)
[7,215 / 15,222] Compiling src/google/protobuf/wire_format.cc [for tool]; 3s local ... (20 actions running)
ERROR: /home/chat/.cache/bazel/_bazel_chat/e07bb7f39ed7b030eaf9bab18b94dd76/external/llvm-project/llvm/BUILD.bazel:783:7: Generating code from table: include/llvm/CodeGen/ValueTypes.td @llvm-project//llvm:vt_gen__gen_vt_genrule failed: (Illegal instruction): bash failed: error executing command (from target @llvm-project//llvm:vt_gen__gen_vt_genrule)
(cd /home/chat/.cache/bazel/_bazel_chat/e07bb7f39ed7b030eaf9bab18b94dd76/execroot/**main** && 
exec env - 
LD_LIBRARY_PATH=/usr/local/cuda-12.3/lib64:/usr/local/cuda-12.3/lib64 
PATH=/usr/local/cuda-12.3/bin:/home/chat/home/chat/anaconda3/bin/bin:/home/chat/.vscode-server/cli/servers/Stable-ea1445cc7016315d0f5728f8e8b12a45dc0a7286/server/bin/remote-cli:/usr/local/cuda-12.3/bin:/home/chat/home/chat/anaconda3/bin/bin:/home/chat/anaconda3/envs/xuyunlian_clone_cloud/bin:/home/chat/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin 
TF_CUDA_COMPUTE_CAPABILITIES=sm_50,sm_60,sm_70,sm_80,compute_90 
/bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/k8-opt-exec-50AE0418/bin/external/llvm-project/llvm/llvm-min-tblgen -I external/llvm-project/llvm/include -I external/llvm-project/clang/include -I $(dirname external/llvm-project/llvm/include/llvm/CodeGen/ValueTypes.td) -gen-vt external/llvm-project/llvm/include/llvm/CodeGen/ValueTypes.td  -o bazel-out/k8-opt/bin/external/llvm-project/llvm/include/llvm/CodeGen/GenVT.inc')
Configuration: 833f5f4976e067f110730df7e3b0b8f20258e7d01a0245e165b3de4c2e3de8cc
Execution platform: @local_execution_config_platform//:platform
Target //jaxlib/tools:build_wheel failed to build
INFO: Elapsed time: 44.051s, Critical Path: 11.96s
INFO: 6941 processes: 5584 internal, 1357 local.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
Traceback (most recent call last):
File "/home/chat/jax/jax-main/build/build.py", line 750, in <module>
main()
File "/home/chat/jax/jax-main/build/build.py", line 701, in main
shell(build_cpu_wheel_command)
File "/home/chat/jax/jax-main/build/build.py", line 45, in shell
output = subprocess.check_output(cmd)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/chat/anaconda3/envs/xuyunlian_clone_cloud/lib/python3.11/subprocess.py", line 465, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/chat/anaconda3/envs/xuyunlian_clone_cloud/lib/python3.11/subprocess.py", line 569, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/bazel', 'run', '--verbose_failures=true', '//jaxlib/tools:build_wheel', '--', '--output_path=/home/chat/jax/jax-main/dist', '--jaxlib_git_hash=', '--cpu=x86_64']' returned non-zero exit status 1.
(xuyunlian_clone_cloud) chat@chat-Standard-PC-i440FX-PIIX-1996:~/jax/jax-main$/usr/bin/bazel run --verbose_failures=true //jaxlib/tools:build_wheel -- --output_path=/home/chat/jax/jax-main/dist --jaxlib_git_hash= --cpu=x86_64
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=157
INFO: Reading rc options for 'run' from /home/chat/jax/jax-main/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'run' from /home/chat/jax/jax-main/.bazelrc:
  Inherited 'build' options: --nocheck_visibility --apple_platform_type=macos --macos_minimum_os=10.14 --announce_rc --define open_source_build=true --spawn_strategy=standalone --enable_platform_specific_config --experimental_cc_shared_library --define=no_aws_support=true --define=no_gcp_support=true --define=no_hdfs_support=true --define=no_kafka_support=true --define=no_ignite_support=true --define=grpc_no_ares=true --define=tsl_link_protobuf=true -c opt --config=short_logs --copt=-DMLIR_PYTHON_PACKAGE_PREFIX=jaxlib.mlir. --@xla//xla/python:enable_gpu=false
INFO: Reading rc options for 'run' from /home/chat/jax/jax-main/.jax_configure.bazelrc:
  Inherited 'build' options: --strategy=Genrule=standalone --config=avx_posix --config=mkl_open_source_only --config=cuda --repo_env HERMETIC_PYTHON_VERSION=3.11
INFO: Found applicable config definition build:short_logs in file /home/chat/jax/jax-main/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:avx_posix in file /home/chat/jax/jax-main/.bazelrc: --copt=-mavx --host_copt=-mavx
INFO: Found applicable config definition build:mkl_open_source_only in file /home/chat/jax/jax-main/.bazelrc: --define=tensorflow_mkldnn_contraction_kernel=1
INFO: Found applicable config definition build:cuda in file /home/chat/jax/jax-main/.bazelrc: --repo_env TF_NEED_CUDA=1 --repo_env TF_NCCL_USE_STUB=1 --action_env TF_CUDA_COMPUTE_CAPABILITIES=sm_50,sm_60,sm_70,sm_80,compute_90 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda --@xla//xla/python:enable_gpu=true --@xla//xla/python:jax_cuda_pip_rpaths=true --define=xla_python_enable_gpu=true --linkopt=-Wl,--disable-new-dtags
INFO: Found applicable config definition build:linux in file /home/chat/jax/jax-main/.bazelrc: --config=posix --copt=-Wno-unknown-warning-option --copt=-Wno-stringop-truncation --copt=-Wno-array-parameter
INFO: Found applicable config definition build:posix in file /home/chat/jax/jax-main/.bazelrc: --copt=-fvisibility=hidden --copt=-Wno-sign-compare --cxxopt=-std=c++17 --host_cxxopt=-std=c++17
INFO: Analyzed target //jaxlib/tools:build_wheel (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/chat/.cache/bazel/_bazel_chat/e07bb7f39ed7b030eaf9bab18b94dd76/external/llvm-project/llvm/BUILD.bazel:1296:7: Generating code from table: lib/Target/RISCV/RISCV.td @llvm-project//llvm:RISCVTargetParserDefGen__gen_riscv_target_def_genrule [for tool] failed: (Illegal instruction): bash failed: error executing command (from target @llvm-project//llvm:RISCVTargetParserDefGen__gen_riscv_target_def_genrule) 
  (cd /home/chat/.cache/bazel/_bazel_chat/e07bb7f39ed7b030eaf9bab18b94dd76/execroot/__main__ && \
  exec env - \
    LD_LIBRARY_PATH=/usr/local/cuda-12.3/lib64:/usr/local/cuda-12.3/lib64 \
    PATH=/usr/local/cuda-12.3/bin:/home/chat/home/chat/anaconda3/bin/bin:/home/chat/.vscode-server/cli/servers/Stable-ea1445cc7016315d0f5728f8e8b12a45dc0a7286/server/bin/remote-cli:/usr/local/cuda-12.3/bin:/home/chat/home/chat/anaconda3/bin/bin:/home/chat/anaconda3/envs/xuyunlian_clone_cloud/bin:/home/chat/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/k8-opt-exec-50AE0418/bin/external/llvm-project/llvm/llvm-min-tblgen -I external/llvm-project/llvm/include -I external/llvm-project/clang/include -I$(dirname external/llvm-project/llvm/lib/Target/RISCV/RISCV.td) -gen-riscv-target-def external/llvm-project/llvm/lib/Target/RISCV/RISCV.td  -o bazel-out/k8-opt-exec-50AE0418/bin/external/llvm-project/llvm/include/llvm/TargetParser/RISCVTargetParserDef.inc')
Configuration: 96e81dc836f2097966e75983107cb61c476a61d38f22eded3fcd30b0d3cc1a49
Execution platform: @local_execution_config_platform//:platform

Target //jaxlib/tools:build_wheel failed to build

INFO: Elapsed time: 1.152s, Critical Path: 0.26s

INFO: 22 processes: 21 internal, 1 local.

FAILED: Build did NOT complete successfully

ERROR: Build failed. Not running target

---
ERROR: /home/chat/.cache/bazel/_bazel_chat/e07bb7f39ed7b030eaf9bab18b94dd76/external/llvm-project/llvm/BUILD.bazel:1296:7: Generating code from table: lib/Target/RISCV/RISCV.td @llvm-project//llvm:RISCVTargetParserDefGen__gen_riscv_target_def_genrule [for tool] failed: (Illegal instruction): bash failed: error executing command (from target @llvm-project//llvm:RISCVTargetParserDefGen__gen_riscv_target_def_genrule) 
(cd /home/chat/.cache/bazel/_bazel_chat/e07bb7f39ed7b030eaf9bab18b94dd76/execroot/__main__ && \
exec env - \
LD_LIBRARY_PATH=/usr/local/cuda-12.3/lib64:/usr/local/cuda-12.3/lib64 \
PATH=/usr/local/cuda-12.3/bin:/home/chat/home/chat/anaconda3/bin/bin:/home/chat/.vscode-server/cli/servers/Stable-ea1445cc7016315d0f5728f8e8b12a45dc0a7286/server/bin/remote-cli:/usr/local/cuda-12.3/bin:/home/chat/home/chat/anaconda3/bin/bin:/home/chat/anaconda3/envs/xuyunlian_clone_cloud/bin:/home/chat/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
/bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/k8-opt-exec-50AE0418/bin/external/llvm-project/llvm/llvm-min-tblgen -I external/llvm-project/llvm/include -I external/llvm-project/clang/include -I $(dirname external/llvm-project/llvm/lib/Target/RISCV/RISCV.td) -gen-riscv-target-def external/llvm-project/llvm/lib/Target/RISCV/RISCV.td  -o bazel-out/k8-opt-exec-50AE0418/bin/external/llvm-project/llvm/include/llvm/TargetParser/RISCVTargetParserDef.inc')
Configuration: 96e81dc836f2097966e75983107cb61c476a61d38f22eded3fcd30b0d3cc1a49
Execution platform: @local_execution_config_platform//:platform
Target //jaxlib/tools:build_wheel failed to build
INFO: Elapsed time: 1.152s, Critical Path: 0.26s
INFO: 22 processes: 21 internal, 1 local.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target!

**Looking forward to a helpful reply！**

**Comment by rajasekharporeddy** [comment]
Hi @sfdeggb 

Are you attempting to install JAX with CUDA support on Windows? If so, please note that [JAX with CUDA support is not available on windows](https://jax.readthedocs.io/en/latest/installation.html#supported-platforms). Please let us know if you are using any other OS.

Thank you.
