### ISSUE TITLE
 Failed to load Starlark extension '@com_github_grpc_grpc//bazel:grpc_deps.bzl'.

### ISSUE THREAD

**Issue by oliviermattelaer** [google/jax#2270]
Hi,

When compiling on centos7, it directly crashes stating some extension are missing
Is this a dependency  missing?

Thanks,

Olivier

```
Bazel binary path: ./bazel-1.2.1-linux-x86_64
Python binary path: /opt/sw/arch/easybuild/2019b/software/Python/3.7.4-GCCcore-8.3.0/bin/python
Python version: 3.7
MKL-DNN enabled: yes
-march=native: yes
CUDA enabled: yes

Building XLA and installing it in the jaxlib source tree...
./bazel-1.2.1-linux-x86_64 run --verbose_failures=true --config=opt --config=mkl_open_source_only --config=cuda --define=xla_python_enable_gpu=true :install_xla_in_source_tree /usr/local/Software/jax/build
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'run' from /usr/local/Software/jax/.bazelrc:
  Inherited 'build' options: --repo_env PYTHON_BIN_PATH=/opt/sw/arch/easybuild/2019b/software/Python/3.7.4-GCCcore-8.3.0/bin/python --python_path=/opt/sw/arch/easybuild/2019b/software/Python/3.7.4-GCCcore-8.3.0/bin/python --repo_env TF_NEED_CUDA=1 --distinct_host_configuration=false --copt=-Wno-sign-compare -c opt --apple_platform_type=macos --macos_minimum_os=10.9 --announce_rc --define=no_aws_support=true --define=no_gcp_support=true --define=no_hdfs_support=true --define=no_kafka_support=true --define=no_ignite_support=true --define=grpc_no_ares=true --spawn_strategy=standalone --strategy=Genrule=standalone --cxxopt=-std=c++14 --host_cxxopt=-std=c++14
INFO: Found applicable config definition build:opt in file /usr/local/Software/jax/.bazelrc: --copt=-march=native --host_copt=-march=native
INFO: Found applicable config definition build:mkl_open_source_only in file /usr/local/Software/jax/.bazelrc: --define=tensorflow_mkldnn_contraction_kernel=1
INFO: Found applicable config definition build:cuda in file /usr/local/Software/jax/.bazelrc: --crosstool_top=@local_config_cuda//crosstool:toolchain --define=using_cuda=true --define=using_cuda_nvcc=true
Loading:
Loading: 0 packages loaded
ERROR: Failed to load Starlark extension '@com_github_grpc_grpc//bazel:grpc_deps.bzl'.
Cycle in the workspace file detected. This indicates that a repository is used prior to being defined.
The following chain of repository dependencies lead to the missing definition.
 - @com_github_grpc_grpc
This could either mean you have to add the '@com_github_grpc_grpc' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or move an existing definition earlier in your WORKSPACE file.
ERROR: cycles detected during target parsing
INFO: Elapsed time: 0.085s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully (0 packages loaded)
Traceback (most recent call last):
  File "build/build.py", line 365, in <module>
    main()
  File "build/build.py", line 360, in main
    shell(command)
  File "build/build.py", line 47, in shell
    output = subprocess.check_output(cmd)
  File "/opt/sw/arch/easybuild/2019b/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/opt/sw/arch/easybuild/2019b/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./bazel-1.2.1-linux-x86_64', 'run', '--verbose_failures=true', '--config=opt', '--config=mkl_open_source_only', '--config=cuda', '--define=xla_python_enable_gpu=true', ':install_xla_in_source_tree', '/usr/local/Software/jax/build']' returned non-zero exit status 1.
```

**Comment by hawkinsp** [comment]
I think a recent PR broke the build. Sorry for the breakage. We'll look into it. For now, can you sync back to https://github.com/google/jax/commit/96b66ac9762225da4d3977e82dfd35c1160827bc ?

(Alternatively, just use a prebuilt jaxlib, as described in the README!)

**Comment by j-towns** [comment]
FYI I'm seeing the same error on macOS.
