### ISSUE TITLE
checkify: false positive in jnp.where

### ISSUE THREAD

**Issue by jakevdp** [google/jax#22806]
```python
import jax.numpy as jnp
import jax.experimental.checkify as checkify

x = jnp.arange(2)
err, _ = checkify.checkify(jnp.where, errors=checkify.index_checks)(x > 0.5, size=1)
err.throw()
```
```pytb
Traceback (most recent call last):
  File "/Users/vanderplas/github/google/jax/tmp.py", line 5, in <module>
    err, _ = checkify.checkify(jnp.where, errors=checkify.index_checks)(x > 0.5, size=1)
  File "/Users/vanderplas/github/google/jax/jax/_src/numpy/lax_numpy.py", line 2116, in where
    return nonzero(condition, size=size, fill_value=fill_value)
  File "/Users/vanderplas/github/google/jax/jax/_src/numpy/lax_numpy.py", line 2607, in nonzero
    bincount(reductions.cumsum(mask), length=calculated_size))
  File "/Users/vanderplas/github/google/jax/jax/_src/numpy/lax_numpy.py", line 2229, in bincount
    return zeros(length, _dtype(weights)).at[clip(x, 0)].add(weights)
  File "/Users/vanderplas/github/google/jax/jax/_src/numpy/array_methods.py", line 537, in add
    return scatter._scatter_update(self.array, self.index, values,
  File "/Users/vanderplas/github/google/jax/jax/_src/ops/scatter.py", line 76, in _scatter_update
    return _scatter_impl(x, y, scatter_op, treedef, static_idx, dynamic_idx,
  File "/Users/vanderplas/github/google/jax/jax/_src/ops/scatter.py", line 127, in _scatter_impl
    out = scatter_op(
jax._src.checkify.OOBError: out-of-bounds indexing for array of shape (1,): index 1 is out of bounds for axis 0 with size 1. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/vanderplas/github/google/jax/tmp.py", line 6, in <module>
    err.throw()
  File "/Users/vanderplas/github/google/jax/jax/_src/checkify.py", line 245, in throw
    _check_error(self)
  File "/Users/vanderplas/github/google/jax/jax/_src/checkify.py", line 1194, in _check_error
    return check_p.bind(*err_args, err_tree=tree_def, debug=debug)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/core.py", line 429, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/core.py", line 433, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/core.py", line 939, in process_primitive
    return primitive.impl(*tracers, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanderplas/github/google/jax/jax/_src/checkify.py", line 494, in check_impl
    raise JaxRuntimeError(str(exc)) from exc
jax._src.checkify.JaxRuntimeError: out-of-bounds indexing for array of shape (1,): index 1 is out of bounds for axis 0 with size 1. 
```

**Comment by jakevdp** [comment]
I think the approach to fixing this is:
- make checkify only error when `mode=PROMISE_IN_BOUNDS`
- ensure that `gather` and `scatter` default to `mode=PROMISE_IN_BOUNDS`
- explicitly set `mode=DROP` or `mode=FILL` in `jnp.where` implementation, as well as other library code, to avoid checkify errors

**Comment by jakevdp** [comment]
On discussion with @hawkinsp, it seems that defaulting to `PROMISE_IN_BOUNDS` is not the right approach, because it has problematic semantics (particularly for autodiff). Given this, the plan is to add a new `GatherScatterMode.DEFAULT` mode that is semantically equivalent to `FILL_OR_DROP`, except that `checkify` will raise for out-of-bound indices in DEFAULT mode.

**Comment by jakevdp** [comment]
I think I'll leave this until checkify has stabilized more.
