### ISSUE TITLE
local_device_count fails on wsl with 'cpu'

### ISSUE THREAD

**Issue by AvisP** [google/jax#23034]
### Description

In wsl2 when doing a `jax.local_device_count('cpu')` the following error is returned. No gpu in the machine and getting the following error

```
Traceback (most recent call last):
  File "/mnt/c/....../TimesFMEnv/lib/python3.10/site-packages/jax/_src/xla_bridge.py", line 853, in backends
    backend = _init_backend(platform)
  File "/mnt/c/...../TimesFMEnv/lib/python3.10/site-packages/jax/_src/xla_bridge.py", line 935, in _init_backend
    backend = registration.factory()
  File "/mnt/c/...../TimesFMEnv/lib/python3.10/site-packages/jax/_src/xla_bridge.py", line 646, in factory
    return xla_client.make_c_api_client(plugin_name, updated_options, None)
  File "/mnt/c/....../TimesFMEnv/lib/python3.10/site-packages/jaxlib/xla_client.py", line 198, in make_c_api_client
    return _xla.get_c_api_client(plugin_name, options, distributed_client)
jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: No visible GPU devices.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/...../TimesFMEnv/lib/python3.10/site-packages/jax/_src/xla_bridge.py", line 1019, in local_device_count
    return int(get_backend(backend).local_device_count())
  File "/mnt/c/......./TimesFMEnv/lib/python3.10/site-packages/jax/_src/xla_bridge.py", line 981, in get_backend
    return _get_backend_uncached(platform)
  File "/mnt/c/...../TimesFMEnv/lib/python3.10/site-packages/jax/_src/xla_bridge.py", line 960, in _get_backend_uncached
    bs = backends()
  File "/mnt/c/...../TimesFMEnv/lib/python3.10/site-packages/jax/_src/xla_bridge.py", line 869, in backends
    raise RuntimeError(err_msg)
RuntimeError: Unable to initialize backend 'cuda': FAILED_PRECONDITION: No visible GPU devices. (you may need to uninstall the failing plugin package, or set JAX_PLATFORMS=cpu to skip this backend.)
```

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.26
jaxlib: 0.4.26
numpy:  1.26.4
python: 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
jax.devices (1 total, 1 local): [CpuDevice(id=0)]
process_count: 1
platform: uname_result(system='Linux', node='DevMontreal01', release='5.15.153.1-microsoft-standard-WSL2', version='#1 SMP Fri Mar 29 23:14:13 UTC 2024', machine='x86_64')
```

**Comment by rajasekharporeddy** [comment]
Hi @AvisP 

I was not able reproduce the issue on WSL2. Please take a look at the attached screenshot for confirmation.

![image](https://github.com/user-attachments/assets/8cce9d3b-edfc-477e-879a-d6397e0aac2e)


Thank you

**Comment by vfdev-5** [comment]
@AvisP as the error message says, you may need to add `JAX_PLATFORMS=cpu` to env vars before running any scripts/code: `JAX_PLATFORMS=cpu  python script.py`

**Comment by AvisP** [comment]
Thanks @vfdev-5 setting it fixed the issue.

**Comment by vfdev-5** [comment]
@AvisP let me close the issue as solved, feel free to reopen if needed any other support on this question
