### ISSUE TITLE
custom_jvp leaks tracers if they're marked as nondiff_argnum

### ISSUE THREAD

**Issue by jakevdp** [google/jax#23065]
```python
import jax
import jax.numpy as jnp
from functools import partial

jax.config.update("jax_check_tracer_leaks", True)

@partial(jax.custom_jvp, nondiff_argnums=(1,))
def f(x, index):
  return x[indices]

@f.defjvp
def f_jvp(primals, tangents):
  x, indices = primals
  x_dot, _ = tangents
  return f(x, indices), x_dot[indices]

f = jax.jit(f)

x = jnp.arange(10.0)
indices = jnp.array([1, 3, 5])

jax.jacobian(f)(x, indices)
```
```pytb
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
[<ipython-input-4-187c7ba61f1a>](https://localhost:8080/#) in <cell line: 22>()
     20 indices = jnp.array([1, 3, 5])
     21 
---> 22 jax.jacobian(f)(x, indices)

8 frames
    [... skipping hidden 9 frame]

[/usr/local/lib/python3.10/dist-packages/jax/_src/core.py](https://localhost:8080/#) in new_main(trace_type, dynamic, **payload)
   1201     if t() is not None:
   1202       leaked_tracers = maybe_find_leaked_tracers(t())
-> 1203       if leaked_tracers: raise leaked_tracer_error("trace", t(), leaked_tracers)
   1204 
   1205 @contextmanager

Exception: Leaked trace MainTrace(3,DynamicJaxprTrace). Leaked tracer(s):

Traced<ShapedArray(int32[3])>with<DynamicJaxprTrace(level=3/0)>
This DynamicJaxprTracer was created on line <ipython-input-4-187c7ba61f1a>:22 (<cell line: 22>)
<DynamicJaxprTracer 132784232580496> is referred to by <Unhashable 132784232965184>
<Unhashable 132784232965184> is referred to by <tuple 132784232963024>[0]
<tuple 132784232963024> is referred to by <tuple 132784233015296>[0]
<tuple 132784233015296> is referred to by <tuple 132784230409408>[1]
<tuple 132784230409408> is referred to by <tuple 132784232368448>[2]
<tuple 132784232368448> is referred to by <WrappedFun 132784230029152>
<WrappedFun 132784230029152> is referred to by <function 132784230549536> (jvp_jaxpr_thunk) closed-over variable jvp
<function 132784230549536> is referred to by <function 132784230549968> (memoized) closed-over variable fn
<function 132784230549968> is referred to by <dict 132784230413568>['jvp_jaxpr_thunk']
<dict 132784230413568> is referred to by <JaxprEqn 132784230695264>[3]
<JaxprEqn 132784230695264> is referred to by <list 132784230082816>[1]
<list 132784230082816> is referred to by <Jaxpr 132784230694976>
```
The problem is here that `indices` is a traced array, but is marked as a `nondiff_argnum`. This is user error, but we should fail with a more informative error.

**Comment by dfm** [comment]
I _think_ this is actually a bug (although @mattjj and @froystig will know better, of course!). If we update `f_jvp` to:

```python
@f.defjvp
def f_jvp(indices, primals, tangents):
  x, = primals
  x_dot, = tangents
  return x[indicies], x_dot[indices]
```

everything works as it should without any leaked tracers. I haven't had a chance to dig into why this is, but there's a lot of subtlety around handling these recursive patterns. Regardless, I don't think that we do need to require that "nondiff" args be "static".

**Comment by dfm** [comment]
OK maybe I take that back! It's clear from this error message:

https://github.com/google/jax/blob/82d3cfb3c6f88321f0b29b4cc41134a464de82c2/jax/_src/custom_derivatives.py#L656-L662

that custom _VJP_ at least has this requirement that nondiff args cannot be tracers. I think it also follows that they can't be tracers because they're handled by [baking them into the functions](https://github.com/google/jax/blob/82d3cfb3c6f88321f0b29b4cc41134a464de82c2/jax/_src/custom_derivatives.py#L238-L239), rather than [binding them](https://github.com/google/jax/blob/82d3cfb3c6f88321f0b29b4cc41134a464de82c2/jax/_src/custom_derivatives.py#L249-L250). I guess from my example above, there are some cases where things might still work, but they shouldn't be expected to.

Perhaps it would be reasonable to add the tracer check from [`custom_vjp`](https://github.com/google/jax/blob/82d3cfb3c6f88321f0b29b4cc41134a464de82c2/jax/_src/custom_derivatives.py#L605) to [`custom_jvp`](https://github.com/google/jax/blob/82d3cfb3c6f88321f0b29b4cc41134a464de82c2/jax/_src/custom_derivatives.py#L234)?

**Comment by kcdodd** [comment]
I think I ran into this issue from some jax builtins use custom_jvp,  minimal example is below. @dfm I would have naively agreed with your first interpretation that it seems like there is nothing conceptually intrinsic about nondiff arguments that should cause them to be static.

```python
from jax import numpy as jnp
import jax

@jax.jit
def f(A, rtol):
  return jnp.linalg.pinv(A, rtol)

_A = f(jnp.eye(3), 0.001)

print(f"{_A=}")
```

```text
Traceback (most recent call last):
  File "/home/cdodd/proj/test.py", line 8, in <module>
    _A = f(jnp.eye(3), 0.001)
         ^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.11.0/gcc-system/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
^^^^^^^^^^^^^^^^^^
Exception: Leaked trace DynamicJaxprTrace. Leaked tracer(s):

Traced<ShapedArray(float32[], weak_type=True)>with<DynamicJaxprTrace>
The error occurred while tracing the function f at /home/cdodd/proj/test.py:4 for jit. This concrete value was not available in Python because it depends on the value of the argument rtol.
<DynamicJaxprTracer 139925252380672> is referred to by <Unhashable 139925252235440>
<Unhashable 139925252235440> is referred to by <tuple 139925450911040>[0]
<tuple 139925450911040> is referred to by <tuple 139927089822496>[0]
<tuple 139927089822496> is referred to by <tuple 139925252395520>[1]
<tuple 139925252395520> is referred to by <tuple 139925252395840>[1]
<tuple 139925252395840> is referred to by <WrappedFun 139925451088576>
<WrappedFun 139925451088576> is referred to by <function 139925451687712> (jvp_jaxpr_thunk) closed-over variable jvp
<function 139925451687712> is referred to by <function 139925451688672> (memoized) closed-over variable fn
<function 139925451688672> is referred to by <dict 139925252426496>['jvp_jaxpr_thunk']
<dict 139925252426496> is referred to by <JaxprEqn 139925451094912>
<JaxprEqn 139925451094912> is referred to by <list 139925451708160>[1]
<list 139925451708160> is referred to by <Jaxpr 139925451094432>

--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

```

**Comment by mattjj** [comment]
It’s true that “non differentiable argument” need not imply “static argument”. But this feature is actually for declaring static arguments, and the name was chosen badly.

We should probably:
1. Change the name to static_argnums (except keep the old one working for back compatibility);
2. add the check to custom_jvp;
3. add a new convenience feature for array like (ie tracery) values that we don’t want involved in differentiation.  

The third has limited upside because you can already get this behavior today by passing in ordinary arguments and just ignoring their corresponding tangents.

**Comment by kcdodd** [comment]
That makes sense. I may open a separate issue for the case like 'pinv', it seems like rtol shouldn't need to be static.
