### ISSUE TITLE
ImportError: libcusolver.so.10.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by manuel-delverme** [google/jax#2315]
After running:
```
nvidia-smi # success

PYTHON_VERSION=cp38 
PLATFORM=linux_x86_64
CUDA_VERSION=cuda101
BASE_URL='https://storage.googleapis.com/jax-releases'
pip install --upgrade $BASE_URL/$CUDA_VERSION/jaxlib-0.1.39-$PYTHON_VERSION-none-$PLATFORM.whl
pip install --upgrade jax
```
I get the following error:
ImportError: libcusolver.so.10.0: cannot open shared object file: No such file or directory

**Comment by mattjj** [comment]
@hawkinsp any advice?

**Comment by mattjj** [comment]
@manuel-delverme two questions for you:

1. is this still an issue for you?
1. can you locate libcusolver.so.10.0 (or any other version of that file) on your system?

**Comment by hawkinsp** [comment]
Most likely you need to set the environment variable `LD_LIBRARY_PATH` to some place like `/usr/local/cuda/lib64`. Out of curiosity, where is your CUDA installation? We could definitely try to simplify this.

**Comment by manuel-delverme** [comment]
```
➜ fax git:(extragradient) ✗ source venv/bin/activate
(venv) ➜ fax git:(extragradient) ✗ locate libcusolver.so   
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcusolver.so.10
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcusolver.so.10.1.105
/usr/share/man/man7/libcusolver.so.7
(venv) ➜ fax git:(extragradient) ✗ export "LD_LIBRARY_PATH=/usr/local/cuda-10.1/targets/x86_64-linux/lib/"
(venv) ➜ fax git:(extragradient) ✗ nvidia-smi # success
Tue Mar 10 10:20:10 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2060    On   | 00000000:01:00.0  On |                  N/A |
| N/A   46C    P3    22W /  N/A |    119MiB /  5934MiB |     16%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1475      G   /usr/lib/xorg/Xorg                           118MiB |
+-----------------------------------------------------------------------------+
(venv) ➜ fax git:(extragradient) ✗ pip uninstall jaxlib
Found existing installation: jaxlib 0.1.39
Uninstalling jaxlib-0.1.39:
  Would remove:
    /home/esac/research/fax/venv/lib/python3.8/site-packages/jaxlib-0.1.39.dist-info/*
    /home/esac/research/fax/venv/lib/python3.8/site-packages/jaxlib/*
Proceed (y/n)? y
  Successfully uninstalled jaxlib-0.1.39
(venv) ➜ fax git:(extragradient) ✗ pip uninstall jax   
Found existing installation: jax 0.1.59
Uninstalling jax-0.1.59:
  Would remove:
    /home/esac/research/fax/venv/lib/python3.8/site-packages/jax-0.1.59.dist-info/*
    /home/esac/research/fax/venv/lib/python3.8/site-packages/jax/*
Proceed (y/n)? y
  Successfully uninstalled jax-0.1.59
(venv) ➜ fax git:(extragradient) ✗ PYTHON_VERSION=cp38 
PLATFORM=linux_x86_64
CUDA_VERSION=cuda101
BASE_URL='https://storage.googleapis.com/jax-releases'
pip install --upgrade $BASE_URL/$CUDA_VERSION/jaxlib-0.1.39-$PYTHON_VERSION-none-$PLATFORM.whl
pip install --upgrade jax
Collecting jaxlib==0.1.39
  Using cached https://storage.googleapis.com/jax-releases/cuda101/jaxlib-0.1.39-cp38-none-linux_x86_64.whl (65.5 MB)
Requirement already satisfied, skipping upgrade: scipy in ./venv/lib/python3.8/site-packages (from jaxlib==0.1.39) (1.4.1)
Requirement already satisfied, skipping upgrade: absl-py in ./venv/lib/python3.8/site-packages (from jaxlib==0.1.39) (0.9.0)
Requirement already satisfied, skipping upgrade: numpy>=1.12 in ./venv/lib/python3.8/site-packages (from jaxlib==0.1.39) (1.18.1)
Requirement already satisfied, skipping upgrade: six in ./venv/lib/python3.8/site-packages (from absl-py->jaxlib==0.1.39) (1.14.0)
ERROR: fax 0.0.4 requires jax, which is not installed.
Installing collected packages: jaxlib
Successfully installed jaxlib-0.1.39
Processing /home/esac/.cache/pip/wheels/95/80/ef/c6dc1bccfd1c49174cd44712aa5eda89168cb69c57ebcf74d7/jax-0.1.59-py3-none-any.whl
Requirement already satisfied, skipping upgrade: opt-einsum in ./venv/lib/python3.8/site-packages (from jax) (3.1.0)
Requirement already satisfied, skipping upgrade: absl-py in ./venv/lib/python3.8/site-packages (from jax) (0.9.0)
Requirement already satisfied, skipping upgrade: numpy>=1.12 in ./venv/lib/python3.8/site-packages (from jax) (1.18.1)
Requirement already satisfied, skipping upgrade: six in ./venv/lib/python3.8/site-packages (from absl-py->jax) (1.14.0)
Installing collected packages: jax
Successfully installed jax-0.1.59
(venv) ➜ fax git:(extragradient) ✗ python -m jax
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 184, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 143, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/esac/research/fax/venv/lib/python3.8/site-packages/jax/__init__.py", line 19, in <module>
    from jax.api import *
  File "/home/esac/research/fax/venv/lib/python3.8/site-packages/jax/api.py", line 40, in <module>
    from . import ad_util
  File "/home/esac/research/fax/venv/lib/python3.8/site-packages/jax/ad_util.py", line 17, in <module>
    from .tree_util import register_pytree_node
  File "/home/esac/research/fax/venv/lib/python3.8/site-packages/jax/tree_util.py", line 42, in <module>
    from .lib import pytree
  File "/home/esac/research/fax/venv/lib/python3.8/site-packages/jax/lib/__init__.py", line 51, in <module>
    from jaxlib import xla_client
  File "/home/esac/research/fax/venv/lib/python3.8/site-packages/jaxlib/xla_client.py", line 37, in <module>
    from . import xla_extension as _xla
ImportError: libcudnn.so.7: cannot open shared object file: No such file or directory
```

It seems i'm missing CuDNN

**Comment by hawkinsp** [comment]
Yes, you have to provide your own CuDNN. We don't package it with jaxlib at the moment. (We may in the future.)

**Comment by hawkinsp** [comment]
Closing because there doesn't seem to be any action for us to take here.

**Comment by RylanSchaeffer** [comment]
@hawkinsp I'm receiving the same error `ImportError: libcusolver.so.10: cannot open shared object file: No such file or directory` but I don't want to use a GPU whatsoever. The source of the error appears to be `from . import xla_extension as _xla` inside `jaxlib/xla_client.py`. How do I disable XLA?

**Comment by hawkinsp** [comment]
@RylanSchaeffer You should install a non-GPU version of jaxlib.

**Comment by RylanSchaeffer** [comment]
ah, thank you

**Comment by RylanSchaeffer** [comment]
Wait, is there no way to install a JAX version that flexibly swaps between CPU and GPU?

**Comment by RylanSchaeffer** [comment]
I'm trying to run a repo with the following requirements:
```
jax==0.1.72
jaxlib @ https://storage.googleapis.com/jax-releases/cuda101/jaxlib-0.1.49-cp36-none-linux_x86_64.whl
```

Even if I want to run with CPU, this jaxlib requires a GPU to be available?
