### ISSUE TITLE
[Pallas GPU] `jnp.abs()` gives the wrong result

### ISSUE THREAD

**Issue by ayaka14732** [google/jax#23191]
### Description

```python
import functools
import jax
from jax.experimental import pallas as pl
import jax.numpy as jnp
import numpy as np

def main():
    @jax.jit
    @functools.partial(
        pl.pallas_call,
        out_shape=jax.ShapeDtypeStruct((4, 4), jnp.float32),
    )
    def kernel(x_ref, o_ref):
        o_ref[...] = jnp.abs(x_ref[...])

    val = -3.2
    x = jnp.full((4, 4), val)
    out = kernel(x)
    expected = jnp.abs(x)
    np.testing.assert_array_equal(out, expected)

if __name__ == '__main__':
    main()
```

Expected behaviour:

No error.

Actual behaviour:

```
2024-08-22 13:22:04.157537: W external/xla/xla/service/gpu/nvptx_compiler.cc:836] The NVIDIA driver's CUDA version is 12.5 which is older than the PTX compiler version (12.6.20). Because the driver is older than the PTX compiler version, XLA is disabling parallel compilation, which may slow down compilation. You should update your NVIDIA driver or use the NVIDIA-provided CUDA forward compatibility packages.
Traceback (most recent call last):
  File "/home/ayx/test/main.py", line 23, in <module>
    main()
  File "/home/ayx/test/main.py", line 20, in main
    np.testing.assert_array_equal(out, expected)
  File "/home/ayx/test/venv/lib/python3.12/site-packages/numpy/_utils/__init__.py", line 85, in wrapper
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ayx/test/venv/lib/python3.12/site-packages/numpy/testing/_private/utils.py", line 1025, in assert_array_equal
    assert_array_compare(operator.__eq__, actual, desired, err_msg=err_msg,
  File "/home/ayx/miniconda3/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ayx/test/venv/lib/python3.12/site-packages/numpy/testing/_private/utils.py", line 889, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

Mismatched elements: 16 / 16 (100%)
Max absolute difference among violations: 3.2
Max relative difference among violations: 1.
 ACTUAL: array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)
 DESIRED: array([[3.2, 3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2, 3.2]], dtype=float32)
```

I noticed that there would be no error if I change the line

```python
x = jnp.full((4, 4), val)
```

to

```python
x = jnp.full((4, 4), val, dtype=jnp.float32)
```

In other words, the error only happens when `weak_type` is True.

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.32.dev20240822+b56ed8eed
jaxlib: 0.4.31
numpy:  2.1.0
python: 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:12:24) [GCC 11.2.0]
jax.devices (1 total, 1 local): [CudaDevice(id=0)]
process_count: 1
platform: uname_result(system='Linux', node='ayx-gpu-test-1', release='5.15.0-1062-gcp', version='#70~20.04.1-Ubuntu SMP Fri May 24 20:12:18 UTC 2024', machine='x86_64')


$ nvidia-smi
Thu Aug 22 13:26:34 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.52.04              Driver Version: 555.52.04      CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-40GB          Off |   00000000:00:04.0 Off |                    0 |
| N/A   32C    P0             59W /  400W |     526MiB /  40960MiB |      3%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A     37173      G   /usr/lib/xorg/Xorg                             65MiB |
|    0   N/A  N/A     37257      G   /usr/bin/gnome-shell                           17MiB |
|    0   N/A  N/A     37977      C   python                                        416MiB |
+-----------------------------------------------------------------------------------------+
```

**Comment by ayaka14732** [comment]
Found the root cause.

The general issue is that `jnp.abs(x)` gives the wrong result if `x.weak_type` is `True`, but gives the correct result otherwise.

The problem is on this line:

https://github.com/google/jax/blob/b56ed8eeddc5794f3981832a38b6bcc195eb20f8/jax/_src/pallas/triton/lowering.py#L566-L569

If `aval.weak_type` is true, the code will always return `True`.

The aim of this code is to match a table of entries. As it always returns `True`, it matches the first entry it encounters, which is:

```python
_Extern(["int32"], "__nv_abs", "int32")
```

Since we are using a `float32` array, it's incorrect here to match the entry for `int32`, hence resulting the error.

### 1. But why is the result `0.`?

Generated MLIR:

```mlir
module @kernel {
  tt.func public @kernel(%arg0: !tt.ptr<f32> {tt.divisibility = 32 : i32}, %arg1: !tt.ptr<f32> {tt.divisibility = 32 : i32}) {
    %c0_i32 = arith.constant 0 : i32
    %c0_i32_0 = arith.constant 0 : i32
    %c4_i32 = arith.constant 4 : i32
    %0 = arith.muli %c0_i32, %c4_i32 : i32
    %c4_i32_1 = arith.constant 4 : i32
    %1 = arith.muli %c0_i32_0, %c4_i32_1 : i32
    %c0_i32_2 = arith.constant 0 : i32
    %c0_i32_3 = arith.constant 0 : i32
    %c4_i32_4 = arith.constant 4 : i32
    %2 = arith.muli %c0_i32_2, %c4_i32_4 : i32
    %c4_i32_5 = arith.constant 4 : i32
    %3 = arith.muli %c0_i32_3, %c4_i32_5 : i32
    %4 = tt.make_range {end = 4 : i32, start = 0 : i32} : tensor<4xi32>
    %5 = tt.expand_dims %4 {axis = 1 : i32} : tensor<4xi32> -> tensor<4x1xi32>
    %6 = tt.broadcast %5 : tensor<4x1xi32> -> tensor<4x4xi32>
    %7 = tt.splat %0 : i32 -> tensor<4x4xi32>
    %8 = arith.addi %6, %7 : tensor<4x4xi32>
    %c4_i32_6 = arith.constant 4 : i32
    %9 = tt.splat %c4_i32_6 : i32 -> tensor<4x4xi32>
    %10 = arith.muli %8, %9 : tensor<4x4xi32>
    %11 = tt.make_range {end = 4 : i32, start = 0 : i32} : tensor<4xi32>
    %12 = tt.expand_dims %11 {axis = 0 : i32} : tensor<4xi32> -> tensor<1x4xi32>
    %13 = tt.broadcast %12 : tensor<1x4xi32> -> tensor<4x4xi32>
    %14 = tt.splat %1 : i32 -> tensor<4x4xi32>
    %15 = arith.addi %13, %14 : tensor<4x4xi32>
    %c1_i32 = arith.constant 1 : i32
    %16 = tt.splat %c1_i32 : i32 -> tensor<4x4xi32>
    %17 = arith.muli %15, %16 : tensor<4x4xi32>
    %18 = tt.splat %arg0 : !tt.ptr<f32> -> tensor<4x4x!tt.ptr<f32>>
    %19 = tt.addptr %18, %10 : tensor<4x4x!tt.ptr<f32>>, tensor<4x4xi32>
    %20 = tt.addptr %19, %17 : tensor<4x4x!tt.ptr<f32>>, tensor<4x4xi32>
    %21 = tt.load %20 : tensor<4x4x!tt.ptr<f32>>
    %22 = arith.fptoui %21 : tensor<4x4xf32> to tensor<4x4xi32>
    %23 = tt.extern_elementwise %22 {libname = "", libpath = "", pure = true, symbol = "__nv_abs"} : (tensor<4x4xi32>) -> tensor<4x4xi32>
    %24 = tt.make_range {end = 4 : i32, start = 0 : i32} : tensor<4xi32>
    %25 = tt.expand_dims %24 {axis = 1 : i32} : tensor<4xi32> -> tensor<4x1xi32>
    %26 = tt.broadcast %25 : tensor<4x1xi32> -> tensor<4x4xi32>
    %27 = tt.splat %2 : i32 -> tensor<4x4xi32>
    %28 = arith.addi %26, %27 : tensor<4x4xi32>
    %c4_i32_7 = arith.constant 4 : i32
    %29 = tt.splat %c4_i32_7 : i32 -> tensor<4x4xi32>
    %30 = arith.muli %28, %29 : tensor<4x4xi32>
    %31 = tt.make_range {end = 4 : i32, start = 0 : i32} : tensor<4xi32>
    %32 = tt.expand_dims %31 {axis = 0 : i32} : tensor<4xi32> -> tensor<1x4xi32>
    %33 = tt.broadcast %32 : tensor<1x4xi32> -> tensor<4x4xi32>
    %34 = tt.splat %3 : i32 -> tensor<4x4xi32>
    %35 = arith.addi %33, %34 : tensor<4x4xi32>
    %c1_i32_8 = arith.constant 1 : i32
    %36 = tt.splat %c1_i32_8 : i32 -> tensor<4x4xi32>
    %37 = arith.muli %35, %36 : tensor<4x4xi32>
    %38 = tt.splat %arg1 : !tt.ptr<f32> -> tensor<4x4x!tt.ptr<f32>>
    %39 = tt.addptr %38, %30 : tensor<4x4x!tt.ptr<f32>>, tensor<4x4xi32>
    %40 = tt.addptr %39, %37 : tensor<4x4x!tt.ptr<f32>>, tensor<4x4xi32>
    %41 = tt.load %40 : tensor<4x4x!tt.ptr<f32>>
    %42 = arith.uitofp %23 : tensor<4x4xi32> to tensor<4x4xf32>
    tt.store %40, %42 : tensor<4x4x!tt.ptr<f32>>
    tt.return
  }
}
```

Notice the 2 lines:

```
%22 = arith.fptoui %21 : tensor<4x4xf32> to tensor<4x4xi32>
```

and

```
%42 = arith.uitofp %23 : tensor<4x4xi32> to tensor<4x4xf32>
```

Here, since we are now incorrectly expecting an `int32` oprand, Pallas will convert the `float32` input to `uint32` using `arith.fptoui`, and convert the result back to `float32`.

Documentation of [`arith.fptoui`](https://mlir.llvm.org/docs/Dialects/ArithOps/#arithfptoui-arithfptouiop): Cast from a value interpreted as floating-point to the nearest (rounding towards zero) unsigned integer value.

Therefore, `-3.2` is cast into `0.`.

### 2. But why does Pallas cast it into \*unsigned\* `uint32` instead of signed `int32`?

The type conversion happens here:

https://github.com/google/jax/blob/b56ed8eeddc5794f3981832a38b6bcc195eb20f8/jax/_src/pallas/triton/lowering.py#L611-L612

which calls

https://github.com/google/jax/blob/b56ed8eeddc5794f3981832a38b6bcc195eb20f8/jax/_src/pallas/triton/lowering.py#L1471-L1480

Notice this line:

```python
signed=jnp.issubdtype(src_type, jnp.signedinteger)
```

Since `src_type` is `float32`, it's definitely not a subdtype of `jnp.signedinteger`. Therefore, `signed` is `False` and it is cast into \*unsigned\* `uint32`.

### 3. Why does only `jnp.abs()` have this problem?

`jnp.abs()` is currently the only operation that works for both `int` and `float`. For operations that only work for `float`, no `int` entry will be matched and therefore the type conversion will not be triggered.
