### ISSUE TITLE
`jax.nn.dot_product_attention(...implementation='cudnn')` throws error `libnvrtc.so.12` not found

### ISSUE THREAD

**Issue by danjenson** [google/jax#23227]
### Description

I am calling `jax.nn.dot_product_attention` with the following line:
```python
ctx = dot_product_attention(qs, ks, vs, is_causal=True, implementation="cudnn")
```
However, this throws the following error:
```
2024-08-25 00:37:01.671910: W external/xla/xla/service/gpu/nvptx_compiler.cc:836] The NVIDIA driver's CUDA version is 12.4 which is older than the PTX compiler version (12.5.82). Because the driver is older than the PTX compiler version, XLA is disabling parallel compilation, which may slow down compilation. You should update your NVIDIA driver or use the NVIDIA-provided CUDA forward compatibility packages.
Could not load library libnvrtc.so.12. Error: libnvrtc.so.12: cannot open shared object file: No such file or directory
Could not load library libnvrtc.so. Error: libnvrtc.so: cannot open shared object file: No such file or directory
Could not load library libnvrtc.so.12. Error: libnvrtc.so.12: cannot open shared object file: No such file or directory
Could not load library libnvrtc.so. Error: libnvrtc.so: cannot open shared object file: No such file or directory
Could not load library libnvrtc.so.12. Error: libnvrtc.so.12: cannot open shared object file: No such file or directory
Could not load library libnvrtc.so. Error: libnvrtc.so: cannot open shared object file: No such file or directory
Could not load library libnvrtc.so.12. Error: libnvrtc.so.12: cannot open shared object file: No such file or directory
Could not load library libnvrtc.so. Error: libnvrtc.so: cannot open shared object file: No such file or directory
Could not load library libnvrtc.so.12. Error: libnvrtc.so.12: cannot open shared object file: No such file or directory
Could not load library libnvrtc.so. Error: libnvrtc.so: cannot open shared object file: No such file or directory
Could not load library libnvrtc.so.12. Error: libnvrtc.so.12: cannot open shared object file: No such file or directory
Could not load library libnvrtc.so. Error: libnvrtc.so: cannot open shared object file: No such file or directory
Error executing job with overrides: ['data=shakespeare-full', 'model=gpt-2', 'wandb=False', 'data.train_num_steps=101']
Traceback (most recent call last):
  File "/data/repos/lore/./train.py", line 81, in main
    state = train(
            ^^^^^^
  File "/data/repos/lore/./train.py", line 120, in train
    params = model.init(rng_init, token_ids)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/repos/lore/gpt.py", line 73, in __call__
    x = blk(x, training)
        ^^^^^^^^^^^^^^^^
  File "/data/repos/lore/gpt.py", line 45, in __call__
    x += MultiheadCausalAttention(
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/repos/lore/gpt.py", line 22, in __call__
    ctx = dot_product_attention(qs, ks, vs, is_causal=True, implementation="cudnn")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danj/.pyenv/versions/jax/lib/python3.12/site-packages/jax/_src/nn/functions.py", line 911, in dot_product_attention
    return cudnn_dot_product_attention(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danj/.pyenv/versions/jax/lib/python3.12/site-packages/jax/_src/cudnn/fused_attention_stablehlo.py", line 1029, in dot_product_attention
    output = _dot_product_attention(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danj/.pyenv/versions/jax/lib/python3.12/site-packages/jax/_src/cudnn/fused_attention_stablehlo.py", line 930, in _dot_product_attention
    output = _dot_product_attention_fwd(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danj/.pyenv/versions/jax/lib/python3.12/site-packages/jax/_src/cudnn/fused_attention_stablehlo.py", line 326, in _dot_product_attention_fwd
    outputs = _dot_product_attention_fwd_p_wrapper.bind(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danj/.pyenv/versions/jax/lib/python3.12/site-packages/jax/_src/cudnn/fused_attention_stablehlo.py", line 365, in _dot_product_attention_fwd_impl
    outputs = _dot_product_attention_fwd_p.bind(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: No valid engine configs for Matmul_MUL_GEN_INDEX_GEN_INDEX_CMP_GE_BINARY_SELECT_Reduction_SUB_EXP_Reduction_LOG_ADD_DIV_Matmul_
in external/xla/xla/stream_executor/cuda/cuda_dnn.cc(8362): 'graph_.create_execution_plans({cudnn_frontend::HeurMode_t::A})'
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```
I have tried installing both regular and nightly:
`pip install -U "jax[cuda12]"`
`pip install -U --pre jax[cuda12] -f https://storage.googleapis.com/jax-releases/jax_nightly_releases.html`

I also tried to install the nvrtc library independently with:
`pip install nvidia-cuda-nvrtc-cu12`

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.31
jaxlib: 0.4.31
numpy:  1.26.4
python: 3.12.2 (main, Mar  2 2024, 09:51:01) [GCC 13.2.0]
jax.devices (1 total, 1 local): [CudaDevice(id=0)]
process_count: 1
platform: uname_result(system='Linux', node='ghost', release='6.6.47_1', version='#1 SMP PREEMPT_DYNAMIC Mon Aug 19 16:42:31 UTC 2024', machine='x86_64')


$ nvidia-smi
Sun Aug 25 00:45:36 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.107.02             Driver Version: 550.107.02     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090        Off |   00000000:01:00.0 Off |                  Off |
| 32%   36C    P2             78W /  480W |     393MiB /  24564MiB |      3%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |```
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      5145      C   ...ions/3.12.2/envs/jax/bin/python3.12        386MiB |
+-----------------------------------------------------------------------------------------+
```

**Comment by danjenson** [comment]
This had to do with a CUDA toolkit on Void Linux, which has been resolved.

**Comment by samos123** [comment]
I am hitting the same or similar issue:
```
    self._trainer_state, outputs = self._jit_train_step(self._trainer_state, input_batch)
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: No valid engine configs for Matmul_MUL_GEN_INDEX_GEN_INDEX_CMP_GE_BINARY_SELECT_Reduction_SUB_EXP_Reduction_LOG_ADD_DIV_Matmul_
in external/xla/xla/stream_executor/cuda/cuda_dnn.cc(8382): 'graph_.create_execution_plans({cudnn_frontend::HeurMode_t::A})' 
```

Do you have any more details on what the issue was with CUDA toolkit? @danjenson

**Comment by guyujun** [comment]
> I am hitting the same or similar issue:
> 
> ```
>     self._trainer_state, outputs = self._jit_train_step(self._trainer_state, input_batch)
> jaxlib.xla_extension.XlaRuntimeError: INTERNAL: No valid engine configs for Matmul_MUL_GEN_INDEX_GEN_INDEX_CMP_GE_BINARY_SELECT_Reduction_SUB_EXP_Reduction_LOG_ADD_DIV_Matmul_
> in external/xla/xla/stream_executor/cuda/cuda_dnn.cc(8382): 'graph_.create_execution_plans({cudnn_frontend::HeurMode_t::A})' 
> ```
> 
> Do you have any more details on what the issue was with CUDA toolkit? [@danjenson](https://github.com/danjenson)

same, running training using RTX4090. 

```
    td.train()
  File "/home/weikun/workspace/pallatom/Pallatom/train/training.py", line 667, in train
    self.params, self.opt_state, self.accumu_g, aux = jax.pmap(train_step, in_axes=(0,0,0,0,0,0,None), axis_name="pbatch",
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: No valid engine configs for Matmul_MUL_GEN_INDEX_GEN_INDEX_CMP_GE_BINARY_SELECT_Reduction_SUB_EXP_Reduction_LOG_ADD_DIV_Matmul_
in external/xla/xla/stream_executor/cuda/cuda_dnn.cc(8426): 'graph_.create_execution_plans({cudnn_frontend::HeurMode_t::A})' 
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```

any updates?
