### ISSUE TITLE
An error from a combination of scan, complex numbers, and np.diag

### ISSUE THREAD

**Issue by XiaotongNi** [google/jax#2325]
A very high level summary: I got an error when I did some complex number computation inside a lax.scan function (compute1 in the code below). But the almost identical code can be run with a for loop (compute2). Only gradient computation raises the error. Forward computation is fine for both method. If I replace np.diag(d) with v in the function f, then also no error.

```python
import jax.numpy as np
from jax import grad, random, jit, lax

def f(carrier, x):
    h =  x*np.array([[0, 1j], [-1j, 0]])
    d, v = np.linalg.eigh(h, symmetrize_input=False)
    carrier = np.diag(d) @ carrier
    return carrier, None

def compute1(p):
    u = np.eye(2, dtype=np.complex64)
    carrier, _ = lax.scan(f, u, p)
    return np.abs(np.trace(carrier))

def compute2(p):
    u = np.eye(2, dtype=np.complex64)
    for i in range(3):
        h =  p[i]*np.array([[0, 1j], [-1j, 0]])

        d, v = np.linalg.eigh(h, symmetrize_input=False)
        u = np.diag(d) @ u
    return np.abs(np.trace(u))

print(grad(compute1)(np.arange(2,5,dtype=np.complex64)))
# print(compute1(np.arange(2,5,dtype=np.complex64)))
```

Error message:
/home/xiaotongni/miniconda3/lib/python3.7/site-packages/jax/lib/xla_bridge.py:122: UserWarning: No GPU/TPU found, falling back to CPU.
  warnings.warn('No GPU/TPU found, falling back to CPU.')
Traceback (most recent call last):
  File "/home/xiaotongni/jax-qoc/test_scan.py", line 24, in <module>
    print(grad(compute1)(np.arange(2,5,dtype=np.complex64)))
  File "/home/xiaotongni/miniconda3/lib/python3.7/site-packages/jax/api.py", line 352, in grad_f
    _, g = value_and_grad_f(*args, **kwargs)
  File "/home/xiaotongni/miniconda3/lib/python3.7/site-packages/jax/api.py", line 407, in value_and_grad_f
    ans, vjp_py = vjp(f_partial, *dyn_args)
  File "/home/xiaotongni/miniconda3/lib/python3.7/site-packages/jax/api.py", line 1285, in vjp
    out_primal, out_vjp = ad.vjp(flat_fun, primals_flat)
  File "/home/xiaotongni/miniconda3/lib/python3.7/site-packages/jax/interpreters/ad.py", line 106, in vjp
    out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
  File "/home/xiaotongni/miniconda3/lib/python3.7/site-packages/jax/interpreters/ad.py", line 95, in linearize
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr(jvpfun_flat, in_pvals)
  File "/home/xiaotongni/miniconda3/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 354, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/home/xiaotongni/miniconda3/lib/python3.7/site-packages/jax/linear_util.py", line 149, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/xiaotongni/jax-qoc/test_scan.py", line 12, in compute1
    carrier, _ = lax.scan(f, u, p)
  File "/home/xiaotongni/miniconda3/lib/python3.7/site-packages/jax/lax/lax_control_flow.py", line 804, in scan
    linear=(False,) * (len(consts) + len(in_flat)))
  File "/home/xiaotongni/miniconda3/lib/python3.7/site-packages/jax/lax/lax_control_flow.py", line 1166, in scan_bind
    num_carry=num_carry, linear=linear)
  File "/home/xiaotongni/miniconda3/lib/python3.7/site-packages/jax/core.py", line 182, in bind
    out_tracer = top_trace.process_primitive(self, tracers, kwargs)
  File "/home/xiaotongni/miniconda3/lib/python3.7/site-packages/jax/interpreters/ad.py", line 305, in process_primitive
    primal_out, tangent_out = jvp(primals_in, tangents_in, **params)
  File "/home/xiaotongni/miniconda3/lib/python3.7/site-packages/jax/lax/lax_control_flow.py", line 865, in _scan_jvp
    jaxpr, nonzeros, instantiate=carry_nz + [False] * num_ys)
  File "/home/xiaotongni/miniconda3/lib/python3.7/site-packages/jax/interpreters/ad.py", line 575, in jvp_jaxpr
    jaxpr_out, pvals_out, literals_out = pe.trace_to_jaxpr(f_jvp, pvals, instantiate=True)
  File "/home/xiaotongni/miniconda3/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 354, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/home/xiaotongni/miniconda3/lib/python3.7/site-packages/jax/linear_util.py", line 149, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/xiaotongni/miniconda3/lib/python3.7/site-packages/jax/core.py", line 97, in jaxpr_as_fun
    return eval_jaxpr(typed_jaxpr.jaxpr, typed_jaxpr.literals, *args)
  File "/home/xiaotongni/miniconda3/lib/python3.7/site-packages/jax/core.py", line 251, in eval_jaxpr
    ans = eqn.primitive.bind(*(subfuns + in_vals), **params)
  File "/home/xiaotongni/miniconda3/lib/python3.7/site-packages/jax/core.py", line 182, in bind
    out_tracer = top_trace.process_primitive(self, tracers, kwargs)
  File "/home/xiaotongni/miniconda3/lib/python3.7/site-packages/jax/interpreters/ad.py", line 305, in process_primitive
    primal_out, tangent_out = jvp(primals_in, tangents_in, **params)
  File "/home/xiaotongni/miniconda3/lib/python3.7/site-packages/jax/interpreters/ad.py", line 388, in linear_jvp
    val_out = primitive.bind(*primals, **params)
  File "/home/xiaotongni/miniconda3/lib/python3.7/site-packages/jax/core.py", line 182, in bind
    out_tracer = top_trace.process_primitive(self, tracers, kwargs)
  File "/home/xiaotongni/miniconda3/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 98, in process_primitive
    return self.default_process_primitive(primitive, tracers, params)
  File "/home/xiaotongni/miniconda3/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 106, in default_process_primitive
    out_aval = primitive.abstract_eval(*avals, **params)
  File "/home/xiaotongni/miniconda3/lib/python3.7/site-packages/jax/lax/lax.py", line 1523, in standard_abstract_eval
    return ShapedArray(shape_rule(*args, **kwargs), dtype_rule(*args, **kwargs))
  File "/home/xiaotongni/miniconda3/lib/python3.7/site-packages/jax/lax/lax.py", line 2484, in _pad_dtype_rule
    raise TypeError(msg.format(operand.dtype, padding_value.dtype))
TypeError: pad operand and padding_value must be same dtype: got complex64 and float32.

**Comment by hawkinsp** [comment]
This turned out to be a bug in the gradient rule for complex `eigh`; it was producing complex eigenvalues when it should have produced real eigenvalues. Sorry for the slow fix!
