### ISSUE TITLE
Cannot pass constant to `lax.fori_loop` body inside pallas kernel

### ISSUE THREAD

**Issue by lengstrom** [google/jax#23301]
### Description

Hi,

I have a basic reproduction of an issue I've been facing where I cannot pass a constant inside of a `fori_loop` in a pallas kernel on jax nightly:

```
import jax
from jax import numpy as jnp
from jax.experimental import pallas as pl
from jax import lax
import functools

def kernel_func(A_ref, out_ref, scale: float, blocks: int, N: int):
    accum = jnp.zeros((N, N), dtype=jnp.float32)
    def body(idx, accum):
        tile = pl.load(A_ref, (idx, pl.dslice(None), pl.dslice(None)))
        accum += tile * scale
        return accum

    out_tile = lax.fori_loop(0, blocks, body, accum)
    pl.store(out_ref, (pl.dslice(None), pl.dslice(None)), out_tile)
    
@jax.jit
def f(A, scale):
    blocks, N, _ = A.shape
    grid = (1, 1)
    in_specs = [ pl.BlockSpec(lambda r, c: (0, 0, 0), (blocks, N, N)) ]

    kernel = functools.partial(kernel_func, scale=scale, blocks=blocks, N=N)
    out = pl.pallas_call(
        kernel, grid=grid, in_specs=in_specs,
        out_shape=jax.ShapeDtypeStruct((N, N), A.dtype), 
        name="f"
    )(A)
    return out

N = 64
A = jax.random.uniform(jax.random.PRNGKey(0), (5, N, N), dtype=jnp.float32)

C = f(A, 1.1)
print(C)
```
yields
```
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/xfs/home/engstrom/src/backward-backward/issue.py", line 34, in <module>
    C = f(A, 1.1)
  File "/mnt/xfs/home/engstrom/src/backward-backward/issue.py", line 24, in f
    out = pl.pallas_call(
  File "/mnt/xfs/home/engstrom/conda_envs/ajax/lib/python3.10/site-packages/jax/_src/pallas/pallas_call.py", line 1359, in wrapped
    jaxpr = _trace_kernel_to_jaxpr(
  File "/mnt/xfs/home/engstrom/conda_envs/ajax/lib/python3.10/site-packages/jax/_src/pallas/pallas_call.py", line 1123, in _trace_kernel_to_jaxpr
    raise ValueError(
ValueError: The kernel function in the pallas_call kernel_func at /mnt/xfs/home/engstrom/src/backward-backward/issue.py:7 captures constants [ShapedArray(float32[], weak_type=True)]. You should pass them as inputs
```
I am not sure what it means to pass these as inputs, it feels like bad practice to pass these values through the carry if they are just constants. Is there a different way of doing this, or is this a bug?

### System info (python version, jaxlib version, accelerator, etc.)

```
Python 3.10.14 (main, Mar 21 2024, 16:24:04) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jax; jax.print_environment_info()

jax:    0.4.32.dev20240827
jaxlib: 0.4.31
numpy:  1.26.4
python: 3.10.14 (main, Mar 21 2024, 16:24:04) [GCC 11.2.0]
jax.devices (1 total, 1 local): [CudaDevice(id=0)]
process_count: 1
platform: uname_result(system='Linux', node='deep-chungus-10.csail.mit.edu', release='5.15.0-113-generic', version='#123-Ubuntu SMP Mon Jun 10 08:16:17 UTC 2024', machine='x86_64')


$ nvidia-smi
Wed Aug 28 15:35:43 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100 80GB PCIe          On  |   00000000:01:00.0 Off |                    0 |
| N/A   41C    P0             65W /  300W |     425MiB /  81920MiB |      2%      Default |
```

**Comment by justinjfu** [comment]
You need to make `scale` a static argument to `f`. e.g.
```
@functools.partial(jax.jit, static_argnames=['scale'])
def f(A, scale):
  ...
```

Otherwise, it is not actually being interpreted as a constant by JAX since the function does not know what value `scale` will be during jit compilation.
