### ISSUE TITLE
[Pallas GPU] `jnp.pow()` triggers dtype promotion when it should not

### ISSUE THREAD

**Issue by ayaka14732** [google/jax#23337]
### Description

I am testing with `jax_numpy_dtype_promtion` set to `strict`.

```python
import functools
import jax
from jax.experimental import pallas as pl
import jax.numpy as jnp

jax.config.update('jax_numpy_dtype_promotion', 'strict')

def main():
    @functools.partial(
        pl.pallas_call,
        out_shape=jax.ShapeDtypeStruct((), jnp.float32),
    )
    def pow_kernel(x_ref, i_ref, o_ref):
      o_ref[...] = jnp.pow(x_ref[...], i_ref[...])

    x = jnp.array(2, dtype=jnp.float32)
    i = jnp.array(2, dtype=jnp.int32)

    print(pow_kernel(x, i))

if __name__ == '__main__':
    main()
```

Expected behavior:

Output 4.0

Actual behavior:

```
Traceback (most recent call last):
  File "/home/ayx/jax/1.py", line 22, in <module>
    main()
  File "/home/ayx/jax/1.py", line 19, in main
    print(pow_kernel(x, i))
          ^^^^^^^^^^^^^^^^
  File "/home/ayx/jax/jax/_src/pallas/pallas_call.py", line 1359, in wrapped
    jaxpr = _trace_kernel_to_jaxpr(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ayx/jax/jax/_src/pallas/pallas_call.py", line 1118, in _trace_kernel_to_jaxpr
    jaxpr, _, consts, () = pe.trace_to_jaxpr_dynamic(wrapped_kernel_fun,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ayx/jax/1.py", line 14, in pow_kernel
    o_ref[...] = jnp.pow(x_ref[...], i_ref[...])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ayx/jax/jax/_src/numpy/ufuncs.py", line 821, in power
    return _power(x1, x2)
           ^^^^^^^^^^^^^^
  File "/home/ayx/jax/jax/_src/numpy/ufuncs.py", line 831, in _power
    x1_, x2_ = promote_args_numeric("power", x1, x2)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ayx/jax/jax/_src/numpy/util.py", line 375, in promote_args_numeric
    return promote_shapes(fun_name, *promote_dtypes_numeric(*args))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ayx/jax/jax/_src/numpy/util.py", line 283, in promote_dtypes_numeric
    to_dtype, weak_type = dtypes._lattice_result_type(*args)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jax._src.dtypes.TypePromotionError: Input dtypes ('int32', 'float32') have no available implicit dtype promotion path when jax_numpy_dtype_promotion=strict. Try explicitly casting inputs to the desired output type, or set jax_numpy_dtype_promotion=standard.
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```

Notice that if we just do `jnp.pow(x, i)`, the program would run successfully without errors.

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.32.dev20240830+4342c0c0f
jaxlib: 0.4.31
numpy:  2.1.0
python: 3.12.3 (main, Jul 31 2024, 17:43:48) [GCC 13.2.0]
jax.devices (1 total, 1 local): [CudaDevice(id=0)]
process_count: 1
platform: uname_result(system='Linux', node='ayx-gpu-test-3.us-central1-f.c.jax-dev.internal', release='6.8.0-1013-gcp', version='#14-Ubuntu SMP Thu Aug  8 23:18:23 UTC 2024', machine='x86_64')


$ nvidia-smi
Fri Aug 30 12:16:52 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-40GB          Off |   00000000:00:04.0 Off |                    0 |
| N/A   33C    P0             64W /  400W |     429MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      4525      C   python                                        416MiB |
+-----------------------------------------------------------------------------------------+
```

**Comment by ayaka14732** [comment]
The `('int32', 'float32')` should work because there is such entry in the dispatch table:

https://github.com/google/jax/blob/1dff3a2c71275c083cc3feb4f3526be50d2ba06c/jax/_src/pallas/triton/lowering.py#L775-L782

**Comment by ayaka14732** [comment]
This also happens to vanilla JAX under jit, i.e. `jax.jit(jnp.pow)(x, i)`

**Comment by jakevdp** [comment]
> This also happens to vanilla JAX under jit, i.e. `jax.jit(jnp.pow)(x, i)`

This is the intended behavior, I think. `jnp.power(float_array, int)` only works without type promotion for static integers, in which case it lowers to `lax.integer_pow`. If the second argument is non-static, then it must be type-promoted in order to be compatible with `lax.pow`.

So under JIT or another transformation, this will require promotion. Absent a transformation, it can be done without promotion.
