### ISSUE TITLE
jnp.vectorize causes ```FloatingPointError: invalid value (nan)``` when there is no nan returned.

### ISSUE THREAD

**Issue by PeishiJiang** [google/jax#23389]
### Description

Hi,

My vectorized function complains ```FloatingPointError: invalid value (nan) encountered in jit(pow).``` when ```jax_debug_nans``` is set to ```True```. The function returns no ```nan``` if this environment variable is turned off. Is there a potential bug causing the issue?

Below is the sample code --
```python
import jax
import jax.numpy as jnp

jax.config.update("jax_debug_nans", True)

@jnp.vectorize
def func(x_e):
    return jax.lax.cond(
            x_e > 0,
            lambda: jnp.power(1.0 + x_e, -0.75),
            lambda: jnp.power(1.0 + x_e, -2.0),
        )

x = jnp.array([-3.6927774, 1.5781837])

# Would print "[0.13791107 0.49148992]" if jax_debug_nans is turned off
print(func(x))
```

It will throw out the error -- 
```
--------------------

The above exception was the direct cause of the following exception:

jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jian449/Library/CloudStorage/OneDrive-PNNL/Codes/jax-watershed/examples/debug_nan.py", line 112, in <module>
    func(x)
  File "/Users/jian449/anaconda3/envs/jax-canoak/lib/python3.10/site-packages/jax/_src/numpy/vectorize.py", line 321, in wrapped
    result = vectorized_func(*squeezed_args)
  File "/Users/jian449/anaconda3/envs/jax-canoak/lib/python3.10/site-packages/jax/_src/numpy/vectorize.py", line 138, in wrapped
    out = func(*args)
  File "/Users/jian449/Library/CloudStorage/OneDrive-PNNL/Codes/jax-watershed/examples/debug_nan.py", line 104, in func
    return jax.lax.cond(
FloatingPointError: invalid value (nan) encountered in jit(pow). Because jax_config.debug_nans.value and/or config.jax_debug_infs is set, the de-optimized function (i.e., the function as if the `jit` decorator were removed) was called in an attempt to get a more precise error message. However, the de-optimized function did not produce invalid values during its execution. This behavior can result from `jit` optimizations causing the invalid value to be produced. It may also arise from having nan/inf constants as outputs, like `jax.jit(lambda ...: jax.numpy.nan)(...)`.
```

Thanks in advance!
Peishi

### System info (python version, jaxlib version, accelerator, etc.)

System information --
```
jax:    0.4.26
jaxlib: 0.4.26
numpy:  1.26.4
python: 3.10.0 | packaged by conda-forge | (default, Nov 20 2021, 02:27:15) [Clang 11.1.0 ]
jax.devices (1 total, 1 local): [CpuDevice(id=0)]
process_count: 1
platform: uname_result(system='Darwin', node='WE46779', release='23.6.0', version='Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000', machine='arm64')
```

**Comment by f0uriest** [comment]
When you vectorize lax.cond it becomes lax.select which evaluates both branches and discards one, but in your case it would still create a nan as an intermediate value due to the fractional power of a negative number

**Comment by PeishiJiang** [comment]
> When you vectorize lax.cond it becomes lax.select which evaluates both branches and discards one, but in your case it would still create a nan as an intermediate value due to the fractional power of a negative number

Thanks for the reply! The conversion to ```jax.lax.select``` when using ```vectorize``` or ```vmap``` is likely the reason. Is there a way to get around this? Note that I intentionally used the conditioning to avoid calculating the fractional power of negative values.

**Comment by f0uriest** [comment]
Usually some version of the "double where trick": https://jax.readthedocs.io/en/latest/faq.html#gradients-contain-nan-where-using-where

**Comment by PeishiJiang** [comment]
> Usually some version of the "double where trick": https://jax.readthedocs.io/en/latest/faq.html#gradients-contain-nan-where-using-where

Thank you for the suggestion. In a similar spirit, I can now resolve this issue by changing the codes as --
```python
import jax
import jax.numpy as jnp

jax.config.update("jax_debug_nans", True)

@jnp.vectorize
def exp_func(x_e):
    return jax.lax.cond(
        x_e > 0,
        lambda: -0.75,
        lambda: -2.0
    )
def func(x):
    return jnp.power(1.0+x, exp_func(x))

x = jnp.array([-3.6927774, 1.5781837])
print(func(x))
```
