### ISSUE TITLE
`NNFunctionsTest.testDotProductAttention` failing on A100/H100 with `use_vmap=True, `impl='cudnn'`

### ISSUE THREAD

**Issue by belitskiy** [google/jax#23401]
### Description

```
Traceback (most recent call last):
  File "absl/testing/parameterized.py", line 321, in bound_param_test
    return test_method(self, **testcase_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "jax/tests/nn_test.py", line 87, in testDotProductAttention
    out_ans, sdpa_vjp_ans = jax.vjp(sdpa_ans, Q, K, V, bias, mask)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "jax/_src/api.py", line 2187, in vjp
    return _vjp(
           ^^^^^
  File "jax/_src/api.py", line 2196, in _vjp
    out_primals, vjp = ad.vjp(flat_fun, primals_flat)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "jax/_src/interpreters/ad.py", line 143, in vjp
    out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "jax/_src/interpreters/ad.py", line 132, in linearize
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr_nounits(jvpfun_flat, in_pvals)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "jax/_src/profiler.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "jax/_src/interpreters/partial_eval.py", line 777, in trace_to_jaxpr_nounits
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
                                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "jax/_src/linear_util.py", line 193, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "jax/_src/traceback_util.py", line 180, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "jax/_src/api.py", line 1226, in vmap_f
    out_flat = batching.batch(
               ^^^^^^^^^^^^^^^
  File "jax/_src/linear_util.py", line 193, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "jax/_src/nn/functions.py", line 1011, in dot_product_attention
    out = cudnn_dot_product_attention(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "jax/_src/cudnn/fused_attention_stablehlo.py", line 1059, in dot_product_attention
    output = _dot_product_attention(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "jax/_src/traceback_util.py", line 180, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "jax/_src/custom_derivatives.py", line 642, in __call__
    out_flat = custom_vjp_call_p.bind(flat_fun, flat_fwd, flat_bwd,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "jax/_src/custom_derivatives.py", line 833, in bind
    outs = top_trace.process_custom_vjp_call(self, fun, fwd, bwd_, tracers,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "jax/_src/interpreters/batching.py", line 572, in process_custom_vjp_call
    out_vals = prim.bind(fun, fwd, bwd, *in_vals, out_trees=out_trees,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "jax/_src/custom_derivatives.py", line 833, in bind
    outs = top_trace.process_custom_vjp_call(self, fun, fwd, bwd_, tracers,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "jax/_src/interpreters/ad.py", line 396, in process_custom_vjp_call
    res_and_primals_out = fwd.call_wrapped(*fwd_in)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "jax/_src/linear_util.py", line 193, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "jax/_src/cudnn/fused_attention_stablehlo.py", line 345, in _dot_product_attention_fwd_rule
    outputs = _dot_product_attention_fwd_p_wrapper.bind(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "jax/_src/core.py", line 429, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "jax/_src/core.py", line 433, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "jax/_src/interpreters/batching.py", line 442, in process_primitive
    val_out, dim_out = batched_primitive(vals_in, dims_in, **params)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "jax/_src/cudnn/fused_attention_stablehlo.py", line 646, in _dot_product_attention_fwd_batcher
    outputs = _dot_product_attention_fwd_p_wrapper.bind(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "jax/_src/core.py", line 429, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "jax/_src/core.py", line 433, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "jax/_src/core.py", line 939, in process_primitive
    return primitive.impl(*tracers, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _dot_product_attention_fwd_impl() missing 1 required positional argument: 'sliding_window_length'
```

### System info (python version, jaxlib version, accelerator, etc.)

N/A

**Comment by belitskiy** [comment]
@Cjkkkk
Hi, please take a look.

**Comment by hawkinsp** [comment]
I think this was already fixed by https://github.com/google/jax/pull/23393
