### ISSUE TITLE
Pallas flash attention fails on GPU

### ISSUE THREAD

**Issue by knyazer** [google/jax#23495]
### Description

Trying to use flash attention on a GPU, hitting a Value error straight away.

code:
```
from jax.experimental.pallas.ops.tpu import flash_attention as attn_lib
x = jnp.ones((2, 32, 1024, 128), dtype=jnp.float32)
out = attn_lib.flash_attention(x, x, x)
```

error:
```
Traceback (most recent call last):
  File "...", line 19, in <module>
    out = attn_lib.flash_attention(x, x, x)
  File "/home/dev/.local/lib/python3.11/site-packages/jax/experimental/pallas/ops/tpu/flash_attention.py", line 198, in flash_attention
    return _flash_attention(
  File "/home/dev/.local/lib/python3.11/site-packages/jax/experimental/pallas/ops/tpu/flash_attention.py", line 216, in _flash_attention
    return _flash_attention_impl(
  File "/home/dev/.local/lib/python3.11/site-packages/jax/experimental/pallas/ops/tpu/flash_attention.py", line 737, in _flash_attention_impl
    o, *aux = pl.pallas_call(
  File "/home/dev/.local/lib/python3.11/site-packages/jax/_src/pallas/pallas_call.py", line 1106, in wrapped
    out_flat = pallas_call_p.bind(
jax._src.source_info_util.JaxStackTraceBeforeTransformation: ValueError: safe_zip() argument 2 is shorter than argument 1

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/run/host/home/knyaz/workspace/nano_jax_gpt/model.py", line 19, in <module>
    out = attn_lib.flash_attention(x, x, x)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dev/.local/lib/python3.11/site-packages/jax/_src/pallas/pallas_call.py", line 948, in _pallas_call_lowering
    return mlir.lower_per_platform(ctx, "pallas_call",
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dev/.local/lib/python3.11/site-packages/jax/_src/pallas/pallas_call.py", line 944, in gpu_lowering
    return pallas_call_registration.pallas_call_lowering(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dev/.local/lib/python3.11/site-packages/jax/_src/pallas/triton/pallas_call_registration.py", line 73, in pallas_call_lowering
    lowering_result = lowering.lower_jaxpr_to_triton_module(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dev/.local/lib/python3.11/site-packages/jax/_src/pallas/triton/lowering.py", line 335, in lower_jaxpr_to_triton_module
    () = lower_jaxpr_to_triton_ir(ctx, jaxpr, block_infos, *entry.arguments)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dev/.local/lib/python3.11/site-packages/jax/_src/pallas/triton/lowering.py", line 361, in lower_jaxpr_to_triton_ir
    for invar, block_info in zip(jaxpr.invars, block_infos):
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: safe_zip() argument 2 is shorter than argument 1
```

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.31
jaxlib: 0.4.31
numpy:  1.26.4
python: 3.11.9 (main, Apr  6 2024, 17:59:24) [GCC 11.4.0]
jax.devices (1 total, 1 local): [CudaDevice(id=0)]
process_count: 1
platform: uname_result(system='Linux', node='dev.knyaz', release='6.8.0-40-generic', version='#40~22.04.3-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 30 17:30:19 UTC 2', machine='x86_64')


$ nvidia-smi
Sun Sep  8 11:36:36 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2
```

**Comment by knyazer** [comment]
I wonder, is it actually supposed to work on GPU? I was always assuming that Pallas should feel no difference between a TPU and GPU, but maybe there is a difference? I don't know..

**Comment by knyazer** [comment]
Right, so this works:```    from jax.experimental.pallas.ops.gpu import attention

    bs = 2
    seqlen = 1024
    n_heads = 32
    dim = 128
    x = jnp.ones((bs, n_heads, seqlen, dim), dtype=jnp.float32)
    out = attention.mha(x, x, x, None, causal=True)
```
So I will just stick with the correct ops. Sorry for the noise!
