### ISSUE TITLE
add support for QR decomposition gradient calculation for wide matrices (rows > columns)

### ISSUE THREAD

**Issue by rlucas7** [google/jax#23533]
Please:

- [x] Check for duplicate requests.
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

I would like to inquire about adding support for gradients for the wide case of QR factorization to JAX. To understand this better consider the following code snippet:

```python
>>> rows,cols = 2,2 # works fine for square matrices
>>> key = jax.random.key(1337)
>>> x = jax.random.normal(key, shape=(rows, cols))
>>> 
>>> def loss(x):
...     q, r = jnp.linalg.qr(x)
...     rows, cols=r.shape
...     y1 = jnp.ones(rows)
...     y2 = jnp.ones(cols)
...     xQ = y1@q
...     Ry = r@y2
...     z = xQ + Ry
...     return jnp.mean(z ** 2)
... 
>>> 
>>> grad_loss = jax.grad(loss)
>>> 
>>> print('loss value', loss(x=x))
loss value 4.989746
>>> print('gradient of loss value', grad_loss(x))
gradient of loss value [[0.42152637 0.4215265 ]
 [3.1307836  3.1307838 ]]

### Note here we make a wide matrix (columns > rows)
>>> rows,cols = 2,4
>>> x = jax.random.normal(key, shape=(rows, cols))
>>> print('loss value', loss(x=x))
loss value 7.9449735
>>> # this next line raises an exception
>>> print('gradient of loss value', grad_loss(x))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in loss
  File "/usr/local/lib/python3.11/site-packages/jax/_src/numpy/linalg.py", line 1291, in qr
    q, r = lax_linalg.qr(a, full_matrices=full_matrices)
jax._src.source_info_util.JaxStackTraceBeforeTransformation: NotImplementedError: Unimplemented case of QR decomposition derivative

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in loss
NotImplementedError: Unimplemented case of QR decomposition derivative
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
>>> 
```

however you can take a gradient for a wide matrix through a QR decomposition provided the input matrix has full (column) rank. E.g. for matrix A, `rank(A) = min(rows, columns)`. 

For this scenario we've written the derivations for the gradient as well as implemented in pytorch and tensorflow. Here is the [arxiv draft of our paper](https://arxiv.org/pdf/2009.10071) and the corresponding PRs for [pytorch](https://github.com/pytorch/pytorch/pull/42216) and [tensorflow](https://github.com/tensorflow/tensorflow/pull/45475), the latter for the complex matrix case. Here is the [tensorflow  pr](https://github.com/tensorflow/tensorflow/pull/39321) for the wide matrix real entry case. 

**Paper clarifying notes:**

1.  for the wide case the gradient using equation 3.8 replaces the gradient of Q with the `Q_prime` gradient everywhere it occurs for the square matrix `X`. 
2. The matrix `Y` for the wide case has a gradient that uses the same formulae regardless of whether equation 3.3 or equation 3.8 are used. 

Here equations have the first number indicating the section of the paper, so equation 3.8 for example, is section 3 of arxiv draft of paper and equation 8 of that section.  

Empirically, From the pytorch implementation I've found that as matrices increase in size then equation 3.3 is a somewhat faster runtime so that's another reason to prefer equation 3.3 for the calculations. It is also a simpler mathematical expression etc. 

**Questions:** 

1. Would jax maintainers accept a pr implementing the support for the wide matrix case? 
2. If the answer to (1) is yes, is there-preferably merged-pr on the jax repo which implements a gradient in a matrix factorization that I could crib from? In lieue of this, any guidance on where to look and study in the repo would be appreciated.

**Some notes on the idea of the proofs for the wide case:**

1. call the input matrix `A`, note that `A` has `rows > columns` and `rank(A) = min(rows, columns)`. 

2. rank condition implies that we can partition `A = [X | Y]` where `X` is square and the `Y` matrix is a formed via a linear  combination of the basis for `X` columns. 

3. `(Q, R) = qr(A)` and `Q` is square, partition `R` analogously to `A`, `R=[U | V]`. 

4. gradients for `Q` and `U`, `V` are formed from the backward pass and then used to construct the gradients of Q and R,  with the latter gradient formed by concatenating-the inverse of matrix column partitioning is some sense-the U,V gradients to get R gradient. 

5. These are further concatenated etc. to form the gradient of the `A` matrix, 2 equivalent formulae are given in the paper (equation 3.3 and 3.8) these are proven equivalent in the paper as well.

**Comment by EmilianoG-byte** [comment]
Hi! Are there plans to implement this? Thank you for your time : )
