### ISSUE TITLE
Orthogonal Initializer raises gpusolverDnCreate(&handle) failed: cuSolver internal error

### ISSUE THREAD

**Issue by brianorbrain** [google/jax#23616]
### Description

I am having issues initializing a Flax.linen neural network when running with GPU support.  I have narrowed it down to the flax.linen.initializers.orthogonal.  Running the below code will result in a:
 `RuntimeError: jaxlib/gpu/solver_handle_pool.cc:37: operation gpusolverDnCreate(&handle) failed: cuSolver internal error`

However running the code in another venv with only CPU support it runs just fine.  And secondly running it without the orthogonal kernel initializer it runs just fine.
The jax is installed using `pip install -U "jax[cuda12]"
`

I have attached a minimal example that will raise the issue.
```

import os

os.environ['JAX_TRACEBACK_FILTERING'] = 'off'

import jax
import jax.numpy as jnp
import flax.linen as nn
from flax.linen.initializers import constant, orthogonal




class SingleLayer(nn.Module):
    @nn.compact
    def __call__(self, x):
        layer = nn.Dense(64, kernel_init=orthogonal())(x)
        return layer


network = SingleLayer()
init_x = jnp.zeros(128)
network_params = network.init(rngs=jax.random.PRNGKey(0), x=init_x)
print(network_params)
```

Thanks,
Brian

### System info (python version, jaxlib version, accelerator, etc.)

```
jax.print_environment_info()
jax:    0.4.32
jaxlib: 0.4.32
numpy:  2.1.1
python: 3.12.5 (main, Aug 23 2024, 00:00:00) [GCC 14.2.1 20240801 (Red Hat 14.2.1-1)]
jax.devices (1 total, 1 local): [CudaDevice(id=0)]
process_count: 1
platform: uname_result(system='Linux', node='programming-desktop', release='6.10.8-200.fc40.x86_64', version='#1 SMP PREEMPT_DYNAMIC Wed Sep  4 21:41:11 UTC 2024', machine='x86_64')
$ nvidia-smi
Thu Sep 12 22:41:39 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3090        Off |   00000000:01:00.0  On |                  N/A |
| 59%   57C    P0            180W /  390W |    1759MiB /  24576MiB |     34%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      2921      G   /usr/libexec/Xorg                             456MiB |
|    0   N/A  N/A      3172    C+G   ...libexec/gnome-remote-desktop-daemon        258MiB |
|    0   N/A  N/A      3255      G   /usr/bin/gnome-shell                           76MiB |
|    0   N/A  N/A      4696      G   /usr/bin/nautilus                              24MiB |
|    0   N/A  N/A      4978      G   /usr/lib64/firefox/firefox                    190MiB |
|    0   N/A  N/A     64410      C   ...ensor/Sin_PPO_test/.venv/bin/python        366MiB |
|    0   N/A  N/A     98376      G   ...erProcess --variations-seed-version         16MiB |
|    0   N/A  N/A    111528      C   ...brain/Tensor/JaxRL/.venv/bin/python        256MiB |
+-----------------------------------------------------------------------------------------+
```

```(.venv) brain@programming-desktop:~/Tensor/JaxRL$ pip freeze | grep nvidia
nvidia-cublas-cu12==12.6.1.4
nvidia-cuda-cupti-cu12==12.6.68
nvidia-cuda-nvcc-cu12==12.6.68
nvidia-cuda-runtime-cu12==12.6.68
nvidia-cudnn-cu12==9.4.0.58
nvidia-cufft-cu12==11.2.6.59
nvidia-cusolver-cu12==11.6.4.69
nvidia-cusparse-cu12==12.5.3.3
nvidia-nccl-cu12==2.23.4
nvidia-nvjitlink-cu12==12.6.68
```

**Comment by dfm** [comment]
Thanks for the report. I'm not too sure what the issue is here, but I'm happy to help dig into it. 2 requests:

1. Would you be able to try to put together an (even!) smaller example that doesn't depend on flax? I.e. just calling QR on an array you construct yourself to make it easier to reproduce.
2. Can you try downgrading to jax/jaxlib 0.4.31? v0.4.32 got yanked because of TPU issues (unrelated to this conversation!), but it'll be easier for me to try with v0.4.31 if you still see the issue there.

**Comment by hawkinsp** [comment]
If I had to guess, you're probably running out of GPU memory. Try lowering the preallocation fraction here: https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html ?

**Comment by brianorbrain** [comment]
I have an even smaller example.  Pulled it right from the documentation. https://jax.readthedocs.io/en/latest/_autosummary/jax.nn.initializers.orthogonal.html#jax.nn.initializers.orthogonal

I am running this on jax 0.4.31 and still have the exact same issue.  I am even setting the environment variable to restrict the preallocation to 0.25 and am still having the same issue.

```import os
os.environ['XLA_PYTHON_CLIENT_MEM_FRACTION'] = '.25'
import jax, jax.numpy as jnp


initializer = jax.nn.initializers.orthogonal()

initializer(jax.random.key(42), (2, 3), jnp.float32)
```

```Traceback (most recent call last):
  File "/home/brain/Tensor/jax/jax_orthogonal.py", line 8, in <module>
    initializer(jax.random.key(42), (2, 3), jnp.float32)
  File "/home/brain/Tensor/jax/.venv/lib/python3.11/site-packages/jax/_src/nn/initializers.py", line 611, in init
    Q, R = jnp.linalg.qr(A)
  File "/home/brain/Tensor/jax/.venv/lib/python3.11/site-packages/jax/_src/numpy/linalg.py", line 1291, in qr
    q, r = lax_linalg.qr(a, full_matrices=full_matrices)
jax._src.source_info_util.JaxStackTraceBeforeTransformation: RuntimeError: jaxlib/gpu/solver_kernels.cc:45: operation gpusolverDnCreate(&handle) failed: cuSolver internal error

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/brain/Tensor/jax/jax_orthogonal.py", line 8, in <module>
    initializer(jax.random.key(42), (2, 3), jnp.float32)
  File "/home/brain/Tensor/jax/.venv/lib/python3.11/site-packages/jax/_src/nn/initializers.py", line 611, in init
    Q, R = jnp.linalg.qr(A)
           ^^^^^^^^^^^^^^^^
  File "/home/brain/Tensor/jax/.venv/lib64/python3.11/site-packages/jaxlib/gpu_solver.py", line 156, in _geqrf_hlo
    lwork, opaque = gpu_solver.build_geqrf_descriptor(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: jaxlib/gpu/solver_kernels.cc:45: operation gpusolverDnCreate(&handle) failed: cuSolver internal error
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```

```jax.print_environment_info()
jax:    0.4.31
jaxlib: 0.4.31
numpy:  2.1.1
python: 3.11.9 (main, Aug 23 2024, 00:00:00) [GCC 14.2.1 20240801 (Red Hat 14.2.1-1)]
jax.devices (1 total, 1 local): [CudaDevice(id=0)]
process_count: 1
platform: uname_result(system='Linux', node='programming-desktop', release='6.10.8-200.fc40.x86_64', version='#1 SMP PREEMPT_DYNAMIC Wed Sep  4 21:41:11 UTC 2024', machine='x86_64')
$ nvidia-smi
Sun Sep 15 14:55:58 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3090        Off |   00000000:01:00.0  On |                  N/A |
| 59%   50C    P8             58W /  390W |    2585MiB /  24576MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      2921      G   /usr/libexec/Xorg                             490MiB |
|    0   N/A  N/A      3172    C+G   ...libexec/gnome-remote-desktop-daemon        258MiB |
|    0   N/A  N/A      3255      G   /usr/bin/gnome-shell                          174MiB |
|    0   N/A  N/A      4696      G   /usr/bin/nautilus                              15MiB |
|    0   N/A  N/A     98376      G   ...erProcess --variations-seed-version         16MiB |
|    0   N/A  N/A    111528      C   ...brain/Tensor/JaxRL/.venv/bin/python        256MiB |
|    0   N/A  N/A    158963      G   ...local/share/Steam/ubuntu12_32/steam          6MiB |
|    0   N/A  N/A    159598      G   ./steamwebhelper                                5MiB |
|    0   N/A  N/A    176468      G   /usr/lib64/firefox/firefox                    176MiB |
|    0   N/A  N/A    301901      C   ...ensor/Sin_PPO_test/.venv/bin/python        810MiB |
|    0   N/A  N/A    304334      C   ...e/brain/Tensor/jax/.venv/bin/python        256MiB |
+-----------------------------------------------------------------------------------------+
```

**Comment by Leikoe** [comment]
@brianorbrain Hi! did you find a fix ?

**Comment by Leikoe** [comment]
upgrading `nvidia-cublas-cu12` fixed it ..
```
 - nvidia-cublas-cu12==12.8.4.1
 + nvidia-cublas-cu12==12.9.0.13
```

**Comment by rivershah** [comment]
Likewise. Can we please release `jax` that allows `nvidia-cublas-cu12==12.9.0.13`

**Comment by dfm** [comment]
The next version of JAX won't include the upper limit on the cuBLAS dependency (see https://github.com/jax-ml/jax/pull/28897 for more details), which I believe was only included in the most recent 0.6.0 JAX release.
