### ISSUE TITLE
Confusing error message when indexing arrays with floats

### ISSUE THREAD

**Issue by gnecula** [google/jax#2495]
Suggested by discussion in #2486 

The code `np.zeros(2)[0.]` (indexing with a float), on numpy results in the error
```
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```
 
In JAX it results in the less helpful error message
```
Traceback (most recent call last):
  File "/Users/necula/Source/jax/jax/core.py", line 758, in __len__
    return self.shape[0]
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  ...
  File "/Users/necula/Source/jax/jax/core.py", line 760, in __len__
    raise TypeError("len() of unsized object")  # same as numpy error
TypeError: len() of unsized object
```

**Comment by munozariasjm** [comment]
Hi!, it does not seems to work when one cast a tuple and not a vector, please add to docs.
