### ISSUE TITLE
working jit code, but jax.disable_jit() produces an error

### ISSUE THREAD

**Issue by samuela** [google/jax#2598]
I'm running on 824ac86620572285b86dd09529f8869ef36883ad
```python
import jax
from jax import vmap
from jax.experimental import ode

with jax.disable_jit():
  t = jax.numpy.array([0.0, 1.0])
  x0_eval = jax.numpy.zeros((5, 2))
  vmap(lambda x0: ode.odeint(lambda x, _t: x, x0, t))(x0_eval)
```
without the `with jax.disable_jit():` works just fine but with it we get an error:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/skainswo/dev/research/research/odecontrol/jaxbug_disable_jit.py", line 9, in <module>
    vmap(lambda x0: ode.odeint(lambda x, _t: x, x0, t))(x0_eval)
  File "/Users/skainswo/dev/jax/jax/api.py", line 724, in batched_fun
    lambda: _flatten_axes(out_tree(), out_axes))
  File "/Users/skainswo/dev/jax/jax/interpreters/batching.py", line 34, in batch
    return batched_fun.call_wrapped(*in_vals)
  File "/Users/skainswo/dev/jax/jax/linear_util.py", line 150, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/skainswo/dev/research/research/odecontrol/jaxbug_disable_jit.py", line 9, in <lambda>
    vmap(lambda x0: ode.odeint(lambda x, _t: x, x0, t))(x0_eval)
  File "/Users/skainswo/dev/jax/jax/experimental/ode.py", line 158, in odeint
    return _odeint_wrapper(func, rtol, atol, mxstep, y0, t, *args)
  File "/Users/skainswo/dev/jax/jax/api.py", line 135, in f_jitted
    return fun(*args, **kwargs)
  File "/Users/skainswo/dev/jax/jax/experimental/ode.py", line 164, in _odeint_wrapper
    out = _odeint(func, rtol, atol, mxstep, y0, ts, *args)
  File "/Users/skainswo/dev/jax/jax/custom_derivatives.py", line 456, in __call__
    *args_flat, out_trees=out_trees)
  File "/Users/skainswo/dev/jax/jax/custom_derivatives.py", line 504, in _custom_vjp_call_bind
    out_trees=out_trees)
  File "/Users/skainswo/dev/jax/jax/interpreters/batching.py", line 189, in process_custom_vjp_call
    out_vals = prim.bind(fun, fwd, bwd, *in_vals, out_trees=out_trees)
  File "/Users/skainswo/dev/jax/jax/custom_derivatives.py", line 500, in _custom_vjp_call_bind
    outs = prim.impl(fun, fwd, bwd, *args, out_trees=out_trees)
  File "/Users/skainswo/dev/jax/jax/custom_derivatives.py", line 510, in _custom_vjp_call_impl
    return fun.call_wrapped(*args)
  File "/Users/skainswo/dev/jax/jax/linear_util.py", line 150, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/skainswo/dev/jax/jax/experimental/ode.py", line 199, in _odeint
    _, ys = lax.scan(scan_fun, init_carry, ts[1:])
  File "/Users/skainswo/dev/jax/jax/lax/lax_control_flow.py", line 838, in scan
    carry, y = f(carry, tree_unflatten(xs_tree, xs_slice))
  File "/Users/skainswo/dev/jax/jax/experimental/ode.py", line 189, in scan_fun
    _, *carry = lax.while_loop(cond_fun, body_fun, [0] + carry)
  File "/Users/skainswo/dev/jax/jax/lax/lax_control_flow.py", line 221, in while_loop
    while cond_fun(val):
  File "/Users/skainswo/dev/jax/jax/core.py", line 421, in __bool__
    def __bool__(self): return self.aval._bool(self)
  File "/Users/skainswo/dev/jax/jax/core.py", line 709, in error
    raise TypeError(concretization_err_msg(fun, context))
TypeError: Abstract value passed to `bool`, which requires a concrete value. The function to be transformed can't be traced at the required level of abstraction. If using `jit`, try using `static_argnums` or applying `jit` to smaller subfunctions instead.
```

**Comment by mattjj** [comment]
Tricky... this is happening because when using `disable_jit` we [use Python-based implementations of the control flow primitives](https://github.com/google/jax/blob/2c4ced2143375ed8a4f8e467c501d9c794d385cb/jax/lax/lax_control_flow.py#L219-L223) (for better debuggability, since otherwise they effectively act like `jit` themselves), but we can't `vmap` a Python while loop like we can a `lax.while_loop` (as it leads to this abstraction error).

I think we should
1. raise a custom exception class due to these tracing errors rather than a TypeError,
2. catch that exception when we execute the Python version of control flow primitives, and in that case fall back to doing the non-Python vmap-transformable version.

Another option would be to stop making jit_is_disabled affect the control flow primitives this way, but it seems like a nice option to have for debugging... @jekbradbury let me know if you have thoughts.

In the meantime, a workaround would be to disable the logic in lax_control_flow.py that depends on `jax.api._jit_is_disabled()`, e.g. by just commenting out those lines. I verified that by commenting out [these lines](https://github.com/google/jax/blob/2c4ced2143375ed8a4f8e467c501d9c794d385cb/jax/lax/lax_control_flow.py#L219-L223) your test code runs.

**Comment by samuela** [comment]
I would be ok with `vmap` not actually doing a fully vectorized map in `disable_jit` contexts. Just doing `map` and then sewing together the results would be fine for debugging purposes.

**Comment by ysulsky** [comment]
The same issue comes up in the context of jax.eval_shape as well. For instance, this test fails with a type error:

  def testCondEvalShapeNoJit(self):
    def f(x):
      return lax.cond(x < 2, x, lambda x: 3. * x, x, lambda x: np.sin(x))
    with api.disable_jit():
      self.assertEqual(api.eval_shape(f, 0.).shape, ())
