### ISSUE TITLE
jax_debug_nans doesn't work with pmap

### ISSUE THREAD

**Issue by ibab** [google/jax#2611]
If I ran the following script:
```
from functools import partial
import jax
import jax.numpy as jnp


@partial(jax.pmap, axis_name='i')
def nan_with_pmap(x):
  return jnp.log(-x)


print(nan_with_pmap(jnp.array([42.])))
```
using
```
JAX_DEBUG_NANS=true python script.py
```
I expected it to crash at the point where the nan was produced, but instead the script prints:
```
[nan]
```

Would it be possible to add nan detection to `pmap` as well?

**Comment by ibab** [comment]
I think jax should at least check the output of pmap and crash, saying something like "the cause of the NaN can't be narrowed down further". Right now the debug_nans flag gets silently ignored.

**Comment by mattjj** [comment]
FWIW we have made progress on this! The test code now crashes when the pmapped function application returns, with this error:

```
Traceback (most recent call last):
  File "/usr/local/google/home/mattjj/packages/jax/2611.py", line 12, in <module>
    print(nan_with_pmap(jnp.array([42.])))
  File "/usr/local/google/home/mattjj/packages/jax/jax/interpreters/xla.py", line 418, in _check_special
    raise FloatingPointError(f"invalid value (nan) encountered in {name}")
FloatingPointError: invalid value (nan) encountered in parallel computation
```

**Comment by sracaniere** [comment]
Nice. That's much better!

**Comment by mattjj** [comment]
What's missing is we can't "drill down" into the pmap, like we do with jit.

**Comment by qlan3** [comment]
Any update about how to "drill down" into the pmap?

**Comment by SimiPixel** [comment]
> What's missing is we can't "drill down" into the pmap, like we do with jit.

Any update on how to do this? Currently i have a run that throws exactly this error message if i enable NaN-debugging.

**Comment by hawkinsp** [comment]
Fixed, because `pmap` now lowers to `jit` and `shard_map`.
