### ISSUE TITLE
Simple Classification with MSE Loss

### ISSUE THREAD

**Issue by g-benton** [google/jax#2697]
I'm getting hangups in the loss when doing classification using MSE loss. I'm attempting to follow the standard setup provided in the guides but the loss continues to get stuck at 0.25 regardless of the architecture of the network, which is making me suspicious that there is an error somewhere. The same setup works fine for a single dimensional regression task, so I believe the code is working.  

I've attached a simple example trying to classify two dimensional data using MSE Loss

```python
## IMPORTS ##
import math
import jax.numpy as np
from jax.experimental import stax
import jax
from jax import random
from jax import grad, jit, vmap
from jax.experimental import optimizers

## LOSS FUNCTION ##

def loss(params, apply_fn, inputs, targets):
    preds = apply_fn(params, inputs)
    out = np.mean((preds - targets)**2)
    print(out)
    return out

## INIT NETWORK ##
width = 100
init, apply = stax.serial(stax.Dense(width), stax.Relu,
                          stax.Dense(width), stax.Relu,
                          stax.Dense(width), stax.Relu,
                          stax.Dense(width), stax.Relu,
                          stax.Dense(1))

## GENERATE KEYS AND DATA ##
key = random.PRNGKey(10)
gen_key1, gen_key2, key = random.split(key, 3)

def twospirals(n_points, noise=.5, random_state=920):
    """
     Returns the two spirals dataset.
    """
    n = np.sqrt(random.uniform(key,(n_points,1))) * 600 * (2*np.pi)/360
    d1x = -1.5*np.cos(n)*n + random.normal(gen_key1,(n_points,1)) * noise
    d1y =  1.5*np.sin(n)*n + random.normal(gen_key2,(n_points,1)) * noise
    
    return (np.vstack((np.hstack((d1x,d1y)),np.hstack((-d1x,-d1y)))),
            np.hstack((np.zeros(n_points),np.ones(n_points))))


n_train = 500
train_x, train_y = twospirals(n_train, noise=0.5)

## DRAWING PARAMETERS ##
init_key = random.PRNGKey(42)
_, params = init(init_key, (-1, 2))

## RUNNING OPTIMIZATION ##
opt_init, opt_update, get_params = optimizers.adam(step_size=0.01)

def step(i, opt_state):
    params = get_params(opt_state)
    g = grad(loss)(params, apply, train_x, train_y)
    return opt_update(i, g, opt_state)

# Optimize parameters in a loop
opt_state = opt_init(params)
for i in range(1000):
    opt_state = step(i, opt_state)
```
And the classifier looks like:
![image (3)](https://user-images.githubusercontent.com/29232979/79144361-d6271380-7d8c-11ea-92d9-c2cdb04031d4.png)

As mentioned above the fact that independent of model width/depth the loss does not go below 0.25 gives the sense that something is amiss. Any help would be appreciated - thanks!

**Comment by hawkinsp** [comment]
Are you sure this isn't just an artifact of your NN's loss function: e.g.,

```
def loss(params, apply_fn, inputs, targets):
    preds = apply_fn(params, inputs)
    out = np.mean((preds - jax.nn.one_hot(targets, 2))**2)
    return out

## INIT NETWORK ##
width = 100
init, apply = stax.serial(stax.Dense(width), stax.Relu,
                          stax.Dense(width), stax.Relu,
                          stax.Dense(width), stax.Relu,
                          stax.Dense(width), stax.Relu,
                          stax.Dense(2))
```
seems to train fine, as does:

```

def loss(params, apply_fn, inputs, targets):
    preds = apply_fn(params, inputs)
    logits = jax.nn.log_softmax(preds)
    return -np.sum(logits * jax.nn.one_hot(targets, 2))

## INIT NETWORK ##
width = 100
init, apply = stax.serial(stax.Dense(width), stax.Relu,
                          stax.Dense(width), stax.Relu,
                          stax.Dense(width), stax.Relu,
                          stax.Dense(width), stax.Relu,
                          stax.Dense(2))
```

What do you think?

**Comment by g-benton** [comment]
That was my thought at first, however there's some indicators that it's not just the loss function. Changing to a one-hot encoded response like in the first suggestion is still giving me that the loss will still not decrease below 0.25. It's converging to exactly 0.25 for all architectures as well, out to 5 decimals.

Changing to an entropy-based loss like in the second snippet does work, but I'm limited to viewing the problem as regression just due to the use case.

For reference using MSE Loss with the same architecture/optimizer/learning rate in pytorch gives the following:

![image (4)](https://user-images.githubusercontent.com/29232979/79157157-147afd80-7da2-11ea-9a83-969d44d48f14.png)

**Comment by froystig** [comment]
For reference, is the linear regression baseline, or the pytorch-based version, publicly available?

**Comment by g-benton** [comment]
Thank you all for the rapid replies! 

The 1D case was just trying to model the data:
```python
def sine_func(x, noise=0.1):
    return np.sin(x) + 0.2 * np.sin(2 * x) + random.normal(key,(x.shape[0],1))  * noise

train_x = np.linspace(-math.pi, math.pi)
train_x = np.expand_dims(train_x, -1)
train_y = sine_func(train_x, noise=0.1)

_, params = init(key, (-1, 1))
```

and the full pytorch-based version is here:
```python
import math
import torch
from torch import nn
import numpy as np
from determination.nets import SimpleNet
import matplotlib.pyplot as plt

## SETUP DATA ##
def twospirals(n_points, noise=.5, random_state=920):
    """
     Returns the two spirals dataset.
    """
    n = np.sqrt(np.random.rand(n_points,1)) * 600 * (2*np.pi)/360
    d1x = -1.5*np.cos(n)*n + np.random.randn(n_points,1) * noise
    d1y =  1.5*np.sin(n)*n + np.random.randn(n_points,1) * noise
    return (np.vstack((np.hstack((d1x,d1y)),np.hstack((-d1x,-d1y)))),
            np.hstack((np.zeros(n_points),np.ones(n_points))))

n_train = 250
n_test = 250
X, Y = twospirals(n_train, noise=1.25)

train_x = torch.FloatTensor(X)
train_y = torch.FloatTensor(Y).unsqueeze(-1)

## DEFINE MODEL ##
width = 25
mod_def = nn.ModuleList()

mod_list = [nn.Linear(2, width), nn.ReLU(),
            nn.Linear(width, width), nn.ReLU(),
            nn.Linear(width, width), nn.ReLU(),
            nn.Linear(width, width), nn.ReLU(),
            nn.Linear(width, 1)]
model = nn.Sequential(*mod_list)

## OPTIMIZATION ##
n_iters=1000
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
loss_func = torch.nn.MSELoss()

for step in range(n_iters):
    optimizer.zero_grad()
    outputs = model(train_x)

    loss=loss_func(outputs, train_y)
    loss.backward()
    print(loss.item())
    
    optimizer.step()
    

## THIS IS JUST PLOTTING ##
buffer = 1.
h = 0.1
x_min, x_max = train_x[:, 0].min() - buffer, train_x[:, 0].max() + buffer
y_min, y_max = train_x[:, 1].min() - buffer, train_x[:, 1].max() + buffer

xx,yy=np.meshgrid(np.arange(x_min.cpu(), x_max.cpu(), h), 
                  np.arange(y_min.cpu(), y_max.cpu(), h))
in_grid = torch.FloatTensor([xx.ravel(), yy.ravel()]).t()

pred = model(in_grid).detach().reshape(xx.shape)
plt.figure(figsize=(15, 10))
plt.contourf(xx, yy, pred, alpha=0.5)
plt.title("Classifier", fontsize=24)
plt.colorbar()
plt.scatter(train_x[:, 0].cpu(), train_x[:, 1].cpu(), c=train_y[:, 0].cpu(), cmap=plt.cm.binary)


```

**Comment by froystig** [comment]
I suspect that the predictions and the targets have different dimensions in the loss function. Let's say N is `width`. The output of the `Dense(1)` layer is 2-dimensional, N x 1. Meanwhile, the targets that you supply are 1-dimensional, of length N. This causes `targets` to be broadcast within `loss`, but likely not in the way that you intend: `preds - targets` is (N, N)-shaped.

This behavior is dictated by NumPy, so the same issue would have come up in a pure NumPy implementation, without having JAX involved.

You could change the training set to produce (N, 1)-shaped targets. Alternatively, in `loss`, changing the line

    out = np.mean((preds - targets)**2)

to

    out = np.mean((preds.squeeze() - targets)**2)

should work as well.

@hawkinsp's suggestion above likely improved matters simply because it led to shapes.

**Comment by mattjj** [comment]
Turning on [this rank-promotion warning/error](https://jax.readthedocs.io/en/latest/rank_promotion_warning.html), which disables this NumPy-like rank promotion, would've caught the error earlier.

Except... I just noticed that stax doesn't play nicely with this disabled, since it relies on rank promotion semantics when it adds bias vectors:

```bash
$ env JAX_NUMPY_RANK_PROMOTION=raise python issue2697.py
Traceback (most recent call last):
  File "issue2697.py", line 60, in <module>
    opt_state = step(i, opt_state)
  File "issue2697.py", line 54, in step
    g = grad(loss)(params, apply, train_x, train_y)
  File "/usr/local/google/home/mattjj/packages/jax/jax/api.py", line 372, in grad_f
    _, g = value_and_grad_f(*args, **kwargs)
  File "/usr/local/google/home/mattjj/packages/jax/jax/api.py", line 428, in value_and_grad_f
    ans, vjp_py = _vjp(f_partial, *dyn_args)
  File "/usr/local/google/home/mattjj/packages/jax/jax/api.py", line 1389, in _vjp
    out_primal, out_vjp = ad.vjp(flat_fun, primals_flat)
  File "/usr/local/google/home/mattjj/packages/jax/jax/interpreters/ad.py", line 106, in vjp
    out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
  File "/usr/local/google/home/mattjj/packages/jax/jax/interpreters/ad.py", line 95, in linearize
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr(jvpfun_flat, in_pvals)
  File "/usr/local/google/home/mattjj/packages/jax/jax/interpreters/partial_eval.py", line 421, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/usr/local/google/home/mattjj/packages/jax/jax/linear_util.py", line 150, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "issue2697.py", line 13, in loss
    preds = apply_fn(params, inputs)
  File "/usr/local/google/home/mattjj/packages/jax/jax/experimental/stax.py", line 304, in apply_fun
    inputs = fun(param, inputs, rng=rng, **kwargs)
  File "/usr/local/google/home/mattjj/packages/jax/jax/experimental/stax.py", line 59, in apply_fun
    return np.dot(inputs, W) + b
  File "/usr/local/google/home/mattjj/packages/jax/jax/core.py", line 390, in __add__
    def __add__(self, other): return self.aval._add(self, other)
  File "/usr/local/google/home/mattjj/packages/jax/jax/numpy/lax_numpy.py", line 3660, in deferring_binary_op
    return binary_op(self, other)
  File "/usr/local/google/home/mattjj/packages/jax/jax/numpy/lax_numpy.py", line 403, in fn
    x1, x2 = _promote_args(numpy_fn.__name__, x1, x2)
  File "/usr/local/google/home/mattjj/packages/jax/jax/numpy/lax_numpy.py", line 265, in _promote_args
    return _promote_shapes(fun_name, *_promote_dtypes(*args))
  File "/usr/local/google/home/mattjj/packages/jax/jax/numpy/lax_numpy.py", line 201, in _promote_shapes
    _rank_promotion_warning_or_error(fun_name, shapes)
  File "/usr/local/google/home/mattjj/packages/jax/jax/numpy/lax_numpy.py", line 219, in _rank_promotion_warning_or_error
    raise ValueError(msg.format(fun_name, ' '.join(map(str, shapes))))
ValueError: Operands could not be broadcast together for add on shapes (1000, 100) (100,) and with the config option jax_numpy_rank_promotion='raise'. For more information, see https://jax.readthedocs.io/en/latest/rank_promotion_warning.html.
```

So perhaps that's not so useful in this case :)

**Comment by sunny2309** [comment]
Hello @froystig ,

Your comment above about preds dimension being (N,1) in loss function helped me a lot. I was stuck on it for long as my MSE for simple regression task was not reducing beyond particular value. With just addition of squeeze() solved problem immediately. I had no idea that broadcasting can create such problem. I was just doing .mean() on last value without checking dimensions. 

Your one comment helped me solve my problem.

Really Appreciate it.

Regards,
Sunny
