### ISSUE TITLE
Add support for different models of GPU in the same process

### ISSUE THREAD

**Issue by caihao** [google/jax#2721]
```python
from jax import device_put, devices, jit
import jax.numpy as np
import numpy as onp


def f(x):
    return np.sum(x)


data = onp.random.rand(10000)

x0 = device_put(data, device=devices()[0])
x1 = device_put(data, device=devices()[1])

f0 = jit(f, device=devices()[0])
print("f on gpu 0:", f0(x0))

f1 = jit(f, device=devices()[1])
print("f on gpu 1:", f1(x1))
````

On my machine, there are errors like these
```
f on gpu 0: 4993.7783
2020-04-15 13:59:45.496271: E external/org_tensorflow/tensorflow/compiler/xla/python/local_client.cc:758] Execution of replica 0 failed: Invalid argument: executable is built for device CUDA:0 of type "GeForce RTX 2080 Ti"; cannot run it on device CUDA:1 of type "Tesla P100-PCIE-16GB"
Traceback (most recent call last):
  File "test3.py", line 22, in <module>
    print("f on gpu 1:", f1(x1))
  File "/usr/local/lib/python3.6/dist-packages/jax/api.py", line 150, in f_jitted
    out = xla.xla_call(flat_fun, *args_flat, device=device, backend=backend)
  File "/usr/local/lib/python3.6/dist-packages/jax/core.py", line 592, in call_bind
    outs = primitive.impl(f, *args, **params)
  File "/usr/local/lib/python3.6/dist-packages/jax/interpreters/xla.py", line 402, in _xla_call_impl
    return compiled_fun(*args)
  File "/usr/local/lib/python3.6/dist-packages/jax/interpreters/xla.py", line 486, in _execute_compiled
    out_bufs = compiled.Execute(input_bufs).destructure()
RuntimeError: Invalid argument: executable is built for device CUDA:0 of type "GeForce RTX 2080 Ti"; cannot run it on device CUDA:1 of type "Tesla P100-PCIE-16GB"
```
There two gpu cards in my machine.
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.26       Driver Version: 430.26       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  On   | 00000000:3B:00.0 Off |                  N/A |
|  0%   38C    P8    15W / 280W |      0MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-PCIE...  On   | 00000000:AF:00.0 Off |                    0 |
| N/A   37C    P0    27W / 250W |      0MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

Could you give me some advice?

**Comment by hawkinsp** [comment]
JAX doesn't support two different models of GPUs in the same machine at the moment. But we should! It isn't hard to fix, just something we haven't fixed yet.

I'll see what we can do!

**Comment by caihao** [comment]
Thanks! Looking forward to the next wonderful version!

Peter Hawkins <notifications@github.com> 于2020年4月15日周三 下午10:04写道：

**Comment by hawkinsp** [comment]
This turned out to be not that hard to fix. Updating to `jaxlib` 0.1.44 should fix it. Let us know how it goes!
