### ISSUE TITLE
MaxPool does not yet support jvp

### ISSUE THREAD

**Issue by jonasrauber** [google/jax#274]
This issue is just to keep track of jvp supoort for MaxPool which has not yet been implemented:

```python3
from functools import partial
from jax.experimental import stax
import jax.numpy as np
import jax

x = np.zeros((100, 2, 2, 3))

init_fn, apply_fun = stax.AvgPool((2, 2))
output_shape, params = init_fn((-1, 2, 2, 3))
print(output_shape)
print(params)

f = partial(apply_fun, params)
output = f(x)
print(output.shape)

Jv = jax.jvp(f, [x], [x])
```

This fails with a `NotImplementedError`:

```
(-1, 1, 1, 3)
()
(100, 1, 1, 3)
Traceback (most recent call last):
  File "minimal_example.py", line 18, in <module>
    Jv = jax.jvp(f, [x], [x])
  File "/gpfs01/bethge/home/jrauber/PhD/063_jax/jax/jax/api.py", line 269, in jvp
    out_primal, out_tangent = ad.jvp(jaxtree_fun).call_wrapped(ps_flat, ts_flat)
  File "/gpfs01/bethge/home/jrauber/PhD/063_jax/jax/jax/linear_util.py", line 86, in call_wrapped
    ans = self.f(*args, **self.kwargs)
  File "/gpfs01/bethge/home/jrauber/PhD/063_jax/jax/jax/experimental/stax.py", line 171, in apply_fun
    out = lax.reduce_window(inputs, init_val, reducer, dims, strides, padding)
  File "/gpfs01/bethge/home/jrauber/PhD/063_jax/jax/jax/lax.py", line 345, in reduce_window
    return monoid_reducer(operand, window_dimensions, window_strides, padding)
  File "/gpfs01/bethge/home/jrauber/PhD/063_jax/jax/jax/lax.py", line 372, in _reduce_window_max
    window_strides=tuple(window_strides), padding=padding)
  File "/gpfs01/bethge/home/jrauber/PhD/063_jax/jax/jax/core.py", line 74, in bind
    out_tracer = top_trace.process_primitive(self, tracers, kwargs)
  File "/gpfs01/bethge/home/jrauber/PhD/063_jax/jax/jax/interpreters/ad.py", line 179, in process_primitive
    primal_out, tangent_out = jvp(primals_in, tangents_in, **params)
  File "/gpfs01/bethge/home/jrauber/PhD/063_jax/jax/jax/interpreters/ad.py", line 298, in standard_jvp
    return val_out, reduce(add_tangents, tangents_out, zero)
  File "/gpfs01/bethge/home/jrauber/PhD/063_jax/jax/jax/interpreters/ad.py", line 297, in <genexpr>
    if rule is not None and t is not zero)
  File "/gpfs01/bethge/home/jrauber/PhD/063_jax/jax/jax/lax.py", line 2288, in reduce_window_chooser_jvp_rule
    window_strides, padding)
  File "/gpfs01/bethge/home/jrauber/PhD/063_jax/jax/jax/lax.py", line 401, in _select_and_gather_add
    window_strides=tuple(window_strides), padding=padding)
  File "/gpfs01/bethge/home/jrauber/PhD/063_jax/jax/jax/core.py", line 71, in bind
    return self.impl(*args, **kwargs)
  File "/gpfs01/bethge/home/jrauber/PhD/063_jax/jax/jax/interpreters/xla.py", line 48, in apply_primitive
    compiled_fun = xla_primitive_callable(prim, *abstract_args, **kwargs)
  File "/gpfs01/bethge/home/jrauber/PhD/063_jax/jax/jax/util.py", line 161, in memoized_fun
    ans = cache[key] = fun(*args, **kwargs)
  File "/gpfs01/bethge/home/jrauber/PhD/063_jax/jax/jax/interpreters/xla.py", line 54, in xla_primitive_callable
    built_c = primitive_computation(prim, *shapes, **kwargs)
  File "/gpfs01/bethge/home/jrauber/PhD/063_jax/jax/jax/util.py", line 161, in memoized_fun
    ans = cache[key] = fun(*args, **kwargs)
  File "/gpfs01/bethge/home/jrauber/PhD/063_jax/jax/jax/interpreters/xla.py", line 64, in primitive_computation
    xla_result = translation_rule(prim)(c, *xla_args, **kwargs)
  File "/gpfs01/bethge/home/jrauber/PhD/063_jax/jax/jax/lax.py", line 2398, in select_and_gather_add_translation
    raise NotImplementedError("No efficient translation.")
NotImplementedError: No efficient translation.
```

P.S. there was a similar problem in TensorFlow that I reported here and has been fixed since then: https://github.com/tensorflow/tensorflow/issues/23397

**Comment by mattjj** [comment]
I'm glad you're trying out forward-mode!

When we wrote this JVP code, XLA didn't have a good way to generate the "select and gather" operation we need for this JVP. (It has a [special operation "select and scatter"](https://www.tensorflow.org/xla/operation_semantics#selectandscatter) for the VJP, i.e. the adjoint of this operation used in reverse-mode.) Last I heard, the XLA developers were unhappy with that state of things, and wanted to decompose SelectAndScatter into more basic operations (which might then be general enough for us to implement SelectAndGather efficiently), but I don't know if anyone is working on it.

@hawkinsp does the new `lax.gather` give us some hope for an efficient lowering here? Any other ideas?

**Comment by jonasrauber** [comment]
Thanks for the explanation. They have added forward-mode AD of maxpool to TensorFlow so I would guess there is some way to do it in XLA. 
https://github.com/tensorflow/tensorflow/issues/23397

**Comment by hawkinsp** [comment]
PR https://github.com/google/jax/pull/286 adds an implementation of the necessary rule, but it has two requirements:
a) we need to update the version of XLA in jaxlib for the code to work on CPU
b) the user currently needs to set --jax_enable_x64=True for this code to work.

I'm working on cleaning up/finishing both aspects.

**Comment by hawkinsp** [comment]
Ok, this issue should now be fixed, at least for 32-bit types, provided you rebuild your jaxlib from source or wait for us to make a new jaxlib release (0.1.7). 64-bit types won't work without some more substantial extensions to XLA, but you can work around that by casting to 32-bit locally.

Closing; feel free to reopen if someone needs the 64-bit support.

**Comment by jonasrauber** [comment]
Awesome! Thank you!
