### ISSUE TITLE
Nested vmap over while_loop sometimes raises errors.

### ISSUE THREAD

**Issue by SiegeLordEx** [google/jax#2960]
Consider this code:
```python
import jax.numpy as jnp
import jax
import jaxlib

print(jax.__version__)
print(jaxlib.__version__)

def repeat(step_size, num_steps):
  def cond(ix):
    return ix[0] < num_steps

  def body(ix):
    i, x = ix
    y = x + step_size
    return i + 1, y

  return jax.lax.while_loop(cond, body, (0, 0.))[1]

def grid1(step_size, num_steps):
  @jax.vmap
  def iter_num_steps(num_steps):
    @jax.vmap
    def iter_step_size(step_size):
      return repeat(step_size, num_steps)
    return iter_step_size(step_size)
  return iter_num_steps(num_steps)

def grid2(step_size, num_steps):
  @jax.vmap
  def iter_step_size(step_size):
    @jax.vmap
    def iter_num_steps(num_steps):
      return repeat(step_size, num_steps)
    return iter_num_steps(num_steps)
  return iter_step_size(step_size)

print(grid1(jnp.linspace(0.1, 1., 3), jnp.arange(5)))
print(grid2(jnp.linspace(0.1, 1., 3), jnp.arange(5)))
```

Running it yields this input. I'd have expected it to not error have `grid2` produce the transposed output of `grid1`. Errors aside, is one approach supposed to be more efficient than the other?

```
0.1.65
0.1.45
[[0.        0.        0.       ]
 [0.1       0.55      1.       ]
 [0.2       1.1       2.       ]
 [0.3       1.6500001 3.       ]
 [0.4       2.2       4.       ]]
Traceback (most recent call last):
  File "jax_bug.py", line 38, in <module>
    print(grid2(jnp.linspace(0.1, 1., 3), jnp.arange(5)))
  File "jax_bug.py", line 35, in grid2
    return iter_step_size(step_size)
  File "/home/siege/.local/lib/python3.7/site-packages/jax/api.py", line 807, in batched_fun
    lambda: _flatten_axes(out_tree(), out_axes))
  File "/home/siege/.local/lib/python3.7/site-packages/jax/interpreters/batching.py", line 34, in batch
    return batched_fun.call_wrapped(*in_vals)
  File "/home/siege/.local/lib/python3.7/site-packages/jax/linear_util.py", line 150, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "jax_bug.py", line 34, in iter_step_size
    return iter_num_steps(num_steps)
  File "/home/siege/.local/lib/python3.7/site-packages/jax/api.py", line 807, in batched_fun
    lambda: _flatten_axes(out_tree(), out_axes))
  File "/home/siege/.local/lib/python3.7/site-packages/jax/interpreters/batching.py", line 34, in batch
    return batched_fun.call_wrapped(*in_vals)
  File "/home/siege/.local/lib/python3.7/site-packages/jax/linear_util.py", line 150, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "jax_bug.py", line 33, in iter_num_steps
    return repeat(step_size, num_steps)
  File "jax_bug.py", line 17, in repeat
    return jax.lax.while_loop(cond, body, (0, 0.))[1]
  File "/home/siege/.local/lib/python3.7/site-packages/jax/lax/lax_control_flow.py", line 246, in while_loop
    body_nconsts=len(body_consts), body_jaxpr=body_jaxpr)
  File "/home/siege/.local/lib/python3.7/site-packages/jax/core.py", line 202, in bind
    out_tracer = top_trace.process_primitive(self, tracers, kwargs)
  File "/home/siege/.local/lib/python3.7/site-packages/jax/interpreters/batching.py", line 134, in process_primitive
    val_out, dim_out = batched_primitive(vals_in, dims_in, **params)
  File "/home/siege/.local/lib/python3.7/site-packages/jax/lax/lax_control_flow.py", line 344, in _while_loop_batching_rule
    body_nconsts=body_nconsts, body_jaxpr=body_jaxpr_batched)
  File "/home/siege/.local/lib/python3.7/site-packages/jax/core.py", line 202, in bind
    out_tracer = top_trace.process_primitive(self, tracers, kwargs)
  File "/home/siege/.local/lib/python3.7/site-packages/jax/interpreters/batching.py", line 134, in process_primitive
    val_out, dim_out = batched_primitive(vals_in, dims_in, **params)
  File "/home/siege/.local/lib/python3.7/site-packages/jax/lax/lax_control_flow.py", line 344, in _while_loop_batching_rule
    body_nconsts=body_nconsts, body_jaxpr=body_jaxpr_batched)
  File "/home/siege/.local/lib/python3.7/site-packages/jax/core.py", line 199, in bind
    return self.impl(*args, **kwargs)
  File "/home/siege/.local/lib/python3.7/site-packages/jax/interpreters/xla.py", line 171, in apply_primitive
    compiled_fun = xla_primitive_callable(prim, *map(arg_spec, args), **params)
  File "/home/siege/.local/lib/python3.7/site-packages/jax/interpreters/xla.py", line 196, in xla_primitive_callable
    *avals, **params)
  File "/home/siege/.local/lib/python3.7/site-packages/jax/interpreters/xla.py", line 243, in primitive_computation
    *xla_args, **params)
  File "/home/siege/.local/lib/python3.7/site-packages/jax/lax/lax_control_flow.py", line 290, in _while_loop_translation_r
ule
    new_z = _map(partial(_pred_bcast_select, body_c, body_pred), new_z, z)
  File "/home/siege/.local/lib/python3.7/site-packages/jax/util.py", line 34, in safe_map
    return list(map(f, *args))
  File "/home/siege/.local/lib/python3.7/site-packages/jax/lax/lax_control_flow.py", line 304, in _pred_bcast_select
    assert pred_shape == x_shape[:len(pred_shape)] == y_shape[:len(pred_shape)]
AssertionError
```

**Comment by jekbradbury** [comment]
What I think is happening is:
- we implement `vmap` of `while_loop` by defining our `while_loop` primitive as "natively batched" (akin to how our convolution or elementwise function primitives have rank polymorphism/built-in support for batch dimensions)
- in particular, `while_loop` allows its `cond_fn` argument to return a non-scalar predicate; it then broadcasts that predicate against the output of the `body_fn` to decide which items in the batch should have their loop carry values updated for a given iteration (meanwhile the loop runs until the predicate is all `False`)

This broadcasting assumes that the shape of the predicate is a prefix of the shape of the body outputs; this is violated here because the predicate was batched by one vmap (size 3, I think) while the outputs were batched by a different vmap (size 5). It would be even worse if the vmaps had been the same size: the computation would have given silently wrong results rather than throwing an error!

Going to look into this more (and hopefully come up with a fix) later this week.

**Comment by mattjj** [comment]
This doesn't reproduce on master; I think it's fixed!

**Comment by mattjj** [comment]
I think it was #3174 which fixed this.
