### ISSUE TITLE
RuntimeError: Unimplemented: complex comparison 'LT'

### ISSUE THREAD

**Issue by samuela** [google/jax#3074]
I'm getting a weird internal JAX error with this script:
```python
import jax.numpy as jp

def lqr_continuous_time_infinite_horizon(A, B, Q, R, N):
  # Take the last dimension, in case we try to do some kind of broadcasting
  # thing in the future.
  x_dim = A.shape[-1]

  # See https://en.wikipedia.org/wiki/Linear%E2%80%93quadratic_regulator#Infinite-horizon,_continuous-time_LQR.
  A1 = A - B @ jp.linalg.solve(R, N.T)
  Q1 = Q - N @ jp.linalg.solve(R, N.T)

  # See https://en.wikipedia.org/wiki/Algebraic_Riccati_equation#Solution.
  H = jp.block([[A1, -B @ jp.linalg.solve(R, B.T)], [-Q1, -A1]])
  eigvals, eigvectors = jp.linalg.eig(H)
  argsort = jp.argsort(eigvals)
  ix = argsort[:x_dim]
  U = eigvectors[:, ix]
  P = U[x_dim:, :] @ jp.linalg.inv(U[:x_dim, :])

  K = jp.linalg.solve(R, (B.T @ P + N.T))
  return K, P, eigvals[ix]

def _test_lqr(n):
  import control
  from jax.tree_util import tree_multimap

  A = jp.eye(n)
  B = jp.eye(n)
  Q = jp.eye(n)
  R = jp.eye(n)
  N = jp.zeros((n, n))

  actual = lqr_continuous_time_infinite_horizon(A, B, Q, R, N)
  expected = control.lqr(A, B, Q, R, N)
  assert tree_multimap(jp.allclose, actual, expected)

if __name__ == "__main__":
  _test_lqr(2)
```
I'm getting:
```
❯ pipenv run python -m research.lqr
/Users/skainswo/dev/jax/jax/lib/xla_bridge.py:116: UserWarning: No GPU/TPU found, falling back to CPU.
  warnings.warn('No GPU/TPU found, falling back to CPU.')
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/skainswo/dev/research/research/lqr.py", line 50, in <module>
    _test_lqr1(2)
  File "/Users/skainswo/dev/research/research/lqr.py", line 45, in _test_lqr1
    actual = lqr_continuous_time_infinite_horizon(A, B, Q, R, N)
  File "/Users/skainswo/dev/research/research/lqr.py", line 26, in lqr_continuous_time_infinite_horizon
    argsort = jp.argsort(eigvals)
  File "/Users/skainswo/dev/jax/jax/numpy/lax_numpy.py", line 2886, in argsort
    _, perm = lax.sort_key_val(a, iota, dimension=axis)
  File "/Users/skainswo/dev/jax/jax/lax/lax.py", line 1190, in sort_key_val
    result = sort_key_val_p.bind(keys, values, dimension=dimension)
  File "/Users/skainswo/dev/jax/jax/core.py", line 211, in bind
    return self.impl(*args, **kwargs)
  File "/Users/skainswo/dev/jax/jax/interpreters/xla.py", line 217, in apply_primitive
    compiled_fun = xla_primitive_callable(prim, *map(arg_spec, args), **params)
  File "/Users/skainswo/dev/jax/jax/interpreters/xla.py", line 254, in xla_primitive_callable
    compiled = backend.compile(built_c, compile_options=options)
RuntimeError: Unimplemented: complex comparison 'LT'
```
I'm guessing that this has something to do with the fact that I'm getting complex eigenvalues out, but the error message is pretty confusing...

**Comment by hawkinsp** [comment]
Yes, this is certainly a bad error.

I'm curious if you actually want the `np.argsort` behavior on complex numbers (lexicographic order) or just a better error... either way, I guess we'll implement the `np.argsort` behavior.

**Comment by samuela** [comment]
@hawkinsp Yeah, that's a great question. I think I'd personally prefer a better error, but only because it's not immediately clear what the right ordering should be.

**Comment by hawkinsp** [comment]
#3096 implements complex-valued sorts, although it will need another jaxlib release before it works on CPU. It works right now on GPU.
