### ISSUE TITLE
sparse solvers

### ISSUE THREAD

**Issue by mganahl** [google/jax#3112]
Hi!

Our team is currently developing sparse symmetric and non-symmetric solvers in JAX (implicitly restarted arnoldi and lanzcos). I have it from hearsay that there are efforts to support this natively in JAX. I wanted to ask what the status there is. It would be actually great if JAX would provide those.

**Comment by shoyer** [comment]
By "solvers" are you referring specifically to eigenvalue solvers?

Yes, I think we would be interested in adding some of these to JAX, but they would need to be reasonably robust and scalable, ideally comparable to the SciPy algorithms. The "basic" Lanczos method would probably not qualify, but restarted Arnoldi (used by SciPy in ARPACK) probably would.

It would also be nice to include auto-diff rules for these operations, but that could come later.

**Comment by jakevdp** [comment]
Since scipy comes bundled with ARPACK, it may be possible to write a CPU translation rule to use the bundled ARPACK version for JAX (fun fact: my first scipy contribution involved the ARPACK wrappers :smile:). GPU & TPU would have to use another approach, though.

**Comment by shoyer** [comment]
I played around with writing a thick-restart Lanczos solver. As a point of reference, you can find it in https://github.com/google/jax/pull/3114 but I'm not sure we actually want to merge it.

**Comment by Thenerdstation** [comment]
We have an implementation at https://github.com/google/TensorNetwork/blob/d4ec0a381dbf1a7d453d97525ccc857fc416b575/tensornetwork/backends/jax/jax_backend.py#L230

Not sure if it would useful to have in JAX proper.

**Comment by mganahl** [comment]
This version does not support restarts right now, and is in general geared towards tensornetwork applications. It could serve as a starting point for an implicitly restarted lanczos.

**Comment by mganahl** [comment]
I had a look at #3114, and this would indeed be interesting for us. The three most prevalent problems that pop up frequently in our applications are sparse symmetric (mostly SA or LA eigenvalues, usually only one to a few), sparse non-symmetric (with LR eigenvalues), and linear system solvers (symmetric and non-symmetric, i.e. gmres or lgmres), all of which we are currently working on.
The requirement in terms of robustness and accuracy are often less rigorous for tensor networks than for other applications, hence our implementations are more mundane. But if the JAX team was interested as well in supporting those, it could make sense to join efforts.

**Comment by shoyer** [comment]
GMRES and L-GMRES for linear solves would also be quite welcome in JAX. These would fit in quite naturally alongside our new CG solver.

**Comment by momchilmm** [comment]
> It would also be nice to include auto-diff rules for these operations, but that could come later.

Just a note on this: [here](https://github.com/fancompute/legume/blob/2c40563d13c866ba6829e25376f8c2386e9242ed/legume/primitives.py#L140) I have defined an `autograd` primitive wrapping `scipy.sparse.linalg.eigsh`. The `vjp` is almost identical to the one for `numpy.linalg.eigh`, but the summation in the backprop of eigenvector gradient is restricted only the `numeig` number of computed eigenvectors. This makes the eigenvector gradient approximate (becoming exact in the limit of `numeig` going to the linear size of the matrix). The gradient w.r.t. the eigenvalues however is exact. So you'll have to decide if you only support auto-diff w.r.t. the eigenvalues (I assume you don't want appoximate results...)

**Comment by mattjj** [comment]
Wowww cool, that is really helpful @momchilmm !

**Comment by shoyer** [comment]
Indeed, very cool to see! I also made a note with a few references about methods for calculating eigenvector derivatives from a partial decomposition over in https://github.com/google/jax/pull/3114.

**Comment by momchilmm** [comment]
@shoyer oh this is very interesting! I might consider adding something like this in my `autograd` implementation because storing all (or many of) the eigenvectors to get the exact gradient is sometimes a significant memory overhead.

**Comment by momchilmm** [comment]
@shoyer so I wrote a method to compute the eigenvector derivatives from a partial decomposition, along the lines of the works you had pointed out, and it works! Here's the [vjp](https://github.com/fancompute/legume/blob/99dd012feee28156292787330dac5e4f0c41d4c8/legume/primitives.py#L170-L210), and a [test](https://github.com/fancompute/legume/blob/99dd012feee28156292787330dac5e4f0c41d4c8/tests/test_primitives.py#L40-L66). The works mentioned in #3114 are overly complex because they consider degenerate eigenvalues, so I ended up following Steven Johnson's notes [here](https://math.mit.edu/~stevenj/18.336/adjoint.pdf), which I extended to the case of a Hermitian matrix with a small modification. 

So yeah this seems to work for non-degenerate eigenvalues. I do think (similarly to you I believe) that the gradient is not a well-defined quantity in the case of degenerate eigenvalues, specifically when we have more than one input parameters. Basically, for a single parameter, you can define the derivative of each eigenvalue by choosing eigenvectors in your subspace that are also eigenvectors of the system with the corresponding small perturbation. However, this choice of eigenvectors will be *different* for every different input parameter (corresponding to a different matrix perturbation), and so a full gradient cannot be defined.

**Comment by jackd** [comment]
@momchilmm I've been playing around with your vjp, and I occasionally get wildly inaccurate gradients. I'm guessing this is related to the cg-solve operating on a [necessarily non-positive definite matrix](https://github.com/fancompute/legume/blob/99dd012feee28156292787330dac5e4f0c41d4c8/legume/primitives.py#L195). Have you enountered this? Any thoughts?

**Comment by momchilmm** [comment]
@jackd I think you are right! I have not encountered it myself since it seems to just work in some cases, but I can see how that might be a problem in others. In the Steven Johsnon notes there's a footnote: 

> Since P commutes with A−α, we can solve for λ 0 easily by
an iterative method such as conjugate gradient: if we start with an
initial guess orthogonal to x, all subsequent iterates will also be
orthogonal to x and will thus converge to λ 0 (except for roundoff,
which can be corrected by multiplying the final result by P).

However I don't think that would *guarantee* convergence, unless I'm missing something? I'm also not sure what's the best method to use for this matrix - we only know that it's Hermitian. But you could try just changing the solver to bicg or gmers and see if your troubles are gone. If you see it becoming stable I encourage you to submit a PR!

**Comment by jackd** [comment]
@momchilmm glad I'm not going crazy :). I'm not having trouble with the smallest eigenvalue - and if I were I suspect a small diagonal shift might be enough to resolve it - but I am finding my tests often break as I increase the number of eigenvectors solved.

I'm looking at [MINRES-QLD](https://www.mcs.anl.gov/papers/P3027-0812.pdf) as a substitute, as it explicitly caters for singular symmetric matrices with pre-conditioning - alas there's no jax implementation of that though, so it's not just a one-line change :S.

**Comment by jackd** [comment]
Sigh, false alarm. Turns out my errors were due to my `lobpcg` implementation returning eigenvectors with different signs in the forward difference gradient check. I'll keep this in mind if I get any more NaN errors / gradient mis-matches in the future, but I have no evidence to suggest this is a problem at this stage. Thanks anyway :)

**Comment by momchilmm** [comment]
Ah. Yeah. If your objective function depends on the sign (or complex phase more generally) of the eigenvectors, and you're not deterministically setting it in your solver, then you're in trouble yeah. That's one of the main reasons this current issue exists.

**Comment by jackd** [comment]
If anyone's looking for a LOBPCG implementation I've hacked up a basic implementation [here](https://github.com/jackd/jju/blob/master/jju/linalg/lobpcg/basic.py#L11). The sparse implementation works without `jit`ting - but I need to work out how to resolve [this issue](https://github.com/google/jax/issues/5609) before the sparse jitted version will work.

There's also some `vjp`s [here](https://github.com/jackd/jju/blob/master/jju/linalg/custom_gradients.py#L29) based on @momchilmm's work above. Needs some more documentation, but hopefully the tests show integration with `lobpcg`.

**Comment by lobpcg** [comment]
> If anyone's looking for a LOBPCG implementation I've hacked up a basic implementation [here](https://github.com/jackd/jju/blob/master/jju/linalg/lobpcg/basic.py#L11). The sparse implementation works without `jit`ting - but I need to work out how to resolve [this issue](https://github.com/google/jax/issues/5609) before the sparse jitted version will work.
> 
> There's also some `vjp`s [here](https://github.com/jackd/jju/blob/master/jju/linalg/custom_gradients.py#L29) based on @momchilmm's work above. Needs some more documentation, but hopefully the tests show integration with `lobpcg`.

See also https://github.com/eserie/jju

**Comment by vlad17** [comment]
Hey @jackd , are you planning on putting together a PR to land a version of lobpcg into jax core?

**Comment by jackd** [comment]
@vlad17 no plan to right now. I'm willing to bet it wouldn't be a high priority from the jax core team even if it fit in the package (from memory mine is based on a pytorch implementation as opposed to the scipy one). Anyone else can feel free to use it however they want (e.g. for their own PR), though I haven't looked at it for a while so @lobpcg 's more recent adaption is probably in a better state.

**Comment by vlad17** [comment]
@lobpcg I've been toying with a simplified but fairly stable version of LOBPCG which solves the standard eigenvalue problem. I think JAX users would benefit from a PR which puts this into an experimental jax directory. Would you be able to help review it for correctness?

**Comment by vlad17** [comment]
@mganahl `jax.experimental.sparse.linalg.lobpcg_standard` is in master. Right now it's top-k only, no jvp, so pretty barebones, but feel free to give it a spin and let me know what you think.

**Comment by choltz95** [comment]
Thanks a ton for your work on this. `jax.experimental.sparse` has been generally really helpful for my projects & I appreciate that it's actively developed. I think something that would be nice is having an argument for a preconditioner + bottom-k eigenvalues. I saw that there are already some comments in master about it. I have been doing this with some success on big Laplacians & happy to submit a PR, but unsure if there are design considerations. 

On something else - I know preconditioning has been discussed in the main matrix-free thread (#1531), but I also want to express my interest in something like an accelerated multigrid preconditioner.

**Comment by vlad17** [comment]
bottom-k and preconditioner are reasonable next steps; I could add them (or review) if there are enough use cases that they'd be high priority.

@rmlarsen mentioned some interest in bottom-k, though not sure if he knows about possible users for it.

**Comment by lobpcg** [comment]
@rmlarsen @choltz95 The bottom-k of a matrix A is trivial to run in the existing code just run the code on negative matrix -A and change the sign of the eigenvalues to the opposite in the existing code at a level of the user.

@vlad17 Or modify the code to select the smallest eigenvalues instead of the largest in the RR; cf. option "largest" in https://github.com/scipy/scipy/blob/main/scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py

**Comment by rmlarsen** [comment]
When I said "smallest" I meant smallest absolute value. Of course flipping the sign of `A` is trivial.

**Comment by jakevdp** [comment]
How hard would it be to add a shift-invert mode to the current lobpcg solver?

**Comment by rmlarsen** [comment]
The way I read the paper, the beautiful thing about LOBPCG is it's ability to solve for 1/lambda by a change of variables in the generalized eigenvalue problem.

**Comment by choltz95** [comment]
For my specific use case w/ Laplacians, there isn't too much ambiguity about the eigenvalues (large, small, etc. are all nonnegative). So flipping the sign of A or order of RR like prev. mentioned is great. At least for me, the important thing is that preconditioning (which is already there, just commented out) can be valuable for large problems.

**Comment by lobpcg** [comment]
@rmlarsen Solving Ax = lambda Bx in LOBPCG, the matrix B must be positive definite (PD). If A is not PD, you cannot plug Bx = 1/lambda Ax into LOBPCG

**Comment by rmlarsen** [comment]
@lobpcg If B is the identity, I can use LOBPCG for this, right?

**Comment by lobpcg** [comment]
@jakevdp LOBPCG is matrix-free, so solving Ax = lambda Bx in LOBPCG one needs only the multiplications by A and B, e.g., via external functions, but B must be PD.  

One can solve Ax = lambda x in the shift-invert mode with a fixed shift alpha in LOBPCG, e.g., by plugging inv(A - alpha I) x = gamma x, by providing a function that solves (A - alpha I) x = b and going for largest or smallest gamma, which would give lambdas around the shift alpha, separately below and above alpha

**Comment by lobpcg** [comment]
> @lobpcg So if B is the identity, I can use LOBPCG for this, right?

Let me clarify: LOBPCG solves for smallest or largest eigenvalues of Ax = lambda Bx, where A is symmetric, and B is symmetric positive definite, e.g., B=I. Whatever eigenvalue problem you want to solve originally, you need to transform it mathematically into this form and satisfy these assumptions. If these assumptions are violated, the code would most likely break.

**Comment by rmlarsen** [comment]
@lobpcg and by "smallest lambda" you mean the "largest of 1/lambda"?

**Comment by lobpcg** [comment]
> @lobpcg and by "smallest lambda" you mean the "largest of 1/lambda"?

Remember that A does not need to be positive, only B must be positive, so lambda can be positive, negative, or zero. One could only plug Bx = 1/lambda Ax into LOBPCG if A is positive.

**Comment by rmlarsen** [comment]
@lobpcg ah, thanks for clarifying. So in the case where A is positive, is there any advantage of rewriting to Bx = 1/lambda Ax, rather than solving for the largest eigenvalues of -A (when B=I). I suppose the gap structure and thus speed of convergence comes into play then?

**Comment by lobpcg** [comment]
> @lobpcg ah, thanks for clarifying. So in the case where A is positive, is there any advantage of rewriting to Bx = 1/lambda Ax, rather than solving for the largest eigenvalues of -A (when B=I). I suppose the gap structure and thus speed of convergence comes into play then?

Good question. Without doing any math, I would guess that that speed should probably be the same, since in both cases one only multiplies by A anyways. The convergence speed is technically determined by the relative gap, so one should be able to write it down and compare.  Too lazy to do it myself at the moment :=)

**Comment by rmlarsen** [comment]
@lobpcg you are right. The relative gap size should be the same to first order.

**Comment by jemisjoky** [comment]
On a much more mundane level, I just wanted to point out that `jax.experimental.sparse.linalg.lobpcg_standard` currently crashes when a complex Hermitian matrix is input. I'm including a script below that reproduces this issue, but the fix is simply to change [this line](https://github.com/google/jax/blob/3cd069f2dabe0db9a714556effa15b9c44ca13d7/jax/experimental/sparse/linalg.py#L139) to `theta = jnp.sum(X * AX, axis=0, keepdims=True).real`.

SCRIPT
```python
import jax.numpy as jnp
from jax.experimental.sparse.linalg import lobpcg_standard

for dtype in ("float32", "complex64"):
    matrix = jnp.zeros((6, 6), dtype=dtype).at[0, 0].set(1)
    init_vec = jnp.ones((6, 1), dtype=dtype)

    output = lobpcg_standard(matrix, init_vec)
    print(f"LOBPCG works with {dtype}")
```

OUTPUT
```
LOBPCG works with float32
Traceback (most recent call last):
  File "jax_bug_test.py", line 9, in <module>
    eig_info = lobpcg_standard(matrix, init_vec)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/experimental/sparse/linalg.py", line 97, in lobpcg_standard
    return _lobpcg_standard_matrix(A, X, m, tol, debug=False)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/_src/api.py", line 622, in cache_miss
    execute = dispatch._xla_call_impl_lazy(fun_, *tracers, **params)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/_src/dispatch.py", line 241, in _xla_call_impl_lazy
    return xla_callable(fun, device, backend, name, donated_invars, keep_unused,
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/linear_util.py", line 303, in memoized_fun
    ans = call(fun, *args)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/_src/dispatch.py", line 357, in _xla_callable_uncached
    computation = sharded_lowering(fun, device, backend, name, donated_invars,
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/_src/dispatch.py", line 348, in sharded_lowering
    return pxla.lower_sharding_computation(
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/interpreters/pxla.py", line 2792, in lower_sharding_computation
    jaxpr, global_out_avals, consts = pe.trace_to_jaxpr_final(
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 2065, in trace_to_jaxpr_final
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1998, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/linear_util.py", line 167, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/experimental/sparse/linalg.py", line 108, in _lobpcg_standard_matrix
    return _lobpcg_standard_callable(
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/_src/api.py", line 626, in cache_miss
    top_trace.process_call(primitive, fun_, tracers, params))
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1739, in process_call
    jaxpr, out_type, consts = trace_to_subjaxpr_dynamic2(f, self.main, debug_info=dbg)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 2027, in trace_to_subjaxpr_dynamic2
    ans = fun.call_wrapped(*in_tracers_)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/linear_util.py", line 167, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/experimental/sparse/linalg.py", line 231, in _lobpcg_standard_callable
    state = jax.lax.while_loop(cond, body, state)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/_src/lax/control_flow/loops.py", line 1119, in while_loop
    _check_tree_and_avals("body_fun output and input",
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/_src/lax/control_flow/common.py", line 108, in _check_tree_and_avals
    raise TypeError(f"{what} must have identical types, got\n{diff}.")
jax._src.traceback_util.UnfilteredStackTrace: TypeError: body_fun output and input must have identical types, got
('ShapedArray(int32[], weak_type=True)', 'ShapedArray(complex64[6,1])', 'ShapedArray(complex64[6,1])', 'ShapedArray(complex64[6,1])', 'ShapedArray(int32[])', 'DIFFERENT ShapedArray(float32[1,1]) vs. ShapedArray(complex64[1,1])').

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "jax_bug_test.py", line 9, in <module>
    eig_info = lobpcg_standard(matrix, init_vec)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/experimental/sparse/linalg.py", line 97, in lobpcg_standard
    return _lobpcg_standard_matrix(A, X, m, tol, debug=False)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/experimental/sparse/linalg.py", line 108, in _lobpcg_standard_matrix
    return _lobpcg_standard_callable(
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/experimental/sparse/linalg.py", line 231, in _lobpcg_standard_callable
    state = jax.lax.while_loop(cond, body, state)
TypeError: body_fun output and input must have identical types, got
('ShapedArray(int32[], weak_type=True)', 'ShapedArray(complex64[6,1])', 'ShapedArray(complex64[6,1])', 'ShapedArray(complex64[6,1])', 'ShapedArray(int32[])', 'DIFFERENT ShapedArray(float32[1,1]) vs. ShapedArray(complex64[1,1])').
(umps38) ~/Orquestra/z-qml-nlp (new_core_types ✗) python jax_bug_test.py
LOBPCG works with float32
Traceback (most recent call last):
  File "jax_bug_test.py", line 8, in <module>
    eig_info = lobpcg_standard(matrix, init_vec)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/experimental/sparse/linalg.py", line 97, in lobpcg_standard
    return _lobpcg_standard_matrix(A, X, m, tol, debug=False)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/_src/api.py", line 622, in cache_miss
    execute = dispatch._xla_call_impl_lazy(fun_, *tracers, **params)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/_src/dispatch.py", line 241, in _xla_call_impl_lazy
    return xla_callable(fun, device, backend, name, donated_invars, keep_unused,
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/linear_util.py", line 303, in memoized_fun
    ans = call(fun, *args)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/_src/dispatch.py", line 357, in _xla_callable_uncached
    computation = sharded_lowering(fun, device, backend, name, donated_invars,
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/_src/dispatch.py", line 348, in sharded_lowering
    return pxla.lower_sharding_computation(
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/interpreters/pxla.py", line 2792, in lower_sharding_computation
    jaxpr, global_out_avals, consts = pe.trace_to_jaxpr_final(
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 2065, in trace_to_jaxpr_final
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1998, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/linear_util.py", line 167, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/experimental/sparse/linalg.py", line 108, in _lobpcg_standard_matrix
    return _lobpcg_standard_callable(
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/_src/api.py", line 626, in cache_miss
    top_trace.process_call(primitive, fun_, tracers, params))
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1739, in process_call
    jaxpr, out_type, consts = trace_to_subjaxpr_dynamic2(f, self.main, debug_info=dbg)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 2027, in trace_to_subjaxpr_dynamic2
    ans = fun.call_wrapped(*in_tracers_)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/linear_util.py", line 167, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/experimental/sparse/linalg.py", line 231, in _lobpcg_standard_callable
    state = jax.lax.while_loop(cond, body, state)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/_src/lax/control_flow/loops.py", line 1119, in while_loop
    _check_tree_and_avals("body_fun output and input",
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/_src/lax/control_flow/common.py", line 108, in _check_tree_and_avals
    raise TypeError(f"{what} must have identical types, got\n{diff}.")
jax._src.traceback_util.UnfilteredStackTrace: TypeError: body_fun output and input must have identical types, got
('ShapedArray(int32[], weak_type=True)', 'ShapedArray(complex64[6,1])', 'ShapedArray(complex64[6,1])', 'ShapedArray(complex64[6,1])', 'ShapedArray(int32[])', 'DIFFERENT ShapedArray(float32[1,1]) vs. ShapedArray(complex64[1,1])').

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "jax_bug_test.py", line 8, in <module>
    eig_info = lobpcg_standard(matrix, init_vec)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/experimental/sparse/linalg.py", line 97, in lobpcg_standard
    return _lobpcg_standard_matrix(A, X, m, tol, debug=False)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/experimental/sparse/linalg.py", line 108, in _lobpcg_standard_matrix
    return _lobpcg_standard_callable(
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/jax/experimental/sparse/linalg.py", line 231, in _lobpcg_standard_callable
    state = jax.lax.while_loop(cond, body, state)
TypeError: body_fun output and input must have identical types, got
('ShapedArray(int32[], weak_type=True)', 'ShapedArray(complex64[6,1])', 'ShapedArray(complex64[6,1])', 'ShapedArray(complex64[6,1])', 'ShapedArray(int32[])', 'DIFFERENT ShapedArray(float32[1,1]) vs. ShapedArray(complex64[1,1])').
```

**Comment by jakevdp** [comment]
@jemisjoky good catch! Are you interested in doing a pull request with the fix? If not I can look into it.

**Comment by jemisjoky** [comment]
@jakevdp, I'd love to! I honestly haven't done a PR with a major project like JAX before, but the [contributor guide](https://jax.readthedocs.io/en/latest/contributing.html) is pretty clear here. Will let you know if I have any questions in the process!

**Comment by lobpcg** [comment]
> Hi, apologies for the bump. Is there any news on the implementation of sparse eigensolvers for smallest eigenvalues? Currently, `jax.experimental.sparse.linalg.lobpcg_standard` seems to only support largest eigenvalues. Thanks!

Just run LOBPCG for -A where A is the matrix of the eigenvalue problem and multiply the largest eigenvectors of -A by -1.

**Comment by rmlarsen** [comment]
I agree that running LOBPCG is probably your best choice for not. If by smallest you mean of smallest magnitude, you can try running LOBPCG on the inverse of A, if that is available. 

Notice that we recently added a mechanism `subset_by_index` for selecting a subset of eigenvalues in the spectral bisection eigensolver  here: https://github.com/google/jax/blob/main/jax/_src/lax/eigh.py#L506
It is also available for the corresponding SVD. There is no such thing for general non-Hermitian matrices.

**Comment by lobpcg** [comment]
The inverse is typically infeasible although may give a much faster convergence in theory.

A function multiplying by -A is always feasible. That's the approach used, e.g., in LOBPCG's scipy implementation.

In contrast to a popular misunderstanding,  LOBPCG does not require the matrix to be positive definite.

**Comment by qiyang-ustc** [comment]
Hi, everyone. I am new here, and my target is to implement dominant eigensolver for Tensor Network. I am not sure if vanilla Krylov/Arnoldi solver is also what people want in this context(It seems you are interested in LOBPCG).

For my work, I have a very naive implementation: https://github.com/qiyang-ustc/jaxeigs . The Arnoldi decomposition can be processed on GPU and the final callback is on CPU(via pure_callback).

In the future, I believe Krylov-Schur algorithm is what many people may want. And the kernel is the same: Arnoldi on GPU, Schur/eig on CPU. This is also the implementation in KrylovKit.jl I am working on this.

If anyone has comments, please let me know.

**Comment by lobpcg** [comment]
> Hi, everyone. I am new here, and my target is to implement dominant eigensolver for Tensor Network. I am not sure if vanilla Krylov/Arnoldi solver is also what people want in this context(It seems you are interested in LOBPCG).

I am personally interested in LOBPCG since I have invented it :-) People have implemented it here, I guess, because it is simple, efficient, and have several features unavailable in Krylov; e.g., see https://en.wikipedia.org/wiki/LOBPCG, rather than because being interested in it... 

> For my work, I have a very naive implementation: https://github.com/qiyang-ustc/jaxeigs . The Arnoldi decomposition can be processed on GPU and the final callback is on CPU(via pure_callback).

LOBPCG uses a somewhat similar approach, but the size of the matrix solved by eig in LOBPCG is fixed, while in Krylov it grows with the number of iterations which could become a bottleneck leading to performance loss. 

I would be interested to see results of benchmarking with the existing implementation of LOBPCG as the baseline. If you post it please feel free to ping me. 

> In the future, I believe Krylov-Schur algorithm is what many people may want. And the kernel is the same: Arnoldi on GPU, Schur/eig on CPU. This is also the implementation in KrylovKit.jl I am working on this.

Krylov-Schur-Arnoldi solves non-symmetric eigenproblems while LOBPCG is limited to symmetric only which are however much more common in practice.

**Comment by qiyang-ustc** [comment]
@lobpcg  Thank you for your response a lot! I am sorry for my rudeness (T_T). I mentioned it just because the title is "sparse eigenvalue solvers", also, the original/pytorch version of`jaxeigs` in fact is written by(I guess) mostly by @mganahl , who opened this issue.  Thus I thought that everything is related :-) here

In the field of Tensor Network, non-symmetric problem is quite essential for many interesting problems, this is the main reason we want it. I greatly appriciate you introduction and demonstration for LOBPCG! Quite coincidentally, my current project involves symmetric problems at hand right now. Thus I'm going to try LOBPCG for that! Thank you again!
