### ISSUE TITLE
Using vmap inside defjvp

### ISSUE THREAD

**Issue by gao462** [google/jax#3201]
I have my own defined Jacobian-vector product function. It requires vertorizing function inside its computation. It seems that this will result in shape dismatch if I then use `jax.grad` or `jax.jacrev`. Although I can replace `vmap` result by my manually designed vectorized function, is it possible to allow `vmap` inside defvjp for convenience?
My code is long, so I put a brief description. (I can try to make a simple example if this is unclear):
```python
import jax

@jax.custom_jvp
def f(args):
    # do something
    pass

@f.defjvp
def f_jvp(primals, tangents):
    # do something
    pass

    # an inside function
    def g(args):
        # do something
        pass

    # vectorize it
    # vjp_py WILL RAISE SHAPE EXCEPTION AFTER f_jvp
    bat_g = jax.vmap(g)

    # do something with bat_g
    pass

# they will raise shape error at vjp_py
jax.grad(f)(something)
jax.jacrev(f)(something)
```

**Comment by gao462** [comment]
An example of the same problem:
```python
import jax
import jax.numpy as jnp
import jax.scipy as jsc

seed = 47
key = jax.random.PRNGKey(seed)
mat = jax.random.normal(key, (2, 2))

@jax.custom_jvp
def f(mat, aux):
    num_rows, num_cols = mat.shape
    return jnp.ones((num_rows, 1)) / num_cols

@f.defjvp
def f_jvp(primals, tangents):
    mat, aux = primals
    vec, _ = tangents
    output = f(*primals)
    num_rows, num_cols = mat.shape
    size = num_rows * num_cols
    bd_mat = mat.reshape(num_rows, 1, num_cols)
    bd_mat = jnp.tile(bd_mat, reps=(1, num_cols, 1))
    bd_mat = jsc.linalg.block_diag(*bd_mat)
    bd_sum = jnp.sum(mat, axis=1).reshape(num_rows, 1)
    bd_sum = jnp.tile(bd_sum, reps=(1, num_cols)).reshape(size)
    bd_sum = jsc.linalg.block_diag(*bd_sum)
    bd_buf = (bd_mat + bd_sum).reshape(num_rows, num_cols, size)
    bd_buf = jnp.moveaxis(bd_buf, (0, 1, 2), (2, 1, 0))
    # -----
    # Vertorizing or Broadcasting will raise shape error
    bd_buf = jnp.matmul(bd_buf, bd_mat.reshape(1, num_rows, num_cols))
    # -----
    # Manually Eumerate along axis can avoid shape error
    # // bd_buf_list = []
    # // for itr in bd_buf:
    # //     bd_buf_list.append(jnp.matmul(itr, mat))
    # // bd_buf = jnp.stack(bd_buf_list)
    # -----
    bd_buf = bd_buf / aux
    jvp = jnp.sum(bd_buf, axis=0)
    jvp = jnp.mean(jvp, axis=1, keepdims=True)
    return (output, jvp)

jax.jacrev(f)(mat, 0.5)
```

**Comment by hawkinsp** [comment]
Can you make the example self-contained and runnable? e.g., your second example doesn't use `vmap` and the first example isn't runnable.

**Comment by gao462** [comment]
Update the example. The problem is that JVP function ends successfully, but still get a shape error.
```python
import jax
import jax.numpy as jnp
import jax.scipy as jsc

seed = 47
key = jax.random.PRNGKey(seed)
mat = jax.random.normal(key, (2, 3))

@jax.custom_jvp
def f(mat, aux):
    num_rows, num_cols = mat.shape
    return jnp.ones((num_rows, 1)) / num_cols

@f.defjvp
def f_jvp(primals, tangents):
    mat, aux = primals
    vec, _ = tangents
    output = f(*primals)
    num_rows, num_cols = mat.shape
    size = num_rows * num_cols
    # -----
    bd_mat = mat.reshape(1, 1, num_rows, num_cols)
    bd_mat = jnp.tile(bd_mat, reps=(num_rows, num_cols))
    bd_mat = bd_mat.reshape(size, num_rows, num_cols)
    # -----
    rowsum = jnp.sum(mat, axis=1, keepdims=True)
    colsum = jnp.sum(mat, axis=0, keepdims=True)
    bd_rowsum = jnp.tile(rowsum, reps=(1, num_rows))
    bd_colsum = jnp.tile(colsum, reps=(num_cols, 1))
    # -----
    bd_vec = vec.reshape(size, 1)
    # -----
    def operate(mx, val):
        buf = 0
        for i in range(2):
            buf = buf + jnp.matmul(mx, bd_colsum) / jnp.power(aux, i)
        buf = jnp.matmul(bd_rowsum, buf)
        return buf * val
    # -----
    # Vertorizing will raise shape error
    bd_buf = jax.vmap(operate, in_axes=(0, 0), out_axes=0)(bd_mat, bd_vec)
    # -----
    bd_buf = bd_buf / aux
    jvp = jnp.sum(bd_buf, axis=0)
    jvp = jnp.mean(jvp, axis=1, keepdims=True)
    # -----
    # JVP ends successfully, but still raise an error
    print(output.shape, jvp.shape)
    return (output, jvp)

jax.grad(lambda mat, aux: jnp.sum(f(mat, aux)))(mat, 0.5)
```
My error message is
```
(2, 1) (2, 1)
Traceback (most recent call last):
  File "try.py", line 51, in <module>
    jax.grad(lambda mat, aux: jnp.sum(f(mat, aux)))(mat, 0.5)
  File "/homes/gao462/Miniconda3/envs/JAX/lib/python3.7/site-packages/jax/api.py", line 383, in grad_f
    _, g = value_and_grad_f(*args, **kwargs)
  File "/homes/gao462/Miniconda3/envs/JAX/lib/python3.7/site-packages/jax/api.py", line 450, in value_and_grad_f
    g = vjp_py(onp.ones((), dtype=dtype))
  File "/homes/gao462/Miniconda3/envs/JAX/lib/python3.7/site-packages/jax/api.py", line 1402, in _vjp_pullback_wrapper
    ans = fun(*args)
  File "/homes/gao462/Miniconda3/envs/JAX/lib/python3.7/site-packages/jax/interpreters/ad.py", line 113, in vjp_
    arg_cts = backward_pass(jaxpr, consts, dummy_args, dummy_primals_and_cts)
  File "/homes/gao462/Miniconda3/envs/JAX/lib/python3.7/site-packages/jax/interpreters/ad.py", line 225, in backward_pass
    cts_out = get_primitive_transpose(eqn.primitive)(cts_in, *invals, **eqn.params)
  File "/homes/gao462/Miniconda3/envs/JAX/lib/python3.7/site-packages/jax/interpreters/ad.py", line 466, in linear_transpose2
    return zero if cotangent is zero else transpose_rule(cotangent, *args, **kwargs)
  File "/homes/gao462/Miniconda3/envs/JAX/lib/python3.7/site-packages/jax/lax/lax.py", line 2986, in _reshape_transpose_rule
    return [reshape(t, operand.aval.shape)]
  File "/homes/gao462/Miniconda3/envs/JAX/lib/python3.7/site-packages/jax/lax/lax.py", line 685, in reshape
    dimensions=None if dimensions is None or same_dims else tuple(dimensions))
  File "/homes/gao462/Miniconda3/envs/JAX/lib/python3.7/site-packages/jax/core.py", line 211, in bind
    return self.impl(*args, **kwargs)
  File "/homes/gao462/Miniconda3/envs/JAX/lib/python3.7/site-packages/jax/lax/lax.py", line 2886, in _reshape_impl
    dimensions=dimensions)
  File "/homes/gao462/Miniconda3/envs/JAX/lib/python3.7/site-packages/jax/interpreters/xla.py", line 217, in apply_primitive
    compiled_fun = xla_primitive_callable(prim, *map(arg_spec, args), **params)
  File "/homes/gao462/Miniconda3/envs/JAX/lib/python3.7/site-packages/jax/interpreters/xla.py", line 231, in xla_primitive_callable
    aval_out = prim.abstract_eval(*avals, **params)
  File "/homes/gao462/Miniconda3/envs/JAX/lib/python3.7/site-packages/jax/lax/lax.py", line 1712, in standard_abstract_eval
    return ShapedArray(shape_rule(*args, **kwargs), dtype_rule(*args, **kwargs))
  File "/homes/gao462/Miniconda3/envs/JAX/lib/python3.7/site-packages/jax/lax/lax.py", line 2966, in _reshape_shape_rule
    raise TypeError(msg.format(new_sizes, onp.shape(operand)))
TypeError: reshape total size must be unchanged, got new_sizes (6, 1) for shape (6, 2, 3).
```

**Comment by mattjj** [comment]
Hey @gao462, I noticed that if I replace this line:

```python
    bd_buf = jax.vmap(operate, in_axes=(0, 0), out_axes=0)(bd_mat, bd_vec)
```

with this semantically equivalent line which avoids vmap:

```python
    bd_buf = jnp.stack([operate(x, y) for x, y in zip(bd_mat, bd_vec)])
```

Then I still get a shape error. That suggests to me the issue isn't specific to vmap. (Still, it's unclear to me exactly where or why this shape error is only cropping up in JAX internals...)

One other clue is that `jax.jvp(lambda mat: jnp.sum(f(mat, 0.5)), (mat,), (mat,))` runs fine.

**Comment by mattjj** [comment]
Ah, I see the issue: it's because of an implicit broadcast. Unfortunately I can't provide a great summary of it now, but hopefully this note is enough for my future self to go on...

**Comment by mattjj** [comment]
#6470 will fix this!
