### ISSUE TITLE
ValueError: conv_general_dilated lhs feature dimension size divided by feature_group_count must equal the rhs input feature dimension size, but 1 // 1 != 3.

### ISSUE THREAD

**Issue by rolandgvc** [google/jax#3289]
I was trying to get the per-example gradients by modifying the `train_step` function of the mnist example from Flax, but got this error. Any ideas what could be happening?

```python
@jax.jit
def train_step(optimizer, batch):
  """Train for a single step."""
  def loss_fn(model):
    logits = model(batch['image'])
    loss = cross_entropy_loss(logits, batch['label'])
    return loss, logits
  
  # Get per example gradients
  def vmap_loss_fn(model, inputs, labels):
    return cross_entropy_loss(model(inputs), labels)
  vmap_loss_grad = jax.vmap(jax.grad(vmap_loss_fn), in_axes=(None, 0, 0))
  grads = vmap_loss_grad(optimizer.target, batch['image'], batch['label'])
  print(onp.shape(grads))
  
  grad_fn = jax.value_and_grad(loss_fn, has_aux=True)
  (_, logits), grad = grad_fn(optimizer.target)
  print(type(grad))
  optimizer = optimizer.apply_gradient(grad)
  metrics = compute_metrics(logits, batch['label'])
  return optimizer, metrics

```

Traceback (most recent call last):
  File "mnist.py", line 232, in <module>
    app.run(main)
  File "/Applications/miniconda3/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Applications/miniconda3/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "mnist.py", line 228, in main
    train(train_ds, test_ds)
  File "mnist.py", line 214, in train
    optimizer, train_ds, batch_size, epoch, input_rng)
  File "mnist.py", line 164, in train_epoch
    optimizer, metrics = train_step(optimizer, batch)
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/api.py", line 154, in f_jitted
    name=flat_fun.__name__)
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/core.py", line 1021, in _call_bind
    outs = primitive.impl(f, *args, **params)
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/interpreters/xla.py", line 521, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, name, *map(arg_spec, args))
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/linear_util.py", line 221, in memoized_fun
    ans = call(fun, *args)
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/interpreters/xla.py", line 538, in _xla_callable
    fun, pvals, instantiate=False, stage_out=True, bottom=True)
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 438, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/linear_util.py", line 150, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "mnist.py", line 124, in train_step
    grads = vmap_loss_grad(optimizer.target, batch['image'], batch['label'])
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/api.py", line 770, in batched_fun
    lambda: flatten_axes(out_tree(), out_axes))
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/interpreters/batching.py", line 34, in batch
    return batched_fun.call_wrapped(*in_vals)
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/linear_util.py", line 150, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/api.py", line 383, in grad_f
    _, g = value_and_grad_f(*args, **kwargs)
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/api.py", line 440, in value_and_grad_f
    ans, vjp_py = _vjp(f_partial, *dyn_args)
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/api.py", line 1456, in _vjp
    out_primal, out_vjp = ad.vjp(flat_fun, primals_flat)
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/interpreters/ad.py", line 106, in vjp
    out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/interpreters/ad.py", line 95, in linearize
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr(jvpfun_flat, in_pvals)
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 438, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/linear_util.py", line 150, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "mnist.py", line 122, in vmap_loss_fn
    return cross_entropy_loss(model(inputs), labels)
  File "/Users/rolandgavrilescu/Github/flax/flax/nn/base.py", line 907, in __call__
    return self.module.call(self.params, *args, **kwargs)
  File "/Users/rolandgavrilescu/Github/flax/flax/nn/base.py", line 221, in wrapper
    return super_fn(*args, **kwargs)
  File "/Users/rolandgavrilescu/Github/flax/flax/nn/base.py", line 538, in call
    y = instance.apply(*args, **kwargs)
  File "mnist.py", line 67, in apply
    x = nn.Conv(x, features=32, kernel_size=(3, 3))
  File "/Users/rolandgavrilescu/Github/flax/flax/nn/base.py", line 277, in __new__
    y = instance.apply(*args, **apply_kwargs)
  File "/Users/rolandgavrilescu/Github/flax/flax/nn/linear.py", line 243, in apply
    precision=precision)
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/lax/lax.py", line 548, in conv_general_dilated
    precision=_canonicalize_precision(precision))
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/core.py", line 214, in bind
    out_tracer = top_trace.process_primitive(self, tracers, kwargs)
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/interpreters/ad.py", line 330, in process_primitive
    primal_out, tangent_out = jvp(primals_in, tangents_in, **params)
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/interpreters/ad.py", line 475, in standard_jvp
    val_out = primitive.bind(*primals, **params)
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/core.py", line 214, in bind
    out_tracer = top_trace.process_primitive(self, tracers, kwargs)
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/interpreters/batching.py", line 134, in process_primitive
    val_out, dim_out = batched_primitive(vals_in, dims_in, **params)
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/lax/lax.py", line 2413, in _conv_general_dilated_batch_rule
    feature_group_count, precision=precision)
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/lax/lax.py", line 548, in conv_general_dilated
    precision=_canonicalize_precision(precision))
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/core.py", line 214, in bind
    out_tracer = top_trace.process_primitive(self, tracers, kwargs)
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 143, in process_primitive
    return self.default_process_primitive(primitive, tracers, params)
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 153, in default_process_primitive
    out_aval = primitive.abstract_eval(*avals, **params)
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/lax/lax.py", line 1712, in standard_abstract_eval
    return ShapedArray(shape_rule(*args, **kwargs), dtype_rule(*args, **kwargs))
  File "/Applications/miniconda3/lib/python3.7/site-packages/jax/lax/lax.py", line 2237, in _conv_general_dilated_shape_rule
    rhs.shape[dimension_numbers.rhs_spec[1]]))
ValueError: conv_general_dilated lhs feature dimension size divided by feature_group_count must equal the rhs input feature dimension size, but 1 // 1 != 3.

**Comment by rolandgvc** [comment]
Solved by adding an extra dimension to inputs and labels.

**Comment by mapmeld** [comment]
for others with a similar issue, it turned out that my ResNet code expected image dimensions in NCHW order {batch size, channels, height, width}, and my data source had color channels as the last dimension. Use ```tf.transpose(images, [0, 3, 1, 2])```

**Comment by rolandgvc** [comment]
@mapmeld You can also have a look at the ResNet implementation from [flaxvision](https://github.com/rolandgvc/flaxvision), specifically at how parameter conversion is being handled.
