### ISSUE TITLE
pip install with Python 2.7 on Mac OS fails

### ISSUE THREAD

**Issue by kmader** [google/jax#342]
The install succeeds with `pip install jax jaxlib` but when you try to import the library XLA does not seem to be found
```
>>> import jax
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/jaxtest/lib/python2.7/site-packages/jax/__init__.py", line 17, in <module>
    from jax.api import *
  File "/anaconda3/envs/jaxtest/lib/python2.7/site-packages/jax/api.py", line 42, in <module>
    from .lib.xla_bridge import canonicalize_dtype
  File "/anaconda3/envs/jaxtest/lib/python2.7/site-packages/jax/lib/xla_bridge.py", line 34, in <module>
    from jaxlib import xla_client
  File "/anaconda3/envs/jaxtest/lib/python2.7/site-packages/jaxlib/xla_client.py", line 33, in <module>
    from . import pywrap_xla as c_api
  File "/anaconda3/envs/jaxtest/lib/python2.7/site-packages/jaxlib/pywrap_xla.py", line 28, in <module>
    _pywrap_xla = swig_import_helper()
  File "/anaconda3/envs/jaxtest/lib/python2.7/site-packages/jaxlib/pywrap_xla.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_xla', fp, pathname, description)
ImportError: dynamic module does not define init function (init_pywrap_xla)
```

## Python Version
```
Python 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 13:10:39) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
```

**Comment by hawkinsp** [comment]
Hmm. That's unfortunate.

I'm pretty sure the Python 3 wheels work fine on Mac, so you might try one of them for now.

My guess is I was over-aggressive in hiding symbols in the fix for: https://github.com/google/jax/issues/120
and that broke the combination of Mac and Python 2.7.

**Comment by kmader** [comment]
Thanks, that fixed it, but unfortunately I have a number of not yet py3 libraries and so I'll need a second environment just for jax

**Comment by hawkinsp** [comment]
I should have a fix shortly, although it will require a new jaxlib release (which happily I was just about to make anyway.)

**Comment by hawkinsp** [comment]
I've pushed new jaxlib wheels. A `pip install --upgrade jaxlib` should fix the problem.

Hope that helps!

**Comment by kmader** [comment]
Thanks great!
