### ISSUE TITLE
Improve jnp.sum's error messages for tuple inputs

### ISSUE THREAD

**Issue by ajbrock** [google/jax#3451]
I feel that the error messages related to jax.numpy.sum's handling of tuples could be improved.

Normally if you pass the wrong type of thing to a jax.numpy function it gives you an unexpected input type. However, if you pass a tuple of e.g. (array_or_tracer, {}) to jnp.sum it gives "RuntimeError: Invalid argument: Unknown NumPy type O size 8", e.g. jnp.sum((jnp.zeros(1), {})). Even simpler, jnp.sum(({},)). [I'm now also getting this on jnp.sum({}) maybe?]. Compare this to jnp.sum({'x': jnp.zeros(1)}) which throws a type error. 

This came up in a spot with a lot of other moving parts, due to a typo on my end, but this error message made it difficult for me to spot exactly what went wrong initially. I think I see why it is this way since sum allows you to pass in tuples, but maybe some type-checking of the tuples would be better here rather than a runtime error?

**Comment by IgorWilbert** [comment]
@mattjj could you please explain what you think that should be done here? I would like to work on it, if it is not too complex. Thank you!

**Comment by jakevdp** [comment]
This seems to be relatively recent. In jax v0.1.69, I get this error
```
>>> import jax.numpy as jnp
>>> jnp.sum((jnp.zeros(1), {}))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-9cd439c142de> in <module>()
      1 import jax.numpy as jnp
----> 2 jnp.sum((jnp.zeros(1), {}))

/usr/local/lib/python3.6/dist-packages/jax/numpy/lax_numpy.py in reduction(a, axis, dtype, out, keepdims)
   1520       raise ValueError("reduction does not support the `out` argument.")
   1521 
-> 1522     a = a if isinstance(a, ndarray) else asarray(a)
   1523     a = preproc(a) if preproc else a
   1524     dims = _reduction_dims(a, axis)

/usr/local/lib/python3.6/dist-packages/jax/numpy/lax_numpy.py in asarray(a, dtype, order)
   2141 def asarray(a, dtype=None, order=None):
   2142   lax._check_user_dtype_supported(dtype, "asarray")
-> 2143   return array(a, dtype=dtype, copy=False, order=order)
   2144 
   2145 

/usr/local/lib/python3.6/dist-packages/jax/numpy/lax_numpy.py in array(object, dtype, copy, order, ndmin)
   2121   elif isinstance(object, (list, tuple)):
   2122     if object:
-> 2123       out = stack([array(elt, dtype=dtype) for elt in object])
   2124     else:
   2125       out = array(np.array([], dtype or float_))

/usr/local/lib/python3.6/dist-packages/jax/numpy/lax_numpy.py in <listcomp>(.0)
   2121   elif isinstance(object, (list, tuple)):
   2122     if object:
-> 2123       out = stack([array(elt, dtype=dtype) for elt in object])
   2124     else:
   2125       out = array(np.array([], dtype or float_))

/usr/local/lib/python3.6/dist-packages/jax/numpy/lax_numpy.py in array(object, dtype, copy, order, ndmin)
   2132       return array(np.asarray(view), dtype, copy)
   2133 
-> 2134     raise TypeError("Unexpected input type for array: {}".format(type(object)))
   2135 
   2136   if ndmin > ndim(out):

TypeError: Unexpected input type for array: <class 'dict'>
```
In jax version 0.1.70, I get this:
```
>>> import jax.numpy as jnp
>>> jnp.sum((jnp.zeros(1), {}))
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-2-9cd439c142de> in <module>()
      1 import jax.numpy as jnp
----> 2 jnp.sum((jnp.zeros(1), {}))

/usr/local/lib/python3.6/dist-packages/jax/numpy/lax_numpy.py in reduction(a, axis, dtype, out, keepdims)
   1520       raise ValueError("reduction does not support the `out` argument.")
   1521 
-> 1522     a = a if isinstance(a, ndarray) else asarray(a)
   1523     a = preproc(a) if preproc else a
   1524     dims = _reduction_dims(a, axis)

/usr/local/lib/python3.6/dist-packages/jax/numpy/lax_numpy.py in asarray(a, dtype, order)
   2155 def asarray(a, dtype=None, order=None):
   2156   lax._check_user_dtype_supported(dtype, "asarray")
-> 2157   return array(a, dtype=dtype, copy=False, order=order)
   2158 
   2159 

/usr/local/lib/python3.6/dist-packages/jax/numpy/lax_numpy.py in array(object, dtype, copy, order, ndmin)
   2126   elif isinstance(object, (list, tuple)):
   2127     if object:
-> 2128       out = stack([array(elt, dtype=dtype) for elt in object])
   2129     else:
   2130       out = _device_put_raw(np.array([], dtype or float_))

/usr/local/lib/python3.6/dist-packages/jax/numpy/lax_numpy.py in <listcomp>(.0)
   2126   elif isinstance(object, (list, tuple)):
   2127     if object:
-> 2128       out = stack([array(elt, dtype=dtype) for elt in object])
   2129     else:
   2130       out = _device_put_raw(np.array([], dtype or float_))

/usr/local/lib/python3.6/dist-packages/jax/numpy/lax_numpy.py in array(object, dtype, copy, order, ndmin)
   2118 
   2119   if type(object) is np.ndarray:
-> 2120     out = _device_put_raw(object)
   2121     if dtype: assert _dtype(out) == dtype
   2122   elif isinstance(object, (DeviceValue, core.Tracer)):

/usr/local/lib/python3.6/dist-packages/jax/numpy/lax_numpy.py in _device_put_raw(x)
   2148 
   2149 def _device_put_raw(x):
-> 2150   aval = core.raise_to_shaped(core.get_aval(x))
   2151   return array_result_handler(None, aval)(device_put(x))
   2152 

/usr/local/lib/python3.6/dist-packages/jax/core.py in get_aval(x)
    770     return x.aval
    771   else:
--> 772     return concrete_aval(x)
    773 
    774 

/usr/local/lib/python3.6/dist-packages/jax/core.py in concrete_aval(x)
    762   for typ in type(x).mro():
    763     handler = pytype_aval_mappings.get(typ)
--> 764     if handler: return handler(x)
    765   raise TypeError(f"{type(x)} is not a valid JAX type")
    766 

/usr/local/lib/python3.6/dist-packages/jax/core.py in __init__(self, val, weak_type)
    960     # Note: canonicalized self.dtype doesn't necessarily match self.val
    961     self.val = val
--> 962     assert self.dtype != onp.dtype('O')
    963 
    964   def __eq__(self, other):

AssertionError: 
```
The best way to proceed would be to try to identify what caused this regression in behavior.

**Comment by IgorWilbert** [comment]
@jakevdp thank you for the explanation, I will take a look.

**Comment by IgorWilbert** [comment]
@jakevdp upon investigation I think the behavior change you mentioned was introduced by #3350 . For testing, try pointing HEAD to `2a10dbbf3730ca8ff359716652b9e7fb590a365e` (before) and `fd886b17a48f23637f3fcae810117721f155e16c` (after).

**Comment by IgorWilbert** [comment]
@jakevdp I think I was able to identify another change in the behavior.
Before (ae60654dd4314f38eecc86b83f4949aab9960e1e)
```
>>> import jax.numpy as jnp
>>> jnp.sum((jnp.zeros(1), {}))
/Users/igor/projects/jax/jax/lib/xla_bridge.py:125: UserWarning: No GPU/TPU found, falling back to CPU.
  warnings.warn('No GPU/TPU found, falling back to CPU.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/igor/projects/jax/jax/numpy/lax_numpy.py", line 1522, in reduction
    a = a if isinstance(a, ndarray) else asarray(a)
  File "/Users/igor/projects/jax/jax/numpy/lax_numpy.py", line 2157, in asarray
    return array(a, dtype=dtype, copy=False, order=order)
  File "/Users/igor/projects/jax/jax/numpy/lax_numpy.py", line 2128, in array
    out = stack([array(elt, dtype=dtype) for elt in object])
  File "/Users/igor/projects/jax/jax/numpy/lax_numpy.py", line 2128, in <listcomp>
    out = stack([array(elt, dtype=dtype) for elt in object])
  File "/Users/igor/projects/jax/jax/numpy/lax_numpy.py", line 2120, in array
    out = _device_put_raw(object)
  File "/Users/igor/projects/jax/jax/numpy/lax_numpy.py", line 2150, in _device_put_raw
    aval = core.raise_to_shaped(core.get_aval(x))
  File "/Users/igor/projects/jax/jax/core.py", line 785, in get_aval
    return concrete_aval(x)
  File "/Users/igor/projects/jax/jax/core.py", line 777, in concrete_aval
    if handler: return handler(x)
  File "/Users/igor/projects/jax/jax/core.py", line 975, in __init__
    assert self.dtype != onp.dtype('O')
AssertionError
```
After (d55c0edeace05c51fc979d0ea2481c2cb72992ca)
```
>>> import jax.numpy as jnp
>>> jnp.sum((jnp.zeros(1), {}))
/Users/igor/projects/jax/jax/lib/xla_bridge.py:125: UserWarning: No GPU/TPU found, falling back to CPU.
  warnings.warn('No GPU/TPU found, falling back to CPU.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/igor/projects/jax/jax/numpy/lax_numpy.py", line 1522, in reduction
    a = a if isinstance(a, ndarray) else asarray(a)
  File "/Users/igor/projects/jax/jax/numpy/lax_numpy.py", line 2163, in asarray
    return array(a, dtype=dtype, copy=False, order=order)
  File "/Users/igor/projects/jax/jax/numpy/lax_numpy.py", line 2131, in array
    out = stack([array(elt, dtype=dtype) for elt in object])
  File "/Users/igor/projects/jax/jax/numpy/lax_numpy.py", line 2131, in <listcomp>
    out = stack([array(elt, dtype=dtype) for elt in object])
  File "/Users/igor/projects/jax/jax/numpy/lax_numpy.py", line 2120, in array
    out = _device_put_raw(object)
  File "/Users/igor/projects/jax/jax/numpy/lax_numpy.py", line 2157, in _device_put_raw
    return array_result_handler(None, abstractify(x))(device_put(x))
  File "/Users/igor/projects/jax/jax/interpreters/xla.py", line 114, in device_put
    return device_put_handlers[type(x)](x, device)
  File "/Users/igor/projects/jax/jax/interpreters/xla.py", line 120, in _device_put_array
    return backend.buffer_from_pyval(x, device)
RuntimeError: Invalid argument: Unknown NumPy type O size 8
```

**Comment by mattjj** [comment]
@IgorWilbert, thanks for pinning this down! That's super helpful already.

I'm not sure exactly what the fix should be; I might try poking at it too to see what's going on.

**Comment by mkunesch** [comment]
The error message now (version `0.2.18`) is:

```TypeError: sum requires ndarray or scalar arguments, got <class 'tuple'> at position 0.```

so I think this has been solved. Please reopen the issue if that's incorrect!
