### ISSUE TITLE
Issue with JIT when compiling scan function with given length

### ISSUE THREAD

**Issue by markusschmitt** [google/jax#3603]
Hi,

I encounter an issue when compiling a scan function with given length. A minimal example is
```
import jax

def do_stuff(length):
    def f(carry,x):
        return carry, [None]

    jax.lax.scan(f,[1], xs=None, length=length)

jax.jit(do_stuff)(10)
```
which produces the error message
```
Traceback (most recent call last):
  File "tmpBug.py", line 9, in <module>
    jax.jit(do_stuff)(10)
  File "/usr/local/anaconda3/envs/jax/lib/python3.8/site-packages/jax/api.py", line 155, in f_jitted
    out = xla.xla_call(flat_fun, *args_flat, device=device, backend=backend,
  File "/usr/local/anaconda3/envs/jax/lib/python3.8/site-packages/jax/core.py", line 1028, in _call_bind
    outs = primitive.impl(f, *args, **params)
  File "/usr/local/anaconda3/envs/jax/lib/python3.8/site-packages/jax/interpreters/xla.py", line 524, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, name, *map(arg_spec, args))
  File "/usr/local/anaconda3/envs/jax/lib/python3.8/site-packages/jax/linear_util.py", line 221, in memoized_fun
    ans = call(fun, *args)
  File "/usr/local/anaconda3/envs/jax/lib/python3.8/site-packages/jax/interpreters/xla.py", line 540, in _xla_callable
    jaxpr, pvals, consts = pe.trace_to_jaxpr(
  File "/usr/local/anaconda3/envs/jax/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 444, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/usr/local/anaconda3/envs/jax/lib/python3.8/site-packages/jax/linear_util.py", line 150, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "tmpBug.py", line 7, in do_stuff
    jax.lax.scan(f,[1], xs=None, length=length)
  File "/usr/local/anaconda3/envs/jax/lib/python3.8/site-packages/jax/lax/lax_control_flow.py", line 1029, in scan
    length = int(length)
  File "/usr/local/anaconda3/envs/jax/lib/python3.8/site-packages/jax/core.py", line 441, in __int__
    def __int__(self): return self.aval._int(self)
  File "/usr/local/anaconda3/envs/jax/lib/python3.8/site-packages/jax/core.py", line 758, in error
    raise_concretization_error(arg, fname_context)
  File "/usr/local/anaconda3/envs/jax/lib/python3.8/site-packages/jax/core.py", line 749, in raise_concretization_error
    raise ConcretizationTypeError(msg)
jax.core.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected (in `int` Try using `x.astype(int)` instead.).
Use transformation parameters such as `static_argnums` for `jit` to avoid tracing input values.
See `https://jax.readthedocs.io/en/latest/faq.html#abstract-tracer-value-encountered-where-concrete-value-is-expected-error`.
Encountered value: Traced<ShapedArray(int32[], weak_type=True):JaxprTrace(level=-1/1)>
```

I guess the hint `Try using x.astype(int) instead` points out a suited fix?

**Comment by mattjj** [comment]
Thanks for the question!

Actually, this won't work with `jax.jit` because the shape of the output depends on the value of `length`, which isn't allowed.

I think we can improve the error message here, and the FAQ and/or the sharp bits notebook it links to.

**Comment by markusschmitt** [comment]
Right, I did not think about that. That makes sense. Thanks!

**Comment by selamw1** [comment]
Hi @mattjj 

I believe this issue can be considered fixed. The error message now provides much better information, which is in line with your suggestion for improvement.

```Python
import jax

def do_stuff(length):
    def f(carry,x):
        return carry, [None]

    jax.lax.scan(f,[1], xs=None, length=length)

jax.jit(do_stuff)(10)

```
Output:
```
ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: traced array with shape int32[].
The problem arose with the `int` function. If trying to convert the data type of a value, try using `x.astype(int)` or `jnp.array(x, int)` instead.
The error occurred while tracing the function do_stuff at <ipython-input-26-083c7485a775>:3 for jit. This concrete value was not available in Python because it depends on the value of the argument length.

See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError
```
