### ISSUE TITLE
Assertion when using id_print

### ISSUE THREAD

**Issue by NeilGirdhar** [google/jax#3863]
Sorry that I wasn't able to create a minimum working example, but here's the traceback:
```
Traceback (most recent call last):
  File "demos/encoding.py", line 95, in <module>
    encoding_demo()
  File "demos/encoding.py", line 80, in encoding_demo
    training_trajectory = problem.train()
  File "/home/neil/.pyenv/versions/3.8.2/lib/python3.8/site-packages/cmm/problem/problem.py", line 31, in train
    trajectory, self.model_parameters, self.iterated_function = train_model(
  File "/home/neil/.pyenv/versions/3.8.2/lib/python3.8/site-packages/cmm/model/inference.py", line 76, in train_model
    augmented, trajectory = method(model_meta_parameters,
  File "/home/neil/.pyenv/versions/3.8.2/lib/python3.8/site-packages/jax/api.py", line 169, in f_jitted
    out = xla.xla_call(flat_fun, *args_flat, device=device, backend=backend,
  File "/home/neil/.pyenv/versions/3.8.2/lib/python3.8/site-packages/jax/core.py", line 1103, in call_bind
    outs = primitive.impl(fun, *args, **params)
  File "/home/neil/.pyenv/versions/3.8.2/lib/python3.8/site-packages/jax/interpreters/xla.py", line 532, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, name, donated_invars,
  File "/home/neil/.pyenv/versions/3.8.2/lib/python3.8/site-packages/jax/linear_util.py", line 221, in memoized_fun
    ans = call(fun, *args)
  File "/home/neil/.pyenv/versions/3.8.2/lib/python3.8/site-packages/jax/interpreters/xla.py", line 641, in _xla_callable
    out_nodes = jaxpr_subcomp(
  File "/home/neil/.pyenv/versions/3.8.2/lib/python3.8/site-packages/jax/interpreters/xla.py", line 410, in jaxpr_subcomp
    ans = rule(c, axis_env, extend_name_stack(name_stack, eqn.primitive.name),
  File "/home/neil/.pyenv/versions/3.8.2/lib/python3.8/site-packages/jax/interpreters/xla.py", line 912, in f
    jaxpr, _, consts = pe.trace_to_jaxpr(
  File "/home/neil/.pyenv/versions/3.8.2/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 429, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/home/neil/.pyenv/versions/3.8.2/lib/python3.8/site-packages/jax/linear_util.py", line 150, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/neil/.pyenv/versions/3.8.2/lib/python3.8/site-packages/jax/lax/lax_control_flow.py", line 1319, in _scan_impl
    return _scan_impl_loop(
  File "/home/neil/.pyenv/versions/3.8.2/lib/python3.8/site-packages/jax/lax/lax_control_flow.py", line 1280, in _scan_impl_loop
    _, *outs = while_loop(cond_fun, body_fun, init_val)
  File "/home/neil/.pyenv/versions/3.8.2/lib/python3.8/site-packages/jax/lax/lax_control_flow.py", line 277, in while_loop
    body_jaxpr, body_consts, body_tree = _initial_style_jaxpr(body_fun, in_tree, init_avals)
  File "/home/neil/.pyenv/versions/3.8.2/lib/python3.8/site-packages/jax/lax/lax_control_flow.py", line 72, in _initial_style_jaxpr
    jaxpr, out_pvals, consts, out_tree = _initial_style_untyped_jaxpr(
  File "/home/neil/.pyenv/versions/3.8.2/lib/python3.8/site-packages/jax/lax/lax_control_flow.py", line 66, in _initial_style_untyped_jaxpr
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr(
  File "/home/neil/.pyenv/versions/3.8.2/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 429, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/home/neil/.pyenv/versions/3.8.2/lib/python3.8/site-packages/jax/linear_util.py", line 150, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/neil/.pyenv/versions/3.8.2/lib/python3.8/site-packages/jax/lax/lax_control_flow.py", line 1270, in body_fun
    out_flat = f_impl(*consts, *carry, *x)
  File "/home/neil/.pyenv/versions/3.8.2/lib/python3.8/site-packages/jax/core.py", line 142, in jaxpr_as_fun
    return eval_jaxpr(typed_jaxpr.jaxpr, typed_jaxpr.literals, *args)
  File "/home/neil/.pyenv/versions/3.8.2/lib/python3.8/site-packages/jax/core.py", line 346, in eval_jaxpr
    ans = eqn.primitive.bind(*(subfuns + in_vals), **params)
  File "/home/neil/.pyenv/versions/3.8.2/lib/python3.8/site-packages/jax/core.py", line 1106, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/home/neil/.pyenv/versions/3.8.2/lib/python3.8/site-packages/jax/core.py", line 1115, in process
    return trace.process_call(self, fun, tracers, params)
  File "/home/neil/.pyenv/versions/3.8.2/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 232, in process_call
    new_params = update_params(new_params, [not t.pval.is_known() for t in tracers])
  File "/home/neil/.pyenv/versions/3.8.2/lib/python3.8/site-packages/jax/interpreters/xla.py", line 813, in _xla_call_partial_eval_update_params
    donated_invars = [d for d, uk in zip(donated_invars, in_unknowns) if uk]
  File "/home/neil/.pyenv/versions/3.8.2/lib/python3.8/site-packages/jax/util.py", line 26, in safe_zip
    assert len(arg) == n, 'length mismatch: {}'.format(list(map(len, args)))
AssertionError: length mismatch: [18, 19]
```
If I have time this week, I'll get a MWE.  Hope this helps in the mean time.

@gnecula

**Comment by mattjj** [comment]
Thanks for catching this! The traceback is something, and George is wizardly enough that he might be able to go just on that, but any kind of repro is often helpful, even if not minimal. Just priming you with that in case you come up with something :)

**Comment by gnecula** [comment]
I cannot understand what is happening here and especially how is this related to `id_print`. The stack trace suggests that this may be an issue with handling of argument donation in a scan. Have you tried the example without `id_print`? 

We want to fix this bug, but I think that we need some way to reproduce it.

**Comment by NeilGirdhar** [comment]
@gnecula Yes, without the `id_print` call, it runs fine.  You're right there are scans involved.  The `id_print` is actually called from a `while` inside a `scan`.

I will try to get you a minimum working example.  I tried to guess one and build it constructively, but I couldn't find it.  My code is around 2400 lines, so I will have to delete a hundred lines at a time to produce a MWE.  I want to help you debug this; I just need to find the time.

On another note, thank you very much for `id_print`, it is a great debugging tool since it allows you to get debug information without disabling the JIT!

**Comment by gnecula** [comment]
If you can point me to a way to run the code, I can try to work even if the repro is not minimal.

**Comment by NeilGirdhar** [comment]
@gnecula Sorry for the late reply.  I'm not completely comfortable sharing my entire codebase yet, but I'm going to eventually get you a minimal repro as soon as I have a bit more time.

**Comment by gnecula** [comment]
I closed this issue because I think it is fixed, please verify and reopen if necessary. Thanks for your patience!

**Comment by NeilGirdhar** [comment]
@gnecula Thanks a lot for the quick fix without much to go on!!
