### ISSUE TITLE
lax.population_count does not support boolean dtype

### ISSUE THREAD

**Issue by SIben** [google/jax#3886]
Even though the use case is limited (`population_count(x) == x` if `x`'s dtype is `jax.numpy.bool_`), `lax.population_count_p` is defined as `population_count_p = standard_unop(_bool_or_int, 'population_count')`. However, this is what happens if `lax.population_count` is called with an argument with dtype `jax.numpy.bool_`:

```python
>>> lax.population_count(np.array([True, False], dtype=np.bool_))
Traceback (most recent call last):
  File "/jax/jax/interpreters/xla.py", line 311, in primitive_computation
    return c.build()
RuntimeError: Invalid argument: Expected an integral element type in argument to PopulationCount operation; got PRED.: 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/jax/jax/lax/lax.py", line 296, in population_count
    return population_count_p.bind(x)
  File "/jax/jax/core.py", line 275, in bind
    return self.impl(*args, **kwargs)
  File "/jax/jax/interpreters/xla.py", line 224, in apply_primitive
    compiled_fun = xla_primitive_callable(prim, *unsafe_map(arg_spec, args), **params)
  File "/jax/jax/interpreters/xla.py", line 257, in xla_primitive_callable
    built_c = primitive_computation(prim, AxisEnv(nreps), backend, tuple_args,
  File "/jax/jax/interpreters/xla.py", line 316, in primitive_computation
    raise RuntimeError(msg) from e
RuntimeError: Invalid argument: Expected an integral element type in argument to PopulationCount operation; got PRED.: 
This is a bug in JAX's shape-checking rules; please report it!
https://github.com/google/jax/issues
```

I think the simplest (and probably best) way to fix this is to remove booleans from the list of allowed types.

**Comment by mattjj** [comment]
Good call! Either we could remove it from the allowed types, or cast to integer internally. I lean the same way you do, that removing the purported support for booleans is probably best.
