### ISSUE TITLE
Question about install GPU version JAX

### ISSUE THREAD

**Issue by ruoxia-c** [google/jax#3992]
Hi,

I'm trying to install GPU version JAX inside a Ubuntu virtual machine contains cuda. However, when I trying to build from source and run `python build/build.py --enable_cuda`, I got this error: 

```
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 56 bytes for AllocateHeap
# An error report file with more information is saved as:
# /home/ruoxia/try/jax/hs_err_pid17816.log
Traceback (most recent call last):
  File "build/build.py", line 382, in <module>
    main()
  File "build/build.py", line 335, in main
    check_bazel_version(bazel_path, min_version="2.0.0", max_version=None)
  File "build/build.py", line 157, in check_bazel_version
    version_output = shell([bazel_path, "--bazelrc=/dev/null", "version"])
  File "build/build.py", line 47, in shell
    output = subprocess.check_output(cmd)
  File "/opt/miniconda3/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/opt/miniconda3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./bazel-2.0.0-linux-x86_64', '--bazelrc=/dev/null', 'version']' returned non-zero exit status 37.
```

Then I tried to use pip to directly install Cuda version JAX. But when I trying to test the JAX package using `python tests/lax_numpy_test.py --num_generated_cases=5`, I got error messages as below: 

```
Traceback (most recent call last):
  File "/home/ruoxia/.local/lib/python3.7/site-packages/absl/testing/parameterized.py", line 263, in bound_param_test
    test_method(self, **testcase_params)
  File "tests/lax_numpy_test.py", line 1184, in testPiecewise
    self._CheckAgainstNumpy(np_fun, jnp_fun, args_maker, check_dtypes=True)
  File "/home/ruoxia/.local/lib/python3.7/site-packages/jax/test_util.py", line 878, in _CheckAgainstNumpy
    lax_ans = lax_op(*args)
  File "/home/ruoxia/.local/lib/python3.7/site-packages/jax/numpy/lax_numpy.py", line 4367, in wrapped
    raise NotImplementedError(msg.format(fun))
NotImplementedError: Numpy function <function piecewise at 0x2ad4da5b9cb0> not yet implemented

----------------------------------------------------------------------
Ran 1367 tests in 73.511s

FAILED (errors=15, skipped=9)
```
I'm not sure if how to solve this problem, any suggestion will be very great.

**Comment by ruoxia-c** [comment]
I solve this problem by myself. I'll close this issue.
