### ISSUE TITLE
RuntimeError on GCP TPU

### ISSUE THREAD

**Issue by JaySunnn** [google/jax#4020]
I tried to run the example code in [README](https://github.com/google/jax/blob/master/cloud_tpu_colabs/README.md#running-jax-on-a-cloud-tpu-from-a-gce-vm) to use jax on TPU from a GCE VM, but I got RuntimeError.

```
2020-08-11 08:26:26.301652: E external/org_tensorflow/tensorflow/compiler/xla/python/tpu_driver/grpc_tpu_driver.cc:1068] Failed to open the gRPC driver: 12: :
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sj2660089/.local/lib/python3.7/site-packages/jax/random.py", line 85, in PRNGKey
    k1 = convert(np.bitwise_and(np.right_shift(seed, 32), 0xFFFFFFFF))
  File "/home/sj2660089/.local/lib/python3.7/site-packages/jax/random.py", line 81, in <lambda>
    convert = lambda k: lax.reshape(lax.convert_element_type(k, np.uint32), [1])
  File "/home/sj2660089/.local/lib/python3.7/site-packages/jax/lax/lax.py", line 397, in convert_element_type
    operand, new_dtype=new_dtype, old_dtype=old_dtype)
  File "/home/sj2660089/.local/lib/python3.7/site-packages/jax/core.py", line 276, in bind
    return self.impl(*args, **kwargs)
  File "/home/sj2660089/.local/lib/python3.7/site-packages/jax/interpreters/xla.py", line 224, in apply_primitive
    compiled_fun = xla_primitive_callable(prim, *unsafe_map(arg_spec, args), **params)
  File "/home/sj2660089/.local/lib/python3.7/site-packages/jax/interpreters/xla.py", line 236, in xla_primitive_callable
    backend = xb.get_device_backend(device)
  File "/home/sj2660089/.local/lib/python3.7/site-packages/jax/lib/xla_bridge.py", line 176, in get_device_backend
    return get_backend(platform)
  File "/home/sj2660089/.local/lib/python3.7/site-packages/jax/lib/xla_bridge.py", line 170, in get_backend
    return backend(platform)
  File "/home/sj2660089/.local/lib/python3.7/site-packages/jax/lib/xla_bridge.py", line 148, in _get_tpu_driver_backend
    _tpu_backend = tpu_client.TpuBackend.create(worker=backend_target)
  File "/home/sj2660089/.local/lib/python3.7/site-packages/jaxlib/tpu_client.py", line 59, in create
    return _tpu_client.TpuClient.Get(worker)
RuntimeError: Unimplemented: Failed to connect to remote server at address: grpc://10.240.1.2:8470. Error from gRPC: . Details:
```

Any idea why this happens?

**Comment by mattjj** [comment]
@skye can you take a look at this one?

**Comment by skye** [comment]
Can you verify that you have a running Cloud TPU VM at 10.240.1.2 and that you can ping it from the GCE VM?

cc @henrytansetiawan @jekbradbury, who may have more debugging ideas...

**Comment by JaySunnn** [comment]
I'm pretty sure that a Cloud TPU VM is running, because when I use `resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='tpu-test')`, it gives `2020-08-12 01:23:34.424424: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job worker -> {0 -> 10.37.10.226:8470}`. The change of ip is because I delete the TPU and create a new one, hope that wouldn't be a problem.

But I can't ping the TPU from GCE VM, and can't use jax to run on it either.

**Comment by jekbradbury** [comment]
If you can communicate with a Cloud TPU VM using TensorFlow, then I think that means it's exposing a TF gRPC server. JAX needs a tpu_driver gRPC server instead (`--version=tpu_driver_nightly`), and I thought the two were currently mutually exclusive?

**Comment by JaySunnn** [comment]
Now it works, thank you.

**Comment by mattjj** [comment]
@jekbradbury @skye you are the greatest!
