### ISSUE TITLE
Error with doubly-nested loop and custom VJP

### ISSUE THREAD

**Issue by C-J-Cundy** [google/jax#4114]
Running the following code consisting of a doubly-nested loop with a custom-defined VJP inside causes an error: 
``` 
import jax.numpy as np
from jax.experimental import loops
from jax import grad
import jax


@jax.custom_vjp
def f(x):
    return np.sin(x)


def f_fwd(x):
    return f(x), (np.cos(x),)


def f_bwd(res, g):
    (cos_x,) = res
    return (cos_x * g,)


f.defvjp(f_fwd, f_bwd)


def test_loss(x):
    # return x # This works fine
    return f(x)  # This doesn't work


def leapfrog(q):
    with loops.Scope() as s:
        s.q = q
        for i in s.range(10):
            tmp_1 = grad(test_loss)(s.q)
            s.q += tmp_1
    return s.q


def hmc(x):
    with loops.Scope() as s:
        s.q_new = 0.0
        for idx in s.range(10):
            s.q_new = leapfrog(s.q_new)
    return s.q_new


samples = hmc(1.0)
```

The error I get is 

```
Traceback (most recent call last):
  File "test.py", line 46, in <module>
    samples = hmc(1.0)
  File "test.py", line 42, in hmc
    s.q_new = leapfrog(s.q_new)
  File "test.py", line 33, in leapfrog
    tmp_1 = grad(test_loss)(s.q)
  File "/atlas/u/cundy/conda_envs/jax/lib/python3.7/site-packages/jax/api.py", line 429, in grad_f
    _, g = value_and_grad_f(*args, **kwargs)
  File "/atlas/u/cundy/conda_envs/jax/lib/python3.7/site-packages/jax/api.py", line 487, in value_and_grad_f
    ans, vjp_py = _vjp(f_partial, *dyn_args)
  File "/atlas/u/cundy/conda_envs/jax/lib/python3.7/site-packages/jax/api.py", line 1516, in _vjp
    out_primal, out_vjp = ad.vjp(flat_fun, primals_flat)
  File "/atlas/u/cundy/conda_envs/jax/lib/python3.7/site-packages/jax/interpreters/ad.py", line 110, in vjp
    out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
  File "/atlas/u/cundy/conda_envs/jax/lib/python3.7/site-packages/jax/interpreters/ad.py", line 97, in linearize
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr(jvpfun_flat, in_pvals)
  File "/atlas/u/cundy/conda_envs/jax/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 423, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/atlas/u/cundy/conda_envs/jax/lib/python3.7/site-packages/jax/linear_util.py", line 150, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "test.py", line 26, in test_loss
    return f(x)  # This doesn't work
  File "/atlas/u/cundy/conda_envs/jax/lib/python3.7/site-packages/jax/custom_derivatives.py", line 478, in __call__
    *args_flat, out_trees=out_trees)
  File "/atlas/u/cundy/conda_envs/jax/lib/python3.7/site-packages/jax/custom_derivatives.py", line 525, in bind
    out_trees=out_trees)
  File "/atlas/u/cundy/conda_envs/jax/lib/python3.7/site-packages/jax/interpreters/ad.py", line 306, in process_custom_vjp_call
    res_and_primals_out = fwd.call_wrapped(*map(core.full_lower, primals_in))
  File "/atlas/u/cundy/conda_envs/jax/lib/python3.7/site-packages/jax/linear_util.py", line 150, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "test.py", line 13, in f_fwd
    return f(x), (np.cos(x),)
  File "/atlas/u/cundy/conda_envs/jax/lib/python3.7/site-packages/jax/custom_derivatives.py", line 478, in __call__
    *args_flat, out_trees=out_trees)
  File "/atlas/u/cundy/conda_envs/jax/lib/python3.7/site-packages/jax/custom_derivatives.py", line 525, in bind
    out_trees=out_trees)
  File "/atlas/u/cundy/conda_envs/jax/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 296, in process_custom_vjp_call
    assert self.master.trace_type is StagingJaxprTrace
AssertionError
```

As you can guess by the function names, this came up when I tried to run my adaptation of [Hamiltonian Monte-Carlo](https://github.com/C-J-Cundy/hamiltonian-jax) on a probability density which uses `linalg.slogdet`, which has uses a custom VJP.

**Comment by mattjj** [comment]
Thanks for the clear repro!

As with at least a dozen or two other bugs on our issue tracker, this problem goes away if you switch on "omnistaging" (see #3370), which will soon be on by default. Concretely, if you add this to the top of your file, it no longer fails:

```python
from jax.config import config
config.enable_omnistaging()
```

Does that work for you?

**Comment by mattjj** [comment]
By the way, #4038 will switch omnistaging on by default. The only blocker (for the last couple months actually...) has been fixing up some google-internal downstream monorepo code so as to be compatible.

**Comment by C-J-Cundy** [comment]
Thanks for the reply!
Turning on omnistaging does indeed solve this bug due to the custom VJP, but I now have a new bug in the same setting that I'm struggling to fix. I'm not sure if it's related to turning the omnistaging on.

The likelihood I'm interested in for HMC has a term involving  a log determinant, as well as a term involving the trace of a matrix exponential. Based on issue #3447 I made a variant of the expm function with a vjp for taking gradients of the likelihood. 

However when I run the HMC algorithm with this matrix exponential on the GPU, jax either hangs or takes a very long time to compile. It's hard to tell since I've never seen the GPU version finish. If I force jax to jit on the cpu then the HMC algorithm finishes in a few seconds.

It seems like there is some sort of GPU-specific XLA weirdness going on, but I'm at a loss for how to debug this. 
The full code:

```
import jax.numpy as np
import jax
from jax.experimental import loops
from jax import value_and_grad, ops, jit, partial, api
from jax.config import config
import jax.random as rnd
import time
from jax.scipy.linalg import _expm, _calc_P_Q, _solve_P_Q, _squaring, expm_frechet, _T

config.enable_omnistaging()


# Define VJP-compatible matrix exponential
# -----
def expm(A, *, upper_triangular=False):
    return _expm(A, upper_triangular)


@partial(api.custom_vjp, nondiff_argnums=(1,))
def _expm(A, upper_triangular):
    P, Q, n_squarings = _calc_P_Q(A)
    R = _solve_P_Q(P, Q, upper_triangular)
    R = _squaring(R, n_squarings)
    return R


def f_fwd(A, upper_triangular):
    return expm(A), A


def f_bwd(upper_triangular, matrix, g):
    return (expm_frechet(_T(matrix), g, compute_expm=False),)

_expm.defvjp(f_fwd, f_bwd)    
# -----

def to_W(w_params):
    """Turns a (2 x (2-1)) vector into a 2 x 2 matrix with zero diagonal."""
    out = np.zeros((2, 2))
    out = ops.index_update(out, np.triu_indices(2, 1), w_params[: 2 // 2])
    out = ops.index_update(out, np.tril_indices(2, -1), w_params[2 // 2 :])
    return out


def potential(x):
    W = to_W(x)
    # W = np.eye(2) * x[0] # Seems like the indexing is important, since this works OK
    # return np.linalg.slogdet(W * W)[1] # Likewise the matrix exponential is important since this works
    return np.trace(expm(W * W))


def leapfrog(q, p, path_len):
    step_size = 1.0
    num_steps = np.round(path_len / step_size)
    with loops.Scope() as s:
        s.q = q
        s.V, s.dVdq = value_and_grad(potential)(s.q)
        s.p = p - step_size * s.dVdq / 2
        s.idx = 1
        for i in s.while_range(lambda: s.idx < num_steps):
            s.q = s.q + step_size * s.p  # whole step
            s.V, s.dVdq = value_and_grad(potential)(s.q)
            s.p -= step_size * s.dVdq  # whole step
            s.idx += 1
    s.q += step_size * s.p  # whole step
    s.V, s.dVdq = value_and_grad(potential)(s.q)
    s.p -= step_size * s.dVdq / 2  # half step
    return s.q


def hamiltonian_monte_carlo(initial_position):
    rnd_key = rnd.PRNGKey(0)
    initial_position = np.array(initial_position)
    n_samples = 2
    # size = (n_samples,) + initial_position.shape[:1]
    size = (n_samples, 2)
    momentum_draws = rnd.normal(rnd_key, shape=size)
    with loops.Scope() as s:
        s.q_new = np.zeros_like(initial_position)
        s.samples = np.ones(size)
        for idx in s.range(size[0]):
            s.q_new = leapfrog(
                s.q_new, momentum_draws[idx], path_len=2 * momentum_draws[idx][0],
            )
            s.samples = ops.index_update(s.samples, ops.index[idx], s.q_new)
    return np.array(s.samples)


print("Starting Sampling...")
t0 = time.time()
samples = jit(hamiltonian_monte_carlo, backend="cpu")(
    rnd.normal(rnd.PRNGKey(0), shape=(2,)) * 3
)
# print(samples)
print(f"Finished Sampling, took {time.time() - t0}s with cpu backend")

print("Starting Sampling...")
t0 = time.time()
samples = jit(hamiltonian_monte_carlo, backend="gpu")(
    rnd.normal(rnd.PRNGKey(0), shape=(2,)) * 3
)
print(f"Finished Sampling, took {time.time() - t0}s with gpu backend")
```

I also put the code in a colab [here](https://colab.research.google.com/drive/1R_tGp9O04GpJWdVTZl4PzRB5RMmgxFnc?usp=sharing), just to check it's not something wrong with my machine

**Comment by mattjj** [comment]
Hrm, interesting...

To remove possible sources of complexity, you might want to try writing it without `jax.experimental.loops` (and just use `lax.fori_loop` instead).

Stalling forever with `n_samples = 2` certainly sounds like an issue, and XLA:GPU does seem a plausible culprit given that the CPU version finishes (so JAX can clearly finish tracing this program).

I'll try to make an HLO-only repro for the XLA:GPU team to look at.

**Comment by C-J-Cundy** [comment]
I had a further look, found two important things: 

- The conclusion I came to before about it not working with GPU but working on CPU seems to be wrong, just an artifact of the jax asynchronous dispatch. If I put `block_until_ready()` for the cpu version, it stalls just like the gpu version (or if I try to print out the results of the cpu version). 

- If I change the `experimental.loops` to a `lax.fori_loop` which is semantically the same, the function doesn't stall. So it seems like this issue is due to the loops. 

Semantically equivalent `fori_loop`:
```
def hamiltonian_monte_carlo_fori(initial_position):
    rnd_key = rnd.PRNGKey(0)
    initial_position = np.array(initial_position)
    n_samples = 2
    # size = (n_samples,) + initial_position.shape[:1]
    size = (n_samples, 2)
    momentum_draws = rnd.normal(rnd_key, shape=size)
    def fori_body(i, val):
        q, samples = val
        momentum = momentum_draws[i]
        q_new = leapfrog(q, momentum, 2 * momentum[0])
        samples = ops.index_update(samples, ops.index[i], q_new)
        return q, samples

    q_last, samples = lax.fori_loop(
        0, size[0], fori_body, (np.zeros_like(initial_position), np.ones(size))
    )
    return np.array(samples)    
```

**Comment by mattjj** [comment]
Thanks for following up on this! That's great new information.

Hm, maybe a good way to proceed is:
1. we open a new issue with the experimental.loops bug
2. we close this issue when we enable omnistaging by default

What do you think?

**Comment by C-J-Cundy** [comment]
Yep, sounds like the best way to handle this bug!

**Comment by C-J-Cundy** [comment]
Looking into it even more, the conclusions I came to above were not correct.

The 'equivalent' `fori_loop` wasn't actually equivalent after all, and swapping it out for the `experimental.loops` didn't actually change anything--both the experimental.loops and fori loop approach resulted in the function hanging. 

I've boiled the problem down to a much simpler repro: it seems that the issue arises simply from evaluating `jax.scipy.linalg.expm` inside a doubly-nested `lax.scan`/`while_loop`/`fori_loop`. The issue comes about even without looking at the gradient, so my custom vjp code wasn't the issue. 

Here is a minimal repro:

```import jax.numpy as np
import jax
from jax import lax, jit
from jax.config import config
import jax.random as rnd
import time

# config.enable_omnistaging()
print(f"Number of devices: {jax.device_count()}")
print("Device:", jax.devices()[0].device_kind)


def potential(x):
    W = np.array([[0.0, x[0]], [x[1], 0.0]])
    return np.trace(jax.scipy.linalg.expm(W * W))


def leapfrog(q):
    def scan_fun(q, xs):
        V = potential(q)
        q -= V
        return q, (q, V)

    _, (qs, V) = lax.scan(scan_fun, q, xs=None, length=3)

    return qs[-1]


def hamiltonian_monte_carlo_fori(initial_position):
    initial_position = np.array(initial_position)
    n_samples = 2

    def scan_fun(carry, xs):
        q = carry
        q_new = leapfrog(q)
        return q_new, q_new

    _, samples = lax.scan(scan_fun, initial_position, None, length=n_samples)

    return samples

t0 = time.time()

print("Starting Sampling")
t0 = time.time()
fori_samples = hamiltonian_monte_carlo_fori(
    rnd.normal(rnd.PRNGKey(0), shape=(2,)) * 3
).block_until_ready()

print(f"Finished Sampling, took {time.time() - t0}s")
```

I'm struggling to debug what's going on since the program never terminates. Do you have any tips for debugging/an inkling of what could be going on here?

**Comment by jekbradbury** [comment]
Sounds like the underlying issue here is captured in #4162. Closing unless that's a misinterpretation?
