### ISSUE TITLE
jit(grad(f))(x) returns NaN, but grad(f)(x) evaluates fine

### ISSUE THREAD

**Issue by langosco** [google/jax#4275]
I'm having an issue where `jit(grad(fn))(x)` evaluates to NaN, but `grad(fn)(x)` returns a real value, where `fn` is a neural network loss.

This only happens for particular sets of parameters, and I haven't been able to figure out a way to reproduce the bug without parametrizing a neural net, so I'm sharing the (small: [32, 32, 1]) set of parameters to reproduce the bug. [Here's the reproduction in a notebook](https://github.com/langosco/jax-NaN-error/blob/master/Weird%20NaN.ipynb) (loading the NN params from a json file). Sorry for not figuring out an easier repro!

I'm running jax version 0.1.76 and jaxlib version 0.1.55 on CPU.

**Comment by mattjj** [comment]
Thanks for the report!

Could you share the json file with the parameters as well?

**Comment by langosco** [comment]
Jup! It's in the same [repo](https://github.com/langosco/jax-NaN-error).

**Comment by mattjj** [comment]
Tangentially, when I ran this with `JAX_DEBUG_NANS=1`, I got a surprising internal error:

```python
$ env JAX_DEBUG_NANS=1 python issue4275.py
Invalid value encountered in the output of a jit function. Calling the de-optimized version.
Traceback (most recent call last):
  File "issue4275.py", line 52, in <module>
    g_jit = jit(grad(l2_norm))(params, samples)
jax.traceback_util.FilteredStackTrace: jax.linear_util.StoreException: Store occupied

The stack trace above excludes JAX-internal frames.
The following is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "issue4275.py", line 52, in <module>
    g_jit = jit(grad(l2_norm))(params, samples)
  File "/usr/local/google/home/mattjj/packages/jax/jax/traceback_util.py", line 136, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/google/home/mattjj/packages/jax/jax/api.py", line 214, in f_jitted
    donated_invars=donated_invars)
  File "/usr/local/google/home/mattjj/packages/jax/jax/core.py", line 1146, in bind
    return call_bind(self, fun, *args, **params)
  File "/usr/local/google/home/mattjj/packages/jax/jax/core.py", line 1135, in call_bind
    outs = primitive.impl(fun, *args, **params)
  File "/usr/local/google/home/mattjj/packages/jax/jax/interpreters/xla.py", line 536, in _xla_call_impl
    return fun.call_wrapped(*args)  # probably won't return
  File "/usr/local/google/home/mattjj/packages/jax/jax/linear_util.py", line 167, in call_wrapped
    out_store.store(side)
  File "/usr/local/google/home/mattjj/packages/jax/jax/linear_util.py", line 85, in store
    raise StoreException("Store occupied")
jax.linear_util.StoreException: Store occupied
```

Maybe this just means that Haiku isn't compatible with jax_debug_nans, or something.

**Comment by selamw1** [comment]
Hi @langosco 

While executing the notebook you shared on Colab (CPU backend) with the `jax_debug_nans` flag enabled:
```Python
from jax import config
config.update("jax_debug_nans", True) 
```
I got the following stack trace:
```
FloatingPointError: invalid value (nan) encountered in jit(l2_norm). Because jax_config.debug_nans.value and/or config.jax_debug_infs is set, the de-optimized function (i.e., the function as if the `jit` decorator were removed) was called in an attempt to get a more precise error message. However, the de-optimized function did not produce invalid values during its execution. This behavior can result from `jit` optimizations causing the invalid value to be produced. It may also arise from having nan/inf constants as outputs, like `jax.jit(lambda ...: jax.numpy.nan)(...)`. 

It may be possible to avoid the invalid value by removing the `jit` decorator, at the cost of losing optimizations. 

If you see this error, consider opening a bug report at https://github.com/google/jax.

```
Further investigation using `jax.debug.print` revealed that `NaN` values were produced in the backward pass of a gradient evaluation. The [runtime value debugging documentation](https://jax.readthedocs.io/en/latest/debugging/index.html) provides helpful tips for examining intermediate values in your computation. 

Here's a quick fix:
By default, JAX uses single-precision to improve performance. To use double-precision numbers, you can set the [`jax_enable_x64`](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#double-64bit-precision) configuration flag to `True` at startup. This forces JAX to use double-precision:
```Python
from jax import config
config.update("jax_enable_x64", True)
```

I've also attached a [gist](https://colab.research.google.com/gist/selamw1/a1934b2fa0d367edd2a14f7d2001e35d/-4275.ipynb#scrollTo=nCXT81xzBbhZ) for your reference.

NOTE: 
- Setting the environment variable `--xla_cpu_enable_fast_math=false `doesn't seem to have any effect on this issue.
- This issue only occurs on the CPU backend. The code runs normally on  GPUs and TPUs.
