### ISSUE TITLE
Error when creating test for new implementation

### ISSUE THREAD

**Issue by alexminnaar** [google/jax#4365]
Hello, I am trying to add an implementation for numpy's [histogramdd](https://numpy.org/doc/stable/reference/generated/numpy.histogramdd.html#numpy.histogramdd).  My implementation is currently in my fork [here](https://github.com/alexminnaar/jax/blob/6165163e2af91a458e04d4209f85a5c807cfbe74/jax/numpy/lax_numpy.py#L902).  I wanted to create a test for my histogramdd implementation but I am running into an error that I'm having a hard time understanding.

My test implementation is also in my fork [here](https://github.com/alexminnaar/jax/blob/6165163e2af91a458e04d4209f85a5c807cfbe74/tests/lax_numpy_test.py#L2305) which basically compares my implementations result of a test case with numpy's result.

The test case args are `np.array([[2,3,1], [4,6,2], [5,5,1]]), (5, 4, 3), None, None, None, None` and the result for my implementation is 
```
(DeviceArray([[[1., 0., 0.],
              [0., 0., 0.],
              [0., 0., 0.],
              [0., 0., 0.]],

             [[0., 0., 0.],
              [0., 0., 0.],
              [0., 0., 0.],
              [0., 0., 0.]],

             [[0., 0., 0.],
              [0., 0., 0.],
              [0., 0., 0.],
              [0., 0., 0.]],

             [[0., 0., 0.],
              [0., 0., 0.],
              [0., 0., 0.],
              [0., 0., 1.]],

             [[0., 0., 0.],
              [0., 0., 0.],
              [1., 0., 0.],
              [0., 0., 0.]]], dtype=float32), [DeviceArray([2. , 2.6, 3.2, 3.8, 4.4, 5. ], dtype=float32), DeviceArray([3.  , 3.75, 4.5 , 5.25, 6.  ], dtype=float32), DeviceArray([1.       , 1.3333333, 1.6666667, 2.       ], dtype=float32)])
```
and the result from numpy is 
```
(array([[[1., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 0., 0.],
        [0., 0., 0.]]]), [array([2. , 2.6, 3.2, 3.8, 4.4, 5. ]), array([3.  , 3.75, 4.5 , 5.25, 6.  ]), array([1.        , 1.33333333, 1.66666667, 2.        ])])
```
Which appear to match however when I run my test case I get the error

```
Traceback (most recent call last):
  File "tests/lax_numpy_test.py", line 4492, in <module>
    absltest.main(testLoader=jtu.JaxTestLoader())
  File "/home/alexminnaar/jax-venv/lib/python3.8/site-packages/absl/testing/absltest.py", line 1999, in main
    _run_in_app(run_tests, args, kwargs)
  File "/home/alexminnaar/jax-venv/lib/python3.8/site-packages/absl/testing/absltest.py", line 2116, in _run_in_app
    app.run(main=main_function)
  File "/home/alexminnaar/jax-venv/lib/python3.8/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/alexminnaar/jax-venv/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/alexminnaar/jax-venv/lib/python3.8/site-packages/absl/testing/absltest.py", line 2114, in main_function
    function(argv, args, kwargs)
  File "/home/alexminnaar/jax-venv/lib/python3.8/site-packages/absl/testing/absltest.py", line 2430, in run_tests
    result = _run_and_get_tests_result(
  File "/home/alexminnaar/jax-venv/lib/python3.8/site-packages/absl/testing/absltest.py", line 2401, in _run_and_get_tests_result
    test_program = unittest.TestProgram(*args, **kwargs)
  File "/usr/lib/python3.8/unittest/main.py", line 101, in __init__
    self.runTests()
  File "/usr/lib/python3.8/unittest/main.py", line 271, in runTests
    self.result = testRunner.run(self.test)
  File "/home/alexminnaar/jax-venv/lib/python3.8/site-packages/absl/testing/_pretty_print_reporter.py", line 87, in run
    return super(TextTestRunner, self).run(test)
  File "/usr/lib/python3.8/unittest/runner.py", line 176, in run
    test(result)
  File "/usr/lib/python3.8/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.8/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.8/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.8/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.8/unittest/case.py", line 736, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/alexminnaar/jax-venv/lib/python3.8/site-packages/absl/testing/parameterized.py", line 284, in bound_param_test
    return test_method(self, *testcase_params)
  File "tests/lax_numpy_test.py", line 2310, in testHistogramdd
    self._CompileAndCheck(jnp.histogramdd, args_maker)
  File "/home/alexminnaar/jax/jax/test_util.py", line 855, in _CompileAndCheck
    monitored_ans = cfun(*args)
  File "/home/alexminnaar/jax/jax/test_util.py", line 837, in wrapped_fun
    return fun(*args)
  File "/home/alexminnaar/jax/jax/numpy/lax_numpy.py", line 912, in histogramdd
    bin_edges = histogram_bin_edges(sample[:, i], bins[i], range, weights)
  File "/home/alexminnaar/jax/jax/numpy/lax_numpy.py", line 879, in histogram_bin_edges
    return linspace(range[0], range[1], bins + 1, dtype=dtype)
  File "/home/alexminnaar/jax/jax/numpy/lax_numpy.py", line 2528, in linspace
    if num < 0:
jax.traceback_util.FilteredStackTrace: jax.core.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected.

The problem arose with the `bool` function. 

While tracing the function wrapped_fun at /home/alexminnaar/jax/jax/test_util.py:835, this value became a tracer due to JAX operations on these lines:

  operation cy:int32[] = add b:int32[] cx:int32[]
    from line tests/lax_numpy_test.py:2310 (testHistogramdd)

  operation da:bool[] = lt cy:int32[] cz:int32[]
    from line tests/lax_numpy_test.py:2310 (testHistogramdd)

You can use transformation parameters such as `static_argnums` for `jit` to avoid tracing particular arguments of transformed functions.

See https://jax.readthedocs.io/en/latest/faq.html#abstract-tracer-value-encountered-where-concrete-value-is-expected-error for more information.

Encountered tracer value: Traced<ShapedArray(bool[])>with<DynamicJaxprTrace(level=0/1)>

The stack trace above excludes JAX-internal frames.
The following is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alexminnaar/jax-venv/lib/python3.8/site-packages/absl/testing/parameterized.py", line 284, in bound_param_test
    return test_method(self, *testcase_params)
  File "tests/lax_numpy_test.py", line 2310, in testHistogramdd
    self._CompileAndCheck(jnp.histogramdd, args_maker)
  File "/home/alexminnaar/jax/jax/test_util.py", line 855, in _CompileAndCheck
    monitored_ans = cfun(*args)
  File "/home/alexminnaar/jax/jax/traceback_util.py", line 137, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/alexminnaar/jax/jax/api.py", line 208, in f_jitted
    out = xla.xla_call(
  File "/home/alexminnaar/jax/jax/core.py", line 1144, in bind
    return call_bind(self, fun, *args, **params)
  File "/home/alexminnaar/jax/jax/core.py", line 1135, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/home/alexminnaar/jax/jax/core.py", line 1147, in process
    return trace.process_call(self, fun, tracers, params)
  File "/home/alexminnaar/jax/jax/core.py", line 577, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/alexminnaar/jax/jax/interpreters/xla.py", line 529, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, name, donated_invars,
  File "/home/alexminnaar/jax/jax/linear_util.py", line 234, in memoized_fun
    ans = call(fun, *args)
  File "/home/alexminnaar/jax/jax/interpreters/xla.py", line 595, in _xla_callable
    jaxpr, out_avals, consts = pe.trace_to_jaxpr_final(fun, abstract_args)
  File "/home/alexminnaar/jax/jax/interpreters/partial_eval.py", line 1023, in trace_to_jaxpr_final
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, main, in_avals)
  File "/home/alexminnaar/jax/jax/interpreters/partial_eval.py", line 1004, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers)
  File "/home/alexminnaar/jax/jax/linear_util.py", line 151, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/alexminnaar/jax/jax/test_util.py", line 837, in wrapped_fun
    return fun(*args)
  File "/home/alexminnaar/jax/jax/numpy/lax_numpy.py", line 912, in histogramdd
    bin_edges = histogram_bin_edges(sample[:, i], bins[i], range, weights)
  File "/home/alexminnaar/jax/jax/numpy/lax_numpy.py", line 879, in histogram_bin_edges
    return linspace(range[0], range[1], bins + 1, dtype=dtype)
  File "/home/alexminnaar/jax/jax/numpy/lax_numpy.py", line 2528, in linspace
    if num < 0:
  File "/home/alexminnaar/jax/jax/core.py", line 507, in __bool__
    def __bool__(self): return self.aval._bool(self)
  File "/home/alexminnaar/jax/jax/core.py", line 864, in error
    raise_concretization_error(arg, fname_context)
  File "/home/alexminnaar/jax/jax/core.py", line 853, in raise_concretization_error
    raise ConcretizationTypeError(msg)
jax.core.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected.

The problem arose with the `bool` function. 

While tracing the function wrapped_fun at /home/alexminnaar/jax/jax/test_util.py:835, this value became a tracer due to JAX operations on these lines:

  operation cy:int32[] = add b:int32[] cx:int32[]
    from line tests/lax_numpy_test.py:2310 (testHistogramdd)

  operation da:bool[] = lt cy:int32[] cz:int32[]
    from line tests/lax_numpy_test.py:2310 (testHistogramdd)

You can use transformation parameters such as `static_argnums` for `jit` to avoid tracing particular arguments of transformed functions.

See https://jax.readthedocs.io/en/latest/faq.html#abstract-tracer-value-encountered-where-concrete-value-is-expected-error for more information.

Encountered tracer value: Traced<ShapedArray(bool[])>with<DynamicJaxprTrace(level=0/1)>

----------------------------------------------------------------------
Ran 1 test in 0.641s

FAILED (errors=1)
```
I can't quite understand the error.  Am I missing something in my test implementation?

**Comment by jakevdp** [comment]
In JAX's JIT compilation model, the shapes of arrays cannot be dependent on data values, unless those values are static. In your function, the `bins` value determines the shape of the output, so it must be a static parameter in the computation.

There are various ways to make certain a parameter is static, but in the test suite, this is generally done by leaving them out of `args_maker` and passing them to the function in question within a closure. You can see an example of that here, in the test for the 1D histogram: https://github.com/google/jax/blob/e0af77fbca88ec882ef33c18926f8382f7178aed/tests/lax_numpy_test.py#L2286-L2300

Notice that `bins` and `density` are treated as static arguments, i.e. they're not parameters passed to the jitted function. If `bins` were passed to the function by `args_maker` in this test, it would result in the same error you're seeing in your test.

Does that make sense?

**Comment by alexminnaar** [comment]
Thanks @jakevdp I made that change and it looks like it fixed it.  I am curious though, in the testHistogram example you posted, doesn't the `shape` value also determine the shape of the output? Why does that not produce the error when put in `args_maker`?

**Comment by jakevdp** [comment]
Yes, it's fine for the **shape** of input arrays to determine the **shape** of outputs within JIT-compiled computations. Where problems arise is when the **values** within input arrays determine the shape of outputs.

There's a bit of relevant discussion of this here: https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#python-control-flow-+-JIT

**Comment by alexminnaar** [comment]
Interesting.  Thanks again @jakevdp
