### ISSUE TITLE
Question: Cloud TPU and JAX under python3

### ISSUE THREAD

**Issue by mganahl** [google/jax#4408]
Hi! Trying to set up a VM + cloud TPU on GCP and everything works great using python2. In python3 though I get 
`RuntimeError: Deadline exceeded: Failed to connect to remote server at address: grpc://10.240.1.2:8470. Error from gRPC: Deadline Exceeded`. Is Cloud TPU support currently restrictes to python2?
thanks!

**Comment by mattjj** [comment]
Hm, I don't think there should be a Python 2 restriction.

@jekbradbury or @skye wdyt?

**Comment by mganahl** [comment]
I think the problem may be the TPU driver. I was using `tpu_driver_nightly`. Are there any other software versions except that one I could use with JAX?

**Comment by mganahl** [comment]
Hi! the problem was indeed the TPU configuration. Switching from `'tpu_driver_nightly'` to `'tpu_driver0.1-dev20200320'` using `cloud_tpu_client` (https://cloud.google.com/tpu/docs/version-switching?hl=de) seems to fix the issue.
thanks!

**Comment by lucasliunju** [comment]
Hi I have the same problem when I try to connect jax with multi-host tpu.

My code is:
```
from jax.config import config
# The following is required to use TPU Driver as JAX's backend.
config.FLAGS.jax_xla_backend = "tpu_driver"
config.FLAGS.jax_backend_target = "grpc://[my tpu ip address]:8475"
```


And thr error is 

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/supercomputer_ai/vision_transformer/vit_jax/train.py", line 53, in <module>
    print(jax.local_devices())
  File "/home/supercomputer_ai/.local/lib/python3.7/site-packages/jax/lib/xla_bridge.py", line 255, in local_devices
    host_id = get_backend(backend).host_id()
  File "/home/supercomputer_ai/.local/lib/python3.7/site-packages/jax/lib/xla_bridge.py", line 178, in get_backend
    return backend(platform)
  File "/home/supercomputer_ai/.local/lib/python3.7/site-packages/jax/lib/xla_bridge.py", line 156, in _get_tpu_driver_backend
    _tpu_backend = tpu_client.TpuBackend.create(worker=backend_target)
  File "/home/supercomputer_ai/.local/lib/python3.7/site-packages/jaxlib/tpu_client.py", line 59, in create
    return _tpu_client.TpuClient.Get(worker)
RuntimeError: Not found: Unable to find driver in registry given worker: rpc://10.86.90.58:8470
```


I searched on google and don't  get useful suggestion. 

Thank you very much!

Yong

**Comment by jakevdp** [comment]
@lucasliunju - comments on closed issues are not a great way to get answers. Since you've already asked this question in a new thread in #6159, I think we should avoid discussing this issue here.
