### ISSUE TITLE
RuntimeError: Internal: libdevice not found at ./libdevice.10.bc

### ISSUE THREAD

**Issue by PostQuantum** [google/jax#4452]
I install GPU version JAX and I encounter the following error when I first run a program with the AD support of JAX.

The following is the error info.

```
2020-10-05 16:30:40.039587: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:70] Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice. This may result in compilation or runtime failures, if the program we try to run uses routines from libdevice.
2020-10-05 16:30:40.039604: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:71] Searched for CUDA in the following directories:
2020-10-05 16:30:40.039608: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   ./cuda_sdk_lib
2020-10-05 16:30:40.039611: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   /usr/local/cuda-10.1
2020-10-05 16:30:40.039613: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   .
2020-10-05 16:30:40.039616: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:76] You can choose the search directory by setting xla_gpu_cuda_data_dir in HloModule's DebugOptions.  For most apps, setting the environment variable XLA_FLAGS=--xla_gpu_cuda_data_dir=/path/to/cuda will work.
i: 0
2020-10-05 16:30:40.769544: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:320] libdevice is required by this HLO module but was not found at ./libdevice.10.bc
Traceback (most recent call last):
  File "adpath.py", line 252, in <module>
...........
  File "/home/tie/anaconda3/lib/python3.8/site-packages/jax/numpy/lax_numpy.py", line 347, in fn
    return lax_fn(x)
  File "/home/tie/anaconda3/lib/python3.8/site-packages/jax/lax/lax.py", line 285, in sqrt
    return sqrt_p.bind(x)
jax.traceback_util.FilteredStackTrace: RuntimeError: Internal: libdevice not found at ./libdevice.10.bc
The stack trace above excludes JAX-internal frames.
The following is the original exception that occurred, unmodified.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "adpath.py", line 252, in <module>
.......
  File "/home/tie/anaconda3/lib/python3.8/site-packages/jax/api.py", line 900, in jacfun
    y, jac = vmap(pushfwd, out_axes=(None, -1))(_std_basis(dyn_args))
  File "/home/tie/anaconda3/lib/python3.8/site-packages/jax/traceback_util.py", line 137, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/tie/anaconda3/lib/python3.8/site-packages/jax/api.py", line 1217, in batched_fun
    out_flat = batching.batch(flat_fun, args_flat, in_axes_flat,
  File "/home/tie/anaconda3/lib/python3.8/site-packages/jax/interpreters/batching.py", line 36, in batch
    return batched_fun.call_wrapped(*in_vals)
  File "/home/tie/anaconda3/lib/python3.8/site-packages/jax/linear_util.py", line 151, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/tie/anaconda3/lib/python3.8/site-packages/jax/api.py", line 1681, in _jvp
    out_primals, out_tangents = ad.jvp(flat_fun).call_wrapped(ps_flat, ts_flat)
  File "/home/tie/anaconda3/lib/python3.8/site-packages/jax/linear_util.py", line 151, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  ..........
  File "/home/tie/anaconda3/lib/python3.8/site-packages/jax/numpy/lax_numpy.py", line 347, in fn
    return lax_fn(x)
  File "/home/tie/anaconda3/lib/python3.8/site-packages/jax/lax/lax.py", line 285, in sqrt
    return sqrt_p.bind(x)
  File "/home/tie/anaconda3/lib/python3.8/site-packages/jax/core.py", line 266, in bind
    out = top_trace.process_primitive(self, tracers, params)
  File "/home/tie/anaconda3/lib/python3.8/site-packages/jax/core.py", line 574, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/tie/anaconda3/lib/python3.8/site-packages/jax/interpreters/xla.py", line 224, in apply_primitive
    compiled_fun = xla_primitive_callable(prim, *unsafe_map(arg_spec, args), **params)
  File "/home/tie/anaconda3/lib/python3.8/site-packages/jax/interpreters/xla.py", line 264, in xla_primitive_callable
    compiled = backend_compile(backend, built_c, options)
  File "/home/tie/anaconda3/lib/python3.8/site-packages/jax/interpreters/xla.py", line 325, in backend_compile
    return backend.compile(built_c, compile_options=options)
RuntimeError: Internal: libdevice not found at ./libdevice.10.bc
====================================================================================
```
Maybe I don't install the correct CUDA version. I don't know. Can anyone help me figure it out?

**Comment by skye** [comment]
Check out the instructions near the bottom of https://github.com/google/jax#pip-installation, starting with "Note that some GPU functionality expects the CUDA installation to be at `/usr/local/cuda-X.X`". Do any of the suggestions there help?

**Comment by PostQuantum** [comment]
I tried to create a symlink, 
sudo ln -s /path/to/cuda /usr/local/cuda-X.X

And it still give the above error info.

**Comment by PostQuantum** [comment]
sudo ln -s /usr/lib/cuda /usr/local/cuda-10.1

This actually solves my problem. Thanks very much @skye

**Comment by skye** [comment]
Thanks for letting us know!

**Comment by mvxxx** [comment]
If you are not able to `ln -s` your cuda (for example because public cluster permissions), you always can set `XLA_FLAGS=--xla_gpu_cuda_data_dir=/usr/lib/cuda` before each command you need to use cuda:
```bash
XLA_FLAGS=--xla_gpu_cuda_data_dir=/usr/lib/cuda python3 your_script_with_cuda.py
```

Thank you very much for that post.

**Comment by srihari-humbarwadi** [comment]
@mvxxx thanks, worked for tensorflow as well!

**Comment by pharringtonp19** [comment]
I have a lambdalabs machine, and when I try to local where cuda is, I get the following

`whereis -b cuda
cuda: /usr/include/cuda.h /usr/include/cuda /usr/local/cuda011.1
`
The last one shows up because I tried to follow some of the online instructions and made an error along the way. 

Given that this is where my cuda is, I am not sure how to proceed.

Any help would be appreciated

**Comment by martiningram** [comment]
In case it's helpful for anyone: I just struggled with this on my university's managed cluster. I set the XLA_FLAGS environment variable, but to no avail. I wasn't able to make the symlink to `/usr/local/cuda-11.1` suggested as I don't have admin rights. However, I noticed that JAX reported:

```
2021-05-28 14:08:11.947002: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:71] Searched for CUDA in the following directories:                                              
2021-05-28 14:08:11.947013: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   ./cuda_sdk_lib                                                                             
2021-05-28 14:08:11.947021: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   /usr/local/cuda-11.1                                                                       
2021-05-28 14:08:11.947028: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   . 
```

So I symlinked the CUDA directory to `./cuda_sdk_lib`, and this did the trick! Admittedly it's not the neatest solution, as I will have to make new symlinks whenever I change directories, but for me it's a workaround I can live with. Just posting in case anyone else finds it helpful!

**Comment by peteflorence** [comment]
How would one solve this on colab?

**Comment by sbrl** [comment]
Nope, doing `export XLA_FLAGS=--xla_gpu_cuda_data_dir=/path/to/cuda` does not work on Ubuntu 22.04 with CUDA 11.2 and Tensorflow 2.11.

Instead, one gets this error:

```
2022-12-02 21:02:18.029083: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:446 : INTERNAL: libdevice not found at ./libdevice.10.bc
Traceback (most recent call last):
....
  File "/home/sbrl/.local/lib/python3.10/site-packages/tensorflow/python/eager/execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InternalError: Graph execution error:
.....
    File "/home/sbrl/.local/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1216, in _distributed_apply_gradients_fn
      distribution.extended.update(
    File "/home/sbrl/.local/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1211, in apply_grad_to_update_var
      return self._update_step_xla(grad, var, id(self._var_key(var)))
Node: 'StatefulPartitionedCall_409'
libdevice not found at ./libdevice.10.bc
	 [[{{node StatefulPartitionedCall_409}}]] [Op:__inference_train_function_357445]

```

**Comment by hawkinsp** [comment]
@sbrl That's a TensorFlow issue, not a JAX one, so I suggest opening a bug on the TensorFlow github.

**Comment by miguelgargallo** [comment]
still stuck:

```
1

sudo ln -s /opt/cuda /usr/local/cuda

Epoch 1/200

2023-01-19 14:07:32.719434: W tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:326] libdevice is required by this HLO module but was not found at ./libdevice.10.bc
2023-01-19 14:07:32.719780: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:446 : INTERNAL: libdevice not found at ./libdevice.10.bc
2023-01-19 14:07:32.734790: W tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:326] libdevice is required by this HLO module but was not found at ./libdevice.10.bc
2023-01-19 14:07:32.735059: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:446 : INTERNAL: libdevice not found at ./libdevice.10.bc

---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
Cell In[131], line 2
      1 #training the model
----> 2 train = model.fit(x_train,y_train,epochs=200)

File ~/.local/lib/python3.10/site-packages/keras/utils/traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File ~/.local/lib/python3.10/site-packages/tensorflow/python/eager/execute.py:52, in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     50 try:
     51   ctx.ensure_initialized()
---> 52   tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     53                                       inputs, attrs, num_outputs)
     54 except core._NotOkStatusException as e:
     55   if name is not None:

InternalError: Graph execution error:

Detected at node 'StatefulPartitionedCall_5' defined at (most recent call last):
    File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/usr/lib/python3.10/site-packages/ipykernel_launcher.py", line 17, in <module>
      app.launch_new_instance()
    File "/usr/lib/python3.10/site-packages/traitlets/config/application.py", line 1041, in launch_instance
      app.start()
    File "/usr/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 724, in start
      self.io_loop.start()
    File "/usr/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 215, in start
      self.asyncio_loop.run_forever()
    File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
      self._run_once()
    File "/usr/lib/python3.10/asyncio/base_events.py", line 1906, in _run_once
      handle._run()
    File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
      self._context.run(self._callback, *self._args)
    File "/usr/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 512, in dispatch_queue
      await self.process_one()
    File "/usr/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 501, in process_one
      await dispatch(*args)
    File "/usr/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 408, in dispatch_shell
      await result
    File "/usr/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 731, in execute_request
      reply_content = await reply_content
    File "/usr/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 417, in do_execute
      res = shell.run_cell(
    File "/usr/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 540, in run_cell
      return super().run_cell(*args, **kwargs)
    File "/usr/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 2945, in run_cell
      result = self._run_cell(
    File "/usr/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3000, in _run_cell
      return runner(coro)
    File "/usr/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "/usr/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3203, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "/usr/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3382, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "/usr/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3442, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "/tmp/ipykernel_40257/48579934.py", line 2, in <module>
      train = model.fit(x_train,y_train,epochs=200)
    File "/home/fengh/.local/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/home/fengh/.local/lib/python3.10/site-packages/keras/engine/training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "/home/fengh/.local/lib/python3.10/site-packages/keras/engine/training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "/home/fengh/.local/lib/python3.10/site-packages/keras/engine/training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/fengh/.local/lib/python3.10/site-packages/keras/engine/training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "/home/fengh/.local/lib/python3.10/site-packages/keras/engine/training.py", line 1054, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "/home/fengh/.local/lib/python3.10/site-packages/keras/optimizers/optimizer.py", line 532, in minimize
      self.apply_gradients(grads_and_vars)
    File "/home/fengh/.local/lib/python3.10/site-packages/keras/optimizers/optimizer.py", line 1163, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "/home/fengh/.local/lib/python3.10/site-packages/keras/optimizers/optimizer.py", line 639, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "/home/fengh/.local/lib/python3.10/site-packages/keras/optimizers/optimizer.py", line 1189, in _internal_apply_gradients
      return tf.__internal__.distribute.interim.maybe_merge_call(
    File "/home/fengh/.local/lib/python3.10/site-packages/keras/optimizers/optimizer.py", line 1239, in _distributed_apply_gradients_fn
      distribution.extended.update(
    File "/home/fengh/.local/lib/python3.10/site-packages/keras/optimizers/optimizer.py", line 1234, in apply_grad_to_update_var
      return self._update_step_xla(grad, var, id(self._var_key(var)))
Node: 'StatefulPartitionedCall_5'
libdevice not found at ./libdevice.10.bc
	 [[{{node StatefulPartitionedCall_5}}]] [Op:__inference_train_function_30698]
```

Here: https://github.com/miguelgargallo/jupyter-notebook/blob/main/03-tensorflow-pirates-chatbot/03-tensorflow-pirates-chatbot.ipynb

But this worked on Google Colab, I want it in local

So here I am

![image](https://user-images.githubusercontent.com/5947268/213451019-f6134fc6-9ab4-492e-a9c5-29fcda1fcad6.png)

**Comment by hawkinsp** [comment]
@miguelgargallo That's a TensorFlow error, not a JAX one. Please file an issue on the TensorFlow github issue tracker.

**Comment by miguelgargallo** [comment]
Okay, understood

anyway if I can help anyone in the future with same error:

```
find / -type d -name nvvm 2>/dev/null
```

go to this directory if it's not /usr/lib/nvvm/
create directories: /usr/lib/nvvm/
and place there the file: libdevice.10.bc

then go to your project directory where it fails, and paste the file libdevice.10.bc there too.

This solved my problem <3 good luck!

**Comment by BraveDrXuTF** [comment]
Same error occurs on windows 10, what should I do?

**Comment by hawkinsp** [comment]
@BraveDrXuTF JAX does not support Windows on GPU. We welcome PRs, but it's up to the community to fix any problems.
