### ISSUE TITLE
GPU memory allocation issues

### ISSUE THREAD

**Issue by mc2engel** [google/jax#4528]
Hello,

I'm trying to optimise over the parameters of an Ising lattice dynamics simulation using Jax. My simulation itself works fine in Jax for arbitrary 2D lattice sizes (well, I've tried up to 256x256), but when I attempt to use **grad()** to differentiate over the simulation, I run into the following error for lattices larger than 40x40:

> $ singularity exec --nv ~/SINGULARITIES/jaxmdsept22-2020-09-21-b0ac2a349a9b.simg python3 ~/CODE/ISING/Ising_optimize.py input losses.dat protocols.dat
2020-10-09 14:45:08.845162: W external/org_tensorflow/tensorflow/core/common_runtime/bfc_allocator.cc:433] Allocator (GPU_0_bfc) ran out of memory trying to allocate 128.0KiB (rounded to 131072)requested by op 
2020-10-09 14:45:09.068002: W external/org_tensorflow/tensorflow/core/common_runtime/bfc_allocator.cc:441] ****************************************************************************************************
2020-10-09 14:45:09.068055: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_client.cc:1765] Execution of replica 0 failed: Resource exhausted: Out of memory while trying to allocate 131072 bytes.
Traceback (most recent call last):
  File \"/n/home05/mengel/CODE/ISING/Ising_optimize.py\", line 81, in <module>
    opt_state, loss_ = step(split, i0, get_params, opt_state, opt_update, lattice_size,init_lattice,timesteps,Jij,num_its_w)
  File "/n/home05/mengel/CODE/ISING/optimize_defs.py", line 93, in step
    loss, g = grun(params,split,lattice_size,init_lattice,timesteps,Jij,num_iterations)
  File "/usr/local/lib/python3.6/dist-packages/jax/api.py", line 811, in value_and_grad_f
    ans, vjp_py = \_vjp(f_partial, *dyn_args)
  File "/usr/local/lib/python3.6/dist-packages/jax/api.py", line 1856, in \_vjp
    out\_primal, out\_vjp = ad.vjp(flat\_fun, primals_flat)
  File "/usr/local/lib/python3.6/dist-packages/jax/interpreters/ad.py", line 110, in vjp
    out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
  File "/usr/local/lib/python3.6/dist-packages/jax/interpreters/ad.py", line 97, in linearize
    jaxpr, out\_pvals, consts = pe.trace_to_jaxpr(jvpfun\_flat, in\_pvals)
  File "/usr/local/lib/python3.6/dist-packages/jax/interpreters/partial\_eval.py", line 422, in trace\_to\_jaxpr
    jaxpr, (out\_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/usr/local/lib/python3.6/dist-packages/jax/linear\_util.py", line 151, in call\_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/n/home05/mengel/CODE/ISING/optimize_defs.py", line 81, in run
    return average\_dissipation\_only(num\_iterations,subkey,lattice\_size,init\_lattice,timesteps,Jij,Bsched,kTsched)
  File "/n/home05/mengel/CODE/ISING/optimize\_defs.py", line 67, in average\_dissipation_only
    w, \_ = Ising\_sim\_checkerboard(subkey,lattice\_size,init\_lattice,timesteps,Bsched,kTsched)
  File "/n/home05/mengel/CODE/ISING/optimize\_defs.py", line 38, in Ising\_sim\_checkerboard
    winc\_w, lattice\_=jit\_update\_checker\_white(subkey2,lattice\_,kT,B)
  File "/usr/local/lib/python3.6/dist-packages/jax/api.py", line 214, in f\_jitted
    donated\_invars=donated\_invars)
  File "/usr/local/lib/python3.6/dist-packages/jax/core.py", line 1146, in bind
    return call\_bind(self, fun, *args, **params)
  File "/usr/local/lib/python3.6/dist-packages/jax/core.py", line 1138, in call\_bind
    outs = primitive.process(top\_trace, fun, tracers, params)
  File "/usr/local/lib/python3.6/dist-packages/jax/core.py", line 1149, in process
    return trace.process\_call(self, fun, tracers, params)
  File "/usr/local/lib/python3.6/dist-packages/jax/interpreters/ad.py", line 275, in process\_call
    result = call_primitive.bind(f\_jvp, *primals, *nonzero\_tangents, **new\_params)
  File "/usr/local/lib/python3.6/dist-packages/jax/core.py", line 1146, in bind
    return call\_bind(self, fun, *args, **params)
  File "/usr/local/lib/python3.6/dist-packages/jax/core.py", line 1138, in call_bind
    outs = primitive.process(top\_trace, fun, tracers, params)
  File "/usr/local/lib/python3.6/dist-packages/jax/core.py", line 1149, in process
    return trace.process\_call(self, fun, tracers, params)
  File "/usr/local/lib/python3.6/dist-packages/jax/interpreters/partial_eval.py", line 182, in process\_call
    f, in\_pvals, partial(primitive.bind, **params))
  File "/usr/local/lib/python3.6/dist-packages/jax/interpreters/partial\_eval.py", line 281, in partial_eval
    out\_flat, (out\_avals, jaxpr, env) = app(f, *in\_consts), aux()
  File "/usr/local/lib/python3.6/dist-packages/jax/core.py", line 1146, in bind
    return call\_bind(self, fun, *args, **params)
  File "/usr/local/lib/python3.6/dist-packages/jax/core.py", line 1135, in call\_bind
    outs = primitive.impl(fun, *args, **params)
  File "/usr/local/lib/python3.6/dist-packages/jax/interpreters/xla.py", line 532, in \_xla\_call\_impl
    return compiled\_fun(*args)
  File "/usr/local/lib/python3.6/dist-packages/jax/interpreters/xla.py", line 762, in \_execute\_compiled
    out\_bufs = compiled.execute(input\_bufs)
RuntimeError: Resource exhausted: Out of memory while trying to allocate 131072 bytes.

Regardless of what lattice size I try to run (for larger than 40x40), the error always occurs at 131072 bytes. I saw that similar issues were flagged previously (#788 and #1491), but then closed, and I'm not sure why I'm still seeing this error. I assume my GPU has ample memory for the task?

Details of my runtime environment:

Ubuntu 18.04
Cuda 10.1
Cudnn 7
Python 3.6
NVIDIA V100 GPUs
Nvidia driver version 396.26 (supports Cuda 9, but 10.1 is backward-compatible)
Jaxlib v 0.1.55
Jax v 0.1.77

I have to run Jax from a Singularity on a cluster because of an incompatibility with the cluster's OS, CentOS7.

One last strange detail: I only get the error for 40x40 lattices with certain initial simulation parameters (eg temperature profile). All lattices larger than 40x40 fail, though. Also, comparing the log output of a 40x40 simulation that succeeded and a 40x40 simulation that failed reveals that the crucial step is indeed compiling the backward pass; the orange box indicates output the successful run has that the unsuccessful run does not:

<img width="1735" alt="log_success" src="https://user-images.githubusercontent.com/50532257/95623851-fb4ac500-0a43-11eb-8321-672630e5bac9.png">

Any insight on this would be greatly appreciated! I am not an expert with CUDA or GPU programming, so please forgive anything obvious I've overlooked...

**Comment by hawkinsp** [comment]
I think we'd need something we can run in order to debug this issue. There are a lot of possible causes of a GPU out of memory issue.

**Comment by hawkinsp** [comment]
Closing until there's something we can run to debug. Feel free to reopen with a reproduction!
