### ISSUE TITLE
Building from source not using cuda defined path

### ISSUE THREAD

**Issue by kennychowdhary** [google/jax#4703]
I am trying to compile jax from source on a Linux CentosOS7 machine using **cuda-10.1.243** and **cudnn-7.6.5.32** with python 3.6.8. I have defined the cuda path and the cudnn path as follows:

**CUDA_ROOT**:
```
/opt/spack/c7.7/compilers-20200612/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/cuda-10.1.243-7pddwdl3rtgpr5cmojwalw266jg64clc/
```

and 

**CUDNN_ROOT**:
```
/opt/spack/c7.7/stock-20200612/spack/opt/spack/linux-centos7-x86_64/gcc-7.5.0/cudnn-7.6.5.32-10.2-linux-x64-jj7xix24767akabowzvo4lq2nwlbapuv/
```
When I run 
```
$python build/build.py --enable_cuda --cuda_path $CUDA_ROOT --cudnn_path $CUDNN_ROOT`
```
in the command line, the initialization goes fine, but then afterwards I get an error. It seems that it's linking to /usr/local/cuda incorrectly even though I defined a different root. See below:  

```
     _   _  __  __
    | | / \ \ \/ /
 _  | |/ _ \ \  /
| |_| / ___ \/  \
 \___/_/   \/_/\_\


Bazel binary path: ./bazel-2.0.0-linux-x86_64
Python binary path: /home/kchowdh/gpu_test_py36/bin/python
Python version: 3.6
MKL-DNN enabled: yes
-march=native: no
CUDA enabled: yes
CUDA toolkit path: /opt/spack/c7.7/compilers-20200612/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/cuda-10.1.243-7pddwdl3rtgpr5cmojwalw266jg64clc/
CUDNN library path: /opt/spack/c7.7/stock-20200612/spack/opt/spack/linux-centos7-x86_64/gcc-7.5.0/cudnn-7.6.5.32-10.2-linux-x64-jj7xix24767akabowzvo4lq2nwlbapuv/
CUDA compute capabilities: 3.5,5.2,6.0,6.1,7.0
```
So it's setting the user defined folders correctly, but then it tries to look in the wrong folder:

```
Building XLA and installing it in the jaxlib source tree...
./bazel-2.0.0-linux-x86_64 run --verbose_failures=true --config=short_logs --config=mkl_open_source_only --config=cuda --define=xla_python_enable_gpu=true :install_xla_in_source_tree /home/kchowdh/jax/build
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'run' from /home/kchowdh/jax/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'run' from /home/kchowdh/jax/.bazelrc:
  Inherited 'build' options: --repo_env PYTHON_BIN_PATH=/home/kchowdh/gpu_test_py36/bin/python --python_path=/home/kchowdh/gpu_test_py36/bin/python --repo_env TF_NEED_CUDA=1 --action_env TF_CUDA_COMPUTE_CAPABILITIES=3.5,5.2,6.0,6.1,7.0 --distinct_host_configuration=false --copt=-Wno-sign-compare -c opt --apple_platform_type=macos --macos_minimum_os=10.9 --announce_rc --define open_source_build=true --define=no_aws_support=true --define=no_gcp_support=true --define=no_hdfs_support=true --define=no_kafka_support=true --define=no_ignite_support=true --define=grpc_no_ares=true --spawn_strategy=standalone --strategy=Genrule=standalone --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --action_env CUDA_TOOLKIT_PATH=/opt/spack/c7.7/compilers-20200612/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/cuda-10.1.243-7pddwdl3rtgpr5cmojwalw266jg64clc/ --action_env CUDNN_INSTALL_PATH=/opt/spack/c7.7/stock-20200612/spack/opt/spack/linux-centos7-x86_64/gcc-7.5.0/cudnn-7.6.5.32-10.2-linux-x64-jj7xix24767akabowzvo4lq2nwlbapuv/
INFO: Found applicable config definition build:short_logs in file /home/kchowdh/jax/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:mkl_open_source_only in file /home/kchowdh/jax/.bazelrc: --define=tensorflow_mkldnn_contraction_kernel=1
INFO: Found applicable config definition build:cuda in file /home/kchowdh/jax/.bazelrc: --crosstool_top=@local_config_cuda//crosstool:toolchain --define=using_cuda=true --define=using_cuda_nvcc=true
Loading: 
Loading: 0 packages loaded
INFO: Call stack for the definition of repository 'local_config_cuda' which is a cuda_configure (rule definition at /home/kchowdh/.cache/bazel/_bazel_kchowdh/cc36dafb1b8e245ab9b2a660c3a2dc0d/external/org_tensorflow/third_party/gpus/cuda_configure.bzl:1430:18):
 - /home/kchowdh/.cache/bazel/_bazel_kchowdh/cc36dafb1b8e245ab9b2a660c3a2dc0d/external/org_tensorflow/tensorflow/workspace.bzl:97:5
 - /home/kchowdh/.cache/bazel/_bazel_kchowdh/cc36dafb1b8e245ab9b2a660c3a2dc0d/external/org_tensorflow/tensorflow/workspace.bzl:76:5
 - /home/kchowdh/jax/WORKSPACE:46:1
Loading: 0 packages loaded
    currently loading: build
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
	File "/home/kchowdh/.cache/bazel/_bazel_kchowdh/cc36dafb1b8e245ab9b2a660c3a2dc0d/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1400
		_create_local_cuda_repository(<1 more arguments>)
	File "/home/kchowdh/.cache/bazel/_bazel_kchowdh/cc36dafb1b8e245ab9b2a660c3a2dc0d/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1075, in _create_local_cuda_repository
		_find_libs(repository_ctx, <2 more arguments>)
	File "/home/kchowdh/.cache/bazel/_bazel_kchowdh/cc36dafb1b8e245ab9b2a660c3a2dc0d/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 606, in _find_libs
		_check_cuda_libs(repository_ctx, <2 more arguments>)
	File "/home/kchowdh/.cache/bazel/_bazel_kchowdh/cc36dafb1b8e245ab9b2a660c3a2dc0d/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 501, in _check_cuda_libs
		execute(repository_ctx, <1 more arguments>)
	File "/home/kchowdh/.cache/bazel/_bazel_kchowdh/cc36dafb1b8e245ab9b2a660c3a2dc0d/external/org_tensorflow/third_party/remote_config/common.bzl", line 217, in execute
		fail(<1 more arguments>)
Repository command failed
No library found under: /opt/spack/c7.3/base2/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/cuda-8.0.44-7damutmq5sdv5bzxgccunxoppdc5hymy/lib64/libcublas.so.10
```
The CUDA_ROOT I defined above is NOT being used in the compilation. From above, it looks like the compilation is trying to look in /usr/local/cuda which (on this machine) is linked to 

```
/opt/spack/c7.3/base2/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/cuda-8.0.44-7damutmq5sdv5bzxgccunxoppdc5hymy
```
I am not the admin on the system so I cannot change this (although I am trying to get it fixed). So somewhere in the build code it is using /usr/local/cuda and not $CUDA_ROOT.

**Comment by kennychowdhary** [comment]
I think it may be an issue with the bazel installation. Is there a way to edit the bazel configuration to force it to look into the custom CUDA ROOT?

**Comment by kennychowdhary** [comment]
I was able to solve this problem by defining TF_CUDA_PATHS ahead of the installation. In my terminal I ran 

export TF_CUDA_PATHS=$CUDA_ROOT,$INCLUDE,$LD_LIBRARY_PATH

After this, bazel was able to find the correct path to cuda. I also had to upgrade my gcc to 7.5.0 FYI.
