### ISSUE TITLE
Missing libcublasLt.so on CUDA 10.0

### ISSUE THREAD

**Issue by clemisch** [google/jax#4705]
Dear jax team,

I am trying to compile jaxlib from HEAD with CUDA 10.0.

```
python3 build/build.py --enable_cuda --cuda_path /usr/local/cuda-10.0/
```

The compilation fails because of missing

```
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcublasLt.so.10.0
```

**I have been unable to find `libcublasLt.so` for CUDA 10.0.** `dpkg -S` returns nothing and the file is not included in the apt package `libcublas10`. I tried 

```
sudo ln -s /usr/local/cuda-10.0/targets/x86_64-linux/lib/libcublas.so /usr/local/cuda-10.0/targets/x86_64-linux/lib/libcublasLt.so.10.0
```

but unsurprisingly this is not the correct file and I get a SONAME error. 

Going from your [install guide](https://github.com/google/jax#installation), you still support CUDA 10.0. Is the new requirement of `libcublasLt.so` on your radar? Am I missing something?

<details>
  <summary>Full log</summary>

```
[clemisch@server][jax]$ python3 build/build.py --enable_cuda --cuda_path /usr/local/cuda-10.0/ 

     _   _  __  __
    | | / \ \ \/ /
 _  | |/ _ \ \  /
| |_| / ___ \/  \
 \___/_/   \/_/\_\


Bazel binary path: ./bazel-2.0.0-linux-x86_64
Python binary path: /usr/bin/python3
Python version: 3.6
MKL-DNN enabled: yes
-march=native: no
CUDA enabled: yes
CUDA toolkit path: /usr/local/cuda-10.0/
CUDA compute capabilities: 3.5,5.2,6.0,6.1,7.0

Building XLA and installing it in the jaxlib source tree...
./bazel-2.0.0-linux-x86_64 run --verbose_failures=true --config=short_logs --config=mkl_open_source_only --config=cuda --define=xla_python_enable_gpu=true :install_xla_in_source_tree /buffer/clemisch/jax/build
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'run' from /buffer/clemisch/jax/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'run' from /buffer/clemisch/jax/.bazelrc:
  Inherited 'build' options: --repo_env PYTHON_BIN_PATH=/usr/bin/python3 --python_path=/usr/bin/python3 --repo_env TF_NEED_CUDA=1 --action_env TF_CUDA_COMPUTE_CAPABILITIES=3.5,5.2,6.0,6.1,7.0 --distinct_host_configuration=false --copt=-Wno-sign-compare -c opt --apple_platform_type=macos --macos_minimum_os=10.9 --announce_rc --define open_source_build=true --define=no_aws_support=true --define=no_gcp_support=true --define=no_hdfs_support=true --define=no_kafka_support=true --define=no_ignite_support=true --define=grpc_no_ares=true --spawn_strategy=standalone --strategy=Genrule=standalone --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --action_env CUDA_TOOLKIT_PATH=/usr/local/cuda-10.0/
INFO: Found applicable config definition build:short_logs in file /buffer/clemisch/jax/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:mkl_open_source_only in file /buffer/clemisch/jax/.bazelrc: --define=tensorflow_mkldnn_contraction_kernel=1
INFO: Found applicable config definition build:cuda in file /buffer/clemisch/jax/.bazelrc: --crosstool_top=@local_config_cuda//crosstool:toolchain --define=using_cuda=true --define=using_cuda_nvcc=true
Loading: 
Loading: 0 packages loaded
INFO: Call stack for the definition of repository 'local_config_cuda' which is a cuda_configure (rule definition at /buffer/clemisch/bazel_cache_3/_bazel_clemisch/64c20291e7b583e08f1dc1b7df40e5f2/external/org_tensorflow/third_party/gpus/cuda_configure.bzl:1430:18):
 - /buffer/clemisch/bazel_cache_3/_bazel_clemisch/64c20291e7b583e08f1dc1b7df40e5f2/external/org_tensorflow/tensorflow/workspace.bzl:97:5
 - /buffer/clemisch/bazel_cache_3/_bazel_clemisch/64c20291e7b583e08f1dc1b7df40e5f2/external/org_tensorflow/tensorflow/workspace.bzl:76:5
 - /buffer/clemisch/jax/WORKSPACE:46:1
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "/buffer/clemisch/bazel_cache_3/_bazel_clemisch/64c20291e7b583e08f1dc1b7df40e5f2/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1400
                _create_local_cuda_repository(<1 more arguments>)
        File "/buffer/clemisch/bazel_cache_3/_bazel_clemisch/64c20291e7b583e08f1dc1b7df40e5f2/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1075, in _create_local_cuda_repository
                _find_libs(repository_ctx, <2 more arguments>)
        File "/buffer/clemisch/bazel_cache_3/_bazel_clemisch/64c20291e7b583e08f1dc1b7df40e5f2/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 606, in _find_libs
                _check_cuda_libs(repository_ctx, <2 more arguments>)
        File "/buffer/clemisch/bazel_cache_3/_bazel_clemisch/64c20291e7b583e08f1dc1b7df40e5f2/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 501, in _check_cuda_libs
                execute(repository_ctx, <1 more arguments>)
        File "/buffer/clemisch/bazel_cache_3/_bazel_clemisch/64c20291e7b583e08f1dc1b7df40e5f2/external/org_tensorflow/third_party/remote_config/common.bzl", line 217, in execute
                fail(<1 more arguments>)
Repository command failed
No library found under: /usr/local/cuda-10.0/targets/x86_64-linux/lib/libcublasLt.so.10.0
ERROR: Skipping ':install_xla_in_source_tree': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "/buffer/clemisch/bazel_cache_3/_bazel_clemisch/64c20291e7b583e08f1dc1b7df40e5f2/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1400
                _create_local_cuda_repository(<1 more arguments>)
        File "/buffer/clemisch/bazel_cache_3/_bazel_clemisch/64c20291e7b583e08f1dc1b7df40e5f2/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1075, in _create_local_cuda_repository
                _find_libs(repository_ctx, <2 more arguments>)
        File "/buffer/clemisch/bazel_cache_3/_bazel_clemisch/64c20291e7b583e08f1dc1b7df40e5f2/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 606, in _find_libs
                _check_cuda_libs(repository_ctx, <2 more arguments>)
        File "/buffer/clemisch/bazel_cache_3/_bazel_clemisch/64c20291e7b583e08f1dc1b7df40e5f2/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 501, in _check_cuda_libs
                execute(repository_ctx, <1 more arguments>)
        File "/buffer/clemisch/bazel_cache_3/_bazel_clemisch/64c20291e7b583e08f1dc1b7df40e5f2/external/org_tensorflow/third_party/remote_config/common.bzl", line 217, in execute
                fail(<1 more arguments>)
Repository command failed
No library found under: /usr/local/cuda-10.0/targets/x86_64-linux/lib/libcublasLt.so.10.0
WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "/buffer/clemisch/bazel_cache_3/_bazel_clemisch/64c20291e7b583e08f1dc1b7df40e5f2/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1400
                _create_local_cuda_repository(<1 more arguments>)
        File "/buffer/clemisch/bazel_cache_3/_bazel_clemisch/64c20291e7b583e08f1dc1b7df40e5f2/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1075, in _create_local_cuda_repository
                _find_libs(repository_ctx, <2 more arguments>)
        File "/buffer/clemisch/bazel_cache_3/_bazel_clemisch/64c20291e7b583e08f1dc1b7df40e5f2/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 606, in _find_libs
                _check_cuda_libs(repository_ctx, <2 more arguments>)
        File "/buffer/clemisch/bazel_cache_3/_bazel_clemisch/64c20291e7b583e08f1dc1b7df40e5f2/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 501, in _check_cuda_libs
                execute(repository_ctx, <1 more arguments>)
        File "/buffer/clemisch/bazel_cache_3/_bazel_clemisch/64c20291e7b583e08f1dc1b7df40e5f2/external/org_tensorflow/third_party/remote_config/common.bzl", line 217, in execute
                fail(<1 more arguments>)
Repository command failed
No library found under: /usr/local/cuda-10.0/targets/x86_64-linux/lib/libcublasLt.so.10.0
INFO: Elapsed time: 0.509s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully (0 packages loaded)
Traceback (most recent call last):
  File "build/build.py", line 380, in <module>
    main()
  File "build/build.py", line 375, in main
    shell(command)
  File "build/build.py", line 47, in shell
    output = subprocess.check_output(cmd)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./bazel-2.0.0-linux-x86_64', 'run', '--verbose_failures=true', '--config=short_logs', '--config=mkl_open_source_only', '--config=cuda', '--define=xla_python_enable_gpu=true', ':install_xla_in_source_tree', '/buffer/clemisch/jax/build']' returned non-zero exit status 1.
```
</details>

**Comment by clemisch** [comment]
Sorry to bug you with such technical issues. I have read [on SO](https://stackoverflow.com/a/63316574/6465762) that CUDA 10.0 and lower don't have `libcublasLt.so`. 

> libcublasLt.so is not on your machine. This means you are working with CUDA version prior to the introduction of the cublasLt API **(i.e. 10.0 or prior)** [...]

Could you just let me know whether you are able to build HEAD with CUDA 10.0 and this _is_ an error on my side?

**Comment by skye** [comment]
We're seeing this error too, so I don't think it's an error on your side. This is an underlying build error from XLA, which is built out of the Tensorflow source tree. I'm not sure TF officially supports building against multiple CUDA versions (see https://www.tensorflow.org/install/source#linux), so I'm guessing that something recently-ish broke when building against CUDA 10.0.

I'm gonna see if I can find a solution for this since it's preventing us from building new jaxlib+cuda100 wheels, but in the meantime, upgrading to CUDA 10.1 will likely fix the issue if you're able to upgrade.

**Comment by clemisch** [comment]
Thank you skye for the information!
