### ISSUE TITLE
Use system-wide flatbuffers

### ISSUE THREAD

**Issue by surak** [google/jax#4743]
The old libstdc++ problem, with flatbuffers

```
INFO: Found 1 target...
[0 / 21] [Prepa] BazelWorkspaceStatusAction stable-status.txt
[379 / 3,869] Executing genrule @local_config_cuda//cuda:cuda-lib; 8s local ... (80 actions, 79 running)
[569 / 3,869] Executing genrule @local_config_cuda//cuda:cuda-lib; 16s local ... (80 actions, 79 running)
[686 / 3,869] Executing genrule @local_config_python//:numpy_include; 26s local ... (80 actions, 79 running)
[828 / 3,869] Executing genrule @local_config_python//:python_include; 37s local ... (80 actions, 79 running)
[939 / 3,869] Executing genrule @local_config_python//:python_include; 50s local ... (80 actions, 79 running)
[1,125 / 3,869] Executing genrule @local_config_python//:python_include; 65s local ... (80 actions, 79 running)
[1,385 / 3,869] Executing genrule @local_config_python//:python_include; 82s local ... (80 actions, 79 running)
ERROR: /dev/shm/strube1/JAX/0.2.5/gpsmkl-2020-Python-3.8.5/jax-jax-v0.2.5/jaxlib/BUILD:187:22: Generating flatbuffer files for <source file jaxlib/pocketfft.fbs>: failed (Exit 1): flatc failed: error executing command 
  (cd /dev/shm/strube1/JAX/0.2.5/gpsmkl-2020-Python-3.8.5/.home/.cache/bazel/_bazel_strube1/e32c15cefdda779df66db3467646629f/execroot/__main__ && \
  exec env - \
  bazel-out/k8-opt/bin/external/flatbuffers/flatc --python -o bazel-out/k8-opt/bin/jaxlib/pocketfft_flatbuffers_py_srcs_no_include_all -I ./ -I bazel-out/k8-opt/bin -I bazel-out/k8-opt/bin --no-includes --no-union-value-namespacing --gen-object-api jaxlib/pocketfft.fbs)
Execution platform: @local_execution_config_platform//:platform
bazel-out/k8-opt/bin/external/flatbuffers/flatc: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by bazel-out/k8-opt/bin/external/flatbuffers/flatc)
Target //build:install_xla_in_source_tree failed to build
INFO: Elapsed time: 141.896s, Critical Path: 93.97s
INFO: 2679 processes: 1761 internal, 918 local.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully

     _   _  __  __
    | | / \ \ \/ /
 _  | |/ _ \ \  /
| |_| / ___ \/  \
 \___/_/   \/_/\_\


Bazel binary path: /p/software/juwels/stages/Devel-2020/software/Bazel/3.6.0-GCCcore-9.3.0/bin/bazel
Python binary path: /p/software/juwels/stages/Devel-2020/software/Python/3.8.5-GCCcore-9.3.0/bin/python
Python version: 3.8
MKL-DNN enabled: no
-march=native: no
CUDA enabled: yes
CUDA toolkit path: /p/software/juwels/stages/Devel-2020/software/CUDA/11.0
CUDNN library path: /p/software/juwels/stages/Devel-2020/software/cuDNN/8.0.2.39-CUDA-11.0
CUDA compute capabilities: 3.5,5.2,6.0,6.1,7.0

Building XLA and installing it in the jaxlib source tree...
/p/software/juwels/stages/Devel-2020/software/Bazel/3.6.0-GCCcore-9.3.0/bin/bazel run --verbose_failures=true --action_env=PYTHONPATH --config=short_logs --config=cuda --define=xla_python_enable_gpu=true :install_xla_in_source_tree /dev/shm/strube1/JAX/0.2.5/gpsmkl-2020-Python-3.8.5/jax-jax-v0.2.5/build
Traceback (most recent call last):
  File "build/build.py", line 380, in <module>
    main()
  File "build/build.py", line 375, in main
    shell(command)
  File "build/build.py", line 47, in shell
    output = subprocess.check_output(cmd)
  File "/p/software/juwels/stages/Devel-2020/software/Python/3.8.5-GCCcore-9.3.0/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/p/software/juwels/stages/Devel-2020/software/Python/3.8.5-GCCcore-9.3.0/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/p/software/juwels/stages/Devel-2020/software/Bazel/3.6.0-GCCcore-9.3.0/bin/bazel', 'run', '--verbose_failures=true', '--action_env=PYTHONPATH', '--config=short_logs', '--config=cuda', '--define=xla_python_enable_gpu=true', ':install_xla_in_source_tree', '/dev/shm/strube1/JAX/0.2.5/gpsmkl-2020-Python-3.8.5/jax-jax-v0.2.5/build']' returned non-zero exit status 1.
 (at easybuild/tools/run.py:533 in parse_cmd_output)
== 2020-10-30 17:15:58,223 filetools.py:1610 INFO Removing lock /p/software/juwels/stages/Devel-2020/software/.locks/_p_software_juwels_stages_Devel-2020_software_JAX_0.2.5-gpsmkl-2020-Python-3.8.5.lock...
== 2020-10-30 17:15:58,224 filetools.py:330 INFO Path /p/software/juwels/stages/Devel-2020/software/.locks/_p_software_juwels_stages_Devel-2020_software_JAX_0.2.5-gpsmkl-2020-Python-3.8.5.lock successfully removed.
== 2020-10-30 17:15:58,224 filetools.py:1614 INFO Lock removed: /p/software/juwels/stages/Devel-2020/software/.locks/_p_software_juwels_stages_Devel-2020_software_JAX_0.2.5-gpsmkl-2020-Python-3.8.5.lock
== 2020-10-30 17:15:58,224 easyblock.py:3311 WARNING build failed (first 300 chars): cmd " export TF_CUDA_PATHS=${EBROOTCUDA} && export HOME=/dev/shm/strube1/JAX/0.2.5/gpsmkl-2020-Python-3.8.5/.home/ && python build/build.py --enable_cuda --cuda_path ${EBROOTCUDA} --cudnn_path ${EBROOTCUDNN} --bazel_path ${EBROOTBAZEL}/bin/bazel --bazel_options=--action_env=PYTHONPATH --noenable_mkl
== 2020-10-30 17:15:58,224 easyblock.py:295 INFO Closing log for application name JAX version 0.2.5
== 2020-10-30 17:15:58,224 build_log.py:265 INFO FAILED: Installation ended unsuccessfully (build directory: /dev/shm/strube1/JAX/0.2.5/gpsmkl-2020-Python-3.8.5): build failed (first 300 chars): cmd " export TF_CUDA_PATHS=${EBROOTCUDA} && export HOME=/dev/shm/strube1/JAX/0.2.5/gpsmkl-2020-Python-3.8.5/.home/ && python build/build.py --enable_cuda --cuda_path ${EBROOTCUDA} --cudnn_path ${EBROOTCUDNN} --bazel_path ${EBROOTBAZEL}/bin/bazel --bazel_options=--action_env=PYTHONPATH --noenable_mkl (took 2 min 29 sec)
== FAILED: Installation ended unsuccessfully (build directory: /dev/shm/strube1/JAX/0.2.5/gpsmkl-2020-Python-3.8.5): build failed (first 300 chars): cmd " export TF_CUDA_PATHS=${EBROOTCUDA} && export HOME=/dev/shm/strube1/JAX/0.2.5/gpsmkl-2020-Python-3.8.5/.home/ && python build/build.py --enable_cuda --cuda_path ${EBROOTCUDA} --cudnn_path ${EBROOTCUDNN} --bazel_path ${EBROOTBAZEL}/bin/bazel --bazel_options=--action_env=PYTHONPATH --noenable_mkl (took 2 min 29 sec)
== 2020-10-30 17:15:58,225 build_log.py:265 INFO Results of the build can be found in the log file(s) /tmp/eb-b4d0za4p/easybuild-JAX-0.2.5-20201030.171329.wPoIS.log
== Results of the build can be found in the log file(s) /tmp/eb-b4d0za4p/easybuild-JAX-0.2.5-20201030.171329.wPoIS.log
== 2020-10-30 17:15:58,225 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): build failed (first 300 chars): cmd " export TF_CUDA_PATHS=${EBROOTCUDA} && export HOME=/dev/shm/strube1/JAX/0.2.5/gpsmkl-2020-Python-3.8.5/.home/ && python build/build.py --enable_cuda --cuda_path ${EBROOTCUDA} --cudnn_path ${EBROOTCUDNN} --bazel_path ${EBROOTBAZEL}/bin/bazel --bazel_options=--action_env=PYTHONPATH --noenable_mkl (at easybuild/main.py:118 in build_and_install_software)
== 2020-10-30 17:15:58,227 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): Build of /p/project/cjsc/a.strube/zlixo/2020-2/easybuild-repository/Golden_Repo/j/JAX/JAX-0.2.5-gpsmkl-2020-Python-3.8.5.eb failed (err: 'build failed (first 300 chars): cmd " export TF_CUDA_PATHS=${EBROOTCUDA} && export HOME=/dev/shm/strube1/JAX/0.2.5/gpsmkl-2020-Python-3.8.5/.home/ && python build/build.py --enable_cuda --cuda_path ${EBROOTCUDA} --cudnn_path ${EBROOTCUDNN} --bazel_path ${EBROOTBAZEL}/bin/bazel --bazel_options=--action_env=PYTHONPATH --noenable_mkl') (at easybuild/main.py:150 in build_and_install_software)
ERROR: Build of /p/project/cjsc/a.strube/zlixo/2020-2/easybuild-repository/Golden_Repo/j/JAX/JAX-0.2.5-gpsmkl-2020-Python-3.8.5.eb failed (err: 'build failed (first 300 chars): cmd " export TF_CUDA_PATHS=${EBROOTCUDA} && export HOME=/dev/shm/strube1/JAX/0.2.5/gpsmkl-2020-Python-3.8.5/.home/ && python build/build.py --enable_cuda --cuda_path ${EBROOTCUDA} --cudnn_path ${EBROOTCUDNN} --bazel_path ${EBROOTBAZEL}/bin/bazel --bazel_options=--action_env=PYTHONPATH --noenable_mkl')
```

**Comment by hawkinsp** [comment]
I don't think your issue is related to flatbuffers per se. The issue is that the `flatc` compiler built by bazel is not able to run successfully on your machine, and that would be an issue for other binaries (e.g., JAX itself!) even if we used a system-provided `flatc`. I'm not sure what's going on, but without more details it's impossible for me to debug this. Can you provide details of your build environment? Can I reproduce this problem, in, for example, a cloud VM set up a particular way?

**Comment by surak** [comment]
This is on 3 of our supercomputers, JUWELS/JUWELSBOOSTER, JUSUF and a smaller HDFML cluster.

Everything is built from source on them, by using EasyBuild (as ou can see by the comment). That goes all the way down from the softwares necessary to bootstrap GCC.

This is a regression from 0.1.77, which is what I am using now, instead of 0.2.5, as it works for me. 

It happens when part of the compilation uses the environment-set stdlibc++, but later, bazel decides to use the hard-coded version in /usr/lib64 or something similar, which is older and will fail.

**Comment by hawkinsp** [comment]
It's going to be very difficult for me to debug this problem if I can't reproduce it somehow.

I also wonder whether it might be preferable to use a prebuilt jaxlib rather than building one from scratch. Is that possible? Could we make it possible?

One thing I might try is setting the `LD_LIBRARY_PATH` environment to point to the directory with the correct `libstdc++`. Does that help?

**Comment by surak** [comment]
> It's going to be very difficult for me to debug this problem if I can't reproduce it somehow.

Is it ok to have it on a container image?

> I also wonder whether it might be preferable to use a prebuilt jaxlib rather than building one from scratch. Is that possible? Could we make it possible?

Unfortunately not. The machines have the whole software stack upgraded once a year, while keeping the old versions still working - having a prebuilt library would be a showstopper for fixing bugs on different versions of everything.
 
> One thing I might try is setting the `LD_LIBRARY_PATH` environment to point to the directory with the correct `libstdc++`. Does that help?

It does not, as bazel tends to do its own stuff regarding that. Most supercomputers use LMOD to keep track of LD_LIBRARY_PATH (and other environment variables), and so do we.
