### ISSUE TITLE
ImportError: libstdc++.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by TetraMiyazaki** [google/jax#4747]
Hi, 
I trying import jax. However I faced a strange problem.
Please help with this import error on a fresh install.

```
>>> import jax
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dl-box/miyazaki/Quantized_UKR/.venv/lib/python3.8/site-packages/jax/__init__.py", line 22, in <module>
    from .api import (
  File "/home/dl-box/miyazaki/Quantized_UKR/.venv/lib/python3.8/site-packages/jax/api.py", line 37, in <module>
    from . import core
  File "/home/dl-box/miyazaki/Quantized_UKR/.venv/lib/python3.8/site-packages/jax/core.py", line 31, in <module>
    from . import dtypes
  File "/home/dl-box/miyazaki/Quantized_UKR/.venv/lib/python3.8/site-packages/jax/dtypes.py", line 31, in <module>
    from .lib import xla_client
  File "/home/dl-box/miyazaki/Quantized_UKR/.venv/lib/python3.8/site-packages/jax/lib/__init__.py", line 53, in <module>
    from jaxlib import xla_client
  File "/home/dl-box/miyazaki/Quantized_UKR/.venv/lib/python3.8/site-packages/jaxlib/xla_client.py", line 39, in <module>
    from . import xla_extension as _xla
ImportError: libstdc++.so.6: cannot open shared object file: No such file or directory
```

My PC OS Information is
```
> dl-box@DL-Box:~/miyazaki/$ cat /proc/version
Linux version 3.13.0-24-generic (buildd@batsu) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014
(.venv) dl-box@DL-Box:~/miyazaki/cat /etc/debian_version
jessie/sid
(.venv) dl-box@DL-Box:~/miyazaki/$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.6 LTS"
(.venv) dl-box@DL-Box:~/miyazaki/$ cat /proc/version
Linux version 3.13.0-24-generic (buildd@batsu) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014
```

My libstdc++6 is newest in this apt-get version.
```
(.venv) dl-box@DL-Box:~/miyazaki/Quantized_UKR$ apt-get --version
apt 1.0.1ubuntu2.24 for amd64 compiled on Oct 10 2019 22:48:21

```

I'm very beginner. and my PC is so old. If you have some adviece, please note me.

**Comment by hawkinsp** [comment]
Thanks for the question!

In general, JAX has a similar set of system requirements to TensorFlow: https://www.tensorflow.org/install/pip#system-requirements because we depend on some components of TensorFlow. The minimum Ubuntu version required is 16.04. So I suggest upgrading your Linux installation.

You could also use something like Colab (colab.research.google.com) to run JAX for free in the cloud!
