### ISSUE TITLE
Error caused by shutil.rmtree 

### ISSUE THREAD

**Issue by cloudhan** [google/jax#4983]
```
Traceback (most recent call last):
  File "\\?\C:\Users\cloud\AppData\Local\Temp\Bazel.runfiles_vfpgffuf\runfiles\__main__\build\install_xla_in_source_tree.py", line 83, in <module>
    shutil.rmtree(jaxlib_dir)
  File "C:\Users\cloud\miniconda3\lib\shutil.py", line 516, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\cloud\miniconda3\lib\shutil.py", line 400, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\cloud\miniconda3\lib\shutil.py", line 398, in _rmtree_unsafe
    os.unlink(fullname)
WindowsError: [Error 5] Access is denied.: 'D:\\jax\\build\\jaxlib\\cublas_kernels.pyd'
```

This only happens on rebuild.

The reason is `shutil.rmtree` will not delete readonly file on Windows.

**Comment by hawkinsp** [comment]
@cloudhan can you try with https://github.com/google/jax/pull/4982 patched in?

This reworks the build a bit more so it builds a wheel file rather than writing into the source tree. Since it uses a temporary directory it doesn't need this particular line of code.

**Comment by hawkinsp** [comment]
I just updated that PR to fix some more windows-specific problems and verified I was able to build a windows wheel.

**Comment by hawkinsp** [comment]
#4982 has now been submitted.

**Comment by cloudhan** [comment]
Python issue tracker [discussion](https://bugs.python.org/issue19643)
