### ISSUE TITLE
jax.numpy.max([1,2]) doesn't work

### ISSUE THREAD

**Issue by qixuanf** [google/jax#5044]
Hello,

when I do
```Python
import jax.numpy as jnp
jnp.max([1,2])
```

I got
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "//volper/users/gaowang/anaconda3/envs/gppr/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 1837, in reduction
    _check_arraylike(name, a)
  File "//volper/users/gaowang/anaconda3/envs/gppr/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 304, in _check_arraylike
    raise TypeError(msg.format(fun_name, type(arg), pos))
TypeError: max requires ndarray or scalar arguments, got <class 'list'> at position 0.
```

My jax version is 0.2.6

Thanks for any help in advance!

**Comment by cgarciae** [comment]
Due to [omnistaging](https://github.com/google/jax/blob/master/design_notes/omnistaging.md) the correct way now should be:

```python
import jax.numpy as jnp
jnp.max(jnp.array([1,2]))
```
Or
```python
import jax.numpy as jnp
import numpy as np
jnp.max(np.array([1,2]))
```

**Comment by jakevdp** [comment]
Small correction: this is unrelated to omnistaging (the check was added in https://github.com/google/jax/pull/4195) but you're correct that the fix is to explicitly cast lists to arrays.
