### ISSUE TITLE
Infinite recursion in jax2tf with bfloat16 input.

### ISSUE THREAD

**Issue by jakevdp** [google/jax#5106]
Short repro:
```python
import jax.numpy as jnp
from jax.experimental import jax2tf

jax2tf.convert(lambda x: x)(jnp.bfloat16(1.0))
```
```pytb
Traceback (most recent call last):
  File "tmp.py", line 7, in <module>
    f(jnp.bfloat16(1.0))
  File "/Users/vanderplas/github/google/jax/jax/experimental/jax2tf/jax2tf.py", line 278, in converted_fun
    out_flat = converted_fun_flat_with_custom_gradient(*args_flat)
  File "/Users/vanderplas/.local/share/virtualenvs/jax-LBbfM5ix/lib/python3.8/site-packages/tensorflow/python/ops/custom_gradient.py", line 258, in __call__
    return self._d(self._f, a, k)
  File "/Users/vanderplas/.local/share/virtualenvs/jax-LBbfM5ix/lib/python3.8/site-packages/tensorflow/python/ops/custom_gradient.py", line 212, in decorated
    return _eager_mode_decorator(wrapped, args, kwargs)
  File "/Users/vanderplas/.local/share/virtualenvs/jax-LBbfM5ix/lib/python3.8/site-packages/tensorflow/python/ops/custom_gradient.py", line 409, in _eager_mode_decorator
    result, grad_fn = f(*args, **kwargs)
  File "/Users/vanderplas/github/google/jax/jax/experimental/jax2tf/jax2tf.py", line 273, in converted_fun_flat_with_custom_gradient
    out_with_avals = _interpret_fun(flat_fun, args_flat, args_avals_flat)
  File "/Users/vanderplas/github/google/jax/jax/experimental/jax2tf/jax2tf.py", line 304, in _interpret_fun
    out_vals: Sequence[Tuple[TfVal, core.AbstractValue]] = fun.call_wrapped(*in_vals)
  File "/Users/vanderplas/github/google/jax/jax/linear_util.py", line 155, in call_wrapped
    args, kwargs = next(gen)
  File "/Users/vanderplas/github/google/jax/jax/experimental/jax2tf/jax2tf.py", line 341, in _interpret_subtrace
    in_tracers = tuple(TensorFlowTracer(trace, val, aval)
  File "/Users/vanderplas/github/google/jax/jax/experimental/jax2tf/jax2tf.py", line 341, in <genexpr>
    in_tracers = tuple(TensorFlowTracer(trace, val, aval)
  File "/Users/vanderplas/github/google/jax/jax/experimental/jax2tf/jax2tf.py", line 657, in __init__
    self.val = _safe_convert_to_tensor(val, dtype=self._aval.dtype)  # type: ignore[attr-defined]
  File "/Users/vanderplas/github/google/jax/jax/experimental/jax2tf/jax2tf.py", line 95, in _safe_convert_to_tensor
    val = tf.bitcast(tf.convert_to_tensor(val.view(jnp.uint16),
  File "/Users/vanderplas/github/google/jax/jax/_src/numpy/lax_numpy.py", line 4909, in _view
    return lax.bitcast_convert_type(arr, dtype)

<snip>

  File "/Users/vanderplas/github/google/jax/jax/experimental/jax2tf/jax2tf.py", line 703, in pure
    return TensorFlowTracer(self, val, core.ShapedArray(shape, dtype))
  File "/Users/vanderplas/github/google/jax/jax/experimental/jax2tf/jax2tf.py", line 657, in __init__
    self.val = _safe_convert_to_tensor(val, dtype=self._aval.dtype)  # type: ignore[attr-defined]
  File "/Users/vanderplas/github/google/jax/jax/experimental/jax2tf/jax2tf.py", line 95, in _safe_convert_to_tensor
    val = tf.bitcast(tf.convert_to_tensor(val.view(jnp.uint16),
  File "/Users/vanderplas/github/google/jax/jax/_src/numpy/lax_numpy.py", line 4909, in _view
    return lax.bitcast_convert_type(arr, dtype)
  File "/Users/vanderplas/github/google/jax/jax/_src/lax/lax.py", line 463, in bitcast_convert_type
    return bitcast_convert_type_p.bind(operand, new_dtype=new_dtype)
  File "/Users/vanderplas/github/google/jax/jax/core.py", line 270, in bind
    tracers = map(top_trace.full_raise, args)
  File "/Users/vanderplas/github/google/jax/jax/util.py", line 36, in safe_map
    return list(map(f, *args))
  File "/Users/vanderplas/github/google/jax/jax/core.py", line 377, in full_raise
    return self.pure(val)
  File "/Users/vanderplas/github/google/jax/jax/experimental/jax2tf/jax2tf.py", line 703, in pure
    return TensorFlowTracer(self, val, core.ShapedArray(shape, dtype))
  File "/Users/vanderplas/github/google/jax/jax/experimental/jax2tf/jax2tf.py", line 657, in __init__
    self.val = _safe_convert_to_tensor(val, dtype=self._aval.dtype)  # type: ignore[attr-defined]
  File "/Users/vanderplas/github/google/jax/jax/experimental/jax2tf/jax2tf.py", line 92, in _safe_convert_to_tensor
    if not isinstance(val, jnp.ndarray):
  File "/Users/vanderplas/github/google/jax/jax/_src/numpy/lax_numpy.py", line 112, in __instancecheck__
    return isinstance(instance.aval, _arraylike_types)
RecursionError: maximum recursion depth exceeded in __instancecheck__
```
I believe this is the issue blocking #5085

**Comment by jakevdp** [comment]
I think the issue is that for bfloat16, `_safe_convert_to_tensor` calls `view()`, which leads to another call to `_safe_convert_to_tensor` within the primitive binding. We'll need to somehow work around this.

**Comment by sbodenstein** [comment]
Is there any update about timeframes for the TF/JAX bfloat16 unification work that would fix this? It's causing some significant issues for us.

**Comment by jakevdp** [comment]
Assigning to @gnecula, as this is jax2tf related, and my initial fix was rejected.
