### ISSUE TITLE
Gradients with np.linalg.inv

### ISSUE THREAD

**Issue by mnazaal** [google/jax#518]
Hi,

I noticed that taking gradients involving the np.linalg.inv function gives an error. Take for example, 

```
from jax import grad
import jax.numpy as np
import jax.random as random
key = random.PRNGKey(0)

W = random.uniform(key, (10, 10), minval=-1, maxval=1)

def some_func(W):
    return np.linalg.inv(W)[0][0]

grad(some_func)(W)
```

This gives the error (included the warnings just in case)

```[...]/jax/lib/xla_bridge.py:146: UserWarning: No GPU found, falling back to CPU.
  warnings.warn('No GPU found, falling back to CPU.')
[...]/jax/numpy/linalg.py:114: UserWarning: numpy.linalg support is experimental and may cause silent failures or wrong outputs
  warnings.warn(_EXPERIMENTAL_WARNING)
[...]/jax/numpy/linalg.py:124: UserWarning: numpy.linalg support is experimental and may cause silent failures or wrong outputs
  warnings.warn(_EXPERIMENTAL_WARNING)
Traceback (most recent call last):
  File "[...]/interpreters/ad.py", line 149, in get_primitive_transpose
    return primitive_transposes[p]
KeyError: sub

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "error.py", line 11, in <module>
    grad(some_func)(W)
  File "[...]/jax/api.py", line 114, in grad_f
    ans, g = value_and_grad_f(*args, **kwargs)
  File "[...]/jax/api.py", line 151, in value_and_grad_f
    g = vjp_py(onp.ones((), onp.result_type(ans)))
  File "[...]/jax/api_util.py", line 55, in apply_jaxtree_fun
    ans = fun(*args)
  File "[...]/jax/api.py", line 366, in out_vjp_packed
    return out_vjp(cotangent_in)
  File "[...]/jax/interpreters/ad.py", line 78, in vjp_
    _, arg_cts = backward_pass(jaxpr, consts, (), dummy_primal_and_ct)
  File "[...]/jax/interpreters/ad.py", line 135, in backward_pass
    cts_out = get_primitive_transpose(eqn.primitive)(ct_in, *invals, **eqn.params)
  File "[...]/jax/interpreters/ad.py", line 152, in get_primitive_transpose
    "Reverse-mode differentiation rule for '{}' not implemented".format(p))
NotImplementedError: Reverse-mode differentiation rule for 'sub' not implemented
```

I'm assuming this is similar to #407 ? 

Thanks

**Comment by hawkinsp** [comment]
I think this is actually fixed already. Are you using an up to date `jax`? (It's possible we haven't pushed it into a release yet, so you might need to use `jax` but not `jaxlib` from Github rather than Pypi.)

**Comment by mnazaal** [comment]
Yes that was the case, apologies my bad
