### ISSUE TITLE
Built with '--enable_cuda' from source; importing jax fails with KeyError: 'CUDA'

### ISSUE THREAD

**Issue by Ed-von-Schleck** [google/jax#5238]
After building jax on Linux from source with

```sh
python build/build.py --noenable_rocm --enable_cuda --cuda_path=<my/cuda/path>   --cudnn_path=<my/cuda/path>
```

and completing without errors, then installing jax/jaxlib with

```sh
pip install dist/*.whl
pip install -e .
```

(again without errors), I get the following exception when trying to import `jax`:

```python
>>> import jax
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<...>/git/jax/jax/__init__.py", line 22, in <module>
    from .api import (
  File "<...>/git/jax/jax/api.py", line 38, in <module>
    from . import core
  File "<...>/git/jax/jax/core.py", line 31, in <module>
    from . import dtypes
  File "<...>/git/jax/jax/dtypes.py", line 31, in <module>
    from .lib import xla_client
  File "<...>/git/jax/jax/lib/__init__.py", line 62, in <module>
    from jaxlib import cusolver
  File "<...>/.virtualenvs/myjax/lib/python3.9/site-packages/jaxlib/cusolver.py", line 26, in <module>
    xla_client.register_custom_call_target(_name, _value, platform="CUDA")
  File "<...>/.virtualenvs/myjax/lib/python3.9/site-packages/jaxlib/xla_client.py", line 434, in register_custom_call_target
    _xla.register_custom_call_target(name, fn, xla_platform_names[platform])
KeyError: 'CUDA'
```

I have exported the following XLA_FLAGS

```sh
export XLA_FLAGS="--xla_gpu_cuda_data_dir=<my/cuda/path>"
```

My CUDA-Installation works in other libraries (e.g. _pytorch_), and since I had no errors building _jax_, I don't know where to start debugging this error. Any help would be very much appreciated.

**Comment by henrysky** [comment]
I have the same issue currently on Windows when trying to compile jax with CUDA 11.2

**Comment by rwightman** [comment]
I just hit the same issue rebuilding from master for a new NGC container release. Not the container though, building from the jax-v0.2.7 tag works fine.

**Comment by dwrtz** [comment]
I also ran into this issue on windows. I was able to get around it by replacing "CUDA" with "gpu" in the following line:

xla_client.register_custom_call_target(_name, _value, platform="CUDA")

the above line shows up twice in jaxlib/cusolver.py and once in jaxlib/cuda_prng.py. making these changes and rebuilding/reinstalling the jaxlib wheel seems to fix the issue. when I run the pytests i get 736 failed, 9370 passed, 1068 skipped, 31 errors.

**Comment by trickarcher** [comment]
I've also hit the same issue, all the tests fail due to the `KeyError: 'CUDA'`. 

The `wheel` gets built without any error, but the tests fail with `KeyError: 'CUDA'`. 

However, JAX with the pre-built `wheel` `jaxlib-0.1.57+cuda101`, gets imported without any complaints. But when I get a runtime error when I try to run a minimal example from the `ReadMe.md` :
```py
from jax import grad
import jax.numpy as jnp

def tanh(x):  # Define a function
  y = jnp.exp(-2.0 * x)
  return (1.0 - y) / (1.0 + y)

grad_tanh = grad(tanh)  # Obtain its gradient function
print(grad_tanh(1.0))   # Evaluate it at x = 1.0
# prints 0.4199743
``` 
```
2020-12-31 19:09:32.512697: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:70] Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice. This may result in compilation or runtime failures, if the program we try to run uses routines from libdevice.
2020-12-31 19:09:32.512732: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:71] Searched for CUDA in the following directories:
2020-12-31 19:09:32.512738: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   ./cuda_sdk_lib
2020-12-31 19:09:32.512743: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   /usr/local/cuda-10.1
2020-12-31 19:09:32.512747: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   .
2020-12-31 19:09:32.512752: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:76] You can choose the search directory by setting xla_gpu_cuda_data_dir in HloModule's DebugOptions.  For most apps, setting the environment variable XLA_FLAGS=--xla_gpu_cuda_data_dir=/path/to/cuda will work.
2020-12-31 19:09:32.592147: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:320] libdevice is required by this HLO module but was not found at ./libdevice.10.bc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in tanh
  File "<...>/.local/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 366, in <lambda>
    fn = lambda x: lax_fn(*_promote_args_inexact(numpy_fn.__name__, x))
  File "<...>/.local/lib/python3.8/site-packages/jax/_src/lax/lax.py", line 189, in exp
    return exp_p.bind(x)
jax._src.traceback_util.FilteredStackTrace: RuntimeError: Internal: libdevice not found at ./libdevice.10.bc

The stack trace above excludes JAX-internal frames.
The following is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<...>/.local/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 139, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "<...>/.local/lib/python3.8/site-packages/jax/api.py", line 706, in grad_f
    _, g = value_and_grad_f(*args, **kwargs)
  File "<...>/.local/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 139, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "<...>/.local/lib/python3.8/site-packages/jax/api.py", line 769, in value_and_grad_f
    ans, vjp_py = _vjp(f_partial, *dyn_args)
  File "<...>/.local/lib/python3.8/site-packages/jax/api.py", line 1846, in _vjp
    out_primal, out_vjp = ad.vjp(flat_fun, primals_flat)
  File "<...>/.local/lib/python3.8/site-packages/jax/interpreters/ad.py", line 114, in vjp
    out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
  File "<...>/.local/lib/python3.8/site-packages/jax/interpreters/ad.py", line 101, in linearize
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr(jvpfun_flat, in_pvals)
  File "<...>/.local/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 516, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "<...>/.local/lib/python3.8/site-packages/jax/linear_util.py", line 160, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "<stdin>", line 2, in tanh
  File "<...>/.local/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 366, in <lambda>
    fn = lambda x: lax_fn(*_promote_args_inexact(numpy_fn.__name__, x))
  File "<...>/.local/lib/python3.8/site-packages/jax/_src/lax/lax.py", line 189, in exp
    return exp_p.bind(x)
  File "<...>/.local/lib/python3.8/site-packages/jax/core.py", line 271, in bind
    out = top_trace.process_primitive(self, tracers, params)
  File "<...>/.local/lib/python3.8/site-packages/jax/interpreters/ad.py", line 285, in process_primitive
    primal_out, tangent_out = jvp(primals_in, tangents_in, **params)
  File "<...>/.local/lib/python3.8/site-packages/jax/interpreters/ad.py", line 469, in standard_jvp2
    val_out = primitive.bind(*primals, **params)
  File "<...>/.local/lib/python3.8/site-packages/jax/core.py", line 271, in bind
    out = top_trace.process_primitive(self, tracers, params)
  File "<...>/.local/lib/python3.8/site-packages/jax/core.py", line 595, in process_primitive
    return primitive.impl(*tracers, **params)
  File "<...>/.local/lib/python3.8/site-packages/jax/interpreters/xla.py", line 235, in apply_primitive
    compiled_fun = xla_primitive_callable(prim, *unsafe_map(arg_spec, args), **params)
  File "<...>/.local/lib/python3.8/site-packages/jax/interpreters/xla.py", line 285, in xla_primitive_callable
    compiled = backend_compile(backend, built_c, options)
  File "<...>/.local/lib/python3.8/site-packages/jax/interpreters/xla.py", line 346, in backend_compile
    return backend.compile(built_c, compile_options=options)
RuntimeError: Internal: libdevice not found at ./libdevice.10.bc
```
Could this `RuntimeError` give any hint as to why importing JAX after building from source returns a `KeyError: 'CUDA'`? Or is it a seperate issue all together?

**Operating System:** PopOS! 20.10
**CUDA Version:** 10.1.105

**Comment by inailuig** [comment]
This is caused by the changes made in https://github.com/google/jax/pull/5115 which went along with https://github.com/tensorflow/tensorflow/pull/45583, so updating tensorflow/XLA to include the latter should fix this.

I guess If we need compatibility with older jaxlib releases we need to change the platform for cuda back to 'gpu' as suggested in https://github.com/google/jax/issues/5302

@hawkinsp

**Comment by hawkinsp** [comment]
I'm pretty sure this just requires bumping the XLA version in the JAX WORKSPACE file. I'll verify that and do it.

**Comment by hawkinsp** [comment]
This is now fixed at head. Sorry for the slow response, I was on vacation!
