### ISSUE TITLE
Build failed with internal compiler error: Segmentation fault

### ISSUE THREAD

**Issue by tataudat** [google/jax#5304]
```
(jax) ➜  jax git:(27a4c888) python build/build.py --enable_cuda

     _   _  __  __
    | | / \ \ \/ /
 _  | |/ _ \ \  /
| |_| / ___ \/  \
 \___/_/   \/_/\_\


Starting local Bazel server and connecting to it...
Bazel binary path: ./bazel-3.1.0-linux-x86_64
Python binary path: /home/dat/frameworks/miniconda3/envs/jax/bin/python
Python version: 3.8
MKL-DNN enabled: yes
-march=native: no
CUDA enabled: yes
CUDA compute capabilities: 3.5,5.2,6.0,6.1,7.0

Building XLA and installing it in the jaxlib source tree...
./bazel-3.1.0-linux-x86_64 run --verbose_failures=true --config=short_logs --config=mkl_open_source_only --config=cuda --define=xla_python_enable_gpu=true :build_wheel -- --output_path=/home/dat/resources/src/contribute/machine-learning/dl-systems/jax/jax/dist
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'run' from /home/dat/resources/src/contribute/machine-learning/dl-systems/jax/jax/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'run' from /home/dat/resources/src/contribute/machine-learning/dl-systems/jax/jax/.bazelrc:
  Inherited 'build' options: --repo_env PYTHON_BIN_PATH=/home/dat/frameworks/miniconda3/envs/jax/bin/python --action_env=PYENV_ROOT --python_path=/home/dat/frameworks/miniconda3/envs/jax/bin/python --repo_env TF_NEED_CUDA=1 --action_env TF_CUDA_COMPUTE_CAPABILITIES=3.5,5.2,6.0,6.1,7.0 --distinct_host_configuration=false -c opt --apple_platform_type=macos --macos_minimum_os=10.9 --announce_rc --define open_source_build=true --define=no_kafka_support=true --define=no_ignite_support=true --define=grpc_no_ares=true --spawn_strategy=standalone --strategy=Genrule=standalone --enable_platform_specific_config
INFO: Found applicable config definition build:short_logs in file /home/dat/resources/src/contribute/machine-learning/dl-systems/jax/jax/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:mkl_open_source_only in file /home/dat/resources/src/contribute/machine-learning/dl-systems/jax/jax/.bazelrc: --define=tensorflow_mkldnn_contraction_kernel=1
INFO: Found applicable config definition build:cuda in file /home/dat/resources/src/contribute/machine-learning/dl-systems/jax/jax/.bazelrc: --crosstool_top=@local_config_cuda//crosstool:toolchain --define=using_cuda=true --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:linux in file /home/dat/resources/src/contribute/machine-learning/dl-systems/jax/jax/.bazelrc: --copt=-Wno-sign-compare --define=no_aws_support=true --define=no_gcp_support=true --define=no_hdfs_support=true --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --copt=-Wno-stringop-truncation
Loading:
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
DEBUG: /home/dat/.cache/bazel/_bazel_dat/7a3b8e6abebe283be3e689daef6000a8/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:118:5:
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
Analyzing: target //build:build_wheel (1 packages loaded, 0 targets configured)
Analyzing: target //build:build_wheel (13 packages loaded, 15 targets configured)
Analyzing: target //build:build_wheel (84 packages loaded, 1381 targets configured)
Analyzing: target //build:build_wheel (147 packages loaded, 5767 targets configured)
Analyzing: target //build:build_wheel (151 packages loaded, 6872 targets configured)
Analyzing: target //build:build_wheel (151 packages loaded, 6872 targets configured)
INFO: Analyzed target //build:build_wheel (167 packages loaded, 13585 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /home/dat/.cache/bazel/_bazel_dat/7a3b8e6abebe283be3e689daef6000a8/sandbox
[4 / 325] [Prepa] BazelWorkspaceStatusAction stable-status.txt ... (5 actions, 0 running)
[3,989 / 10,224] Executing genrule @local_config_cuda//cuda:cuda-lib; 2s local ... (4 actions, 2 running)
[4,203 / 10,781] Compiling external/flatbuffers/grpc/src/compiler/go_generator.cc; 2s local ... (24 actions, 23 running)
[4,241 / 10,781] Compiling external/flatbuffers/src/idl_gen_cpp.cpp; 5s local ... (24 actions, 23 running)
[4,289 / 10,781] Compiling external/nccl_archive/src/collectives/device/sum_i8_reduce.cu.cc; 7s local ... (24 actions, 23 running)
[4,372 / 10,781] Compiling external/nccl_archive/src/collectives/device/sum_i8_reduce.cu.cc; 11s local ... (24 actions, 23 running)
[4,475 / 10,781] Compiling external/com_google_protobuf/src/google/protobuf/descriptor.cc; 11s local ... (24 actions, 23 running)
[4,538 / 10,781] Compiling external/nccl_archive/src/collectives/device/max_f32_all_reduce.cu.cc; 15s local ... (24 actions, 23 running)
[4,629 / 10,781] Compiling external/nccl_archive/src/collectives/device/max_f32_all_reduce.cu.cc; 22s local ... (24 actions, 23 running)
[4,709 / 10,781] Compiling external/nccl_archive/src/collectives/device/max_f32_all_reduce.cu.cc; 30s local ... (24 actions, 23 running)
[4,734 / 10,781] Compiling external/nccl_archive/src/collectives/device/max_f32_all_reduce.cu.cc; 39s local ... (24 actions running)
[4,758 / 10,781] Compiling external/nccl_archive/src/collectives/device/max_f32_all_reduce.cu.cc; 49s local ... (24 actions running)
[4,785 / 10,781] Compiling external/nccl_archive/src/collectives/device/sum_i32_all_reduce.cu.cc; 54s local ... (24 actions running)
[4,831 / 10,781] Compiling external/nccl_archive/src/collectives/device/sum_u32_all_reduce.cu.cc; 62s local ... (23 actions, 22 running)
[5,047 / 10,781] Compiling external/nccl_archive/src/collectives/device/prod_u8_all_reduce.cu.cc; 37s local ... (24 actions, 23 running)
[5,163 / 10,781] Compiling external/nccl_archive/src/collectives/device/prod_u8_all_reduce.cu.cc; 56s local ... (24 actions, 23 running)
[5,199 / 10,781] Compiling external/nccl_archive/src/collectives/device/prod_f16_all_reduce.cu.cc; 50s local ... (24 actions, 23 running)
[5,243 / 10,781] Compiling external/org_tensorflow/tensorflow/compiler/xla/service/cpu/runtime_matmul.cc; 57s local ... (24 actions, 23 running)
[5,301 / 10,781] Compiling external/org_tensorflow/tensorflow/compiler/xla/service/cpu/runtime_matmul.cc; 86s local ... (24 actions, 23 running)
[5,348 / 10,781] Compiling external/org_tensorflow/tensorflow/compiler/xla/service/cpu/runtime_matmul.cc; 119s local ... (24 actions, 23 running)
[5,412 / 10,781] Compiling external/org_tensorflow/tensorflow/compiler/xla/service/cpu/runtime_matmul.cc; 157s local ... (24 actions, 23 running)
[5,575 / 10,781] Compiling external/nccl_archive/src/collectives/device/max_u8_all_reduce.cu.cc; 50s local ... (24 actions, 23 running)
[5,999 / 10,781] Compiling external/nccl_archive/src/collectives/device/sum_u8_all_reduce.cu.cc; 61s local ... (24 actions, 23 running)
[6,617 / 10,782] Compiling external/flatbuffers/src/idl_parser.cpp; 11s local ... (24 actions, 23 running)
[7,234 / 10,782] Compiling external/llvm-project/llvm/utils/TableGen/CodeGenDAGPatterns.cpp; 13s local ... (24 actions, 23 running)
[8,155 / 10,782] Compiling external/llvm-project/llvm/lib/Analysis/ScalarEvolution.cpp; 15s local ... (24 actions, 23 running)
[8,467 / 10,782] Compiling external/llvm-project/llvm/lib/Transforms/IPO/WholeProgramDevirt.cpp; 11s local ... (24 actions, 23 running)
[8,783 / 10,782] Compiling external/llvm-project/llvm/lib/Passes/PassBuilder.cpp; 98s local ... (24 actions, 23 running)
[9,225 / 10,782] Compiling external/llvm-project/mlir/lib/Dialect/LLVMIR/IR/LLVMDialect.cpp; 24s local ... (24 actions, 23 running)
[9,845 / 10,782] Compiling external/org_tensorflow/tensorflow/compiler/xla/literal.cc; 38s local ... (24 actions, 23 running)
ERROR: /home/dat/.cache/bazel/_bazel_dat/7a3b8e6abebe283be3e689daef6000a8/external/org_tensorflow/tensorflow/core/common_runtime/BUILD:823:1: C++ compilation of rule '@org_tensorflow//tensorflow/core/common_runtime:hierarchical_tree_broadcaster' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /home/dat/.cache/bazel/_bazel_dat/7a3b8e6abebe283be3e689daef6000a8/execroot/__main__ && \
  exec env - \
    PATH=/home/dat/src/contribute/tools/vcpkg:/home/dat/frameworks/tensorswift/usr/bin:/home/dat/.cargo/bin:/home/dat/.nix-profile/bin:/home/linuxbrew/.linuxbrew/bin:/home/dat/.go/bin:/home/dat/.go_workspace/bin:/usr/local/cuda/bin:/home/dat/bin:/home/dat/.local/bin:/home/dat/frameworks/miniconda3/envs/jax/bin:/home/dat/frameworks/miniconda3/condabin:/home/dat/.cargo/bin:/home/dat/.local/bin:/home/dat/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/cuda/bin \
    PWD=/proc/self/cwd \
    TF_CUDA_COMPUTE_CAPABILITIES=3.5,5.2,6.0,6.1,7.0 \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/core/common_runtime/_objs/hierarchical_tree_broadcaster/hierarchical_tree_broadcaster.pic.d '-frandom-seed=bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/core/common_runtime/_objs/hierarchical_tree_broadcaster/hierarchical_tree_broadcaster.pic.o' -DTF_USE_SNAPPY -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' '-DEIGEN_HAS_TYPE_TRAITS=0' -DHAVE_SYS_UIO_H -D__CLANG_SUPPORT_DYN_ANNOTATION__ -iquote external/org_tensorflow -iquote bazel-out/k8-opt/bin/external/org_tensorflow -iquote external/com_google_absl -iquote bazel-out/k8-opt/bin/external/com_google_absl -iquote external/nsync -iquote bazel-out/k8-opt/bin/external/nsync -iquote external/eigen_archive -iquote bazel-out/k8-opt/bin/external/eigen_archive -iquote external/gif -iquote bazel-out/k8-opt/bin/external/gif -iquote external/libjpeg_turbo -iquote bazel-out/k8-opt/bin/external/libjpeg_turbo -iquote external/com_google_protobuf -iquote bazel-out/k8-opt/bin/external/com_google_protobuf -iquote external/zlib -iquote bazel-out/k8-opt/bin/external/zlib -iquote external/com_googlesource_code_re2 -iquote bazel-out/k8-opt/bin/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/k8-opt/bin/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/k8-opt/bin/external/fft2d -iquote external/highwayhash -iquote bazel-out/k8-opt/bin/external/highwayhash -iquote external/double_conversion -iquote bazel-out/k8-opt/bin/external/double_conversion -iquote external/snappy -iquote bazel-out/k8-opt/bin/external/snappy -iquote external/local_config_cuda -iquote bazel-out/k8-opt/bin/external/local_config_cuda -iquote external/local_config_tensorrt -iquote bazel-out/k8-opt/bin/external/local_config_tensorrt -Ibazel-out/k8-opt/bin/external/local_config_cuda/cuda/_virtual_includes/cuda_headers_virtual -Ibazel-out/k8-opt/bin/external/local_config_tensorrt/_virtual_includes/tensorrt_headers -isystem external/nsync/public -isystem bazel-out/k8-opt/bin/external/nsync/public -isystem external/eigen_archive -isystem bazel-out/k8-opt/bin/external/eigen_archive -isystem external/gif -isystem bazel-out/k8-opt/bin/external/gif -isystem external/com_google_protobuf/src -isystem bazel-out/k8-opt/bin/external/com_google_protobuf/src -isystem external/zlib -isystem bazel-out/k8-opt/bin/external/zlib -isystem external/farmhash_archive/src -isystem bazel-out/k8-opt/bin/external/farmhash_archive/src -isystem external/double_conversion -isystem bazel-out/k8-opt/bin/external/double_conversion -isystem external/local_config_cuda/cuda -isystem bazel-out/k8-opt/bin/external/local_config_cuda/cuda -isystem external/local_config_cuda/cuda/cuda/include -isystem bazel-out/k8-opt/bin/external/local_config_cuda/cuda/cuda/include -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fPIC -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -fno-omit-frame-pointer -no-canonical-prefixes -fno-canonical-system-headers -DNDEBUG -g0 -O2 -ffunction-sections -fdata-sections -Wno-sign-compare -Wno-stringop-truncation '-std=c++14' -DEIGEN_AVOID_STL_ARRAY -Iexternal/gemmlowp -Wno-sign-compare '-ftemplate-depth=900' -fno-exceptions '-DGOOGLE_CUDA=1' '-DTENSORFLOW_USE_NVCC=1' -msse3 -DTENSORFLOW_MONOLITHIC_BUILD -pthread -c external/org_tensorflow/tensorflow/core/common_runtime/hierarchical_tree_broadcaster.cc -o bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/core/common_runtime/_objs/hierarchical_tree_broadcaster/hierarchical_tree_broadcaster.pic.o)
Execution platform: @local_execution_config_platform//:platform
In file included from external/org_tensorflow/tensorflow/core/platform/protobuf.h:32,
                 from external/org_tensorflow/tensorflow/core/platform/tensor_coding.h:23,
                 from external/org_tensorflow/tensorflow/core/framework/resource_handle.h:21,
                 from external/org_tensorflow/tensorflow/core/framework/types.h:31,
                 from external/org_tensorflow/tensorflow/core/framework/tensor.h:26,
                 from external/org_tensorflow/tensorflow/core/framework/device_base.h:26,
                 from external/org_tensorflow/tensorflow/core/framework/collective.h:22,
                 from external/org_tensorflow/tensorflow/core/common_runtime/base_collective_executor.h:22,
                 from external/org_tensorflow/tensorflow/core/common_runtime/hierarchical_tree_broadcaster.h:20,
                 from external/org_tensorflow/tensorflow/core/common_runtime/hierarchical_tree_broadcaster.cc:15:
external/com_google_protobuf/src/google/protobuf/descriptor.pb.h:5287:3: internal compiler error: Segmentation fault
 5287 |   }
      |   ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-10/README.Bugs> for instructions.
Target //build:build_wheel failed to build
INFO: Elapsed time: 1077.715s, Critical Path: 161.01s
INFO: 5849 processes: 5849 local.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "build/build.py", line 466, in <module>
    main()
  File "build/build.py", line 461, in main
    shell(command)
  File "build/build.py", line 51, in shell
    output = subprocess.check_output(cmd)
  File "/home/dat/frameworks/miniconda3/envs/jax/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/dat/frameworks/miniconda3/envs/jax/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['./bazel-3.1.0-linux-x86_64', 'run', '--verbose_failures=true', '--config=short_logs', '--config=mkl_open_source_only', '--config=cuda', '--define=xla_python_enable_gpu=true', ':build_wheel', '--', '--output_path=/home/dat/resources/src/contribute/machine-learning/dl-systems/jax/jax/dist']' returned non-zero exit status 1.
```

# Steps to reproduce:

```
git clone https://github.com/google/jax/ && cd jax
git checkout jax-v0.2.7
conda create -n jax Python=3.8
conda install numpy scipy six wheel
python build/build.py --enable_cuda
```

The build works well without the `enable_cuda` flag.

```
(jax) ➜  jax git:(27a4c888) nvidia-smi
Mon Jan  4 00:07:48 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.38       Driver Version: 455.38       CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:0B:00.0 Off |                  N/A |
| 30%   34C    P8     8W / 300W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:43:00.0  On |                  N/A |
| 30%   36C    P8    41W / 300W |    882MiB / 11016MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Comment by hawkinsp** [comment]
This is a bug in your compiler (gcc). I suggest trying a different (newer?) version; if it still occurs with an up-to-date gcc, you should probably report a bug to them. I don't think there's much we can do on our end to fix it. Hope that helps!

**Comment by tataudat** [comment]
Run the build with `python build/build.py --enable_cuda --enable_march_native` solves the issue for me.

**Comment by hayday100** [comment]
Make sure to download/clone the new branch https://github.com/google/jax/tree/jaxlib-v0.1.59 and the problem should be fixed.
