### ISSUE TITLE
Tap function crashes when passed no arguments

### ISSUE THREAD

**Issue by NeilGirdhar** [google/jax#5414]
```python
from typing import Any, Tuple

from jax.experimental.host_callback import id_tap
from jax.lax import scan
from tjax import TapFunctionTransforms


def tap_function(_: None, transforms: TapFunctionTransforms) -> None:
    pass

def f(state: None, x: None) -> Tuple[None, Any]:
    trajectory = 1.0
    trajectory = id_tap(tap_function, None, result=trajectory)  # Passing in 0 instead of None stifles the error.
    return None, trajectory

print(scan(f, None, None, 10))
```
produces
```
Traceback (most recent call last):
  File "/home/neil/src/a.py", line 13, in <module>
    print(scan(f, None, None, 10))
  File "/home/neil/src/jax/jax/_src/lax/control_flow.py", line 1266, in scan
    init_flat, carry_avals, carry_avals_out, init_tree, *rest = _create_jaxpr(init)
  File "/home/neil/src/jax/jax/_src/lax/control_flow.py", line 1253, in _create_jaxpr
    jaxpr, consts, out_tree = _initial_style_jaxpr(f, in_tree, carry_avals + x_avals)
  File "/home/neil/src/jax/jax/_src/lax/control_flow.py", line 72, in _initial_style_jaxpr
    jaxpr, consts, out_tree = _initial_style_open_jaxpr(fun, in_tree, in_avals)
  File "/home/neil/src/jax/jax/_src/lax/control_flow.py", line 67, in _initial_style_open_jaxpr
    jaxpr, _, consts = pe.trace_to_jaxpr_dynamic(wrapped_fun, in_avals)
  File "/home/neil/src/jax/jax/interpreters/partial_eval.py", line 1191, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, main, in_avals)
  File "/home/neil/src/jax/jax/interpreters/partial_eval.py", line 1201, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers)
  File "/home/neil/src/jax/jax/linear_util.py", line 160, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/neil/src/a.py", line 11, in f
    id_tap(tap_function, None, result=trajectory)
  File "/home/neil/src/jax/jax/experimental/host_callback.py", line 464, in id_tap
    assert call_flat_results
AssertionError
```

**Comment by NeilGirdhar** [comment]
(@gnecula )

**Comment by NeilGirdhar** [comment]
Also, when should I prefer to use `id_tap` versus `call`?

**Comment by gnecula** [comment]
When you need a result from the callback, you must use `call`. When  you need to support JAX transformations, you must use `id_tap` (except for custom AD as explained in the docstring); `id_tap` and `id_print` are sometimes used to see the effect of transformations. If you do not need transforms and do not need the result from the callback, you can use either (they will be implemented the same way under the hood) but it is probably easier to use `id_tap` because you do not need to declare anything about the expected result.

**Comment by NeilGirdhar** [comment]
Thanks again for the quick fix, and the great explanation.   `id_tap` has allowed me to build a very useful progress bar,  and `id_print` has been critical in my debugging!
