### ISSUE TITLE
eval_shape with function as argument

### ISSUE THREAD

**Issue by PhilipVinc** [google/jax#5503]
currently it is not possible to pass to `eval_shape` arguments which are function themselves, even though it technically could work.

example:

```python
>>> import jax
>>> def f(x): 
...   return x+1
... 
>>> def g(fun, x):
...   return fun(x)
... 
>>> g(f, 1)
2
>>> jax.eval_shape(g, f, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.8/site-packages/jax/api.py", line 2307, in eval_shape
    *map(abstractify, args_flat))
  File "/Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.8/site-packages/jax/_src/util.py", line 37, in safe_map
    return list(map(f, *args))
  File "/Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.8/site-packages/jax/api.py", line 2303, in abstractify
    return ShapedArray(np.shape(x), dtypes.result_type(x))
  File "/Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.8/site-packages/jax/dtypes.py", line 305, in result_type
    return canonicalize_dtype(dtype(args[0]))
  File "/Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.8/site-packages/jax/dtypes.py", line 299, in dtype
    return np.result_type(x)
  File "<__array_function__ internals>", line 5, in result_type
TypeError: Cannot interpret '<function f at 0x15dd5a820>' as a data type
>>> 
```

**Comment by froystig** [comment]
This follows the behavior of several other main API functions, which only support arguments with shape/dtype fields (or, more generally, pytrees thereof). It's an intentional convention: the caller can best tie in all other types of arguments as needed. For instance, in the case of your example:

```python
>>> from functools import partial
>>> jax.eval_shape(partial(g, f), 1)
ShapeDtypeStruct(shape=(), dtype=int32)
```

I'll close this but please feel to reopen if you think there's a separate reason for it that we're overlooking.
