### ISSUE TITLE
ImportError: cannot import name 'xla_client' from 'jaxlib' (unknown location)

### ISSUE THREAD

**Issue by VladPerervenko** [google/jax#5800]
Building jaxlib [from source](https://jax.readthedocs.io/en/latest/developer.html#additional-notes-for-building-jaxlib-from-source-on-windows) on Windows.
Installation sequence as [here](https://www.msys2.org/) and [here](https://github.com/bazelbuild/bazel/releases) 

- PowerShell: https://github.com/PowerShell/PowerShell/releases/tag/v7.1.2
- Bazel: https://github.com/bazelbuild/bazel/releases
- MSYS2: https://repo.msys2.org/distrib/x86_64/msys2-x86_64-20210105.exe
- Check if there is pacman in PATH
- Install patch realpath: pacman -S patch realpath
- Check that the PATH contains bazel, path, realpath
- Clone the repository: git clone https://github.com/google/jax
- We go to the directory
- Activating the conda environment: conda activate
- Trying to build jaxlib: python. \ Build \ build.py
- If so, install jax: pip install -e.

Trying to run the package in Python
`>>> import jax.numpy as jnp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\bin\jax\jax\__init__.py", line 22, in <module>
    from .api import (
  File "c:\bin\jax\jax\api.py", line 39, in <module>
    from . import core
  File "c:\bin\jax\jax\core.py", line 31, in <module>
    from . import dtypes
  File "c:\bin\jax\jax\dtypes.py", line 32, in <module>
    from .lib import xla_client
  File "c:\bin\jax\jax\lib\__init__.py", line 53, in <module>
    from jaxlib import xla_client
ImportError: cannot import name 'xla_client' from 'jaxlib' (unknown location)`
But xla_client it is C:\bin\jax\bazel-jax\external\org_tensorflow\tensorflow\compiler\xla\python\xla_client.py
And how to introduce them? Where is the mistake?
Sys.info()
       sysname        release        version       nodename        machine 
     "Windows"       "10 x64"  "build 19042"  "VLAD-MASTER"       "x86-64"

**Comment by hawkinsp** [comment]
Did you install the `jaxlib` you built?

You need to `pip install dist/jaxlib*.whl` in your `jaxlib` directory.

**Comment by VladPerervenko** [comment]
Thank. I will try.

**Comment by VladPerervenko** [comment]
- "Did you install the jaxlib you built?"
 Look at the logs and tell me where I am from jaxlib. 
[instal_jax.txt](https://github.com/google/jax/files/6036083/instal_jax.txt)
[cla_client_test.txt](https://github.com/google/jax/files/6036085/cla_client_test.txt)
