### ISSUE TITLE
jax.scipy.special.logsumexp raises OverflowError

### ISSUE THREAD

**Issue by neelnanda-io** [google/jax#5931]
`jax.scipy.special.logsumexp` seems to be broken in jax 0.2.9.

The following code:
```
import jax, scipy
print(jax.scipy.special.logsumexp(jax.numpy.array([-1, 1])))
print(scipy.special.logsumexp(jax.numpy.array([-1, 1])))
```

Raises the following error:
```Traceback (most recent call last):
  File "txt.py", line 2, in <module>
    print(jax.scipy.special.logsumexp(jax.numpy.array([-1, 1])))
  File "/opt/conda/lib/python3.7/site-packages/jax/_src/scipy/special.py", line 107, in logsumexp
    amax = lax.reduce(a, _constant_like(a, -np.inf), lax.max, dims)
  File "/opt/conda/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 335, in _constant_like
    return np.array(const, dtype=_dtype(x))
OverflowError: cannot convert float infinity to integer```

While the line from scipy runs fine. This was reproduced for the handful of other inputs I tried

**Comment by clemisch** [comment]
`jax.scipy.special.logsumexp` does not work on integers. If you use floats like

```python
jax.scipy.special.logsumexp(jax.numpy.array([-1., 1.]))
# -> DeviceArray(1.1269281, dtype=float32)
```

it works. You may still consider this a bug, just FYI.

**Comment by jakevdp** [comment]
Thanks for the report. Indeed I think the issue is that `logsumexp` currently fails for integer input (although the error is more explicit on master due to changes in #5872). The fix will be to internally promote inputs to floating point.
