### ISSUE TITLE
Errror with gpu pip install - ImportError: libcusolver.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Razcle** [google/jax#602]
Hi,

I tried to install jax and jaxlib on Ubuntu 18.04. The installation seemed to go fine but when I import jax I get the following error:

'''
>>> import jax
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/raza/miniconda3/envs/jax/lib/python3.6/site-packages/jax/__init__.py", line 19, in <module>
    from jax.api import *
  File "/home/raza/miniconda3/envs/jax/lib/python3.6/site-packages/jax/api.py", line 46, in <module>
    from .lib.xla_bridge import canonicalize_dtype, device_count
  File "/home/raza/miniconda3/envs/jax/lib/python3.6/site-packages/jax/lib/xla_bridge.py", line 33, in <module>
    import jaxlib
  File "/home/raza/miniconda3/envs/jax/lib/python3.6/site-packages/jaxlib/__init__.py", line 15, in <module>
    from . import xla_client
  File "/home/raza/miniconda3/envs/jax/lib/python3.6/site-packages/jaxlib/xla_client.py", line 38, in <module>
    from . import pywrap_xla as c_api
  File "/home/raza/miniconda3/envs/jax/lib/python3.6/site-packages/jaxlib/pywrap_xla.py", line 28, in <module>
    _pywrap_xla = swig_import_helper()
  File "/home/raza/miniconda3/envs/jax/lib/python3.6/site-packages/jaxlib/pywrap_xla.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_xla', fp, pathname, description)
  File "/home/raza/miniconda3/envs/jax/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/raza/miniconda3/envs/jax/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcusolver.so.9.0: cannot open shared object file: No such file or directory'''

cuda version 9.0
cudnn version 7.5

I installed using the following short script:

'''
#!/bin/bash
PYTHON_VERSION=cp36  # alternatives: cp27, cp35, cp36, cp37
CUDA_VERSION=cuda90  # alternatives: cuda90, cuda92, cuda100
PLATFORM=linux_x86_64  # alternatives: linux_x86_64
BASE_URL='https://storage.googleapis.com/jax-wheels'
pip install --upgrade $BASE_URL/$CUDA_VERSION/jaxlib-0.1.12-$PYTHON_VERSION-none-$PLATFORM.whl

pip install --upgrade jax  # install jax 
'''
would appreciate any advice If I'm doing something wrong, thanks!

**Comment by Razcle** [comment]
Found the problem. I hadn't set the LD_LIBRARY_PATH environment variable correctly.

**Comment by mattjj** [comment]
Glad to see you're working with JAX :)
