### ISSUE TITLE
0.2.9 fails: ModuleNotFoundError: No module named 'jaxlib'

### ISSUE THREAD

**Issue by yurivict** [google/jax#6071]
```
Python 3.7.9 (default, Dec 12 2020, 01:25:17) 
[Clang 8.0.1 (tags/RELEASE_801/final 366581)] on freebsd12
Type "help", "copyright", "credits" or "license" for more information.
```

These lines:
```
import jax.numpy as jnp
from jax import grad, jit, vmap
```
fail:
```
$ python3.7 j.py 
Traceback (most recent call last):
  File "j.py", line 1, in <module>
    import jax.numpy as jnp
  File "/usr/local/lib/python3.7/site-packages/jax/__init__.py", line 22, in <module>
    from .api import (
  File "/usr/local/lib/python3.7/site-packages/jax/api.py", line 39, in <module>
    from . import core
  File "/usr/local/lib/python3.7/site-packages/jax/core.py", line 31, in <module>
    from . import dtypes
  File "/usr/local/lib/python3.7/site-packages/jax/dtypes.py", line 32, in <module>
    from .lib import xla_client
  File "/usr/local/lib/python3.7/site-packages/jax/lib/__init__.py", line 23, in <module>
    import jaxlib
ModuleNotFoundError: No module named 'jaxlib'
```

installed from the FreeBSD port
OS: FreeBSD 12.2

Downstream bug report: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=252871

**Comment by jakevdp** [comment]
Installing `jax` does not automatically install `jaxlib`; you'll need to separately install `jaxlib` in order to use JAX.

The reason `jaxlib` is not listed as a requirement is because you need different flavors of jaxlib depending on what chip and drivers you plan to use, and Python's dependency specification system does not have the granularity to allow for that.

**Comment by yurivict** [comment]
What is the easiest way to build ```jaxlib``` for CPU?

**Comment by jakevdp** [comment]
There is information on this at [Building JAX From Source](https://jax.readthedocs.io/en/latest/developer.html#building-from-source).
