### ISSUE TITLE
astype('float16') failure

### ISSUE THREAD

**Issue by nottombrown** [google/jax#616]
## Minimal reproduction
Running the following
```python
import jax.numpy as np
x = np.ones([1], dtype='float32')
x = x.astype('float16')
print(x)
```

Gives an error
```
Traceback (most recent call last):
  File "trax/float16_test.py", line 32, in <module>
    test_print_fp32_to_fp16_cast()
  File "trax/float16_test.py", line 25, in test_print_fp32_to_fp16_cast
    print(x)  # FAILS
  File "/root/code/jax/jax/interpreters/xla.py", line 322, in forward_method
    return fun(getattr(self, attrname), *args)
  File "/root/code/jax/jax/interpreters/xla.py", line 341, in _value
    self._npy_value = self.device_buffer.to_py()
  File "/opt/conda/lib/python3.6/site-packages/jaxlib/xla_client.py", line 327, in to_py
    return self.c_buffer.ToPython()
  File "/opt/conda/lib/python3.6/site-packages/numpy/core/_internal.py", line 598, in _dtype_from_pep3118
    dtype, align = __dtype_from_pep3118(stream, is_subdtype=False)
  File "/opt/conda/lib/python3.6/site-packages/numpy/core/_internal.py", line 675, in __dtype_from_pep3118
    raise ValueError("Unknown PEP 3118 data type specifier %r" % stream.s)
ValueError: Unknown PEP 3118 data type specifier 'oat16'
```

Looks like the dtype is being truncated somehow?

## Other tests
```python
import jax.numpy as np


def test_print_fp16_no_cast():
    x = np.ones([1], dtype='float16')
    print(x)  # FAILS


def test_print_fp16():
    x = np.ones([1], dtype='float16')
    x = x.astype('float16')
    print(x)  # OK


def test_print_fp32():
    x = np.ones([1], dtype='float16')
    x = x.astype('float16')
    x = x.astype('float32')
    print(x)  # OK


def test_print_fp32_to_fp16_cast():
    x = np.ones([1], dtype='float32')
    x = x.astype('float16')
    print(x)  # FAILS


if __name__ == '__main__':
    test_print_fp32()
    test_print_fp16_no_cast()
    test_print_fp16()
    test_print_fp32_to_fp16_cast()
```
All but the first work for me

### Build details
I built `master` on commit `bc4d1fc` on an ubuntu box

**Comment by hawkinsp** [comment]
Thanks for the report. Our float16 support is minimally tested, but this looks easy enough to fix. I think this is a recent regression; at master we switched to using pybind11 as the Python binding framework instead of SWIG.

If you plan to use float16, we should also test it as part of our test suite. Is float16 support a high priority for you?

**Comment by nottombrown** [comment]
Thanks for the quick response. Support for float16 is quite important to me because I'd like to train large models, and using tensorcores on a V100 gives me roughly a 3x throughput improvement on my workload.

**Comment by hawkinsp** [comment]
Ok, I've fixed the specific problem you identified. A jaxlib rebuild is needed.

I filed https://github.com/google/jax/issues/618 for improving the float16 test coverage. Please let us know if you hit any more issues.
