### ISSUE TITLE
"Could not find any cudnn.h" when building from source

### ISSUE THREAD

**Issue by nottombrown** [google/jax#627]
Starting on commit https://github.com/google/jax/commit/60d7198381db2098c3319c01ba8060bad9a14422 I get the following error when building with cuda support. Commits before that build correctly.

```
$ python build/build.py --enable_cuda

     _   _  __  __
    | | / \ \ \/ /
 _  | |/ _ \ \  /
| |_| / ___ \/  \
 \___/_/   \/_/\_\


Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Bazel binary path: ./bazel-0.24.0-linux-x86_64
Python binary path: /opt/conda/bin/python
MKL-DNN enabled: yes
-march=native: no
CUDA enabled: yes
CUDA toolkit path: /usr/local/cuda
CUDNN library path: /usr/local/cuda

Building XLA and installing it in the jaxlib source tree...
ERROR: /root/code/jax/build/BUILD.bazel:21:1: error loading package '@org_tensorflow//tensorflow/compiler/xla/python': in /root/.cache/bazel/_bazel_root/180cc62733246893a6f39cd7c8b63394/external/org_tensorflow/tensorflow/compiler/xla/xla.bzl: Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/180cc62733246893a6f39cd7c8b63394/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1253
		_create_local_cuda_repository(repository_ctx)
	File "/root/.cache/bazel/_bazel_root/180cc62733246893a6f39cd7c8b63394/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 956, in _create_local_cuda_repository
		_get_cuda_config(repository_ctx)
	File "/root/.cache/bazel/_bazel_root/180cc62733246893a6f39cd7c8b63394/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 688, in _get_cuda_config
		find_cuda_config(repository_ctx, ["cuda", "cudnn"])
	File "/root/.cache/bazel/_bazel_root/180cc62733246893a6f39cd7c8b63394/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 668, in find_cuda_config
		auto_configure_fail(("Failed to run find_cuda_config...))
	File "/root/.cache/bazel/_bazel_root/180cc62733246893a6f39cd7c8b63394/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 274, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Failed to run find_cuda_config.py: Could not find any cudnn.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        '/usr/local/cuda'

 and referenced by '//build:install_xla_in_source_tree'
ERROR: Analysis of target '//build:install_xla_in_source_tree' failed; build aborted: error loading package '@org_tensorflow//tensorflow/compiler/xla/python': in /root/.cache/bazel/_bazel_root/180cc62733246893a6f39cd7c8b63394/external/org_tensorflow/tensorflow/compiler/xla/xla.bzl: Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/180cc62733246893a6f39cd7c8b63394/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1253
		_create_local_cuda_repository(repository_ctx)
	File "/root/.cache/bazel/_bazel_root/180cc62733246893a6f39cd7c8b63394/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 956, in _create_local_cuda_repository
		_get_cuda_config(repository_ctx)
	File "/root/.cache/bazel/_bazel_root/180cc62733246893a6f39cd7c8b63394/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 688, in _get_cuda_config
		find_cuda_config(repository_ctx, ["cuda", "cudnn"])
	File "/root/.cache/bazel/_bazel_root/180cc62733246893a6f39cd7c8b63394/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 668, in find_cuda_config
		auto_configure_fail(("Failed to run find_cuda_config...))
	File "/root/.cache/bazel/_bazel_root/180cc62733246893a6f39cd7c8b63394/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 274, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Failed to run find_cuda_config.py: Could not find any cudnn.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        '/usr/local/cuda'
```

**Comment by nottombrown** [comment]
I think that this could be something like the new XLA version needing different flags / locations of cuda headers?

**Comment by hawkinsp** [comment]
I think TensorFlow changed how it finds CUDA.

Try this patch. It removes the `--cudnn_path` option and lets TF's logic find CuDNN automatically.
https://gist.github.com/hawkinsp/29139c1edfa60e7ddaea8143fdcbcb5e

(In general our `jaxlib"` build does unusual things with the TF build process to build XLA. We should probably move the `jaxlib` build entirely into the XLA tree so we aren't as prone to this kind of breakage. `jaxlib` is really `xlapy` anyway.)

**Comment by pskrunner14** [comment]
> I think TensorFlow changed how it finds CUDA.
> 
> Try this patch. It removes the `--cudnn_path` option and lets TF's logic find CuDNN automatically.
> https://gist.github.com/hawkinsp/29139c1edfa60e7ddaea8143fdcbcb5e
> 
> (In general our `jaxlib"` build does unusual things with the TF build process to build XLA. We should probably move the `jaxlib` build entirely into the XLA tree so we aren't as prone to this kind of breakage. `jaxlib` is really `xlapy` anyway.)

Worked for me!

**Comment by jey07** [comment]
Can someone tell me how to apply this patch ?

**Comment by CharlesJQuarra** [comment]
this simple fix was never pushed to main, so I don't really understand what development process would close this issue. Also this patch will not apply to the `master` version of `build/build.py`, which still has several references to `cudnn_install_path`

Please reopen this issue to avoid opening a new one

**Comment by hawkinsp** [comment]
Please open a new issue. I don't think this is the same problem.
a) if you haven't considered it, you should prefer to use a prebuilt jaxlib.
b) everything that patch did is present in master (i.e., `--cudnn_path` is optional, and if you don't specify it, it acts the same way as that patch did.)
