### ISSUE TITLE
IPython: stack traces are so large, terminal cuts them off

### ISSUE THREAD

**Issue by aterenin** [google/jax#6271]
Hi all

I'm working with a reinforcement learning codebase which generates stack traces that are so large, it is not possible to scroll through them in full because the terminal window scroll bar runs out. This is caused by a large set of JAX-internal frames which get printed at the end.

I therefore suggest not printing JAX-internal stack frames by default, unless the user enables this by setting an appropriate option or environment variable.

**Comment by froystig** [comment]
Our stack trace filtering machinery only adds information (namely, it appends a custom exception to any raised exception's cause chain). It doesn't control how anything is displayed downstream.

Perhaps you would like to specially handle exception formatting/display in your application? Our filtered-traceback exception is reachable from one that you catch (follow `e.__cause__` for an exception `e`). For anything more complex, Python has [utilities](https://docs.python.org/3/library/traceback.html) for traversing and formatting exception chains.

**Comment by hawkinsp** [comment]
Good news! We've recently flipped the order of the filtered and unfiltered stack frames.

This should mean the more useful (filtered) part of the stack trace is at the bottom, and should not scroll off the screen.

Here's an example, at `jax` and `jaxlib` head:
```
Traceback (most recent call last):
  File "/Users/phawkins/p/jax/t.py", line 13, in <module>
    print(f(3))
  File "/Users/phawkins/p/jax/jax/_src/traceback_util.py", line 143, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/phawkins/p/jax/jax/_src/api.py", line 425, in cache_miss
    out_flat = xla.xla_call(
  File "/Users/phawkins/p/jax/jax/core.py", line 1558, in bind
    return call_bind(self, fun, *args, **params)
  File "/Users/phawkins/p/jax/jax/core.py", line 1549, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/Users/phawkins/p/jax/jax/core.py", line 1561, in process
    return trace.process_call(self, fun, tracers, params)
  File "/Users/phawkins/p/jax/jax/core.py", line 606, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/Users/phawkins/p/jax/jax/interpreters/xla.py", line 582, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, name, donated_invars,
  File "/Users/phawkins/p/jax/jax/linear_util.py", line 262, in memoized_fun
    ans = call(fun, *args)
  File "/Users/phawkins/p/jax/jax/interpreters/xla.py", line 657, in _xla_callable
    jaxpr, out_avals, consts = pe.trace_to_jaxpr_final(
  File "/Users/phawkins/p/jax/jax/interpreters/partial_eval.py", line 1284, in trace_to_jaxpr_final
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, main, in_avals)
  File "/Users/phawkins/p/jax/jax/interpreters/partial_eval.py", line 1262, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers)
  File "/Users/phawkins/p/jax/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/phawkins/p/jax/t.py", line 5, in f
    return g(x) + 1
  File "/Users/phawkins/p/jax/jax/_src/traceback_util.py", line 143, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/phawkins/p/jax/jax/_src/api.py", line 425, in cache_miss
    out_flat = xla.xla_call(
  File "/Users/phawkins/p/jax/jax/core.py", line 1558, in bind
    return call_bind(self, fun, *args, **params)
  File "/Users/phawkins/p/jax/jax/core.py", line 1549, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/Users/phawkins/p/jax/jax/core.py", line 1561, in process
    return trace.process_call(self, fun, tracers, params)
  File "/Users/phawkins/p/jax/jax/interpreters/partial_eval.py", line 1072, in process_call
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(f, self.main, in_avals)
  File "/Users/phawkins/p/jax/jax/interpreters/partial_eval.py", line 1262, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers)
  File "/Users/phawkins/p/jax/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/phawkins/p/jax/t.py", line 9, in g
    raise ValueError("yo")
jax._src.traceback_util.UnfilteredStackTrace: ValueError: yo

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/phawkins/p/jax/t.py", line 13, in <module>
    print(f(3))
  File "/Users/phawkins/p/jax/t.py", line 5, in f
    return g(x) + 1
  File "/Users/phawkins/p/jax/t.py", line 9, in g
    raise ValueError("yo")
ValueError: yo
```

We could optionally not include the `UnfilteredStackTrace` at all, but I'm hesitant to discard this kind of information completely. At least this way it won't scroll off the screen.

I think we can consider this issue fixed?

**Comment by aterenin** [comment]
Awesome!

I would further suggest adding a config option to remove the UnfilteredStackTrace, perhaps enabled by default. That way the information is discarded unless the user is debugging the JAX library itself and requests it.
