### ISSUE TITLE
Error in custom JVP involving tokens

### ISSUE THREAD

**Issue by dionhaefner** [google/jax#6285]
In `mpi4jax`, we encountered some errors when working with gradients of primitives that use tokens.

### Issue 1

The following throws an error:

```python
from mpi4py import MPI
import jax
import jax.numpy as jnp
import mpi4jax

comm = MPI.COMM_WORLD

def foo(x, token):
    token = jax.lax.create_token()
    x1, token = mpi4jax.allreduce(x, op=MPI.SUM, comm=comm, token=token)
    x2, token = mpi4jax.allreduce(x, op=MPI.SUM, comm=comm, token=token)
    return x1 + x2

x = 0.0
gfoo = jax.grad(foo)
gx = gfoo(x)
```

Traceback:

```python
Traceback (most recent call last):
  File "bug.py", line 18, in <module>
    gx = gfoo(x)
jax._src.traceback_util.FilteredStackTrace: AssertionError

The stack trace above excludes JAX-internal frames.
The following is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bug.py", line 18, in <module>
    gx = gfoo(x)
  File "/Users/dion/.virtualenvs/mpi4jax/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 139, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/dion/.virtualenvs/mpi4jax/lib/python3.8/site-packages/jax/api.py", line 760, in grad_f
    _, g = value_and_grad_f(*args, **kwargs)
  File "/Users/dion/.virtualenvs/mpi4jax/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 139, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/dion/.virtualenvs/mpi4jax/lib/python3.8/site-packages/jax/api.py", line 823, in value_and_grad_f
    ans, vjp_py = _vjp(f_partial, *dyn_args)
  File "/Users/dion/.virtualenvs/mpi4jax/lib/python3.8/site-packages/jax/api.py", line 1896, in _vjp
    out_primal, out_vjp = ad.vjp(flat_fun, primals_flat)
  File "/Users/dion/.virtualenvs/mpi4jax/lib/python3.8/site-packages/jax/interpreters/ad.py", line 114, in vjp
    out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
  File "/Users/dion/.virtualenvs/mpi4jax/lib/python3.8/site-packages/jax/interpreters/ad.py", line 103, in linearize
    assert all(out_primal_pval.is_known() for out_primal_pval in out_primals_pvals)
AssertionError
```

This is an abridged version of our custom JVP:

```python
def mpi_allreduce_value_and_jvp(in_args, tan_args, op, comm, transpose):
    x, token = in_args
    x_tan, _ = tan_args

    # sum x across all ranks
    val, token = mpi_allreduce_p.bind(x, token, op=op, comm=comm, transpose=transpose)

    # sum of x_tan across all ranks
    jvp, token = mpi_allreduce_p.bind(x_tan, token, op=op, comm=comm, transpose=transpose)

    return (val, token), (jvp, ad.Zero.from_value(token))
```

### Issue 2

The error above doesn't occur when I generate a new token before every call:

```python
def foo(x):
    token = jax.lax.create_token()
    x1, token = mpi4jax.allreduce(x, op=MPI.SUM, comm=comm, token=token)
    token = jax.lax.create_token()
    x2, token = mpi4jax.allreduce(x, op=MPI.SUM, comm=comm, token=token)
    return x1 + x2
```

(of course this gives bogus results now, just for illustration)

But now, I get a different error:

```python
Traceback (most recent call last):
  File "bug.py", line 19, in <module>
    gx = gfoo(x)
jax._src.traceback_util.FilteredStackTrace: KeyError: <class 'jax.interpreters.xla.Token'>

The stack trace above excludes JAX-internal frames.
The following is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bug.py", line 19, in <module>
    gx = gfoo(x)
  File "/Users/dion/.virtualenvs/mpi4jax/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 139, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/dion/.virtualenvs/mpi4jax/lib/python3.8/site-packages/jax/api.py", line 760, in grad_f
    _, g = value_and_grad_f(*args, **kwargs)
  File "/Users/dion/.virtualenvs/mpi4jax/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 139, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/dion/.virtualenvs/mpi4jax/lib/python3.8/site-packages/jax/api.py", line 829, in value_and_grad_f
    g = vjp_py(np.ones((), dtype=dtype))
  File "/Users/dion/.virtualenvs/mpi4jax/lib/python3.8/site-packages/jax/api.py", line 1816, in _vjp_pullback_wrapper
    ans = fun(*args)
  File "/Users/dion/.virtualenvs/mpi4jax/lib/python3.8/site-packages/jax/interpreters/ad.py", line 121, in unbound_vjp
    arg_cts = backward_pass(jaxpr, consts, dummy_args, cts)
  File "/Users/dion/.virtualenvs/mpi4jax/lib/python3.8/site-packages/jax/interpreters/ad.py", line 231, in backward_pass
    map(partial(write_cotangent, eqn.primitive), eqn.invars, cts_out)
  File "/Users/dion/.virtualenvs/mpi4jax/lib/python3.8/site-packages/jax/_src/util.py", line 41, in safe_map
    return list(map(f, *args))
  File "/Users/dion/.virtualenvs/mpi4jax/lib/python3.8/site-packages/jax/interpreters/ad.py", line 176, in write_cotangent
    ct_env[v] = add_tangents(ct_env[v], ct) if v in ct_env else ct
  File "/Users/dion/.virtualenvs/mpi4jax/lib/python3.8/site-packages/jax/interpreters/ad.py", line 482, in add_tangents
    return add_jaxvals(x, y)
  File "/Users/dion/.virtualenvs/mpi4jax/lib/python3.8/site-packages/jax/ad_util.py", line 37, in add_jaxvals
    return add_jaxvals_p.bind(x, y)
  File "/Users/dion/.virtualenvs/mpi4jax/lib/python3.8/site-packages/jax/core.py", line 284, in bind
    out = top_trace.process_primitive(self, tracers, params)
  File "/Users/dion/.virtualenvs/mpi4jax/lib/python3.8/site-packages/jax/core.py", line 622, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/Users/dion/.virtualenvs/mpi4jax/lib/python3.8/site-packages/jax/ad_util.py", line 44, in add_impl
    return jaxval_adders[type(xs)](xs, ys)
KeyError: <class 'jax.interpreters.xla.Token'>
```

It looks like the tangent accumulator is trying to add the input tokens.

**Comment by froystig** [comment]
Looking at your "issue 1" setup it seems the definition of `foo` is not intended to take a `token` argument (typo?). I'll assume that, but please correct otherwise.

Also, by "custom JVP" I'm guessing that you mean an entire custom primitive (`mpi_allreduce_p`) with a JVP rule, rather than `jax.custom_jvp` (which won't work with an output token).

Here is a self-contained example that captures what's going on:

```python
from jax import grad, lax, core
from jax.interpreters import ad

def sin2(x, tok):
  return sin2_p.bind(x, tok)

def sin2_impl(x, tok):
  return lax.sin(x), lax.after_all(tok)

def sin2_abstract_eval(x, tok):
  assert isinstance(x, core.ShapedArray)
  assert tok is core.abstract_token
  return x, tok

def sin2_jvp(primals, tangents):
  x, tok = primals
  x_dot, _ = tangents
  y, tok = sin2_p.bind(x, tok)
  y_dot, tok = sin2_p.bind(x_dot, tok)
  return (y, tok), (y_dot, ad.Zero.from_value(tok))

sin2_p = core.Primitive('sin2')
sin2_p.def_impl(sin2_impl)
sin2_p.def_abstract_eval(sin2_abstract_eval)
sin2_p.multiple_results = True
ad.primitive_jvps[sin2_p] = sin2_jvp

def g(x):
  y1, t = sin2(x, lax.create_token())
  y2, t = sin2(x, t)
  return y1 + y2

x = 2.
grad(g)(x)
```

A JVP rule (which is really a "value and JVP" rule) for a function of type `a -> b` has the type:
```haskell
jvp_rule :: (a, T a) -> (b, T b)
```
VJP (for `grad`) calls this JVP rule with an assumption that, given all primal inputs (`a`), the primal output (`b`) is known. But in the JVP rule above, the primal output token also depends on the _tangent_ input `x_dot`, via the line:
```python
y_dot, tok = sin2_p.bind(x_dot, tok)
```
That's the direct cause of the error, and we can't work around it without somehow breaking that dependence, e.g. by writing instead:
```python
def sin2_jvp(primals, tangents):
  x, tok = primals
  x_dot, _ = tangents
  y, tok = sin2_p.bind(x, tok)
  y_dot, tok2 = sin2_p.bind(x_dot, tok)
  return (y, tok), (y_dot, ad.Zero.from_value(tok2))
```
This might be fine in this example since the two primitive `bind`s operate on different input operands `x` and `x_dot` anyway (this is reflected in your JVP as well). We could even split the token a step earlier if the two binding sites are indeed order-independent:
```python
  y, tok1 = sin2_p.bind(x, tok)
  y_dot, tok2 = sin2_p.bind(x_dot, tok)
  return (y, tok1), (y_dot, ad.Zero.from_value(tok2))
```

Would this approach resolve your original issue?

For the more general case, this seems like a good reason to consider allowing auxiliary data to be threaded through JVP rules. Doing that would require a larger change in jax's AD system. We should also consider improving the original error message.

**Comment by dionhaefner** [comment]
Thank you very much for the great answer! 

#### Issue 1

I understand the error now, although I'm not sure your proposed solution works for us.

Our custom calls are stateful and can under no circumstances be allowed to be re-ordered. I see that doing it this way:

```python
  y, tok = sin2_p.bind(x, tok)
  y_dot, tok2 = sin2_p.bind(x_dot, tok)
  return (y, tok), (y_dot, ad.Zero.from_value(tok2))
```

does ensure the correct order inside the JVP rule, but I'm not sure whether the second `bind` could be re-ordered with subsequent calls to `sin2` *after* taking the gradient. (We have never observed this, so I suspect that XLA does always respect the order here, but it would be nice to have a guarantee.)

And I agree that a better error message would be helpful here :)

#### Issue 2

As it turns out, this was actually because of an incorrect transpose rule. Our tranpose rule returned `(res, token)` instead of `(res, token_tangent)` (aka `(res, Zero)`). After fixing it this works as intended.

**Comment by froystig** [comment]
> Our custom calls are stateful and can under no circumstances be allowed to be re-ordered.
> [...]
> I'm not sure whether the second bind could be re-ordered with subsequent calls to `sin2` *after* evaluating the JVP.

Is that requirement not inconsistent with reverse-mode AD (i.e. `jax.grad`), in which all cotangent ("reverse") computation is data-dependent on all primal ("forward") computation? In other words, how would you expect to order `bind`s in the following (pasting from my previous example)?

```python
def g(x):
  y1, t = sin2(x, lax.create_token())
  y2, t = sin2(x, t)
  return y1 + y2

x = 2.
grad(g)(x)
```

**Comment by dionhaefner** [comment]
Maybe I'm mistaken, but with the 2 `sin2` calls back-to-back, this is my mental model what JAX sees when evaluating the gradient:

```python
# first sin2 call
y, tok = sin2_p.bind(x, tok)
y_dot, _ = sin2_p.bind(x_dot, tok)  # <-
# second sin2 call
y, tok2 = sin2_p.bind(x, tok)  # <-
y_dot, _ = sin2_p.bind(x_dot, tok2)
```

I can't see any data dependency between the two marked lines, so they could in principle be re-ordered, right?

**Comment by froystig** [comment]
> this is my mental model what JAX sees when evaluating the gradient: [...]

That's what forward-mode AD of `g` would look like (via `jax.jvp` or `jax.jacfwd`), but `jax.grad` calls for reverse-mode AD (VJP), and your example focuses on `jax.grad`.

> I can't see any data dependency between the two marked lines, so they could in principle be re-ordered, right?

That's correct (under JVP). I had understood from your comment that this reordering would be problematic, such that you would like to enforce the original ordering strictly, even if that violates a technical requirement of JVP routines. Is that right?

But in reverse-mode AD, the analogue of the original strict ordering is not possible even in principle. That's what I attempted to highlight in my previous question.

**Comment by dionhaefner** [comment]
Aha, I see! Thanks for clearing this up. I think we're on the same page now.

> I had understood from your comment that this reordering would be problematic, such that you would like to enforce the original ordering strictly, even if that violates a technical requirement of JVP routines. Is that right?

Correct.

> But in reverse-mode AD, the analogue of the original strict ordering is not possible even in principle. That's what I attempted to highlight in my previous question.

Actually, the situation is a bit more complicated in my case - executing everything in mirrored order is actually fine, so I wouldn't be worried about forward vs. reverse AD here.

**Comment by froystig** [comment]
Another approach to consider: if you are only expecting reverse-mode usage, and if there is an implementable ordering under reverse-mode (as your most recent comment suggests), then you could consider disallowing forward-mode altogether and defining only a VJP with `jax.custom_vjp`.
