### ISSUE TITLE
jax.ops.segment_sum incompatible with jit

### ISSUE THREAD

**Issue by proteneer** [google/jax#6350]
segment sum appears to be non-jittable
```python
import jax
import numpy as np

c = np.array([[1,2,3,4], [4, 3, 2, 1], [5,6,7,8]])
b = np.array([0, 0, 1])
jax.ops.segment_sum(c, b)
jit_fn = jax.jit(jax.ops.segment_sum)
jit_fn(c, b) 
```

Even if we use static_argnums we run into a similar issue. Traceback:

```
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
/home/yutong/venv37/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py:2872: UserWarning: Explicitly requested dtype int64 requested in zeros is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/google/jax#current-gotchas for more.
  lax._check_user_dtype_supported(dtype, "zeros")
Traceback (most recent call last):
  File "test_jit.py", line 8, in <module>
    jit_fn(c, b)
  File "/home/yutong/venv37/lib/python3.7/site-packages/jax/_src/ops/scatter.py", line 347, in segment_sum
    num_segments = int(num_segments)
jax._src.traceback_util.FilteredStackTrace: jax.core.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected.

The problem arose with the `int` function. If trying to convert the data type of a value, try using `x.astype(int)` or `jnp.array(x, int)` instead.

While tracing the function segment_sum at /home/yutong/venv37/lib/python3.7/site-packages/jax/_src/ops/scatter.py:312, this concrete value was not available in Python because it depends on the value of the arguments to segment_sum at /home/yutong/venv37/lib/python3.7/site-packages/jax/_src/ops/scatter.py:312 at flattened positions [1], and the computation of these values is being staged out (that is, delayed rather than executed eagerly).

You can use transformation parameters such as `static_argnums` for `jit` to avoid tracing particular arguments of transformed functions, though at the cost of more recompiles.

See https://jax.readthedocs.io/en/latest/faq.html#abstract-tracer-value-encountered-where-concrete-value-is-expected-error for more information.

Encountered tracer value: Traced<ShapedArray(int32[])>with<DynamicJaxprTrace(level=0/1)>

The stack trace above excludes JAX-internal frames.
The following is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test_jit.py", line 8, in <module>
    jit_fn(c, b)
  File "/home/yutong/venv37/lib/python3.7/site-packages/jax/_src/traceback_util.py", line 139, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/yutong/venv37/lib/python3.7/site-packages/jax/api.py", line 398, in f_jitted
    return cpp_jitted_f(context, *args, **kwargs)
  File "/home/yutong/venv37/lib/python3.7/site-packages/jax/api.py", line 295, in cache_miss
    donated_invars=donated_invars)
  File "/home/yutong/venv37/lib/python3.7/site-packages/jax/core.py", line 1275, in bind
    return call_bind(self, fun, *args, **params)
  File "/home/yutong/venv37/lib/python3.7/site-packages/jax/core.py", line 1266, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/home/yutong/venv37/lib/python3.7/site-packages/jax/core.py", line 1278, in process
    return trace.process_call(self, fun, tracers, params)
  File "/home/yutong/venv37/lib/python3.7/site-packages/jax/core.py", line 631, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/yutong/venv37/lib/python3.7/site-packages/jax/interpreters/xla.py", line 581, in _xla_call_impl
    *unsafe_map(arg_spec, args))
  File "/home/yutong/venv37/lib/python3.7/site-packages/jax/linear_util.py", line 260, in memoized_fun
    ans = call(fun, *args)
  File "/home/yutong/venv37/lib/python3.7/site-packages/jax/interpreters/xla.py", line 656, in _xla_callable
    jaxpr, out_avals, consts = pe.trace_to_jaxpr_final(fun, abstract_args)
  File "/home/yutong/venv37/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 1216, in trace_to_jaxpr_final
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, main, in_avals)
  File "/home/yutong/venv37/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 1196, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers)
  File "/home/yutong/venv37/lib/python3.7/site-packages/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/yutong/venv37/lib/python3.7/site-packages/jax/_src/ops/scatter.py", line 347, in segment_sum
    num_segments = int(num_segments)
  File "/home/yutong/venv37/lib/python3.7/site-packages/jax/core.py", line 561, in __int__
    def __int__(self): return self.aval._int(self)
  File "/home/yutong/venv37/lib/python3.7/site-packages/jax/core.py", line 955, in error
    raise_concretization_error(arg, fname_context)
  File "/home/yutong/venv37/lib/python3.7/site-packages/jax/core.py", line 944, in raise_concretization_error
    raise ConcretizationTypeError(msg)
jax.core.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected.

The problem arose with the `int` function. If trying to convert the data type of a value, try using `x.astype(int)` or `jnp.array(x, int)` instead.

While tracing the function segment_sum at /home/yutong/venv37/lib/python3.7/site-packages/jax/_src/ops/scatter.py:312, this concrete value was not available in Python because it depends on the value of the arguments to segment_sum at /home/yutong/venv37/lib/python3.7/site-packages/jax/_src/ops/scatter.py:312 at flattened positions [1], and the computation of these values is being staged out (that is, delayed rather than executed eagerly).

You can use transformation parameters such as `static_argnums` for `jit` to avoid tracing particular arguments of transformed functions, though at the cost of more recompiles.

See https://jax.readthedocs.io/en/latest/faq.html#abstract-tracer-value-encountered-where-concrete-value-is-expected-error for more information.

Encountered tracer value: Traced<ShapedArray(int32[])>with<DynamicJaxprTrace(level=0/1)>
```

**Comment by jakevdp** [comment]
Hi - thanks for the report. The issue is mentioned in the [docstring](https://jax.readthedocs.io/en/latest/_autosummary/jax.ops.segment_sum.html)

> Since `num_segments` determines the size of the output, a static value must be provided to use ``segment_sum`` in a ``jit``-compiled function.

You can fix this passing a static value for `num_segments`; for example:
```python
import jax
import numpy as np

c = np.array([[1,2,3,4], [4, 3, 2, 1], [5,6,7,8]])
b = np.array([0, 0, 1])
jax.ops.segment_sum(c, b)
jit_fn = jax.jit(jax.ops.segment_sum, static_argnums=2)
jit_fn(c, b, 2)
# DeviceArray([[5, 5, 5, 5],
#              [5, 6, 7, 8]], dtype=int32)
```

**Comment by proteneer** [comment]
Thanks for this - I was trying to use static_argnums=1, should've read the docs more carefully!
