### ISSUE TITLE
[FR] Provide a method to probe available devices

### ISSUE THREAD

**Issue by PhilipVinc** [google/jax#6459]
Right now the only way to probe available devices in jax is to attempt to run `jax.devices(string)` with the arguments `cpu`, `gpu` and `tpu`.
However, if you have a cpu-only jaxlib, and/or tpus are not available an error is thrown.

For library authors relying on jax this is inconvenient because we have to put everything within a try-catch block.

Would it be possible for you to add a way to get a list of available backends to more reliably probe the system?

**Comment by jakevdp** [comment]
Does this do what you want?
```python
from jax.lib import xla_bridge
xla_bridge.devices()
# [CpuDevice(id=0)]
```

**Comment by PhilipVinc** [comment]
No, because it throws if there are no gpus available instead of returning an empty list.

```python
>>> xla_bridge.devices()
[CpuDevice(id=0)]
>>> xla_bridge.devices("gpu")
Traceback (most recent call last):
  File "/home/filippovicentini/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/jaxlib/xla_client.py", line 156, in get_local_backend
    return backends[name]
KeyError: 'gpu'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/filippovicentini/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/jax/lib/xla_bridge.py", line 232, in devices
    return get_backend(backend).devices()
  File "/home/filippovicentini/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/jax/lib/xla_bridge.py", line 180, in get_backend
    return backend(platform)
  File "/home/filippovicentini/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/jax/lib/xla_bridge.py", line 132, in _get_local_backend
    backend = xla_client.get_local_backend(platform)
  File "/home/filippovicentini/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/jaxlib/xla_client.py", line 158, in get_local_backend
    raise RuntimeError(
RuntimeError: Unknown backend gpu. Available: ['interpreter', 'cpu']
>>> 
```

**Comment by PhilipVinc** [comment]
And if i do this when i have gpus available i get
```python
>>> jax.devices()
[CpuDevice(id=0)]
>>> jax.devices('gpu')
[GpuDevice(id=0, process_index=0)]
```
So there is no way, without a try-catch statement, to know if the user actually has gpus or not.

**Comment by jakevdp** [comment]
In a perfect world, what API would you like to have?

**Comment by PhilipVinc** [comment]
```python
>>> jax.backends()
["cpu"]
```
or
```python
>>> jax.backends()
["cpu", "gpu"]
```
or 
```python
>>> jax.backends()
["cpu", "gpu", "tpu"]
```
depending on what's available

**Comment by jakevdp** [comment]
Thanks! So effectively you want jax to provide a function that is something like this:
```python
def backends():
  backends = []
  for backend in ['cpu', 'gpu', 'tpu']:
    try:
      jax.devices(backend)
    except RuntimeError:
      pass
    else:
      backends.append(backend)
  return backends
```
(the strange thing I just noticed, though, is that on Colab TPU this returns `['cpu', 'gpu', 'tpu']` because `jax.devices('gpu')` returns the list of TPU devices. That may be a bug)

**Comment by PhilipVinc** [comment]
Yes, that's kind-of how I do it right now but it feels very hacky so If there was something 'officially' provided that would be great.

**Comment by jakevdp** [comment]
In fact, on TPU `jax.devices(platform)` only checks if `platform == "cpu"`, and otherwise ignores the string: https://github.com/google/jax/blob/3c003a68fcc2ecea575a58bae033b951fc0e08a5/jax/lib/xla_bridge.py#L148-L159

**Comment by pearu** [comment]
I was hit the same issue reported here: have a runtime predicate function that tests if a particular platform support is available in jax.

I think the `jax.devices(platform)` provides a reasonable API for that: if `jax.devices(platform)` returns an empty list then we'll know that the corresponding platform is not supported.

However, with the current jax main branch it raises an exception:
```python
>>> jax.devices('tpu')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pearu/git/pearu/jax/jax/_src/xla_bridge.py", line 1083, in devices
    return get_backend(backend).devices()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/pearu/git/pearu/jax/jax/_src/xla_bridge.py", line 1017, in get_backend
    return _get_backend_uncached(platform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pearu/git/pearu/jax/jax/_src/xla_bridge.py", line 1002, in _get_backend_uncached
    raise RuntimeError(f"Backend '{platform}' failed to initialize: "
RuntimeError: Backend 'tpu' failed to initialize: INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory. Available backends are ['cpu', 'cuda']
```

I suggest that instead of a RuntimeError, `jax.devices` returns an empty list when the specified backend is not available. And return RuntimeError only when the specified backend is unknown as it is currently:
```python
>> jax.devices('foo')
...
RuntimeError: Unknown backend foo. Available backends are ['cpu', 'cuda']
```

What do you think?
