### ISSUE TITLE
build fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [google/jax#6506]
[jw@cn06 jax]$ python3 build/build.py

     _   _  __  __
    | | / \ \ \/ /
 _  | |/ _ \ \  /
| |_| / ___ \/  \
 \___/_/   \/_/\_\

Downloading bazel from: https://github.com/bazelbuild/bazel/releases/download/3.7.2/bazel-3.7.2-linux-x86_64
bazel-3.7.2-linux-x86_64 [########################################] 100%
Traceback (most recent call last):
  File "/data/jw/jax/build/build.py", line 521, in <module>
    main()
  File "/data/jw/jax/build/build.py", line 439, in main
    bazel_path = get_bazel_path(args.bazel_path)
  File "/data/jw/jax/build/build.py", line 165, in get_bazel_path
    if check_bazel_version(path):
  File "/data/jw/jax/build/build.py", line 174, in check_bazel_version
    version_output = shell([bazel_path, "--bazelrc=/dev/null", "version"])
  File "/data/jw/jax/build/build.py", line 51, in shell
    output = subprocess.check_output(cmd)
  File "/usr/lib64/python3.9/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.9/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: './bazel-3.7.2-linux-x86_64'
[jw@cn06 jax]$

**Comment by hawkinsp** [comment]
The build script doesn't support aarch64 on Linux yet! But that's ok, we accept contributions.

I suspect we need to teach this logic about aarch64:
https://cs.opensource.google/jax/jax/+/master:build/build.py;drc=7b7a2a1ba83fec86f6fa6e4526a12c5e33f80ebb;l=81

Do you want to send a PR adding an Aarch64 case? (Another option is that we may be able to use something like Bazelisk instead of having our own "download bazel" logic.)

(I suspect once the build script is fixed, there's a pretty good chance that everything will work.)

**Comment by LutzWeischerFujitsu** [comment]
It's pretty common that build processes have unintentional "Intel-isms". 
You, please, do a PR, I'll test it and keep on reporting issues. BTW, Bazel does work already.

**Comment by hawkinsp** [comment]
#6701 was my best guess at a fix. I don't have such a machine to test with, though. Please try it out!
