### ISSUE TITLE
Caching bug for jax.experimental.callback.rewrite for `jit` call inside `custom_gradient`

### ISSUE THREAD

**Issue by hawkinsp** [google/jax#6685]
```
import jax

from jax import lax
from jax import grad, jit
from jax.experimental.callback import rewrite

import numpy as np

@jax.custom_gradient
def f(x):
  return jax.jit(lax.mul)(x, 2.), lambda g: g + x

x = 2.

rewrites = {
    lax.mul_p: lambda x, y: x / y
}
g = rewrite(f, rewrites)

np.testing.assert_allclose(g(x), 1.)

rewrites = {
    lax.add_p: lambda x, y: x - y
}
g = rewrite(f, rewrites)

np.testing.assert_allclose(g(x), 4.)
```

```
Traceback (most recent call last):
  File "/Users/phawkins/p/jax/c.py", line 28, in <module>
    np.testing.assert_allclose(g(x), 4.)
  File "/Users/phawkins/.pyenv/versions/py3.9.0/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 1527, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/Users/phawkins/.pyenv/versions/py3.9.0/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 1 / 1 (100%)
Max absolute difference: 3.
Max relative difference: 0.75
 x: array(1., dtype=float32)
 y: array(4.)
```

If you remove the first call to `g(x)`, then the assertion passes. It seems we are erroneously reusing the previous definition of a function in caching.

My guess is the jit cache key is missing some relevant context.

**Comment by froystig** [comment]
cc @sschoenholz @sharadmv

**Comment by nireekshak** [comment]
Hi @hawkinsp, The module `jax.experimental.callback` was removed in JAX version 0.4.2, which was released on January 24, 2023. For more information, please refer to the following [link](https://jax.readthedocs.io/en/latest/changelog.html#:~:text=Deleted%20jax.experimental.callback). I hope this clarifies the issue, and you may close it at your convenience. Thank you!
