### ISSUE TITLE
Surprising interaction between `jit` and `remat(concrete=True)`

### ISSUE THREAD

**Issue by hawkinsp** [google/jax#6713]
```
from functools import partial
import jax
from jax import lax, jit
import numpy as np

@partial(jax.remat, concrete=True)
def g(x):
  if jax.jit(lax.gt)(x, 0.):
    return lax.sin(x), 3.
  else:
    return lax.cos(x), 4.

def f(x):
  x, _ = g(x)
  return x

ans = jax.grad(f)(2.)
expected = np.cos(2.)
np.testing.assert_allclose(ans, expected)
```

```
Traceback (most recent call last):
  File "/Users/phawkins/p/jax/c.py", line 17, in <module>
    ans = jax.grad(f)(2.)
  File "/Users/phawkins/p/jax/c.py", line 14, in f
    x, _ = g(x)
  File "/Users/phawkins/p/jax/c.py", line 8, in g
    if jax.jit(lax.gt)(x, 0.):
jax._src.errors.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: Traced<ShapedArray(bool[], weak_type=True):JaxprTrace(level=1/1)>
The problem arose with the `bool` function.
See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError
```

**Comment by hawkinsp** [comment]
I was about to file this bug a second time. Let me dust off the old one instead...

**Comment by hawkinsp** [comment]
This is moot because `remat` no longer has a `concrete` option.
