### ISSUE TITLE
nans in gradient of scale_and_translate

### ISSUE THREAD

**Issue by lukepfister** [google/jax#6780]
I'd like to take gradients of `scale_and_translate` wrt the translation parameters.  Currently the gradients are `nan` whenever the translation is >1.  Example: 

```python
import jax
import jax.numpy as jnp
from jax.image import scale_and_translate

xin = jnp.r_[:16].reshape(4, 4) + 1.
xin = jax.device_put(xin)

def f(x):
    out = scale_and_translate(xin, shape=xin.shape, spatial_dims=(0, 1),
                              scale=jnp.array([1.0, 1.0]),
                              translation=jnp.array([x[0], x[1]]),
                              method='linear', antialias=True)
    return out

f((1.1, 1.2))  # raises an error if JAX_DEBUG_NANS=1

g = lambda x: jnp.sum(f(x))

print(jax.grad(g)( (1.1, 1.2)))  # nans
```

If `JAX_DEBUG_NANS=1` is set, the script throws an exception at the evaluation of `f`:
```
Traceback (most recent call last):
  File "resize.py", line 15, in <module>
    f((1.1, 1.2))  # raises an error if JAX_DEBUG_NANS=1
  File "resize.py", line 9, in f
    out = scale_and_translate(xin, shape=xin.shape, spatial_dims=(0, 1),
  File "/home/pfister/miniconda3/envs/scico/lib/python3.8/site-packages/jax/_src/image/scale.py", line 219, in scale_and_translate
    return _scale_and_translate(image, shape, spatial_dims, scale, translation,
  File "/home/pfister/miniconda3/envs/scico/lib/python3.8/site-packages/jax/_src/image/scale.py", line 92, in _scale_and_translate
    w = compute_weight_mat(m, n, scale[i], translation[i],
  File "/home/pfister/miniconda3/envs/scico/lib/python3.8/site-packages/jax/_src/image/scale.py", line 69, in compute_weight_mat
    weights / total_weight_sum, 0)
  File "/home/pfister/miniconda3/envs/scico/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 5666, in deferring_binary_op
    return binary_op(self, other)
  File "/home/pfister/miniconda3/envs/scico/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 569, in true_divide
    return lax.div(x1, x2)
  File "/home/pfister/miniconda3/envs/scico/lib/python3.8/site-packages/jax/_src/lax/lax.py", line 352, in div
    return div_p.bind(x, y)
  File "/home/pfister/miniconda3/envs/scico/lib/python3.8/site-packages/jax/core.py", line 264, in bind
    out = top_trace.process_primitive(self, tracers, params)
  File "/home/pfister/miniconda3/envs/scico/lib/python3.8/site-packages/jax/core.py", line 606, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/pfister/miniconda3/envs/scico/lib/python3.8/site-packages/jax/interpreters/xla.py", line 232, in apply_primitive
    return compiled_fun(*args)
  File "/home/pfister/miniconda3/envs/scico/lib/python3.8/site-packages/jax/interpreters/xla.py", line 351, in _execute_compiled_primitive
    check_special(prim.name, out_bufs)
  File "/home/pfister/miniconda3/envs/scico/lib/python3.8/site-packages/jax/interpreters/xla.py", line 370, in check_special
    _check_special(name, buf.xla_shape(), buf)
  File "/home/pfister/miniconda3/envs/scico/lib/python3.8/site-packages/jax/interpreters/xla.py", line 376, in _check_special
    raise FloatingPointError(f"invalid value (nan) encountered in {name}")
FloatingPointError: invalid value (nan) encountered in div
```

The issue is in this block: 
https://github.com/google/jax/blob/c85e835951c68b4383dbc9ef25bef99ea996fd84/jax/_src/image/scale.py#L66-L69
in particular, the computaiton `weights/total_weight_sum` can involve a divide by 0, even though those locations get set to zero in the course of the `jnp.where`.

I'll submit a PR shortly with the "where inside of where" fix.

**Comment by zhangqiaorjc** [comment]
Assigning to @hawkinsp since Peter is shepherding the PR review

**Comment by astanziola** [comment]
I have observed the same problem with the `sinc` function defined [here](https://github.com/google/jax/blob/d39261497c12488632cf7c5d5f19d2c074a565dd/jax/_src/numpy/lax_numpy.py#L1061).

A quick fix for the `sinc` case is given below. I would add this to another PR, but I've never done one and don't want to clutter with my inexperience :)

```python
def safe_sinc(x: jnp.ndarray) -> jnp.ndarray:
    _check_arraylike("sinc", x)
    (x,) = _promote_dtypes_inexact(x)
    eq_zero = lax.eq(x, lax._const(x, 0))
    pi_x = lax.mul(lax._const(x, pi), x)
    safe_pi_x = where(eq_zero, lax._const(x, 1), pi_x)
    return where(
        eq_zero, _sinc_maclaurin(0, pi_x), lax.div(lax.sin(safe_pi_x), safe_pi_x)
    )
```

**Comment by lukepfister** [comment]
This problem, and the same "double where" fix, seems to come up often.  Is it worth adding a `divide_where_safe` function to the library in `util` or somewhere similar?

**Comment by hawkinsp** [comment]
@astanziola Open a new issue or send a PR for `sinc`?

@lukepfister Perhaps. I wonder how often we want to apply the double-where trick just around a division (as opposed to other things as well).

**Comment by astanziola** [comment]
@hawkinsp Sure, I'll do one this weekend
