### ISSUE TITLE
jax.random bug if "jax_disable_jit" == True

### ISSUE THREAD

**Issue by mr128254** [google/jax#6922]
jax.random.choice does not work as expected if jit is disabled.

```python
import jax 
jax.config.update('jax_disable_jit', True)
jax.random.choice(jax.random.PRNGKey(1234), 8, shape=(100,))
```

Output:
```
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/usr/anaconda3/lib/python3.7/site-packages/jax/_src/random.py", line 619, in choice
    ind = randint(key, shape, 0, n_inputs)
  File "/home/usr/anaconda3/lib/python3.7/site-packages/jax/_src/random.py", line 438, in randint
    return _randint(key, shape, minval, maxval, dtype)
  File "/home/usr/anaconda3/lib/python3.7/site-packages/jax/_src/random.py", line 446, in _randint
    minval = _asarray(minval)
  File "/home/moritz/anaconda3/lib/python3.7/site-packages/jax/_src/random.py", line 92, in _asarray
    raise TypeError(f"Function requires array input, got {x} of type {type(x)}.")
TypeError: Function requires array input, got 0 of type <class 'int'>.
```

**Comment by jakevdp** [comment]
Thanks for the report – I think this check is too restrictive. We should probably use the `_check_arraylike` utility from `lax_numpy.py`.
