### ISSUE TITLE
Trace leak with `odeint`

### ISSUE THREAD

**Issue by jatentaki** [google/jax#7182]
# Bug
This is a follow-up to #7142: I have since moved from `haiku` to `stax` to avoid the statefulness and transforms, but I am still trying to backpropagate through `jax.experimental.ode.odeint`. My actual code runs fine until we try to take a gradient, in which case it fails due to leaked tracers. When I set the `JAX_CHECK_TRACER_LEAKS=1` flag, all my test cases involving `odeint` (and not just backprop) start to fail. Since my code is too big to be distilled into a minimal repro, I tried building one from ground up, including operations which I find relevant. I arrive at the code below, which runs fine with `JAX_CHECK_TRACER_LEAKS=0` (unlike my actual codebase, gradients get computed without erroring out) but similarly to it, with `JAX_CHECK_TRACER_LEAKS=1` it fails at the forward computation (and backward too, if you comment out the forward computation).

In #7142 I was told that the tracer checker may give false positives, but I am unable to judge this myself. Is the case below enough to diagnose some bugs? I can potentially open my actual codebase, but I'd prefer to avoid that.

# Code
```python
import jax
import jax.numpy as jnp
import jax.experimental.stax as sx
import numpy as np
from jax.experimental.ode import odeint

def dense(n):
    '''
    A simple example definition of the function f in `dy = f(y, t)`.
    We just concatenate `y` and `t` into a single vector and apply a
    dense layer.
    '''

    d_init_fn, d_apply_fn = sx.Dense(n)

    def init_fn(rng, input_shape):
        y_shape, t_shape, = input_shape

        d_input_shape = (*y_shape[:-1], y_shape[-1] + 1)
        output_shape, params = d_init_fn(rng, d_input_shape)
        return output_shape, params

    def apply_fn(params, y, t):
        assert len(y.shape) == 1
        assert len(t.shape) == 0
        yt = jnp.concatenate([y, t[None]])

        return d_apply_fn(params, yt)

    return init_fn, apply_fn

def solve_ode(f, params, y0):
    ''' solves the ode defined by f over t between 0 and 1 '''
    t = jnp.linspace(0, 1, 10)
    fun = lambda y, t: f(params, y, t)
    y = odeint(fun, y0, t)
    return y

def grad_ode(f, params, y0):
    def loss(params):
        ''' an example way to define some loss which we can backprop on '''
        d_t = solve_ode(f, params, y0)
        return d_t[-1].mean()

    return jax.value_and_grad(loss)(params)

rng_key = jax.random.PRNGKey(42)
N, C = 5, 3

y0 = np.random.randn(N)
t = np.array(0.5)

d_init, d_apply = dense(N)
_, params = d_init(rng_key, (y0.shape, t.shape))

d_t = solve_ode(d_apply, params, y0)
print(d_t.shape)

loss, g = grad_ode(d_apply, params, y0) 

print(loss)
print(g)
```

# Error stack trace

```
jatentaki@drozd:~/Programs/jflow/debugging$ JAX_CHECK_TRACER_LEAKS=1 python test.py 
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Traceback (most recent call last):
  File "test.py", line 56, in <module>
    d_t = solve_ode(d_apply, params, y0)
  File "test.py", line 36, in solve_ode
    y = odeint(fun, y0, t)
  File "/home/jatentaki/miniconda3/lib/python3.8/site-packages/jax/experimental/ode.py", line 173, in odeint
    return _odeint_wrapper(converted, rtol, atol, mxstep, y0, t, *args, *consts)
  File "/home/jatentaki/miniconda3/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 183, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/jatentaki/miniconda3/lib/python3.8/site-packages/jax/_src/api.py", line 424, in cache_miss
    out_flat = xla.xla_call(
  File "/home/jatentaki/miniconda3/lib/python3.8/site-packages/jax/core.py", line 1560, in bind
    return call_bind(self, fun, *args, **params)
  File "/home/jatentaki/miniconda3/lib/python3.8/site-packages/jax/core.py", line 1551, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/home/jatentaki/miniconda3/lib/python3.8/site-packages/jax/core.py", line 1563, in process
    return trace.process_call(self, fun, tracers, params)
  File "/home/jatentaki/miniconda3/lib/python3.8/site-packages/jax/core.py", line 606, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/jatentaki/miniconda3/lib/python3.8/site-packages/jax/interpreters/xla.py", line 592, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, name, donated_invars,
  File "/home/jatentaki/miniconda3/lib/python3.8/site-packages/jax/linear_util.py", line 262, in memoized_fun
    ans = call(fun, *args)
  File "/home/jatentaki/miniconda3/lib/python3.8/site-packages/jax/interpreters/xla.py", line 667, in _xla_callable
    jaxpr, out_avals, consts = pe.trace_to_jaxpr_final(
  File "/home/jatentaki/miniconda3/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1284, in trace_to_jaxpr_final
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, main, in_avals)
  File "/home/jatentaki/miniconda3/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/home/jatentaki/miniconda3/lib/python3.8/site-packages/jax/core.py", line 806, in new_sublevel
    raise Exception(f'Leaked sublevel {t()}.')
jax._src.traceback_util.UnfilteredStackTrace: Exception: Leaked sublevel 1.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 56, in <module>
    d_t = solve_ode(d_apply, params, y0)
  File "test.py", line 36, in solve_ode
    y = odeint(fun, y0, t)
  File "/home/jatentaki/miniconda3/lib/python3.8/site-packages/jax/experimental/ode.py", line 173, in odeint
    return _odeint_wrapper(converted, rtol, atol, mxstep, y0, t, *args, *consts)
  File "/home/jatentaki/miniconda3/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
Exception: Leaked sublevel 1.
```

## Library versions:
```
jatentaki@drozd:~/Programs/jflow$ python -c "import jax, jaxlib; print(jax.__version__, jaxlib.__version__)"
0.2.16 0.1.68
```

**Comment by jakevdp** [comment]
Thanks for the report & clear repro, @jatentaki. Hopefully someone will be able to take a closer look soon.

**Comment by selamw1** [comment]
Hi @jatentaki 

It looks like this issue has been fixed in the latest JAX versions. I executed the mentioned code in JAX version 0.4.23 without any errors. However, note that [`jax.experimental.stax`](https://jax.readthedocs.io/en/latest/changelog.html#jax-0-3-16:~:text=Removed%20jax.experimental.stax%3B%20it%20has%20long%20been%20a%20deprecated%20alias%20of%20jax.example_libraries.stax) has been deprecated and replaced by `jax.example_libraries.stax`.

```Python
import jax
import jax.numpy as jnp
# jax.experimental.stax is removed; it has long been a deprecated alias of jax.example_libraries.stax.
# import jax.experimental.stax as sx 
import jax.example_libraries.stax as sx
import numpy as np
from jax.experimental.ode import odeint

def dense(n):
    '''
    A simple example definition of the function f in `dy = f(y, t)`.
    We just concatenate `y` and `t` into a single vector and apply a
    dense layer.
    '''

    d_init_fn, d_apply_fn = sx.Dense(n)

    def init_fn(rng, input_shape):
        y_shape, t_shape, = input_shape

        d_input_shape = (*y_shape[:-1], y_shape[-1] + 1)
        output_shape, params = d_init_fn(rng, d_input_shape)
        return output_shape, params

    def apply_fn(params, y, t):
        assert len(y.shape) == 1
        assert len(t.shape) == 0
        yt = jnp.concatenate([y, t[None]])

        return d_apply_fn(params, yt)

    return init_fn, apply_fn

def solve_ode(f, params, y0):
    ''' solves the ode defined by f over t between 0 and 1 '''
    t = jnp.linspace(0, 1, 10)
    fun = lambda y, t: f(params, y, t)
    y = odeint(fun, y0, t)
    return y

def grad_ode(f, params, y0):
    def loss(params):
        ''' an example way to define some loss which we can backprop on '''
        d_t = solve_ode(f, params, y0)
        return d_t[-1].mean()

    return jax.value_and_grad(loss)(params)

rng_key = jax.random.PRNGKey(42)
N, C = 5, 3

y0 = np.random.randn(N)
t = np.array(0.5)

d_init, d_apply = dense(N)
_, params = d_init(rng_key, (y0.shape, t.shape))

d_t = solve_ode(d_apply, params, y0)
print(d_t.shape)

loss, g = grad_ode(d_apply, params, y0) 

print(loss)
print(g)
```
Output:
```
(10, 5)
0.045054007
(Array([[ 0.00094843, -0.17762688, -0.09329863, -0.02836601, -0.08737083],
       [-0.01951531, -0.09566554, -0.05993164, -0.02846049, -0.05375667],
       [-0.04377968,  0.43775326,  0.20988415,  0.04158223,  0.2004192 ],
       [-0.01857239,  0.5370345 ,  0.27447653,  0.07459338,  0.25807694],
       [ 0.0255919 , -0.33067527, -0.16216335, -0.03688037, -0.15443903],
       [ 0.03454172,  0.15016206,  0.09596114,  0.04780234,  0.08623691]],      dtype=float32), Array([-0.00179814,  0.3366217 ,  0.17680681,  0.05351925,  0.16534077],      dtype=float32))
```

I've included a [Gist](https://colab.research.google.com/gist/selamw1/43300cd8a5b6c008e132842a59ba6717/-7182.ipynb) here for your reference.

**Comment by jakevdp** [comment]
Thanks for the followup! It looks like we can close this.
