### ISSUE TITLE
Jax older version as newer version does not work within my code

### ISSUE THREAD

**Issue by paramjeet2021** [google/jax#7334]
I installed jax == 0.2.12 because my code specifically works with this version. When I import then it generated below error:
``` 
import jax
2021-07-20 13:32:45.335463: F external/org_tensorflow/tensorflow/core/tpu/tpu_executor_init_fns.inc:110] TpuTransferManager_ReadDynamicShapes not available in this library.
Aborted (core dumped)
```
If I used 0.2.15 onwards, then import jax works fine but my code does not works. 

How can I setup Jax==0.2.12 to make import jax work?

**Comment by skye** [comment]
I take it you're running JAX on a Cloud TPU VM? Can you say more about what doesn't work with jax >= 0.2.15? (e.g. what error do you get?)

If you must use jax 0.2.12, try creating a fresh TPU VM, and install jax like this: `pip install jax==0.2.12`. However, this is a pretty brittle setup and may break in the future, so I suggest figuring out how to get your code to run with new jax versions, which will be more stable on a TPU VM.

**Comment by paramjeet2021** [comment]
I have installed jax== 2.16 on my TPU VM and executing repo https://github.com/kingoflolz/mesh-transformer-jax

In this code base, I have to train a custom ML model followed by  colab_demo file to generate content.   Everything worked with jax 2.16 but I am stuck in colab_demo.ipynb and people are recommending Jax=2.12 works and this issue will not arise. You can look more into the below error and same error has been reported at https://github.com/google/jax/issues/6962 
```
Traceback (most recent call last):
  File "content_generation.py", line 93, in <module>
    print(infer("EleutherAI is")[0])
  File "content_generation.py", line 82, in infer
    output = network.generate(batched_tokens, length, gen_len, {"top_p": np.ones(total_batch) * top_p, "temp": np.ones(total_batch) * temp})
  File "/home/paramjeetsingh80/mesh-transformer-jax/mesh_transformer/transformer_shard.py", line 309, in generate
    return self.generate_xmap(self.state,
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/jax/experimental/maps.py", line 615, in fun_mapped
    out_flat = xmap_p.bind(
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/jax/experimental/maps.py", line 818, in bind
    return core.call_bind(self, fun, *args, **params)  # type: ignore
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/jax/core.py", line 1551, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/jax/experimental/maps.py", line 821, in process
    return trace.process_xmap(self, fun, tracers, params)
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/jax/core.py", line 606, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/jax/experimental/maps.py", line 646, in xmap_impl
    xmap_callable = make_xmap_callable(
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/jax/linear_util.py", line 262, in memoized_fun
    ans = call(fun, *args)
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/jax/experimental/maps.py", line 673, in make_xmap_callable
    _check_out_avals_vs_out_axes(out_avals, out_axes, global_axis_sizes)
  File "/home/paramjeetsingh80/.local/lib/python3.8/site-packages/jax/experimental/maps.py", line 1454, in _check_out_avals_vs_out_axes
    raise TypeError(f"One of xmap results has an out_axes specification of "
TypeError: One of xmap results has an out_axes specification of ['batch', ...], but is actually mapped along more axes defined by this xmap call: shard
```


My code snipper is 

params = {
  "layers": 28,
  "d_model": 4096,
  "n_heads": 16,
  "n_vocab": 50400,
  "norm": "layernorm",
  "pe": "rotary",
  "pe_rotary_dims": 64,

  "seq": 2048,
  "cores_per_replica": 8,
  "per_replica_batch": 1,
}

per_replica_batch = params["per_replica_batch"]
cores_per_replica = params["cores_per_replica"]
seq = params["seq"]


params["sampler"] = nucleaus_sample

# here we "remove" the optimizer parameters from the model (as we don't need them for inference)
params["optimizer"] = optax.scale(0)

mesh_shape = (jax.device_count() // cores_per_replica, cores_per_replica)
devices = np.array(jax.devices()).reshape(mesh_shape)

maps.thread_resources.env = maps.ResourceEnv(maps.Mesh(devices, ('dp', 'mp')))

tokenizer = transformers.GPT2TokenizerFast.from_pretrained('gpt2')
```

**Comment by hawkinsp** [comment]
I'm going to close this issue, because the right fix is to upgrade to the current JAX. If you need help migrating your code, I suggest opening a Github discussion about it and we can help you out!
