### ISSUE TITLE
np.trace is broken

### ISSUE THREAD

**Issue by Thenerdstation** [google/jax#738]
```
import jax.numpy as np
import numpy as onp

# This works
print(onp.trace(onp.ones((2, 3, 4, 4)), axis1=-1, axis2=-2))

# This does not work
print(np.trace(np.ones((2, 3, 4, 4)), axis1=-1, axis2=-2))
```

Error message:
```
>>> print(np.trace(np.ones((2, 3, 4, 4)), axis1=-1, axis2=-2))
Traceback (most recent call last):
  File "/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/jax/interpreters/xla.py", line 70, in primitive_computation
    return c.Build()
  File "/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/jax/lib/xla_bridge.py", line 267, in Build
    *args, **kwargs)
  File "/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/jaxlib/xla_client.py", line 640, in Build
    return Computation(self._builder.Build(), backend=backend)
RuntimeError: Invalid argument: Transpose dimensions [0,1,2,3,-1,-2] are not a permutation of the operand dimensions (operand shape is f32[2,3,4,4]).: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/jax/numpy/lax_numpy.py", line 1465, in trace
    a = lax.transpose(a, perm)
  File "/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/jax/lax/lax.py", line 685, in transpose
    return transpose_p.bind(operand, permutation=permutation)
  File "/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/jax/core.py", line 117, in bind
    return self.impl(*args, **kwargs)
  File "/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/jax/interpreters/xla.py", line 51, in apply_primitive
    compiled_fun = xla_primitive_callable(prim, *abstract_args, **kwargs)
  File "/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/jax/util.py", line 174, in memoized_fun
    ans = cache[key] = fun(*args, **kwargs)
  File "/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/jax/interpreters/xla.py", line 57, in xla_primitive_callable
    built_c = primitive_computation(prim, *shapes, **kwargs)
  File "/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/jax/util.py", line 174, in memoized_fun
    ans = cache[key] = fun(*args, **kwargs)
  File "/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/jax/interpreters/xla.py", line 73, in primitive_computation
    prim.abstract_eval(*map(aval_from_xla_shape, shapes), **kwargs)
  File "/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/jax/lax/lax.py", line 1295, in standard_abstract_eval
    return ShapedArray(shape_rule(*args, **kwargs), dtype_rule(*args, **kwargs))
  File "/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/jax/lax/lax.py", line 2268, in _transpose_shape_rule
    raise TypeError(msg.format(permutation, operand.shape))
TypeError: transpose permutation isn't a permutation of operand dimensions, got permutation (0, 1, 2, 3, -1, -2) for operand shape (2, 3, 4, 4).

```

**Comment by mattjj** [comment]
Thanks for catching this!

We were missing an `axis % ndim` on these axes. #741 will squash the issue and add tests for negative axis values passed to `np.trace`.

(It takes ~30 min for Travis CI to run our tests, though, so hopefully you can wait that long!)

**Comment by Thenerdstation** [comment]
Thanks! When will the next JAX release include this?

**Comment by mattjj** [comment]
We do pypi releases on an ad-hoc basis. Making a new jax release is pretty easy, though, so if you ever need one, just ask and we'll make it happen! (I just pushed 0.1.33 for you, which includes these fixes.)

However, if you want to get the latest jax code without having to wait for us to push an update, you can just work from the github master branch. You can even point pip at github directly.
