### ISSUE TITLE
Debug infs and logsumexp

### ISSUE THREAD

**Issue by yallup** [google/jax#7390]
I've found a difference in behavior between the latest versions and a (recent) previous version of the library I was using. I found this trying to debug a larger issue on an hpc application being build using jax but when trying to debug that, this was thrown which might point to the root cause of the larger issue.

I wanted to clarify if the following is expected:

Specifically it appears that when trying to use the debug_infs config option, with a special function that does some checking for np.inf itself (in this case logsumexp), the latest version of the library from pip will throw an error that was passed previously

MWE:
```python
from jax.scipy.special import logsumexp

from jax.config import config
config.update("jax_debug_infs", True)

import numpy as np

x=np.ones(10)
y=logsumexp(x)

print(y)
```

Using jaxlib 0.1.64 and jax 0.2.10 this prints the value fine (note none of the values in the array that is being summed are inf)

updating to jaxlib 0.1.69 and jax 0.2.18 the following error shows:

```
Traceback (most recent call last):
  File "test_inf.py", line 9, in <module>
    y=logsumexp(x)
  File "/rds/user/dy297/hpc-work/install/python/lib/python3.8/site-packages/jax/_src/scipy/special.py", line 124, in logsumexp
    sign = jnp.where(out == -np.inf, 0.0, sign)
  File "/rds/user/dy297/hpc-work/install/python/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 5871, in deferring_binary_op
    return binary_op(self, other)
  File "/rds/user/dy297/hpc-work/install/python/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 421, in <lambda>
    fn = lambda x1, x2: lax_fn(*_promote_args(numpy_fn.__name__, x1, x2))
  File "/rds/user/dy297/hpc-work/install/python/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 326, in _promote_args
    return _promote_shapes(fun_name, *_promote_dtypes(*args))
  File "/rds/user/dy297/hpc-work/install/python/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 272, in _promote_dtypes
    return [lax._convert_element_type(x, to_dtype, weak_type) for x in args]
  File "/rds/user/dy297/hpc-work/install/python/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 272, in <listcomp>
    return [lax._convert_element_type(x, to_dtype, weak_type) for x in args]
  File "/rds/user/dy297/hpc-work/install/python/lib/python3.8/site-packages/jax/_src/lax/lax.py", line 454, in _convert_element_type
    return convert_element_type_p.bind(operand, new_dtype=new_dtype,
  File "/rds/user/dy297/hpc-work/install/python/lib/python3.8/site-packages/jax/core.py", line 264, in bind
    out = top_trace.process_primitive(self, tracers, params)
  File "/rds/user/dy297/hpc-work/install/python/lib/python3.8/site-packages/jax/core.py", line 604, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/rds/user/dy297/hpc-work/install/python/lib/python3.8/site-packages/jax/interpreters/xla.py", line 262, in apply_primitive
    return compiled_fun(*args)
  File "/rds/user/dy297/hpc-work/install/python/lib/python3.8/site-packages/jax/interpreters/xla.py", line 379, in _execute_compiled_primitive
    check_special(prim.name, out_bufs)
  File "/rds/user/dy297/hpc-work/install/python/lib/python3.8/site-packages/jax/interpreters/xla.py", line 398, in check_special
    _check_special(name, buf.xla_shape(), buf)
  File "/rds/user/dy297/hpc-work/install/python/lib/python3.8/site-packages/jax/interpreters/xla.py", line 406, in _check_special
    raise FloatingPointError(f"invalid value (inf) encountered in {name}")
FloatingPointError: invalid value (inf) encountered in convert_element_type

```

And it appears to be pulling up the -np.inf used to check inside `jnp.where(out == -np.inf, 0.0, sign)`

Is it expected that these sorts of condition checks inside special functions should fail the debug configs?

**Comment by jakevdp** [comment]
Thanks for the report - I'm not sure why this changed between versions, but I think I know the fix. I'll try to get it in today
