### ISSUE TITLE
Complex number support

### ISSUE THREAD

**Issue by hawkinsp** [google/jax#74]
There is some support for complex numbers already, but many things are missing. Even things as simple as:

```
np.array([[1,-2j],[2j,5]])
```

don't work. We should fix this!

**Comment by mattjj** [comment]
The root of the issue may be that `complex` (the built-in type) is missing from [this list](https://github.com/google/jax/blob/master/jax/abstract_arrays.py#L155).

**Comment by mattjj** [comment]
Indeed that fixes this particular issue. We have tests for complex types and complex differentiation, but they didn't cover this case because our tests don't include Python literals (even though they should).

I'm going to close this issue because it solves the specific issue you cited, but maybe we can reopen it (or open new ones) for any other specific issues around complex numbers.

**Comment by mgbukov** [comment]
there seems to be a problem with optimizing complex-valued cost functions (script attached):

```
warnings.warn('No GPU/TPU found, falling back to CPU.')
Traceback (most recent call last):
  File "test2.py", line 31, in <module>
    print("Initial loss: {:0.2f}".format(loss(weights, inputs, targets)))
  File "/Users/mgbukov/jax/jax/interpreters/xla.py", line 574, in __format__
    return format(self._value[()], format_spec)
ValueError: Zero padding is not allowed in complex format specifier
```

Interestingly, if the cost function is real-valued (enable line 17 from the attached script), then jax can do the optimization of complex-valued parameters. Does this seem fix-able?

TensorFlow is notorious for the lack of support of complex-valued optimization so this feature would probably be a very useful addition :)

[test2.txt](https://github.com/google/jax/files/3297714/test2.txt)

**Comment by mgbukov** [comment]
sorry, the above was a `format`, not a `jax` issue. 

Complex-valued cost/loss functions can already be handled by `jax` by passing the option `holomorphic=True` to `grad`.
