### ISSUE TITLE
np.tensordot crashes when axes=0

### ISSUE THREAD

**Issue by Thenerdstation** [google/jax#740]
```python
import jax.numpy as np
import numpy as onp

result = onp.tensordot(onp.ones((2, 3, 4)), onp.ones((5, 6, 7)), 0) 
print(result.shape) # should print (2, 3, 4, 5, 6, 7)
# This errors out.
result = np.tensordot(np.ones((2, 3, 4)), np.ones((5, 6, 7)), 0) 
```
This is the error message I receive.
```
>>> result = np.tensordot(np.ones((2, 3, 4)), np.ones((5, 6, 7)), 0) 
/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/jax/lib/xla_bridge.py:130: UserWarning: No GPU/TPU found, falling back to CPU.
  warnings.warn('No GPU/TPU found, falling back to CPU.')
Traceback (most recent call last):
  File "/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/jax/interpreters/xla.py", line 70, in primitive_computation
    return c.Build()
  File "/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/jax/lib/xla_bridge.py", line 267, in Build
    *args, **kwargs)
  File "/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/jaxlib/xla_client.py", line 640, in Build
    return Computation(self._builder.Build(), backend=backend)
RuntimeError: Invalid argument: Cannot infer shape for dot operation: f32[1,24] <dot> f32[1,210]. Contracting dimension sizes do not match.: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/jax/numpy/lax_numpy.py", line 1598, in tensordot
    out_reshape = lax.dot(a_reshape, b_reshape)
  File "/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/jax/lax/lax.py", line 462, in dot
    return dot_p.bind(lhs, rhs)
  File "/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/jax/core.py", line 117, in bind
    return self.impl(*args, **kwargs)
  File "/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/jax/interpreters/xla.py", line 51, in apply_primitive
    compiled_fun = xla_primitive_callable(prim, *abstract_args, **kwargs)
  File "/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/jax/util.py", line 174, in memoized_fun
    ans = cache[key] = fun(*args, **kwargs)
  File "/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/jax/interpreters/xla.py", line 57, in xla_primitive_callable
    built_c = primitive_computation(prim, *shapes, **kwargs)
  File "/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/jax/util.py", line 174, in memoized_fun
    ans = cache[key] = fun(*args, **kwargs)
  File "/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/jax/interpreters/xla.py", line 73, in primitive_computation
    prim.abstract_eval(*map(aval_from_xla_shape, shapes), **kwargs)
  File "/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/jax/lax/lax.py", line 1295, in standard_abstract_eval
    return ShapedArray(shape_rule(*args, **kwargs), dtype_rule(*args, **kwargs))
  File "/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/jax/lax/lax.py", line 1824, in _dot_shape_rule
    require(lhs.shape[1] == rhs.shape[0])
  File "/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/jax/lax/lax.py", line 1818, in require
    raise TypeError(msg.format(lhs.shape, rhs.shape))
TypeError: Incompatible shapes for dot: got (1, 24) and (1, 210).
```

**Comment by mattjj** [comment]
Thanks for catching this!

Our tensordot was handling the int case with expressions like `a.shape[-axes:]`, but those expressions aren't right when `axes = 0`!

#742 will squash this.
