### ISSUE TITLE
Invalid value (nan) encountered in broadcast_in_dim with logsumexp and scan

### ISSUE THREAD

**Issue by HGangloff** [google/jax#7434]
Hello,

I am stuck with an error message, it seems to involve logsumexp and scan functions that lead to NaN values appearing. I have shortened the code to a minimal example to reproduce. Am I doing something wrong ?

```python
import jax.numpy as jnp
import jax
from jax import grad as jgrad
from jax.config import config
from jax.scipy.special import logsumexp

T = 1000

config.update("jax_enable_x64", True)
config.update("jax_debug_nans", True)

A = jnp.zeros((2, 2))

def fun(A):

    a_init = jnp.array([jnp.log(0.5), jnp.log(0.5)])

    def scan_fn_a(a_t_1, t):
        a_t =  logsumexp(jnp.stack([a_t_1, a_t_1], axis=1) + A, axis=0)
        return a_t, a_t

    _, alpha = jax.lax.scan(scan_fn_a, a_init, jnp.arange(1, T, 1))

    return jnp.mean(alpha)

grad_fun = jgrad(fun)
grad_A_val = grad_fun(A)
```

Here is a shortened error message:
```
Traceback (most recent call last):
  File "jax_bug.py", line 27, in <module>
    grad_A_val = grad_fun(A)
  File "jax_bug.py", line 22, in fun
    _, alpha = jax.lax.scan(scan_fn_a, a_init, jnp.arange(1, T, 1))
FloatingPointError: invalid value (nan) encountered in broadcast_in_dim
```

Thanks

**Comment by hawkinsp** [comment]
I'm sorry it took so long to look at this, but I tried running this repro at head on CPU and GPU and it works fine for me without giving any NaNs. So I'm going to guess that the original problem is fixed!
