### ISSUE TITLE
xla_call incompatible with xla.primitive_computation

### ISSUE THREAD

**Issue by ZYHowell** [google/jax#7529]
Primitive `xla_call` has a parameter named `backend`, while `xla.primitive_computation` has a parameter with the same name. Maybe it's better for `primitive_(sub)computation` to receive a dict of all kwargs. 

An easy reproducable example is as:
```python
import jax
import jax.numpy as jnp
from jax.interpreters import xla

@jax.jit
def f(x, y):
  return jnp.dot(x, y)

x = y = jnp.ones((4, 4), dtype=jnp.float32)
jaxpr = jax.make_jaxpr(f)(x, y)
eqn = jaxpr.eqns[0]
xla.primitive_subcomputation(eqn.primitive, *map(lambda x : x.aval, eqn.invars), **eqn.params)
```

The example above raises an exception with traceback:
```
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    xla.primitive_subcomputation(eqn.primitive, *map(lambda x : x.aval, eqn.invars), **eqn.params)
  File ".../jax/jax/interpreters/xla.py", line 378, in primitive_subcomputation
    return primitive_computation(prim, axis_env, None, False, *avals, **params)
  File ".../jax/jax/_src/util.py", line 186, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
  File ".../jax/jax/_src/util.py", line 179, in cached
    return f(*args, **kwargs)
TypeError: primitive_computation() got multiple values for argument 'backend'
```

**Comment by mattjj** [comment]
Thanks for surfacing this! These are internal API functions, and AIUI we don't expect ever to call `xla.primitive_subcomputation` with an `xla_call` primitive.

But you make a great point, this is a problem with splatting out keyword arguments!

Unless this is blocking your work somehow, I might mark this as a low-priority bug...

cc @LenaMartens tangentially because she was looking at unrelated "backend" cleanups.
