### ISSUE TITLE
`jnp.apply_along_axis` errors, but numpy works

### ISSUE THREAD

**Issue by wangleiphy** [google/jax#7542]
```python
import numpy as np 
import jax.numpy as jnp

>>> x = np.array([[0, 0, 1, 1], [1, 1, 0, 0], [0, 1, 1, 0]])
>>> np.apply_along_axis(np.where, 1, x).squeeze()
array([[2, 3],
       [0, 1],
       [1, 2]])
>>> jnp.apply_along_axis(jnp.where, 1, x).squeeze()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wanglei/anaconda3/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 3702, in apply_along_axis
    return func(arr)
  File "/home/wanglei/anaconda3/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 3697, in <lambda>
    func = lambda arr: func1d(arr, *args, **kwargs)
  File "/home/wanglei/anaconda3/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 1698, in where
    return nonzero(asarray(condition))
  File "/home/wanglei/anaconda3/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 2268, in nonzero
    a = core.concrete_or_error(atleast_1d, a, "The error arose in jnp.nonzero")
jax._src.traceback_util.FilteredStackTrace: jax._src.errors.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: Traced<ShapedArray(int32[4])>with<BatchTrace(level=1/0)>
  with val = array([[0, 0, 1, 1],
                    [1, 1, 0, 0],
                    [0, 1, 1, 0]])
       batch_dim = 0
The error arose in jnp.nonzero

 (https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError)

The stack trace above excludes JAX-internal frames.
The following is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wanglei/anaconda3/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 3702, in apply_along_axis
    return func(arr)
  File "/home/wanglei/anaconda3/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 139, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/wanglei/anaconda3/lib/python3.8/site-packages/jax/api.py", line 1223, in batched_fun
    out_flat = batching.batch(
  File "/home/wanglei/anaconda3/lib/python3.8/site-packages/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/wanglei/anaconda3/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 3697, in <lambda>
    func = lambda arr: func1d(arr, *args, **kwargs)
  File "/home/wanglei/anaconda3/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 1698, in where
    return nonzero(asarray(condition))
  File "/home/wanglei/anaconda3/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 2268, in nonzero
    a = core.concrete_or_error(atleast_1d, a, "The error arose in jnp.nonzero")
  File "/home/wanglei/anaconda3/lib/python3.8/site-packages/jax/core.py", line 968, in concrete_or_error
    raise ConcretizationTypeError(val, context)
jax._src.errors.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: Traced<ShapedArray(int32[4])>with<BatchTrace(level=1/0)>
  with val = array([[0, 0, 1, 1],
                    [1, 1, 0, 0],
                    [0, 1, 1, 0]])
       batch_dim = 0
The error arose in jnp.nonzero

 (https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError)

**Comment by jakevdp** [comment]
Thanks for the report!

This comes from the fact that one-argument `jnp.where` has output shape that is dependent on values in the input, and therefore is not compatible with JAX transformation. A more direct way to surface this error is:
```python
jit(jnp.where)(jnp.arange(5))
```
Because `apply_along_axis` is implemented via `vmap`, the function you pass to it must be compatible with JAX transforms.

You can work around this by using the equivalent `nonzero` function along with the static `size` argument to specify the size of the ouput:
```python
>>> jnp.apply_along_axis(jnp.nonzero, 1, x, size=2)
(DeviceArray([[2, 3],
              [0, 1],
              [1, 2]], dtype=int32),)
```

**Comment by wangleiphy** [comment]
Thanks! It is clear to me now. 
It is good to know there is a `size` argument of `jnp.nonzero`! 

BTW, I was doing this as a work around before knowing the `size` trick: 
```python 
>>> jnp.argsort(x)[:, -2:]
DeviceArray([[2, 3],
             [0, 1],
             [1, 2]], dtype=int32)
```
I guess `jnp.nonzero` will be more efficient for this purpose.

**Comment by mattjj** [comment]
Thanks for raising this! I'm going to close it because I _think_ it's solved, but please reopen if I'm mistaken.
