### ISSUE TITLE
Jaxlib build failed: Check the visibility declaration of the former target if you think the dependency is legitimate

### ISSUE THREAD

**Issue by tataudat** [google/jax#7623]
When I tried to run `python build/build.py --enable_cuda` to build jaxlib from source, this error occur:

```
(jax) ➜  jax git:(563e08fa) python build/build.py --enable_cuda


     _   _  __  __
    | | / \ \ \/ /
 _  | |/ _ \ \  /
| |_| / ___ \/  \
 \___/_/   \/_/\_\


Bazel binary path: ./bazel-4.1.0-linux-x86_64
Python binary path: /home/dat/frameworks/miniconda3/envs/jax/bin/python
Python version: 3.8
NumPy version: 1.20.3
SciPy version: 1.6.2
MKL-DNN enabled: yes
Target CPU: x86_64
Target CPU features: release
CUDA enabled: yes
CUDA compute capabilities: 3.5,5.2,6.0,6.1,7.0
NCCL enabled: yes
TPU enabled: no
ROCm enabled: no

Building XLA and installing it in the jaxlib source tree...
./bazel-4.1.0-linux-x86_64 run --verbose_failures=true --config=avx_posix --config=mkl_open_source_only --config=cuda :build_wheel -- --output_path=/home/dat/resources/src/scientific-computing/jax/jax/dist --cpu=x86_64
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'run' from /home/dat/resources/src/scientific-computing/jax/jax/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'run' from /home/dat/resources/src/scientific-computing/jax/jax/.bazelrc:
  Inherited 'build' options: --apple_platform_type=macos --macos_minimum_os=10.9 --announce_rc --define open_source_build=true --spawn_strategy=standalone --strategy=Genrule=standalone --enable_platform_specific_config --define=no_aws_support=true --define=no_gcp_support=true --define=no_hdfs_support=true --define=no_kafka_support=true --define=no_ignite_support=true --define=grpc_no_ares=true -c opt --config=short_logs
INFO: Reading rc options for 'run' from /home/dat/resources/src/scientific-computing/jax/jax/.jax_configure.bazelrc:
  Inherited 'build' options: --repo_env PYTHON_BIN_PATH=/home/dat/frameworks/miniconda3/envs/jax/bin/python --action_env=PYENV_ROOT --python_path=/home/dat/frameworks/miniconda3/envs/jax/bin/python --distinct_host_configuration=false
INFO: Found applicable config definition build:short_logs in file /home/dat/resources/src/scientific-computing/jax/jax/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:avx_posix in file /home/dat/resources/src/scientific-computing/jax/jax/.bazelrc: --copt=-mavx --host_copt=-mavx
INFO: Found applicable config definition build:mkl_open_source_only in file /home/dat/resources/src/scientific-computing/jax/jax/.bazelrc: --define=tensorflow_mkldnn_contraction_kernel=1
INFO: Found applicable config definition build:cuda in file /home/dat/resources/src/scientific-computing/jax/jax/.bazelrc: --repo_env TF_NEED_CUDA=1 --action_env=TF_CUDA_COMPUTE_CAPABILITIES=3.5,5.2,6.0,6.1,7.0 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda --define=xla_python_enable_gpu=true
INFO: Found applicable config definition build:linux in file /home/dat/resources/src/scientific-computing/jax/jax/.bazelrc: --config=posix --copt=-Wno-stringop-truncation
INFO: Found applicable config definition build:posix in file /home/dat/resources/src/scientific-computing/jax/jax/.bazelrc: --copt=-Wno-sign-compare --cxxopt=-std=c++14 --host_cxxopt=-std=c++14
DEBUG: /home/dat/.cache/bazel/_bazel_dat/f8fc504cbc33979a512a89dbfa606d4a/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:118:10: 
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
Loading:  (0 packages loaded)
Loading: 0 packages loaded
Analyzing: target //build:build_wheel (0 packages loaded, 0 targets configured)
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1596824487 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  /home/dat/resources/src/scientific-computing/jax/jax/WORKSPACE:37:14: in <toplevel>
  /home/dat/.cache/bazel/_bazel_dat/f8fc504cbc33979a512a89dbfa606d4a/external/org_tensorflow/tensorflow/workspace0.bzl:108:34: in workspace
  /home/dat/.cache/bazel/_bazel_dat/f8fc504cbc33979a512a89dbfa606d4a/external/bazel_toolchains/repositories/repositories.bzl:35:23: in repositories
Repository rule git_repository defined at:
  /home/dat/.cache/bazel/_bazel_dat/f8fc504cbc33979a512a89dbfa606d4a/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
**ERROR: /home/dat/resources/src/scientific-computing/jax/jax/jaxlib/BUILD:245:13: in cc_library rule //jaxlib:cuda_lu_pivot_kernels_lib: target '@org_tensorflow//tensorflow/compiler/xla/service:custom_call_status' is not visible from target '//jaxlib:cuda_lu_pivot_kernels_lib'. Check the visibility declaration of the former target if you think the dependency is legitimate**
**ERROR: Analysis of target '//build:build_wheel' failed; build aborted: Analysis of target '//jaxlib:cuda_lu_pivot_kernels_lib' failed**
INFO: Elapsed time: 0.161s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 1 target configured)
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully (0 packages loaded, 1 target configured)
b''
Traceback (most recent call last):
  File "build/build.py", line 522, in <module>
    main()
  File "build/build.py", line 517, in main
    shell(command)
  File "build/build.py", line 53, in shell
    output = subprocess.check_output(cmd)
  File "/home/dat/frameworks/miniconda3/envs/jax/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/dat/frameworks/miniconda3/envs/jax/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['./bazel-4.1.0-linux-x86_64', 'run', '--verbose_failures=true', '--config=avx_posix', '--config=mkl_open_source_only', '--config=cuda', ':build_wheel', '--', '--output_path=/home/dat/resources/src/scientific-computing/jax/jax/dist', '--cpu=x86_64']' returned non-zero exit status 1.
```

All the dependencies are satisfied. Output from `nvidia-smi`:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:43:00.0  On |                  N/A |
|  0%   36C    P8    33W / 300W |   1039MiB / 11016MiB |      7%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Comment by mattjj** [comment]
@yashk2810 , can you take a look? Seems like a visibility error...

**Comment by yashk2810** [comment]
Yeah, we just need to update the commit status here: https://github.com/google/jax/blob/main/WORKSPACE#L11

I can send a PR shortly.

**Comment by yashk2810** [comment]
https://github.com/google/jax/pull/7624 should fix
