### ISSUE TITLE
Jaxlib : Compiling/Building from source failed (Linux, cuda enabled)

### ISSUE THREAD

**Issue by Corentin-pro** [google/jax#7712]
Trying to build `jaxlib` from source as stated in [the documentation](https://jax.readthedocs.io/en/latest/developer.html#building-jaxlib-from-source) fails.

## Commit used

The `jax-v0.2.19` fails because of wrong repository/hash (see [other issue](https://github.com/google/jax/issues/7623)), this is fixed in `main`

Both `main` or `jaxlib-v0.1.70` have been tested with same output, here 'main' is used.

## Environment

Tested on up-to-date ArchLinux (Linux 5.13.12)

### GCC 11.1

```
$ gcc --version
gcc (GCC) 11.1.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

### CUDA/NVCC 11.4

```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Wed_Jul_14_19:41:19_PDT_2021
Cuda compilation tools, release 11.4, V11.4.100
Build cuda_11.4.r11.4/compiler.30188945_0
```

### Python 3.9.6

```
$ python --version
Python 3.9.6
```

###  Bazel 0.29

```
$ bazel --version
bazel 0.29.1- (@non-git)
```

## Compilation log

The command used is `python build/build.py --enable_cuda --cuda_path /opt/cuda --cudnn_path /usr`.

Without the `cuda_path` `cuda.h` is not found, without 'cdnn_path' `cudnn.h` is not found (looking into sub-folders of cuda_path).

```

     _   _  __  __
    | | / \ \ \/ /
 _  | |/ _ \ \  /
| |_| / ___ \/  \
 \___/_/   \/_/\_\


Bazel binary path: ./bazel-4.1.0-linux-x86_64
Python binary path: /usr/bin/python
Python version: 3.9
NumPy version: 1.20.3
SciPy version: 1.7.1
MKL-DNN enabled: yes
Target CPU: x86_64
Target CPU features: release
CUDA enabled: yes
CUDA toolkit path: /opt/cuda
CUDNN library path: /usr
NCCL enabled: yes
TPU enabled: no
ROCm enabled: no

Building XLA and installing it in the jaxlib source tree...
./bazel-4.1.0-linux-x86_64 run --verbose_failures=true --config=avx_posix --config=mkl_open_source_only --config=cuda :build_wheel -- --output_path=/home/corentin/tools/jax/dist --cpu=x86_64
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'run' from /home/corentin/tools/jax/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'run' from /home/corentin/tools/jax/.bazelrc:
  Inherited 'build' options: --apple_platform_type=macos --macos_minimum_os=10.9 --announce_rc --define open_source_build=true --spawn_strategy=standalone --enable_platform_specific_config --define=no_aws_support=true --define=no_gcp_support=true --define=no_hdfs_support=true --define=no_kafka_support=true --define=no_ignite_support=true --define=grpc_no_ares=true -c opt --config=short_logs
INFO: Reading rc options for 'run' from /home/corentin/tools/jax/.jax_configure.bazelrc:
  Inherited 'build' options: --strategy=Genrule=standalone --repo_env PYTHON_BIN_PATH=/usr/bin/python --action_env=PYENV_ROOT --python_path=/usr/bin/python --action_env CUDA_TOOLKIT_PATH=/opt/cuda --action_env CUDNN_INSTALL_PATH=/usr --action_env TF_CUDA_PATHS=/opt/cuda,/usr --distinct_host_configuration=false
INFO: Found applicable config definition build:short_logs in file /home/corentin/tools/jax/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:avx_posix in file /home/corentin/tools/jax/.bazelrc: --copt=-mavx --host_copt=-mavx
INFO: Found applicable config definition build:mkl_open_source_only in file /home/corentin/tools/jax/.bazelrc: --define=tensorflow_mkldnn_contraction_kernel=1
INFO: Found applicable config definition build:cuda in file /home/corentin/tools/jax/.bazelrc: --repo_env TF_NEED_CUDA=1 --action_env TF_CUDA_COMPUTE_CAPABILITIES=3.5,5.2,6.0,6.1,7.0 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda --define=xla_python_enable_gpu=true
INFO: Found applicable config definition build:linux in file /home/corentin/tools/jax/.bazelrc: --config=posix --copt=-Wno-stringop-truncation
INFO: Found applicable config definition build:posix in file /home/corentin/tools/jax/.bazelrc: --copt=-Wno-sign-compare --cxxopt=-std=c++14 --host_cxxopt=-std=c++14
WARNING: Download from http://mirror.tensorflow.org/github.com/tensorflow/runtime/archive/25862028b6af73e05ea365100e2b27f72b29e874.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/fda176892e64b093996763465338863067e5b09e.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
DEBUG: /home/corentin/.cache/bazel/_bazel_corentin/a0fa63890cb5b3a952ed96be718f0989/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:118:10: 
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
Loading:  (1 packages loaded)
Loading: 1 packages loaded
Analyzing: target //build:build_wheel (2 packages loaded, 0 targets configured)
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1596824487 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  /home/corentin/tools/jax/WORKSPACE:37:14: in <toplevel>
  /home/corentin/.cache/bazel/_bazel_corentin/a0fa63890cb5b3a952ed96be718f0989/external/org_tensorflow/tensorflow/workspace0.bzl:108:34: in workspace
  /home/corentin/.cache/bazel/_bazel_corentin/a0fa63890cb5b3a952ed96be718f0989/external/bazel_toolchains/repositories/repositories.bzl:35:23: in repositories
Repository rule git_repository defined at:
  /home/corentin/.cache/bazel/_bazel_corentin/a0fa63890cb5b3a952ed96be718f0989/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
Analyzing: target //build:build_wheel (15 packages loaded, 12 targets configured)
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/NVIDIA/cudnn-frontend/archive/73210a930333eaf66b42b01693bce7b70719c354.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Analyzed target //build:build_wheel (196 packages loaded, 15228 targets configured).
INFO: Found 1 target...
[0 / 42] [Prepa] Writing file jaxlib/cuda_lu_pivot_kernels.so-2.params ... (2 actions, 0 running)
[1,832 / 2,565] Compiling tensorflow/core/platform/default/env_time.cc; 1s local ... (12 actions, 11 running)
[2,076 / 2,565] Compiling src/google/protobuf/descriptor.cc; 4s local ... (12 actions, 11 running)
[2,301 / 2,614] Compiling jaxlib/cuda_lu_pivot_kernels.cu.cc; 3s local ... (12 actions, 11 running)
[2,634 / 3,720] Compiling external/org_tensorflow/tensorflow/core/protobuf/meta_graph.pb.cc; 8s local ... (12 actions, 11 running)
[3,039 / 4,070] Compiling external/org_tensorflow/tensorflow/core/protobuf/meta_graph.pb.cc; 9s local ... (12 actions, 11 running)
[3,466 / 4,508] Compiling llvm/lib/Support/CommandLine.cpp; 3s local ... (12 actions, 11 running)
[4,008 / 5,014] Compiling llvm/utils/TableGen/GlobalISelEmitter.cpp; 16s local ... (12 actions, 11 running)
[4,432 / 5,398] Compiling mlir/lib/Dialect/LLVMIR/IR/LLVMDialect.cpp; 42s local ... (12 actions, 11 running)
[4,676 / 5,651] Compiling llvm/lib/Transforms/Utils/SimplifyCFG.cpp; 15s local ... (12 actions, 11 running)
[4,940 / 5,882] Compiling src/cpu/x64/gemm/f32/jit_avx_f32_copy_at_kern_autogen.cpp; 6s local ... (12 actions, 11 running)
[5,143 / 6,330] Compiling llvm/lib/Transforms/Vectorize/LoopVectorize.cpp; 20s local ... (12 actions, 11 running)
[5,333 / 6,330] Compiling llvm/lib/CodeGen/MIRParser/MIParser.cpp; 7s local ... (12 actions, 11 running)
[5,717 / 6,822] Compiling external/nccl_archive/src/collectives/device/min_i8_all_reduce.cu.cc; 41s local ... (12 actions, 11 running)
[5,955 / 6,941] Compiling external/nccl_archive/src/collectives/device/min_u64_all_reduce.cu.cc; 34s local ... (12 actions, 11 running)
[6,149 / 7,214] Compiling external/nccl_archive/src/collectives/device/sum_f16_all_reduce.cu.cc; 49s local ... (12 actions, 11 running)
[6,314 / 7,257] Compiling external/nccl_archive/src/collectives/device/max_f16_all_reduce.cu.cc; 44s local ... (12 actions, 11 running)
ERROR: /home/corentin/.cache/bazel/_bazel_corentin/a0fa63890cb5b3a952ed96be718f0989/external/boringssl/BUILD:130:11: Compiling src/third_party/fiat/curve25519.c failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home/corentin/.cache/bazel/_bazel_corentin/a0fa63890cb5b3a952ed96be718f0989/execroot/__main__ && \
  exec env - \
    CUDA_TOOLKIT_PATH=/opt/cuda \
    CUDNN_INSTALL_PATH=/usr \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/corentin/.local/bin:/home/corentin/.config/yarn/global/node_modules/.bin \
    PWD=/proc/self/cwd \
    TF_CUDA_COMPUTE_CAPABILITIES=3.5,5.2,6.0,6.1,7.0 \
    TF_CUDA_PATHS=/opt/cuda,/usr \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/external/boringssl/_objs/crypto/curve25519.pic.d '-frandom-seed=bazel-out/k8-opt/bin/external/boringssl/_objs/crypto/curve25519.pic.o' -iquote external/boringssl -iquote bazel-out/k8-opt/bin/external/boringssl -isystem external/boringssl/src/include -isystem bazel-out/k8-opt/bin/external/boringssl/src/include -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fPIC -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -fno-omit-frame-pointer -no-canonical-prefixes -fno-canonical-system-headers -DNDEBUG -g0 -O2 -ffunction-sections -fdata-sections -Wno-sign-compare -Wno-stringop-truncation -mavx -Wa,--noexecstack '-D_XOPEN_SOURCE=700' -Wall -Werror '-Wformat=2' -Wsign-compare -Wmissing-field-initializers -Wwrite-strings -Wshadow -fno-common '-std=c11' -Wmissing-prototypes -Wold-style-definition -Wstrict-prototypes -c external/boringssl/src/third_party/fiat/curve25519.c -o bazel-out/k8-opt/bin/external/boringssl/_objs/crypto/curve25519.pic.o)
Execution platform: @local_execution_config_platform//:platform
external/boringssl/src/third_party/fiat/curve25519.c:511:57: error: argument 2 of type 'const uint8_t[32]' {aka 'const unsigned char[32]'} with mismatched bound [-Werror=array-parameter=]
  511 | int x25519_ge_frombytes_vartime(ge_p3 *h, const uint8_t s[32]) {
      |                                           ~~~~~~~~~~~~~~^~~~~
In file included from external/boringssl/src/third_party/fiat/curve25519.c:41:
external/boringssl/src/third_party/fiat/internal.h:117:58: note: previously declared as 'const uint8_t *' {aka 'const unsigned char *'}
  117 | int x25519_ge_frombytes_vartime(ge_p3 *h, const uint8_t *s);
      |                                           ~~~~~~~~~~~~~~~^
external/boringssl/src/third_party/fiat/curve25519.c:831:57: error: argument 2 of type 'const uint8_t *' {aka 'const unsigned char *'} declared as a pointer [-Werror=array-parameter=]
  831 | void x25519_ge_scalarmult_base(ge_p3 *h, const uint8_t *a) {
      |                                          ~~~~~~~~~~~~~~~^
In file included from external/boringssl/src/third_party/fiat/curve25519.c:41:
external/boringssl/src/third_party/fiat/internal.h:125:56: note: previously declared as an array 'const uint8_t[32]' {aka 'const unsigned char[32]'}
  125 | void x25519_ge_scalarmult_base(ge_p3 *h, const uint8_t a[32]);
      |                                          ~~~~~~~~~~~~~~^~~~~
cc1: all warnings being treated as errors
Target //build:build_wheel failed to build
INFO: Elapsed time: 1382.702s, Critical Path: 85.32s
INFO: 7118 processes: 2836 internal, 4282 local.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully
b''
Traceback (most recent call last):
  File "/home/corentin/tools/jax/build/build.py", line 513, in <module>
    main()
  File "/home/corentin/tools/jax/build/build.py", line 508, in main
    shell(command)
  File "/home/corentin/tools/jax/build/build.py", line 53, in shell
    output = subprocess.check_output(cmd)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['./bazel-4.1.0-linux-x86_64', 'run', '--verbose_failures=true', '--config=avx_posix', '--config=mkl_open_source_only', '--config=cuda', ':build_wheel', '--', '--output_path=/home/corentin/tools/jax/dist', '--cpu=x86_64']' returned non-zero exit status 1.
```

**Comment by yashk2810** [comment]
This looks like an error in boringssl dependency. Maybe try bumping up the version here: https://source.corp.google.com/piper///depot/google3/third_party/tensorflow/workspace2.bzl;l=694?q=f:tensorflow%20boringssl&ct=os&sq=package:piper%20file:%2F%2Fdepot%2Fgoogle3%20-file:google3%2Fexperimental

and then use this flag `override_repository`.

```
python build/build.py --override_repository=org_tensorflow="$PWD"/tensorflow
```

Note: The path to org_tensorflow should be absolute path to the tensorflow directory. Given that TF hasn't hit this when building with 11.4 yet, I don't know what could be causing this, but when I build JAX with cuda 11.4, I can post the update here on how it goes.

**Comment by Corentin-pro** [comment]
The `override_repository` doesn't exists on the main branch at least (just pulled):

```
> python build/build.py --override_repository=org_tensorflow="$PWD"/tensorflow
usage: build.py [-h] [--bazel_path BAZEL_PATH] [--python_bin_path PYTHON_BIN_PATH]
                [--target_cpu_features {release,native,default}] [--enable_mkl_dnn [ENABLE_MKL_DNN] |
                --noenable_mkl_dnn] [--enable_cuda [ENABLE_CUDA] | --noenable_cuda] [--enable_tpu [ENABLE_TPU] |
                --noenable_tpu] [--enable_rocm [ENABLE_ROCM] | --noenable_rocm] [--enable_nccl [ENABLE_NCCL] |
                --noenable_nccl] [--remote_build [REMOTE_BUILD] | --noremote_build] [--cuda_path CUDA_PATH]
                [--cudnn_path CUDNN_PATH] [--cuda_version CUDA_VERSION] [--cudnn_version CUDNN_VERSION]
                [--rocm_path ROCM_PATH] [--bazel_startup_options BAZEL_STARTUP_OPTIONS]
                [--bazel_options BAZEL_OPTIONS] [--output_path OUTPUT_PATH] [--target_cpu TARGET_CPU]
build.py: error: unrecognized arguments: --override_repository=org_tensorflow=/home/corentin/tools/jax/tensorflow
```

**Comment by yashk2810** [comment]
I think you'll need to use the bazel_options flag if you are passing it to build.py

**Comment by Corentin-pro** [comment]
Tell me how it works (and also what version to bump for boringssl) because `build.py: error: argument --bazel_options: expected one argument`

**Comment by hawkinsp** [comment]
I'm guessing this issue is long fixed. Please reopen if it's still a problem!
