### ISSUE TITLE
Jaxlib 0.1.71 Fails to Build on Windows

### ISSUE THREAD

**Issue by oracle3001** [google/jax#7786]
With Python 3.9, Cuda 11.2, Bazel 4.1, build run with the following command

python .\build\build.py --enable_cuda --cuda_path="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2" --cudnn_path="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2" --cuda_version="11.2" --cudnn_version="8.1.0" --noenable_rocm --noenable_tpu

results in the following error.

```
ERROR: An error occurred during the fetch of repository 'llvm-project':
   Traceback (most recent call last):
        File "C:/users/adam/_bazel_adam/4ijt6ef5/external/llvm-raw/utils/bazel/configure.bzl", line 73, column 25, in _llvm_configure_impl
                _overlay_directories(repository_ctx)
        File "C:/users/adam/_bazel_adam/4ijt6ef5/external/llvm-raw/utils/bazel/configure.bzl", line 62, column 13, in _overlay_directories
                fail(("Failed to execute overlay script: '{cmd}'\n" +
Error in fail: Failed to execute overlay script: 'C:/Users/Adam/anaconda3/envs/jax39/python.exe C:/users/adam/_bazel_adam/4ijt6ef5/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/adam/_bazel_adam/4ijt6ef5/external/llvm-raw --overlay C:/users/adam/_bazel_adam/4ijt6ef5/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 1
stdout:

stderr:
Traceback (most recent call last):
  File "C:\users\adam\_bazel_adam\4ijt6ef5\external\llvm-raw\utils\bazel\overlay_directories.py", line 92, in <module>
    main(parse_arguments())
  File "C:\users\adam\_bazel_adam\4ijt6ef5\external\llvm-raw\utils\bazel\overlay_directories.py", line 80, in main
    _symlink_abs(os.path.join(args.overlay, relpath),
  File "C:\users\adam\_bazel_adam\4ijt6ef5\external\llvm-raw\utils\bazel\overlay_directories.py", line 64, in _symlink_abs
    os.symlink(os.path.abspath(from_path), os.path.abspath(to_path))
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\users\\adam\\_bazel_adam\\4ijt6ef5\\external\\llvm-raw\\utils\\bazel\\llvm-project-overlay\\.bazelignore' -> 'C:\\users\\adam\\_bazel_adam\\4ijt6ef5\\external\\llvm-project\\.bazelignore'

ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/users/adam/_bazel_adam/4ijt6ef5/external/llvm-raw/utils/bazel/configure.bzl", line 73, column 25, in _llvm_configure_impl
                _overlay_directories(repository_ctx)
        File "C:/users/adam/_bazel_adam/4ijt6ef5/external/llvm-raw/utils/bazel/configure.bzl", line 62, column 13, in _overlay_directories
                fail(("Failed to execute overlay script: '{cmd}'\n" +
Error in fail: Failed to execute overlay script: 'C:/Users/Adam/anaconda3/envs/jax39/python.exe C:/users/adam/_bazel_adam/4ijt6ef5/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/adam/_bazel_adam/4ijt6ef5/external/llvm-raw --overlay C:/users/adam/_bazel_adam/4ijt6ef5/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 1
stdout:

stderr:
Traceback (most recent call last):
  File "C:\users\adam\_bazel_adam\4ijt6ef5\external\llvm-raw\utils\bazel\overlay_directories.py", line 92, in <module>
    main(parse_arguments())
  File "C:\users\adam\_bazel_adam\4ijt6ef5\external\llvm-raw\utils\bazel\overlay_directories.py", line 80, in main
    _symlink_abs(os.path.join(args.overlay, relpath),
  File "C:\users\adam\_bazel_adam\4ijt6ef5\external\llvm-raw\utils\bazel\overlay_directories.py", line 64, in _symlink_abs
    os.symlink(os.path.abspath(from_path), os.path.abspath(to_path))
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\users\\adam\\_bazel_adam\\4ijt6ef5\\external\\llvm-raw\\utils\\bazel\\llvm-project-overlay\\.bazelignore' -> 'C:\\users\\adam\\_bazel_adam\\4ijt6ef5\\external\\llvm-project\\.bazelignore'

INFO: Repository double_conversion instantiated at:
  C:/sdks/jax-jaxlib-v0.1.71/WORKSPACE:31:14: in <toplevel>
  C:/users/adam/_bazel_adam/4ijt6ef5/external/org_tensorflow/tensorflow/workspace2.bzl:1091:21: in workspace
  C:/users/adam/_bazel_adam/4ijt6ef5/external/org_tensorflow/tensorflow/workspace2.bzl:871:20: in _tf_repositories
  C:/users/adam/_bazel_adam/4ijt6ef5/external/org_tensorflow/third_party/repo.bzl:113:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  C:/users/adam/_bazel_adam/4ijt6ef5/external/org_tensorflow/third_party/repo.bzl:66:35: in <toplevel>
INFO: Repository 'double_conversion' used the following cache hits instead of downloading the corresponding file.
 * Hash '2f7fbffac0d98d201ad0586f686034371a6d152ca67508ab611adc2386ad30de' for https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/double-conversion/archive/3992066a95b823efc8ccc1baf82a1cfc73f6e9b8.zip
If the definition of 'double_conversion' was updated, verify that the hashes were also updated.
INFO: Repository farmhash_archive instantiated at:
  C:/sdks/jax-jaxlib-v0.1.71/WORKSPACE:31:14: in <toplevel>
  C:/users/adam/_bazel_adam/4ijt6ef5/external/org_tensorflow/tensorflow/workspace2.bzl:1084:28: in workspace
  C:/users/adam/_bazel_adam/4ijt6ef5/external/org_tensorflow/tensorflow/workspace2.bzl:66:13: in _initialize_third_party
  C:/users/adam/_bazel_adam/4ijt6ef5/external/org_tensorflow/third_party/farmhash/workspace.bzl:14:20: in repo
  C:/users/adam/_bazel_adam/4ijt6ef5/external/org_tensorflow/third_party/repo.bzl:113:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  C:/users/adam/_bazel_adam/4ijt6ef5/external/org_tensorflow/third_party/repo.bzl:66:35: in <toplevel>
INFO: Repository eigen_archive instantiated at:
  C:/sdks/jax-jaxlib-v0.1.71/WORKSPACE:31:14: in <toplevel>
  C:/users/adam/_bazel_adam/4ijt6ef5/external/org_tensorflow/tensorflow/workspace2.bzl:1084:28: in workspace
  C:/users/adam/_bazel_adam/4ijt6ef5/external/org_tensorflow/tensorflow/workspace2.bzl:65:11: in _initialize_third_party
  C:/users/adam/_bazel_adam/4ijt6ef5/external/org_tensorflow/third_party/eigen3/workspace.bzl:14:20: in repo
  C:/users/adam/_bazel_adam/4ijt6ef5/external/org_tensorflow/third_party/repo.bzl:113:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  C:/users/adam/_bazel_adam/4ijt6ef5/external/org_tensorflow/third_party/repo.bzl:66:35: in <toplevel>
ERROR: C:/users/adam/_bazel_adam/4ijt6ef5/external/org_tensorflow/tensorflow/compiler/xla/service/BUILD:1155:11: @org_tensorflow//tensorflow/compiler/xla/service:gpu_plugin_impl depends on @org_tensorflow//tensorflow/compiler/xla/service/gpu:gpu_compiler in repository @org_tensorflow which failed to fetch. no such package '@llvm-project//mlir': Failed to execute overlay script: 'C:/Users/Adam/anaconda3/envs/jax39/python.exe C:/users/adam/_bazel_adam/4ijt6ef5/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/adam/_bazel_adam/4ijt6ef5/external/llvm-raw --overlay C:/users/adam/_bazel_adam/4ijt6ef5/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 1
stdout:

stderr:
Traceback (most recent call last):
  File "C:\users\adam\_bazel_adam\4ijt6ef5\external\llvm-raw\utils\bazel\overlay_directories.py", line 92, in <module>
    main(parse_arguments())
  File "C:\users\adam\_bazel_adam\4ijt6ef5\external\llvm-raw\utils\bazel\overlay_directories.py", line 80, in main
    _symlink_abs(os.path.join(args.overlay, relpath),
  File "C:\users\adam\_bazel_adam\4ijt6ef5\external\llvm-raw\utils\bazel\overlay_directories.py", line 64, in _symlink_abs
    os.symlink(os.path.abspath(from_path), os.path.abspath(to_path))
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\users\\adam\\_bazel_adam\\4ijt6ef5\\external\\llvm-raw\\utils\\bazel\\llvm-project-overlay\\.bazelignore' -> 'C:\\users\\adam\\_bazel_adam\\4ijt6ef5\\external\\llvm-project\\.bazelignore'

ERROR: C:/users/adam/_bazel_adam/4ijt6ef5/external/org_tensorflow/tensorflow/compiler/xla/service/BUILD:1155:11: @org_tensorflow//tensorflow/compiler/xla/service:gpu_plugin_impl depends on @org_tensorflow//tensorflow/compiler/xla/service/gpu:gpu_transfer_manager in repository @org_tensorflow which failed to fetch. no such package '@llvm-project//mlir': Failed to execute overlay script: 'C:/Users/Adam/anaconda3/envs/jax39/python.exe C:/users/adam/_bazel_adam/4ijt6ef5/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/adam/_bazel_adam/4ijt6ef5/external/llvm-raw --overlay C:/users/adam/_bazel_adam/4ijt6ef5/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 1
stdout:

stderr:
Traceback (most recent call last):
  File "C:\users\adam\_bazel_adam\4ijt6ef5\external\llvm-raw\utils\bazel\overlay_directories.py", line 92, in <module>
    main(parse_arguments())
  File "C:\users\adam\_bazel_adam\4ijt6ef5\external\llvm-raw\utils\bazel\overlay_directories.py", line 80, in main
    _symlink_abs(os.path.join(args.overlay, relpath),
  File "C:\users\adam\_bazel_adam\4ijt6ef5\external\llvm-raw\utils\bazel\overlay_directories.py", line 64, in _symlink_abs
    os.symlink(os.path.abspath(from_path), os.path.abspath(to_path))
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\users\\adam\\_bazel_adam\\4ijt6ef5\\external\\llvm-raw\\utils\\bazel\\llvm-project-overlay\\.bazelignore' -> 'C:\\users\\adam\\_bazel_adam\\4ijt6ef5\\external\\llvm-project\\.bazelignore'

ERROR: C:/users/adam/_bazel_adam/4ijt6ef5/external/org_tensorflow/tensorflow/compiler/xla/service/BUILD:1155:11: @org_tensorflow//tensorflow/compiler/xla/service:gpu_plugin_impl depends on @org_tensorflow//tensorflow/compiler/xla/service/gpu:nvptx_compiler in repository @org_tensorflow which failed to fetch. no such package '@llvm-project//mlir': Failed to execute overlay script: 'C:/Users/Adam/anaconda3/envs/jax39/python.exe C:/users/adam/_bazel_adam/4ijt6ef5/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/adam/_bazel_adam/4ijt6ef5/external/llvm-raw --overlay C:/users/adam/_bazel_adam/4ijt6ef5/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 1
stdout:

stderr:
Traceback (most recent call last):
  File "C:\users\adam\_bazel_adam\4ijt6ef5\external\llvm-raw\utils\bazel\overlay_directories.py", line 92, in <module>
    main(parse_arguments())
  File "C:\users\adam\_bazel_adam\4ijt6ef5\external\llvm-raw\utils\bazel\overlay_directories.py", line 80, in main
    _symlink_abs(os.path.join(args.overlay, relpath),
  File "C:\users\adam\_bazel_adam\4ijt6ef5\external\llvm-raw\utils\bazel\overlay_directories.py", line 64, in _symlink_abs
    os.symlink(os.path.abspath(from_path), os.path.abspath(to_path))
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\users\\adam\\_bazel_adam\\4ijt6ef5\\external\\llvm-raw\\utils\\bazel\\llvm-project-overlay\\.bazelignore' -> 'C:\\users\\adam\\_bazel_adam\\4ijt6ef5\\external\\llvm-project\\.bazelignore'

ERROR: Analysis of target '//build:build_wheel' failed; build aborted: Analysis failed
INFO: Elapsed time: 200.340s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (116 packages loaded, 1302 targets\
FAILED: Build did NOT complete successfully (116 packages loaded, 1302 targets\
 configured)
    currently loading: @org_tensorflow//tensorflow/compiler/xla/service/gpu ..\
. (3 packages)
    Fetching @cython; fetching
    Fetching ...cython; Extracting C:/users/adam/_bazel_adam/4ijt6ef5/external\
/cython/temp1625008697659128040/0.29.21.tar.gz
    Fetching ...ersion; Extracting C:/users/adam/_bazel_adam/4ijt6ef5/external\
/double_conversion/temp11808560150991477933/3992066a95b823efc8ccc1baf82a1cfc73\
f6e9b8.zip
    Fetching @com_googlesource_code_re2; fetching
    Fetching ...de_re2; Extracting C:/users/adam/_bazel_adam/4ijt6ef5/external\
/com_googlesource_code_re2/temp3848262190484820638/506cfa4bffd060c06ec338ce50e\
a3468daa6c814.tar.gz
b''
Traceback (most recent call last):
  File "C:\sdks\jax-jaxlib-v0.1.71\build\build.py", line 513, in <module>
    main()
  File "C:\sdks\jax-jaxlib-v0.1.71\build\build.py", line 508, in main
    shell(command)
  File "C:\sdks\jax-jaxlib-v0.1.71\build\build.py", line 53, in shell
    output = subprocess.check_output(cmd)
  File "C:\Users\Adam\anaconda3\envs\jax39\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\Adam\anaconda3\envs\jax39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\bazel\\bazel.EXE', 'run', '--verbose_failures=true', '--config=mkl_open_source_only', '--config=cuda', ':build_wheel', '--', '--output_path=C:\\sdks\\jax-jaxlib-v0.1.71\\dist', '--cpu=AMD64']' returned non-zero exit status 1.
```

**Comment by cloudhan** [comment]
It seems to be your OS configuration problem. Symlinks in windows requires admin privilege by default, to circumvent this problem, you can refer to [Symlinks in Windows 10!](https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/)
