### ISSUE TITLE
Jax PRNGKeyArray report `dtype` field on tab completion

### ISSUE THREAD

**Issue by PhilipVinc** [google/jax#7820]
A very minor issue: the new `PRNGKeyArray` report, when using tab completion, that they have a `dtype` field, but `hasattr(key, "dtype")` returns False, and trying to access it fails.

Maybe the `__dir__` entry must be updated?

```python
>>> import jax
>>> jax.config.update('jax_enable_custom_prng', True)
>>> k=jax.random.PRNGKey(0)
>>> k
PRNGKeyArray:
  shape = ()
  impl = PRNGImpl:
           key_shape = (2,)
           seed = <function threefry_seed at 0x136c700d0>
           split = <function threefry_split at 0x1151afaf0>
           random_bits = <CompiledFunction object at 0x136c48880>
           fold_in = <function threefry_fold_in at 0x1151af790>
>>> k. # [/tab /tab]
k.dtype           k.impl            k.keys            k.shape(          k.tree_flatten(   k.tree_unflatten(
>>> k.dtype
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.8/site-packages/jax/_src/prng.py", line 122, in dtype
    raise AttributeError("'PRNGKeyArray' has no attribute 'dtype'")
AttributeError: 'PRNGKeyArray' has no attribute 'dtype'
```

**Comment by froystig** [comment]
Good catch. At the latest, this will go away once we [pass the upgrade period](https://github.com/google/jax/blob/64884e613403a406242c46b6fcafb53bf0a81039/jax/_src/prng.py#L120-L122), which is hopefully soon enough.

**Comment by froystig** [comment]
Now generally tracking the upgrade in #9263

**Comment by froystig** [comment]
This works these days. [Key arrays](https://jax.readthedocs.io/en/latest/jep/9263-typed-keys.html) have a special element type and a `dtype` attribute that shows it.

```python
>>> import jax
>>> key = jax.random.key(17)
>>> hasattr(key, 'dtype')
True
>>> key.dtype
key<fry>
```
