### ISSUE TITLE
jax.numpy.histogram2d error when passing 'range' kwarg

### ISSUE THREAD

**Issue by mr128254** [google/jax#7853]
When using `jax.numpy.histogram2d` together with the `range` keyword argument, an error occurs.

```python
import jax
import jax.numpy as jnp
import numpy as np

samples = jax.random.uniform(jax.random.PRNGKey(123), shape=(2, 30))
lims = [[-.5, .5], [-.5, .5]]

# numpy version works fine
hist = np.histogram2d(samples[0, :], samples[1, :], range=lims)
# jnp version fail with error below
hist = jnp.histogram2d(samples[0, :], samples[1, :], range=lims)
```

Error:
```
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Traceback (most recent call last):
  File "/home/jnphist2d.py", line 11, in <module>
    hist = jnp.histogram2d(samples[0, :], samples[1, :], range=lims)
  File "/home/usr/anaconda3/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 1005, in histogram2d
    hist, edges = histogramdd(sample, bins, range, weights, density)
  File "/home/usr/anaconda3/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 1031, in histogramdd
    bin_idx = searchsorted(bin_edges, sample[:, i], side='right')
  File "/home/usr/anaconda3/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 5717, in searchsorted
    raise ValueError("a should be 1-dimensional")
ValueError: a should be 1-dimensional
```

**Comment by jakevdp** [comment]
I think this is similar to #7715

**Comment by jakevdp** [comment]
On closer look, I believe this was fixed by #7715. Running your snippet with the most recent JAX release (v0.2.20) does not result in an error.

Can you check whether your original issue is fixed if you update JAX? Thanks!

**Comment by jakevdp** [comment]
Marking as duplicate of #7714

**Comment by mr128254** [comment]
v0.2.20 does fix the issue. Thanks!
