### ISSUE TITLE
pip only installs jax from the repository source code

### ISSUE THREAD

**Issue by sergiuiacob1** [google/jax#7921]
I'm expecting that installing from github source code would install jax and jaxlib.

```
➜  python: pip3 install --no-index --no-cache-dir jax jaxlib -f https://github.com/google/jax/releases/tag/jax-v0.2.9
Looking in links: https://github.com/google/jax/releases/tag/jax-v0.2.9
Collecting jax
  Downloading https://github.com/google/jax/archive/refs/tags/jax-v0.2.9.tar.gz
     - 8.6 MB 846 kB/s
ERROR: Could not find a version that satisfies the requirement jaxlib (from versions: none)
ERROR: No matching distribution found for jaxlib
```

It doesn't find `jaxlib` because of how the package is nested inside `jax/jaxlib`.

Installing just jax works:
```
➜  python: pip3 install --no-index --no-cache-dir jax -f https://github.com/google/jax/releases/tag/jax-v0.2.9
Looking in links: https://github.com/google/jax/releases/tag/jax-v0.2.9
Collecting jax
  Downloading https://github.com/google/jax/archive/refs/tags/jax-v0.2.9.tar.gz
     - 8.6 MB 850 kB/s
Requirement already satisfied: numpy>=1.12 in /Users/sergiuiacob/.pyenv/versions/3.7.8/lib/python3.7/site-packages (from jax) (1.17.3)
Requirement already satisfied: absl-py in /Users/sergiuiacob/.pyenv/versions/3.7.8/lib/python3.7/site-packages (from jax) (0.13.0)
Requirement already satisfied: opt_einsum in /Users/sergiuiacob/.pyenv/versions/3.7.8/lib/python3.7/site-packages (from jax) (3.3.0)
Requirement already satisfied: six in /Users/sergiuiacob/.pyenv/versions/3.7.8/lib/python3.7/site-packages (from absl-py->jax) (1.16.0)
Building wheels for collected packages: jax
  Building wheel for jax (setup.py) ... done
  Created wheel for jax: filename=jax-0.2.9-py3-none-any.whl size=639712 sha256=69237573b0ba59ed388fa763f13069ac82d2e86adfa1cbc66c52ad4582717a0d
  Stored in directory: /private/var/folders/sr/1crf366j3r36q7k7166605c40000gn/T/pip-ephem-wheel-cache-0psno0k0/wheels/f9/7c/9d/55c2640b16734f25515197b2acf739ff1fc4e02afc15d9d001
Successfully built jax
Installing collected packages: jax
Successfully installed jax-0.2.9
```

I also tried installing jaxlib using pip3's VCS support, but I have an error:
```
➜  python git:(mets_412) pip3 install --no-index -e "git+https://github.com/google/jax.git#egg=jaxlib&subdirectory=jaxlib"
Obtaining jaxlib from git+https://github.com/google/jax.git#egg=jaxlib&subdirectory=jaxlib
  Cloning https://github.com/google/jax.git to ./src/jaxlib
  Running command git clone -q https://github.com/google/jax.git /Users/sergiuiacob/shoreline/python/src/jaxlib
    ERROR: Command errored out with exit status 1:
     command: /Users/sergiuiacob/.pyenv/versions/3.7.8/bin/python3.7 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/sergiuiacob/shoreline/python/src/jaxlib/jaxlib/setup.py'"'"'; __file__='"'"'/Users/sergiuiacob/shoreline/python/src/jaxlib/jaxlib/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/sr/1crf366j3r36q7k7166605c40000gn/T/pip-pip-egg-info-a3xms75n
         cwd: /Users/sergiuiacob/shoreline/python/src/jaxlib/jaxlib
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/sergiuiacob/shoreline/python/src/jaxlib/jaxlib/setup.py", line 20, in <module>
        with open('jaxlib/version.py') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'jaxlib/version.py'
    ----------------------------------------
WARNING: Discarding git+https://github.com/google/jax.git#egg=jaxlib&subdirectory=jaxlib. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement jaxlib (unavailable) (from versions: none)
ERROR: No matching distribution found for jaxlib (unavailable)
```

I think it happens because the file `jax/jaxlib/setup.py` is looking for `jaxlib/version.py`, however the working directory for the command above is already inside the `jaxlib` directory

How could I install only jaxlib?

**Comment by apaszke** [comment]
jaxlib is not a pure Python package and needs to be built separately, which is why we provide prebuilt wheels that are hosted in other locations. [Installation instructions](https://github.com/google/jax#installation) should have all the details. Please feel free to reopen this if this doesn't help.
