### ISSUE TITLE
Cuda Configuration Error: Invalid compute capability: compute_70build:rocm

### ISSUE THREAD

**Issue by brettkoonce** [google/jax#7955]
> python3 build/build.py --enable_cuda

```
Cuda Configuration Error: Invalid compute capability: compute_70build:rocm
INFO: Found applicable config definition build:cuda in file /home/skoonce/jax/jax/.bazelrc: --repo_env TF_NEED_CUDA=1 --action_env TF_CUDA_COMPUTE_CAPABILITIES=3.5,5.2,6.0,6.1,7.0 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda --define=xla_python_enable_gpu=true
ERROR: @local_config_cuda//:enable_cuda :: Error loading option @local_config_cuda//:enable_cuda: 
Cuda Configuration Error: Invalid compute capability: compute_70build:rocm

b''
Traceback (most recent call last):
  File "build/build.py", line 521, in <module>
    main()
  File "build/build.py", line 516, in main
    shell(command)
  File "build/build.py", line 53, in shell
    output = subprocess.check_output(cmd)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['./bazel-4.1.0-linux-x86_64', 'run', '--verbose_failures=true', '--config=avx_posix', '--config=mkl_open_source_only', '--config=cuda', ':build_wheel', '--', '--output_path=/home/skoonce/jax/jax/dist', '--cpu=x86_64']' returned non-zero exit status 2.
```

ping @yashk2810 eg d0acd9f3435a7eff924c9be937dc2abb1716e79a

**Comment by yashk2810** [comment]
Ahh, there's a `\n` missing. I'll fix it when I have access to my computer or you can send a PR too 😃

**Comment by brettkoonce** [comment]
@yashk2810 kk, give me a sec! 🤓

**Comment by yashk2810** [comment]
Can you test it too with the command you ran? 

Thank you!
