### ISSUE TITLE
bfloat16 pmap cuda11.1 results in error (v2)

### ISSUE THREAD

**Issue by brettkoonce** [google/jax#8044]
i have a second gpu and can now reproduce the behavior/error in #7567 locally (don't have permissions to reopen that):

```
Traceback (most recent call last):
  File "demo-v2-test.py", line 84, in <module>
    replicated_params, loss = update(replicated_params, x_split, y_split)
  File "/home/skoonce/.local/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/skoonce/.local/lib/python3.8/site-packages/jax/_src/api.py", line 1720, in f_pmapped
    out_tree, out_flat = f_pmapped_(*args, **kwargs)
  File "/home/skoonce/.local/lib/python3.8/site-packages/jax/_src/api.py", line 1653, in f_pmapped
    out = pxla.xla_pmap(
  File "/home/skoonce/.local/lib/python3.8/site-packages/jax/core.py", line 1674, in bind
    return call_bind(self, fun, *args, **params)
  File "/home/skoonce/.local/lib/python3.8/site-packages/jax/core.py", line 1605, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/home/skoonce/.local/lib/python3.8/site-packages/jax/core.py", line 1677, in process
    return trace.process_map(self, fun, tracers, params)
  File "/home/skoonce/.local/lib/python3.8/site-packages/jax/core.py", line 613, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/skoonce/.local/lib/python3.8/site-packages/jax/interpreters/pxla.py", line 723, in xla_pmap_impl
    compiled_fun, fingerprint = parallel_callable(fun, backend, axis_name, axis_size,
  File "/home/skoonce/.local/lib/python3.8/site-packages/jax/linear_util.py", line 262, in memoized_fun
    ans = call(fun, *args)
  File "/home/skoonce/.local/lib/python3.8/site-packages/jax/interpreters/pxla.py", line 1006, in parallel_callable
    compiled = xla.compile_or_get_cached(backend, built, compile_options)
  File "/home/skoonce/.local/lib/python3.8/site-packages/jax/interpreters/xla.py", line 81, in compile_or_get_cached
    return backend_compile(backend, computation, compile_options)
  File "/home/skoonce/.local/lib/python3.8/site-packages/jax/interpreters/xla.py", line 385, in backend_compile
    return backend.compile(built_c, compile_options=options)
jax._src.traceback_util.UnfilteredStackTrace: RuntimeError: UNIMPLEMENTED: Requested AllReduce not implemented on GPU; replica_count: 2; partition_count: 1, group_mode: kCrossReplica, operand_count: 2; NCCL support: 1; first operand array element-type: BF16

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "demo-v2-test.py", line 84, in <module>
    replicated_params, loss = update(replicated_params, x_split, y_split)
  File "/home/skoonce/.local/lib/python3.8/site-packages/jax/interpreters/xla.py", line 385, in backend_compile
    return backend.compile(built_c, compile_options=options)
RuntimeError: UNIMPLEMENTED: Requested AllReduce not implemented on GPU; replica_count: 2; partition_count: 1, group_mode: kCrossReplica, operand_count: 2; NCCL support: 1; first operand array element-type: BF16

```

this is with latest master + cuda11.1 + 2x 3060 gpu fwiw.

**Comment by brettkoonce** [comment]
code fwiw:

```
import jax
import numpy as np
import jax.numpy as jnp
jax.devices()

from typing import NamedTuple, Tuple
import functools

class Params(NamedTuple):
    weight: jnp.ndarray
    bias: jnp.ndarray


def init(rng) -> Params:
    """Returns the initial model params."""
    weights_key, bias_key = jax.random.split(rng)
    weight = jax.random.normal(weights_key, (), dtype=D_TYPE)
    bias = jax.random.normal(bias_key, (), dtype=D_TYPE)
    return Params(weight, bias)


def loss_fn(params: Params, xs: jnp.ndarray, ys: jnp.ndarray) -> jnp.ndarray:
    """Computes the least squares error of the model's predictions on x against y."""
    pred = params.weight * xs + params.bias
    return jnp.mean((pred - ys) ** 2)

LEARNING_RATE = 0.005

# So far, the code is identical to the single-device case. Here's what's new:


# Remember that the `axis_name` is just an arbitrary string label used
# to later tell `jax.lax.pmean` which axis to reduce over. Here, we call it
# 'num_devices', but could have used anything, so long as `pmean` used the same.
@functools.partial(jax.pmap, axis_name='num_devices')
def update(params: Params, xs: jnp.ndarray, ys: jnp.ndarray) -> Tuple[Params, jnp.ndarray]:
    """Performs one SGD update step on params using the given data."""

    # Compute the gradients on the given minibatch (individually on each device).
    loss, grads = jax.value_and_grad(loss_fn)(params, xs, ys)

    # Combine the gradient across all devices (by taking their mean).
    grads = jax.lax.pmean(grads, axis_name='num_devices')

    # Also combine the loss. Unnecessary for the update, but useful for logging.
    loss = jax.lax.pmean(loss, axis_name='num_devices')

    # Each device performs its own update, but since we start with the same params
    # and synchronise gradients, the params stay in sync.
    new_params = jax.tree_multimap(
        lambda param, g: param - g * LEARNING_RATE, params, grads)

    return new_params, loss

# Generate true data from y = w*x + b + noise
true_w, true_b = 2, -1
xs = np.random.normal(size=(128, 1))
noise = 0.5 * np.random.normal(size=(128, 1))
ys = xs * true_w + true_b + noise

# Initialise parameters and replicate across devices.
D_TYPE = jnp.bfloat16
params = init(jax.random.PRNGKey(123))
n_devices = jax.local_device_count()
replicated_params = jax.tree_map(lambda x: jnp.array([x] * n_devices), params)

def split(arr):
    """Splits the first axis of `arr` evenly across the number of devices."""
    return arr.reshape(n_devices, arr.shape[0] // n_devices, *arr.shape[1:])

# Reshape xs and ys for the pmapped `update()`.
x_split = split(xs)
y_split = split(ys)

type(x_split)

def type_after_update(name, obj):
    print(f"after first `update()`, `{name}` is a", type(obj))

# Actual training loop.
for i in range(1000):

    # This is where the params and data gets communicated to devices:
    replicated_params, loss = update(replicated_params, x_split, y_split)

    # The returned `replicated_params` and `loss` are now both ShardedDeviceArrays,
    # indicating that they're on the devices.
    # `x_split`, of course, remains a NumPy array on the host.
    if i == 0:
        type_after_update('replicated_params.weight', replicated_params.weight)
        type_after_update('loss', loss)
        type_after_update('x_split', x_split)

    if i % 100 == 0:
        # Note that loss is actually an array of shape [num_devices], with identical
        # entries, because each device returns its copy of the loss.
        # So, we take the first element to print it.
        print(f"Step {i:3d}, loss: {loss[0]:.3f}")


# Plot results.

# Like the loss, the leaves of params have an extra leading dimension,
# so we take the params from the first device.
params = jax.device_get(jax.tree_map(lambda x: x[0], replicated_params))

```

**Comment by jakevdp** [comment]
What version of jaxlib do you have installed?

**Comment by brettkoonce** [comment]
latest jaxlib/jax (eg git pull, python3 build/build.py --enable_cuda + install, pip install -e . for jax)

**Comment by mattiasmar** [comment]
@brettkoonce @yashk2810 Do you know now how to overcome this error? I see it with the latest jax-build and with [this NLP huggingface repo](https://huggingface.co/pere/norwegian-gptneo-red/blob/main/run_clm_mp.py) when running on a host with 8 Titan-X GPU's.

**Comment by brettkoonce** [comment]
@mattiasmar a titan-x doesn't support bf16, for what it's worth!

**Comment by mattiasmar** [comment]
Ouch! That doesn't leave me with any option to work with this pre-trained model, does it?

**Comment by brettkoonce** [comment]
@mattiasmar if you have 8 gpu's you should have enough ram to run things (slowly) in fp32 mode, afaik!  you might consider joining the gpt-neo discord server and asking for help there: https://www.eleuther.ai

**Comment by mattiasmar** [comment]
@brettkoonce Do you know how to convert the bf16 layers to fp32 in jax?

**Comment by brettkoonce** [comment]
@mattiasmar Loosely, you audit the logic and make sure the model is being upsampled correctly, then have Jax emit fp32 code.  There are Jax flags to emulate different levels of precision as well, you might look at the fp32 --> fp64 docs: https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html?highlight=precision#double-64bit-precision

**Comment by hawkinsp** [comment]
I'm pretty sure this is fixed if you use a current `jaxlib` and a sufficiently new CUDA. (It does not reproduce at head for me with the current `jaxlib` and CUDA 11.7, I suspect CUDA 11.4 or so is enough.)
