### ISSUE TITLE
Fail more gracefully if CUDA libraries are not found.

### ISSUE THREAD

**Issue by hawkinsp** [google/jax#8289]
A user reported the following problem:
```
>>> import jax.numpy as jnp
>>> A = jnp.array([[0, 1], [1, 1], [1, 1], [2, 1]])
>>> q, r = jnp.linalg.qr(A)
2021-10-19 12:49:58.203647: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /pkgs/cuda-11.0/lib64:/pkgs/cudnn-11.0-v8.0.5.39/lib64:/pkgs/TensorRT-6/lib:/pkgs/cuda-11.0/extras/CUPTI/lib64
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/h/winniexu/software/anaconda/lib/python3.7/site-packages/jax/_src/numpy/linalg.py", line 476, in qr
    q, r = lax_linalg.qr(a, full_matrices)
jax._src.source_info_util.JaxStackTraceBeforeTransformation: RuntimeError: jaxlib/cusolver.cc:51: operation cusolverDnCreate(&handle) failed: cuSolver internal error
```

It turned out they had `libcusolver.so.10` installed.

JAX should fail with a more graceful and informative error if CUDA libraries cannot be found.

**Comment by xwinxu** [comment]
Note: JAX and Jaxlib installed via `pip install --upgrade jax jaxlib==0.1.70+cuda110 -f https://storage.googleapis.com/jax-releases/jax_releases.html`

**Comment by carlosgmartin** [comment]
@hawkinsp Can GPU-JAX fall back to CPU functionality if CUDA is unavailable? See https://github.com/google/jax/discussions/14208.
