### ISSUE TITLE
Building from source fails on linux machine

### ISSUE THREAD

**Issue by mberaha** [google/jax#8482]
I am running into troubles when installing JAX on a remote virtual machine (I don't know the hardware specs, I am just given an ssh access to a dedicated VM)
`pip3 install jaxlib jax` works just fine, but when I try to import jax I get the error
```
>>> import jax
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/beraha/usr/jax/jax/__init__.py", line 37, in <module>
    from . import config as _config_module
  File "/home/beraha/usr/jax/jax/config.py", line 18, in <module>
    from jax._src.config import config
  File "/home/beraha/usr/jax/jax/_src/config.py", line 27, in <module>
    from jax._src import lib
  File "/home/beraha/usr/jax/jax/_src/lib/__init__.py", line 72, in <module>
    cpu_feature_guard.check_cpu_features()
RuntimeError: This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support. You may be able work around this issue by building jaxlib from source.
```

When building from source, the build fails:
```
python3 build/build.py 

     _   _  __  __
    | | / \ \ \/ /
 _  | |/ _ \ \  /
| |_| / ___ \/  \
 \___/_/   \/_/\_\


Bazel binary path: ./bazel-4.1.0-linux-x86_64
Bazel version: 4.1.0
Python binary path: /usr/bin/python3
Python version: 3.8
NumPy version: 1.21.2
MKL-DNN enabled: yes
Target CPU: x86_64
Target CPU features: release
CUDA enabled: no
TPU enabled: no
ROCm enabled: no

Building XLA and installing it in the jaxlib source tree...
./bazel-4.1.0-linux-x86_64 run --verbose_failures=true --config=avx_posix --config=mkl_open_source_only :build_wheel -- --output_path=/home/beraha/usr/jax/dist --cpu=x86_64
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'run' from /home/beraha/usr/jax/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'run' from /home/beraha/usr/jax/.bazelrc:
  Inherited 'build' options: --apple_platform_type=macos --macos_minimum_os=10.9 --announce_rc --define open_source_build=true --spawn_strategy=standalone --enable_platform_specific_config --define=no_aws_support=true --define=no_gcp_support=true --define=no_hdfs_support=true --define=no_kafka_support=true --define=no_ignite_support=true --define=grpc_no_ares=true -c opt --config=short_logs
INFO: Reading rc options for 'run' from /home/beraha/usr/jax/.jax_configure.bazelrc:
  Inherited 'build' options: --strategy=Genrule=standalone --repo_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env=PYENV_ROOT --python_path=/usr/bin/python3 --distinct_host_configuration=false
INFO: Found applicable config definition build:short_logs in file /home/beraha/usr/jax/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:avx_posix in file /home/beraha/usr/jax/.bazelrc: --copt=-mavx --host_copt=-mavx
INFO: Found applicable config definition build:mkl_open_source_only in file /home/beraha/usr/jax/.bazelrc: --define=tensorflow_mkldnn_contraction_kernel=1
INFO: Found applicable config definition build:linux in file /home/beraha/usr/jax/.bazelrc: --config=posix --copt=-Wno-stringop-truncation
INFO: Found applicable config definition build:posix in file /home/beraha/usr/jax/.bazelrc: --copt=-Wno-sign-compare --cxxopt=-std=c++14 --host_cxxopt=-std=c++14
Loading: 
Loading: 0 packages loaded
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/6da63573e48397decfb772884a36f176d6c81209.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from http://mirror.tensorflow.org/github.com/tensorflow/runtime/archive/ad09d3736c5120de1e7dba6edd0ff5eeae6b8102.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
Analyzing: target //build:build_wheel (1 packages loaded, 0 targets configured)
Analyzing: target //build:build_wheel (15 packages loaded, 12 targets configured)
Analyzing: target //build:build_wheel (148 packages loaded, 4460 targets configured)
Analyzing: target //build:build_wheel (179 packages loaded, 13175 targets configured)
INFO: Analyzed target //build:build_wheel (180 packages loaded, 13471 targets configured).

INFO: Found 1 target...
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
[87 / 175] Executing genrule @local_config_python//:python_include; 1s local ... (20 actions running)
[90 / 175] Compiling grpc/src/compiler/cpp_generator.cc; 2s local ... (20 actions running)
[93 / 175] Compiling grpc/src/compiler/cpp_generator.cc; 4s local ... (20 actions running)
[99 / 175] Compiling grpc/src/compiler/cpp_generator.cc; 5s local ... (20 actions running)
[104 / 175] Compiling src/flatc.cpp; 7s local ... (20 actions running)
[112 / 175] Compiling src/idl_parser.cpp; 10s local ... (20 actions running)
[129 / 175] Compiling src/idl_parser.cpp; 12s local ... (20 actions running)
[165 / 1,499] Compiling src/idl_parser.cpp; 15s local ... (20 actions running)
[188 / 1,499] Compiling src/idl_parser.cpp; 19s local ... (20 actions running)
[210 / 1,499] Compiling src/idl_parser.cpp; 23s local ... (20 actions, 19 running)
ERROR: /home/beraha/usr/jax/jaxlib/BUILD:177:22: Generating flatbuffer files for pocketfft_flatbuffers_cc_srcs: //jaxlib:pocketfft_flatbuffers_cc_srcs failed: (Illegal instruction): bash failed: error executing command 
  (cd /home/beraha/.cache/bazel/_bazel_beraha/24259ef897c8798bfdef130aeefe1099/execroot/__main__ && \
  exec env - \
    PATH=/home/beraha/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; for f in jaxlib/pocketfft.fbs; do bazel-out/k8-opt/bin/external/flatbuffers/flatc --no-union-value-namespacing --gen-object-api  -c -o bazel-out/k8-opt/bin/jaxlib $f; done')
Execution platform: @local_execution_config_platform//:platform
/bin/bash: line 1: 898809 Illegal instruction     (core dumped) bazel-out/k8-opt/bin/external/flatbuffers/flatc --no-union-value-namespacing --gen-object-api -c -o bazel-out/k8-opt/bin/jaxlib $f
Target //build:build_wheel failed to build
INFO: Elapsed time: 35.793s, Critical Path: 28.24s
INFO: 177 processes: 31 internal, 146 local.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully
b''
Traceback (most recent call last):
  File "build/build.py", line 524, in <module>
    main()
  File "build/build.py", line 519, in main
    shell(command)
  File "build/build.py", line 53, in shell
    output = subprocess.check_output(cmd)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['./bazel-4.1.0-linux-x86_64', 'run', '--verbose_failures=true', '--config=avx_posix', '--config=mkl_open_source_only', ':build_wheel', '--', '--output_path=/home/beraha/usr/jax/dist', '--cpu=x86_64']' returned non-zero exit status 1.
```

Here are some basic infos on the machine I'm getting out from the terminal
```
> lscpu

Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   40 bits physical, 48 bits virtual
CPU(s):                          20
On-line CPU(s) list:             0-19
Thread(s) per core:              1
Core(s) per socket:              10
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      15
Model:                           6
Model name:                      Common KVM processor
Stepping:                        1
CPU MHz:                         2194.848
BogoMIPS:                        4389.69
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       640 KiB
L1i cache:                       640 KiB
L2 cache:                        80 MiB
L3 cache:                        32 MiB
NUMA node0 CPU(s):               0-9
NUMA node1 CPU(s):               10-19
Vulnerability Itlb multihit:     KVM: Vulnerable
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc no
                                 pl xtopology cpuid tsc_known_freq pni cx16 x2apic hypervisor lahf_lm cpuid_fault pti

```

```
> cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

```
> uname -r
5.4.0-89-generic
```

**Comment by nicholasjng** [comment]
Not a maintainer, but it seems that your build fails because building `jaxlib` requires AVX these days. Googling some of the processor info you posted puts the processor's model at Pentium 4 "Cedar Mill", which supports SSE3 at maximum, so that would be in line with the error message you got.

There is some info about `jaxlib`'s AVX requirement in this issue here: https://github.com/google/jax/issues/6671 

Judging from the comments there, it seems there is a way to build `jaxlib` without AVX, but without any further information on how to do it.

**Comment by yashk2810** [comment]
You can comment on these lines and try to build without AVX: https://source.corp.google.com/piper///depot/google3/third_party/py/jax/oss/build/build.py;l=492-494

**Comment by mberaha** [comment]
> You can comment on these lines and try to build without AVX: https://source.corp.google.com/piper///depot/google3/third_party/py/jax/oss/build/build.py;l=492-494

I cannot access this link (an SSO username ending in @google.com is required)

**Comment by nicholasjng** [comment]
Judging by the ending of that link, it's these lines he means, which add an AVX flag to the bazel build command:

https://github.com/google/jax/blob/e5e5bb3ac1019f0b57097ec9aa77f60ba826844f/build/build.py#L492-L494

So commenting them out should skip AVX use.

**Comment by mberaha** [comment]
I commented out those lines and it worked! Thanks so much :)

**Comment by yashk2810** [comment]
Sorry, I meant this: https://github.com/google/jax/blob/main/build/build.py#L494

**Comment by xloem** [comment]
It looks like automating this "properly" might mean adding a dependency of https://github.com/robbmcleod/cpufeature or https://github.com/flababah/cpuid.py
