### ISSUE TITLE
jax.numpy.meshgrid arg check for "indexing" fails

### ISSUE THREAD

**Issue by wztdream** [google/jax#8495]
Hi,
I just noticed `meshgrid` function failed to throw error if  there is typo for arg `indexing`, this cause me a lot time for debugging.

```python
import jax.numpy as jnp
import numpy as np

if __name__ == "__main__":
    jm = jnp.arange(2)
    jn = jnp.arange(2)
    # here is a typo "index" which should be "indexing"
    # but there is no error, and the output is just as if
    # it was indexing="xy"
    jmm, jnn = jnp.meshgrid(jm, jn, index="ij")
    print("jax: typo index, but no error,xy ordered output")
    print(jmm)
    print(jnn)
    print("jax: no typo, correct ij ordered output")
    # here is the right args
    jmm, jnn = jnp.meshgrid(jm, jn, indexing="ij")
    print(jmm)
    print(jnn)

    m = np.arange(2)
    n = np.arange(2)
    mm, nn = np.meshgrid(m, n, indexing="ij")
    print("numpy correct ij ordered output")
    print(mm)
    print(nn)

    # below typo of index for numpy code will error
    mm, nn = np.meshgrid(m, n, index="ij")

```
output:
```python
jax: typo index, but no error,xy ordered output
[[0 1]
 [0 1]]
[[0 0]
 [1 1]]
jax: no typo, correct ij ordered output
[[0 0]
 [1 1]]
[[0 1]
 [0 1]]
numpy correct ij ordered output
[[0 0]
 [1 1]]
[[0 1]
 [0 1]]
Traceback (most recent call last):
  File "6.py", line 28, in <module>
    mm, nn = np.meshgrid(m, n, index="ij")
  File "<__array_function__ internals>", line 4, in meshgrid
TypeError: _meshgrid_dispatcher() got an unexpected keyword argument 'index'
```

**Comment by jakevdp** [comment]
Thanks for the report - we should add better argument validation there.
