### ISSUE TITLE
error when importing jax 

### ISSUE THREAD

**Issue by VanWieren** [google/jax#8500]
I have jax and jaxlib with cuda installed on my computer running zorin os (Ubuntu 18), and I have had jax working for over a year and all of a sudden after doing some sudo updates, it no longer will work. I have cuda 11.5 installed, and have installed the GPU version according to the jax github instructions.

install method
```
(base) cvanwieren@ConnorPC:~$ pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_releases.html
Looking in links: https://storage.googleapis.com/jax-releases/jax_releases.html
Collecting jax[cuda]
  Using cached jax-0.2.24-py3-none-any.whl
Requirement already satisfied: opt-einsum in ./anaconda3/lib/python3.8/site-packages (from jax[cuda]) (3.3.0)
Requirement already satisfied: typing-extensions in ./anaconda3/lib/python3.8/site-packages (from jax[cuda]) (3.10.0.2)
Requirement already satisfied: numpy>=1.18 in ./anaconda3/lib/python3.8/site-packages (from jax[cuda]) (1.20.3)
Requirement already satisfied: scipy>=1.2.1 in ./anaconda3/lib/python3.8/site-packages (from jax[cuda]) (1.7.1)
Requirement already satisfied: absl-py in ./anaconda3/lib/python3.8/site-packages (from jax[cuda]) (0.12.0)
Collecting jaxlib==0.1.73+cuda11.cudnn82
  Using cached https://storage.googleapis.com/jax-releases/cuda11/jaxlib-0.1.73%2Bcuda11.cudnn82-cp38-none-manylinux2010_x86_64.whl (138.6 MB)
Requirement already satisfied: flatbuffers<3.0,>=1.12 in ./anaconda3/lib/python3.8/site-packages (from jaxlib==0.1.73+cuda11.cudnn82->jax[cuda]) (1.12)
Requirement already satisfied: six in ./anaconda3/lib/python3.8/site-packages (from absl-py->jax[cuda]) (1.16.0)
Installing collected packages: jaxlib, jax
Successfully installed jax-0.2.24 jaxlib-0.1.73+cuda11.cudnn82

```

results of nvcc -V
```
(base) cvanwieren@ConnorPC:~$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_Sep_13_19:13:29_PDT_2021
Cuda compilation tools, release 11.5, V11.5.50
Build cuda_11.5.r11.5/compiler.30411180_0

```
results of nvidia-smi
```
(base) cvanwieren@ConnorPC:~$ nvidia-smi
Tue Nov  9 13:43:39 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.29.05    Driver Version: 495.29.05    CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0  On |                  N/A |
|  0%   39C    P8    19W / 270W |    482MiB /  7979MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1284      G   /usr/lib/xorg/Xorg                 26MiB |
|    0   N/A  N/A      1402      G   /usr/bin/gnome-shell               95MiB |
|    0   N/A  N/A      1827      G   /usr/lib/xorg/Xorg                210MiB |
|    0   N/A  N/A      1985      G   /usr/bin/gnome-shell               28MiB |
|    0   N/A  N/A      2634      G   ...AAAAAAAAA= --shared-files       38MiB |
|    0   N/A  N/A      3412      G   ...AAAAAAAAA= --shared-files       78MiB |
+-----------------------------------------------------------------------------+

```

**error**
```python
(base) cvanwieren@ConnorPC:~$ python
Python 3.8.12 | packaged by conda-forge | (default, Sep 29 2021, 19:52:28) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jax
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cvanwieren/anaconda3/lib/python3.8/site-packages/jax/__init__.py", line 37, in <module>
    from . import config as _config_module
  File "/home/cvanwieren/anaconda3/lib/python3.8/site-packages/jax/config.py", line 18, in <module>
    from jax._src.config import config
  File "/home/cvanwieren/anaconda3/lib/python3.8/site-packages/jax/_src/config.py", line 27, in <module>
    from jax._src import lib
  File "/home/cvanwieren/anaconda3/lib/python3.8/site-packages/jax/_src/lib/__init__.py", line 74, in <module>
    from jaxlib import xla_client
  File "/home/cvanwieren/anaconda3/lib/python3.8/site-packages/jaxlib/xla_client.py", line 29, in <module>
    from absl import logging
ImportError: cannot import name 'logging' from 'absl' (unknown location)
```
not sure how to procede.

**Comment by jakevdp** [comment]
It looks like your `absl` installation is somehow corrupted. Try running:
```
$ pip uninstall absl-py
$ pip install -U absl-py
```
and then try again.

**Comment by VanWieren** [comment]
@jakevdp after those changes, this is the error:

```python
(base) cvanwieren@ConnorPC:~$ python
Python 3.8.12 | packaged by conda-forge | (default, Sep 29 2021, 19:52:28) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jaxd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'jaxd'
>>> import jax
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cvanwieren/anaconda3/lib/python3.8/site-packages/jax/__init__.py", line 37, in <module>
    from . import config as _config_module
  File "/home/cvanwieren/anaconda3/lib/python3.8/site-packages/jax/config.py", line 18, in <module>
    from jax._src.config import config
  File "/home/cvanwieren/anaconda3/lib/python3.8/site-packages/jax/_src/config.py", line 27, in <module>
    from jax._src import lib
  File "/home/cvanwieren/anaconda3/lib/python3.8/site-packages/jax/_src/lib/__init__.py", line 76, in <module>
    from jaxlib import pocketfft
  File "/home/cvanwieren/anaconda3/lib/python3.8/site-packages/jaxlib/pocketfft.py", line 18, in <module>
    from . import pocketfft_flatbuffers_py_generated as pd
  File "/home/cvanwieren/anaconda3/lib/python3.8/site-packages/jaxlib/pocketfft_flatbuffers_py_generated.py", line 1, in <module>
    import flatbuffers
ModuleNotFoundError: No module named 'flatbuffers'

```

**Comment by VanWieren** [comment]
and after trying to install flatbuffers this error comes up

```python
(base) cvanwieren@ConnorPC:~$ python
Python 3.8.12 | packaged by conda-forge | (default, Sep 29 2021, 19:52:28) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jax
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cvanwieren/anaconda3/lib/python3.8/site-packages/jax/__init__.py", line 127, in <module>
    from . import nn as nn
  File "/home/cvanwieren/anaconda3/lib/python3.8/site-packages/jax/nn/__init__.py", line 21, in <module>
    from jax._src.nn.functions import (
  File "/home/cvanwieren/anaconda3/lib/python3.8/site-packages/jax/_src/nn/functions.py", line 28, in <module>
    from jax.scipy.special import expit
  File "/home/cvanwieren/anaconda3/lib/python3.8/site-packages/jax/scipy/__init__.py", line 18, in <module>
    from . import signal as signal
  File "/home/cvanwieren/anaconda3/lib/python3.8/site-packages/jax/scipy/signal.py", line 17, in <module>
    from jax._src.scipy.signal import (
  File "/home/cvanwieren/anaconda3/lib/python3.8/site-packages/jax/_src/scipy/signal.py", line 15, in <module>
    import scipy.signal as osp_signal
  File "/home/cvanwieren/anaconda3/lib/python3.8/site-packages/scipy/signal/__init__.py", line 294, in <module>
    from ._max_len_seq import max_len_seq
  File "/home/cvanwieren/anaconda3/lib/python3.8/site-packages/scipy/signal/_max_len_seq.py", line 8, in <module>
    from ._max_len_seq_inner import _max_len_seq_inner
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/cvanwieren/anaconda3/lib/python3.8/site-packages/scipy/signal/_max_len_seq_inner.cpython-38-x86_64-linux-gnu.so)
```

**Comment by jakevdp** [comment]
It seems like your conda environment is hopelessly corrupted – this is unrelated to JAX (I suspect `import scipy` would give you the same error). You could ask for help in conda support channels, but my suggestion would be to start over in a clean environment:
```
$ conda create -n jax-env python=3.9
$ conda activate jax-env
$ pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_releases.html
```
