### ISSUE TITLE
"cuSolver internal error" when using jax.numpy.linalg.det

### ISSUE THREAD

**Issue by Zejun-Liu** [google/jax#8607]
I was trying to run a program with jax.numpy.linalg.det in my spyder IDE, but it failed with "cuSolver internal error", while this issue didn't occur when the program was run on Colab. Is it possible to solve this issue?
The code for this program is 

```python
import jax.numpy as jnp
import jax.random as jrd
L = 16; N1 = 8; N2 = 8; 
key = jrd.PRNGKey(1)
keys = jrd.split(key,2)
def init_c(key, n): 
  Q = jrd.choice(key, L, (n,), replace=0)  
  Q = jnp.sort(Q)
  B = jnp.zeros((n,L))+0j
  B = B.at[:,Q].set(jnp.identity(n)+0j) 
  return B, Q 
B1, Q1 = init_c(keys[0], N1)
B2, Q2 = init_c(keys[1], N2)
print(jnp.linalg.det(B2[:,Q2]))
# expected result : 1.
```

And it gives the following error report when running on spyder:
```
Traceback (most recent call last):

  File "/home/zejun/zejun/slater/code/slateriT.py", line 25, in <module>
    print(jnp.linalg.det(B2[:,Q2]))

  File "/home/zejun/anaconda3/envs/spyder-env/lib/python3.9/site-packages/jax/_src/custom_derivatives.py", line 215, in __call__
    out_flat = custom_jvp_call_p.bind(flat_fun, flat_jvp, *args_flat)

  File "/home/zejun/anaconda3/envs/spyder-env/lib/python3.9/site-packages/jax/_src/custom_derivatives.py", line 277, in bind
    outs = top_trace.process_custom_jvp_call(self, fun, jvp, tracers)  # type: ignore

  File "/home/zejun/anaconda3/envs/spyder-env/lib/python3.9/site-packages/jax/core.py", line 612, in process_custom_jvp_call
    return fun.call_wrapped(*tracers)

  File "/home/zejun/anaconda3/envs/spyder-env/lib/python3.9/site-packages/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))

  File "/home/zejun/anaconda3/envs/spyder-env/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 183, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)

  File "/home/zejun/anaconda3/envs/spyder-env/lib/python3.9/site-packages/jax/_src/api.py", line 424, in cache_miss
    out_flat = xla.xla_call(

  File "/home/zejun/anaconda3/envs/spyder-env/lib/python3.9/site-packages/jax/core.py", line 1560, in bind
    return call_bind(self, fun, *args, **params)

  File "/home/zejun/anaconda3/envs/spyder-env/lib/python3.9/site-packages/jax/core.py", line 1551, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)

  File "/home/zejun/anaconda3/envs/spyder-env/lib/python3.9/site-packages/jax/core.py", line 1563, in process
    return trace.process_call(self, fun, tracers, params)

  File "/home/zejun/anaconda3/envs/spyder-env/lib/python3.9/site-packages/jax/core.py", line 606, in process_call
    return primitive.impl(f, *tracers, **params)

  File "/home/zejun/anaconda3/envs/spyder-env/lib/python3.9/site-packages/jax/interpreters/xla.py", line 592, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, name, donated_invars,

  File "/home/zejun/anaconda3/envs/spyder-env/lib/python3.9/site-packages/jax/linear_util.py", line 262, in memoized_fun
    ans = call(fun, *args)

  File "/home/zejun/anaconda3/envs/spyder-env/lib/python3.9/site-packages/jax/interpreters/xla.py", line 723, in _xla_callable
    out_nodes = jaxpr_subcomp(

  File "/home/zejun/anaconda3/envs/spyder-env/lib/python3.9/site-packages/jax/interpreters/xla.py", line 462, in jaxpr_subcomp
    ans = rule(c, axis_env, extend_name_stack(name_stack, eqn.primitive.name),

  File "/home/zejun/anaconda3/envs/spyder-env/lib/python3.9/site-packages/jax/interpreters/xla.py", line 1040, in f
    outs = jaxpr_subcomp(c, jaxpr, backend, axis_env, _xla_consts(c, consts),

  File "/home/zejun/anaconda3/envs/spyder-env/lib/python3.9/site-packages/jax/interpreters/xla.py", line 470, in jaxpr_subcomp
    ans = rule(c, axis_env, in_nodes,

  File "/home/zejun/anaconda3/envs/spyder-env/lib/python3.9/site-packages/jax/interpreters/xla.py", line 965, in _xla_call_translation_rule
    out_nodes = jaxpr_subcomp(subc, call_jaxpr, backend, axis_env, (),

  File "/home/zejun/anaconda3/envs/spyder-env/lib/python3.9/site-packages/jax/interpreters/xla.py", line 453, in jaxpr_subcomp
    ans = rule(c, *in_nodes, **eqn.params)

  File "/home/zejun/anaconda3/envs/spyder-env/lib/python3.9/site-packages/jax/_src/lax/linalg.py", line 999, in _lu_cpu_gpu_translation_rule
    lu, pivot, info = getrf_impl(c, operand)

  File "/home/zejun/anaconda3/envs/spyder-env/lib/python3.9/site-packages/jaxlib/cusolver.py", line 156, in getrf
    lwork, opaque = cusolver_kernels.build_getrf_descriptor(

RuntimeError: cuSolver internal error
```

**Comment by hawkinsp** [comment]
What versions of `jax`, `jaxlib`, CUDA and CuDNN do you have?

**Comment by Zejun-Liu** [comment]
@hawkinsp 
jax: 0.2.17
jaxlib: 0.1.68+cuda111
CUDA: release 10.1, V10.1.243
CuDNN:  (not sure if it is the version information)
#define CUDNN_MAJOR 8
#define CUDNN_MINOR 2
#define CUDNN_PATCHLEVEL 2

#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

**Comment by hawkinsp** [comment]
If nothing else, you have a version mismatch. You've installed a CUDA 11.1+ wheel, but you have CUDA 10.1. I suspect that's related to your problem.

I should note that we have dropped support for CUDA 10.1. There are known bugs (on NVIDIA's side) in CUDA 10.1 that we cannot work around, so we decided to drop support. Please update to a supported version of CUDA (11.1 or greater), install the most current `jax` and `jaxlib` wheels, and try again.

Please let me know if that works!

If that doesn't work, I'd also want to know the output of `nvidia-smi`.
