### ISSUE TITLE
Installation Problem - PTX was compiled with an unsupported toolchain

### ISSUE THREAD

**Issue by AlexanderKoch-Koch** [google/jax#8731]
I am unable to install a working version of jax with gpu support.
Here is some info about my machine:
Ubuntu 20.04
Nvidia driver 465.19.01
CUDA 11.3
cuDNN 8.2.1.32
Two GPUs: RTX 3080 and GTX 1080 Ti

I have installed jax and jaxlib with this command:
```
pip install https://storage.googleapis.com/jax-releases/cuda11/jaxlib-0.1.74+cuda11.cudnn82-cp38-none-manylinux2010_x86_64.whl
```

```python
from jax import random
key = random.PRNGKey(0)
x = random.normal(key, (10,))
```
This is the error message I receive:
```
2021-11-30 16:30:21.162015: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2086] Execution of replica 0 failed: INTERNAL: CustomCall failed: jaxlib/cuda_prng_kernels.cc:30: operation cudaGetLastError() failed: the provided PTX was compiled with an unsupported toolchain.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alex/.local/lib/python3.8/site-packages/jax/_src/random.py", line 521, in normal
    return _normal(key, shape, dtype)  # type: ignore
  File "/home/alex/.local/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/alex/.local/lib/python3.8/site-packages/jax/_src/api.py", line 416, in cache_miss
    out_flat = xla.xla_call(
  File "/home/alex/.local/lib/python3.8/site-packages/jax/core.py", line 1632, in bind
    return call_bind(self, fun, *args, **params)
  File "/home/alex/.local/lib/python3.8/site-packages/jax/core.py", line 1623, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/home/alex/.local/lib/python3.8/site-packages/jax/core.py", line 1635, in process
    return trace.process_call(self, fun, tracers, params)
  File "/home/alex/.local/lib/python3.8/site-packages/jax/core.py", line 627, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/alex/.local/lib/python3.8/site-packages/jax/interpreters/xla.py", line 690, in _xla_call_impl
    out = compiled_fun(*args)
  File "/home/alex/.local/lib/python3.8/site-packages/jax/interpreters/xla.py", line 1100, in _execute_compiled
    out_bufs = compiled.execute(input_bufs)
jax._src.traceback_util.UnfilteredStackTrace: RuntimeError: INTERNAL: CustomCall failed: jaxlib/cuda_prng_kernels.cc:30: operation cudaGetLastError() failed: the provided PTX was compiled with an unsupported toolchain.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alex/.local/lib/python3.8/site-packages/jax/_src/random.py", line 521, in normal
    return _normal(key, shape, dtype)  # type: ignore
  File "/home/alex/.local/lib/python3.8/site-packages/jax/interpreters/xla.py", line 1100, in _execute_compiled
    out_bufs = compiled.execute(input_bufs)
RuntimeError: INTERNAL: CustomCall failed: jaxlib/cuda_prng_kernels.cc:30: operation cudaGetLastError() failed: the provided PTX was compiled with an unsupported toolchain.
```

**Comment by hawkinsp** [comment]
This isn't so much a bug as "you need a newer NVidia driver". We have recently realized that since our jaxlib builds are made with CUDA 11.4, users need to either install driver 470 or to use the CUDA compat packages that Nvidia provides.

Is upgrading the driver possible?

**Comment by AlexanderKoch-Koch** [comment]
Thanks for the fast response. I have updated the driver and now it works. But I think it would be good to add this requirement to the installation instructions.

**Comment by milutter** [comment]
@hawkinsp It would be great if this would be reflected in the README installation guide, that sometimes CUDA 11.4 runtime is required. Especially as the statement 
> # Installs the wheel compatible with CUDA 11 and cuDNN 8.2 or newer.
> pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_releases.html 
seems to be wrong for some combinations of GPU / CUDA as CUDA 11 is not sufficient. Furthermore, it would be great to maintain Cuda 11.2 version as upgrading NVIDIA drivers is not really possible for compute clusters. 

An interesting side-remark, we only observed this error on a 3080TI and A100, while the same CUDA version runs fine with an 2080TI.
