### ISSUE TITLE
Bug in odeint for complex-valued functions

### ISSUE THREAD

**Issue by FlorianH-1QBit** [google/jax#8757]
This is happening on the `main` branch and in 0.2.25, not in some older versions. 
I think it was introduced in https://github.com/google/jax/commit/de777c8d37fed5504e5b161a40f4fbdc3bb31026

Code to reproduce the issue: Modified from `tests/ode_test.py` by adding ` * jnp.exp(-t)` in line 11.
```python
import jax
import jax.numpy as jnp
import jax.test_util as jtu
from jax.experimental.ode import odeint


def test_complex_odeint():
    print(jax.__version__)

    def dy_dt(y, t, alpha):
        return alpha * y * jnp.exp(-t)

    def f(y0, ts, alpha):
        return odeint(dy_dt, y0, ts, alpha).real

    alpha = 3 + 4j
    y0 = 1 + 2j
    ts = jnp.linspace(0., 1., 11)
    tol = 1e-1

    jtu.check_grads(f, (y0, ts, alpha), modes=["rev"], order=2, atol=tol, rtol=tol)


test_complex_odeint()
```
The error that's thrown is `TypeError: mul requires arguments to have the same dtypes, got float32, complex64.`, full trace below.

It looks like in https://github.com/google/jax/blob/main/jax/experimental/ode.py#L95, the dtype of `alpha` is `complex64`, which leads to a complex time `ti` in `https://github.com/google/jax/blob/main/jax/experimental/ode.py#L112`.
So `func_` in https://github.com/google/jax/blob/main/jax/experimental/ode.py#L184 gets called sometimes with a time of dtype `float32`, and sometime `complex64`, which seems to cause this problem.

The fix should be to change the dtype of `alpha` in https://github.com/google/jax/blob/main/jax/experimental/ode.py#L95 from `f0.dtype` to `t0.dtype`.

I'm happy to put together a PR!

Here is the stack trace:
```
0.2.26
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Traceback (most recent call last):
  File "/Users/florianhopfmueller/Library/Application Support/JetBrains/PyCharmCE2021.2/scratches/debug_complex_odeint.py", line 24, in <module>
    test_complex_odeint()
  File "/Users/florianhopfmueller/Library/Application Support/JetBrains/PyCharmCE2021.2/scratches/debug_complex_odeint.py", line 21, in test_complex_odeint
    jtu.check_grads(f, (y0, ts, alpha), modes=["rev"], order=2, atol=tol, rtol=tol)
  File "/Users/florianhopfmueller/code/jax/jax/_src/test_util.py", line 337, in check_grads
    _check_grads(f, args, order)
  File "/Users/florianhopfmueller/code/jax/jax/_src/test_util.py", line 330, in _check_grads
    _check_vjp(f, partial(api.vjp, f), args, err_msg=rev_msg)
  File "/Users/florianhopfmueller/code/jax/jax/_src/test_util.py", line 280, in check_vjp
    v_out, vjpfun = f_vjp(*args)
  File "/Users/florianhopfmueller/Library/Application Support/JetBrains/PyCharmCE2021.2/scratches/debug_complex_odeint.py", line 14, in f
    return odeint(dy_dt, y0, ts, alpha).real
  File "/Users/florianhopfmueller/code/jax/jax/experimental/ode.py", line 172, in odeint
    converted, consts = custom_derivatives.closure_convert(func, y0, t[0], *args)
  File "/Users/florianhopfmueller/Library/Application Support/JetBrains/PyCharmCE2021.2/scratches/debug_complex_odeint.py", line 11, in dy_dt
    return alpha * y * jnp.exp(-t)
  File "/Users/florianhopfmueller/code/jax/jax/_src/numpy/lax_numpy.py", line 684, in <lambda>
    fn = lambda x: lax_fn(*_promote_args_inexact(numpy_fn.__name__, x))
jax._src.source_info_util.JaxStackTraceBeforeTransformation: TypeError: mul requires arguments to have the same dtypes, got float32, complex64.

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/florianhopfmueller/Library/Application Support/JetBrains/PyCharmCE2021.2/scratches/debug_complex_odeint.py", line 24, in <module>
    test_complex_odeint()
  File "/Users/florianhopfmueller/Library/Application Support/JetBrains/PyCharmCE2021.2/scratches/debug_complex_odeint.py", line 21, in test_complex_odeint
    jtu.check_grads(f, (y0, ts, alpha), modes=["rev"], order=2, atol=tol, rtol=tol)
  File "/Users/florianhopfmueller/code/jax/jax/_src/test_util.py", line 337, in check_grads
    _check_grads(f, args, order)
  File "/Users/florianhopfmueller/code/jax/jax/_src/test_util.py", line 330, in _check_grads
    _check_vjp(f, partial(api.vjp, f), args, err_msg=rev_msg)
  File "/Users/florianhopfmueller/code/jax/jax/_src/test_util.py", line 287, in check_vjp
    cotangent_out = conj(vjpfun(conj(cotangent)))
  File "/Users/florianhopfmueller/code/jax/jax/experimental/ode.py", line 255, in _odeint_rev
    (y_bar, t0_bar, args_bar), rev_ts_bar = lax.scan(
  File "/Users/florianhopfmueller/code/jax/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/florianhopfmueller/code/jax/jax/_src/lax/control_flow.py", line 1505, in scan
    init_flat, carry_avals, carry_avals_out, init_tree, *rest = _create_jaxpr(init)
  File "/Users/florianhopfmueller/code/jax/jax/_src/lax/control_flow.py", line 1491, in _create_jaxpr
    jaxpr, consts, out_tree = _initial_style_jaxpr(
  File "/Users/florianhopfmueller/code/jax/jax/_src/util.py", line 202, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
  File "/Users/florianhopfmueller/code/jax/jax/_src/util.py", line 195, in cached
    return f(*args, **kwargs)
  File "/Users/florianhopfmueller/code/jax/jax/_src/lax/control_flow.py", line 81, in _initial_style_jaxpr
    jaxpr, consts, out_tree = _initial_style_open_jaxpr(
  File "/Users/florianhopfmueller/code/jax/jax/_src/util.py", line 202, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
  File "/Users/florianhopfmueller/code/jax/jax/_src/util.py", line 195, in cached
    return f(*args, **kwargs)
  File "/Users/florianhopfmueller/code/jax/jax/_src/lax/control_flow.py", line 75, in _initial_style_open_jaxpr
    jaxpr, _, consts = pe.trace_to_jaxpr_dynamic(wrapped_fun, in_avals, debug)
  File "/Users/florianhopfmueller/code/jax/jax/interpreters/partial_eval.py", line 1530, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, main, in_avals)
  File "/Users/florianhopfmueller/code/jax/jax/interpreters/partial_eval.py", line 1540, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers)
  File "/Users/florianhopfmueller/code/jax/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/florianhopfmueller/code/jax/jax/experimental/ode.py", line 245, in scan_fun
    _, y_bar, t0_bar, args_bar = odeint(
  File "/Users/florianhopfmueller/code/jax/jax/experimental/ode.py", line 173, in odeint
    return _odeint_wrapper(converted, rtol, atol, mxstep, y0, t, *args, *consts)
  File "/Users/florianhopfmueller/code/jax/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/florianhopfmueller/code/jax/jax/_src/api.py", line 424, in cache_miss
    out_flat = xla.xla_call(
  File "/Users/florianhopfmueller/code/jax/jax/core.py", line 1659, in bind
    return call_bind(self, fun, *args, **params)
  File "/Users/florianhopfmueller/code/jax/jax/core.py", line 1650, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/Users/florianhopfmueller/code/jax/jax/core.py", line 1662, in process
    return trace.process_call(self, fun, tracers, params)
  File "/Users/florianhopfmueller/code/jax/jax/interpreters/partial_eval.py", line 1350, in process_call
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(f, self.main, in_avals)
  File "/Users/florianhopfmueller/code/jax/jax/interpreters/partial_eval.py", line 1540, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers)
  File "/Users/florianhopfmueller/code/jax/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/florianhopfmueller/code/jax/jax/experimental/ode.py", line 179, in _odeint_wrapper
    out = _odeint(func, rtol, atol, mxstep, y0, ts, *args)
  File "/Users/florianhopfmueller/code/jax/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/florianhopfmueller/code/jax/jax/_src/custom_derivatives.py", line 530, in __call__
    out_flat = custom_vjp_call_p.bind(flat_fun, flat_fwd, flat_bwd, *args_flat,
  File "/Users/florianhopfmueller/code/jax/jax/_src/custom_derivatives.py", line 613, in bind
    outs = top_trace.process_custom_vjp_call(self, fun, fwd, bwd, tracers,
  File "/Users/florianhopfmueller/code/jax/jax/interpreters/partial_eval.py", line 1429, in process_custom_vjp_call
    fun_jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, self.main, in_avals)
  File "/Users/florianhopfmueller/code/jax/jax/interpreters/partial_eval.py", line 1540, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers)
  File "/Users/florianhopfmueller/code/jax/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/florianhopfmueller/code/jax/jax/experimental/ode.py", line 216, in _odeint
    _, ys = lax.scan(scan_fun, init_carry, ts[1:])
  File "/Users/florianhopfmueller/code/jax/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/florianhopfmueller/code/jax/jax/_src/lax/control_flow.py", line 1505, in scan
    init_flat, carry_avals, carry_avals_out, init_tree, *rest = _create_jaxpr(init)
  File "/Users/florianhopfmueller/code/jax/jax/_src/lax/control_flow.py", line 1491, in _create_jaxpr
    jaxpr, consts, out_tree = _initial_style_jaxpr(
  File "/Users/florianhopfmueller/code/jax/jax/_src/util.py", line 202, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
  File "/Users/florianhopfmueller/code/jax/jax/_src/util.py", line 195, in cached
    return f(*args, **kwargs)
  File "/Users/florianhopfmueller/code/jax/jax/_src/lax/control_flow.py", line 81, in _initial_style_jaxpr
    jaxpr, consts, out_tree = _initial_style_open_jaxpr(
  File "/Users/florianhopfmueller/code/jax/jax/_src/util.py", line 202, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
  File "/Users/florianhopfmueller/code/jax/jax/_src/util.py", line 195, in cached
    return f(*args, **kwargs)
  File "/Users/florianhopfmueller/code/jax/jax/_src/lax/control_flow.py", line 75, in _initial_style_open_jaxpr
    jaxpr, _, consts = pe.trace_to_jaxpr_dynamic(wrapped_fun, in_avals, debug)
  File "/Users/florianhopfmueller/code/jax/jax/interpreters/partial_eval.py", line 1530, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, main, in_avals)
  File "/Users/florianhopfmueller/code/jax/jax/interpreters/partial_eval.py", line 1540, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers)
  File "/Users/florianhopfmueller/code/jax/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/florianhopfmueller/code/jax/jax/experimental/ode.py", line 206, in scan_fun
    _, *carry = lax.while_loop(cond_fun, body_fun, [0] + carry)
  File "/Users/florianhopfmueller/code/jax/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/florianhopfmueller/code/jax/jax/_src/lax/control_flow.py", line 309, in while_loop
    init_vals, init_avals, body_jaxpr, in_tree, *rest = _create_jaxpr(init_val)
  File "/Users/florianhopfmueller/code/jax/jax/_src/lax/control_flow.py", line 292, in _create_jaxpr
    body_jaxpr, body_consts, body_tree = _initial_style_jaxpr(
  File "/Users/florianhopfmueller/code/jax/jax/_src/util.py", line 202, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
  File "/Users/florianhopfmueller/code/jax/jax/_src/util.py", line 195, in cached
    return f(*args, **kwargs)
  File "/Users/florianhopfmueller/code/jax/jax/_src/lax/control_flow.py", line 81, in _initial_style_jaxpr
    jaxpr, consts, out_tree = _initial_style_open_jaxpr(
  File "/Users/florianhopfmueller/code/jax/jax/_src/util.py", line 202, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
  File "/Users/florianhopfmueller/code/jax/jax/_src/util.py", line 195, in cached
    return f(*args, **kwargs)
  File "/Users/florianhopfmueller/code/jax/jax/_src/lax/control_flow.py", line 75, in _initial_style_open_jaxpr
    jaxpr, _, consts = pe.trace_to_jaxpr_dynamic(wrapped_fun, in_avals, debug)
  File "/Users/florianhopfmueller/code/jax/jax/interpreters/partial_eval.py", line 1530, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, main, in_avals)
  File "/Users/florianhopfmueller/code/jax/jax/interpreters/partial_eval.py", line 1540, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers)
  File "/Users/florianhopfmueller/code/jax/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/florianhopfmueller/code/jax/jax/experimental/ode.py", line 196, in body_fun
    next_y, next_f, next_y_error, k = runge_kutta_step(func_, y, f, t, dt)
  File "/Users/florianhopfmueller/code/jax/jax/experimental/ode.py", line 118, in runge_kutta_step
    k = lax.fori_loop(1, 7, body_fun, k)
  File "/Users/florianhopfmueller/code/jax/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/florianhopfmueller/code/jax/jax/_src/lax/control_flow.py", line 221, in fori_loop
    (_, result), _ = scan(_fori_scan_body_fun(body_fun), (lower_, init_val),
  File "/Users/florianhopfmueller/code/jax/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/florianhopfmueller/code/jax/jax/_src/lax/control_flow.py", line 1505, in scan
    init_flat, carry_avals, carry_avals_out, init_tree, *rest = _create_jaxpr(init)
  File "/Users/florianhopfmueller/code/jax/jax/_src/lax/control_flow.py", line 1491, in _create_jaxpr
    jaxpr, consts, out_tree = _initial_style_jaxpr(
  File "/Users/florianhopfmueller/code/jax/jax/_src/util.py", line 202, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
  File "/Users/florianhopfmueller/code/jax/jax/_src/util.py", line 195, in cached
    return f(*args, **kwargs)
  File "/Users/florianhopfmueller/code/jax/jax/_src/lax/control_flow.py", line 81, in _initial_style_jaxpr
    jaxpr, consts, out_tree = _initial_style_open_jaxpr(
  File "/Users/florianhopfmueller/code/jax/jax/_src/util.py", line 202, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
  File "/Users/florianhopfmueller/code/jax/jax/_src/util.py", line 195, in cached
    return f(*args, **kwargs)
  File "/Users/florianhopfmueller/code/jax/jax/_src/lax/control_flow.py", line 75, in _initial_style_open_jaxpr
    jaxpr, _, consts = pe.trace_to_jaxpr_dynamic(wrapped_fun, in_avals, debug)
  File "/Users/florianhopfmueller/code/jax/jax/interpreters/partial_eval.py", line 1530, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, main, in_avals)
  File "/Users/florianhopfmueller/code/jax/jax/interpreters/partial_eval.py", line 1540, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers)
  File "/Users/florianhopfmueller/code/jax/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/florianhopfmueller/code/jax/jax/_src/lax/control_flow.py", line 148, in scanned_fun
    return (i + 1, body_fun(i, x)), None
  File "/Users/florianhopfmueller/code/jax/jax/experimental/ode.py", line 114, in body_fun
    ft = func(yi, ti)
  File "/Users/florianhopfmueller/code/jax/jax/experimental/ode.py", line 185, in func_
    return func(y, t, *args)
  File "/Users/florianhopfmueller/code/jax/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/florianhopfmueller/code/jax/jax/_src/custom_derivatives.py", line 910, in converted_fun
    out_flat = core.eval_jaxpr(jaxpr, consts, *all_args)
  File "/Users/florianhopfmueller/code/jax/jax/core.py", line 367, in eval_jaxpr
    ans = eval_jaxpr_eqn(eqn, map(read, eqn.invars))
  File "/Users/florianhopfmueller/code/jax/jax/core.py", line 349, in eval_jaxpr_eqn
    return eqn.primitive.bind(*(subfuns + in_vals), **bind_params)
  File "/Users/florianhopfmueller/code/jax/jax/core.py", line 278, in bind
    out = top_trace.process_primitive(self, tracers, params)
  File "/Users/florianhopfmueller/code/jax/jax/interpreters/partial_eval.py", line 1337, in process_primitive
    out_avals = primitive.abstract_eval(*avals, **params)
  File "/Users/florianhopfmueller/code/jax/jax/_src/lax/utils.py", line 67, in standard_abstract_eval
    dtype_rule(*avals, **kwargs), weak_type=weak_type,
  File "/Users/florianhopfmueller/code/jax/jax/_src/lax/lax.py", line 1342, in naryop_dtype_rule
    _check_same_dtypes(name, False, *aval_dtypes)
  File "/Users/florianhopfmueller/code/jax/jax/_src/lax/lax.py", line 4219, in _check_same_dtypes
    raise TypeError(msg.format(name, ", ".join(map(str, types))))
jax._src.traceback_util.UnfilteredStackTrace: TypeError: mul requires arguments to have the same dtypes, got float32, complex64.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/florianhopfmueller/Library/Application Support/JetBrains/PyCharmCE2021.2/scratches/debug_complex_odeint.py", line 24, in <module>
    test_complex_odeint()
  File "/Users/florianhopfmueller/Library/Application Support/JetBrains/PyCharmCE2021.2/scratches/debug_complex_odeint.py", line 21, in test_complex_odeint
    jtu.check_grads(f, (y0, ts, alpha), modes=["rev"], order=2, atol=tol, rtol=tol)
  File "/Users/florianhopfmueller/code/jax/jax/_src/test_util.py", line 337, in check_grads
    _check_grads(f, args, order)
  File "/Users/florianhopfmueller/code/jax/jax/_src/test_util.py", line 330, in _check_grads
    _check_vjp(f, partial(api.vjp, f), args, err_msg=rev_msg)
  File "/Users/florianhopfmueller/code/jax/jax/_src/test_util.py", line 287, in check_vjp
    cotangent_out = conj(vjpfun(conj(cotangent)))
  File "/Users/florianhopfmueller/code/jax/jax/_src/tree_util.py", line 326, in <lambda>
    func = lambda *args, **kw: original_func(*args, **kw)
  File "/Users/florianhopfmueller/code/jax/jax/_src/api.py", line 2340, in _vjp_pullback_wrapper
    ans = fun(*args)
  File "/Users/florianhopfmueller/code/jax/jax/_src/tree_util.py", line 326, in <lambda>
    func = lambda *args, **kw: original_func(*args, **kw)
  File "/Users/florianhopfmueller/code/jax/jax/interpreters/ad.py", line 123, in unbound_vjp
    arg_cts = backward_pass(jaxpr, reduce_axes, consts, dummy_args, cts)
  File "/Users/florianhopfmueller/code/jax/jax/interpreters/ad.py", line 222, in backward_pass
    cts_out = get_primitive_transpose(eqn.primitive)(
  File "/Users/florianhopfmueller/code/jax/jax/interpreters/ad.py", line 558, in call_transpose
    out_flat = primitive.bind(fun, *all_args, **new_params)
  File "/Users/florianhopfmueller/code/jax/jax/core.py", line 1659, in bind
    return call_bind(self, fun, *args, **params)
  File "/Users/florianhopfmueller/code/jax/jax/core.py", line 1650, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/Users/florianhopfmueller/code/jax/jax/core.py", line 1662, in process
    return trace.process_call(self, fun, tracers, params)
  File "/Users/florianhopfmueller/code/jax/jax/core.py", line 633, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/Users/florianhopfmueller/code/jax/jax/_src/dispatch.py", line 127, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, name, donated_invars,
  File "/Users/florianhopfmueller/code/jax/jax/linear_util.py", line 263, in memoized_fun
    ans = call(fun, *args)
  File "/Users/florianhopfmueller/code/jax/jax/_src/dispatch.py", line 154, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars,
  File "/Users/florianhopfmueller/code/jax/jax/_src/dispatch.py", line 167, in lower_xla_callable
    jaxpr, out_avals, consts = pe.trace_to_jaxpr_final(
  File "/Users/florianhopfmueller/code/jax/jax/interpreters/partial_eval.py", line 1562, in trace_to_jaxpr_final
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, main, in_avals)
  File "/Users/florianhopfmueller/code/jax/jax/interpreters/partial_eval.py", line 1540, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers)
  File "/Users/florianhopfmueller/code/jax/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/florianhopfmueller/code/jax/jax/interpreters/ad.py", line 228, in backward_pass
    cts_out = get_primitive_transpose(eqn.primitive)(cts_in, *invals,
  File "/Users/florianhopfmueller/code/jax/jax/interpreters/ad.py", line 690, in _custom_lin_transpose
    cts_in = bwd.call_wrapped(*res, *cts_out)
  File "/Users/florianhopfmueller/code/jax/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/florianhopfmueller/code/jax/jax/experimental/ode.py", line 255, in _odeint_rev
    (y_bar, t0_bar, args_bar), rev_ts_bar = lax.scan(
  File "/Users/florianhopfmueller/code/jax/jax/experimental/ode.py", line 245, in scan_fun
    _, y_bar, t0_bar, args_bar = odeint(
  File "/Users/florianhopfmueller/code/jax/jax/experimental/ode.py", line 173, in odeint
    return _odeint_wrapper(converted, rtol, atol, mxstep, y0, t, *args, *consts)
  File "/Users/florianhopfmueller/code/jax/jax/experimental/ode.py", line 179, in _odeint_wrapper
    out = _odeint(func, rtol, atol, mxstep, y0, ts, *args)
  File "/Users/florianhopfmueller/code/jax/jax/experimental/ode.py", line 216, in _odeint
    _, ys = lax.scan(scan_fun, init_carry, ts[1:])
  File "/Users/florianhopfmueller/code/jax/jax/experimental/ode.py", line 206, in scan_fun
    _, *carry = lax.while_loop(cond_fun, body_fun, [0] + carry)
  File "/Users/florianhopfmueller/code/jax/jax/experimental/ode.py", line 196, in body_fun
    next_y, next_f, next_y_error, k = runge_kutta_step(func_, y, f, t, dt)
  File "/Users/florianhopfmueller/code/jax/jax/experimental/ode.py", line 118, in runge_kutta_step
    k = lax.fori_loop(1, 7, body_fun, k)
  File "/Users/florianhopfmueller/code/jax/jax/experimental/ode.py", line 114, in body_fun
    ft = func(yi, ti)
  File "/Users/florianhopfmueller/code/jax/jax/experimental/ode.py", line 185, in func_
    return func(y, t, *args)
TypeError: mul requires arguments to have the same dtypes, got float32, complex64.
```

**Comment by zhangqiaorjc** [comment]
@jakevdp would you be able to help review the PR on this dtype issue in ode.py?
