### ISSUE TITLE
Unable to import jax installed using prebuilt binaries from the instructions given from readme. (Ubuntu)

### ISSUE THREAD

**Issue by nischal-sanil** [google/jax#8761]
I am unable to import JAX following the redme. Please do let me know if i am doing anything wrong.

```
$ python -V

Python 3.7.12

$ nvcc -V

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0

$ pip install jax[cuda11_cudnn805] -f https://storage.googleapis.com/jax-releases/jax_releases.html

Looking in indexes: https://pypi.org/simple, https://pip.repos.neuron.amazonaws.com
Looking in links: https://storage.googleapis.com/jax-releases/jax_releases.html
Collecting jax[cuda11_cudnn805]
  Using cached jax-0.2.25-py3-none-any.whl
Collecting absl-py
  Using cached absl_py-1.0.0-py3-none-any.whl (126 kB)
Collecting numpy>=1.18
  Using cached numpy-1.21.4-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
Collecting scipy>=1.2.1
  Using cached scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.1 MB)
Collecting typing-extensions
  Using cached typing_extensions-4.0.1-py3-none-any.whl (22 kB)
Collecting opt-einsum
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Collecting jaxlib==0.1.73+cuda11.cudnn805
  Using cached https://storage.googleapis.com/jax-releases/cuda11/jaxlib-0.1.73%2Bcuda11.cudnn805-cp37-none-manylinux2010_x86_64.whl (138.5 MB)
Collecting flatbuffers<3.0,>=1.12
  Using cached flatbuffers-2.0-py2.py3-none-any.whl (26 kB)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: six, numpy, typing-extensions, scipy, opt-einsum, flatbuffers, absl-py, jaxlib, jax
Successfully installed absl-py-1.0.0 flatbuffers-2.0 jax-0.2.25 jaxlib-0.1.73+cuda11.cudnn805 numpy-1.21.4 opt-einsum-3.3.0 scipy-1.7.3 six-1.16.0 typing-extensions-4.0.1

$ python -c "import jax"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/NS/VaxNeRF/thridparty/jax/jax/__init__.py", line 37, in <module>
    from jax import config as _config_module
  File "/home/ubuntu/NS/VaxNeRF/thridparty/jax/jax/config.py", line 18, in <module>
    from jax._src.config import config
  File "/home/ubuntu/NS/VaxNeRF/thridparty/jax/jax/_src/config.py", line 27, in <module>
    from jax._src import lib
  File "/home/ubuntu/NS/VaxNeRF/thridparty/jax/jax/_src/lib/__init__.py", line 69, in <module>
    _check_jaxlib_version()
  File "/home/ubuntu/NS/VaxNeRF/thridparty/jax/jax/_src/lib/__init__.py", line 67, in _check_jaxlib_version
    raise ValueError(msg)
ValueError: jaxlib is version 0.1.73, but this version of jax requires version 0.1.74.
```

**Comment by jakevdp** [comment]
The minimum jaxlib was incremented to 0.1.74 in https://github.com/google/jax/commit/3fd3c46f205b9a65bcd6280fd86f1b32c3201d38, which is not yet part of an external release.

This makes me think that despite having installed JAX 0.2.25, you are importing a development version. What is the result of the following?
```
$ python -c "import jax; print(jax.__path__)"
```

**Comment by jakevdp** [comment]
Actually, I see it in your traceback: you are indeed importing JAX from your git repository.

Try changing the directory so that you import the installed JAX.

Alternatively, you can run
```
pip install .[cuda11_cudnn805]
```
to install the appropriate jaxlib for your development version.

**Comment by nischal-sanil** [comment]
@jakevdp , Thank you for you quick response. Unfortunately, I have the same issue because I am unable to import Jax.

```
$ python -c "import jax; print(jax.__path__)"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/NS/VaxNeRF/thridparty/jax/jax/__init__.py", line 37, in <module>
    from jax import config as _config_module
  File "/home/ubuntu/NS/VaxNeRF/thridparty/jax/jax/config.py", line 18, in <module>
    from jax._src.config import config
  File "/home/ubuntu/NS/VaxNeRF/thridparty/jax/jax/_src/config.py", line 27, in <module>
    from jax._src import lib
  File "/home/ubuntu/NS/VaxNeRF/thridparty/jax/jax/_src/lib/__init__.py", line 69, in <module>
    _check_jaxlib_version()
  File "/home/ubuntu/NS/VaxNeRF/thridparty/jax/jax/_src/lib/__init__.py", line 67, in _check_jaxlib_version
    raise ValueError(msg)
ValueError: jaxlib is version 0.1.73, but this version of jax requires version 0.1.74.
```

**Comment by jakevdp** [comment]
Ignore that, see my second comment.

**Comment by nischal-sanil** [comment]
Oh, Yes. My bad I was import from the jax git repo. It works fine now. Thanks again for taking you time to respond.
