### ISSUE TITLE
[FR] Bitcast complex dtypes to real

### ISSUE THREAD

**Issue by PhilipVinc** [google/jax#8816]
Currently it is not allowed to bit cast complex dtypes to float. 
In particular, I'd like `complex64->float32`, `complex128->float64` and vice-versa.

I suspect this is not supported even in XLA, because after removing a few checks in jax I get the error
```python
>>> jax.lax.bitcast_convert_type(jnp.ones(3, jnp.complex64), jnp.float64)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.9/site-packages/jax/_src/lax/lax.py", line 500, in bitcast_convert_type
    return bitcast_convert_type_p.bind(operand, new_dtype=new_dtype)
  File "/Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.9/site-packages/jax/core.py", line 272, in bind
    out = top_trace.process_primitive(self, tracers, params)
  File "/Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.9/site-packages/jax/core.py", line 624, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.9/site-packages/jax/interpreters/xla.py", line 311, in apply_primitive
    compiled_fun = xla_primitive_callable(prim, *unsafe_map(arg_spec, args),
  File "/Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.9/site-packages/jax/_src/util.py", line 187, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
  File "/Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.9/site-packages/jax/_src/util.py", line 180, in cached
    return f(*args, **kwargs)
  File "/Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.9/site-packages/jax/interpreters/xla.py", line 334, in xla_primitive_callable
    compiled = _xla_callable_uncached(lu.wrap_init(prim_fun), device, None,
  File "/Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.9/site-packages/jax/interpreters/xla.py", line 653, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars,
  File "/Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.9/site-packages/jax/interpreters/xla.py", line 723, in lower_xla_callable
    out_nodes = jaxpr_subcomp(ctx, jaxpr, xla_consts, *xla_args)
  File "/Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.9/site-packages/jax/interpreters/xla.py", line 476, in jaxpr_subcomp
    map(ctx.builder.get_shape, ans)  # force xla to do shape error checking
  File "/Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.9/site-packages/jax/_src/util.py", line 43, in safe_map
    return list(map(f, *args))
RuntimeError: INVALID_ARGUMENT: Conversion from complex to real type c64[3] => F64.
```

**Comment by froystig** [comment]
What's the higher-level goal? Since XLA doesn't support this particular operation, we might be better off thinking of an approach comprising several XLA operations instead. Is this cast meant to retrieve the real/imaginary part as a float?

**Comment by PhilipVinc** [comment]
In NetKet we have some code for working with non-holomoprhic functions where we do something like

```python
params, reassemble = tree_to_real(params)
def f(W, σ):
    return forward_fn(reassemble(W), σ)

jax.grad(f)(σ) 
```

where `tree_to_real` [defined here](https://github.com/netket/netket/blob/3d6a504ff554593e06446905fe606f25381f30f3/netket/jax/utils.py#L255) essentially splits the real and imaginary part into a tuple, and we reassemble them by concatenating them again.

```
def _tree_to_real(x):
    return jax.tree_map(lambda x: (x.real, x.imag), x)

# invert the transformation using linear_transpose (AD)
def _tree_reassemble_complex(x, target, fun=_tree_to_real):
    (res,) = jax.linear_transpose(fun, target)(x)
    return tree_conj(res)

```

XLA is not smart enough to figure out that all those things are a no-operation, and we would love to be able to express this.
using bitcast would allow us to do that easily, but maybe there's another way to do that?

**Comment by froystig** [comment]
> XLA is not smart enough to figure out that all those things are a no-operation [...] but maybe there's another way to do that?

This is after compiler optimizations? If so, have you tried to manually write the inverse of `lambda x: (x.real, x.imag)` as `lambda y: lax.complex(y[0], y[1])`, instead of relying on automatic transposition? Your AD-based approach stages out roughly as follows:

```python
>>> def noop(x):
...   out, back = tree_to_real(x)
...   return back(out)
...
>>> x = jnp.ones(3, jnp.complex64)
>>> jax.make_jaxpr(noop)(x)
{ lambda ; a:c64[3]. let
    b:f32[3] = real a
    c:f32[3] = imag a
    d:f32[3] = neg c
    e:c64[3] = complex 0.0 d
    f:c64[3] = complex b 0.0
    g:c64[3] = add_any e f
    h:c64[3] = conj[input_dtype=complex64] g
  in (h,) }
```

Perhaps the compiler is not detecting the double-conjugation, since only the second is done via an explicit `conj` whereas the first is via negation, packing, and addition. I haven't tried this out, but it's my best guess from what you've shared.

**Comment by PhilipVinc** [comment]
> This is after compiler optimizations? 

I'm inspecting the 'compiled' code using 3 tools:
 - 1: `jax.make_jaxpr(fun)(arg)`, which prints the JAX IR, and of course is un-optimised
 - 2: `print(jax.jit(fun).lower(arg)._xla_computation().as_hlo_text())`  which I believe prints the unoptimised HLO (but i'm unsure)
 - 3: `print(jax.xla_computation(fun)(arg).as_hlo_text())` which is almost equivalent to (2). (It adds an extra `tuple` statement at the end, i guess because one returns a tuple and the other does not?)
 - 4: `print(jax.jit(fun).lower(arg).compile()._xla_executable().hlo_modules()[0].to_string())` which I believe prints the optimised HLO. (By the way, is there a better way to print optimised HLO?)

So of course method 1 does not yield any insight, method 3 does not report any optimisation, and indeed method 4 does show that by using `jax.lax.complex` XLA is able to figure out how to get rid of this noop! thanks!

```python
>>> import jax; import jax.numpy as jnp; import netket as nk; import netket.jax as nkjax

>>> a=jnp.ones(3, dtype=complex) + jnp.ones(3)*1j

>>> def _unpack(x):
...    return x.real, x.imag

>>> def noop1(x):
...   out = _unpack(x)
...   return jax.linear_transpose(_unpack, x)(out)[0]
>>> def noop2(x):
...   re,im = x.real, x.imag
...   return jax.lax.complex(re, im)
>>> jax.make_jaxpr(noop1)(a)
{ lambda ; a:c128[3]. let
    b:f64[3] = real a
    c:f64[3] = imag a
    d:f64[3] = neg c
    e:c128[3] = complex 0.0 d
    f:c128[3] = complex b 0.0
    g:c128[3] = add_any e f
  in (g,) }
>>> jax.make_jaxpr(noop2)(a)
{ lambda ; a:c128[3]. let
    b:f64[3] = real a
    c:f64[3] = imag a
    d:c128[3] = complex b c
  in (d,) }
>>> print(jax.xla_computation(noop1)(a).as_hlo_text())
HloModule xla_computation_noop1.14

ENTRY xla_computation_noop1.14 {
  constant.2 = pred[] constant(false)
  constant.6 = f64[] constant(0)
  broadcast.7 = f64[3]{0} broadcast(constant.6), dimensions={}
  parameter.1 = c128[3]{0} parameter(0)
  imag.4 = f64[3]{0} imag(parameter.1)
  negate.5 = f64[3]{0} negate(imag.4)
  complex.8 = c128[3]{0} complex(broadcast.7, negate.5)
  real.3 = f64[3]{0} real(parameter.1)
  constant.9 = f64[] constant(0)
  broadcast.10 = f64[3]{0} broadcast(constant.9), dimensions={}
  complex.11 = c128[3]{0} complex(real.3, broadcast.10)
  add.12 = c128[3]{0} add(complex.8, complex.11)
  ROOT tuple.13 = (c128[3]{0}) tuple(add.12)
}


>>> print(jax.xla_computation(noop2)(a).as_hlo_text())
HloModule xla_computation_noop2.7

ENTRY xla_computation_noop2.7 {
  constant.2 = pred[] constant(false)
  parameter.1 = c128[3]{0} parameter(0)
  real.3 = f64[3]{0} real(parameter.1)
  imag.4 = f64[3]{0} imag(parameter.1)
  complex.5 = c128[3]{0} complex(real.3, imag.4)
  ROOT tuple.6 = (c128[3]{0}) tuple(complex.5)
}
>>> print(jax.jit(noop1).lower(a).compile()._xla_executable().hlo_modules()[0].to_string())
HloModule jit_noop1.13

%fused_computation (param_0.2: c128[3]) -> c128[3] {
  %constant.0 = f64[] constant(0), metadata={op_type="complex" op_name="jit(noop1)/complex" source_file="<stdin>" source_line=2}
  %broadcast.0 = f64[3]{0} broadcast(f64[] %constant.0), dimensions={}, metadata={op_type="complex" op_name="jit(noop1)/complex" source_file="<stdin>" source_line=2}
  %param_0.2 = c128[3]{0} parameter(0)
  %imag.0 = f64[3]{0} imag(c128[3]{0} %param_0.2), metadata={op_type="imag" op_name="jit(noop1)/imag" source_file="<stdin>" source_line=2}
  %negate.0 = f64[3]{0} negate(f64[3]{0} %imag.0), metadata={op_type="neg" op_name="jit(noop1)/neg" source_file="<stdin>" source_line=2}
  %complex.1 = c128[3]{0} complex(f64[3]{0} %broadcast.0, f64[3]{0} %negate.0), metadata={op_type="complex" op_name="jit(noop1)/complex" source_file="<stdin>" source_line=2}
  %real.0 = f64[3]{0} real(c128[3]{0} %param_0.2), metadata={op_type="real" op_name="jit(noop1)/real" source_file="<stdin>" source_line=2}
  %complex.0 = c128[3]{0} complex(f64[3]{0} %real.0, f64[3]{0} %broadcast.0), metadata={op_type="complex" op_name="jit(noop1)/complex" source_file="<stdin>" source_line=2}
  ROOT %add.0 = c128[3]{0} add(c128[3]{0} %complex.1, c128[3]{0} %complex.0), metadata={op_type="add_any" op_name="jit(noop1)/add_any" source_file="<stdin>" source_line=3}
}

ENTRY %jit_noop1.13 (parameter.1: c128[3]) -> c128[3] {
  %parameter.1 = c128[3]{0} parameter(0)
  ROOT %fusion = c128[3]{0} fusion(c128[3]{0} %parameter.1), kind=kLoop, calls=%fused_computation, metadata={op_type="add_any" op_name="jit(noop1)/add_any" source_file="<stdin>" source_line=3}
}


>>> print(jax.jit(noop2).lower(a).compile()._xla_executable().hlo_modules()[0].to_string())
HloModule jit_noop2.6

ENTRY %jit_noop2.6 (parameter.1: c128[3]) -> c128[3] {
  %parameter.1 = c128[3]{0} parameter(0), metadata={op_type="complex" op_name="jit(noop2)/complex" source_file="<stdin>" source_line=3}
  ROOT %copy = c128[3]{0} copy(c128[3]{0} %parameter.1)
}
```

**Comment by PhilipVinc** [comment]
@froystig Still, since I have to apply this operation to a PyTree, using `jax.linear_transpose` was the easiest way to _reverse_ the real-imaginary splitting on the tree. 

Using `bitcast` was exactly how I envisaged avoiding `jax.linear_tranpose`. 
If I can't use nor bitcast nor `jax.linear_transpose`, it means I'll have to write some logic to do this...

**Comment by soraros** [comment]
@PhilipVinc 
> Is there a better way to print optimised HLO

You can do this:
```python
opt = jax.lib.xla_extension.HloPrintOptions.short_parsable()
f.lower().compile().compiler_ir()[0].to_string(opt)
```

**Comment by PhilipVinc** [comment]
@soraros On `jax.__version__==0.2.26` both don't work because
```python
>>> jax.jit(noop1).lower(a).compile_ir()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Lowered' object has no attribute 'compile_ir'
>>> jax.jit(noop1).lower(a).compile_ir()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Lowered' object has no attribute 'compile_ir'
```

**Comment by soraros** [comment]
@PhilipVinc Ah, sorry, I should have mentioned it requires master. But I think master is stable™ enough.

**Comment by froystig** [comment]
> by using jax.lax.complex XLA is able to figure out how to get rid of this noop! thanks!

Great. I'm glad that a solution exists.

> Still, since I have to apply this operation to a PyTree, using jax.linear_transpose was the easiest way to reverse the real-imaginary splitting on the tree. Using bitcast was exactly how I envisaged avoiding jax.linear_tranpose.

Custom transposition is still in development, but perhaps we could imagine using it here. If we defined `real_and_imag = lambda x: (x.real, x.imag)` with a custom JVP/transpose that bottoms out in `lax.conj` explicitly, then maybe the double-conjugation would be recognized and optimized away.

(I'm not even sure whether double-conjugations are indeed optimized out today, but conceptually it seems easier to do.)

> AttributeError: 'Lowered' object has no attribute 'compile_ir'

You're picking up a fresh API under active development! I haven't even documented this publicly yet. Follow #7733 for updates.

**Comment by froystig** [comment]
Closing this issue since we have a solution. Discussion can continue and re-opening is always an option.
