### ISSUE TITLE
DeviceArray as static argument: incompatible with jit cache?

### ISSUE THREAD

**Issue by andihwolf** [google/jax#883]
First of all, thank you for this nice package. I had quite some fun playing around with it in the past couple of days.
I am getting errors as soon as I call a `jit`ed function for the second time if that function treats an argument of type `DeviceArray` as static. The error occurs while querying if the function is already cached. A minimal example is shown below:
```python
import jax.numpy as np
from jax import jit, partial

@partial(jit, static_argnums=(1,))
def f(x,v):
    return x

def main():
    x = np.ones((10,10))
    v = np.array([1,2,3])
    firstCall = f(x,v)
    print(firstCall)
    secondCall = f(x,v)
    print(secondCall)

if __name__=='__main__':
    main()
```
The raised error:
```python
Traceback (most recent call last):

  File "<ipython-input-7-563ff9ef5fe4>", line 1, in <module>
    runfile('/home/hpc/capm/sn0523/SIR/minExample.py', wdir='/home/hpc/capm/sn0523/SIR')

  File "/home/hpc/capm/sn0523/jax/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/home/hpc/capm/sn0523/jax/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/hpc/capm/sn0523/SIR/minExample.py", line 25, in <module>
    main()

  File "/home/hpc/capm/sn0523/SIR/minExample.py", line 21, in main
    secondCall = f(x,v)

  File "/home/hpc/capm/sn0523/jax/lib/python3.6/site-packages/jax/api.py", line 123, in f_jitted
    out = xla.xla_call(flat_fun, *args_flat, device_values=device_values)

  File "/home/hpc/capm/sn0523/jax/lib/python3.6/site-packages/jax/core.py", line 658, in call_bind
    ans = primitive.impl(f, *args, **params)

  File "/home/hpc/capm/sn0523/jax/lib/python3.6/site-packages/jax/interpreters/xla.py", line 653, in xla_call_impl
    compiled_fun = xla_callable(fun, device_values, *map(abstractify, args))

  File "/home/hpc/capm/sn0523/jax/lib/python3.6/site-packages/jax/linear_util.py", line 201, in memoized_fun
    if key in cache:

  File "/home/hpc/capm/sn0523/jax/lib/python3.6/site-packages/jax/linear_util.py", line 174, in __eq__
    return self.hashable_payload() == other.hashable_payload()

  File "/home/hpc/capm/sn0523/jax/lib/python3.6/site-packages/jax/interpreters/xla.py", line 489, in forward_method
    return fun(getattr(self, attrname), *args)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
Surprisingly - at least for me - the same code runs flawlessly if the static argument is a ordinary `numpy.ndarray`. Is this a bug or the intended behavior?

**Comment by mattjj** [comment]
Definitely a bug! Thanks for the simple repro.

**Comment by mattjj** [comment]
By the way, thanks for the kind words about JAX in your message. The whole team finds comments like those really encouraging. They also help us make the case that JAX is having real impacts.

**Comment by romanodev** [comment]
JAX is indeed a nice tool. I still can't run the above repro with the latest version of JAX. 
JAX: 0.2.7
jaxlib:0.1.57

Thanks!

**Comment by jakevdp** [comment]
Hi - I believe it's now intentional that this code fails, as non-hashable static arguments are unsupported as of recent releases. See #4717 for the change that introduced this and a bit of background for why this is the cse.

**Comment by romanodev** [comment]
@jakevdp - thank you!
