### ISSUE TITLE
Linux Mint 20.2 Cinnamon. Nvidia MX250. cuda_11.5.1_495.29.05_linux 

### ISSUE THREAD

**Issue by eric0111** [google/jax#8916]
PC 
Linux Mint 20.2 Cinnamon
Nvidia MX250
cuda_11.5.1_495.29.05_linux 
cudnn-local-repo-ubuntu2004-8.3.1.22_1.0-1_amd64

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0

nvidia-smi
| NVIDIA-SMI 450.156.00   Driver Version: 450.156.00   CUDA Version: 11.0 

CODE
e_norm = -1/2 * (-jnp.sum(digamma((nu_MIX[k] - l)/2)) + jnp.log(jdet(PHI_MIX[k, :, :]))
                         + p/lambda_MIX[k] + nu_MIX[k] * jnp.diag( (y - mu_MIX[k,:]) @ jinv(PHI_MIX[k, :, :]) @ (y - mu_MIX[k,:]).T) )

ERROR LOG
2021-12-13 01:41:41.190919: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2086] Execution of replica 0 failed: INTERNAL: CustomCall failed: jaxlib/cusolver_kernels.cc:44: operation cusolverDnCreate(&handle) failed: cuSolver internal error

Ran 1 test in 6.889s

FAILED (errors=1)

Error
Traceback (most recent call last):
  File "/opt/pycharm-community-2021.3/plugins/python-ce/helpers/pycharm/_jb_unittest_runner.py", line 35, in <module>
    sys.exit(main(argv=args, module=None, testRunner=unittestpy.TeamcityTestRunner, buffer=not JB_DISABLE_BUFFERING))
  File "/usr/lib/python3.8/unittest/main.py", line 101, in __init__
    self.runTests()
  File "/usr/lib/python3.8/unittest/main.py", line 271, in runTests
    self.result = testRunner.run(self.test)
  File "/opt/pycharm-community-2021.3/plugins/python-ce/helpers/pycharm/teamcity/unittestpy.py", line 310, in run
    return super(TeamcityTestRunner, self).run(test)
  File "/usr/lib/python3.8/unittest/runner.py", line 176, in run
    test(result)
  File "/usr/lib/python3.8/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.8/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.8/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.8/unittest/suite.py", line 122, in run
    test(result)
  File "/home/eb/PycharmProjects/VariationalBRAND/tests/cavi/elbo/test_elbo_calculator.py", line 28, in test_elbo_calculator
    update_parameters(data, hyperparameters_model, variational_parameters)
  File "/home/eb/PycharmProjects/VariationalBRAND/root/controller/cavi/updater/parameters_updater.py", line 33, in update_parameters
    update_phi_mk(data, variational_parameters, hyperparameters.T, hyperparameters.J)
  File "/home/eb/PycharmProjects/VariationalBRAND/root/controller/cavi/updater/parameters_updater.py", line 374, in update_phi_mk
    + p/lambda_MIX[k] + nu_MIX[k] * jnp.diag( (y - mu_MIX[k,:]) @ jinv(PHI_MIX[k, :, :]) @ (y - mu_MIX[k,:]).T) )
  File "/home/eb/PycharmProjects/VariationalBRAND/jax/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/eb/PycharmProjects/VariationalBRAND/jax/jax/_src/api.py", line 424, in cache_miss
    out_flat = xla.xla_call(
  File "/home/eb/PycharmProjects/VariationalBRAND/jax/jax/core.py", line 1661, in bind
    return call_bind(self, fun, *args, **params)
  File "/home/eb/PycharmProjects/VariationalBRAND/jax/jax/core.py", line 1652, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/home/eb/PycharmProjects/VariationalBRAND/jax/jax/core.py", line 1664, in process
    return trace.process_call(self, fun, tracers, params)
  File "/home/eb/PycharmProjects/VariationalBRAND/jax/jax/core.py", line 633, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/eb/PycharmProjects/VariationalBRAND/jax/jax/_src/dispatch.py", line 132, in _xla_call_impl
    out = compiled_fun(*args)
  File "/home/eb/PycharmProjects/VariationalBRAND/jax/jax/_src/dispatch.py", line 440, in _execute_compiled
    out_bufs = compiled.execute(input_bufs)
jax._src.traceback_util.UnfilteredStackTrace: RuntimeError: INTERNAL: CustomCall failed: jaxlib/cusolver_kernels.cc:44: operation cusolverDnCreate(&handle) failed: cuSolver internal error

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/eb/PycharmProjects/VariationalBRAND/tests/cavi/elbo/test_elbo_calculator.py", line 28, in test_elbo_calculator
    update_parameters(data, hyperparameters_model, variational_parameters)
  File "/home/eb/PycharmProjects/VariationalBRAND/root/controller/cavi/updater/parameters_updater.py", line 33, in update_parameters
    update_phi_mk(data, variational_parameters, hyperparameters.T, hyperparameters.J)
  File "/home/eb/PycharmProjects/VariationalBRAND/root/controller/cavi/updater/parameters_updater.py", line 374, in update_phi_mk
    + p/lambda_MIX[k] + nu_MIX[k] * jnp.diag( (y - mu_MIX[k,:]) @ jinv(PHI_MIX[k, :, :]) @ (y - mu_MIX[k,:]).T) )
  File "/home/eb/PycharmProjects/VariationalBRAND/jax/jax/_src/dispatch.py", line 440, in _execute_compiled
    out_bufs = compiled.execute(input_bufs)
RuntimeError: INTERNAL: CustomCall failed: jaxlib/cusolver_kernels.cc:44: operation cusolverDnCreate(&handle) failed: cuSolver internal error

**Comment by jecampagne** [comment]
Hi, I think I expereince a similar bug on Nvidia V100 GPU

jax                       0.2.25             pyhd8ed1ab_0    conda-forge
jaxlib                    0.1.73+cuda11.cudnn82          pypi_0    pypi

```python
a = jax.numpy.array([[ 1.01290589e-03,  2.75272126e-05, -2.69166597e-04,
        -5.58780779e-06],
       [ 2.75272126e-05,  1.34740128e-03, -4.34192721e-06,
        -3.00849575e-04],
       [-2.69166597e-04, -4.34192721e-06,  1.28766222e-04,
         7.41944929e-07],
       [-5.58780779e-06, -3.00849575e-04,  7.41944929e-07,
         7.99537441e-05]])

numpy.linalg.cholesky(a)   # ok

jax.numpy.linalg.cholesky(a)   # NOk
```
With the trace
```
anaconda3/envs/jaxcosmo/lib/python3.8/site-packages/jax/_src/numpy/linalg.py in cholesky(***failed resolving arguments***)
     51   a = _promote_arg_dtypes(jnp.asarray(a))
---> 52   return lax_linalg.cholesky(a)
     53 

JaxStackTraceBeforeTransformation: RuntimeError: jaxlib/cusolver_kernels.cc:44: operation cusolverDnCreate(&handle) failed: cuSolver internal error

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_18467/2727132939.py in <module>
----> 1 jnp.linalg.cholesky(a)

    [... skipping hidden 12 frame]

/anaconda3/envs/jaxcosmo/lib/python3.8/site-packages/jaxlib/cusolver.py in potrf(c, a, lower)
    101   batch = _prod(batch_dims)
    102 
--> 103   lwork, opaque = _cusolver.build_potrf_descriptor(
    104       np.dtype(dtype), lower, batch, n)
    105   kernel = b"cusolver_potrf"

RuntimeError: jaxlib/cusolver_kernels.cc:44: operation cusolverDnCreate(&handle) failed: cuSolver internal error
```

**Comment by hawkinsp** [comment]
@eric0111 I have a guess at what's going on here, and it might be that JAX is preallocating too much GPU memory. I believe an MX250 only has ~4GiB of GPU RAM. Can you try lowering `XLA_PYTHON_CLIENT_MEM_FRACTION` (https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html) to something like `.5`? Let me know if that works!

However, I do caution you your Nvidia driver version appears to be too old for JAX. You need a version compatible with CUDA 11.4, which I think is 470 or newer.

@jecampagne Can you also try lowering the preallocate fraction? I'm less sure that's your issue, because a V100 has a lot more GPU RAM.

**Comment by eric0111** [comment]
> @eric0111 I have a guess at what's going on here, and it might be that JAX is preallocating too much GPU memory. I believe an MX250 only has ~4GiB of GPU RAM. Can you try lowering `XLA_PYTHON_CLIENT_MEM_FRACTION` (https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html) to something like `.5`? Let me know if that works!
> 
> However, I do caution you your Nvidia driver version appears to be too old for JAX. You need a version compatible with CUDA 11.4, which I think is 470 or newer.
> 

@hawkinsp Hi Peter, thank you for the reply. 
I have updagred to the latest nvidia drivers 495.29.05 and set XLA_PYTHON_CLIENT_MEM_FRACTION = 0.5 and then 0.1 (via sudo nano ~/.bashrc, export XLA_PYTHON_CLIENT_MEM_FRACTION=.1,source ~/.bashrc ). I still have problems.

PC SPECS 
Linux Mint 20.2 Cinnamon
Nvidia MX250
cuda_11.5.1_495.29.05_linux
cudnn-local-repo-ubuntu2004-8.3.1.22_1.0-1_amd64

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0

nvidia-smi
NVIDIA-SMI 495.29.05    Driver Version: 495.29.05    CUDA Version: 11.5   

CODE 
from jax._src.numpy.linalg import inv as jinv
from jax import numpy as jnp

def buggy_example():
    PHI_MIX = jnp.array([[[ 3.28045,0.17521389],
                        [ 0.17521389 , 5.1232452 ]],

                        [[ 4.6521783 , -0.8761855 ],
                        [-0.8761855  , 2.734903  ]],

                        [[ 2.9329915 , -0.18445067],
                        [-0.18445067 , 3.064779  ]]])

    out = jinv(PHI_MIX[0, :, :])


buggy_example()

STACK TRACE
Traceback (most recent call last):
  File "/home/eb/PycharmProjects/VariationalBRAND/bin/jax_bugs.py", line 37, in <module>
    buggy_example()
  File "/home/eb/PycharmProjects/VariationalBRAND/bin/jax_bugs.py", line 34, in buggy_example
    out = jinv(PHI_MIX[0, :, :])
  File "/home/eb/PycharmProjects/VariationalBRAND/venv/lib/python3.8/site-packages/jax/_src/numpy/linalg.py", line 389, in inv
    return solve(
  File "/home/eb/PycharmProjects/VariationalBRAND/venv/lib/python3.8/site-packages/jax/_src/numpy/linalg.py", line 503, in solve
    return lax_linalg._solve(a, b)
jax._src.source_info_util.JaxStackTraceBeforeTransformation: RuntimeError: jaxlib/cusolver_kernels.cc:44: operation cusolverDnCreate(&handle) failed: cuSolver internal error

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/eb/PycharmProjects/VariationalBRAND/bin/jax_bugs.py", line 37, in <module>
    buggy_example()
  File "/home/eb/PycharmProjects/VariationalBRAND/bin/jax_bugs.py", line 34, in buggy_example
    out = jinv(PHI_MIX[0, :, :])
  File "/home/eb/PycharmProjects/VariationalBRAND/venv/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/eb/PycharmProjects/VariationalBRAND/venv/lib/python3.8/site-packages/jax/_src/api.py", line 424, in cache_miss
    out_flat = xla.xla_call(
  File "/home/eb/PycharmProjects/VariationalBRAND/venv/lib/python3.8/site-packages/jax/core.py", line 1661, in bind
    return call_bind(self, fun, *args, **params)
  File "/home/eb/PycharmProjects/VariationalBRAND/venv/lib/python3.8/site-packages/jax/core.py", line 1652, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/home/eb/PycharmProjects/VariationalBRAND/venv/lib/python3.8/site-packages/jax/core.py", line 1664, in process
    return trace.process_call(self, fun, tracers, params)
  File "/home/eb/PycharmProjects/VariationalBRAND/venv/lib/python3.8/site-packages/jax/core.py", line 633, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/eb/PycharmProjects/VariationalBRAND/venv/lib/python3.8/site-packages/jax/_src/dispatch.py", line 128, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, name, donated_invars,
  File "/home/eb/PycharmProjects/VariationalBRAND/venv/lib/python3.8/site-packages/jax/linear_util.py", line 263, in memoized_fun
    ans = call(fun, *args)
  File "/home/eb/PycharmProjects/VariationalBRAND/venv/lib/python3.8/site-packages/jax/_src/dispatch.py", line 155, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars,
  File "/home/eb/PycharmProjects/VariationalBRAND/venv/lib/python3.8/site-packages/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/home/eb/PycharmProjects/VariationalBRAND/venv/lib/python3.8/site-packages/jax/_src/dispatch.py", line 229, in lower_xla_callable
    module = xla.lower_jaxpr_to_xla_module(
  File "/home/eb/PycharmProjects/VariationalBRAND/venv/lib/python3.8/site-packages/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/home/eb/PycharmProjects/VariationalBRAND/venv/lib/python3.8/site-packages/jax/interpreters/xla.py", line 758, in lower_jaxpr_to_xla_module
    out_nodes = jaxpr_subcomp(ctx, jaxpr.jaxpr, xla_consts, *xla_args)
  File "/home/eb/PycharmProjects/VariationalBRAND/venv/lib/python3.8/site-packages/jax/interpreters/xla.py", line 585, in jaxpr_subcomp
    ans = rule(ctx, map(aval, eqn.invars), map(aval, eqn.outvars),
  File "/home/eb/PycharmProjects/VariationalBRAND/venv/lib/python3.8/site-packages/jax/interpreters/xla.py", line 834, in _xla_call_translation_rule
    out_nodes = jaxpr_subcomp(sub_ctx, call_jaxpr, (), *args)
  File "/home/eb/PycharmProjects/VariationalBRAND/venv/lib/python3.8/site-packages/jax/interpreters/xla.py", line 585, in jaxpr_subcomp
    ans = rule(ctx, map(aval, eqn.invars), map(aval, eqn.outvars),
  File "/home/eb/PycharmProjects/VariationalBRAND/venv/lib/python3.8/site-packages/jax/_src/lax/linalg.py", line 1016, in _lu_cpu_gpu_translation_rule
    lu, pivot, info = getrf_impl(c, operand)
  File "/home/eb/PycharmProjects/VariationalBRAND/venv/lib/python3.8/site-packages/jaxlib/cusolver.py", line 144, in getrf
    lwork, opaque = _cusolver.build_getrf_descriptor(
jax._src.traceback_util.UnfilteredStackTrace: RuntimeError: jaxlib/cusolver_kernels.cc:44: operation cusolverDnCreate(&handle) failed: cuSolver internal error

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/eb/PycharmProjects/VariationalBRAND/bin/jax_bugs.py", line 37, in <module>
    buggy_example()
  File "/home/eb/PycharmProjects/VariationalBRAND/bin/jax_bugs.py", line 34, in buggy_example
    out = jinv(PHI_MIX[0, :, :])
  File "/home/eb/PycharmProjects/VariationalBRAND/venv/lib/python3.8/site-packages/jaxlib/cusolver.py", line 144, in getrf
    lwork, opaque = _cusolver.build_getrf_descriptor(
RuntimeError: jaxlib/cusolver_kernels.cc:44: operation cusolverDnCreate(&handle) failed: cuSolver internal error

**Comment by jecampagne** [comment]
@hawkinsp  no change :(

**Comment by YoannMR** [comment]
@hawkinsp I'm having a similar issue. Do you have another suggestion?

**Comment by jingyueliu6** [comment]
I met the same problem in Pycharm. But it runs well in VS code. Do you have any idea?

**Comment by linyuhongg** [comment]
For me setting XLA_PYTHON_CLIENT_PREALLOCATE to false has solved the problem

**Comment by timnotavailable** [comment]
Hello sorry to comment here again. It seems that the solution which  to decrease the pre-allocated GPU memory or disable the pre-allocated GPU memory does not works for me.

I've tried a very small example:

import jax
import jax.numpy as jnp

key = jax.random.PRNGKey(0)
A = jax.random.uniform(key, (3, 3))

# Perform a Cholesky decomposition (uses cuSOLVER)
L = jnp.linalg.cholesky(A @ A.T)  # Ensure A is positive definite
print("Cholesky decomposition:\n", L)

However the error always raised:
---------------------------------------------------------------------------
XlaRuntimeError                           Traceback (most recent call last)
Cell In[1], [line 12](vscode-notebook-cell:?execution_count=1&line=12)
      [9](vscode-notebook-cell:?execution_count=1&line=9) A = jax.random.uniform(key, (3, 3))
     [11](vscode-notebook-cell:?execution_count=1&line=11) # Perform a Cholesky decomposition (uses cuSOLVER)
---> [12](vscode-notebook-cell:?execution_count=1&line=12) L = jnp.linalg.cholesky(A @ A.T)  # Ensure A is positive definite
     [13](vscode-notebook-cell:?execution_count=1&line=13) print("Cholesky decomposition:\n", L)

    [... skipping hidden 11 frame]

File ~/conda3/anaconda3/envs/bloch/lib/python3.12/site-packages/jax/_src/compiler.py:324, in backend_compile(backend, module, options, host_callbacks)
    [318](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/revolution/BlochSimu/~/conda3/anaconda3/envs/bloch/lib/python3.12/site-packages/jax/_src/compiler.py:318)     return backend.compile(
    [319](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/revolution/BlochSimu/~/conda3/anaconda3/envs/bloch/lib/python3.12/site-packages/jax/_src/compiler.py:319)         built_c, compile_options=options, host_callbacks=host_callbacks
    [320](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/revolution/BlochSimu/~/conda3/anaconda3/envs/bloch/lib/python3.12/site-packages/jax/_src/compiler.py:320)     )
    [321](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/revolution/BlochSimu/~/conda3/anaconda3/envs/bloch/lib/python3.12/site-packages/jax/_src/compiler.py:321)   # Some backends don't have `host_callbacks` option yet
    [322](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/revolution/BlochSimu/~/conda3/anaconda3/envs/bloch/lib/python3.12/site-packages/jax/_src/compiler.py:322)   # TODO(sharadmv): remove this fallback when all backends allow `compile`
    [323](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/revolution/BlochSimu/~/conda3/anaconda3/envs/bloch/lib/python3.12/site-packages/jax/_src/compiler.py:323)   # to take in `host_callbacks`
--> [324](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/revolution/BlochSimu/~/conda3/anaconda3/envs/bloch/lib/python3.12/site-packages/jax/_src/compiler.py:324)   return backend.compile(built_c, compile_options=options)
    [325](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/revolution/BlochSimu/~/conda3/anaconda3/envs/bloch/lib/python3.12/site-packages/jax/_src/compiler.py:325) except xc.XlaRuntimeError as e:
    [326](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/revolution/BlochSimu/~/conda3/anaconda3/envs/bloch/lib/python3.12/site-packages/jax/_src/compiler.py:326)   for error_handler in _XLA_RUNTIME_ERROR_HANDLERS:

XlaRuntimeError: INTERNAL: cuSolver internal error

I've checked and updated all the possible relating factors: Drivers, cuda toolkit, jax version, cuda version, setting XLA_PYTHON_CLIENT_PREALLOCATE to false, but cannot solve:

I'm using WSL2 , other CUDA parameters are below

| NVIDIA-SMI 555.58.02              Driver Version: 556.12         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4080 ...    On  |   00000000:01:00.0  On |                  N/A |
| N/A   53C    P8              6W /  175W |   10416MiB /  12282MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A     63349      C   /python3.12                                 N/A      |


nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2025 NVIDIA Corporation
Built on Wed_Jan_15_19:20:09_PST_2025
Cuda compilation tools, release 12.8, V12.8.61
Build cuda_12.8.r12.8/compiler.35404655_0


jax                       0.5.2                    
jax-cuda12-pjrt           0.5.1              
jax-cuda12-plugin         0.5.1            
jaxlib                    0.5.1            

Do you know how should I solve it?

**Comment by aespielberg** [comment]
Same error here.  JAX_TRACEBACK_FILTERING=off XLA_PYTHON_CLIENT_PREALLOCATE=false

Running @timnotavailable 's minimalist script, I get the same output.

`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2025 NVIDIA Corporation
Built on Fri_Feb_21_20:23:50_PST_2025
Cuda compilation tools, release 12.8, V12.8.93
Build cuda_12.8.r12.8/compiler.35583870_0
`

Driver Version: 570.124.06 

This is on an ADA 5000 RTX GPU, Ubuntu 24.04.2 LTS.  I tried Jax 0.4.31 as well; same problem.  Could there be some incompatibility with CUDA 12.8?

` $conda list
# packages in environment at /home/user/anaconda3/envs/test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
absl-py                   2.2.2                    pypi_0    pypi
ampl-asl                  1.0.0                h5888daf_2    conda-forge
asttokens                 3.0.0              pyhd8ed1ab_1    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
ca-certificates           2025.4.26            hbd8a1cb_0    conda-forge
cfgv                      3.4.0                    pypi_0    pypi
cloudpickle               3.1.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_1    conda-forge
comm                      0.2.2              pyhd8ed1ab_1    conda-forge
contourpy                 1.3.2                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
debugpy                   1.8.14          py311hfdbb021_0    conda-forge
decorator                 5.2.1              pyhd8ed1ab_0    conda-forge
distlib                   0.3.9                    pypi_0    pypi
equinox                   0.12.1                   pypi_0    pypi
etils                     1.12.2                   pypi_0    pypi
exceptiongroup            1.2.2              pyhd8ed1ab_1    conda-forge
executing                 2.2.0              pyhd8ed1ab_0    conda-forge
filelock                  3.18.0                   pypi_0    pypi
fonttools                 4.57.0                   pypi_0    pypi
fsspec                    2025.3.2                 pypi_0    pypi
glfw                      2.9.0                    pypi_0    pypi
icu                       75.1                 he02047a_0    conda-forge
identify                  2.6.10                   pypi_0    pypi
importlib-metadata        8.6.1              pyha770c72_0    conda-forge
importlib-resources       6.5.2                    pypi_0    pypi
iniconfig                 2.1.0                    pypi_0    pypi
ipopt                     3.14.16             h59d4785_11    conda-forge
ipykernel                 6.29.5             pyh3099207_0    conda-forge
ipyparallel               9.0.1              pyh29332c3_0    conda-forge
ipython                   9.2.0              pyhfb0248b_0    conda-forge
ipython_pygments_lexers   1.1.1              pyhd8ed1ab_0    conda-forge
jax                       0.6.0                    pypi_0    pypi
jax-cuda12-pjrt           0.6.0                    pypi_0    pypi
jax-cuda12-plugin         0.6.0                    pypi_0    pypi
jaxlib                    0.6.0                    pypi_0    pypi
jaxtyping                 0.3.2                    pypi_0    pypi
jedi                      0.19.2             pyhd8ed1ab_1    conda-forge
jupyter_client            8.6.3              pyhd8ed1ab_1    conda-forge
jupyter_core              5.7.2              pyh31011fe_1    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.8                    pypi_0    pypi
krb5                      1.21.3               h659f571_0    conda-forge
ld_impl_linux-64          2.43                 h712a8e2_4    conda-forge
libblas                   3.9.0           31_h59b9bed_openblas    conda-forge
libboost                  1.84.0               h6c02f8c_7    conda-forge
libcblas                  3.9.0           31_he106b2a_openblas    conda-forge
libedit                   3.1.20250104    pl5321h7949ede_0    conda-forge
libexpat                  2.7.0                h5888daf_0    conda-forge
libffi                    3.4.6                h2dba641_1    conda-forge
libgcc                    14.2.0               h767d61c_2    conda-forge
libgcc-ng                 14.2.0               h69a702a_2    conda-forge
libgfortran               14.2.0               h69a702a_2    conda-forge
libgfortran-ng            14.2.0               h69a702a_2    conda-forge
libgfortran5              14.2.0               hf1ad2bd_2    conda-forge
libgomp                   14.2.0               h767d61c_2    conda-forge
libhwloc                  2.11.2          default_h0d58e46_1001    conda-forge
libiconv                  1.18                 h4ce23a2_1    conda-forge
liblapack                 3.9.0           31_h7ac8fdf_openblas    conda-forge
liblzma                   5.8.1                hb9d3cd8_0    conda-forge
liblzma-devel             5.8.1                hb9d3cd8_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.29          pthreads_h94d23a6_0    conda-forge
libscotch                 7.0.4                h2fe6a88_5    conda-forge
libsodium                 1.0.20               h4ab18f5_0    conda-forge
libspral                  2024.05.08           h2b245be_4    conda-forge
libsqlite                 3.49.1               hee588c1_2    conda-forge
libstdcxx                 14.2.0               h8f9b012_2    conda-forge
libstdcxx-ng              14.2.0               h4852527_2    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.13.7               h4bc477f_1    conda-forge
libzlib                   1.3.1                hb9d3cd8_2    conda-forge
matplotlib                3.9.2                    pypi_0    pypi
matplotlib-inline         0.1.7              pyhd8ed1ab_1    conda-forge
mediapy                   1.2.2                    pypi_0    pypi
metis                     5.1.0             hd0bcaf9_1007    conda-forge
ml-dtypes                 0.5.1                    pypi_0    pypi
mujoco                    3.2.3                    pypi_0    pypi
mujoco-mjx                3.2.3                    pypi_0    pypi
multimethod               1.12                     pypi_0    pypi
mumps-include             5.7.3               h82cca05_10    conda-forge
mumps-seq                 5.7.3                h27a6a8b_0    conda-forge
ncurses                   6.5                  h2d0b736_3    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_1    conda-forge
networkx                  3.4.2              pyh267e887_2    conda-forge
nlopt                     2.7.1           py311he50ff42_5    conda-forge
nodeenv                   1.9.1                    pypi_0    pypi
numpy                     2.1.1                    pypi_0    pypi
nvidia-cublas-cu12        12.9.0.13                pypi_0    pypi
nvidia-cuda-cupti-cu12    12.9.19                  pypi_0    pypi
nvidia-cuda-nvcc-cu12     12.9.41                  pypi_0    pypi
nvidia-cuda-runtime-cu12  12.9.37                  pypi_0    pypi
nvidia-cudnn-cu12         9.9.0.52                 pypi_0    pypi
nvidia-cufft-cu12         11.4.0.6                 pypi_0    pypi
nvidia-cusolver-cu12      11.7.4.40                pypi_0    pypi
nvidia-cusparse-cu12      12.5.9.5                 pypi_0    pypi
nvidia-nccl-cu12          2.26.5                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.9.41                  pypi_0    pypi
openssl                   3.5.0                h7b32b05_1    conda-forge
opt-einsum                3.4.0                    pypi_0    pypi
packaging                 25.0               pyh29332c3_1    conda-forge
pagmo                     2.19.1               h372fa70_0    conda-forge
parso                     0.8.4              pyhd8ed1ab_1    conda-forge
pexpect                   4.9.0              pyhd8ed1ab_1    conda-forge
pickleshare               0.7.5           pyhd8ed1ab_1004    conda-forge
pillow                    11.2.1                   pypi_0    pypi
pip                       25.1.1             pyh8b19718_0    conda-forge
platformdirs              4.3.7              pyh29332c3_0    conda-forge
pluggy                    1.5.0                    pypi_0    pypi
pre-commit                4.2.0                    pypi_0    pypi
prompt-toolkit            3.0.51             pyha770c72_0    conda-forge
psutil                    7.0.0           py311h9ecbd09_0    conda-forge
ptyprocess                0.7.0              pyhd8ed1ab_1    conda-forge
pure_eval                 0.2.3              pyhd8ed1ab_1    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pygments                  2.19.1             pyhd8ed1ab_0    conda-forge
pygmo                     2.19.7          py311hbf6807a_0    conda-forge
pygmo_plugins_nonfree     0.24            py311hadaa38c_2    conda-forge
pyopengl                  3.1.9                    pypi_0    pypi
pyparsing                 3.2.3                    pypi_0    pypi
pytest                    8.3.5                    pypi_0    pypi
pytest-mock               3.14.0                   pypi_0    pypi
python                    3.11.12         h9e4cc4f_0_cpython    conda-forge
python-dateutil           2.9.0.post0        pyhff2d567_1    conda-forge
python_abi                3.11                    7_cp311    conda-forge
pyyaml                    6.0.2                    pypi_0    pypi
pyzmq                     26.4.0          py311h7deb3e3_0    conda-forge
readline                  8.2                  h8c095d6_2    conda-forge
roboforge                 1.0.0                    pypi_0    pypi
ruff                      0.11.8                   pypi_0    pypi
scipy                     1.13.1                   pypi_0    pypi
setuptools                80.1.0             pyhff2d567_0    conda-forge
six                       1.17.0             pyhd8ed1ab_0    conda-forge
stack_data                0.6.3              pyhd8ed1ab_1    conda-forge
tbb                       2022.1.0             h4ce085d_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tornado                   6.4.2           py311h9ecbd09_0    conda-forge
tqdm                      4.67.1             pyhd8ed1ab_1    conda-forge
traitlets                 5.14.3             pyhd8ed1ab_1    conda-forge
trimesh                   4.6.8                    pypi_0    pypi
typing_extensions         4.13.2             pyh29332c3_0    conda-forge
tzdata                    2025b                h78e105d_0    conda-forge
virtualenv                20.31.0                  pypi_0    pypi
wadler-lindig             0.1.5                    pypi_0    pypi
wcwidth                   0.2.13             pyhd8ed1ab_1    conda-forge
wheel                     0.45.1             pyhd8ed1ab_1    conda-forge
xz                        5.8.1                hbcc6ac9_0    conda-forge
xz-gpl-tools              5.8.1                hbcc6ac9_0    conda-forge
xz-tools                  5.8.1                hb9d3cd8_0    conda-forge
zeromq                    4.3.5                h3b0a872_7    conda-forge
zipp                      3.21.0             pyhd8ed1ab_1    conda-forge
zlib                      1.3.1                hb9d3cd8_2    conda-forge
zstd                      1.5.7                hb8e6e7a_2    conda-forge`

**Comment by robagar** [comment]
Minimal repro case  - https://github.com/robagar/jax_cholesky_internal_error

**Comment by cooijmanstim** [comment]
I was able to get around this by downgrading to `nvidia-cublas-cu12==12.9.0.13` as suggested in https://github.com/jax-ml/jax/issues/29042#issuecomment-2916978884.

**Comment by hawkinsp** [comment]
Closing as likely stale.
