### ISSUE TITLE
Cannot build jax of main branch on Windows.

### ISSUE THREAD

**Issue by mingyr** [google/jax#9086]
Dear Jax developers:

When I tried to build Jax of the main branch on Windows, I think I have followed the exact instructions in preparing the environment to build. But I still got the following error: Anyone has any clue? Thanks a lot:
```
PS D:\Projects\jax> python .\build\build.py `
>>   --enable_cuda `
>>   --cuda_path='C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1' `
>>   --cudnn_path='C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1' `
>>   --cuda_compute_capabilities='6.1' `
>>   --cuda_version='10.1' `
>>   --cudnn_version='7.6.5'

     _   _  __  __
    | | / \ \ \/ /
 _  | |/ _ \ \  /
| |_| / ___ \/  \
 \___/_/   \/_/\_\


$TEST_TMPDIR defined: output root default is 'c:\build' and max_idle_secs default is '15'.
[bazel FATAL src/main/cpp/blaze.cc:1330] Unknown startup option: '--version'.
  For more info, run 'bazel help startup_options'.
b''
$TEST_TMPDIR defined: output root default is 'c:\build' and max_idle_secs default is '15'.
Bazel binary path: .\bazel-4.2.1-windows-x86_64.exe
Bazel version: 4.2.1
Python binary path: C:/Program Files/Python37/python.exe
Python version: 3.7
NumPy version: 1.21.5
MKL-DNN enabled: yes
Target CPU: AMD64
Target CPU features: release
CUDA enabled: yes
CUDA toolkit path: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1
CUDNN library path: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1
CUDA compute capabilities: 6.1
CUDA version: 10.1
CUDNN version: 7.6.5
NCCL enabled: yes
TPU enabled: no
ROCm enabled: no

Building XLA and installing it in the jaxlib source tree...
.\bazel-4.2.1-windows-x86_64.exe run --verbose_failures=true --config=mkl_open_source_only --config=cuda :build_wheel -- --output_path=D:\Projects\jax\dist --cpu=AMD64
$TEST_TMPDIR defined: output root default is 'c:\build' and max_idle_secs default is '15'.
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
INFO: Reading rc options for 'run' from d:\projects\jax\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  Inherited 'build' options: --python_path=C:/Program Files/Python37/python.exe
INFO: Reading rc options for 'run' from d:\projects\jax\.bazelrc:
  Inherited 'build' options: --apple_platform_type=macos --macos_minimum_os=10.9 --announce_rc --define open_source_build=true --spawn_strategy=standalone --enable_platform_specific_config --define=no_aws_support=true --define=no_gcp_support=true --define=no_hdfs_support=true --define=no_kafka_support=true --define=no_ignite_support=true --define=grpc_no_ares=true -c opt --config=short_logs --copt=-DMLIR_PYTHON_PACKAGE_PREFIX=jaxlib.mlir.
INFO: Reading rc options for 'run' from d:\projects\jax\.jax_configure.bazelrc:
  Inherited 'build' options: --strategy=Genrule=standalone --repo_env PYTHON_BIN_PATH=C:/Program Files/Python37/python.exe --action_env=PYENV_ROOT --python_path=C:/Program Files/Python37/python.exe --action_env CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1 --action_env CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1 --action_env TF_CUDA_PATHS=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1 --action_env TF_CUDA_VERSION=10.1 --action_env TF_CUDNN_VERSION=7.6.5 --distinct_host_configuration=false
INFO: Found applicable config definition build:short_logs in file d:\projects\jax\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:mkl_open_source_only in file d:\projects\jax\.bazelrc: --define=tensorflow_mkldnn_contraction_kernel=1
INFO: Found applicable config definition build:cuda in file d:\projects\jax\.bazelrc: --repo_env TF_NEED_CUDA=1 --action_env TF_CUDA_COMPUTE_CAPABILITIES=3.5,5.2,6.0,6.1,7.0 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda --define=xla_python_enable_gpu=true
INFO: Found applicable config definition build:cuda in file d:\projects\jax\.jax_configure.bazelrc: --action_env TF_CUDA_COMPUTE_CAPABILITIES=6.1
INFO: Found applicable config definition build:windows in file d:\projects\jax\.bazelrc: --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/Zc:preprocessor --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true
INFO: Repository local_config_cuda instantiated at:
  D:/projects/jax/WORKSPACE:31:14: in <toplevel>
  C:/build/_bazel_yrming/genbqna7/external/org_tensorflow/tensorflow/workspace2.bzl:878:19: in workspace
  C:/build/_bazel_yrming/genbqna7/external/org_tensorflow/tensorflow/workspace2.bzl:96:19: in _tf_toolchains
Repository rule cuda_configure defined at:
  C:/build/_bazel_yrming/genbqna7/external/org_tensorflow/third_party/gpus/cuda_configure.bzl:1448:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "C:/build/_bazel_yrming/genbqna7/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1401, column 38, in _cuda_autoconf_impl
                _create_local_cuda_repository(repository_ctx)
        File "C:/build/_bazel_yrming/genbqna7/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1076, column 27, in _create_local_cuda_repository
                cuda_libs = _find_libs(repository_ctx, check_cuda_libs_script, cuda_config)
        File "C:/build/_bazel_yrming/genbqna7/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 606, column 21, in _find_libs
                _check_cuda_libs(repository_ctx, check_cuda_libs_script, check_cuda_libs_params.values())
        File "C:/build/_bazel_yrming/genbqna7/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 501, column 28, in _check_cuda_libs
                checked_paths = execute(repository_ctx, [python_bin, "-c", cmd]).stdout.splitlines()
        File "C:/build/_bazel_yrming/genbqna7/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
'C:/Program' is not recognized as an internal or external command,
operable program or batch file.
ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/build/_bazel_yrming/genbqna7/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1401, column 38, in _cuda_autoconf_impl
                _create_local_cuda_repository(repository_ctx)
        File "C:/build/_bazel_yrming/genbqna7/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1076, column 27, in _create_local_cuda_repository
                cuda_libs = _find_libs(repository_ctx, check_cuda_libs_script, cuda_config)
        File "C:/build/_bazel_yrming/genbqna7/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 606, column 21, in _find_libs
                _check_cuda_libs(repository_ctx, check_cuda_libs_script, check_cuda_libs_params.values())
        File "C:/build/_bazel_yrming/genbqna7/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 501, column 28, in _check_cuda_libs
                checked_paths = execute(repository_ctx, [python_bin, "-c", cmd]).stdout.splitlines()
        File "C:/build/_bazel_yrming/genbqna7/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
'C:/Program' is not recognized as an internal or external command,
operable program or batch file.
INFO: Found applicable config definition build:cuda in file d:\projects\jax\.bazelrc: --repo_env TF_NEED_CUDA=1 --action_env TF_CUDA_COMPUTE_CAPABILITIES=3.5,5.2,6.0,6.1,7.0 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda --define=xla_python_enable_gpu=true
ERROR: @local_config_cuda//:enable_cuda :: Error loading option @local_config_cuda//:enable_cuda: Repository command failed
'C:/Program' is not recognized as an internal or external command,
operable program or batch file.

b''
Traceback (most recent call last):
  File ".\build\build.py", line 524, in <module>
    main()
  File ".\build\build.py", line 519, in main
    shell(command)
  File ".\build\build.py", line 53, in shell
    output = subprocess.check_output(cmd)
  File "C:\Program Files\Python37\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Program Files\Python37\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['.\\bazel-4.2.1-windows-x86_64.exe', 'run', '--verbose_failures=true', '--config=mkl_open_source_only', '--config=cuda', ':build_wheel', '--', '--output_path=D:\\Projects\\jax\\dist', '--cpu=AMD64']' returned non-zero exit status 2.
PS D:\Projects\jax>
```
I am very appreciating anyone could give any clue. 
I would be very pleased to provide any further information on request.

**Comment by mingyr** [comment]
I just figured out the cause of the problem, should be related to the path of python executable.

I created a python virtual environment and inside the activated env walked around the problem.

Seems powershell has some problem in activating the virtual environment, so I just used the terminal, where double quotes should be around the parameters with space inside.
