### ISSUE TITLE
Cannot do "nan_to_num" in customized JVP functions

### ISSUE THREAD

**Issue by connection-on-fiber-bundles** [google/jax#9087]
We were trying to remove NAN in a customized JVP function but hit some issues. Please see below for a (overly) simplified example. Not sure if it's a feature or bug. If the behavior is as expected, please help provide some guidance on how to remove or mask out NAN (as well as INF) values in a customized JVP function. Thanks!

Jax version: 0.2.26
Jaxlib version: 0.1.75

```python
import jax
import jax.numpy as jnp

@jax.custom_jvp
def func(x):
    return jnp.sum(x)

@func.defjvp
def func_jvp(primals, tangents):
    tangent, = tangents
    tangent = jnp.nan_to_num(tangent)
    return func(*primals), func(tangent)

val_and_grad = jax.value_and_grad(func)

val_and_grad(jnp.ones(3))
```

Stack trace:
```
Traceback (most recent call last):
  File "bin/reproduce_simple_case.py", line 16, in <module>
    val_and_grad(jnp.ones(3))
  File "bin/reproduce_simple_case.py", line 11, in func_jvp
    tangent = jnp.nan_to_num(tangent)
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 2455, in nan_to_num
    x = where(isneginf(x), array(neginf, dtype=x.dtype), x)
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 2170, in where
    return _where(condition, x, y)
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 2149, in _where
    return lax.select(condition, x, y) if not core.is_empty_shape(np.shape(x)) else x
jax._src.source_info_util.JaxStackTraceBeforeTransformation: AssertionError

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bin/reproduce_simple_case.py", line 16, in <module>
    val_and_grad(jnp.ones(3))
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/_src/api.py", line 1064, in value_and_grad_f
    g = vjp_py(jax.lax._one(ans))
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/_src/tree_util.py", line 326, in <lambda>
    func = lambda *args, **kw: original_func(*args, **kw)
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/_src/api.py", line 2373, in _vjp_pullback_wrapper
    ans = fun(*args)
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/_src/tree_util.py", line 326, in <lambda>
    func = lambda *args, **kw: original_func(*args, **kw)
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/interpreters/ad.py", line 123, in unbound_vjp
    arg_cts = backward_pass(jaxpr, reduce_axes, consts, dummy_args, cts)
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/interpreters/ad.py", line 223, in backward_pass
    params, call_jaxpr, invals, cts_in, cts_in_avals, reduce_axes)
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/interpreters/ad.py", line 558, in call_transpose
    out_flat = primitive.bind(fun, *all_args, **new_params)
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/core.py", line 1661, in bind
    return call_bind(self, fun, *args, **params)
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/core.py", line 1652, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/core.py", line 1664, in process
    return trace.process_call(self, fun, tracers, params)
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/core.py", line 633, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/_src/dispatch.py", line 129, in _xla_call_impl
    *unsafe_map(arg_spec, args))
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/linear_util.py", line 263, in memoized_fun
    ans = call(fun, *args)
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/_src/dispatch.py", line 156, in _xla_callable_uncached
    *arg_specs).compile().unsafe_call
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/_src/dispatch.py", line 170, in lower_xla_callable
    fun, abstract_args, pe.debug_info_final(fun, "jit"))
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 1566, in trace_to_jaxpr_final
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, main, in_avals)
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 1543, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers)
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/interpreters/ad.py", line 223, in backward_pass
    params, call_jaxpr, invals, cts_in, cts_in_avals, reduce_axes)
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/interpreters/ad.py", line 558, in call_transpose
    out_flat = primitive.bind(fun, *all_args, **new_params)
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/core.py", line 1661, in bind
    return call_bind(self, fun, *args, **params)
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/core.py", line 1652, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/core.py", line 1664, in process
    return trace.process_call(self, fun, tracers, params)
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 1352, in process_call
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(f, self.main, in_avals)
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 1543, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers)
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/interpreters/ad.py", line 229, in backward_pass
    **eqn.params)
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/_src/lax/lax.py", line 3104, in _select_transpose_rule
    assert not ad.is_undefined_primal(pred)
jax._src.traceback_util.UnfilteredStackTrace: AssertionError

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bin/reproduce_simple_case.py", line 16, in <module>
    val_and_grad(jnp.ones(3))
  File "/home/tiger/.local/lib/python3.7/site-packages/jax/_src/lax/lax.py", line 3104, in _select_transpose_rule
    assert not ad.is_undefined_primal(pred)
AssertionError
```

**Comment by connection-on-fiber-bundles** [comment]
Sorry, some further investigation shows that it's ok to use `nan_to_num` in customized JVP functions. It's that we cannot use the `tangents` (the second argument of the customized JVP function) in `nan_to_num`. Even more general, `tangents` cannot show up in the condition part in the `jnp.where` functions.

**Comment by connection-on-fiber-bundles** [comment]
Just realized doing `nan_to_num` on `tangents` may break the linearity required for doing transpose automatically (hinted by the function raising the exception, namely `_select_transpose_rule`). Not sure if it's the source of the issue though. 

Let's say we are writing the customized JVP function for the loss function of our model, which would only be used in back-propagation. Does that mean we could write a customized VJP function, instead of JVP, to be used in BP, and we don't need to worry about the linearity and can do `nan_to_num` in customized VJP function in that case?

**Comment by mattjj** [comment]
Thanks for the questions! You pretty much nailed it.

Indeed it seems JAX considers `nan_to_num` to be nonlinear (because of the `where` as you say), and so using it on tangents makes the result non-transposable. (This is a pretty confusing error message though...)

And yes, if you write a custom VJP then you're telling JAX how to perform the transposition, so automatic transposition is no longer necessary and this issue won't come up.

Does using a custom VJP make sense for your use case?

**Comment by connection-on-fiber-bundles** [comment]
@mattjj Thanks for your response and sorry for getting back so late. Yes, I implemented a custom VJP and it worked. I will close the issue here
