### ISSUE TITLE
jax.lax.reduce with vmapped initial values

### ISSUE THREAD

**Issue by alexanderb14** [google/jax#9266]
Hi,

I want to perform a vectorized reduction with different initial values and an own, user-defined reduction function.
jax.lax.reduce generally does what I intend to do - however it only allows one initial value for all parallel vmapped computations.

The example code below shows what I intend to do. The error tells me that providing different initial values is not supported currently.

What would it take to add this functionality?

Best Regards,
Alex

Code:
```python
import jax
import jax.numpy as jnp

arr = jnp.broadcast_to(jnp.arange(10), [5, 10])

def reduce_fn(a, b):
    return a + b

def map_fn(ar):
    initial = ar[0]
    remaining = ar[1:]
    return jax.lax.reduce(remaining, initial, reduce_fn, [0])

map_v = jax.vmap(map_fn)
print(map_v(arr))
```

Error:
```
/xyz/bin/python /home/alex/.config/JetBrains/CLion2020.1/scratches/scratch_1.py
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Traceback (most recent call last):
  File "/home/alex/.config/JetBrains/CLion2020.1/scratches/scratch_1.py", line 15, in <module>
    print(map_v(arr))
  File "/xyz/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 143, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/xyz/lib/python3.8/site-packages/jax/_src/api.py", line 1299, in batched_fun
    out_flat = batching.batch(
  File "/xyz/lib/python3.8/site-packages/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/alex/.config/JetBrains/CLion2020.1/scratches/scratch_1.py", line 12, in map_fn
    return jax.lax.reduce(remaining, initial, reduce_fn, [0])
  File "/xyz/lib/python3.8/site-packages/jax/_src/lax/lax.py", line 1257, in reduce
    out = reduce_p.bind(*(flat_operands + flat_init_values), computation=computation,
  File "/xyz/lib/python3.8/site-packages/jax/core.py", line 264, in bind
    out = top_trace.process_primitive(self, tracers, params)
  File "/xyz/lib/python3.8/site-packages/jax/interpreters/batching.py", line 134, in process_primitive
    val_out, dim_out = batched_primitive(vals_in, dims_in, **params)
  File "/xyz/lib/python3.8/site-packages/jax/_src/lax/lax.py", line 5157, in _reduce_batch_rule
    raise NotImplementedError  # loop and stack
jax._src.traceback_util.UnfilteredStackTrace: NotImplementedError

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alex/.config/JetBrains/CLion2020.1/scratches/scratch_1.py", line 15, in <module>
    print(map_v(arr))
  File "/xyz/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 171, in reraise_with_filtered_traceback
    raise e.with_traceback(filtered_tb)
  File "/home/alex/.config/JetBrains/CLion2020.1/scratches/scratch_1.py", line 12, in map_fn
    return jax.lax.reduce(remaining, initial, reduce_fn, [0])
NotImplementedError

Process finished with exit code 1
```

**Comment by hawkinsp** [comment]
Before we dive into "how do we implement this", I just want to check that it does what you want.

Are your initial values identities for the reducer function? i.e., you have a reducer function with many different identity values?

The contract of XLA's `reduce` is that XLA may freely add as many copies of the identity (initial) value as it wants.

**Comment by alexanderb14** [comment]
Thanks for your comment! Yes, I am aware of that.
I would like to do is reduces with multiple different initial values and they are the identity to the operation - Yes.

**Comment by soraros** [comment]
In that case, can't you just choose one such initial value, as they are by definition equivalent?

**Comment by alexanderb14** [comment]
True, thanks for the hint! I wanted the start element of the sequences as the identity element initially, which is not correct as I just realized. The identity element is specific to the operation and there is only one operation
