### ISSUE TITLE
RBG-based PRNG doesn't work with bf16

### ISSUE THREAD

**Issue by zhangqiaorjc** [google/jax#9274]
bf16 is the norm for TPU training, and RBG-based PRNG is useful to speed up random number generation for large models. It seems that our RBG-based PRNG doesn't yet support bf16. Would be nice to enable this.

See repro

```python
import jax
import jax.numpy as jnp
 
print('-- default software PRNG')
print(jax.random.uniform(jax.random.PRNGKey(1), (2, 2), jnp.bfloat16))
 
print('-- RBG-based PRNG')
 
from jax import prng
jax.config.update('jax_enable_custom_prng', True)
 
def rbg_key(seed: int):
  return prng.seed_with_impl(prng.rbg_prng_impl, seed)
 
jax.random.PRNGKey = rbg_key

print(jax.random.uniform(jax.random.PRNGKey(1), (2, 2), jnp.bfloat16))
```

Default PRNG works
```
-- default software PRNG
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
[[0.53125 0.453125]
 [0.5 0.984375]]
```

RBG-based says unsupported

```
-- RBG-based PRNG
Traceback (most recent call last):
  File "/usr/local/google/home/zhangqiaorjc/Downloads/t.py", line 16, in <module>
    print(jax.random.uniform(jax.random.PRNGKey(1), (2, 2), jnp.bfloat16))
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/_src/random.py", line 239, in uniform
    return _uniform(key, shape, dtype, minval, maxval)  # type: ignore
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/_src/random.py", line 258, in _uniform
    bits = _random_bits(key, nbits, shape)
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/_src/random.py", line 88, in _random_bits
    return key._random_bits(bit_width, shape)
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/_src/prng.py", line 184, in _random_bits
    return self.impl.random_bits(self._keys, bit_width, shape)
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/_src/prng.py", line 540, in _rbg_random_bits
    _, bits = lax.rng_bit_generator(key, shape, dtype=UINT_DTYPES[bit_width])
jax._src.source_info_util.JaxStackTraceBeforeTransformation: RuntimeError: INVALID_ARGUMENT: Unsupported shape for RngBitGenerator: U16

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/google/home/zhangqiaorjc/Downloads/t.py", line 16, in <module>
    print(jax.random.uniform(jax.random.PRNGKey(1), (2, 2), jnp.bfloat16))
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/_src/random.py", line 239, in uniform
    return _uniform(key, shape, dtype, minval, maxval)  # type: ignore
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/_src/traceback_util.py", line 165, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/_src/api.py", line 429, in cache_miss
    donated_invars=donated_invars, inline=inline)
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/core.py", line 1671, in bind
    return call_bind(self, fun, *args, **params)
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/core.py", line 1683, in call_bind
    outs = top_trace.process_call(primitive, fun, tracers, params)
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/core.py", line 596, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/_src/dispatch.py", line 143, in _xla_call_impl
    *unsafe_map(arg_spec, args))
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/linear_util.py", line 272, in memoized_fun
    ans = call(fun, *args)
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/_src/dispatch.py", line 170, in _xla_callable_uncached
    *arg_specs).compile().unsafe_call
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/_src/dispatch.py", line 265, in lower_xla_callable
    arg_partitions=None, out_partitions=None)
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/interpreters/xla.py", line 772, in lower_jaxpr_to_xla_module
    out_nodes = jaxpr_subcomp(ctx, jaxpr.jaxpr, xla_consts, *xla_args)
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/interpreters/xla.py", line 600, in jaxpr_subcomp
    *in_nodes, **eqn.params)
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/_src/lax/lax.py", line 4160, in _rng_bit_generator_translation_rule
    c, xops.RngBitGenerator(algorithm, key, xla_shape))
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/interpreters/xla.py", line 611, in xla_destructure
    num_elements = len(c.get_shape(ans).tuple_shapes())
jax._src.traceback_util.UnfilteredStackTrace: RuntimeError: INVALID_ARGUMENT: Unsupported shape for RngBitGenerator: U16

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/google/home/zhangqiaorjc/Downloads/t.py", line 16, in <module>
    print(jax.random.uniform(jax.random.PRNGKey(1), (2, 2), jnp.bfloat16))
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/_src/random.py", line 239, in uniform
    return _uniform(key, shape, dtype, minval, maxval)  # type: ignore
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/interpreters/xla.py", line 611, in xla_destructure
    num_elements = len(c.get_shape(ans).tuple_shapes())
RuntimeError: INVALID_ARGUMENT: Unsupported shape for RngBitGenerator: U16```

**Comment by froystig** [comment]
For anyone who might pull up this issue, there's a simpler and better way to spell out the example in the OP for the time being:

```python
import jax
import jax.numpy as jnp

print(jax.random.uniform(jax.random.PRNGKey(1), (2, 2), jnp.bfloat16))

with jax.default_prng_impl('rbg'):
  print(jax.random.uniform(jax.random.PRNGKey(1), (2, 2), jnp.bfloat16))

with jax.default_prng_impl('unsafe_rbg'):
  print(jax.random.uniform(jax.random.PRNGKey(1), (2, 2), jnp.bfloat16))
```

And soon enough (after #9263), we'll have a means of seeding explicitly for each RNG implementation, so a process-wide config setting (with the corresponding dynamic scope helper above) won't be needed either.
