### ISSUE TITLE
Provide wheels for Rosetta (macOS, non-avx)

### ISSUE THREAD

**Issue by trologat** [google/jax#9580]
While JAX provides native ARM support for M1 other libraries are not yet there and have to be run under Rosetta. x86 wheels don't work on M1 because Rosetta doesn't emulate AVX. Would it be possible to provide non-AVX x86 wheels for this use case?

**Comment by hawkinsp** [comment]
We could. You can build jaxlib from source without AVX enabled easily enough following the usual instructions.

I'm a bit reluctant to do this because AVX is a CPU feature that was released 8 years ago, and at some point we just want to assume a minimum level of vectorization support. AVX, and fused multiply-add (FMA) which arrived at the same time (Intel Haswell) are pretty important for machine learning workloads.

Can you say more about which other packages you're blocked on? How long would we need to support the non-AVX wheels? I'm trying to gauge how popular this request is likely to be; if it's a niche thing, then I'd suggest just building your own wheels.

**Comment by trologat** [comment]
I fully agree that AVX and FMA should be assumed as a minimum. Unfortunately, we still have some old legacy code in tensorflow 1.x that will probably stay around for a year or so. There are also other packages like https://web.casadi.org and probably some others but tensorflow is the main blocker :(

Yes, I guess that makes sense 👍  If there is no further interest I'll build my own wheels.

**Comment by amir-f** [comment]
I'm new to Jax, have a MacOS ARM and the initial setup wasn't that smooth.

```
pip install -U pip
pip install jax
pip install jaxlib
```

And then I get
```
>>> import jax
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/amir.fayazi/monorepo/.venv/lib/python3.8/site-packages/jax/__init__.py", line 35, in <module>
    from jax import config as _config_module
  File "/Users/amir.fayazi/monorepo/.venv/lib/python3.8/site-packages/jax/config.py", line 17, in <module>
    from jax._src.config import config  # noqa: F401
  File "/Users/amir.fayazi/monorepo/.venv/lib/python3.8/site-packages/jax/_src/config.py", line 28, in <module>
    from jax._src import lib
  File "/Users/amir.fayazi/monorepo/.venv/lib/python3.8/site-packages/jax/_src/lib/__init__.py", line 85, in <module>
    cpu_feature_guard.check_cpu_features()
RuntimeError: This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support. You may be able work around this issue by building jaxlib from source.
```

I [thought](https://github.com/google/jax/issues/9065) the support was there. Is the recommendation to build from source? I want to run it locally on the laptop for initial prototyping.

**Comment by hawkinsp** [comment]
Closing since we don't even ship mac x86 wheels any more.
