### ISSUE TITLE
jnp.load() crashes if save file contains object that is not array

### ISSUE THREAD

**Issue by oscarkey** [google/jax#9700]
Minimum repro:
```python
import jax.numpy as jnp

class TestClass:
    pass

jnp.save("object.npy", TestClass())
print(jnp.load("object.npy", allow_pickle=True))
```

Output:
```
Traceback (most recent call last):
  File ".../lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 3632, in array
    dtype = dtypes._lattice_result_type(*leaves)[0] if leaves else dtypes.float_
  File ".../lib/python3.9/site-packages/jax/_src/dtypes.py", line 362, in _lattice_result_type
    dtypes, weak_types = zip(*(_dtype_and_weaktype(arg) for arg in args))
  File ".../lib/python3.9/site-packages/jax/_src/dtypes.py", line 362, in <genexpr>
    dtypes, weak_types = zip(*(_dtype_and_weaktype(arg) for arg in args))
  File ".../lib/python3.9/site-packages/jax/_src/dtypes.py", line 251, in _dtype_and_weaktype
    return dtype(value), any(value is typ for typ in _weak_types) or is_weakly_typed(value)
  File ".../lib/python3.9/site-packages/jax/_src/dtypes.py", line 357, in dtype
    raise TypeError(f"Value '{x}' with dtype {dt} is not a valid JAX array "
TypeError: Value '<__main__.TestClass object at 0x7f8528b71160>' with dtype object is not a valid JAX array type. Only arrays of numeric types are supported by JAX.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "repro.py", line 9, in <module>
    print(jnp.load("object.npy", allow_pickle=True))
  File ".../lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 652, in load
    out = asarray(out)
  File ".../lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 3693, in asarray
    return array(a, dtype=dtype, copy=False, order=order)
  File ".../lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 3637, in array
    dtype = dtypes._lattice_result_type(*leaves)[0]
  File ".../lib/python3.9/site-packages/jax/_src/dtypes.py", line 362, in _lattice_result_type
    dtypes, weak_types = zip(*(_dtype_and_weaktype(arg) for arg in args))
  File ".../lib/python3.9/site-packages/jax/_src/dtypes.py", line 362, in <genexpr>
    dtypes, weak_types = zip(*(_dtype_and_weaktype(arg) for arg in args))
  File ".../lib/python3.9/site-packages/jax/_src/dtypes.py", line 251, in _dtype_and_weaktype
    return dtype(value), any(value is typ for typ in _weak_types) or is_weakly_typed(value)
  File ".../lib/python3.9/site-packages/jax/_src/dtypes.py", line 357, in dtype
    raise TypeError(f"Value '{x}' with dtype {dt} is not a valid JAX array "
TypeError: Value '<__main__.TestClass object at 0x7f8528b71160>' with dtype object is not a valid JAX array type. Only arrays of numeric types are supported by JAX.
```

jax: 0.3.1
jaxlib: 0.3.0
numpy: 1.21.2
Python: 3.9.7

Maybe I am doing something wrong, but in previous jax versions (e.g. jax-0.2.25) this used to work. `jnp.load` would return an array containing a single element, the Python object, which is what the numpy version does.

Potentially this commit is what changed the behaviour? 1137aa1

Let me know if you need any more information!

**Comment by jakevdp** [comment]
Thanks for the report. Yes, that commit is probably what changed things.

If you want to recover the previous behavior, you can use `np.load` (`jnp.load` previously was a simple alias to that)

In the meantime, I'll work on a fix to the bug!

**Comment by oscarkey** [comment]
Thanks for looking into this! The workaround you suggest works perfectly.
