### ISSUE TITLE
bug with jit, custom_vjp and reduce_window 

### ISSUE THREAD

**Issue by mariogeiger** [google/jax#9961]
I have `jaxlib==0.3.2` and `jax=0.3.3` and the following code crash on my CPU (might also crash on other devices)

```python
import jax
import jax.numpy as jnp
import math
from jax import lax


def _index_max_norm(input, strides):
    norms = jnp.sum(input**2, axis=-1)
    shape = input.shape[:-1]
    assert len(shape) == len(strides)
    idxs = jnp.arange(math.prod(shape)).reshape(shape)

    def g(a, b):
        an, ai = a
        bn, bi = b
        which = an >= bn
        return (jnp.where(which, an, bn), jnp.where(which, ai, bi))

    _, idxs = lax.reduce_window(
        (norms, idxs),
        (-jnp.inf, -1),
        g,
        window_dimensions=strides,
        window_strides=strides,
        padding=((0, 0),) * len(strides),
    )
    return idxs


@jax.custom_vjp
def norm_maxpool(input, strides):
    idxs = _index_max_norm(input, strides)
    return input.reshape(math.prod(input.shape[:-1]), input.shape[-1])[idxs]


def norm_maxpool_fwd(input, strides):
    idxs = _index_max_norm(input, strides)
    output = input.reshape(math.prod(input.shape[:-1]), input.shape[-1])[idxs]
    return output, (idxs, input.shape)


def norm_maxpool_bwd(residuals, grad):
    idxs, shape = residuals
    idxs = idxs.flatten()
    grad = jnp.zeros((math.prod(shape[:-1]),) + (grad.shape[-1],)).at[idxs].add(grad.reshape(idxs.shape[0], -1))
    grad = grad.reshape(shape)
    return (grad, None)


norm_maxpool.defvjp(norm_maxpool_fwd, norm_maxpool_bwd)

x = jnp.array([
    [[1.0, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]],
    [[9, 10], [1, 12]],
])

jax.jit(lambda x: norm_maxpool(x, (2, 2)))(x)
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
    [... skipping hidden 1 frame]

~/base/lib/python3.9/site-packages/jax/core.py in canonicalize_shape(shape, context)
   1594     pass
-> 1595   raise _invalid_shape_error(shape, context)
   1596 

TypeError: Shapes must be 1D sequences of concrete values of integer type, got [Traced<ShapedArray(int32[], weak_type=True)>with<DynamicJaxprTrace(level=0/2)>
 Traced<ShapedArray(int32[], weak_type=True)>with<DynamicJaxprTrace(level=0/2)>].
If using `jit`, try using `static_argnums` or applying `jit` to smaller subfunctions.

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_158588/13487716.py in <module>
     57 ])
     58 
---> 59 jax.jit(lambda x: norm_maxpool(x, (2, 2)))(x)

    [... skipping hidden 14 frame]

/tmp/ipykernel_158588/13487716.py in <lambda>(x)
     57 ])
     58 
---> 59 jax.jit(lambda x: norm_maxpool(x, (2, 2)))(x)

    [... skipping hidden 6 frame]

/tmp/ipykernel_158588/13487716.py in norm_maxpool(input, strides)
     30 @jax.custom_vjp
     31 def norm_maxpool(input, strides):
---> 32     idxs = _index_max_norm(input, strides)
     33     return input.reshape(math.prod(input.shape[:-1]), input.shape[-1])[idxs]
     34 

/tmp/ipykernel_158588/13487716.py in _index_max_norm(input, strides)
     17         return (jnp.where(which, an, bn), jnp.where(which, ai, bi))
     18 
---> 19     _, idxs = lax.reduce_window(
     20         (norms, idxs),
     21         (-jnp.inf, -1),

    [... skipping hidden 7 frame]

~/base/lib/python3.9/site-packages/jax/_src/lax/lax.py in _check_shapelike(fun_name, arg_name, obj, non_zero_shape)
   4554   except TypeError as err:
   4555     msg = "{} {} must have every element be an integer type, got {}."
-> 4556     raise TypeError(msg.format(fun_name, arg_name, tuple(map(type, obj)))) from err
   4557   lower_bound, bound_error = (
   4558       (1, "strictly positive") if non_zero_shape else (0, "nonnegative"))

TypeError: reduce_window window_dimensions must have every element be an integer type, got (<class 'jax.interpreters.partial_eval.DynamicJaxprTracer'>, <class 'jax.interpreters.partial_eval.DynamicJaxprTracer'>).
```

Surprisingly, if I do one of the following it works:
- remove `jit`
- remove `custom_vjp`
- add `grad`

**Comment by mariogeiger** [comment]
Might be related to https://github.com/google/jax/discussions/9818#discussioncomment-2328818 but not sure

**Comment by YouJiacheng** [comment]
On `jaxlib==0.3.2` and `jax==0.3.4` and GPU, I encounter a different error:
```
File "/home/jiacheng/playground/play.py", line 19, in _index_max_norm
    _, idxs = lax.reduce_window(
  File "/home/jiacheng/conda/envs/playground/lib/python3.10/site-packages/jax/_src/lax/windowed_reductions.py", line 94, in reduce_window
    out_flat = reduce_window_p.bind(
  File "/home/jiacheng/conda/envs/playground/lib/python3.10/site-packages/jax/core.py", line 286, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/home/jiacheng/conda/envs/playground/lib/python3.10/site-packages/jax/core.py", line 289, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/jiacheng/conda/envs/playground/lib/python3.10/site-packages/jax/interpreters/partial_eval.py", line 1485, in process_primitive
    return self.default_process_primitive(primitive, tracers, params)
  File "/home/jiacheng/conda/envs/playground/lib/python3.10/site-packages/jax/interpreters/partial_eval.py", line 1489, in default_process_primitive
    out_avals = primitive.abstract_eval(*avals, **params)
  File "/home/jiacheng/conda/envs/playground/lib/python3.10/site-packages/jax/_src/lax/windowed_reductions.py", line 259, in _reduce_window_abstract_eval_rule
    out_shape = _common_reduce_window_shape_rule(
  File "/home/jiacheng/conda/envs/playground/lib/python3.10/site-packages/jax/_src/lax/windowed_reductions.py", line 425, in _common_reduce_window_shape_rule
    lax._check_shapelike("reduce_window", "window_dimensions", window_dimensions,
  File "/home/jiacheng/conda/envs/playground/lib/python3.10/site-packages/jax/_src/lax/lax.py", line 4577, in _check_shapelike
    obj_arr = np.array(obj)
  File "/home/jiacheng/conda/envs/playground/lib/python3.10/site-packages/jax/core.py", line 470, in __array__
    raise TracerArrayConversionError(self)
  File "/home/jiacheng/conda/envs/playground/lib/python3.10/site-packages/jax/_src/errors.py", line 322, in __init__
    f"the JAX Tracer object {tracer}{tracer._origin_msg()}")
  File "/home/jiacheng/conda/envs/playground/lib/python3.10/site-packages/jax/interpreters/partial_eval.py", line 1258, in _origin_msg
    f"of {dbg.arg_info(invar_pos)}.")
  File "/home/jiacheng/conda/envs/playground/lib/python3.10/site-packages/jax/interpreters/partial_eval.py", line 1703, in arg_info_pytree
    for i in flat_pos: dummy_args[i] = True
jax._src.traceback_util.UnfilteredStackTrace: IndexError: list assignment index out of range
```
